### ISSUE TITLE
26号更新后,圆圈的颜色不会变了是固定的

### ISSUE THREAD

**Issue by adsl95** [FelisCatus/SwitchyOmega#1001]
26号这个版本在chrome 42.0.2311.152这个版本用
不管怎么切换规则圆圈颜色都不会变了
希望可以修正
之前的一直没问题,chrome在26号自动更新插件后就这样了.......
现在内圈白色,外圈蓝色不会变了
之前我自己设定的不是这个颜色,虽然手动切换和自动切换都是正常的,但颜色就是打死都不变了,用着不太方便
谢谢

**Comment by celeron533** [comment]
升级到chrome56后再试试？

**Comment by myjlpt** [comment]
@celeron533 56版本改的太不适合中国国情。两个字难用。虽然可以用绿色版启动器实现，但其本身有BUG一样不好用

**Comment by adsl95** [comment]
我用旧版是为了用npapi........所以上不了新版,chrome官方的数据同步api接口不换的话我就先这么一直用着.........
41版本关闭提示每天都提示版本太旧有点烦,有点想关掉这个提示.但搜索整个网络都没人说方法.........

至于这个插件,我卸载了再装然后倒入配置正常一会,然后后台自己更新了新版插件又是只能蓝色了..........

**Comment by myjlpt** [comment]
@adsl95 方法是有的，运行后面加参数--disable-background-networking就不会有更新提示了

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。
