### ISSUE TITLE
2.4.0前几天自动更新后就不正常

### ISSUE THREAD

**Issue by mlkt** [FelisCatus/SwitchyOmega#1002]
不管设置为什么模式，重新启动浏览器后都会变成“系统代理”

还有我也遇到了这个问题→https://github.com/FelisCatus/SwitchyOmega/issues/1001

**Comment by Arthur2012** [comment]
我也遇到相同问题，SwitchyOmega无法切换代理，另外鼠标悬停提示一直为“正在加载......”。
浏览器为360浏览器8.1.1.248，Chrome内核模式，内核版本45.0.2454.101。
把background文件和\js\background.js文件替换为SwitchyOmega 2.3.21版的文件后暂时解决问题。

**Comment by myjlpt** [comment]
@Arthur2012 ;也不麻烦，改两文件信息，昨天我实在忍受不了了，2.4其实还有个BUG，就是，长时间不用代理卡网一会会（比如XX-NET，暂时屏蔽后，就不会，退回上一版本也不会），因此退回了。
manifest.json,这个文件最后面的版本信息；
Preferences;这个文件中的版本号；改完收工;
现在本人版本，2.5.55；等待更新，手动升级去。

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。
