### ISSUE TITLE
关于2.4.0图标不变化

### ISSUE THREAD

**Issue by myjlpt** [FelisCatus/SwitchyOmega#1005]
图标状态永远是蓝色圈圈,之前版本是可以正常变化的.这样的结果是用了代理，可能还不知道已经处于的状态.

SwitchyOmega 2.4.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。
