### ISSUE TITLE
【分享】关于回退后不让其自动升级的方法

### ISSUE THREAD

**Issue by myjlpt** [FelisCatus/SwitchyOmega#1006]
修改两个文件插件目录下的manifest.json ，及最上层目录中的Preferences相应信息
传几张外联图按顺序修改就好
http://i1.piimg.com/1949/0dcecf35d6137dc8s.jpg
http://i1.piimg.com/1949/4f6fccf136f9da76.jpg
http://i1.piimg.com/1949/abb6a7d88c4d0283.jpg
http://i1.piimg.com/1949/e094ac1cbeed51f8.jpg

**Comment by Arthur2012** [comment]
@myjlpt good!
话说你的2.5.55是哪儿来的？github上的是2.3.21，google chrome应用商店上的是2.4.0。

**Comment by celeron533** [comment]
@Arthur2012 , 应该是故意在本地写了个高版本，这样就不会自动升级

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。无须强行回退。
