### ISSUE TITLE
建议在"界面"或者“通用”的选项页里加上版本显示和“反馈问题”

### ISSUE THREAD

**Issue by mlkt** [FelisCatus/SwitchyOmega#1008]
看不到当前版本号不太方便，而且360对插件点右键是显示不出额外菜单的，不能反馈问题了

**Comment by zxysm** [comment]
对的，所以我才来github反馈问题。

**Comment by FelisCatus** [comment]
360 又折腾……不开心……

顺便说下，把反馈问题做在右键菜单上的原因是：当代码不能正常工作的时候，左键菜单或者选项页面可能会加载不出来，只有放在那个地方比较保险。左键菜单虽然看起来也是个菜单，不过其实是一个网页来着……

增加版本显示页面的需求见 #289, 目前还没时间做。

**Comment by zxysm** [comment]
主要是360的下载管理比较好用，chrome的下载管理没那么方便，这样才用的360.提这个建议的目的是为了方便反馈问题，有的时候并不是扩展完全不能工作，或许跟之前2.40版本的问题一样，可以进入扩展管理内部操作，但是360浏览器根本就找不到反馈问题的地方，只能来github反馈，可是直接过来这边反馈又会缺少一些必要的信息。可以考虑在扩展内部界面增加一个反馈的链接。

**Comment by FelisCatus** [comment]
你说的我都懂，我也想另外做个关于页面然后弄个反馈功能……有时间了会试试看。

(不过个人来说，我还是觉得很不开心……真的……)

**Comment by zxysm** [comment]
哈哈，别那么在意，有的时候是需要妥协一下，知道你的出发点是好的，可你知道国内软件的尿性，我也不是那么愿意用。

**Comment by FelisCatus** [comment]
2.4.2 已经添加“关于”页面，可以在选项页面点击左上角 SwitchyOmega 字样查看。
