### ISSUE TITLE
自动切换模式问题确认

### ISSUE THREAD

**Issue by kingsonVIP** [FelisCatus/SwitchyOmega#1009]
URL：http://store.steampowered.com/
google chrome 版本 56.0.2924.87
Proxy SwitchyOmega  版本 2.4.1

例如直接使用“**1代理服务器”\“2代理服务器**”访问steam能正常加载所有信息，但在使用自动切换模式再对URL指定“**1代理服务器”\“2代理服务器**”情况下访问网站加载图片失败。
![pic](https://cloud.githubusercontent.com/assets/17898161/23454370/f4721fc8-fea6-11e6-8ca6-9f0ae274f672.png)

SwitchyOmega 2.4.1
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FelisCatus** [comment]
临时规则仅对显示的那个域名有效，对于页面中其他元素（如图片等）无效。由于 PAC 限制，无法实现选择的代理对整个标签页都有效。

建议在选项中开启检测网络请求，然后用自动切换模式访问此网页。然后，图标上会显示未加载的资源数量，弹出菜单中可以看到未能加载的资源分别来自哪些域名，并批量使用代理。
