### ISSUE TITLE
https://github.com/FelisCatus/SwitchyOmega.git

### ISSUE THREAD

**Issue by ihwwwss** [FelisCatus/SwitchyOmega#1010]

**Comment by FelisCatus** [comment]
?

**Comment by ihwwwss** [comment]
https://drive.google.com/file/d/0B1YsArCuWYX4Vy0xVER5bnVpcmM/view?usp=sharing

**Comment by ihwwwss** [comment]
#1000 #

**Comment by ihwwwss** [comment]
https://github.com/FelisCatus/SwitchyOmega.git

**Comment by FelisCatus** [comment]
This is not your personal playground. Please stop posting random links without explanation, or you will be banned from making any contribution to this project.
