### ISSUE TITLE
SwitchyOmega使用自动切换模式时切换速度有时很慢

### ISSUE THREAD

**Issue by Limsig** [FelisCatus/SwitchyOmega#1011]
使用SwitchyOmega使用自动切换模式访问被屏蔽网如谷歌时，切换速度有时很慢。可以看到SO插件的颜色要等好久才会变，所以网页就一直打不开，这时候如果我再次在地址栏回车确认一次，SO又会很快变成走代理的颜色，然后网页就开了。

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与 SwitchyOmega 无关。颜色的变化是在页面下载之后才会发生的，和切换速度无关。
