### ISSUE TITLE
有没有遇到过开启Proxy SwitchyOmega有时就卡住

### ISSUE THREAD

**Issue by maskboy02** [FelisCatus/SwitchyOmega#1014]
开启Proxy SwitchyOmega后　任务管理器里多了一个Ｖ8代理解析工具，　这个有时会占用很大内存，完全卡住，以前用chrome 39的时候从来有没有这种情况，不过我发现好像打开的网页里如果有flash它就会很卡，要过很久才好。不知道跟这个有没有关系。有没有人遇到过这种情况，有没有解决的方法。

**Comment by FelisCatus** [comment]
像是 #815， 更新 Chrome 可修复。
但如果只有 Flash 有问题的话那就只能说是 Flash 的锅了吧……
