### ISSUE TITLE
是否可以以插件形式完全管理xxnet（不手动开启）

### ISSUE THREAD

**Issue by Jan9th** [FelisCatus/SwitchyOmega#1018]
是否可以实现用SwitchyOmega在不手动开启xxnet的情况下管理xx-net fq，xxnet目前可以独立fq，SwitchyOmega插件xxnet自动切换模式下墙内墙外也都正常使用。之前看到穿越以chrome插件的形式直接fq。

**Comment by FelisCatus** [comment]
GoAgent 情景模式中，端口号是？请按照 XX-Net 的说明设置端口。

**Comment by mttgh** [comment]
@FelisCatus 导入了最新的bak，xxnet代理端口号8087

**Comment by FelisCatus** [comment]
能正常使用就好。

SwitchyOmega 是一个代理设置软件，不是翻墙软件也不是代理软件，所以不能代替代理软件。
