### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by ldfinfontainebleau** [FelisCatus/SwitchyOmega#1019]
晚上和早晨经常登不上。

SwitchyOmega 2.4.2
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by celeron533** [comment]
请描述的具体一点

- 登不上什么？
- 用的是什么代理服务器？
- 代理服务器是否工作正常？
- 你用了什么代理配置？

**Comment by FelisCatus** [comment]
这肯定是代理服务器本身的问题，和 SwitchyOmega 无关。
