### ISSUE TITLE
移植到 Firefox | Migrate to Firefox

### ISSUE THREAD

**Issue by Anaheim55** [FelisCatus/SwitchyOmega#102]
以前一直在chrome上用switchysharp，现在继续用Omega
但是firefox也经常用，可是上面的autoproxy很久不更新了（虽然看样子不更新也能一直用）
可惜foxproxy又设置起来太麻烦…没有emega autoproxy这样的轻量级，所以这里有个不情之请…希望开发组可以考虑考虑啊，开发一个firefox版的switchy Omega

SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2251.0 Safari/537.36

**Comment by hexiyou** [comment]
非常同意，个人也是Firefox重度依赖者

**Comment by FelisCatus** [comment]
2.4 预计加入 Firefox 支持，只要我在那之前没累死的话……

**Comment by Anaheim55** [comment]
大大辛苦，翘首以盼！注意休息XD

发自我的 iPhone

**Comment by VictorSnow** [comment]
一个人弄太累了，大家要加入啊  不要老是提需求什么的

**Comment by nopyhe** [comment]
期待firefox 版！

**Comment by TammyXin** [comment]
foxproxy确实麻烦，试试autoproxy？我个人觉得超级简单，比omega还简单不少。
火狐扩展中心的不能用了，修改版在这里：http://fxthunder.com/blog/archives/2866/

**Comment by Anaheim55** [comment]
用mega是为了在chrome下用啊……

发自我的 iPhone

**Comment by FelisCatus** [comment]
简单来说只是维护Chrome版，我就已经快累死了……要不这个还是推迟些吧……

**Comment by StrollStars** [comment]
似乎没有考虑开发者的感受，看看能否邀请人开发做分支。
辛苦开发者，表示感谢。

**Comment by dl825124** [comment]
感谢作者
期待FF版本

**Comment by TangBaohua** [comment]
autoproxy 不能用pac代理，而且切换代理的时候经常失效，要重启才可以切换，体验差极了。

**Comment by edge-z** [comment]
用了很多同类软件，觉得这个最好用。感谢作者。
期待firefox版本

**Comment by FelisCatus** [comment]
Firefox 正在开发中的 [WebExtensions API](https://wiki.mozilla.org/WebExtensions) 可能会有一些帮助，虽然目前而言，缺少的API/功能实在太多，不足以支持直接迁移。

目前我只能说，短期内确实没有时间来做这么大的工程了。当然， fork 或者 PR 仍然欢迎。各位也可以看一下 https://github.com/Aetf/SwitchyOmega 那边的进展（感谢 @Aetf ），算是一个不错的起点。

另外我也知道目前的文档或者说架构还有很多欠缺的地方，可能其他人难以着手迁移工作。所以，遇到任何问题都可以在这里回复或者 issue 中提出，我会尽量抽时间做一些文档、重构或者（如果实在没时间的话）做一些简单的说明。

**Comment by Aetf** [comment]
唔。。确实我在着手移植工作，然而Firefox目前API (Jetpack Add-on sdk)的理念、结构与Chrome有很大不同，实现新的target扩展的时候确实有些困难，过程中也遇到很多现有代码不好理解的地方，不过由于时间关系还没有整理出来在这边问。再加上我近期要处理开学的各种事情所以实际上现在移植工作处于停滞状态 :disappointed: 

另外，既然提到Firefox正在开发的WebExtensions API，根据Firefox[官方博客](https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/)的说法，使用Jetpack Add-on sdk 的扩展将不能使用`require('chrome')`或者类似的底层API，因此几乎不可能实现这种涉及代理的偏底层扩展。所以我也有些犹豫是否应该继续观望等WebExtensions成熟后再进行移植。

前一段时间完成的还是以正式开发前的准备工作为主，比如把Firefox扩展的构建(`jpm`)融合到了现有的构建系统中，还有我在本地对Firefox的一些API的测试等等。近期如果有时间我会把构思移植过程中遇到的比较重要的问题列出来，到时候如果 @FelisCatus 也能抽时间说明或者补全文档的话，就可以方便后来者着手移植的工作了～

**Comment by FelisCatus** [comment]
@Aetf 感谢回复。我这边最近也是忙于工作，时间比较有限，彼此都辛苦了。

目前而言要实现Firefox代理设置还是需要比较底层的 API 。 chrome 中有相应的高层`chrome.proxy`，而 WebExtensions 是否会实现这个还未可知，不过我看了[支持的API列表和限制](https://wiki.mozilla.org/WebExtensions#List_of_supported_APIs)以后，推测近期是不太可能了。此外我也注意到很多 SO 所需要的 API 都没有。所以不妨还是先从现有的 Jetpack 开始，之后观望是否有迁移的机会。

目前SO的 target 架构并不是最适合，有很多不够灵活的地方，也有很多根据 Chrome 情况而进行的假设。比如，不同 target 支持的功能显然可以有所不同，比如 Firefox 可能就没有办法由扩展提供代理用户名密码，而这些在设计时都没有很好地处理。这些我会尽可能地在之后对接的时候进行改进，到时候多沟通吧。

现在文档的覆盖面还是非常窄，有些比较重要的函数没有注释，或者一些设计决策没有体现在任何文档中，这个都是和之前的赶工有关。我还是比较期待一些来自开发者的意见和建议，相信会比我自己闭门造车好很多。所以 @Aetf 如果能提供一些想法就太好了。也希望更多人可以参与进来，这样社区也可以更繁荣一些，SO也可以向着大家想要的方向发展，包括Firefox用户在内更多人也可以用上更好的软件。

**Comment by celeron533** [comment]
@FelisCatus 这么好的插件，单单靠几位大牛是不足以支撑发展的。
PS. Shadｏｗsｏｃｋs 的IssueBoard都是用英语写的，至少是英语标题。如果有人写了中文标题，相关人员也会协助翻译成英文标题，这样对国际开发者更加友好，也更能吸引非中文圈的优秀人才加入

**Comment by FelisCatus** [comment]
@celeron533 我只能说很多 Issue 讨论我都尽量用中英文写了。某些 Issue 用的是中文标题，但我通常会修改一下内容，注明相应英文标题。
至于标题全用英文，虽然对英文圈友好了很多，但中文用户很难通过目测发现重复 issue ，各有利弊吧。目前我还是觉得减少重复更重要一些（毕竟我维护 issue tracker 真的很辛苦嘛），但之后我会好好考虑下的。

**Comment by celeron533** [comment]
@FelisCatus Or..... Do you need some help on issue management?

**Comment by madjxatw** [comment]
Firefox上的FroxyProxy不好用，极高的CPU占用率。非常希望能有FF版的SwitchyOmega.
The proxy plugin FroxyProxy for FF is not good, high CPU occupancy over 100 frequently on Linux machine. We really need SwitchyOmega for FF.

**Comment by gbtyy** [comment]
只能点点赞了

**Comment by nqzhang** [comment]
谢谢作者 同样求firefox版

**Comment by BaymaxHuang** [comment]
Firefox有个AutoProxy插件的fork版，一直在更新，支持最新的Firefox版本，结合ss很好用

**Comment by StrollStars** [comment]
Firefox48开始支持WebExtensions，也就是能够安装Chrome的扩展了。

**Comment by shishuo365** [comment]
https://github.com/agunchan/autoproxy

**Comment by shishuo365** [comment]
找到一个最新维护的AutoProxy版本，算是目前已知比较好的，先将就着用吧
https://github.com/agunchan/autoproxy

**Comment by longlene** [comment]
昨天看了下Firefox的Web Extension，其中的API里暂时没有chrome.proxy对应的API。根据看到消息，至少到Firefox 55（预计2017.11发布），Firefox才支持此API，所以在此之前，在Web Extension这块估计不会有大的进展。

**Comment by yfdyh000** [comment]
[Support proxy configuration from WebExtensions](https://bugzilla.mozilla.org/show_bug.cgi?id=1295807) 在 Firefox 55，而按[发布日程](https://wiki.mozilla.org/RapidRelease/Calendar )，Firefox 55在2017年8月正式发布。在此之前更适合研究移植，如果缺少什么参数或特性应该尽快报告到 Bugzilla 以讨论、修正或实现，不然还会拖很久。

**Comment by yfdyh000** [comment]
遇到些困难，不确定是否仍需 Mozilla 的开发。目前[定义](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ext-proxy.js)只有`registerProxyScript`和`onProxyError`。没有`chrome.proxy.settings`导致`obj is not an object or null`错误。

https://hg.mozilla.org/integration/autoland/rev/1b162d4857b5#l6.29

但是，下列bug被标为无效了，说将在1295807中解决。而1295807只添加了registerProxyScript。不确定是漏掉了，还是只需registerProxyScript而不需要再考虑和兼容get/set/clear。
```
Bug 1285343 Add support for chrome.proxy.settings.get RESOLVED INVALID
Bug 1285351 Add support for proxy.settings.get RESOLVED INVALID
Bug 1285352 Add support for proxy.settings.clear RESOLVED INVALID
Bug 1285342 Add support for proxy.settings.set RESOLVED INVALID
```

`_proxyChangeListener`可能也还没有，https://developer.chrome.com/extensions/proxy 中没有，不确定是什么机制/目的。
storage方面好像也有问题，`TypeError: this.storage.getAsync is not a function`，去掉Async则`TypeError: this.storage.get(...) is undefined`，不太明白，`OmegaTargetCurrent.Promise`和build封装太多了。

**Comment by FelisCatus** [comment]
Moz 的那个 API 不是设置代理选项，而是在沙盒中运行一个类似 PAC 脚本的脚本来返回具体使用哪个代理，有点像 content script. 具体见 [API Design](https://docs.google.com/document/d/1W45o5X2bFRPrTaQDFp9IzTJ8njCVfEgyENS7i2owaUI/edit).

然后那个沙盒运行的脚本是一个固定的脚本文件（包含在扩展包中），但那个脚本可以访问一部分 runtime API 和全部 storage API 来实现动态行为。这个设计非常灵活，允许携带其他上下文信息，也允许扩展返回`PASS`，`SYSTEM` 等结果。

SwitchyOmega 目前的实现方式是完全不同的，是先生成一段 PAC 代码，然后把 Chrome 的代理设置改成使用此段 PAC 代码。一旦设置完毕，代理的解析等 SwitchyOmega 完全无关。

真的要说的话，我感觉 Moz 的设计下 SwitchyOmega 的逻辑更容易实现，就可以避免繁琐的 JS 代码生成等等，只需要读取配置然后按配置来确定即可。这个在目前的 SwitchyOmega 架构下也不难实现。但……让我先看看 Moz 的 Storage API 怎么用吧。

**Comment by FelisCatus** [comment]
我改了下代码，见 #1030. 代理切换以外的所有功能应该都能正常工作了，欢迎协助测试。

换句话说，扩展应该能正常工作，所有功能可用。但是，代理设置并没有真正改变，所以网络请求还是走系统代理。

**Comment by FelisCatus** [comment]
有人试过现在修改的版本了吗？顺便，如果 Firefox Nightly 支持 Proxy API 了，也请戳我一下，我尽快去加入支持～

**Comment by yfdyh000** [comment]
没有细试，因为代码结构仍然不熟悉，等待其他人的尝试以方便找准方向。

需求是什么，https://bugzilla.mozilla.org/show_bug.cgi?id=1295807 已经在 Nightly 55 了。https://bugzilla.mozilla.org/show_bug.cgi?id=1283639 还有其他几项，可以Vote或加入CC来订阅，或者填报新需求。

**Comment by FelisCatus** [comment]
现在应该已经差不多了，我感觉应该能用了吧？求帮忙测试。
测试需要使用 Firefox Nightly build 版本 55 以上。

**Comment by FelisCatus** [comment]
在线安装地址：
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

（扩展还在审核中，但不影响使用 Nightly 安装。）

**Comment by FelisCatus** [comment]
Fixed an issue with SOCKS5 proxy server. Please update.

**Comment by StrollStars** [comment]
感谢 @FelisCatus ，到时候https://addons.mozilla.org/zh-CN/firefox/会出现么？

**Comment by FelisCatus** [comment]
@StrollStars 目前已经提交 zh-CN, zh-TW 等多种语言，但还在审核中。正在审核中的扩展不会出现在任何列表中，只能通过直接链接来访问。通过审核后我不知道会不会自动出现在那里还是需要再提交什么。如果英文版的出现了但中文版的没出现，再戳我一下好了。

**Comment by StrollStars** [comment]
@FelisCatus 好的，谢谢。

**Comment by FelisCatus** [comment]
审核没通过，可能还需要一些其他的修改，比如提供源代码，禁用`eval`等。

可惜的是禁用了`eval`， PAC 情景模式就没办法正常工作了。 Mozilla 的审核真坑……

**Comment by yfdyh000** [comment]
能把审核结果粘贴发出来吗？大家可以帮忙看看。

Chrome商店没有代码审核吧，Mozilla是由志愿者按 https://developer.mozilla.org/zh-CN/Add-ons/AMO/Policy/Reviews 审核。

**Comment by shuxiao9058** [comment]
自己编译试了下，没有问题，能够正常设置和使用。

**Comment by FelisCatus** [comment]
关于审核：

> 1) The use of 'unsafe-eval' is not allowed in the manifest.json's CSP as it can cause major security issues.
> Please note that  'unsafe-eval' will also affect all the included libraries and not only addon's own code.

本来是不需要 eval 的，但要支持 PAC 情景模式就需要执行用户代码。 Chrome 没这个问题是因为 PAC 代码是直接生成到最终的 PAC 里的。我会先禁用 PAC 情景模式功能，然后之后再和审核团队沟通。

> 2) Please do not include both minified and non-minified versions of the same libraries. (Minified versions are better for known libraries)
> 3) When including libraries/font/packages, please only include the files that are needed and used by the addon, instead of including the entire package.

之后精简下打包的东西再提交。基本上就是改 bower.json ，去掉不需要的文件而已。

> 4) Your add-on includes a JavaScript library file that doesn't match any versions known to us. We require all add-ons to use unmodified release versions.
> We accept JQuery/JQuery-UI libraries downloaded from 'ajax.googleapis.com', 'jquery.com' or  'jqueryui.com'; and used without any modification. Minified versions are better. (file-name change does not matter)
> I'm sorry, but we cannot accept modified, re-configured or customized libraries.
> e.g.: lib/jquery/jquery.min.js

感觉没道理，因为我用的 jQuery 也只不过是 bower 上下载的而已……我更新下 jQuery 版本然后再试试看吧。

> 5) This version contains binary, obfuscated or minified code. In order to pass review, please provide the original sources and instructions on how to generate the final XPI.

下次提交的时候会链接到这个项目首页 README.

**Comment by yfdyh000** [comment]
@FelisCatus https://wiki.mozilla.org/Add-ons/Reviewers/Guide/Reviewing#Libraries.2C_frameworks_and_other_unreadable_code

**Comment by FelisCatus** [comment]
我可以升级到 jQuery v3.2.1. 这个 hash 值是正确的。

> 87083882cc6015984eb0411a99d3981817f5dc5c90ba24f0940420c5548d82de jquery.3.2.1.jquery.min.js

其他的呢？

**Comment by yfdyh000** [comment]
不清楚。在备注里加上本项目的链接或许就可以，让审核员能重现min的来源。或者完整源代码那里传一份本项目的zip拷贝？审核员自己编译比对。

**Comment by FelisCatus** [comment]
又提交了审核： https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

**Comment by FelisCatus** [comment]
关于 eval,  我发了邮件给 AMO Editors, 等回复吧。如果实在不行就把 PAC 功能去掉呗……

**Comment by hzdrro** [comment]
在Fx55上工作正常。但是和ublock origin一起使用的话，未加载的资源中会提示被屏蔽的广告，希望能修正一下。

**Comment by FelisCatus** [comment]
我测试了一下，发现被 uBlock 取消了的请求仍然会触发请求的所有事件，但之后就再也不会触发任何事件了，因此 SwitchyOmega 把那些请求标记为超时了。

Chrome 上所有被取消的请求会触发 `onErrorOccurred` 事件，所以我很容易把它们都忽略掉。但…… Mozilla 上就再也没有消息了，我能怎么办？我怎么区分是真的超时还是被屏蔽了……

我感觉 Mozilla 的实现绝对是有问题的。要么应该触发 `onErrorOccurred` 事件，要么 `onSendHeaders` 就不应该被触发了，因为已经取消了。等我有空做一个最小可复现的扩展然后去提 bugzilla 吧……

暂时而言这个肯定是无法修正了，自行忽略掉未加载的资源，或者去选项里把请求监测禁用掉吧……

**Comment by SquallATF** [comment]
试了2台电脑，用的[Nightly 55.0a1](https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-55.0a1.zh-CN.win64.installer.exe)，装好后然后发现并不能用，同样的设置在Chrome下可以正常使用，可用的ff是那个版本？

**Comment by shuxiao9058** [comment]
@SquallATF 我使用”55.0a1 (2017-04-23) (64-bit)“版本正常的，没有问题。。。

**Comment by SquallATF** [comment]
@shuxiao9058 我在向导完了后修改默认创建的proxy为本地的SOCKS5代理，然后访问网络失败，用自动切换规则+规则列表，也无法访问，不是到是不是后提交审核的版本有问题，第一版我没下到～

**Comment by SquallATF** [comment]
@shuxiao9058 我似乎发现问题了是dns解析的问题，Chrome是由代理解析的dns而ff里面好像不是

**Comment by SquallATF** [comment]
@FelisCatus 设置`network.proxy.socks_remote_dns`也不能远程解析dns，求解决

**Comment by FelisCatus** [comment]
远程 DNS 的问题和 SwitchyOmega 无关，最好直接去 bugzilla 反馈。

顺便 Firefox 目前的代理 API 实现 [只支持 `SOCKS`](https://dxr.mozilla.org/mozilla-central/source/toolkit/components/extensions/ProxyScriptContext.jsm#46) 返回结果，返回 `SOCKS5` 会报错……但返回 `SOCKS` 似乎也能使用 `SOCKS5` 代理的样子，所以我这里实现的就是返回 `SOCKS`. 不要去改 SwitchyOmega 代码啦，没用的啦……

**Comment by TangBaohua** [comment]
SSL_ERROR_RX_RECORD_TOO_LONG
火狐55 报这个错

**Comment by celeron533** [comment]
@TangBaohua 参见 https://github.com/FelisCatus/SwitchyOmega/issues/1062#issuecomment-297604159
>SSL_ERROR_RX_RECORD_TOO_LONG
火狐55 报这个错

**Comment by whour** [comment]
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/
商店版不兼容FF 53?
`Not available for Firefox 53.0`
```
firefox -v
Mozilla Firefox 53.0.2
```

**Comment by yfdyh000** [comment]
@whour Firefox 55 开始支持相关接口。

**Comment by whour** [comment]
@yfdyh000 好的，知道了，多谢。

**Comment by Limius** [comment]
似乎还没正式上架？下载不了。

**Comment by FelisCatus** [comment]
@Limius 在这里随时可以下载： https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

只是目前还没有正式审核通过，所以会有一个提醒。此外，如果审核被拒绝的话这个链接会失效，直到下次提交审核才会恢复。审核周期非常长，可能会等很久。

**Comment by Limius** [comment]
非常感谢，我去试试
		

	_____________________________

**Comment by FelisCatus** [comment]
由于我之前忘记看开发者页面了，忘记回答一个审核者提出的问题，导致上一个版本没有过审核。于是我再提交了一次。

**Comment by reklanirs** [comment]
@FelisCatus  请问是不是审核被拒绝了? 
https://addons.mozilla.org/en-US/firefox/addon/switchyomega/ 链接已经失效了 ( ˘•ω•˘ )
FirefoxDeveloperEdition也终于升到55.0b1了, 好像已经可以使用SwitchyOmega了?

**Comment by EMLVIRUS** [comment]
Developer Edition 已经取消 用的 beta 通道
![image](https://user-images.githubusercontent.com/16912240/27173470-676f612e-51eb-11e7-801a-4fdda514afff.png)

**Comment by Arrow-Li** [comment]
现在审核的时间这么长么

**Comment by TangBaohua** [comment]
@FelisCatus  请问可以提供.xpi文件直接下载吗？ 审核界面经常无法进，不好测试。

**Comment by xcffl** [comment]
@TangBaohua 请问在哪里找到的呢？

**Comment by EMLVIRUS** [comment]
链接已经失效一个月了。。。。

**Comment by FelisCatus** [comment]
啊啊，忘记在这里说了，审核被拒绝了，理由是只接受最新版 Angular JS ，见 #1094.

但问题是目前升级到最新版 Angular JS 会出问题，代理模式的编辑界面会被清空，所以暂时搁置了，有空继续折腾。也欢迎大家帮忙提一下 PR.

**Comment by Arrow-Li** [comment]
可以把xpi传到这来么

**Comment by EMLVIRUS** [comment]
发一份在release里 指出是 pre-release 就好了啊

**Comment by Arrow-Li** [comment]
![default](https://user-images.githubusercontent.com/17962902/27566980-652cc8e6-5b1b-11e7-87d3-2eda4931a85c.png)

**Comment by TangBaohua** [comment]
@xcffl C:\Users\xxx\AppData\Roaming\Mozilla\Firefox\Profiles\**********.dev-edition-default\extensions
这个数据目录内，switchyomega开头的就是

**Comment by xcffl** [comment]
@TangBaohua 这个是以前安装了再移除之后留下的…好吧。

**Comment by TangBaohua** [comment]
@xcffl  移除？我从未移除过

**Comment by StrollStars** [comment]
@FelisCatus 好失望，未通过的版本能够挂在这里么？

**Comment by xcffl** [comment]
@TangBaohua 现在页面不存在，怎么会突然在本地出现……应该是安装过吧。

**Comment by FelisCatus** [comment]
抱歉由于之前一些个人原因耽误了下，不过 Angular 1.6.4 已经升级完毕了，已经再次提交审核。

https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

顺便感谢 @Arrow-Li 的建议，我这里还是比较希望能通过审核的，不过如果再被拒绝了，那我也只有自己托管啦……

**Comment by Arrow-Li** [comment]
谢谢啦

Felis Catus <notifications@github.com>于2017年7月6日周四 上午4:08写道：

**Comment by TangBaohua** [comment]
![20170706124444](https://user-images.githubusercontent.com/11957114/27895906-f2c1ce8e-6248-11e7-8bba-66c18327605f.png)
@FelisCatus  为什么点击扩展栏图标的下拉菜单中的“选项”按钮没反应？应该像Chrome那样弹出设置页面的，要设置只能从附加组件页里面点“选项”了。

**Comment by nopyhe** [comment]
@FelisCatus 
被UBO屏蔽的元素 会显示在 资源未加载中，而在Chrome上不会有这个问题。

![default](https://user-images.githubusercontent.com/7794514/27900613-b47839ec-6261-11e7-9923-fb99a10de88e.png)

**Comment by Arrow-Li** [comment]
这个issue很久之前提过了你翻一下

**Comment by FelisCatus** [comment]
@TangBaohua 是嘛？我这里是好的。另外，您的 Firefox 版本和 build date 是多少？

**Comment by nopyhe** [comment]
@FelisCatus 我这里点击选项也不起作用，Firefox Developer Edition 55.0b7

**Comment by TangBaohua** [comment]
@FelisCatus Firefox Developer Edition 55.07b(64位)；Switch Omega版本 2.4.14

**Comment by Arrow-Li** [comment]
2.4.14在Windows上好像无效，设置和之前一样但Google连不上,用Autoproxy正常。
在Mac上2.4.14可以正常工作。

**Comment by FelisCatus** [comment]
我这里 56.0a1 (2017-07-11) (64-bit) Linux 点击选项是好的……请试试看点开菜单，点选项，然后右键图标选择导出错误日志，看看有没有什么特别的信息。另外，不起作用是指点了完全没反应，菜单都没关掉，还是菜单会消失但没有打开选项页面？

**Comment by FelisCatus** [comment]
@Arrow-Li 不知道是什么，但既然有一个系统是好的，那么就不是 SwitchyOmega 的问题了吧。可能是两个版本的编译日期不同，请继续更新 Nightly 版本到最新。 Beta / Developer Build 的我没测试过。

**Comment by nopyhe** [comment]
@FelisCatus 错误日志什么跟这个有关的信息(先导出一个错误日志，然后点击选项，再导出一个，两个日志没有变化)
不起作用指点击后完全没有反应，菜单也没有关掉。

**Comment by Arrow-Li** [comment]
但是老版本的SwitchyOmega是正常的

nopyhe <notifications@github.com>于2017年7月12日周三 下午4:16写道：

**Comment by xcffl** [comment]
56.0a1 (2017-07-12) (64-bit) Linux 可以点击选项，但代理无效（开了全局后每一个域名都是ERROR）

```

ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://www.googletagservices.com",
    "level": "warn"
}
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://pagead2.googlesyndication.com",
    "level": "warn"
}
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://incoming.telemetry.mozilla.org",
    "level": "warn"
}
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://detectportal.firefox.com",
    "level": "warn"
}
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://incoming.telemetry.mozilla.org",
    "level": "warn"
}
```

**Comment by glacjay** [comment]
Firefox 下的 Pan 插件挺好用的，支持直接切换默认代理的功能，大大可以参考下。

**Comment by HougeLangley** [comment]
安装插件时出现无法通过验证。

现在个人使用 foxproxy 使用订阅功能也能实现自动切换。

**Comment by FelisCatus** [comment]
@Arrow-Li 麻烦另外开个 Issue, 说明下使用的代理服务器类型，详细的 Firefox 版本和编译日期之类的。

顺便：之前有一个问题影响 HTTP/HTTPS 类型代理，是 Mozilla 的代码一开始有错， SwitchyOmega 为了能用做了错误的处理，但后来那边修复了所以这边也跟着修复了。可能你在用的那个版本不够新，还没有修复那个 bug. 我个人强烈建议更新到最新版 Nightly 再试试看。

**Comment by FelisCatus** [comment]
@xcffl 请另外开个 Issue ，上传整个日志文件，并说明使用的是何种类型代理服务器。

**Comment by Arrow-Li** [comment]
beta更新后，正常了，谢谢

**Comment by netroby** [comment]
感谢作者长期支持。

**Comment by FelisCatus** [comment]
审核过了。这个关掉了，有问题请另外开 Issue.

I'm closing this issue since SwitchyOmega has been approved on AMO. Please file a new issue if you run into one.

**Comment by EMLVIRUS** [comment]
前排核电

**Comment by liCN** [comment]
感谢作者
