### ISSUE TITLE
找不到设置代理服务器用户名和密码的地方

### ISSUE THREAD

**Issue by HaroldYu** [FelisCatus/SwitchyOmega#1020]
更新中说到可以使用带有用户名和密码验证的代理服务器，而我并没有在设置中找到这一选项，不知能否告知如何设置，谢谢。

**Comment by celeron533** [comment]
仅支持http和https
目前chrome原生不支持socks5认证
#178 
![image](https://cloud.githubusercontent.com/assets/3608762/23908407/e9da45f0-090e-11e7-9b23-04d244b6f73a.png)

**Comment by FelisCatus** [comment]
我改了下 wiki 里的更新说明。抱歉之前说的不够清楚让人误会了。

**Comment by HaroldYu** [comment]
十分感谢大大

2017年3月16日 10:07于 Felis Catus <notifications@github.com>写道：

我改了下 wiki 里的更新说明。抱歉之前说的不够清楚让人误会了。
