### ISSUE TITLE
Frequent but irregular browser freeze when using GFWList autoswitch

### ISSUE THREAD

**Issue by henrypijames** [FelisCatus/SwitchyOmega#1021]
This is the bug I originally filed with (Chromium-based) Vivaldi browser:
https://forum.vivaldi.net/post/120627

Since then, I've come to the conclusion that it is SwitchyOmega in Autoswitch mode that causes the freeze (it means that the browser can still be partially at fault, but at least the problem is related to SwitchOmega). This is because:

1. Using SwitchyOmega+Autoswitch+GFWList in Chrome produces the same freeze, although much milder - the browser becomes sluggish instead of completely unresponsive, and for a much shorter time.
2. Turning off Autoswitch and going back to manual switching completely eliminate the freeze, both in Vivaldi and in Chrome.

I suspect that this has something to do with processing a huge list of regular expressions - I remember AdBlock Plus having similar problems (which is why I'm now using uBlock Origin instead). But I don't know if the freeze is caused by GFWList update (and re-parsing by SwitchyOmega) or by some ill-defined rules in the GFWList that are particularly problematic at runtime.

Anyway, I'm surprised that there aren't more people having this problem. I have encountered it on two different OS (Windows 7 and 10) and two different browsers (though both Chromium-based).

**Comment by celeron533** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-276563870

Its a Chrome issue and may be fixed in version 57.

However, feedback from v57 users that some of them still unable to get rid of this issue.

**Comment by FelisCatus** [comment]
See #815.
