### ISSUE TITLE
当更改情景模式时刷新当前标签

### ISSUE THREAD

**Issue by Minato0326** [FelisCatus/SwitchyOmega#1022]
明明在选项里关闭了，但是在操作的时候的还是会自动刷新，求修复。

**Comment by celeron533** [comment]
SwitchyOmega 2.4.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
我这边没有出现这个问题。

你修改完配置后保存了吗

![image](https://cloud.githubusercontent.com/assets/3608762/24042315/6bb64f76-0b4c-11e7-99e1-0f5475e2875f.png)

**Comment by FelisCatus** [comment]
等等，是不是 2.4.3 坑掉了……让我试试看……

**Comment by FelisCatus** [comment]
已修复， 2.4.4 发布中。

**Comment by FelisCatus** [comment]
v2.4.4 已修复。
