### ISSUE TITLE
Clarification of proxy tooltip information

### ISSUE THREAD

**Issue by AkshatM** [FelisCatus/SwitchyOmega#1024]
Currently when I hover over the extension icon in Google Chrome, I see:

```
SwitchyOmega:: [Direct]
(default) => Direct
```

On switching to a proxy, I see 

```
SwitchyOmega:: [<Proxy name>]
(default) => <Proxy name>
PROXY <PROXY IP:PORT>
```

across many websites globally. This indicates I am using that proxy profile.

However, on visiting `http://www.arenasolutions.com/resources/articles/defect-management/` with proxy enabled, I see

```
SwitchyOmega:: [<Proxy name>]
(TEMP) *.arenasolutions.com => Direct
```

and the behaviour is as if I had visited with my raw IP, as I imagine is happening here. 

Why do temporary wildcard subdomains force SwitchyOmega to use my raw IP as opposed to the proxy profile I have configured? Shouldn't it be using it globally, across all domain names and subdomains?

**Comment by FelisCatus** [comment]
The temporary rule is using whatever profile you tell it to use. It is accessible through the popup menu. For example, if you navigate to that page, you will see `arenasolutions.com` in the popup menu. Clicking on it allows you to set the profile for `arenasolutions.com`. I think you must have clicked `Direct` for it without noticing.

If you intend to use the global configuration, you do not need to use the temporary rule. If you intend to use another proxy just for that site until you restart Chrome, you can select another proxy profile there. If you've made a mistake, you can always modify the rule using the dropdown menu.
