### ISSUE TITLE
Auto Switch在iMac经常失效

### ISSUE THREAD

**Issue by ChokWah** [FelisCatus/SwitchyOmega#1026]
Mac OS : 10.12
Chrome : 57.0
SwichyOmega : 2.4.5

添加一个pac作为科学模式, 根据规则列表切换, 否则就用系统代理. 系统不设置任何代理.
![jietu20170321-162039](https://cloud.githubusercontent.com/assets/13447070/24138315/c2cc304c-0e52-11e7-94c6-657dad34cc5e.jpg)
![jietu20170321-162116](https://cloud.githubusercontent.com/assets/13447070/24138320/c60bb818-0e52-11e7-93e4-bf8e9d43b295.jpg)

====================================================================
**# 浏览器长时间打开, 就经常会失效, 出现这样的情况, 只有重启chrome才work, 插件图标显示1个资源未加载, 即使把google.com加入也不行, 或者选择国外模式也不行**
![jietu20170320-104614](https://cloud.githubusercontent.com/assets/13447070/24138364/eeb836a6-0e52-11e7-8dd9-76b96679c228.jpg)

已经卸载迅雷mac版, 还是这样.

**Comment by FelisCatus** [comment]
怎么说呢……图标显示是红色的“国外”吗？是的话就对了啦。

然后打开`chrome://net-internals/#events`可以看到请求是否实际使用了代理。是的话应会有相关的日志。如果不知道如何解读日志的话会比较复杂，具体的自行查找教程吧。

如果切换正确、也确实使用了代理，但加载不出，应该就是代理服务器本身的问题了。重启 Chrome 才能工作的情况我觉得很罕见，但下次遇到的时候不妨试试看不重启 Chrome ，而是重启代理服务器/代理软件，看问题是否修复。如果修复的话，大概是代理服务器那边并发连接数量太多会出现问题、资源没正确回收或者其他状态相关。

**Comment by ChokWah** [comment]
@FelisCatus  Auto Switch确实生效, 圈圈外环变成红色了, 是pac那个模式. 就是提示一个资源加载失败.

补充一下: 现在换了个部门专用代理(之前公用). 偶尔会提示无法正常运作, 需要手动切换去国外pac模式. 然后再刷新, 成功. 再切换回auto switch, 也成功. 这样看是代理服务器问题吗? 是的话帮我close issue吧.

**Comment by FelisCatus** [comment]
我很难判断是否是代理服务器问题，因为我没办法诊断您的网络环境和代理服务器等等，不过这种情况基本不是 SwitchyOmega 的问题……
