### ISSUE TITLE
Add host to Bypass List via command line

### ISSUE THREAD

**Issue by c0debreaker** [FelisCatus/SwitchyOmega#1028]
Hi folks,

I'll be doing a demo of our applications tomorrow. I'll be simulating a network failure by adding the target host into the bypass. The target host is in my /etc/hosts file.

However, during my demo, I don't want to open SwitchOmega to add the host in the `Bypass List` since there will be customers watching. If they were just my teammates, I can do that but not with my audience tomorrow.

What I was planning to do is someone will have an existing ssh connection to my computer and add the host into the Bypass List using command line. Is there any configuration file that we can add directly? I tried adding the host into `~/Library/Application\ Support/Google/Chrome/Default/Preferences` but it doesn't take in effect. The file gets overwritten again when I open SwitchyOmega.

Any help would be greatly appreciated.

**Comment by FelisCatus** [comment]
Sorry, I don't see a easy way for SwitchyOmega to parse the command line, read local files and so on.

To simulate a network failure, please just modify `/etc/hosts` on the proxy server and set that domain to `127.0.0.1` or any unreachable IP address you like. If you do not have access to the proxy server, you can run squid or something on your local host and chain the remote proxy.

Please let me know if the problem is still unsolved.

**Comment by FelisCatus** [comment]
Also, did you know that Chrome itself has command line flags to set the proxy without using SwitchyOmega? You can set bypass list on the command line as well. That requires you to restart Chrome though, so I don't know whether that helps. If you uses that, please set SwitchyOmega to `[System Proxy]`.

**Comment by FelisCatus** [comment]
There is another stupid trick that you can do... Basically set up Options Syncing on SwitchyOmega and log in to your Google account on your friend's computer and get the syncing going. Make sure that your changes on your friend's computer can get reflected on your computer before you do the demo. During the demo, just change any settings you like on your friends' computer.

The synchronization process takes a while though. It could be just a few seconds if you are lucky, but ultimately it depends on your connection to Google. There is no way to force a synchronization immediately.

**Comment by c0debreaker** [comment]
Regarding 127.0.0.1, that's currently what I'm doing but our app is only accessible via the proxy server. That's why I had to add the host in the Bypass List manually. When it's in the Bypass List, request to the target server will be sent to the proxy server anymore. It will be resolved by my /etc/hosts file. In this case, it will fail since it's pointing to 127.0.0.1.

**Comment by c0debreaker** [comment]
Yeah, I saw that Sync options but wasn't sure what it was for.

**Comment by c0debreaker** [comment]
I've also been playing with OSX system-wide settings and it's working great. However, it fails when my VPN is on. Hopefully tomorrow, we won't need VPN.

**Comment by c0debreaker** [comment]
Where are the settings getting stored though? Is it hosted externally? It's because it's updating my local Preferences file which tells me there is an external source.

**Comment by FelisCatus** [comment]
What sync does is whenever you change the options on one device, the same changes will be applied to another. It requires you to set it up on two devices and log in to Chrome using the same Google account though.

**Comment by FelisCatus** [comment]
The settings are stored in `chrome.storage.local`, which I have no control. I don't know where it is stored in the file system, but changing files on disk will not help.

**Comment by c0debreaker** [comment]
I've never tried login to Chrome. Where I can I find the login? I wasn't aware we can login to Chrome. However, I can login in to Google.

**Comment by FelisCatus** [comment]
Okay, go to `chrome://settings/` and see the "Sign in" section at the top. If you are prompted about what to sync, make sure that you check `Extensions` and `Settings`.

**Comment by c0debreaker** [comment]
WOW, I see it now. I've never tried this. :)

**Comment by FelisCatus** [comment]
Well, let me know if it works for you. :)

The thing is... if it doesn't, I have no other way to help you on the demo :cry:

**Comment by c0debreaker** [comment]
Thanks for the help. I'll keep you posted after our demo tomorrow.

**Comment by c0debreaker** [comment]
LOL, I played with the localStorage.setItem on `omega.local.availableProfiles` and I was able to update the object. However, look what happened, hehehe :D http://imgur.com/a/Ck7Fs

**Comment by celeron533** [comment]
@c0debreaker , does Chrome protect/verify the local storage?

**Comment by FelisCatus** [comment]
@c0debreaker That's a cache for the popup menu, not the setting value.

**Comment by c0debreaker** [comment]
oh ok

**Comment by c0debreaker** [comment]
I tried the SYNC and the other computer was able to get the new settings after 15 seconds. Not bad.

**Comment by c0debreaker** [comment]
I tried it on our real app. It works, sometimes it takes like 2 mins for Chrome to sync

**Comment by FelisCatus** [comment]
How was the demo?
