### ISSUE TITLE
Auto Switch help

### ISSUE THREAD

**Issue by ordersvivid** [FelisCatus/SwitchyOmega#1029]
I absolutely love the app so far! I set up multiple profiles for each proxy. Quick search or manually changing works perfectly.

Is it possible to set up auto switch or another setting so that every new tab that is opened automatically grabs a random profile without manually clicking quickswitch?

**Comment by celeron533** [comment]
I think it couldn't do that.
And when you switching the profile, it will take effect on all tabs.

**Comment by FelisCatus** [comment]
This is not possible since tab information is not available to PAC scripts.
