### ISSUE TITLE
状态图标的变动没有以前的版本明显，建议改进

### ISSUE THREAD

**Issue by xuexiaokang** [FelisCatus/SwitchyOmega#103]
现在一下子很难通过图标的颜色变动来分辨现在的状态，之前是灰色地球和彩色地球，一看就非常明显，现在的太难分辨了。

SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by FelisCatus** [comment]
见 #107.
