### ISSUE TITLE
Proxy leaks

### ISSUE THREAD

**Issue by paspep** [FelisCatus/SwitchyOmega#1031]
Hello,

Fist of all excellent app! well done.

Just a quick note:

The rule proxies are easy to detect from websites (if they just query another URL).

It would be great if there was an option (if possible) to sandbox the tab.

i.e. if you have a rule for domain *google.com, when you open google.com on a tab, that tab would lock & route ALL traffic via the proxy for all urls hitting it (e.g. even if google.com queries other domains as  this would leak your proxy)

Kind regards,

SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by celeron533** [comment]
Unfortunately, tab information is not available to PAC scripts. #1029

**Comment by FelisCatus** [comment]
Created [FAQ entry](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#can-you-add-support-for-tab-based-or-window-based-switching) for tab-based switching.

Thanks again, @celeron533!

**Comment by celeron533** [comment]
> If you need to use different proxies for different windows, you can add more persons in Chrome. Each person can install SwitchyOmega and keep their own settings. This allows you to open one window for each person with different proxy settings.

Or using [sandboxie](https://www.sandboxie.com/) to create independent instances of Chrome.
