### ISSUE TITLE
情景模式能否排序？

### ISSUE THREAD

**Issue by AmelieNet** [FelisCatus/SwitchyOmega#1032]
请问设置界面里什么排序情景规则
![image 001](https://cloud.githubusercontent.com/assets/7888766/24412819/183a7386-140c-11e7-818a-3d3fcaaedfc5.png)

问题在于我如果临时q切换情景规则的话第一个选项是SS而不是别的，这就很累人了，求能不能加入排序的功能。
![image 003](https://cloud.githubusercontent.com/assets/7888766/24412812/130c8a2a-140c-11e7-9189-7bfff4e0d775.png)

SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by celeron533** [comment]
自定义情景模式排序 Customize profile order #607

**Comment by FelisCatus** [comment]
同种类型的是按字母顺序排列，这个情况的话，把 XX-Net 情景模式改个名，前面加个`0`就好。
