### ISSUE TITLE
菜单条目丢失

### ISSUE THREAD

**Issue by StrollStars** [FelisCatus/SwitchyOmega#1033]
Chrome 31下，只剩下了如下几个菜单项：
直接连接、系统代理、设置的情景模式、选项
其他菜单项都不见了，望修复，谢谢。

**Comment by celeron533** [comment]
现在的chrome最新正式版是57

**Comment by wenliyang** [comment]
使用这么老的版本，是有什么特殊需求么

**Comment by FelisCatus** [comment]
可能确实低版本有兼容问题吧，但我这里没测试过……

请打开一下弹出菜单再关掉，然后右键点图标选择导出错误日志，并将结果上传到这里。“导出日志”功能也可以在选项页面找到，具体操作为点击左上角 SwitchyOmega 字样然后再点导出日志按钮。

如果日志里没有什么特别的，也可以右键图标点“Inspect popup”/“检查弹出窗口”，然后在 Console 一栏查看是否有错误信息。

**Comment by FelisCatus** [comment]
顺便看一下您的 SwitchyOmega 版本吧？之前有一个版本出了些问题，但应该已经修复了。请更新到 2.4.5.

**Comment by StrollStars** [comment]
@celeron533 @wenliyang 使用老版本是为了兼容一些不再更新的扩展。
@FelisCatus 谢谢开发者，导出日志只有我的几个情景模式，控制台也没有信息。不必麻烦了，我还是升级浏览器吧。

**Comment by FelisCatus** [comment]
这究竟是什么原因呢……等我有空弄个 Chrome 35 试试看吧。

**Comment by YuSuu** [comment]
.....ChromeChrome 57.0.2987.138 飘过

**Comment by FelisCatus** [comment]
@YuSuu 求错误报告啊，别直接飘过……具体获取错误报告的方式见上述。

**Comment by StrollStars** [comment]
@FelisCatus 谢谢开发者，因为你给的方法都无法得到日志，所以没法反馈更多。目前升级到64位版57.0.2987.133。

**Comment by YuSuu** [comment]
@FelisCatus呃，我这里使用完美，没什么要报告的，就卡炫耀下版本号哈哈，感谢开发者，
希望能添加快捷键然后使用代理访问当前网页，就只有这一点不爽，每次都需要用鼠标去点

**Comment by StrollStars** [comment]
确实在57版下没发现问题，但是我使用老版本的一大因素是下载扩展，请问下 @celeron533 @wenliyang @YuSuu ，你们在57版下用的是什么下载扩展？
PS： @FelisCatus 借宝地歪个楼

**Comment by YuSuu** [comment]
@StrollStars YAAW这个下载扩展还可以，不过自带的配合微云离线 or 迅雷离线 都足够了

**Comment by StrollStars** [comment]
@YuSuu 感谢推荐，我没说清，我想找一款能够自定义下载工具路径的扩展，以前的**下载工具支持**扩展就不错，可惜不支持新版本。
看了下YAAW for Chrome，好像是把Chrome打造成了Aria2的GUI？

**Comment by FelisCatus** [comment]
@YuSuu 使用代理访问网页的快捷键是`Alt+Shift+O`然后紧接着再按数字键。在弹出窗口按`?`就可以看到哪个情景模式对应哪个数字了。如果您的代理情景是菜单中第一项，快捷键就是`1`。同理切换到直接连接是`Alt+Shift+O`再按`0`.
