### ISSUE TITLE
这种PAC用不了

### ISSUE THREAD

**Issue by xz00311** [FelisCatus/SwitchyOmega#1035]
https://raw.githubusercontent.com/Tuaba/PAC/master/us.pac  是不是软件做不到解密啊

**Comment by FelisCatus** [comment]
我这里可以正常使用。可能 PAC 本身的执行是没有问题的，但 PAC 返回的代理地址您无法正常连接。比如网络问题或者代理服务器不正常工作等等。

具体情况请您查看错误页面上的错误代码，以`ERR`开头的那个。如果不是 `ERR_MANDATORY_PROXY_CONFIGURATION_FAILED`，那么就不是 PAC 脚本执行的问题。
