### ISSUE TITLE
ip地址显示问题

### ISSUE THREAD

**Issue by YukiMakino** [FelisCatus/SwitchyOmega#1036]
清除浏览记录之后，出现了ip切换的问题，没有使用代理的时候ip地址显示的是在美国，导致访问网页出现延时和无法访问等问题。望解决

SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FelisCatus** [comment]
首先请确认 SwitchyOmega 选择的是直接连接模式，或者自动切换模式下图标颜色为灰色（直接连接）。

然后请在地址栏中输入`chrome://net-internals/#proxy`回车，然后查看页面上的内容。可以截图或者把内容复制到这里，不过请注意遮挡服务器地址等以保护个人隐私。

如果有其他代理设置相关的扩展，请禁用那些扩展。
