### ISSUE TITLE
此扩展程序可能已损坏（Chrome）

### ISSUE THREAD

**Issue by asmosn** [FelisCatus/SwitchyOmega#1038]
刚安装正常，使用一段时间后就错，提示：此扩展程序可能已损坏。
Chrome开发模式加载扩展后开始使用正常，一段时间后也出错：
{{'options_tab_general' | tr}}
{{'options_group_proxyChanges' | tr}}
{{'options_revertProxyChanges' | tr}}
{{'options_group_networkRequests' | tr}}
{{'options_monitorWebRequests' | tr}}
{{'options_downloadOptions' | tr}}
{{'options_downloadOptionsHelp' | tr}}

**Comment by celeron533** [comment]
我遇到过一次，结果是win10和SSD之间的驱动有问题，导致SSD随机丢文件。几天后系统文件爷不经意间的损坏，windows无法启动。。。

**Comment by FelisCatus** [comment]
见 #940 ，可能是病毒，也可能是单纯的磁盘错误。先试试看重装吧。

另外，也可以右键点图标选择导出日志然后上传到这里。
