### ISSUE TITLE
chrome52+ 下如何在autoswitch模式下匹配cdn下发的纯ip开头网址

### ISSUE THREAD

**Issue by kalagxw** [FelisCatus/SwitchyOmega#1039]
另外能不能加个匹配ip段的功能（如CIDR）

**Comment by celeron533** [comment]
浏览器的代理设置有两种主流方法：

1. 直接全局代理+排除列表
2. PAC中通过类Javascript实现按需代理

从原理上讲，SO只是个能够动态生成PAC的工具。
如果CDN直接下发的是IP，可以自己写一段script来做CIDR的匹配。但如果下发的是域名，就有点超出PAC的职能范围了。。。

**Comment by kalagxw** [comment]
能不能举个例子，比如用pac（javascript）匹配任意ip开头地址不走代理用什么函数？通配符怎么写?

**Comment by FelisCatus** [comment]
在设置>界面中启用高级切换规则后，即可在自动切换界面使用 `IP 地址字面量`规则，支持 CIDR.

此规则只支持网址中使用 IP 地址的情况，不支持 DNS 解析。
