### ISSUE TITLE
Fault_Report_20170404

### ISSUE THREAD

**Issue by j5shi** [FelisCatus/SwitchyOmega#1041]
SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Comment by FelisCatus** [comment]
?

**Comment by ugksoft** [comment]
楼主都不知道在说什么

To
 FelisCatus,我就不另开主题了,你看过就算不用怎么回复
1.
把"关于"这项,从软件标题里,移动左面的设置项里吧,很多人可能并不知道藏着个"关于"的页面

2.
  有些网站,默认不能访问,手工改成强制代理后,发现能访问了,
  但这时想添加,"添加条件"这个项没了,必须切换回非强制代理模式,才能能添加
  有点这里有点聪明过头了

3.
在主设置页上,加一张支付宝二维码吧,或许你能收到个油条大饼钱,虽然付的比例非常小,总比没有强
(事先申明,我不给,嘿嘿..)如果你感觉这样等于实名了,那你可换成比特币地址
推荐10-100块RMB左右

**Comment by j5shi** [comment]
This was an auto generated fault report, actually I didn't know what it tried to report.

**Comment by FelisCatus** [comment]
Maybe you just clicked on "report issues" in the context menu or on the options page. In that case, you don't have to submit the issue.

**Comment by FelisCatus** [comment]
@ugksoft 1. 找不到关于页面也没事，不影响使用。 2. 自动切换没有激活的场合，无法添加条件。 3. 目前没有接受捐助的计划。

**Comment by ugksoft** [comment]
好像你没明白2

我的意思是,正常是"自动"状态,可是发现某个网值连不上,或是速度爆慢,
这时手工切换到"VPN"状态, 正常了,可是这时想把当前网值加到自动切换的列表里, 发现,菜单里,没有"添加条件"这个选项了

应该把这个"添加条件"的菜单项,改成不论什么情况下,都显示,
