### ISSUE TITLE
扩展栏显示的图标颜色问题

### ISSUE THREAD

**Issue by ProbeKeeper** [FelisCatus/SwitchyOmega#1042]
直连时，显示是一个灰色圈套一个绿色圆 ; 使用代理时，是一个青色圈套一个绿色圆，我的真实感受：差异太小了……经常搞不清，最老的switchy两种状态分别是灰色和蓝色，很好识别，希望作者大大能考虑下

SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by wenliyang** [comment]
请点击“情景模式”前的颜色方块，每个代理情景模式的颜色都是可以自定义的，老的switchy扩展也是这样

**Comment by FelisCatus** [comment]
感谢 @wenliyang!
