### ISSUE TITLE
部分不在规则内的网页“资源未加载”。

### ISSUE THREAD

**Issue by iceliminghui** [FelisCatus/SwitchyOmega#1043]
比如微软的hotmail。
我设置统配规则（`*.onedrive.live.com`）使用代理，但仍然不使用代理并且无法打开。
默认自动切换规则，新增（`*.google.cn`）使用直连，（`*.onedrive.live.com`）使用代理，其他均为默认。
偶尔会访问google的网站打开很慢或者打不开。微软邮箱跳转或者直接访问onedrive则会无法打开提示检查代理，同时omega上提示一个未加载的资源（`*.live.com`）
感觉好像是和gfwlist规则有（兼容？）问题。

SwitchyOmega 2.4.5
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by FelisCatus** [comment]
其他资源也可能在`*.live.com`域名下，但不在`*.onedrive.live.com`下。请尝试添加`*.live.com`.
