### ISSUE TITLE
feature request: customize shortcut key to use proxy to visit current link 

### ISSUE THREAD

**Issue by YuSuu** [FelisCatus/SwitchyOmega#1044]
customize shortcut key to use proxy to visit current link,
and some visible sign to show whether now is using proxy,
thanks!

**Comment by FelisCatus** [comment]
SwitchyOmega can't control the proxies for each tab or window. Also, it cannot associate the user interactions with the proxy requests. Therefore, such features are not technically possible.

The closest thing you can get is to open the link and choose a temporary rule from the popup menu. This can be done using the key sequence `Alt+Shift+O`, `T` and then the arrow keys to choose your desired profile to use.
