### ISSUE TITLE
通过点小圆点的沙漏那个设置当前网站使用proxy访问好像不具有记忆性

### ISSUE THREAD

**Issue by YuSuu** [FelisCatus/SwitchyOmega#1047]
RTRTRTRT
我访问一个测速网站，通过proxy，
重启浏览器后，发现，还是直接访问，没有通过proxy，
希望能具有记忆姓，一次设置后以后都会有效

**Comment by celeron533** [comment]
漏斗那个是临时规则。若要永久生效，则需要点击加号添加条件

**Comment by YuSuu** [comment]
@celeron533  哈哈，谢谢。卖了个萌
