### ISSUE TITLE
please fixed it ! thanks!

### ISSUE THREAD

**Issue by JamesLinus** [FelisCatus/SwitchyOmega#1048]
SwitchyOmega 2.4.5
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3069.0 Safari/537.36

SwitchyOmega does not provide proxies, VPNs, or other network services.

**Comment by celeron533** [comment]
So what's your problem?

**Comment by ares077** [comment]
v tom ze niesom hecker ani vyvojar len som to skusal a bavi ma to len naviem ani to ako vygenerovat napriklad moju komunikaciu na fb ....alebo vytvorit aplikaciu kde sa to naucim?

**Comment by celeron533** [comment]
Hi @ares077 , if you have questions, please create a new issue.
Preferred to written in English.

**Comment by FelisCatus** [comment]
Closing this for now.

@ares077 Please create a new issue if you have new questions. I personally can't understand your language so please try English if possible. This is a issue tracker for issues with SwitchyOmega itself only. This is not a general forum where you can ask for help regarding extension development.
