### ISSUE TITLE
Auto Switch mode doesn't work

### ISSUE THREAD

**Issue by KsaRedFx** [FelisCatus/SwitchyOmega#105]
When rules are applied on the Auto Switch page, no matter what rule the last set proxy is used. 
Even non matching rules will go to the last used proxy before setting auto switch. 

Setup a Proxy, set rule to Host Wildcard, set *.netflix.com,
Set default to go via Direct, go to Netflix.com

You'll be using direct connection. 

No switching happens at all. The icon correctly changes but no switches actually happen.

**Comment by FelisCatus** [comment]
Closing this issue for now. Please attach the error log if you want to reopen it.

**Comment by KsaRedFx** [comment]
I just reinstalled SwitchyOmega and this bug appears to be fixed. I'll post a log if it occurs again.

**Comment by FelisCatus** [comment]
Thanks.
