### ISSUE TITLE
使用shadowsocks提供的pac无法访问http的被墙站点

### ISSUE THREAD

**Issue by huxim** [FelisCatus/SwitchyOmega#1050]
使用pac模式,填入shadowsocks提供的pac地址,确定pac中有被墙域名,但只要是访问http站点就无法访问.

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
![image](https://cloud.githubusercontent.com/assets/2505801/25034026/f9ae3bde-2115-11e7-8ddd-1d63889c8007.png)
![image](https://cloud.githubusercontent.com/assets/2505801/25034040/227e48ba-2116-11e7-804e-2c1f1cce0b75.png)

**Comment by FelisCatus** [comment]
这样很难确定是什么呢……感觉像是没走代理，但又不确定……
但假如是 PAC 文件的话，和直接使用那个 PAC 脚本的结果应该是一样的吧？会不会是那个脚本本身结果就是没走代理的？

有使用过临时规则或者之类的吗？使用前后有没有区别？

此外， PAC 脚本是可以改的，只要清空 URL 就可以手动修改下方的文字内容。可以试试看在最终返回之前加一句`alert(变量名)`之类的，然后就可以在`chrome://net-internals/#events`看到输出。这样有助于调试。

**Comment by huxim** [comment]
访问https版本是正常的

**Comment by huxim** [comment]
pac也是正确的,用ie可以访问

**Comment by huxim** [comment]
其实我也很奇怪,看起来像pac的问题,因为ie用这个pac也没法访问,但访问https版本又是正常的

**Comment by FelisCatus** [comment]
PAC 的问题问我也没用咯……
