### ISSUE TITLE
是否可以支持特定 tab 代理？

### ISSUE THREAD

**Issue by Aqours** [FelisCatus/SwitchyOmega#1051]
比如浏览器打开了五个 tab-[1-5]。

然后让 tab-2 始终走代理或者设定的规则，其他 tab 走自动规则这样。

要代理的网页中的有些资源（比如视频、音频）都是用 cdn 的链接，如果要添加规则需要一条一条找，而右键菜单也不同方便的添加这些链接，因此如果能实现按 tab 代理会便利一点。

**Comment by celeron533** [comment]
Chrome和PAC不支持这样的用法 #646

**Comment by Aqours** [comment]
chrome.webRequest 先做 url 来自哪个 tabId 然后决定用那种代理规则，这样也不行？

**Comment by FelisCatus** [comment]
chrome.webRequest 不能决定代理规则。所有代理设置都通过 PAC 脚本实现。
