### ISSUE TITLE
如何删除外部情景模式？

### ISSUE THREAD

**Issue by lslqtz** [FelisCatus/SwitchyOmega#1052]
之前使用了某个去广告扩展，然后一直有这个模式，删除这个扩展无济于事，只能重新安装。

**Comment by lslqtz** [comment]
同时我发现使用备份文件备份 重置 恢复后也能正常。
这是由于什么引起的？

**Comment by celeron533** [comment]
如果在chrome伤安装了多个会更改代理的扩展，默认是将全部权限交给最后安装的那个。

**Comment by lslqtz** [comment]
该扩展已经被删除，目前权限是被SO接管。
但是仍然是有外部情景模式在这里。

**Comment by FelisCatus** [comment]
这个没做删除功能……目前最好的办法就是无视那一条就好。
或者也可以在选项界面打开开发者工具，在 Console 里输入`delete localStorage['omega.local.externalProfile']`回车。

如果要做删除功能要怎么做呢……放哪里好呢……

**Comment by FelisCatus** [comment]
外部情景模式不是选项的一部分，而是属于“本地状态”，导入配置文件不会覆盖。
在选项页面点左上角 SwitchyOmega 再点重置选项可以清除，不过那个真的就什么都没了……

**Comment by lslqtz** [comment]
导出 重置 导入
重置就删了，导入又恢复了。
可以考虑放重置选项左侧，讲道理强迫症

**Comment by FelisCatus** [comment]
试试看那个 Console 的方式，然后看看是否外部情景模式还是会出现。如果还是会出现的话，那么仍然有其他扩展在设置代理情景模式，不是 bug.

**Comment by FelisCatus** [comment]
想了很久，但感觉最好的办法就是加个选项隐藏掉外部情景模式就好了……

**Comment by lslqtz** [comment]
不会出现，已经确定没有其它扩展，因为已经彻底删除了。

**Comment by gggccc44** [comment]
你试试Tampermonkey里面能看到不，记得某个脚本安装成了扩展模式在Tampermonkey里面能看到

或者谷歌很多参数的啊，你看看哪儿能删不，实在没法只能留着了，反正也没啥影响吧，或者你把SwitchyOmega也给删了重新装

**Comment by FelisCatus** [comment]
Proposed UI:
![image](https://user-images.githubusercontent.com/912649/29145620-d46882fe-7d2b-11e7-958c-58d9366120b1.png)

暂定界面如上，中文翻译暂定如下：

- [ ] 在弹出菜单中显示由其他扩展或应用设置的代理服务器。

**Comment by FelisCatus** [comment]
Added a section called Conflicts which explains conflicts and therefore the UI has been changed accordingly. The checkbox still does the same thing but is under a different section in a different page.

![image](https://user-images.githubusercontent.com/912649/29483419-eedaa136-8473-11e7-8067-8a60e3e55e6c.png)


添加了名为“冲突”的章节，其中描述了关于冲突的内容。因此， UI 也做了相应的更改。勾选框的功能没有任何变化，只是页面和位置变了。

![image](https://user-images.githubusercontent.com/912649/29483401-94fb2500-8473-11e7-8574-4d48edd44494.png)

**Comment by FelisCatus** [comment]
v2.5.1 已经修复， Chrome Web Store 已发布。 Firefox 版仍在审核中。

Fixed on v2.5.1. Published on Chrome Web Store. Firefox version still under review.
