### ISSUE TITLE
希望能为情景模式中的规则添加“启用/禁用”的功能

### ISSUE THREAD

**Issue by liuxb** [FelisCatus/SwitchyOmega#1053]
今天试用了firefox版的proxy switchyomega，感觉缺少这个功能，不知道能否考虑？
谢谢！

**Comment by FelisCatus** [comment]
话说在自动切换界面上，点切换条件类型那个下拉框，里面选择“(Disabled)”不就禁用掉了吗？

**Comment by liuxb** [comment]
明白了谢谢。
