### ISSUE TITLE
Mozilla Firefox: 选择清除 Cookies 时 SwitchyOmega 当前选择的情景模式等信息重启后不会保留

### ISSUE THREAD

**Issue by liuxb** [FelisCatus/SwitchyOmega#1054]
发现一个奇怪的问题，如果设置“退出firefox时清除cookies”，switchyomega的startup profile功能不正常。
复现步骤：
1 firefox55a1，SwitchyOmega 2.4.8，新建一个干净配置。startup profile默认就是current profile不变。
2 点击工具栏按钮设置当前情景模式为 直连。进firefox设置页面--隐私--历史--设置使用自定义设置--接受cookies，下面的“keep until”设置为“i close nightly”。对应设置为user_pref("network.cookie.lifetimePolicy", 2);。
3 关闭firefox，重启。这时工具栏按钮当前情景模式显示为 直连。点击按钮设置当前情景模式为 自动。
4 关闭firefox，重启。这时工具栏按钮当前情景模式显示仍为 直连。正确应为 自动。
不知道就是这么设计的还是bug，我习惯是设置为关闭firefox时清理cookies，需保留cookies的站点放到例外列表中，这样显得干净一点。现在和扩展冲突了。switchyomega记忆上次情景模式的地方能不能放到storage.js里啊？
谢谢！

SwitchyOmega 2.4.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by FelisCatus** [comment]
目前的存储是在 localStorage 里的，也许可以改吧，但暂时优先级不在这里……

可以试试看在选项的 UI 界面设置 Startup profile 为自动切换，那个是保存在 storage 里的。

**Comment by liuxb** [comment]
cookies和localstorage应该是独立的吧，会有影响？
步骤3时，可以看到omega.local.currentProfileName是direct，然后设置自动，值相应变成auto switch，但重启后仍然是direct。好像设置network.cookie.lifetimePolicy以后，localstorage设置不能保存了？

设置 Startup profile 为自动切换，算是暂时方案，还是希望在我1楼那样设置cookies时，启动模式为当前情景模式这个功能也能正常工作，希望在以后版本中能考虑下，多谢！

**Comment by FelisCatus** [comment]
也许那个 policy 也包括 localStorage 吧，我没试过所以不知道。

**Comment by liuxb** [comment]
omega.local.web.last_url这个最后激活页面的设置也是不能记忆了，总之不在storage.js里保存的设置都会受到影响。

**Comment by FelisCatus** [comment]
顺便问一下，能把 SwitchyOmega 加入到例外列表里吗？有没有找到方法？

**Comment by liuxb** [comment]
谢谢提醒，加入例外有效！
SO打开选项时，url是：moz-extension://3aa9773c-0904-441a-95f8-31e92bdbd2a8
把这个地址加入cookies例外规则中，local storage设置在重启以后得到保留了。
有点不足的是3aa9773c-0904-441a-95f8-31e92bdbd2a8它这个是随机的，每个配置中都不一样。

**Comment by FelisCatus** [comment]
统一到 #1350 讨论吧。
