### ISSUE TITLE
Login password

### ISSUE THREAD

**Issue by Vyachesslav** [FelisCatus/SwitchyOmega#1055]
Hello. What is the format for recording a proxy with a username and password?

**Comment by FelisCatus** [comment]
If you are using HTTP/HTTPS proxies, please use the padlock button beside the server column to set the username/password. If you are using SOCKS proxy servers, unfortunately Chrome itself does not support authentication for those.

**Comment by Vyachesslav** [comment]
Thanks for the answer. But I do not see padlock button. Screenshot attached:
![screenshot-5](https://cloud.githubusercontent.com/assets/27506105/25069305/a152c12e-22a7-11e7-8a6b-f1f9b23a6acd.jpg)

**Comment by Vyachesslav** [comment]
It turns out the wrong program downloaded. Downloaded Svitchi Omega - everything works. Thank you
