### ISSUE TITLE
Intermittent connectivity issues

### ISSUE THREAD

**Issue by lconnell** [FelisCatus/SwitchyOmega#1056]
For the most part, this switcher works great. There are times however where I have to refresh a page because there are connectivity issues reported within the plugin. This is when I have it set to either 'direct' or 'system proxy'. Refresh always fixes it, but is inconvenient, especially if you are filling out a form.

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by FelisCatus** [comment]
Network issues are reported, but not caused by SwitchyOmega. SwitchyOmega never does any network internals.

For connectivity issues, please check your internet connection, proxy server and so on.
