### ISSUE TITLE
Privacy error on Chrome 58

### ISSUE THREAD

**Issue by liuyang12** [FelisCatus/SwitchyOmega#1057]
GoAgent and SwitchyOmega work perfectly before I updated Chrome to the latest version of 58.0.3029.81. The Privacy error problem occurs when websites with https are opened. The enclosed text of screenshot is a typical example. The problem might result from the restricted privacy policy in Chrome 58. To this end, is it possible for the SwitchyOmega community to solve the problem?

> Your connection is not private
> Attackers might be trying to steal your information from www.google.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_COMMON_NAME_INVALID
> Subject: *.google.com
> Issuer: GoAgent
> Expires on: Apr 18, 2025
> Current date: Apr 20, 2017

**Comment by wenliyang** [comment]
这是 goagent 的问题，不是 SwitchyOmega 的
goagent 作者已经不再维护，建议你换成 XX-Net 或 goproxy，都已经解决了这个证书问题

**Comment by liuyang12** [comment]
Thank you @wenliyang , XX-Net solves the problem exactly.
