### ISSUE TITLE
打开SwitchyOmega扩展程序就会禁用flash

### ISSUE THREAD

**Issue by neunundneunzig** [FelisCatus/SwitchyOmega#1059]
在chrome的设置里勾选使用flash也没有用
貌似SwitchyOmega会自动禁用flash插件
把这个扩展关掉，网页上用flash插件的视频和其他内容就能用了

有什么办法可以解决吗？

**Comment by celeron533** [comment]
是不是因为你用了SwitchyOmega所以能够访问到一些flash资源导致chrome提示禁用flash。
换句话说，没有SwitchyOmega的时候由于某些原因，页面无法加载flash，所以chrome不会提示任何flash相关信息？

chrome57目前没有问题。
另外似乎从chrome52起就默认禁用flash了

**Comment by FelisCatus** [comment]
诶……哈……？和 SwitchyOmega 无关吧。
更像是因为代理设置之类的问题， Flash 文件没加载出来之类的……

**Comment by neunundneunzig** [comment]
@celeron533 
> 没有SwitchyOmega的时候由于某些原因，页面无法加载flash，所以chrome不会提示任何flash相关信息？
按这个说法的话，没有SwitchyOmega页面无法加载flash，应该一样会有网页上的flash插件无法使用，导致视频和某些元素失效的情况啊。可实际上一关掉SwitchyOmega，页面上的flash就能用了……

@FelisCatus 

> 更像是因为代理设置之类的问题， Flash 文件没加载出来之类的

这个是要在哪里进行设置？
是SwitchyOmega里面还是XXnet？

**Comment by celeron533** [comment]
@neunundneunzig 虽然可能性不大，但有时候某些页面内容不使用代理是无法获取的，比如通过javascript动态生成一个swf访问地址，但如果这段javascript无法正常访问，后面的swf地址也不可能被浏览器请求。
另外你的chrome是什么版本？

**Comment by neunundneunzig** [comment]
@celeron533   版本是58.0.3029.81
