### ISSUE TITLE
SSL 接收到一个超出最大准许长度的记录 （firefox nightly 55）

### ISSUE THREAD

**Issue by shihuibei** [FelisCatus/SwitchyOmega#1060]
使用代理http 127.0.0.1:8087 访问谷歌出现：

建立安全连接失败
SSL 接收到一个超出最大准许长度的记录。

SwitchyOmega 2.4.10
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
```
{
    "message": "An unexpected error occurred"
}
```

**Comment by celeron533** [comment]
基本上和SO无关，SO只能判断是否使用代理。
（从端口上来看似乎是XXNet？）
