### ISSUE TITLE
云备份功能移植建议

### ISSUE THREAD

**Issue by valianliu** [FelisCatus/SwitchyOmega#1061]
能否参考并移植一下Tampermonkey v4.2.7的云备份功能？其支持Google Drive，One Drive等直接备份，云端备份规则很方便迁移到新设备上并保持同步。
目前的 选项同步 (测试中) 功能在360极速上测试好像没有什么反应。
Thx

**Comment by FelisCatus** [comment]
SwitchyOmega 本身可以用文件形式导出备份文件，可以随便上传至任意网盘，然后在新电脑上导入配置即可。操作并不会比登录复杂多少。

目前没有内置网盘集成的计划，主要原因是网盘缺乏即时选项同步的机制，而且开发工作量很大，而且既然扩展已经自己有同步机制了，再去费精力整合第三方的网络存储确实有些超出扩展应该做的范围了。而且支持了一家就会有人再提议另一家……到最后 80% 以上的代码都用来处理各种网盘的问题了，实在是……这边也不比 Tampermonkey 开发那么活跃，长期以来只有我一个人在做编码的工作，有很多更重要的事情需要我花精力去做。

顺便 360 浏览器并不在支持范围内，可能碰巧能用，出了问题我可能也会顺手修一下，但直接禁用掉功能的这种情况，无论如何我也没办法把那功能加回来的吧？这种情况您应该去找他们反馈，让他们不要去掉很多重要的功能。
