### ISSUE TITLE
Mozilla Firefox: HTTP 类型代理服务器无法使用

### ISSUE THREAD

**Issue by liuxb** [FelisCatus/SwitchyOmega#1062]
忘了说了是firefox55a1，扩展2.4.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
#1060 这个帖子也提到了

使用ss的代理一切正常。但是不能使用goproxy的代理。
在扩展中设置一个新的代理模式goproxy，127.0.0.1:8087，然后然后使用这个代理时出错，提示：
An error occurred during a connection to 127.0.0.1:8087. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG
（http网站）
SSL received a record that exceeded the maximum permissible length.
（https网站）
如果在firefox自己的网络--代理中设置http代理为127.0.0.1:8087，使用正常，是不是说明问题是在扩展这里？
请指点下，谢谢。下面是两个截图。
http://i.imgur.com/CNO1RRn.png
http://i.imgur.com/5gPqrUk.png

**Comment by liuxb** [comment]
在foxyproxy上的测试结果：
添加http代理127.0.0.1:8087，正常。
如果勾选了后面的SSL Proxy?，就会得到上面的错误结果。
SO上，无论选择http或者https，都不行。
goproxy的证书已经导入firefox。

**Comment by FelisCatus** [comment]
Firefox WebExtensions API 中，指定 `HTTP` 和 `HTTPS` 的语法相同，都是 `PROXY`, 并且优先尝试 HTTPS 类型代理。然后 GoAgent 的这个代理同时支持 HTTP 和 HTTPS, 然后 HTTPS 就出错了，但 Firefox 并不会再尝试 HTTP 了。这个行为是预期行为，和 SwitchyOmega 无关。

要解决您的问题，有以下方案：

* 让 GoAgent 能够正常地接受 HTTPS 请求。我不知道为什么，但我觉得这里可能可以调整 GoAgent 实现。建议反馈到 GoAgent 项目。
* 或者，禁用掉 GoAgent 的 HTTPS 功能。如果是访问本地的话， HTTPS 代理没任何必要。
* 再或者，使用 Privoxy 之类的代理转发请求。
* 最后，也可以去 bugzilla 反馈，建议 proxy API 可以手动指定 HTTP 还是 HTTPS.

**Comment by FelisCatus** [comment]
话说我可能发现一个问题， Firefox 对于不支持 `HTTPS` 的代理好像也不会用 `HTTP`……没仔细测试，但如果是的话，这问题就大了……

**Comment by FelisCatus** [comment]
已知 Firefox 问题，见 https://bugzilla.mozilla.org/show_bug.cgi?id=1359417

**Comment by TangBaohua** [comment]
我也是这个问题，目前台式机几乎只用GoProxy，所以目前等着这个bug修复，目前Firefox我使用世界通代理服务器管理工具

**Comment by FelisCatus** [comment]
Moz 那边 4 小时之前提交了代码，正在审核中。如果能通过的话，下一个 Nightly 版本大概就能修好了吧？

**Comment by FelisCatus** [comment]
刚才看了下，代码还在审核和 CI 流程中……继续等吧……

**Comment by TangBaohua** [comment]
@加油 另外FF的审核真慢

**Comment by FelisCatus** [comment]
这个应该修复了，请安装最新版 Firefox Nightly 以及最新版 SwitchyOmega: https://github.com/FelisCatus/SwitchyOmega/wiki/Mozilla
