### ISSUE TITLE
Additional white list || black list for PAC mode

### ISSUE THREAD

**Issue by Maristie** [FelisCatus/SwitchyOmega#1064]
It's convenient for PAC mode to automatically renew the PAC file. It's not a severe problem to visit domestic websites by proxy except increase of latency. But is it possible to add some extra white list or black list rules for PAC mode by myself without losing the function of auto-renewal?

**Comment by FelisCatus** [comment]
You can use a Switch Profile and add all your custom rules there. Then, select the default rule in the Switch Profile to the PAC Profile to reuse your PAC script.
