### ISSUE TITLE
只要加载 SwitchyOmega 2.4.6   用CHROM打开代理网站均报错，无法访问。

### ISSUE THREAD

**Issue by alonkings** [FelisCatus/SwitchyOmega#1065]
您的连接不是私密连接

攻击者可能会试图从chrome.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。 NET::ERR_CERT_COMMON_NAME_INVALID

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或者网络问题，与 SwitchyOmega 无关。

P.S. GoAgent 等代理服务器会重新签名网站的证书，需要导入证书才能使用。这个问题与 SwitchyOmega 也无关。
