### ISSUE TITLE
Cannot access HTTP site via port 443

### ISSUE THREAD

**Issue by 1plus-1** [FelisCatus/SwitchyOmega#1066]
Reproduce steps:
1. Enable SwitchyOmega extension in Chrome
2. Choose [Direct]
3. Access link http://xxx.xxx.xxx.xxx:443(this is the openwrt luci config page, the 80 port is blocked by ISP so changed to 443)
Result:
It shows "This site can’t be reached"

It works fine when I disable the extension in Chrome.

**Comment by celeron533** [comment]
Have you tried option [System Proxy]?

**Comment by 1plus-1** [comment]
Yes it works now. But I don't understand why the [Direct] not work. Isn't it supposed to be equivalent to disable the extension?

**Comment by celeron533** [comment]
[Direct]: Always use direct connection, ignore the system's global proxy settings (Windows, Mac)
[System Proxy]: Using the system global proxy settings.

**Comment by 1plus-1** [comment]
But I didn't configure any proxy on my computer. There's no proxy service running either.

**Comment by FelisCatus** [comment]
Can you set SwitchyOmega to `System Proxy` and then check `chrome://network-internals/#proxy`?
There might be a proxy running without being noticed.

**Comment by 1plus-1** [comment]
Use [Direct] option:
              Effective proxy settings
                        Use DIRECT connections.

Use [System Proxy] option:
              Effective proxy settings
                        PAC script: http://wpad/wpad.dat
                        Source: SYSTEM
              Original proxy settings
                        Auto-detect
                        Source: SYSTEM


My computer is inside the corporation domain. Does this mean the domain policy set a proxy for all computers by default? @FelisCatus

**Comment by 1plus-1** [comment]
One more thing is with Direct option I can access to other common site like google.com. But it has to be System Proxy to visit my router config page.

**Comment by FelisCatus** [comment]
Sorry for the late reply. I think your corporation has set a [WPAD configuration](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol). Please try to visit `http://wpad/wpad.dat` to see if you can see a PAC script there. (There can be alternative URLs for this file, please see the linked Wikipedia article above for examples.) If so, please create a PAC profile with the URL `http://wpad/wpad.dat` (or whatever URL that works for you) and use it instead of `[Direct]` in SwitchyOmega whenever you are in the corporation.

**Comment by 1plus-1** [comment]
There does have a file wpad.dat. It works now. Really thanks for the information!

**Comment by FelisCatus** [comment]
No problem! I'm glad it's working for you.
