### ISSUE TITLE
翻墙不使用系统代理的话无法更新chrome组件,chrome://components/，扩展程序那里，chrome://extensions/倒是可以更新的

### ISSUE THREAD

**Issue by switchy1** [FelisCatus/SwitchyOmega#1068]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by FelisCatus** [comment]
所以我猜这个大概是代理服务器或者网络问题？没什么道理不能更新啊……

如果网络环境如此，可以在自动切换模式添加规则，让更新 components 的 URL 不走代理。
