### ISSUE TITLE
Auto Switch, I can't choose the [System Proxy]

### ISSUE THREAD

**Issue by linmonsv** [FelisCatus/SwitchyOmega#1069]
HALLO, 

Maybe it's not a problem, 

but if i can choose the [System Proxy] to the Rule list rules, 

I can use more proxy software.

SwitchyOmega 2.4.6
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by celeron533** [comment]
PAC机能限制，无法在里面写上系统代理
#170

**Comment by FelisCatus** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#why-cant-i-select-system-proxy-in-switch-profiles
