### ISSUE TITLE
状态图标没原来好，难看又难懂，不一目了然

### ISSUE THREAD

**Issue by vvaa** [FelisCatus/SwitchyOmega#107]
SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
大家觉得 #189 的方案怎么样？我反正是觉得挺好的，至少思路很不错。

不过单独使用时的单圆环我觉得挺好的，不想改。所以我的建议可能是自动切换下，单圆环外面加点背景颜色。

**Comment by phyng** [comment]
#189  作者辛苦了，我的想法是，以代理为中心，不要考虑各种情景模式、自动切换
* 直接连接可以设置一种纯色
* 每种代理可以设置一种纯色
* 至于是否是自动切换这个没必要体现，当前网页使用什么代理就显示什么颜色

**Comment by deepsea887** [comment]
![Uploading ezm150115.mp3 . . .]()
xdfsf

**Comment by subgb** [comment]
楼上说的第3点，我又想了想，自动切换的图示应该就是大家困惑的关键点。至于单独使用时是否圆环应该不是重点。

如果我们浏览任何网站都很流畅，肯定是不会去关注代理图标是什么。那什么时候会去关注图标？
设想以下场景：

地址栏输入www.baidu.com，过了半分钟才加载完。
这时我们肯定会想，这么慢是不是走了代理？于是查看图标来验证这个猜测。
此时有以下几种情况：
  * 图标是直连的颜色。
  说明没有开代理，心想：是不是网络有什么问题，要不重启个路由器试试。
  * 图标是某一种颜色圆环（或者实心圆/圆角矩形/地球图标等）。
  于是我们意识到正在用这个颜色的代理，那当然慢了，关掉就好了嘛。
  * 图标类似 ![222](https://cloud.githubusercontent.com/assets/612446/5791685/f118ebe0-9f21-11e4-95ac-f220e0721425.PNG) 这种。
    一般反应是这样：靠！这什么鬼？两种颜色分别啥意思？好像是说自动切换吧。不管了，肯定是在用代理的意思，我关掉吧。
  *  图标类似 ![3333](https://cloud.githubusercontent.com/assets/612446/5791697/94b048c0-9f22-11e4-9dda-b36d20da877e.PNG) 这种。
    反应：这又什么鬼？又两种颜色？到底有代理还是没代理？

反过来的情况（比如输入被墙的google.com时）也是一样的。
查看图标的首要目的是获知当前有无代理生效，如果生效那么这个生效的代理是不是我们预期的，以此决定我们下一步需不需要去切换一个情景模式，至于是不是自动切换并不是影响我们下一步的动作。

因此为了减少困惑，减弱自动切换的图示是有必要的。而最重要的是一定要能非常明确的传递出“有代理”和“无代理”两种状态（无代理包括直接模式和自动切换下的直接），让人不需要任何思索。

目前用灰色表示无代理仍然不够直观。表示“没有”这种概念，白色或灰色都不够直观，透明才是最恰当的。试想没有代理生效时，图标那里什么都不显示，彻底和浏览器背景融为一体。。。当然这样太没存在感了，比较合适的做法是只有边框/轮廓线，而当有代理时，内部填充上颜色。

那么怎么表示自动切换？目前使用的填充了圆心的圆环形式 ![3333](https://cloud.githubusercontent.com/assets/612446/5791697/94b048c0-9f22-11e4-9dda-b36d20da877e.PNG) ，在表达“没有代理生效”这种状态时很让人困惑，此时外圈的灰色圆环很难传递“没有”这个概念，就算把外圈弄成透明的，但此时，人们的注意力会被圆心的颜色所吸引，同样很难与”没有“这个概念等同起来。
我的想法是可以用角标的形式，主体颜色仍是当前生产的代理颜色，如下：
![4444](https://cloud.githubusercontent.com/assets/612446/5791843/251a824c-9f30-11e4-8b24-156c5a47cd5a.PNG)

另外我觉得弹出菜单中那个地球图标也挺好的（好像旧版图标的扁平化吧），如果使用地球图标，可以作以下的修改：
* 直连模式：只保留外圈和大陆的轮廓线，不对大陆填充灰色。
* 代理模式：就像菜单中的图标那样对大陆填色。
* 自动切换：给地球加上类似土星环的色带，像IE图标那样。

**Comment by FelisCatus** [comment]
按照 @subgb 的思路做的，也许可以行？（蓝色自动切换、当前页面为直连）

![omega_quad](https://cloud.githubusercontent.com/assets/912649/5791944/729e4044-9f35-11e4-9e0f-09684c9182a1.png)

**Comment by gepcel** [comment]
顶一下。
本来想来提个建议，现在的图标颜色区分不直观（让人一看不明白各代表什么意思），需要自己测试好几种环境和网站才能测试出来。
另外，现在的颜色对比很不明显，尤其在自动切换模式下，走代理和不走代理一眼看去，区别不明显，仔细看才能看出来区别，又经常搞不清这是代表走代理啊还是不走代理啊？

总结：

    1. 颜色的区分不明显，得仔细看。
    2. 各种模式的含义不直观，得好好记才记得住。

**Comment by FelisCatus** [comment]
最近上传的那个 1/4 圆环的图标方案如何？大家给点反馈啊……

这下我也不知道该怎么做好了……

**Comment by phyng** [comment]
1/4不错，中间放什么呢

**Comment by qq50666** [comment]
1/4圆环？个人感觉反而还不如之前的好看易懂了……青菜萝卜各有所爱啊

在 2015年1月27日 下午4:35，FelisCatus <notifications@github.com>写道：

**Comment by learningendless** [comment]
图标倒是小细节，现在遇到购买力邮箱里显示不出来“归档” “列为垃圾邮件”等按钮图标了，这是为什么啊

在 2015年1月27日 下午10:51，石头 <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
@phyng 中间就那么空着吧，感觉还是单层圆环好看。本来图标就那么挤……之前那种设计难做啊

@qq50666 感觉换一次图标的代价是比较大……之前好不容易建立的识别习惯，就那么突然改变了，总会有人有意见。不过目前的情况，换回 Sharp 的图标是没有可能了。我计划把现在使用的图标和这次讨论中新设计的图标作为两种方案，可供选择。老用户默认不变，但可以去设置里手动改。至于新用户要不要默认用新方案，就看大家的反响如何了。

说起来 @subgb 呢？有机会的话也来发表下见解如何？

P.S.
@learningendless 虽然和这里的主题无关，不过我还是要说，这个问题最好在查看请求的URL以后，去 GFW List 那边反馈。

**Comment by howareyouo** [comment]
还是比较喜欢原来的界面, 简洁大方, 现在的UI看起来高大上其实功能也没多大差别呀,
新用户一看都吓跑了...

**Comment by Tback1** [comment]
我觉得问题不在图标，图标本身很容易理解。反而是点击后的菜单。。。。真不太方便，很多切换设置还是得进去手工调整。

**Comment by FelisCatus** [comment]
@Tback1 可以另外开一个 issue 谈谈如何改进弹出菜单。

**Comment by zzp0** [comment]
我觉得如果站在普通用户角度看，平时上网我只想知道当前网页是否被墙，至于其它都是技术细节，所以就两种状态（开/关），保持外圆环颜色不变（灰色）：1）如果没有墙，中间圆与外环颜色一致，表示关；2）如果被墙，中间圆为绿色，这样好像电源指示灯的颜色，表示开。我不太关心当前使用的是什么 profile。不知大家觉得如何？

**Comment by hcwhan** [comment]
我觉得
1.自动切换 :                      内圈白                    外圈  无适配规则为灰  有适配规则为代理设置色                (意思是内圈白直连为主要 外圈为根据规则连接)
2. 强制某代理模式:           内外圈全为代理设置色  (意思是全走某代理)
3直接连接(无代理):          内外圈全为白                 (意思是全直连)
4系统代理:                       内圈黑                  外圈白  (意思是内圈黑 为浏览器外来控制规则)
白色意味直接连接   有色代表代理

**Comment by hcwhan** [comment]
简单直接

**Comment by hcwhan** [comment]
简单 直接 易懂 双色代表规则适配 单色代表 某种代理

**Comment by zzp0** [comment]
你说的这些很好，也许是我平时使用环境比较简单，没那么多需求。这让我想起一些程序的设置界面，例如 VLC 默认只显示少数设置选项，点击 Show All 显示全部选项，也许没有可比性，权当瞎说;-)

**Comment by AzureDR** [comment]
189的方案看起来很好
其实我是来问，右下角的角标“1”是什么意思的

**Comment by diemus** [comment]
赞同@subgb 。平时只关心代理到底生没生效，不关心使得是什么模式。因为模式一般都是自动切换。
所以无需关心。之所以关心到底代理是什么颜色只是想知道这个网站这么半天打不开是不是因为被墙了却没有加入list。然后换成全部走代理试试，如果是因为墙了则加入规则。所以，我觉得还是原来的灰色和蓝色对比就好。至于图案倒是次要。

火狐那个的真心很难看。

**Comment by gameboy709494** [comment]
自动切换图标“圈圈里面带个字幕‘A’，其他颜色是白色”，意思是Auto。灰色的A代表自动模式下不走代理；绿色代表自动模式下走代理。
直接连接则是“一个灰色的圈圈，里面也是 用灰色填充”
全局代理就是“一个绿色的圈圈，里面也是绿色的填充”

这样不好么？

**Comment by mengqingzhong** [comment]
跪求直接使用proxy switchysharp的图标，就因为图标的问题，一直没有更新。proxy switchysharp的图标设计的太好了。

**Comment by mengqingzhong** [comment]
刚刚升级成了SwitchyOmega，实在受不了图标 :( 
又降级回去了。

**Comment by FelisCatus** [comment]
Closing in favor of #1034.
