### ISSUE TITLE
能做到页面切换场景时，其他标签页的场景不变吗？

### ISSUE THREAD

**Issue by gamexy** [FelisCatus/SwitchyOmega#1071]
能做到页面切换场景时，其他标签页的场景不变吗？

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36

**Comment by FelisCatus** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E6%8C%89%E7%85%A7%E7%AA%97%E5%8F%A3%E6%88%96%E8%80%85%E6%A0%87%E7%AD%BE%E9%A1%B5%E6%9D%A5%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E5%90%97
