### ISSUE TITLE
使用SwitchyOmega重启电脑后浏览器只能访问部分网站

### ISSUE THREAD

**Issue by thirtyjin** [FelisCatus/SwitchyOmega#1072]
之前进行系统升级后重启出现过两次这样的情况（恢复系统解决了），现在Mac book Pro 只是重启了一次后，又出现只能打开个别网页（baidu,apple等），其他网站都无法访问（都是些主流网站不需要翻墙的站点）的情况，在尝试启用 SwitchyOmega 并打开代理后，之前打不开的页面才可以被打开；一旦关闭代理，浏览器就只能上个别的网站（baidu,apple等）。

现在基本上还在进行问题排查，但是高度怀疑会和SwitchyOmega有关。

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by celeron533** [comment]
请问你用的是什么代理服务器

**Comment by thirtyjin** [comment]
连接公司 VPN 后，使用的公司提供的代理；现在只能在SwitchyOmega打开并且走代理的时候正常访问网页，关闭SwitchyOmega 后本地连接，就不能正常访问了，好崩溃

**Comment by celeron533** [comment]
推测：
有些公司的内网必须使用自己的代理服务器才能上网。当你连上了公司后，你也成为了内网的一员，如果你的家用系统没有设置过代理所以无法上网。
你提到的“关闭SwitchyOmega”是什么意思？

**Comment by thirtyjin** [comment]
还是没有确定问题所在，怀疑还是MacOS 自己的问题，通过重新修复系统才得以解决
