### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by xkxf1293** [FelisCatus/SwitchyOmega#1073]
npm ERR! Linux 4.4.0-43-Microsoft
npm ERR! argv "/root/.nvm/versions/node/v7.9.0/bin/node" "/root/.nvm/versions/node/v7.9.0/bin/npm" "run" "deps"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! omega-build@0.0.1 deps: `npm install && (cd ../omega-pac && npm install) && (cd ../omega-target && npm install) && (cd ../omega-web && npm install && bower install) && (cd ../omega-target-chromium-extension/ && npm install)`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omega-build@0.0.1 deps script 'npm install && (cd ../omega-pac && npm install) && (cd ../omega-target && npm install) && (cd ../omega-web && npm install && bower install) && (cd ../omega-target-chromium-extension/ && npm install)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the omega-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && (cd ../omega-pac && npm install) && (cd ../omega-target && npm install) && (cd ../omega-web && npm install && bower install) && (cd ../omega-target-chromium-extension/ && npm install)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs omega-build
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls omega-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-08T13_01_25_602Z-debug.log

请问如何解决呢？

**Comment by xkxf1293** [comment]
这是 debug.log 的内容：

0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v7.9.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v7.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deps' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'predeps', 'deps', 'postdeps' ]
5 info lifecycle omega-build@0.0.1~predeps: omega-build@0.0.1
6 silly lifecycle omega-build@0.0.1~predeps: no script for predeps, continuing
7 info lifecycle omega-build@0.0.1~deps: omega-build@0.0.1
8 verbose lifecycle omega-build@0.0.1~deps: unsafe-perm in lifecycle true

**Comment by celeron533** [comment]
呃，贴代码或者日志的时候最好使用code标签，否则里面的内容很容易被当成格式解析掉
![image](https://cloud.githubusercontent.com/assets/3608762/25831755/cc1bcd26-3498-11e7-8198-da2513fb2379.png)

**Comment by xkxf1293** [comment]
node的版本是 v7.9.0

**Comment by FelisCatus** [comment]
直接在那个项目下运行 `npm install && (cd ../omega-pac && npm install) && (cd ../omega-target && npm install) && (cd ../omega-web && npm install && bower install) && (cd ../omega-target-chromium-extension/ && npm install)` 试试看？另外，请提供完整输出，上面的输出和日志好像少了一些部分。 `debug.log` 文件可以直接拖动到这里上传。

此外，注意到 `Linux 4.4.0-43-Microsoft`, 请问是在 Windows 上运行 Linux 兼容层吗？如果是的话请注意权限问题， `npm link` 很可能需要 root 或者管理员权限。
