### ISSUE TITLE
内存泄漏？

### ISSUE THREAD

**Issue by Devil-Cong** [FelisCatus/SwitchyOmega#1074]
你好，
![wx20170509-104410](https://cloud.githubusercontent.com/assets/13516290/25833526/8e56b0c6-34a4-11e7-93c0-8d9bf85d83c5.png)
我在macos 10.12.4 下，一点击SwitchyOmega这个小图标，系统就立马进入锁屏状态。然后输入开机密码进去系统，发现系统程序都重新启动了，像刚开机的样子。请问这个是不是内存泄漏问题？

**Comment by celeron533** [comment]
好神奇，一般这个东西都是运行在浏览器的沙盒中的。

**Comment by FelisCatus** [comment]
这好神奇啊，假如 SwitchyOmega 能做到崩溃掉系统或者锁屏，那岂不是所有网站/扩展都能做到这个了？

通常这些代码都是运行在沙盒中的，用太多内存只会导致 Chrome 关掉那个标签页，不会有这种情况。总之我从没见过这种情况，估计是 Chrome 或者 OS X 的 bug, 等更新吧……
