### ISSUE TITLE
腾讯网站不能显示二维码和验证码

### ISSUE THREAD

**Issue by qsxmq** [FelisCatus/SwitchyOmega#1075]
http://kf.qq.com/faq/161220zIVzmy161220BruuiQ.html
直接连接打开上述网页的时候，点击登录，刷不出二维码
![image](https://cloud.githubusercontent.com/assets/23392122/25879483/82561f9e-3564-11e7-839b-c1f92ca94431.png)
使用以下方法可以正常刷新：
1、使用GoAgent方式代理。
2、从Chrome移除SwitchyOmega。
不知道是不是SwitchyOmega的bug。
谢谢。

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36

**Comment by celeron533** [comment]
你的SwitchyOmega里可能配置了不正确的规则。试试看如果在SwitchyOmega中选择“系统代理”会恢复吗？

**Comment by FelisCatus** [comment]
这种情况无非就是本来应该使用代理的，结果配置问题没有使用代理。或者是本来不应该使用代理的，结果配置问题使用了代理。

如果您在中国大陆区域内，二维码的地址应该也是直接连接即可访问，所以检查下二维码的网址和自动切换里的规则，看看是不是错误地配置成了代理服务器。比如说，可以在图片上右键选择新窗口打开图片，然后此时地址栏里显示的 URL 就是图片的 URL, SwitchyOmega 的图标颜色可以说明是否使用了代理。鼠标在SwitchyOmega 图标上悬停可以显示具体哪些规则导致了现在的结果。
