### ISSUE TITLE
问个入门问题，这东西下来后，怎么安装？

### ISSUE THREAD

**Issue by hongkonghot** [FelisCatus/SwitchyOmega#1076]
问个入门问题，这东西下来后，怎么安装？

**Comment by lifei6671** [comment]
1、从chrome插件商城安装，
2、chrome开启开发者模式，导入。

**Comment by hongkonghot** [comment]
这个方法我会，但这里下载的压缩文件怎么安装?

**Comment by lifei6671** [comment]
从release中下载ctx文件，导入到Chrome就行

**Comment by hongkonghot** [comment]
请教，我下载的是SwitchyOmega-master.zip ，解压后没有找到任何 ctx文件，如果都在google应用商店安装，那这里的下载有什么用？

**Comment by wenliyang** [comment]
@hongkonghot 你下载的是源代码
下载页第一项就是 SwitchyOmega.crx，不明白你是怎么回事
https://github.com/FelisCatus/SwitchyOmega/releases

**Comment by celeron533** [comment]
网上一搜一大把。。。
https://jingyan.baidu.com/article/8ebacdf029283549f65cd53c.html

**Comment by hongkonghot** [comment]
楼上发的地址下载后会装，但 https://github.com/FelisCatus/SwitchyOmega 下载的是zip的压缩文件，没有crx文件。这个zip怎么为使用？
