### ISSUE TITLE
sock5方式没有用户名密码验证。。。。。。。

### ISSUE THREAD

**Issue by zzzili** [FelisCatus/SwitchyOmega#1077]
sock5方式没有用户名密码验证。。。。。。。

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by celeron533** [comment]
Chrome 目前不支持sock5的认证
https://github.com/FelisCatus/SwitchyOmega/issues/178#issuecomment-69450120

**Comment by Wows233** [comment]
可以使用privoxy新建一个本地代理
