### ISSUE TITLE
chromebook浏览器无法翻墙（安卓应用可通过ss翻墙）

### ISSUE THREAD

**Issue by pdlwf** [FelisCatus/SwitchyOmega#1078]
问题
Chromebook浏览器无法通过swtichyomega翻墙
环境：
1. samsung chromebook plus:Version 57.0.2987.146  Firmware Google_Kevin.8785.157.0
2. 自建vps翻墙（验证是可翻墙，没有问题的）
详情：
1. 安卓应用可以正常翻墙，但浏览器就不行
2. 安卓ss, 后台开启，switchyomega 情景模式+autoswitch模式，gfwlist。fail
3. Chrome store ss, 后台开启，switchyomega 情景模式+autoswitch模式，gfwlist。fail
3. 路由器ss翻墙，使用系统连接OK，但切换成autoswitch就不行了

**Comment by Wows233** [comment]
确定你的规则列表规则使用代理
![image](https://cloud.githubusercontent.com/assets/24245520/26034599/b67bb9e2-38f1-11e7-9d00-0c134de4090b.png)

**Comment by pdlwf** [comment]
![image](https://cloud.githubusercontent.com/assets/5444996/26043019/a2d6e256-396c-11e7-8140-50b3f8eefa5c.png)
![image](https://cloud.githubusercontent.com/assets/5444996/26043032/c737171a-396c-11e7-8114-e96447136a0e.png)
设置分别如上，代理端口因为ss配的是1234的原因，这里也填写的1234

**Comment by Wows233** [comment]
auto switch 的配置页面呢？

**Comment by pdlwf** [comment]
![image](https://cloud.githubusercontent.com/assets/5444996/26043371/29a8f934-396f-11e7-9a24-61705b5fab3a.png)
如图

**Comment by Wows233** [comment]
如果有问题就用SS的pac代理吧。。设置成系统代理。

**Comment by pdlwf** [comment]
PC上面这样来操作没问题，但是chrombook上面ss没法选pac代理。。
不过刚刚试了一下把端口改成1080，居然可以了。
Chromebook上面昨天一直设成1080不行的（很奇怪的是我ss服务器上面设置的local port是1234啊），这个就很尴尬了。。。。

**Comment by pdlwf** [comment]
hi Wows233
刚试了下在chromebook上面，将端口改成1080，还是不行。
这个还有可能是什么原因？

**Comment by FelisCatus** [comment]
可能是协议问题， Chromebook 上的 SS 是不是 `HTTP` 类型代理，而不是 `SOCKS5`? 试试看那个。

此外，代理的端口是SS客户端的端口，而不是SS服务器的端口。这个很复杂我这里不多解释了，但只和SS客户端的配置有关。默认似乎是 `1080`. 作为参考：

浏览器 -> (SS客户端端口， HTTP/SOCKS5 代理协议) -> SS 客户端 -> (SS服务端端口， SS 自有通讯协议，不是代理协议) -> SS 服务端

**Comment by pdlwf** [comment]
＠FelisCatus
在Chromebooks上采用chromestroe版本ss的情况下，我试了如下几种设置
1. ss客户端设置local_port为1234（与服务器端的local_port一致）
1.1 switchyomega设置socks5/http 127.0.0.1 端口1080/1234 都不行
2. ss客户端设置local_port为1080（与服务器端的local_port - 1234不一致）
2.1 switchyomega设置socks5/http 127.0.0.1 端口1080/1234 都不行
不过我在PC上设置local_port 1080, switchyomega也为1080， 服务器端仍为1234，是可以的。与你上面说的吻合。

所以问题，基本上是能锁定在switchyomega的设置上，很有可能就是端口号或者socks5的问题。
不知道有没有哪位懂行的，可以再帮助看 一下。

**Comment by FelisCatus** [comment]
是这个吗？ https://github.com/shadowsocks/shadowsocks-chromeapp
看代码似乎是 SOCKS5, local_port. 不过说不定 Chromebook 的操作系统对于通信或者端口有限制？

**Comment by KJNKJNKJN** [comment]
请问代理服务器的,固定为127.0.0.1 还是看自己买的账号是多少啊

**Comment by Wows233** [comment]
固定的，也可以设置其他端口，但是IP都不变

**Comment by zxyShawn** [comment]
请问这个问题解决了吗？

**Comment by Newt0ng** [comment]
同是这个问题，浏览器不能翻墙，安卓应用可以，求大神赐教

**Comment by zxyShawn** [comment]
在chrome商店里下ss给浏览器翻

**Comment by lstk1898** [comment]
可能原因是chrome os操作系统，和Google play的安卓应用，走的是不同的代理，并不能互相通用。

**Comment by shuishengmu** [comment]
@FelisCatus  @Wows233 @pdlwf 同样的问题  pixelbook 两个翻墙工具，lantern和ss，都可以实用google play里面的安卓应用，商店下载的chrome浏览器也可以实用，就是自带的chrome不能翻墙，可是别人给我一个天行vpn，我通过win10分享wifi（通过猎豹wifi分享）后浏览器可以翻，但是我自己的lantern、ss通过猎豹wifi分享的确不可以。  哪里设置不对？

**Comment by Martin1024** [comment]
我的是浏览器可以翻，但是安卓应用不能翻，用的是omega+绿色的ss，两者的local_port设置的都是1080。

**Comment by Newt0ng** [comment]
成功解决CB安卓应用能翻浏览器不能翻的问题，原来是我switchy代理服务器填错了，应该是填本地ip,不是SS的服务器地址,搞这么久终于发现了

**Comment by saradk** [comment]
on your chromebook, go to chrome://flags/#arc-vpn   , it will use android VPN as system VPN
flag里面打开 arc-vpn， 即可使用安卓vpn来走全局，最新版安卓ss里面，确认模式是vpn模式
