### ISSUE TITLE
让自动切换模式中默认情景模式可以选择系统代理

### ISSUE THREAD

**Issue by imjustfly** [FelisCatus/SwitchyOmega#1079]
有一种需求，在自动切换的模式中，没有匹配到任何规则的可以使用系统代理。目前唯独系统代理不能选，不知道是基于什么考虑。

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by celeron533** [comment]
由于PAC限制，此功能无法实现。
参见 #170

**Comment by FelisCatus** [comment]
[参见 FAQ.](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E4%B8%AD%E4%B8%8D%E8%83%BD%E9%80%89%E6%8B%A9%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86)
