### ISSUE TITLE
升级之前代理正常使用，升级之后所有墙外网上都上不去了，提示NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by hokerffb** [FelisCatus/SwitchyOmega#108]
Proxy SwitchyOmega 2.2.8
版本 38.0.2125.111 m

升级之前代理正常使用，升级之后所有墙外网上都上不去了。
配置已经自动导入完成，看起来没什么问题。
我去chrome设置里禁用了Proxy SwitchySharp，只开SwitchyOmega，发现不管设置为自动切换还是系统代理，都无法再访问任何墙外的网站，提示：

```
您的连接不是私密连接

攻击者可能会试图从docs.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。

重新加载高级
```

展开的详细错误信息：

```
您的连接不是私密连接

攻击者可能会试图从www.google.com窃取您的信息（例如：密码、通讯内容或信用卡信息）。

重新加载隐藏高级设置
www.google.com通常使用加密技术来保护您的信息。Chrome此次尝试连接到www.google.com时，此网站返回了异常的错误凭据。这可能是因为有攻击程序在试图冒充www.google.com，或Wi-Fi登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为Chrome尚未进行任何数据交换便停止了连接。

您目前无法访问www.google.com，因为此网站使用了HSTS。网络错误和攻击通常是暂时的，因此，此网页稍后可能会恢复正常。

NET::ERR_CERT_AUTHORITY_INVALID
```

尝试禁用SwitchyOmega，启用SwitchySharp，一切恢复正常，应该有bug

**Comment by FelisCatus** [comment]
网络问题与 SwitchySharp / SwitchyOmega 无关。如果您的网络情况无法正常连接 google ，建议在自动切换中加入 `*.google.com` 使用代理访问。
