### ISSUE TITLE
启用switchyomega后，https://sneakernews.com  网站无法翻页

### ISSUE THREAD

**Issue by wentao409** [FelisCatus/SwitchyOmega#1080]
启用switchyomega后，https://sneakernews.com  网站无法翻页

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或者网络问题，与 SwitchyOmega 无关。
