### ISSUE TITLE
请问如何设置 chnroute？

### ISSUE THREAD

**Issue by pexcn** [FelisCatus/SwitchyOmega#1081]
我想 chnroute 列表内的地址直连，chnroute 列表外的地址走代理。
就是国内直连，国外走代理，请问能实现吗？

**Comment by FelisCatus** [comment]
见[常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#switchyomega-%E8%83%BD%E6%94%AF%E6%8C%81%E8%B7%AF%E7%94%B1%E8%A1%A8%E5%9F%BA%E4%BA%8E-ip-%E6%88%96%E8%80%85%E5%9C%B0%E7%90%86%E4%BD%8D%E7%BD%AE%E7%9A%84%E5%88%87%E6%8D%A2%E5%90%97)。
