### ISSUE TITLE
搜狗浏览器最新版本  不能加载设置界面

### ISSUE THREAD

**Issue by oosaber** [FelisCatus/SwitchyOmega#1082]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Comment by FelisCatus** [comment]
首先，搜狗浏览器不在支持范围内，如果是小的兼容问题可能我会顺手修一下，但假如是搜狗浏览器本身的问题那我就没办法了。

试试看打开设置界面然后按 F12 打开开发者工具，查看 Console (控制台) 中是否有错误信息。如果有的话请复制到这里。

**Comment by zhuangdx** [comment]
jquery.min.js:3 The specified value "!" does not conform to the required format.  The format is "#rrggbb" where rr, gg, bb are two-digit hexadecimal numbers.

angular.min.js:123 Possibly unhandled rejection: {"message":"The message port closed before a reponse was received."} undefined
