### ISSUE TITLE
请问一下能否通过pac方式支持edge浏览器

### ISSUE THREAD

**Issue by techstay** [FelisCatus/SwitchyOmega#1083]
edge浏览器好像没有提供代理API，所以无法将这个扩展移植到edge。我想了一下，能不能本地部署一个可以增删查改pac的服务器，将代理设置为这个pac地址。然后在edge中用扩展将要设置代理的网址发送给这个服务器，来达到在edge中设置代理的目的？

请问一下这种方式是否可行？开发者能否开发这样的功能？

**Comment by FelisCatus** [comment]
这个比较复杂，最好用插件的形式做。

不过理论上至少是可行的，就是比较折腾。扩展要开服务器应该是需要本地代码了吧…… SwitchyOmega 目前还不想折腾本地代码，因为坑死了……

**Comment by techstay** [comment]
我觉得没必要非得用本地代码吧，我感觉做一个单独的服务器完全可以接受，插件直接发请求就可以了

**Comment by celeron533** [comment]
用户需要同时安装插件和服务器两样东西。抛开可能遇到的技术困难，由于服务器脱离了浏览器的沙箱环境，更容易产生安全问题。
> 我觉得没必要非得用本地代码吧，我感觉做一个单独的服务器完全可以接受，插件直接发请求就可以了

**Comment by techstay** [comment]
好像确实是个问题，我只顾着方便，忘了这茬了

**Comment by gggccc44** [comment]
你直接XX-NET的pac不行么？

**Comment by techstay** [comment]
可以倒是可以，不过那pac好像有点问题。我用的是shadowsocks-windows 那个程序的pac，但是那玩意好像有点问题，用edge浏览器上github的时候静态资源加载不全，页面整个都乱了。而且万一碰上不能访问的网址，也不能随便加入代理。所以我才想能不能用点别的

**Comment by celeron533** [comment]
@techstay shadowsocks的内嵌pac文件是很久以前的，首次使用建议更新一下

**Comment by techstay** [comment]
奇了怪了，以前我更新过结果还是有问题，今天又更新了一下edge浏览器居然一切正常了

**Comment by celeron533** [comment]
PAC文件可能被浏览器缓存了

**Comment by techstay** [comment]
有时候shadowsocks自带pac还是不太方便，我试了试并不能在edge里面qq快速登录……
