### ISSUE TITLE
用着用着就被莫名禁用

### ISSUE THREAD

**Issue by Bodil-X** [FelisCatus/SwitchyOmega#1084]
如标题，不知道为什么，用着用着总会自己消失，一看是被禁用了，需要手动开启

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by FelisCatus** [comment]
Chrome 可能会禁用不是谷歌应用商店下载的扩展，所以推荐在 [商店安装](https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif).

此外，也有可能是其他扩展禁用了 SwitchyOmega. 请检查其他扩展是否有“管理扩展”的权限，如果有的话试试看禁用那些扩展。
