### ISSUE TITLE
自动代理异常

### ISSUE THREAD

**Issue by lzplzp001** [FelisCatus/SwitchyOmega#1085]
最近很奇怪，明明google.com是走代理的，但是实际访问的时候，还是提示不能访问。
字不够？字不够？字不够？字不够？

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3100.0 Safari/537.36

**Comment by gggccc44** [comment]
我怀疑是不是墙或者谷歌的问题，我也反应过，自动的时候很容易卡住，完全代理就没问题，尤其是扩展商店

不过奇怪是同属于谷歌的youtube正常

**Comment by FelisCatus** [comment]
可能是页面内的资源没有走代理导致访问异常。这种情况下扩展图标上会出现数字显示，点击选择“未加载资源”来查看并添加规则。

顺便，这边并没有字数限制，请不要凑字数。
