### ISSUE TITLE
无法切换系统代理

### ISSUE THREAD

**Issue by Geolage** [FelisCatus/SwitchyOmega#1087]
总是提示，注意：其他应用正在控制当前代理（PAC脚本）。
但是PAC已经被我删除了啊，插件我也是重装过的，为什么还是一样？

**Comment by FelisCatus** [comment]
切换到系统代理的时候，相当于放弃控制，这种时候其他扩展可以控制代理设置。

请检查是否有其他代理扩展，或者有些去广告扩展等也会使用 PAC 的形式。
