### ISSUE TITLE
Feature request - Notes for conditions

### ISSUE THREAD

**Issue by zappeee** [FelisCatus/SwitchyOmega#1089]
Would be great if you could leave some notes at every condition to keep track of what's what.

**Comment by FelisCatus** [comment]
noted.

**Comment by celeron533** [comment]
Link to #993

**Comment by zappeee** [comment]
@celeron533, I see, my Chinese is a bit rusty so I didn't see that one :)

**Comment by celeron533** [comment]
@zappeee , no worries, just linked for track

**Comment by FelisCatus** [comment]
Proposed UI:

For existing users, a small button with a note icon will be shown. If you do not add any notes, then the table won't be too wide and still looks good on low resolution.

![image](https://user-images.githubusercontent.com/912649/29145005-22e95654-7d29-11e7-9838-b522ea8937b8.png)

If you click on the button, or import a Profile with notes, a new column will be shown where you can put in notes as you wish. The table will become wider (or the columns will be come narrower on low resolution screens.) The new feature will be enabled for the entire profile and you can edit any condition(s) you want.

![image](https://user-images.githubusercontent.com/912649/29144943-eda900c0-7d28-11e7-86c5-91c134f2afd9.png)

Let me know about how you feel about the proposed UI and I'll move on to implementation if everything looks good.

P.S. If you edit the source code, the notes will still be kept there so you don't lose anything when you switch back and forth. If you export and import to earlier SwitchyOmega versions, then the notes can't be shown of course.

![image](https://user-images.githubusercontent.com/912649/29145259-66e422fc-7d2a-11e7-9430-25b84e680107.png)

**Comment by zappeee** [comment]
@FelisCatus,
Sounds like a great solution!

**Comment by FelisCatus** [comment]
A release is coming soon with the new feature.

I've decided to go with the following rule list format for compatibility:

```ini
[SwitchyOmega Conditions]
@with result

@note some random notes here...
example.com +test
UrlRegex: dddd +test
@note Another Note!
*.example.com +test

* +direct

```

If you copy and paste the rule lists to earlier SwitchyOmega versions, it won't pick up the notes but it will process everything else normally.

**Comment by FelisCatus** [comment]
v2.5.3 published on Chrome Web Store. Firefox version awaiting review on AMO.

**Comment by FelisCatus** [comment]
Firefox version published.

**Comment by zappeee** [comment]
Thank you very much!
