### ISSUE TITLE
能否增加一个全局代理的选项？

### ISSUE THREAD

**Issue by xiaozixun** [FelisCatus/SwitchyOmega#1091]
我还有其他的软件需要联网，不能所有软件都走代理，否则会造成流量不足。

**Comment by celeron533** [comment]
SwitchyOmega是Chrome浏览器插件，所以它的作用范围仅限于浏览器本身。

**Comment by xiaozixun** [comment]
@celeron533 
我的意思是希望能像firefox的autoproxy一样，用“全局代理”替换掉“直接代理”。

**Comment by czmecho** [comment]
@xiaozixun 你选proxy不就是针对浏览器代理吗？

浏览器上用什么“全局代理”？全局代理指的是电脑上，不用乱用，范围不一样。

**Comment by xiaozixun** [comment]
@czmecho 
firefox的autoproxy里“全局代理”选项可以直接全部代理所有网页；而在SwitchyOmega里我想要让全部网页都走代理，却只能选择“直接代理”，然后点上翻墙工具的“全局代理”选项，偏偏这样会造成电脑上所有需要网络连接的请求都会走代理，造成大量流量的白白消耗。
我不想这样，所以希望作者能修改下SwitchyOmega而发出这个Issues。

**Comment by celeron533** [comment]
@xiaozixun , 请直接选定你要用的代理即可
此时就是你所谓的全局代理
![image](https://user-images.githubusercontent.com/3608762/26883160-eaed4494-4bce-11e7-81b3-bd5262ca2cd2.png)
