### ISSUE TITLE
正则表达式前面有个红色感叹号是什么原因

### ISSUE THREAD

**Issue by zhenhappy** [FelisCatus/SwitchyOmega#1093]
这个是正则的规则
UrlRegex: ^http:\/\/[^\/]+\/crossdomain\.xml +ADfree

**Comment by FelisCatus** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-%E5%AE%8C%E6%95%B4%E7%BD%91%E5%9D%80%E9%99%90%E5%88%B6
