### ISSUE TITLE
Update angular to 1.6.4

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1094]
Seems like AMO is only allowing the latest version of Angular. Let's see if we can update to 1.6.4.

**Comment by xiaozixun** [comment]
我的帖子是被删了吗？
我想要个想firefox扩展——autoproxy中的“全局代理”一样的功能。

**Comment by FelisCatus** [comment]
您之前发的 Issue 仍然在那里，并没有被删除。 https://github.com/FelisCatus/SwitchyOmega/issues/1091
其他人已经对您的问题进行了解答，如有疑问请继续在那边回复。请不要在无关的 Issue 中回复。

**Comment by FelisCatus** [comment]
WIP in #1030.
