### ISSUE TITLE
Put add condition button at top of the options page

### ISSUE THREAD

**Issue by waghcwb** [FelisCatus/SwitchyOmega#1095]
When the user have too many rules on the options page, he need to scroll down to see the add condition button.

It'll be better if the button is placed at the top of the page, so he can add a new condition faster.

**Comment by FelisCatus** [comment]
I will consider this.

In the meantime, feel free to click on the Duplicate button and change the first one.

**Comment by FelisCatus** [comment]
Thought about this, and decided not to do this for the following reasons.

* Conditions can be added through the popup menu and it's usually the fastest option. It does place the condition on the top of the list.
* Scrolling down is a little bit inconvenient but isn't too convenient to justify moving the button.
* Similar arguments have been made for inserting conditions in the middle but then we've decided that the users can just use the clone button.

Therefore, I'm closing this issue as won't fix. For users who wants to insert a condition on the top, please feel free to use the Clone button besides the first condition and change the top one. I will point anyone asking the same thing to the Clone button. If more people complain about this, then we shall reopen the issue and reconsider.
