### ISSUE TITLE
将代理服务器设为[::1]时，会出现不走代理的情况

### ISSUE THREAD

**Issue by lslqtz** [FelisCatus/SwitchyOmega#1097]
设为::1的话直接报无法连接，设为[::1]的话不走代理。
从Network看到的连接地址不是[::1]，而是源站的IPv4地址。
不清楚其它IPv6地址是不是这样。

**Comment by lslqtz** [comment]
![](https://ooo.0o0.ooo/2017/06/11/593c78d4cf198.png)

**Comment by FelisCatus** [comment]
`::1` 是正确的写法。 IPv6 地址加方括号的这种特殊写法基本上只在 URL 里会用到。

我这边刚测试了， `::1` 可用。请特别注意，能工作的前提是代理服务器本身支持 IPv6 并且监听 IPv6 连接。例如很多代理服务器如果监听端口设置成 `0.0.0.0` 时，只会监听 IPv4 连接，此时无法访问，会出现 `ERR_PROXY_CONNECTION_FAILED` 错误。这个错误不是 SwitchyOmega 的问题。

**Comment by lslqtz** [comment]
好的，谢谢。
看起来只有Windows下的ping支持[::1]这种写法了。。
