### ISSUE TITLE
不代理的地址列表中设置localhost不起作用

### ISSUE THREAD

**Issue by 39Er** [FelisCatus/SwitchyOmega#1100]
如下设置不代理的地址列表：

```
<local>
*.localhost
localhost:*
127.0.0.1:*
```
无法访问localhost，使用直接连接可以

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by celeron533** [comment]
你写错了
应该是
```
<local>
localhost
127.0.0.1
```

**Comment by 39Er** [comment]
依然不行

**Comment by FelisCatus** [comment]
请检查下图标的弹出菜单，请问选择的是设置的这个情景模式吗？还是另一个情景模式或者自动切换？

请问访问的网址 URL 是什么？是不是 `http://localhost/`? 还是其他的域名等？

**Comment by 39Er** [comment]
不好意思刚看到，我的设置如下：
![default](https://user-images.githubusercontent.com/12530172/28370150-23e986fe-6ccc-11e7-8b0e-0fd58c7fbc8a.JPG)
![1](https://user-images.githubusercontent.com/12530172/28370166-2b149ec8-6ccc-11e7-83b7-4910df32cf9b.JPG)

然后访问http://localhost:[port] 无法访问

**Comment by 39Er** [comment]
刚刚又试了下，发现是自己理解错了情景模式，改了下pac脚本好使了，谢谢
