### ISSUE TITLE
网页版网易云音乐无法播放

### ISSUE THREAD

**Issue by macrovve** [FelisCatus/SwitchyOmega#1101]
使用这个插件的时候，一般都是在auto switch上，网易云音乐有时候就是无法加载出来，只有选择直接连接才可以。我在linux，window上的chrome浏览器都碰到了这个问题。

**Comment by celeron533** [comment]
你看看autoswitch的时候是不是把某些页面元素代理了。如果你的代理服务器在国外，一般网易音乐由于版权限定是不对国外IP服务的

**Comment by macrovve** [comment]
我看了下歌曲的链接是正常的直接连接
![20170611233758](https://user-images.githubusercontent.com/17618273/27012332-420c46ba-4f00-11e7-962c-e6821192af86.png)

**Comment by FelisCatus** [comment]
这个问题基本就是切换规则问题，只有更准确地确认请求是什么才能添加对应的规则。

推荐打开 F12 开发者工具，点击 Network ，然后仔细查看哪些请求有超时或者失败的情况，记下那些 URL. 注意歌曲播放的可能是在不同的 CDN 域名下等。右键菜单的检查元素对 XHR 请求等无效。
