### ISSUE TITLE
本地域名跳转到错误的页面(广告页?)

### ISSUE THREAD

**Issue by chuckbadgley** [FelisCatus/SwitchyOmega#1102]
本地域名 web.ftx.com(重定向到127.0.0.1) 
打开插件时会跳转到如下截图, 关闭插件能打开正确的页面.
(本机为 web 开发环境)

![image](https://user-images.githubusercontent.com/3204292/27017735-3747708a-4f5d-11e7-97e8-3f769775cd57.png)

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by celeron533** [comment]
会不会是你用的代理服务器被人恶意加入了流量劫持？

**Comment by chuckbadgley** [comment]
不会, 自建的 SS 服务器, 运行快半年了, 将此域名的的规则设置为直接连接, 则正常

**Comment by celeron533** [comment]
SwitchyOmega是通过官方途径下载的吗？

**Comment by chuckbadgley** [comment]
是的  Google play 上装的

**Comment by FelisCatus** [comment]
这和 DNS 解析有关，请自行把 `web.ftx.com` 等加入自动切换规则，使用直接连接。

注意，代理服务器的选取只和网址有关。即使您本地 hosts 已经把这个域名设置成 127.0.0.1 了，对代理的选取也没有任何影响，因此需要手动设置白名单。
