### ISSUE TITLE
打开youtube，有GAEproxy timeout

### ISSUE THREAD

**Issue by hackNeo** [FelisCatus/SwitchyOmega#1103]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega已经正确的把传输请求传送到了GAE，剩下的是GAEproxy代理服务器的问题

**Comment by qingjiangshui** [comment]
一般是网速过慢导致的。如果是PAC代理的话，可改为全局代理试试。

**Comment by FelisCatus** [comment]
代理服务器问题，与 SwitchyOmega 无关。
