### ISSUE TITLE
求助：SwitchyOmega设置时导入goagent 或xx-net配置备份文件互相覆盖问题

### ISSUE THREAD

**Issue by hongkonghot** [FelisCatus/SwitchyOmega#1104]
SwitchyOmega设置时，goagent中的SwitchyOptions.bak文件或导入XX-Net-master\SwitchyOmega\OmegaOptions.bak文件时，都会覆盖先导入的配置，怎么同时让两个配置都保留啊！麻烦指教一下吧

**Comment by FelisCatus** [comment]
目前是没办法都保留的，不过您可以试着把两个都导出成配置文件然后手动合并。
