### ISSUE TITLE
域名通配符规则无法完全匹配我所访问的网站

### ISSUE THREAD

**Issue by coreychen** [FelisCatus/SwitchyOmega#1105]
非常不错的软件，非常感谢各位的无私奉献！
但是对我来说还是有一些不便。
我的使用场景是这样的：配置了2个代理，一个是用来翻墙到国外的，用pac方式配置的；一个是用来翻公司的网络限制的（公司网络限制访问京东和淘宝等各种非工作网站）；
用的自动规则是这样的：
```
[SwitchyOmega Conditions]
@with result
*.jd.com +公司代理
* +翻墙
```

就是当我想访问京东的时候就用公司代理，其他时候都用翻墙的代理。
但是这样是无法正常访问京东的，因为像京东这样的大型网站会做很多优化，加载的很多资源都不是在jd这个域名下的，所以打开www.jd.com的时候页面是残缺的，无法完全展示；
![image](https://user-images.githubusercontent.com/5762082/27214576-c65e7918-529f-11e7-8ead-2ac9aab1d386.png)

我不知道是否可以实现这样的逻辑：
我在浏览器上输入了一个url，会匹配到一个代理情景，那么这个页面下对应的所有url请求都使用这个代理去访问。

再次感谢！！

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.86 Safari/537.36

**Comment by coreychen** [comment]
不过这样的网站不多，并且就是京东使用的域名也不是很多，刚发现在页面点击图标有一个添加条件的选项还是比较方便的，自己手动加下也是可以接受的吧

**Comment by FelisCatus** [comment]
抱歉，由于[技术原因](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E6%8C%89%E7%85%A7%E7%AA%97%E5%8F%A3%E6%88%96%E8%80%85%E6%A0%87%E7%AD%BE%E9%A1%B5%E6%9D%A5%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E5%90%97)，无法支持根据页面本身来判断资源。请自行添加规则。
