### ISSUE TITLE
Bypass List googlevideo.com

### ISSUE THREAD

**Issue by maxchendt** [FelisCatus/SwitchyOmega#1106]
从6月16日起，IPv6 的 `*googlevideo.com` 被 reset 或者丢包 等，视频流 当前只能 走 代理

Bypass List 先前的设置为

    *google*.com

当前 改为

    *googlea*.com
    *googlec*.com
    *googled*.com
    *googleg*.com
    *googleh*.com
    *googlel*.com
    *googles*.com
    *googlet*.com
    *googleu*.com
    *googlez*.com
    *google.com

即 `*googlevideo.com` 不被 bypass,  有没有更简单的方法？如下方式可行否

    *google[^v]*.com

根据说明，这好像 不是 wildcard 了，而是 RegExp 了

**Comment by FelisCatus** [comment]
Bypass list 由 Chrome 提供，只支持有限的几种简单规则，不能使用正则表达式。

如果需要复杂的切换规则，请使用自动切换模式。内含正则表达式等。
