### ISSUE TITLE
设置用户名密码中含特殊字符则无效

### ISSUE THREAD

**Issue by clarkhillm** [FelisCatus/SwitchyOmega#111]
密码中有特殊字符：~!@#$%^&*()_+.中的一个或者两个。

SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

**Comment by 1587** [comment]
即使是系统代理也有这个问题,所以我一般都是尽量不用特殊字符(@:;等)
传给系统的代理软件之前一般情况下是如下格式
username:passwd@proxy.xxx.com
他要用:和@作为分隔符
暂时没找到好的方法.

**Comment by FelisCatus** [comment]
Chrome 的问题，关掉了……
