### ISSUE TITLE
virtual profile 到底什么作用？ 是在没看明白， 也没试出来。

### ISSUE THREAD

**Issue by hatelove85911** [FelisCatus/SwitchyOmega#1110]
virtual profile 到底什么作用？ 是在没看明白， 也没试出来。
没有文档解释啊。

**Comment by celeron533** [comment]
Virtual Profile
A virtual profile can act as any of the other profiles on demand. It works well with SwitchProfile, allowing you to change the result of multiple conditions by one click.

有点像是一个位于中间的快捷方式

比如你有好几个switchProfile，都指向了某个代理
```
switch1 --> serverA
switch2 --> serverA
switch3 --> serverA
```

但同时 serverB 和 serverC都是可选的备用服务器，如果你想要将3条现有的switch规则换掉，需要做三次操作。
但如果有如下的结构：
```
switch1 --> virtual
switch2 --> virtual
switch3 --> virtual

virtual --> serverA
```
你只需要将virtual指向serverB即可完成转换
