### ISSUE TITLE
自动切换中规则列表设置，填写更新后这个页面就很卡很卡

### ISSUE THREAD

**Issue by UltimateA** [FelisCatus/SwitchyOmega#1111]
Chrome 版本 59.0.3071.115（正式版本） （64 位）
SwitchyOmega 是 Chrome 商店最新的。Windows 10 64位系统。

在自动切换中填写并更新GFWlist后，这个页面就非常卡，但更新按钮的动画还是会动，然后要过好一会儿才恢复，等可以点其他按钮的时候，点别的页面，像是其他情景模式，就完全不卡了，但一旦点了自动切换就马上卡了。初步测试了一下好像就是填写了下面的规则列表并更新GFWlist之后就立即卡。

第一次发反馈，如果格式不对或信息不足，请多包涵并指正，谢谢。

EDIT: 我的自动切换规则没有多少，确认不是这个过度引起的卡顿。

**Comment by FelisCatus** [comment]
这个要么是文本解析太慢了，要么是因为文本框里文字太多了（不太可能）。

如果是解析的问题的话，目前暂时没什么解析更快的方案了，估计要暂时搁置了吧……
