### ISSUE TITLE
设置页面网址规则过多时动画十分卡顿

### ISSUE THREAD

**Issue by AnnAngela** [FelisCatus/SwitchyOmega#1112]
在设置页面-情景规则-自动切换中如果有过多的规则条目的话则所有动画都会非常卡，点个删除按钮老半天才出来删除提示框。请解决一下

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by AnnAngela** [comment]
翻了下Issue list，个人建议弃用Angular框架，看起来是框架的问题。
要不试一下bs？或者自己撸一个=。=

**Comment by FelisCatus** [comment]
感谢建议，目前的优先级不在这里，不过欢迎优化性能或者使用其他框架实现的 Pull Request.

自己使用的话，建议使用编辑源代码模式，或者将规则分散到多个自动切换情景中。
