### ISSUE TITLE
自动模式下芒果tv/pptv不能播放

### ISSUE THREAD

**Issue by MurrddoL** [FelisCatus/SwitchyOmega#1113]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by celeron533** [comment]
可能是代理规则设置不正确

**Comment by FelisCatus** [comment]
如果正在使用规则列表等，请向规则列表维护者反馈。如果是自己使用切换规则，请根据实际网络状况添加或修改合适的规则。
