### ISSUE TITLE
无法代理https

### ISSUE THREAD

**Issue by jiejingtao** [FelisCatus/SwitchyOmega#1116]
网址协议：默认
代理协议：http
代理服务器：10.x.x.0
端口：8000

http://mydomain.com 可以走代理
https://mydomain.com 不行

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by celeron533** [comment]
配置文件设置错误？

**Comment by FelisCatus** [comment]
请访问 https://mydomain.com ，然后观察 SwitchyOmega 图标的颜色，确认是否经过了代理。也可以鼠标悬停在图标上，查看哪些规则或者设置导致了网址没有使用代理。

**Comment by jiejingtao** [comment]
![image](https://user-images.githubusercontent.com/1564097/28106511-b282fa14-6716-11e7-8feb-338427373042.png)
![image](https://user-images.githubusercontent.com/1564097/28106538-c77c3c46-6716-11e7-8a65-b8c71b51626b.png)

**Comment by jiejingtao** [comment]
应该是我代理的问题，我先close了，谢谢两位~
