### ISSUE TITLE
SwitchyOmega在360极速浏览器9.0里经常出现“冻结”状态响应非常缓慢

### ISSUE THREAD

**Issue by ctexlive** [FelisCatus/SwitchyOmega#1118]
比如刚启动360极速浏览器时，就现实omega扩展在加载．．．然后浏览器的其他扩展就一直无法加载．
或者进入omega扩展的设置时，不定时出现扩展设置页面冻结，表现为鼠标无法拖动或者点击没反应，等一段时间后就恢复．在冻结时候，也很难关闭该扩展设置页面，而且此时我点到其他页面是正常响应的．当我禁止omega扩展后，冷启动360极速浏览器，可以非常迅速的启动，其他扩展加载速度也恢复正常．所以问题应该处在omega扩展响应缓慢的问题．
360极速版本为9.0.126

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FelisCatus** [comment]
这该不会是之前 Chrome 那个 PAC 占用内存过多的问题吧……

**Comment by ctexlive** [comment]
等我再测试测试，再进一步报告．以前没发现这个问题，现在简直没法用扩展了．

**Comment by FelisCatus** [comment]
有什么更新吗？
