### ISSUE TITLE
Firefox 扩展能否提交验证:)

### ISSUE THREAD

**Issue by a632079** [FelisCatus/SwitchyOmega#1120]
我了解到，Firefox上目前也存在 SwitchyOmega 这插件。遗憾的是插件并未签名，请问能给这插件签名一下么？

**Comment by a632079** [comment]
尝试提交了下Chrome下的插件。。。提示了js库引用错误，尴尬

**Comment by FelisCatus** [comment]
已经提交了啊，正在审核，见 https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

不用帮我再提交一次了……
