### ISSUE TITLE
支持socks5用户名&密码认证是否可行(ldap认证更好)？求解

### ISSUE THREAD

**Issue by depfish** [FelisCatus/SwitchyOmega#1121]
公司对内提供翻墙服务，需要支持socks5用户名密码认证(支持ldap更佳),用SwitchyOmega实现，是否可行? 求解

**Comment by FelisCatus** [comment]
参见[常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8D%E6%94%AF%E6%8C%81-socks5-%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E5%AF%86%E7%A0%81%E8%AE%A4%E8%AF%81%E5%90%97)。
