### ISSUE TITLE
建议内置国旗图标或者增加图标文字设置

### ISSUE THREAD

**Issue by soffchen** [FelisCatus/SwitchyOmega#1122]
可以给配置文件设置国旗图标

或者，像 StrongVPN 那样，切换 Profile 之后，在图标上直接写上 HK, JP 字样，可以给配置文件定义两个字符 :)

这样比颜色区分更有识别性

**Comment by celeron533** [comment]
加了字符以后，原先的未加载资源的数字放哪里？

**Comment by FelisCatus** [comment]
国旗图标免了吧……但也许自定义图标可行呢？可以考虑下。

然后写字符的话，确实和未加载资源的 badge 冲突了……这个要怎么做比较好呢？

**Comment by celeron533** [comment]
折中的方法是在标题里写个emoji，哈哈
![image](https://user-images.githubusercontent.com/3608762/28298182-696fcc0c-6ba4-11e7-8a55-8cc98c07dda4.png)

**Comment by soffchen** [comment]
然后标题加 emoji 并不会影响图标显示？

加载资源的数字是右下角？自定义字符显示左上角可能吗？或者，加载资源这个自定义成为显示自定义字符，毕竟……那个加载资源的数字从来没用过 lol

**Comment by celeron533** [comment]
加载资源的数字位置是chrome指定的，无法修改，而且强制规定最多只能显示3个字符

**Comment by soffchen** [comment]
看了一下 StrongProxy，是用 badge 来显示国家字符的

建议，要吗自定义图标，要吗可自定义不显示资源数字改成显示 Profile 的自定义文字（不超过 3 个字符）

**Comment by celeron533** [comment]
自定义图标和目前的设计理念冲突啊。现在是圆环套圆圈，来表示**多种**不同的代理状态，自定义图标目前没想到怎么体现这种场景。

**Comment by TangBaohua** [comment]
完全没必要国旗图标，这个只是代理切换工具
