### ISSUE TITLE
SwitchySharp settings lost after upgrading to 1.10.6

### ISSUE THREAD

**Issue by hanxue** [FelisCatus/SwitchyOmega#1123]
I just restarted Chrome for the latest update, and at the same time Proxy SwitchySharp was updated as well. All my previous profiles and Rules are lost (empty). 

Is there any way to restore the previous rules?

**Comment by FelisCatus** [comment]
Hi there, this is the SwitchyOmega project, not SwitchySharp.

Please kindly raise issues related to the SwitchySharp issue tracker. Note that SwitchySharp is not actively maintained though.
