### ISSUE TITLE
现在连内网都不行了

### ISSUE THREAD

**Issue by tommyonsn** [FelisCatus/SwitchyOmega#1124]
连内网经常出现数字角标，太让人崩溃了，总是出问题

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega是一个代理切换工具，出现角标大都数是代理服务器的问题。

**Comment by FelisCatus** [comment]
一般就是网络环境不稳定导致的， SwitchyOmega 只是如实汇报了这个问题。如果不需要此提示可以在选项中关闭网络检测。
