### ISSUE TITLE
能否增加域名正则匹配的功能

### ISSUE THREAD

**Issue by zeng-xs** [FelisCatus/SwitchyOmega#1125]
只能用通配符匹配域名的话，感觉还是不够方便啊，能否增加域名正则匹配的功能？
虽然说通过网址正则也可以实现这个功能，但是写起来感觉很别扭。

**Comment by celeron533** [comment]
记得有这个功能的啊

**Comment by zeng-xs** [comment]
@celeron533 
SwitchyOmega 2.4.6 (Chrome 59.0.3071.115 x64 on Windows 10 1703) 没有域名正则匹配。只有这三个：
+ 域名通配符
+ 网址通配符
+ 网址正则

**Comment by FelisCatus** [comment]
此功能需要在设置>界面>切换下，选中启用高级切换条件才能开启。对此造成不便敬请谅解。
