### ISSUE TITLE
Firefox: 点Options无法打开swithyOmega的设置页面

### ISSUE THREAD

**Issue by netroby** [FelisCatus/SwitchyOmega#1126]
Firefox developer edition, 最新 55
安装体验SwitchyOmega

点SwitchyOmega图标，然后再点击Options，无法进入设置页面。

点Options的链接
moz-extension://1e5a2646-17fb-4320-b80f-385cc886cd4b/popup/index.html#

实际设置页面的链接地址
moz-extension://1e5a2646-17fb-4320-b80f-385cc886cd4b/options.html#!/ui

**Comment by netroby** [comment]
另外一个项目，ublock origin， 点击设置，会跳转到

chrome://ublock0/content/dashboard.html

chrome://协议开头的地址。

**Comment by FelisCatus** [comment]
这边代码里是用 `chrome.extension.getURL('options.html');` 取得路径，然后用 `chrome.tabs.create({url: options_url});` 打开的，并不是直接写的链接地址。

我这里 Nightly 56.0a1 似乎是可以正常打开的，请升级到最新 Nightly 试试看。

另外再确认一遍，点击了那个选项以后会怎么样？打开错误的页面？还是打不开页面，弹出窗口直接关掉了？还是弹出窗口仍然留在那里？

点过一次 Options 以后，再右键扩展图标，点 Save error log 试试看？

**Comment by netroby** [comment]
用firefox 55.0 b11点击没报错，没有任何反应，但是打不开页面

_Sent from my Xiaomi Mi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nopyhe** [comment]
Firefox 55.0 b11 点击选项按钮后 没有**任何**反应，菜单没有关闭，页面也没有打开。
报错日志没有任何记录。

**Comment by FelisCatus** [comment]
真是奇怪了，能麻烦哪位装下 Nightly 试试看吗？我这里先看看能不能合并 #1127 做个兼容。

**Comment by FelisCatus** [comment]
顺便，能麻烦也试试看 #1134 吗？我想试试看兼容两种做法，但如果不行就回归最简单的链接做法吧。

**Comment by TangBaohua** [comment]
经检验，Nightly 56可以弹出设置界面；Developer 55 不可以；

**Comment by liuxb** [comment]
nightly 56a1
可以打开设置页面。
但是另外一个按钮有问题，设置页面---界面---键盘快捷键 中的 “configure shortcut” 按钮，点击无任何反应。就是自定义alt+shift+o的那个按钮。

**Comment by FelisCatus** [comment]
@liuxb Firefox 本身有任何地方可以设置/修改扩展的快捷键吗？如果有的话，我需要链接到那个页面，如果没有的话，我应该去掉那个按钮。我自己找了下，没找到有任何地方可以像 Chrome 一样的设置……

**Comment by FelisCatus** [comment]
话说这个问题我知道是为什么了，马上做下 Firefox 55 的兼容。

**Comment by FelisCatus** [comment]
2.4.16 已做兼容，但下不为例。

Firefox 的支持还在早期阶段，那边的代码也不稳定。以后如果是 Firefox 那边旧版的 bug （就像这次毫无道理的内部异常），那么一律不做处理，请自行更新到新版。但如果是旧版缺少某个功能，那么一般会做兼容。 Developer Edition / Beta 的进度并不是很快，所以在此再次推荐大家升级到 Nightly ，以免遇到更多类似的问题。

**Comment by nopyhe** [comment]
这也不能算是旧版吧，现在正式版还是54，下个正式版就是55了……
