### ISSUE TITLE
version doesn't work with Chromium

### ISSUE THREAD

**Issue by deepgray** [FelisCatus/SwitchyOmega#1128]
SwitchyOmega 2.4.6
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36

**Comment by celeron533** [comment]
Please provide some details.
What does not work? Have you checked that the proxy server is still alive?

**Comment by Shadowhack0419** [comment]
@celeron533 请问支持Linux的chorme么为什么加载不了？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
