### ISSUE TITLE
无法使用带验证的HTTPS代理

### ISSUE THREAD

**Issue by Max-Sum** [FelisCatus/SwitchyOmega#1131]
带验证的HTTPS代理处理中没有加验证头，导致无法验证。

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by FelisCatus** [comment]
代理协议由 Chromium 处理， SwitchyOmega 只负责在 Chromium 询问用户名密码的时候提供用户名密码。 Chromium 的实现，必须先收到 HTTP 401 才会获取用户名密码，并重新发送带有 Authorization header 的请求。如有问题请前往 Chromium 项目反馈。
