### ISSUE TITLE
Firefox版SwitchyOmega点击下拉“选项”按钮没反应

### ISSUE THREAD

**Issue by TangBaohua** [FelisCatus/SwitchyOmega#1133]
点击工具栏的圆圈图标后能够弹出下拉菜单，可以正常选择代理类型，但是点击最下面的“选项”后没有任何反应，只是在右下角出现超链接的提示：
![default](https://user-images.githubusercontent.com/11957114/28600785-e92352f0-71e6-11e7-90f8-721689a92bd7.png)
按钮位置如下
![default](https://user-images.githubusercontent.com/11957114/28600875-70fa04ee-71e7-11e7-94e3-0f9f2ac0d375.png)

另外请问大概哪个时候通过审核，我想在正式版FF使用此扩展。
55.0b12 64位

**Comment by FelisCatus** [comment]
见 #1126.
