### ISSUE TITLE
chrome can't load 

### ISSUE THREAD

**Issue by mengshixing** [FelisCatus/SwitchyOmega#1135]
![ndy v245a p 75 o_7k 6](https://user-images.githubusercontent.com/20792367/28663855-256369de-72f1-11e7-8ac5-989f2e7a6305.png)

**Comment by celeron533** [comment]
似乎是这个
https://support.google.com/chrome/a/answer/6177431?hl=zh-Hans

> 配置政策和设置
默认情况下，用户可以安装任意扩展程序或应用。作为管理员，您可以阻止特定应用和扩展程序，也可以阻止您批准的特定应用和扩展程序之外的所有应用和扩展程序。您还可以强制安装指定的应用和扩展程序。用户将无法卸载强制安装列表中添加的任何项。
要阻止特定应用和扩展程序，请选择允许除我阻止之外的其他所有应用和扩展程序 （默认选项），接着点击“获准运行的应用和扩展程序”旁边的“管理”链接，然后选择要阻止的项。
要阻止大多数应用和扩展程序，请选择阻止除我允许之外的其他所有应用和扩展程序选项，接着点击获准运行的应用和扩展程序旁边的管理链接，然后选择要获准运行的项。
要将安装的应用或扩展程序固定到 Chrome 启动器中，请点击管理已固定的应用，然后选择要固定的项。
要强制安装特定应用和扩展程序，请点击管理强制安装的应用，然后选择要强制安装的项。

**Comment by FelisCatus** [comment]
看来是政策阻止安装了，请联系您的系统管理员，例如公司或者机构的 IT 部门之类的。

**Comment by celeron533** [comment]
较高级的操作是自己编译一份，以 载入开发中的扩展 来使用
