### ISSUE TITLE
使用Socks5代理时, 如何设置用户名和密码?

### ISSUE THREAD

**Issue by tldzyx** [FelisCatus/SwitchyOmega#1136]
使用Socks5代理时, 如何设置用户名和密码?

SwitchyOmega 2.4.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by celeron533** [comment]
Chrome原生不支持
https://github.com/FelisCatus/SwitchyOmega/issues/178#issuecomment-69450120

**Comment by lzhr** [comment]
可以结合[cow](https://github.com/cyfdecyf/cow)/meow使用

**Comment by tldzyx** [comment]
@celeron533 经过多次试验，找到了一个比较直接的方案：
1. SwitchyOmega新建一个PAC情景模式
2. 更新PAC脚本
``` pac
function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:1080;DIRECT;";
}
```
脚本中的127.0.0.1:1080是socks5代理地址和端口
3. 使用这个场景就可以代理上网了， 首次使用需要输入socks5的用户名和密码。
4. 或许SwitchyOmega可以把上面这一套封装下，用起来会更简洁一些。

**Comment by tldzyx** [comment]
@celeron533 
经过一些实验，发现一种比较直接的方式使用带验证的socks5
1. 创建一个PAC情景模式
2. 更新PAC脚本
``` pac
function FindProxyForURL(url, host) {
  return "PROXY 127.0.0.1:1080;DIRECT;";
}
```
其中127.0.0.1:1080是socks5代理的地址和端口
3. 使用该场景代理上网即可，首次使用浏览器会提示输入socks5的用户名和密码
4. 或许SwitchyOmega可以封装一下上述流程，使得看上去就好像是使用带验证的socks5代理服务器。

**Comment by celeron533** [comment]
@tldzyx ,
Socks5 似乎不是这种写法。
你上文的`PROXY`应该只是指向一般的http代理。

四种代理参考下文：

```
        switch (scheme) {
          case "http":
            return "PROXY 127.0.0.1:80";

          case "https":
            return "HTTPS 127.0.0.1:443";

          case "ftp":
            return "SOCKS 127.0.0.1:1080";

          default:
            return "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080";
        }
```
