### ISSUE TITLE
请求添加 QUIC 类型代理支持。

### ISSUE THREAD

**Issue by phuslu** [FelisCatus/SwitchyOmega#1137]
Chrome 客户端已经实现了 quic 代理协议，见
1. https://bugs.chromium.org/p/chromium/issues/detail?id=335275
2. https://codereview.chromium.org/144623006/patch/230001/230007

而 goproxy-vps 服务端也实现了 quic 协议，见
1. https://github.com/phuslu/gop/tree/server.vps

请考虑加上 QUIC 类型的代理支持。

**Comment by FelisCatus** [comment]
见 #706.
