### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by Shadowhack0419** [FelisCatus/SwitchyOmega#1138]
最新版的插件支持udp流量了吗？

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega ，并不是 Shadowsocks 等项目。 SwitchyOmega 是设置软件，不涉及代理协议。

**Comment by Shadowhack0419** [comment]
@FelisCatus 请问什么意思？他的实现方法是拦截端口流量然后代理？udp不是shadowsocks协议好么，他是传输层标准协议。

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by celeron533** [comment]
Switchyomega主要是用来生成和管理PAC文件的，所以功能和行为和PAC一致
