### ISSUE TITLE
Firefox: Proxy script not initialized

### ISSUE THREAD

**Issue by turbidsoul** [FelisCatus/SwitchyOmega#1139]
*.google.com  无法代理

SwitchyOmega 2.4.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
```
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://mail.google.com",
    "level": "warn"
}
```

**Comment by celeron533** [comment]
似乎和 https://github.com/feliscatus/switchyomega/issues/102#issuecomment-314825654 类似？

**Comment by FelisCatus** [comment]
请等待一段时间然后看是否可以用。如果等一会还是不行，请右键点击图标，导出错误日志并上传到这里。

**Comment by turbidsoul** [comment]
@celeron533 我是安装了ubo

**Comment by turbidsoul** [comment]
[OmegaLog_1501634003883.txt](https://github.com/FelisCatus/SwitchyOmega/files/1192333/OmegaLog_1501634003883.txt)

这是错误日志

**Comment by FelisCatus** [comment]
> Error: Could not establish connection. Receiving end does not exist.

这很诡异，既然 `proxyScriptLog` 都能打印出来，说明代理脚本已经加载，但为什么会无法发送消息呢？

我感觉像是 Firefox 的问题，请更新到最新 Nightly 版本然后再试。

**Comment by turbidsoul** [comment]
@FelisCatus 我的是每夜编译版，早上已经更新到最新的，但是问题依然存在。
[OmegaLog_1501812876657.txt](https://github.com/FelisCatus/SwitchyOmega/files/1199075/OmegaLog_1501812876657.txt)

**Comment by FelisCatus** [comment]
和 #1144 的情况是一样的。试试看换 Developer Edition 看看那边行不行。然后试试看用全新的用户资料路径，来排除其他扩展/设置的问题。如果 `about:config` 里有改过什么设置也请告知。

**Comment by FelisCatus** [comment]
麻烦试下 #1152 的最新编译包，记得下载后改扩展名为 `.xpi` ，关闭扩展签名要求后安装。

**Comment by turbidsoul** [comment]
@FelisCatus 更新 #1152 的新xpi之后，重启浏览器，现在可以代理了

3Q

**Comment by LeeJayl** [comment]
更新 #1152 的新xpi之后，仍无法代理，错误日志如下：
[OmegaLog_1502077164529.txt](https://github.com/FelisCatus/SwitchyOmega/files/1203835/OmegaLog_1502077164529.txt)
Firefox troubleshooting如下(new profile，部分信息删减):

**Comment by FelisCatus** [comment]
有人行有人不行的话，很高的概率是 race condition, 等我加个延时重试看看……

**Comment by turbidsoul** [comment]
@FelisCatus 昨天好了，今天貌似又不行了
[OmegaLog_1502154347921.txt](https://github.com/FelisCatus/SwitchyOmega/files/1206605/OmegaLog_1502154347921.txt)

**Comment by FelisCatus** [comment]
试试看 #1152 上的最新版本，刚更新过。

**Comment by LeeJayl** [comment]
Nighty 57(08-07,64bit) new profile，仍然出现“Proxy script not initialized”，日志如下：
[OmegaLog_1502157340609.txt](https://github.com/FelisCatus/SwitchyOmega/files/1206706/OmegaLog_1502157340609.txt)

**Comment by FelisCatus** [comment]
目前仍然原因不明，但退回 Nightly 2017-07-10 之类的版本应该能暂时凑合用。或者换 Developer Edition 试试看。

**Comment by LeeJayl** [comment]
Developer Edition 56.0b1 troubleshooting(OS:win7 64bit) 如下：
[Troubleshooting Information.txt](https://github.com/FelisCatus/SwitchyOmega/files/1217372/Troubleshooting.Information.txt)
SwithyOmega Log 如下：
[OmegaLog_1502442064861.txt](https://github.com/FelisCatus/SwitchyOmega/files/1217375/OmegaLog_1502442064861.txt)
测试结果仍然出现“Proxy script not initialized”，且无法进行socks5代理。
同样环境下测试Chrome 60.0.3112.90 socks5代理正常。

**Comment by FelisCatus** [comment]
见 #1171 详细说明，大概是 Firefox 的问题。之后有什么进展，我会在那边更新。
