### ISSUE TITLE
有时候没反应，不对地址解析

### ISSUE THREAD

**Issue by zxj930057911** [FelisCatus/SwitchyOmega#1140]
打开浏览器后有时候不会解析地址，需要等待一定时间，相同的配置条件chrome首次开启可以直接访问google，Firefox不行。

SwitchyOmega 2.4.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://twitter.com",
    "level": "warn"
}
```

**Comment by celeron533** [comment]
似乎和 https://github.com/FelisCatus/SwitchyOmega/issues/102#issuecomment-314825654 类似？

**Comment by zxj930057911** [comment]
看样子是的，就是开始代理不工作，需要等待

**Comment by FelisCatus** [comment]
这应该没办法了， Firefox 的设计就这样……需要先加载 proxy script ……
