### ISSUE TITLE
The Best Firefox Proxy extension Ever made

### ISSUE THREAD

**Issue by mrunc** [FelisCatus/SwitchyOmega#1141]
Just wanted to tell you that I just tested SwitchyOmega on Firefox Developer Edition 55.0b14 (64-bit) on both macOS and Windows and it's working like a beast I can't wait for it to be released for Stable Firefox release channel I don't see why it's not allowed to install on Firefox 54.0.1 it's by far the Greatest most stable proxy extension for firefox have you people seen the other bullshit weak extensions that's available for firefox some of them should really focus on only selling proxies and vpns and forget about it.

Thank you guys for this great project

**Comment by FelisCatus** [comment]
Thanks for your feedback! The SwitchyOmega extension uses the Proxy API, which is not available until Firefox 54. Unfortunately, there isn't much that we can do besides waiting for 55 to reach stable. Thanks for your patience.
