### ISSUE TITLE
自己添加的域名列表上报至gfwlist功能

### ISSUE THREAD

**Issue by icecrack** [FelisCatus/SwitchyOmega#1142]
GFWLIST的更新离不开被墙网址的提交,但是大部分的人可能因为麻烦或者啥原因,遇到被墙的网址但是不在GFWLIST会添加到switchyOmega的代理规则的,而不会再去GFWLIST提交下这个网址. 我想我们这个软件是否可以实现将用户添加的自定义代理规则网址上传到GFWLIST提交页面,这样GFWLIST维护者可以根据提交网址的重复数量来添加网址也是有可能的嘛.

**Comment by celeron533** [comment]
gfwlist有专门的上报、检查入口，且是完全不同的项目。过于方便的上报设计会导致上报量激增，加重gfwlist的审核负担。完全没有必要加入这个功能。不要做过度设计。
另外SwitchyOmega只是个代理切换工具，不是专门用来翻墙的。

**Comment by FelisCatus** [comment]
SwitchyOmega 不是翻墙软件，和 gfwlist 也不存在合作关系。比起来这边问，你不如去问问 gfwlist 那边是否需要改进反馈途径之类的……
