### ISSUE TITLE
Firefox for Android

### ISSUE THREAD

**Issue by anguni** [FelisCatus/SwitchyOmega#1143]
打开moz-extension://3d2ae651-b2a1-4207-98a5-730c87dca231/options.html#!/about是一片空白

**Comment by FelisCatus** [comment]
这……有时间我弄个 Firefox for Android 试试看好了。我都不知道 Firefox for Android 是不是有 proxy API ……

**Comment by EMLVIRUS** [comment]
我建议close。ss/ssr客户端都有内置路由，别的代理工具都是全局接管。我看不出有什么必要。

**Comment by celeron533** [comment]
@FelisCatus 辛苦了啊！

**Comment by FelisCatus** [comment]
@EMLVIRUS 目前没有支持的计划，但我会找个时间试一下，看看是不是很简单地修改一下就能兼容。如果不能兼容那么就不说，如果开发成本很高那么再讨论。

**Comment by FelisCatus** [comment]
话说我把 Firefox for Android 版先下架了，本来就没经过任何检验，根本不知道能不能工作。现在既然有人说不能，我早点把这个撤掉大家就不会再被误导下载了。

如果要测试请自己拿 Release 界面的 XPI 或者从源代码编译来测试。如果谁碰巧能运行，那我再把这个弄回去。

**Comment by FelisCatus** [comment]
见 #1145，经过一些 hack 以后至少能安装了……欢迎去那边下载测试版安装。

**Comment by anguni** [comment]
那tor呢？

**Comment by FelisCatus** [comment]
tor 是啥？如果您说的是代理软件那个 tor ，那么和 SwitchyOmega 并没有关系啊。

**Comment by anguni** [comment]
我想说的是orfox太差劲了，希望通过SwitchyOmega让Firefox用tor

**Comment by FelisCatus** [comment]
那你在手机上运行 tor 然后设置好 SwitchyOmega 就好了吧？

**Comment by anguni** [comment]
似乎我只能访问https://check.torproject.org/?lang=zh_CN，同时它显示恭喜，但却连Bing都无法访问。

**Comment by FelisCatus** [comment]
那是代理服务器或者 Tor 网络的问题，与 SwitchyOmega 没有关系。

**Comment by FelisCatus** [comment]
v2.5.1 已经修复，等审核。
