### ISSUE TITLE
Remove PAC Profile from UI in Firefox

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1146]
As of now the PAC Profile won't work in Firefox. People may go though all the trouble of creating one, adding it to auto switch, enabling it and noticed it doesn't work on websites. And the worst part is, there is no warning or error message on the UI.

So let's get rid of PAC Profile when adding new profiles. For existing options or imported options, an error message should be displayed on the top part of the page explaining the situation.

We will probably need a way to detect that WebExtension is used AND `eval` disabled via CSP. Hopefully `new Function("")` inside a try-catch will do it.

**Comment by FelisCatus** [comment]
CSP detection can come later since we don't support PacProfile in any WebExtension environment, even if CSP allows eval.

**Comment by ericjung** [comment]
You can perform eval() on remotely loaded scripts by specifying that permission in manifest.json:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/content_security_policy

**Comment by yfdyh000** [comment]
@ericjung It will block the extension listed on addons.mozilla.org.
> 1. Note: Valid examples display the correct use of keys in CSP. However, extensions with 'unsafe-eval', 'unsafe-inline', remote script, or remote sources in their CSP are not allowed for extensions listed on addons.mozilla.org due to major security issues.

**Comment by ericjung** [comment]
@yfdyh000 can probably get a reviewer's exception because this would be eval()'d inside the FindProxyForURL() sandbox (I presume). That sandbox cannot touch anything else; in fact that is why it must use browser.runtime.sendMessage() to contact the rest of the addon.

**Comment by ericjung** [comment]
I've reached out to some internal mozilla folks about this. Will update.

**Comment by FelisCatus** [comment]
@ericjung Thanks a lot!

**Comment by ericjung** [comment]
@FelisCatus, there is a new proxyAPI specification going around. I would like you to look at it. Please contact me directly for info. Thanks.
