### ISSUE TITLE
Error log should not include user-identifying or sensitive information

### ISSUE THREAD

**Issue by olloff** [FelisCatus/SwitchyOmega#1147]
This.

For now error log can include Options#reset and Options#patch parts with proxy address:port and auth data. Error log should erase this data or, at least, ask for user consent and highlight it in log.

```
"fallbackProxy"
     "port"
     "host"
"proxyForHttp"
     "port"
     "host"
"proxyForHttps"
     "port"
     "host"
"proxyForFtp"
     "port"
     "host"
"auth"
     "proxyForHttp"
          "username"
           "password"
     "proxyForHttps"
          "username"
           "password"
     "proxyForFtp"
          "username"
           "password"
```

**Comment by celeron533** [comment]
Reproduced on my Chrome 60.

**Comment by FelisCatus** [comment]
Good catch. I think I totally forgot this. Let me patch it.

**Comment by FelisCatus** [comment]
For now please restart Chrome after you change options. The logs will be cleared.

Most issues can be reproduced without changing options though.

**Comment by FelisCatus** [comment]
```js
            "auth": {
                "fallbackProxy": {
                    "password": "<secret>",
                    "username": "<secret>"
                }
            },
            "fallbackProxy": {
                "host": "<secret>",
                "port": "<secret>"
            },
```

Now you can only see a bunch of `<secret>` in the logs for `host`, `port`, `username` and `password`. Please let me know if you have other concerns. Note that we're not going to remove profile names since they are usually necessary to debug issues.
