### ISSUE TITLE
请问如何根据网站服务器的地理位置自动跳转profile?

### ISSUE THREAD

**Issue by OnionSalt** [FelisCatus/SwitchyOmega#1148]
比如大陆地区直连，其他所有地区用vpn
谢谢！

**Comment by celeron533** [comment]
1. 浏览器级别的代理服务和VPN没有任何关联
2. SwitchyOmega的核心是PAC（这是一个浏览器的业界标准，用于设置代理服务器），不支持地理位置跳转

**Comment by OnionSalt** [comment]
有没有办法让SwitchyOmega等待dns解析的结果，然后跟ip跳转呢？

**Comment by celeron533** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/914#issuecomment-257211030
