### ISSUE TITLE
Travis Build

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1153]
It would be great if we can do CI on Travis. Each build can run the linters, do grunt tasks and get a compressed zip ball ready for Chrome Web Store uploading.

We can also run web-ext to lint the webextension and get an unsigned XPI package for Firefox.

TODO: Where to host the artifacts? Uploading to S3 looks like a solution but costs $$$.

**Comment by celeron533** [comment]
I did some C# projects and find Travis/Appveyor stores your artifacts under your CI project.
Also you could set a Deployment task to push the Release package to Github release.
Example, builds were uploaded by Appveyor automatically.
https://github.com/celeron533/Stealth/releases

**Comment by yfdyh000** [comment]
https://travis-ci.org/yfdyh000/SwitchyOmega/builds/261445022

https://docs.travis-ci.com/user/deployment/releases/

**Comment by FelisCatus** [comment]
@yfdyh000 Thanks for the link! It's good to know that it works in Travis CI.

For releases, the CRX and XPI packages needs to be signed. This requires submitting manually to Chrome Web Store / Mozilla Add-ons and going through the review. Therefore, Travis CI's GitHub Release upload won't help much here.

Instead, I'm thinking about building artifacts for branches or PRs. Such artifacts can't be uploaded to GitHub via the Releases API.

**Comment by yfdyh000** [comment]
See https://github.com/gorhill/uBlock/blob/master/.travis.yml, I guess crx & xpi sign (with a different name and automatically signed, with not listed) and upload is feasible.

**Comment by FelisCatus** [comment]
@yfdyh000 The uBlock build just creates zip files. There's no signing involved. Plus it only uploads on releases. The `.xpi` one is just an unsigned, renamed zip file as well.

Anyway, the focus here is not signing since signing for PRs and branches are undesired. The main point is to find somewhere to host the artifacts. To be honest, I'm seriously think about just getting S3 and pay the bill.

**Comment by FelisCatus** [comment]
Circle CI may be a better option here since it offers first-class support, without complicated setup. It's free too.

**Comment by FelisCatus** [comment]
Circle CI Done. https://circleci.com/gh/FelisCatus/SwitchyOmega/tree/master
