### ISSUE TITLE
请问 SwitchyOmega 自 2.5.0 开始不再支持域名正则表达式？

### ISSUE THREAD

**Issue by wtlusvm** [FelisCatus/SwitchyOmega#1154]
我确认已经阅读并理解了[Chromium 完整网址限制](https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-%E5%AE%8C%E6%95%B4%E7%BD%91%E5%9D%80%E9%99%90%E5%88%B6)，但是不是说网址通配符和网址正则表达式无法正常工作吗？ SwitchyOmega 2.4.6 在 Chrome 60.0.3112.90 上使用域名正则表达式依然能正常运行呀，请问可以把功能加回来吗？

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by celeron533** [comment]
Show advanced condition types

![image](https://user-images.githubusercontent.com/3608762/29012384-b6dc69d6-7b6d-11e7-97e6-e550f6462e9b.png)

**Comment by wtlusvm** [comment]
@celeron533 Thx!
