### ISSUE TITLE
为什么别的扩展可以实现socks5认证？

### ISSUE THREAD

**Issue by shellus** [FelisCatus/SwitchyOmega#1155]
https://chrome.google.com/webstore/detail/proxy-helper/mnloefcpaepkpmhaoipjkpikbnkmbnic?hl=en

这个扩展支持socks5账号密码哦，能否借鉴一下它的实现方式呢？

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by celeron533** [comment]
Really? Does Chrome start to support today?
Please refer to #291 
and
https://github.com/henices/Chrome-proxy-helper/issues/2
