### ISSUE TITLE
Firefox代理不生效

### ISSUE THREAD

**Issue by Abel-Liu** [FelisCatus/SwitchyOmega#1156]
代理一直不生效，重装一遍也不行。Firefox Nightly 57
[OmegaLog_1502104001394.txt](https://github.com/FelisCatus/SwitchyOmega/files/1204620/OmegaLog_1502104001394.txt)

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://google.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
见 #1139.
