### ISSUE TITLE
无法观看YouTube，其他正常，

### ISSUE THREAD

**Issue by sdmengxiangyu** [FelisCatus/SwitchyOmega#1157]
SwitchyOmega 2.4.6
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by FelisCatus** [comment]
如果 YouTube 需要代理才能访问，那么请把相关的所有域名（包括网站本身和视频等资源）加到自动切换列表中，选择使用代理。如果您正在使用 GFWList 等规则列表，请向规则列表维护者反馈。
