### ISSUE TITLE
不能观看YouTube，

### ISSUE THREAD

**Issue by sdmengxiangyu** [FelisCatus/SwitchyOmega#1158]
8月 08 09:46:58.09 - [WARNING] IP:66.96.226.231 host:ipv4.google.com not support GAE, server type:HTTP server (unknown) status:503 

SwitchyOmega 2.4.6
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by celeron533** [comment]
请勿重复提交 #1157
