### ISSUE TITLE
SwitchyOmega firefox can not use the socket connection

### ISSUE THREAD

**Issue by Titzanyic** [FelisCatus/SwitchyOmega#1161]
http proxy normal

Firefox version == 55.0 (64 )

**Comment by olloff** [comment]
Firefox 55.0 (current stable release) is not supported yet, see [README.md](https://github.com/FelisCatus/SwitchyOmega/blob/master/README.md).
Does you really test http proxy and it works?

**Comment by StrollStars** [comment]
情况如 @Titzanyic ，Firefox 55.0 (32 位)。
HTTP、HTTPS、SOCKS5代理皆通，但只有HTTP能够正常打开网页。使用其他两个方式时，扩展图标显示为所用的模式颜色，同时显示未加载资源数量，未加载资源的域名已在规则中。
PS：有以下两个相关设置：
①network.proxy.socks_remote_dns;true（开启远程解析域名）
②network.proxy.type;4（高级→连接设置→自动检测此网络的代理设置）

**Comment by olloff** [comment]
@StrollStars Two questions:
1. Do you use socks proxy with authorization?
2.  Does your proxy server provides HTTPS (secure/encrypted with TLS) proxy? (see https://github.com/FelisCatus/SwitchyOmega/issues/1144#issuecomment-321094939 for a difference)

**Comment by FelisCatus** [comment]
What happens if you use SOCKS proxy? What error is shown, if any?

Also, are you using SOCKS4 or SOCKS5?

**Comment by StrollStars** [comment]
@olloff 
1.不需要用户名和密码
2.是我测试不完整，和Chrome对比测试（其他环境一致），发现Chrome上HTTPS也不行，但是HTTP和SOCKS5是可以的，而Firefox仅有HTTP是可以的。
@FelisCatus 
通过SOCKS5没法正常打开网页，浏览器显示”建立安全连接失败，载入页面时与 www.google.com 的连接被中断。“

**Comment by FelisCatus** [comment]
Please also try something like `www.example.com`.

**Comment by olloff** [comment]
@StrollStars I can't confirm this. Believe me, I've tried a lot. 

I've tried around 30 different socks5 proxies from https://www.socks-proxy.net/ list (**attention, it may be compromised/scam, use only from your clean testing profile**). Results was... quite different. Many proxies from the list actually can't load an https-page, but at least 70% do it without problems. Similar results I had on Nightly pre-10-07-17.
My socks5 requires auth, so I can't check this issue within controlled environment, sorry. And I'm not quite sure if all socks5 proxies capable to tunnel SSL.

So I can only propose to you to do some additional tests with another socks5 proxy.

**Comment by FelisCatus** [comment]
I'd like to add that I can't reproduce this with my Linux box running Firefox Nightly using `ssh -D`.

**Comment by StrollStars** [comment]
感谢 @olloff 和 @FelisCatus 的辛苦测试，今天我又试了一下www.google.com，发现第一次不能打开，但是第二次能够打开，猜测是不是和域名解析有关。
因此我想请教下，我前面所说的如下两个Firefox选项设置有影响吗？
> ①network.proxy.socks_remote_dns
> ②network.proxy.type

**Comment by FelisCatus** [comment]
@StrollStars 如果你本地无法访问目标网站，必须通过代理才能访问目标网站，那么有很大的可能域名也必须在代理服务器上解析才可以。此外，如果你所在的网络环境不安全， DNS 可能被污染的情况下，建议设置 network.proxy.socks_remote_dns = true

第二个设置我不觉得有影响，但我不敢确定。倒是不妨改改看。

**Comment by StrollStars** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/1161#issuecomment-321268446

**Comment by olloff** [comment]
@StrollStars `network.proxy.socks_remote_dns` setting is used [to change Firefox proxy configuration](http://kb.mozillazine.org/Network.proxy.type), so it can't really affect your setup while you test SwitchyOmega.

Concerning network.proxy.socks_remote_dns: I have somewhat sad news, if I'm right, it could be either not working at all, or not working on Windows. See https://github.com/FelisCatus/SwitchyOmega/issues/1172#issuecomment-321968998

**Comment by StrollStars** [comment]
@olloff 感谢多次耐心的测试和解答，略有沮丧的是，我渐渐发现问题似乎复杂到我无法去诊断哪个环节出了问题。测试还是以www.google.com为例。
首先，是系统DNS Client这个服务。我说重启系统又无法打开的时候，是重启系统之后开了代理然后直接开Firefox，该服务未启动。而后我用Chrome访问成功，再用Firefox访问还是不行。然后打开DNS Client服务，先Chrome访问再Firefox还是不能打开。保持这个DNS Client服务运行一段时间，这段时间不做任何操作，回来后用Firefox访问，结果打开了。这里我并不确定DNS Client服务是否有影响。
其次，是网站的数字证书问题。当初Firefox无法打开的时候，有提示为“建立安全连接失败”。然后我查看了下已打开的Chrome所显示的证书，其地址栏头部显示的是灰色的感叹号（应当是绿色才安全），其证书签名算法为SHA-1。而一段时间后打开的Firefox，其证书签名算法显示的是SHA-256。所以我猜想是不是有可能Firefox拒绝了SHA-1的证书，以至于之前提示“建立安全连接失败”。但这里并不能排除域名解析的问题。
再次，是域名解析顺序问题。Windows操作系统的域名解析是Hosts优先于访问DNS服务器（其他系统应该也是如此吧），也就是说当在Hosts文件中找不到目标域名，才会去联网解析。所以您在https://github.com/FelisCatus/SwitchyOmega/issues/1172#issuecomment-321968998的测试不能解答设置是否起作用的问题。而第一点说到的DNS Client服务优先级，介于Hosts文件和联网解析之间。
@FelisCatus @olloff Chrome上如果走的是SOCKS5代理，则域名就远程解析，Firefox是否也是如此？另最好Firefox版也能像Chrome那样，直接接管/替代浏览器自带的相应功能。

**Comment by StrollStars** [comment]
@olloff 关于network.proxy.socks_remote_dns，你说的可以理解，但是我没法证实。不过我也希望是不影响到SwitchyOmega，最好就和Chrome里一样，这样问题就要简单些了。
关于https://github.com/FelisCatus/SwitchyOmega/issues/1172#issuecomment-321968998，Windows系统域名解析先查Hosts文件，没有再查找设置的DNS服务器进行询问。你的测试将目标域名写入Hosts文件了，也就是说你的DNS服务器无论怎么设置都不会影响127.0.0.2这个解析结果。

我又在不同时段进行了测试，发现HTTP模式总是好用的，而SOCKS5模式时好时坏，我暂时没找出其中的规律。
PS：我找到了http://kb.mozillazine.org/Network.dnsCacheExpiration，却未能找到network.dnsCacheExpirationGracePeriod的说明，如果你找到了麻烦告知我一声，和DNS解析相关。

**Comment by olloff** [comment]
Mind if I will quote translated version of your answers? My chinese as good as Google Translate is.

> Windows system domain name resolution first check Hosts file, no longer find the DNS server to ask to ask.

Thanks for correcting me. My initial thought was: there no need for Firefox to support HOSTS file checks by itself, since windows DNS client is already doing that. I'll try to repeat your findings and see maybe we can find reason together.

PS: [network.dnsCacheExpirationGracePeriod](https://hg.mozilla.org/releases/mozilla-release/rev/c37f6a5a0c8a)

**Comment by FelisCatus** [comment]
I believe network.proxy.socks_remote_dns still affects SwitchyOmega since extensions can't control this setting. But I have no evidence to support it right now.

**Comment by StrollStars** [comment]
@olloff 感谢谷歌翻译，使得跨语言沟通成为可能，因为我英语不好^_^
看了下翻译，就是我所表达的意思。具体Windows解析过程可以参考《[DNS原理及其解析过程]》(http://369369.blog.51cto.com/319630/812889/)，不过还是中文的。
感谢你给的链接，不过看解释感觉和DNS解析不直接相关，当然我也不是很确定，对Firefox了解还不够。

@FelisCatus 如果是这样，问题就变得复杂了，抽空了我直接把解析写入Hosts文件试试，我想这样应该就能绕开network.proxy.socks_remote_dns这些问题了。

**Comment by kkren** [comment]
@FelisCatus @StrollStars I repeat this issue on nightly 8/28, i'm sure my sock5 proxy doesnot need auth, and http proxy works just fine
to be more specific, when i check my ip on ipip.net it shows my proxy ip, and i still cannot open blocked webiste, i think it is a problem with dns.
can we reopen the issue?

**Comment by StrollStars** [comment]
@kkren 感谢测试，Chrome的机制是通过Scoks5代理访问都进行远程域名解析，而Firefox虽然有个“使用 SOCKS v5 代理 DNS”选项，但我不清楚它是如何起作用的，这是其一。
其二，在Chrome上SwitchyOmega扩展能够完全接管浏览器代理功能，而Firefox上似乎不能，这点前面也提到过。
基于上述两个理由，我目前没有太好的思路去测试这个问题。不知 @FelisCatus 和 @olloff 是否能够看出什么。

**Comment by kkren** [comment]
@StrollStars 很奇怪的是出现问题的时候我没有更新任何东西，只是在普通查资料，下一秒就不能用了。你是怎么发现问题的？我怀疑和系统的设置也有关系。我把我的proxy配置发给朋友，没有复现

**Comment by StrollStars** [comment]
@kkren 在此之前你都是没有问题的么？我是把Chrome的配置导入Firefox，发现无法打开，然后测试服务器没有问题，Chrome也没有问题。上来反馈看到这个帖子，测试了下发现确实HTTP是可以的。
你的朋友用的是和你一样的系统版本和Firefox版本吗？其他相关的网络状况以及扩展插件设置也是一致？如果确实是DNS的问题，那可能和系统有关。我的猜想是在用HTTP访问的时候，Firefox调用了Chrome的解析结果（我少数几次成功是Firefox跟在Chrome之后访问同一网站），因为代理服务器和网站没问题，所以可以打开。

**Comment by kkren** [comment]
@StrollStars 我们系统版本和 Firefox 版本是一致的，其他不能保证。我没有用过chrome，http代理一直没问题。

**Comment by FelisCatus** [comment]
@kkren Feel free to write Chinese if it makes sense for you. I can read both.

普通查资料，下一秒就不能用了不太像是 SwitchyOmega 的问题。就算是，也肯定和这里讨论的问题不同。当然也可以试试看重启浏览器是否恢复。如果能复现请另外开 Issue.

**Comment by StrollStars** [comment]
@kkren 今天测试了下，发现我这里应该不是扩展的问题，你可以新建一个配置文件，试试是否还有问题。

**Comment by kkren** [comment]
好的，能不能说一下你是怎么解决的？

**Comment by StrollStars** [comment]
@kkren 重装Firefox
