### ISSUE TITLE
Not working with Firefox Nightly 57.0a1 

### ISSUE THREAD

**Issue by manish2479** [FelisCatus/SwitchyOmega#1162]
Hi

I tried this plugin and it worked well with Google Chrome but it's not working with Firefox nightly 57.0a1. 

Also, it would be nice to have a plugin for other browsers like Opera, IE and IE Edge.

Thank You,
                 Manish

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by FelisCatus** [comment]
See #1144.
