### ISSUE TITLE
“显示高级切换条件”的小问题

### ISSUE THREAD

**Issue by StrollStars** [FelisCatus/SwitchyOmega#1165]
勾选“显示高级切换条件”后，复选框的勾会消失，当然效果还是在的，只是不熟悉的话会以为没有效果。
取消的话就需要勾选后再去掉勾选才能生效。
建议修复一下。

**Comment by FelisCatus** [comment]
v2.5.1 已经修复， Chrome Web Store 已发布。 Firefox 版仍在审核中。

Fixed on v2.5.1. Published on Chrome Web Store. Firefox version still under review.
