### ISSUE TITLE
SwitchyOmega doesn't work with firefox.

### ISSUE THREAD

**Issue by myrshfrs** [FelisCatus/SwitchyOmega#1170]
I install SwitchOmega from AMO but it doesn't work well. I click its icon to change to my proxy.  Although its icon says that i am using proxy, the network proxy in firefox option still shows no proxy and i can't visit some blocked websites. I try to change proxy in firefox's network proxy myself and it works well.  

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
See #1171 for a detailed explanation. Further updates will be posted there.
