### ISSUE TITLE
Firefox: Extension Not Working on Windows | Windows 下扩展无法工作 

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1171]
I believe this is caused by Firefox failing to sendMessage to the proxy script, leading to errors like `Proxy script not initialized` in SwitchyOmega. For now, there is no way to work around the issue in SwitchyOmega. Linux users and OS X users seem to be unaffected.

If you are affected, please try older Firefox Nightly builds such as 2017-07-10 or earlier for now.

Anyway, I've succeeded to reproduce this on Windows with Firefox Nightly with a minimal working extension. I've filed a bug here: https://bugzilla.mozilla.org/show_bug.cgi?id=1389718

Please refer to that bug for the sample extension and more details.

----

我认为这是由于 Firefox 发送消息到代理脚本失败所导致的， SwitchyOmega 可以观测到 `Proxy script not initialized` 之类的错误。目前 SwitchyOmega 无法绕过此问题。 Linux 和 OS X 用户似乎不受影响。

如果您受到此故障影响，请尝试下旧的 Firefox Nightly 编译版，比如 2017-07-10 或更早的版本。

我已经在 Windows 上的 Firefox Nightly 使用一个最简的扩展程序重现了此问题。已经报告： https://bugzilla.mozilla.org/show_bug.cgi?id=1389718

有关情况和样例扩展，请看上方链接的问题报告。

**Comment by sbwtw** [comment]
8 月 23 号的 nightly 在 linux 下也挂了

**Comment by LeeJayl** [comment]
@sbwtw Bug:1389718里有个临时的解决方案（不知道是否能成功），可以尝试下:
about:config->extensions.webextensions.remote=false

**Comment by sbwtw** [comment]
@LeeJayl Linux 下现在默认就是 false 的

**Comment by nopyhe** [comment]
Nightly 57a1 2017-08-26 已修复

**Comment by johnmiroki** [comment]
@LeeJayl 这招对 Windows 下也管用 FF 56.0b6

**Comment by eailfly** [comment]
不知道是不是一样的问题，我这里Arch下的Firefox Nightly 57.0a1.20170831也不能代理

**Comment by sbwtw** [comment]
@eailfly 我升级到 9 月 2 日（大概）之后就没有问题了

**Comment by Arrow-Li** [comment]
@johnmiroki 具体是什么版本的switch？我这边改成false还是连不上

**Comment by johnmiroki** [comment]
@Arrow-Li 官网下的最新版

**Comment by Arrow-Li** [comment]
@FelisCatus 2.5.2已经没有Proxy script not initialized的错误，但是还是连不上，显示SSL_ERROR_BAD_CERT_DOMAIN.

**Comment by daocang** [comment]
代理模式改为http就可以用了

**Comment by shikkoku** [comment]
确实改成HTTP代理就可以工作了。

**Comment by FelisCatus** [comment]
@Arrow-Li #1172.

**Comment by Arrow-Li** [comment]
还是希望能在github上先分发，火狐的审核真的好慢。。

**Comment by FelisCatus** [comment]
@Arrow-Li 一天左右就已经审核通过了啊，并不是很慢： https://addons.mozilla.org/en-US/firefox/addon/switchyomega/

**Comment by FelisCatus** [comment]
各位，请更新到最新 Nightly (>= 2017-09-18) 和最新 SwitchyOmega >= 2.5.4 即可使用远程 DNS.

Please update to latest Nightly build (>= 2017-09-18) and latest SwitchyOmega >= 2.5.4 for remote DNS.

**Comment by Arrow-Li** [comment]
@FelisCatus 提个问题，因为57之后的Firefox是不支持旧式扩展的，很多Firefox的精华扩展也都放弃更新了。最新的56beta和56release还是没解决这个bug，能不能有办法让switchy在56版本支持socks5呢。

**Comment by nopyhe** [comment]
@Arrow-Li  并不能，一些所需要的特性（https://bugzilla.mozilla.org/show_bug.cgi?id=1381290 ）刚刚加入Firefox，realease版本还不支持。另外，beta版本应该已经升级到57了……

**Comment by shikkoku** [comment]
然而57还没推送到Beta Channel

**Comment by Arrow-Li** [comment]
我已经从beta channel切回release了。57没办法当主力用的，太多扩展不支持了。

**Comment by huamao** [comment]
SwitchyOmega Nightly版本怎么获取，没找到地址。
