### ISSUE TITLE
no enough ip  和   GAEProxy状态信息  请检查浏览器代理设置。

### ISSUE THREAD

**Issue by DelingAlieZ10** [FelisCatus/SwitchyOmega#1175]
![image](https://user-images.githubusercontent.com/27910120/29249834-cd7a7844-8069-11e7-905b-1f0273f576b5.png)
![image](https://user-images.githubusercontent.com/27910120/29249847-db46330a-8069-11e7-8641-aeed430abc25.png)
请告知如何解决

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3141.7 Safari/537.36

**Comment by celeron533** [comment]
看上去似乎和本项目无关？

**Comment by Arrow-Li** [comment]
这是你XX-Net搜不到可用ip 和switchy没有任何关系
同时你gae的证书导入了么
去这里提issue [XX-Net](https://github.com/XX-net/XX-Net/issues)

**Comment by FelisCatus** [comment]
总之是代理服务器问题吧，与本项目无关。
