### ISSUE TITLE
搭配SS使用时，SS使用全局模式还是PAC模式？

### ISSUE THREAD

**Issue by Mingfeng0204** [FelisCatus/SwitchyOmega#1176]
大家好，新手来了。SwitchyOmega搭配SS使用时，SS应该选择全局模式还是PAC模式呢？如果选择PAC模式，那么SS中的PAC和SwitchyOmega中的GFWList有优先顺序吗？谢谢。

**Comment by FelisCatus** [comment]
这里不是论坛，而是仅限于 SwitchyOmega 项目本身的故障报告和改进等讨论。这里大部分人对 SS 都不了解。请移步 SS 相关的社群、论坛、讨论组等。
