### ISSUE TITLE
在直连失败情况下自动使用代理重新请求

### ISSUE THREAD

**Issue by lanewu** [FelisCatus/SwitchyOmega#1181]
在使用Direct和PAC Profile的情况下，如果资源请求失败，则扩展自动使用指定的Fallback代理再次请求。现在没法访问的站点太多，GFWList再怎么更新也防不胜防。

**Comment by celeron533** [comment]
以前有人提过类似的需求，但是真正规划起来有很多困难。
资源请求失败有很多种表现形式，比如DNS未找到，403，404，500,，501，502，连接重置，超时，重定向过多等。
资源请求超时若是设定一个固定的值，有些请求会被误判。同时，由于网络高峰的存在，凌晨流畅的站点在晚高峰可能会经常超时。

**Comment by lanewu** [comment]
使用的场景解决的是墙的问题，有返回码的情况是不需要自动重新请求的，不论是4xx还是5xx。平时用一般是选在PAC Profile自动判断，然后访问某个网站如果失败了，我都会手动切换到Proxy Profile全部走代理再试一次这个网站。此外即使是因为直连网络不流畅导致超时，其实也是符合这个建议的适用范围的，用户要的只是把页面正常读出来，能直连最好，如果不能那么走一下代理也无妨。

**Comment by celeron533** [comment]
那可以试试白名单

**Comment by FelisCatus** [comment]
关掉了， SwitchyOmega 是代理设置软件，不是翻墙软件。这个问题无法在“设置”的层面解决，而必须在“请求”或者“协议”的层面实现。具体说明见 #550.
