### ISSUE TITLE
在Firefox上开启无效

### ISSUE THREAD

**Issue by springmarker** [FelisCatus/SwitchyOmega#1182]
开启了代理，但是没有效果，在百度上搜索“IP”，显示的仍然是我的本地IP，同样其他国外网站同样没有效果。在Chrome上就非常正常

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://gsp0.baidu.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
#1171.
