### ISSUE TITLE
规则列表设置填GFWLIST网址并选择autoproxy后，立即更新情景模式按钮不能点

### ISSUE THREAD

**Issue by TankMing** [FelisCatus/SwitchyOmega#1184]
规则列表设置填GFWLIST网址并选择autoproxy后，立即更新情景模式按钮还是不能点，点击应用选项后规则列表网址变空，即没保存成功。昨天更新了chrome，有关系吗？

**Comment by tldzyx** [comment]
遇到一样的问题, 代理设置不了验证用户名和密码, pac情景无法更新, 自动切换也不能用.

**Comment by tldzyx** [comment]
![image](https://user-images.githubusercontent.com/5987706/29484602-d2fe11ba-84f4-11e7-8559-b491d421d80d.png)
chrome看了下, 一堆脚本错误, 不知道是不是这个原因

**Comment by wenliyang** [comment]
看了下更新说明

禁用了 Firefox 中的 PAC 情景模式。（无法工作）

可能是这个造成的，我用的 Cent Browser 也碰到同样问题，不象是浏览器原因，以前的 SwitchyOmega
 版本无此情况

**Comment by azuis** [comment]
遇到相同问题。而且 pac 模式下 pac url 会消失。

**Comment by FelisCatus** [comment]
应该是更新 Angular 导致的，我马上修。

**Comment by FelisCatus** [comment]
v2.5.2 已经修复。
