### ISSUE TITLE
规则列表网址输入后无法点击立即更新按钮

### ISSUE THREAD

**Issue by changyinliangbaikai** [FelisCatus/SwitchyOmega#1185]
SwitchyOmega 2.5.1
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by fredericky123** [comment]
同遇到这个问题

**Comment by fuheinv** [comment]
同遇此问题

**Comment by FelisCatus** [comment]
#1184
