### ISSUE TITLE
“立即更新情景模式”不可用

### ISSUE THREAD

**Issue by banbiantan** [FelisCatus/SwitchyOmega#1186]
在“情景模式”创建“自由切换模式”后，发现在“规则列表设置”里的“立即更新情景模式”按键不可用。在输入“规则列表网址”以后仍不可用，具体表现为按键始终呈灰色，光标移至按键上方显示“禁止”的图标。
我是通过这个网址的教程设置的
https://daofeng.591mogu.com/shimakazego/browserConfig?b=chrome

SwitchyOmega 2.5.1
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Comment by fuheinv** [comment]
我的也是这个问题

**Comment by FelisCatus** [comment]
#1184
