### ISSUE TITLE
PAC情景模式下 不显示“立即更新情景模式”

### ISSUE THREAD

**Issue by wxnsddz** [FelisCatus/SwitchyOmega#1187]
无论怎么输入PAC文件的地址 “立即更新情景模式”按钮 都不会显示
同时之前保存的PAC情景模式中的PAC文件地址也会消失，但是仍显示“立即更新情景模式”按钮

SwitchyOmega 2.5.1 Chrome 60.0.3112.101

**Comment by FelisCatus** [comment]
#1184
