### ISSUE TITLE
为何“立即更新情景模式”始终为灰色，无法按

### ISSUE THREAD

**Issue by shiqianlu** [FelisCatus/SwitchyOmega#1190]
在规则列表网址那里已经填上了gfwlist的地址，而且点击了保存，但是下方的立即更新始终按不动

![image](https://user-images.githubusercontent.com/31175443/29492536-c23b7252-85b0-11e7-83be-b8647db7bda5.png)

**Comment by FelisCatus** [comment]
#1184, 更新到 v2.5.2 即可。
