### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by haodong** [FelisCatus/SwitchyOmega#1192]
Some pages have a lot of external links, which are difficult to add into SwitchyOmega rule. But in the same time, we are also visiting other web pages which need only the common rule. Hope SeitchyOmega can add a new "Condition Type" that when connecting to such web page, it can force all related link to be proxied or directed.

**Comment by FelisCatus** [comment]
See [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#can-you-add-support-for-tab-based-or-window-based-switching).
