### ISSUE TITLE
你好，最近不知道为什么谷歌也很难登录，包括搜索必须弄成direct才能连接，然后YouTube以及提特尔也不能登录，不管怎么调试，希望能帮忙解决一下，感谢

### ISSUE THREAD

**Issue by Rabbitzzc** [FelisCatus/SwitchyOmega#1193]
SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与此项目无关。
