### ISSUE TITLE
Feature Request: Condition based on chrome.system.network.getNetworkInterfaces

### ISSUE THREAD

**Issue by gabrielsoldani** [FelisCatus/SwitchyOmega#1194]
Use case: There's a public Wi-Fi network to which I frequently connect which requires a proxy to access the Internet. I want Proxy SwitchyOmega to be able to detect when I'm in that network and switch to the appropriate proxy settings, and switch back to direct connection when I'm not in that network.

Chrome doesn't seem to allow extensions to list the SSID(s) of the active connection(s) as of yet, but it does let you get some information such as your local IP address and the prefix length of the IP address through the [chrome.system.network.getNetworkInterfaces](https://developer.chrome.com/apps/system_network#method-getNetworkInterfaces) API.

**Comment by FelisCatus** [comment]
Thanks for suggesting the network API, but it's only available to apps, not extensions. Please see #197 for alternative proposals and feel free to join the conversation.
