### ISSUE TITLE
auto switch -> Rule List Config -> Rule List URL 

### ISSUE THREAD

**Issue by skarsgal** [FelisCatus/SwitchyOmega#1196]
Hi,
I am using SwitchyOmega v2.5.2 with Chromium 62.0.3194.0 (dev:) in ..
-> auto switch -> Rule List Config -> Rule List URL - and I ask to add, in next version, a suggested URL for download the file 'gfwlist.txt' as follows: 'https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt'
(the project on GitHub is at 'https://github.com/gfwlist/gfwlist').
Thanks

**Comment by FelisCatus** [comment]
We have no plans to recommend or include gfwlist in anyway. But you are free to subscribe to it yourself if it works well for you.

**Comment by cicku** [comment]
GFWList is an embracive list which may be unapt for all kinds of scenes.

Meanwhile there is also a truncated version of GFWList at: `https://github.com/gfwlist/tinylist`, thus choices are up to users.
