### ISSUE TITLE
No profiles under Firefox Private mode

### ISSUE THREAD

**Issue by peakvision** [FelisCatus/SwitchyOmega#1197]
No profiles(include 2 default profiles: 'proxy' and 'auto switch') under Firefox Private mode

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

**Comment by nopyhe** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/1163
