### ISSUE TITLE
SwitchyOmega 工作不稳定

### ISSUE THREAD

**Issue by megaslx** [FelisCatus/SwitchyOmega#1198]
经常会显示正在建立安全连接，然后就卡住不动了，重启浏览器后就立刻正常了

SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by FelisCatus** [comment]
这 100% 不是 SwitchyOmega 的问题。
