### ISSUE TITLE
Request: use toLocaleString() for lastUpdate on User Interface

### ISSUE THREAD

**Issue by yfdyh000** [FelisCatus/SwitchyOmega#1199]
i.e. `options_ruleListLastUpdate`.

**Comment by RichBron** [comment]
Dear @FelisCatus  , how can i contact you? I have a cooperative suggestion. Can you please give your e-mail or skype?

**Comment by FelisCatus** [comment]
@RichBron Hi, right now I'm not interested in suggestions to advertise, collect user data, or promote proxy/VPN servers. However, if you want to propose something to be done to make another software work with SwitchyOmega, please feel free to open an issue.

**Comment by FelisCatus** [comment]
This is caused by change in loading order of the localization script during Angular upgrade. It affects everything related to localized formats including date. A fix is committed and will be released soon.

**Comment by FelisCatus** [comment]
v2.5.3 published on Chrome Web Store. Firefox version awaiting review on AMO.

**Comment by FelisCatus** [comment]
SwitchyOmega 2.5.4 published with the fix.
