### ISSUE TITLE
loose profiles in incognito mode / private navigation

### ISSUE THREAD

**Issue by akarayn** [FelisCatus/SwitchyOmega#1200]
Hello,
I'm using Firefox 57.
In normal mode I see all my defined proxies, no problem. 
In private mode I only see [Direct], [System proxy], + Add Condition, a blank line, options
My defined proxies are missing

Thank you

SwitchyOmega 2.5.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by nopyhe** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/1163
