### ISSUE TITLE
On Firefox 57 Linux has SSL_ERROR_BAD_CERT_DOMAIN issue

### ISSUE THREAD

**Issue by eailfly** [FelisCatus/SwitchyOmega#1201]
我在linux的firefox nightly上使用switchyomega，全新的profile，只安装switchyomega，访问google.com时显示如下错误，使用pan的话可以正常访问，这个证书是SwitchyOmega自带的吗？
![2017-09-01-163726_1920x1004_scrot](https://user-images.githubusercontent.com/3424220/29962095-6f28a4da-8f34-11e7-8bbc-b8924f9382df.png)

**Comment by yfdyh000** [comment]
你设置的代理有问题吧，怎么重定向到百度了。

**Comment by eailfly** [comment]
我的代理应该没有问题，是我自建的ShadowSocks，而且用全局代理或者pan做代理插件访问一切正常，只有SwitchyOmega有这个问题

**Comment by FelisCatus** [comment]
SwitchyOmega 只进行代理设置，不涉及协议和网络通信部分。证书肯定不是 SwitchyOmega 带的，不如自己找找看可能是哪里来的，比如看看证书详情，签发者之类的。我个人强烈怀疑您所处的网络环境遭到 DNS 劫持（例如需要网页登录的 WiFi 热点等），请勿绕过警告，也不要输入任何个人信息。

使用 SOCKS5 代理的场合，请尝试在 `about:config` 里设置 `network.proxy.socks_remote_dns` 为 `true`. 可能是因为 DNS 的原因导致的差异。如果 DNS 也走代理的话可能可以回避此问题。

**Comment by eailfly** [comment]
已确认问题，证书错误是我这里网络的问题，SwitchyOmega的问题是没有生效，根本没有走代理，所以出现了直连是会出现的证书错误的问题，我再查一下为什么代理没有生效

**Comment by FelisCatus** [comment]
很可能是 #1171.
