### ISSUE TITLE
SOCKS5 能否支持下用户密码验证？

### ISSUE THREAD

**Issue by SmallSO** [FelisCatus/SwitchyOmega#1203]
如题“SOCKS5 能否支持下用户密码验证？”

SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by celeron533** [comment]
#291
