### ISSUE TITLE
在隐私模式下无法正常工作

### ISSUE THREAD

**Issue by lxd0130** [FelisCatus/SwitchyOmega#1204]
<img width="391" alt="1" src="https://user-images.githubusercontent.com/19763937/30012442-683f47ec-9172-11e7-9abd-9105880768b5.png">
在隐私模式下只有系统连接和直接连接。无法进行自动切换

SwitchyOmega 2.5.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by celeron533** [comment]
#1163

**Comment by lxd0130** [comment]
尝试在cookie中添加例外。。但是在隐身模式下还是显示不出来。
