### ISSUE TITLE
使用GFWList自动切换模式时能通过代理解析被屏蔽的域名吗

### ISSUE THREAD

**Issue by alkeni** [FelisCatus/SwitchyOmega#1205]
很多时候需要切换到完全代理模式才可以连接被屏蔽网站

**Comment by celeron533** [comment]
取决于gfwlist有没有涵盖你的目标地址

**Comment by alkeni** [comment]
twitter涵盖了吧，切到完全代理模式就可以连接了，之后再切换回gfwlist自动模式还是一直可以保持连接

**Comment by FelisCatus** [comment]
可能是 Twitter 网页本身加载了，但其中有些资源，例如脚本没有正常加载。这种情况 SwitchyOmega 的图标上会显示数字提示，点击打开菜单，选择未加载资源即可看到那些资源。如果有些资源确认没涵盖，请反馈到 gfwlist.

**Comment by cicku** [comment]
@alkeni 赶紧反馈给我……虽然twitter不太可能
