### ISSUE TITLE
建议为`添加条件到情景模式`添加快捷键

### ISSUE THREAD

**Issue by dodying** [FelisCatus/SwitchyOmega#1206]
原先需要点击图标再点击'资源未加载'
有时候面板加载的时间还可能过长，给人卡顿的感觉

顺便问一下，启用同步会同步在线规则吗

**Comment by FelisCatus** [comment]
按 `Alt+Shift+O` 再按 `A` 即可添加规则。如果要打开未加载资源按 `Alt+Shift+O` 再按 `R`.

菜单中的每个项目都有快捷键，详情可以在打开菜单后按 `?` 键查看帮助。

启用同步会同步在线规则的网址，但不会同步在线规则的文字内容。当然，另一台设备上也会自动更新下载规则。
