### ISSUE TITLE
Does not authenticate with Nord VPN

### ISSUE THREAD

**Issue by AnaranBluto** [FelisCatus/SwitchyOmega#1207]
I configured SwitchyOmega to authenticate with a selected Nord VPN server.  However, the VPN always prompts me for my credentials.  When I used FoxyProxy (the pre-5.0 version), it would authenticate with Nord VPN successfully.

SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
    "level": "warn"
}
```

**Comment by celeron533** [comment]
Web proxy is not VPN. They are totally different things.

**Comment by FelisCatus** [comment]
Closing this since SwitchyOmega is not related to VPN in any way. If you meant "proxy server" instead of "VPN server", please re-open.
