### ISSUE TITLE
vpn频繁提示用户名密码

### ISSUE THREAD

**Issue by rockingdice** [FelisCatus/SwitchyOmega#1209]
可以不要每次都提醒vpn的用户名密码吗？我有一个很长的list都是随机选服务器的，每次都要输入密码好麻烦。能否加一个规则，在一个配置里的用户名密码用默认配置的，如果连不上再提示

SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Comment by FelisCatus** [comment]
VPN? 感觉走错地方了吧，  SwitchyOmega 是代理设置软件，和 VPN 设置无关。

**Comment by rockingdice** [comment]
那么vpn的用户名密码 switchyomega并没有涉及到？假如能记住或者自动填写用户名密码就好了

**Comment by celeron533** [comment]
没有涉及也不可能涉及。

**Comment by lifavor** [comment]
代理端口右侧有个小锁，点击设置用户名和密码。如果你有多个代理，先写填写第一个代理，将你的整个配置（json format）导出以后，将第一个代理的密码粘贴到其他代理。如果你会 json 读写，用代码操作会更快

There is a small lock on the right side of the proxy port. Click to set the username and password. If you have multiple agents, first fill in the first agent, export your entire configuration (json format), and paste the password of the first agent into the other agent. If you are amiliar with json read and write, it will be faster to use code to do these.

**Comment by rockingdice** [comment]
@lifavor 我使用了AutoAuth来解决了这个问题

**Comment by wangjin511** [comment]
> @lifavor 我使用了AutoAuth来解决了这个问题

你好，请问怎么解决的？
