### ISSUE TITLE
Possible malware masquerading as SwitchyOmega on Chrome web store?

### ISSUE THREAD

**Issue by CRWdog193** [FelisCatus/SwitchyOmega#1210]
Went to re-install SwitchyOmega. Just searched on the Webstore. To my surprise, I found two.

There's the "real" one.

There's also another, called "Proxy For Switchyomega", author "freevpns", under "Productivity". Uses the same graphic/logo as the one . Version 1.11, with 211 users. 10.03 KiB in size:

https://chrome.google.com/webstore/detail/proxy-for-switchyomega/mpfgdfdgeijcclgbibkabggckdcahcdm?hl=en-US

Their webpage http://www.freevpnsdownload.com/vpn/proxy-switchyomega-chrome-extension-download.html doesn't exactly inspire confidence either.

**Comment by FelisCatus** [comment]
Thanks for letting me know. It is indeed malware.

Please help us by clicking on the Report Abuse button on that one's Chrome Web Store listing under the bottom-right panel, next to "Additional Information".

**Comment by FelisCatus** [comment]
The malware has been since removed from Chrome Web Store. Thanks again for the report!
