### ISSUE TITLE
isn't work on windows firefox?

### ISSUE THREAD

**Issue by crackself** [FelisCatus/SwitchyOmega#1211]
Windows10 64位 nightly Firefox57，无法正常使用

SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by nopyhe** [comment]
你的Nightly版本是最新的嘛？之前出现过这个问题https://github.com/FelisCatus/SwitchyOmega/issues/1171，但是在2017-08-26及以后的版本应该是修复了。

**Comment by crackself** [comment]
确是最新的，每天自动更新版本

**Comment by benzBrake** [comment]
你是不是用的socks5代理？我也是最新版，习惯通过socks5连接ss，发现也报这个错，换成http就没事了

**Comment by crackself** [comment]
啊。。。还有这中操作。习惯性思维ss代理用socks5

**Comment by FelisCatus** [comment]
#1171.

**Comment by celeron533** [comment]
ss确实只能处理socks5，所以后来加了provixy作为中介
