### ISSUE TITLE
Allow System Proxy to be the default/fallback for an auto switch proxy

### ISSUE THREAD

**Issue by DarrenBishop** [FelisCatus/SwitchyOmega#1214]
I have quite an elaborate `auto switch` proxy rule set to hit 4 different deployment environments (AWS VPCs) with pointing to dynamic (somewhat ephemeral) SSH SOCKS5 proxies.

Of course there is the _rest of the world_, which needs to go through the coorporate firewall which I have setup via my Mac network location... so really just want to delegate _rest of the world_ traffic to the System Proxy; other than the proxy configurations I have set up, `DIRECT` is the only option.

SwitchyOmega 2.5.2
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Comment by FelisCatus** [comment]
See [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#why-cant-i-select-system-proxy-in-switch-profiles).

**Comment by DarrenBishop** [comment]
Your FAQ does not address my use case.

But thanks for trying!
