### ISSUE TITLE
Firefox版本被拦截的广告也会显示未加载

### ISSUE THREAD

**Issue by Jerry-1984** [FelisCatus/SwitchyOmega#1216]
如题，打开同一个国内页面，比如：http://fanyi.baidu.com/，Firefox显示12个资源未加载，Chrome没有显示。这些未加载的应该是被去广告扩展拦截了，目前Firefox版无法判断是因为什么原因未加载吗？

**Comment by nopyhe** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/102#issuecomment-296414942

**Comment by yfdyh000** [comment]
@FelisCatus 我在最新Nightly测试的结果，会触发`onErrorOccurred`，里面有 error:"NS_ERROR_ABORT" 等信息。
[block openpage work.zip](https://github.com/FelisCatus/SwitchyOmega/files/1308806/block.openpage.work.zip)
[block cssloading work.zip](https://github.com/FelisCatus/SwitchyOmega/files/1308807/block.cssloading.work.zip)

**Comment by FelisCatus** [comment]
@yfdyh000 这挺好的，等我加下错误代码判断……

**Comment by FelisCatus** [comment]
#1191 已经修复。很快会发布更新。

**Comment by FelisCatus** [comment]
v2.5.3 已经提交审核。后续更新见 #1191.
