### ISSUE TITLE
chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/about

### ISSUE THREAD

**Issue by JOANNAHADESS** [FelisCatus/SwitchyOmega#1217]
SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

**Comment by FelisCatus** [comment]
？
