### ISSUE TITLE
Will it support Thunderbird?

### ISSUE THREAD

**Issue by wooowooo** [FelisCatus/SwitchyOmega#1218]
.

**Comment by FelisCatus** [comment]
https://support.mozilla.org/en-US/questions/1145386

**Comment by asmwarrior** [comment]
Hi, it now year 2019, and the latest Thunderbird official release is 60.4.0 (sounds like it use the Quantum browser engine?). I can successfully install the SwitchyOmega 2.5.20 xpi file to the Thunderibrd, but the bad thing is, I can't open the add on's option page, it just shows a blank page. Any way to use the SwitchyOmaga under the new Thunderbird? Thanks.

**Comment by oott-one** [comment]
a great need for  SwitchyOmega now, since no other working.

**Comment by lybtongji** [comment]
I really need this extension working in Thunderbird too.

**Comment by asmwarrior** [comment]
To the official developer: can this issue be reopened?  @FelisCatus  Thanks.
