### ISSUE TITLE
如何快速切换代理服务器地址

### ISSUE THREAD

**Issue by wangchuang-chn** [FelisCatus/SwitchyOmega#1219]
我有3台代理服务器。分别是1，2，3
同时我建立了一个auto switch规则列表，默认使用1号代理、
那么我如何在不变更规则列表时使用不同的代理服务器呢。（因为手动创建的规则列表比较多，如果每次在切换代理服务器时全部都进行修改会很繁琐）

![snipaste_20170919_093658](https://user-images.githubusercontent.com/17327178/30572069-2f57f5ac-9d1e-11e7-88a9-ecf8105fa6e2.png)

**Comment by wenliyang** [comment]
使用“虚情景模式”

https://github.com/FelisCatus/SwitchyOmega/issues/739
