### ISSUE TITLE
不能给情景模式换颜色，只能删除以后新建

### ISSUE THREAD

**Issue by sgrjyb** [FelisCatus/SwitchyOmega#1220]
SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36

**Comment by FelisCatus** [comment]
点情景模式左上角的色块就能换颜色了。如果不能的话，麻烦说下试着修改的时候发生了什么。

**Comment by sgrjyb** [comment]
可以了
