### ISSUE TITLE
希望改进状态图标

### ISSUE THREAD

**Issue by ahdung** [FelisCatus/SwitchyOmega#1222]
首先我说的是这个：
![_20170921131037](https://user-images.githubusercontent.com/12094247/30679766-4f77ce3c-9ece-11e7-8019-9707bfea2c96.png)

我想我明白目前这种图标的呈现逻辑，即内圈指示是否处于智能切换，外圈指示是否正在使用代理以及何种代理，对吗？但它的问题在于，区分不够明显，色彩的选择也让表意不够清楚。
作为从SS过来的用户，非常适应SS的图标表达方式，让我们回顾一下：

![a](https://user-images.githubusercontent.com/12094247/30680448-40b5efb0-9ed2-11e7-9ba4-ab7b955a77fd.png)
利用全图灰度和彩色、有无子图示的组合来指示状态，我的感受是一目了然，不需要刻意去研究都能get到意思，再来看看目前的图标：

![b](https://user-images.githubusercontent.com/12094247/30680764-07f2ef64-9ed4-11e7-9461-9b9bcd9fb95f.png)
我感觉就不是那么直观了，事实上我是在提出这个问题时，有意去研究了一下，才明白其中的表现逻辑，虽然不难弄明白~总共也就那么几种组合，但实际使用中，仍然很难一眼看去就知道它的意思，我想这是纯色扁平元素的表现力先天不如拟物元素造成的。

总之我个人非常喜欢旧版的图标，非常期望得到改进。
另外，能在github放心的用母语提issue的感觉真好。

**Comment by celeron533** [comment]
类似的issue很早有人提过，不过一直没有很好的方案

**Comment by onplus** [comment]
可以自己修改颜色。
用取色器获取工具栏色值，在情景模式左上角的色块修改

**Comment by ahdung** [comment]
@celeron533 不认为这东西很难设计，退一万步还有SS的可以借鉴

**Comment by FelisCatus** [comment]
有关讨论请移步 #107. 基本上需要一个好的方案，这边才会去做。图标方案必须支持自定义任何颜色，而原有的地球图标只有那几种颜色，所以不行。

**Comment by ahdung** [comment]
@FelisCatus 反对关闭我的讨论；反对你的图标颜色必须支持自定义的意见，为什么“必须”，这是哪里来的真理？我认为好的设计意味着负责有担当，挨吹挨骂都自己担着，只给个色块完了交给用户自己去填色这是不负责的心态。

**Comment by celeron533** [comment]
@ahdung  这是个免费开源项目，作者没有从这个项目获得任何盈利，连买咖啡的钱都没有。和一般的商业项目不同，作者没有必要无限制的担当所有责任。
因为是开源项目，你可以自己fork下来修改后自己用。

**Comment by FelisCatus** [comment]
@ahdung 我只是说之前有一个相关的讨论串了，在 #107. 如果我们要讨论的话，继续在那边讨论可能会更合适。 GitHub 这边的惯例都是同一个话题在同一个 Issue 下讨论的，重复的都会被关，并无赞同或者不赞同的意思。如果每个人都在不同的讨论串下回复，整理起来会非常困难，请理解。

“必须”确实只是我的一家之言。如果有更合适的方案，欢迎提出。不过“自定义颜色”这个功能现在已经在那里了，如果要去掉的话代价不小呢，必须新的方案足够优秀的话才能权衡吧？ 不过再一次，如果要发表意见，建议先看一遍 #107 之前的讨论，然后再在 #107 下面评论。

**Comment by ahdung** [comment]
@celeron533 我并没有表达作者有任何义务的意思，所谓反对，是对这种设计观点的一种讨论，言辞是有些激烈，但我是基于换做是我的项目，我也能接受这种虽不和善但就事论事的碰撞，正所谓直抒己见。如果你觉得这样不礼貌，那我表示接受你的批评。
@FelisCatus 好的，我有新意见会往107提。多嘴说句，诚心感谢您的付出和创造，但有槽点我还是会吐:)
