### ISSUE TITLE
在Firefox的隐私窗口中图标显示不正常

### ISSUE THREAD

**Issue by chndzcl** [FelisCatus/SwitchyOmega#1224]
SwitchyOmega 2.5.4
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0

如果打开的FF窗口是隐私窗口 ，SwitchOmega图标显示不正常。可以在正常窗口用SwitchOmega切换代理模式，所以暂不影响使用。

**Comment by FelisCatus** [comment]
#1163.
