### ISSUE TITLE
Quick Switch bug

### ISSUE THREAD

**Issue by Choutouketsu** [FelisCatus/SwitchyOmega#1225]
**Quick Switch bug:** 
Step 1: check "√" to enable quick switch in Settings Panel and apply changes, then it works well as a cycle by left click the shortcut at the topright of Chrome.
![_20170926082657](https://user-images.githubusercontent.com/24585116/30837226-fb33aaf0-a295-11e7-943f-0c9bf314d7c6.png)

Step 2: right click on the shortcut at the topright of Chrome, you can find the "√" is not where it should be, but the cycle mode of quick switch is indeed working.
![_20170926084450](https://user-images.githubusercontent.com/24585116/30837363-02eb0f4e-a297-11e7-8b56-adfbea7285a6.png)

SwitchyOmega 2.5.4
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

**Comment by FelisCatus** [comment]
Thanks for the report. I will look into it later.

**Comment by Choutouketsu** [comment]
@FelisCatus and we need thank you for your dedication. I like the extension very much.

**Comment by FelisCatus** [comment]
Fixed on master. Since this is a minor fix, I will publish a release at a later time. In the meantime, feel free to grab an unsigned testing build from https://circleci.com/gh/FelisCatus/SwitchyOmega/14#artifacts/containers/0

**Comment by Choutouketsu** [comment]
thanks

**Comment by FelisCatus** [comment]
Fixed in v2.5.5.

**Comment by Choutouketsu** [comment]
fine now.
