### ISSUE TITLE
插件不能正常工作

### ISSUE THREAD

**Issue by RichardKuroshio** [FelisCatus/SwitchyOmega#1226]
Chrome配合lantern使用仅在第一次安装之后成功使用，重启之后所有需要翻墙的网站都失效了，无论是自动切换还是指定代理

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
lantern仅仅会设置你的系统代理，和SwitchyOmega基本没有联系

**Comment by RichardKuroshio** [comment]
不是这样的。
出于各种原因，我关掉了它的系统代理。按它提供的地址和端口手动配置代理。而同样使用这个插件的火狐就一切正常。

**Comment by FelisCatus** [comment]
我觉得吧，首先试下切换成全局模式（弹出菜单中选择代理的那个情景模式，而不是自动切换）看看是否能使用。如果全局能用但是自动切换不能用，到选项页面的自动切换情景模式那里，查看规则列表是否正常，可以点下立即更新试试看。注意规则列表本身的地址也可能需要代理才能访问，此时应该试试看把规则列表的域名加到自动切换中，然后用弹出菜单切换到自动切换模式，然后再点更新。

如果全局和自动切换都不能用，一般是代理冲突问题。请禁用其他控制代理的扩展、去广告扩展，等等，然后再试。也可以地址栏输入 `chrome://net-internals/#proxy` 然后查看页面上的内容，可以把内容复制粘贴到这里。

**Comment by RichardKuroshio** [comment]
[proxy.txt](https://github.com/FelisCatus/SwitchyOmega/files/1335737/proxy.txt)
依然没有解决，因为Chrome是新装的，所以也没有装很多插件
只好把proxy复制下来了。

**Comment by FelisCatus** [comment]
请把代理协议的 `HTTPS` 改成 `HTTP` 试试看。顺便确认下端口号是否设置正确。

**Comment by x000zh** [comment]
我这边也是，console没有报错， 换回switchSharp就没问题

**Comment by FelisCatus** [comment]
暂时关掉了。如果有新的信息请直接回复。
