### ISSUE TITLE
why chrome addon switchyomega change request

### ISSUE THREAD

**Issue by wangxiexe** [FelisCatus/SwitchyOmega#1227]
I am doing web develop and I use chrome proxy addons switchyomega to do quick proxy setting.

The proxy server I am using is based on node express, which is running on localhost 3000

I noticed that when I turn on proxy (which redirects my web page request to nodejs express which runs on localhost 3000 ), the request object received by express changed a little bit

e.g.

If I type http://localhost:3000 in address bar, without proxy addon turned on, in node express I get a request object with url property value "/" But when I turn on proxy, I get a request object with url property value "localhost:3000"

Any idea what is going on when the chrome proxy addon is on ? Thanks.

**Comment by FelisCatus** [comment]
SwitchyOmega never changes web requests. It just instructs Chrome to use the proxy provided. For any differences, you should look at your proxy server.
