### ISSUE TITLE
Feature request: (auto)switch rule based on network

### ISSUE THREAD

**Issue by Frank071** [FelisCatus/SwitchyOmega#1228]
It would be really helpful to be able to tune the AutoSwitch behaviour based on the network where you are in. Real working example: when I work from home I have to use a proxy to connect to some systems, this is where AutoSwitch kicks in. However when I am at work, there is no need for a proxy and this is when AutoSwitch should preferably not reroute the request. This could be done using a rule if only the condition 'network ip' and/or 'network name' would exist. I do not know however if this is at all possible within the browser context.

**Comment by celeron533** [comment]
PAC is an industrial standard, it uses JavaScript to "route" the request proxy with pre-defined functions.
PAC is running in sandbox for security concern. Perhaps it is not easy to get current browser's/host's network configurations.

**Comment by FelisCatus** [comment]
#197. We need more input there.
