### ISSUE TITLE
SwitchyOmega在360安全浏览器9.1.0.346版本的无痕模式下不能打开需要代理的网站

### ISSUE THREAD

**Issue by thegreatname** [FelisCatus/SwitchyOmega#1229]
无痕模式下不止是无法切换代理，就连设置成全局模式也无法打开需要代理的网站，而标准模式下可以，请排查原因并解决。

**Comment by nopyhe** [comment]
切换到极速模式试试？
不能切换代理这个问题是Firefox的……

**Comment by thegreatname** [comment]
全局代理模式也打不开，只能在标准模式才打得开

**Comment by celeron533** [comment]
一般来说无痕模式为了保护隐私，默认不允许使用扩展

**Comment by thegreatname** [comment]
现在我回退8.1.1可以用无痕代理了

**Comment by FelisCatus** [comment]
看上去像是浏览器的问题，不是我能解决的。

顺便有一件事……可以试试看打开扩展管理界面，然后查看是否有“允许在无痕模式下使用”之类的选项。 Chromium 是有这个选项的，至于 360 ，我没用过所以不知道。
