### ISSUE TITLE
Displays wrong connection in auto-mode

### ISSUE THREAD

**Issue by x4t3a** [FelisCatus/SwitchyOmega#1230]
Hello,
Switchy displays wrong connection type in Auto Switch Mode, version 1.10.6.
For example, there are 2 proxy profiles, "9090" and "local".
"9090" is a ssh socks proxy run on localhost:9090, and "local" is local network corporate proxy.
"9090" is used as the default route in Switch Rules, and local is used for `*.local/*` wildcard (wiki.local, jira.local, etc.)
When connecting to any site (for example, fb:) when mouse pointer is above Switchy icon, it shows: "Auto Switch Mode; Active Page Proxy: [Direct Connection]". Tho actually it uses the "9090" proxy as if I turn off "9090", the page can't be loaded. Btw, for *.local sites it displays just the same status, but actually uses the "local" proxy.

**Comment by celeron533** [comment]
Firefox or Chrome? Which build?
Do you have any PAC file used for "9090"?

**Comment by FelisCatus** [comment]
I think you must be using SwitchySharp / Proxy Switchy! based on your version number "version 1.10.6". If you are using SwitchySharp, please install SwitchyOmega and your options will be migrated to the latest versions where the issues should be fixed.

If you are using Proxy Switchy!, then you have came to the wrong place. But you can still install SwitchyOmega as you wish and configure your proxies again.
