### ISSUE TITLE
快速切换的情景模式出现重复项目

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#1232]
在  界面 -> 快速切换 -> 不循环切换的情景模式 (拖动到上面的框中启用切换)
中拖动情景模式到框外，这个情景模式就消失了！ 消失了啊。。。再怎么操作也不会回来了

SwitchyOmega 2.5.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by FelisCatus** [comment]
还能这样啊……等我看看

**Comment by FelisCatus** [comment]
我这里没法重现，无论怎么拖动，情景模式只会进入两个框之一。能麻烦您录个视频或者 GIF 之类的吗？

**Comment by Justsoos** [comment]
由于目前还有很多规则没备份，还没有重装SwichyOmega，可能我表述有问题。
目前，是如下图这样，情景模式下的可选项实际上至少有4个以上，但现在是空空如也（被拖出框外就消失了！）
![16](https://user-images.githubusercontent.com/3480043/31340005-5341011a-ad37-11e7-811a-bc9671c98b6a.png)

**Comment by Justsoos** [comment]
补充下，已经拖过消失，再次刷新，重新进入设置，这个 【不循环切换的情景模式】框中就再也不会出现 “已经消失的情景模式”，只有再次新建的情景模式会出现在其中。但是即使是新建的，一拖出框外消失，就再不会在这个框里出现了。看起来应该是页面加载配置文件的问题？？

**Comment by FelisCatus** [comment]
请问能否导出一份选项备份文件并上传到这里？在选项界面>导入/导出点“备份选项”之类的即可。导出前可以修改代理服务器地址等信息以保护个人隐私。

**Comment by Justsoos** [comment]
如下附件，等你下载完你/我删除即可
[OmegaOptions.zip](https://github.com/FelisCatus/SwitchyOmega/files/1371786/OmegaOptions.zip)

**Comment by FelisCatus** [comment]
已复现。不知道为什么，“循环的情景模式”列表里出现了重复项目，导致出错。

请问是否还记得做过什么可能会导致有重复的事情？比如，有没有重命名过情景模式或者使用过虚情景模式的替换功能？当然不记得了也没事。

暂时解决方案：在选项界面打开控制台，输入以下代码回车：
```js
chrome.storage.local.set({'-quickSwitchProfiles': []}); chrome.runtime.reload();
```

我会在这边多加下检查，尽可能避免重复的问题。

**Comment by Justsoos** [comment]
输入此命令后运行出错：
VM189:1 Uncaught TypeError: Cannot read property 'local' of undefined
    at <anonymous>:1:16
再次进入SO内，还是老样子，已经丢失的情景模式还是没有，只有一个新建的 test （与给你的配置文件相同），没其他变化。

**Comment by FelisCatus** [comment]
@Justsoos 必须在 SwitchyOmega 的选项界面打开并输入才有效。其他页面不行。

或者也可以在扩展管理界面，打开开发者模式，在 SwitchyOmega 下面点击 `background.html` 然后在那边输入也可。

还有办法就是导出设置备份文件，然后手动打开那个文件把 `'-quickSwitchProfiles':` 后面改成 `[]`（去掉数组中所有内容），保存然后再导入。实在搞不定直接重置设置也可。

**Comment by FelisCatus** [comment]
v2.5.5 已经发布。更新到此版本即可自动去除重复项目，修复您遇到的这个问题。

**Comment by Justsoos** [comment]
有劳有劳 @FelisCatus
