### ISSUE TITLE
[FireFox] Can't load the first page with proxy

### ISSUE THREAD

**Issue by lizongzeshunshun** [FelisCatus/SwitchyOmega#1233]
SwitchyOmega Version: 2.5.4
FireFox Version: Nightly / 58.0a

I use auto switch, usually SwitchyOmega loads Google with proxy but when I set Google as the home page and start FireFox, it loads Google with [default - direct] instead of using proxy.

**Comment by FelisCatus** [comment]
Naturally it takes a while for SwitchyOmega to load and SwitchyOmega have no control over any requests that happens earlier. I don't see a straightforward solution here.

**Comment by FelisCatus** [comment]
Should be fixed by #1456.
