### ISSUE TITLE
Remote DNS with SOCKS5 and DNS leaks?

### ISSUE THREAD

**Issue by yousefamar** [FelisCatus/SwitchyOmega#1235]
I was wondering, what is the state of DNS leak risks when using SwitchyOmega with Chrome 61? The information [here](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy) seems a bit outdated.

I'm thinking that SwitchyOmega now disables prefetching by default? The setting now called "Use a prediction service to load pages more quickly" is turned off and has a little puzzle icon indicating "This setting is enforced by an extension". Is this enough to guarantee remote DNS with SOCKS5 proxies? I'm not sure that services like https://dnsleaktest.com/ would capture things like that, and nothing suspicious shows up on WireShark, but I just wanted to make sure.

Any information (and perhaps an update to that wiki page) would be much appreciated!

**Comment by FelisCatus** [comment]
SwitchyOmega does not disable prefetching. You must be using another extension that does.

The information on the wiki page still applies. It doesn't matter whether you disabled it manually or another extension does it for you. As long as it is disabled you should be fine.
