### ISSUE TITLE
选项同步 包括了情景模式的同步吗？可以在哪里看到这个同步？

### ISSUE THREAD

**Issue by zhouhounan** [FelisCatus/SwitchyOmega#1236]
SwitchyOmega 2.5.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by FelisCatus** [comment]
包括，在其他设备登录相同的 Google 账户即可看到同步。
