### ISSUE TITLE
【Firefox】Nightly 58a1 基本无效

### ISSUE THREAD

**Issue by 775405984** [FelisCatus/SwitchyOmega#1240]
无论怎样设置 SwitchyOmega，都无法接管firefox内置的代理设置。

**Comment by FelisCatus** [comment]
首先，不要在 Firefox 自己的代理设置界面里设置代理。在 Firefox Preferences 里的代理设置中，请确认选择 "Use system proxy settings". 另外也检查下系统的代理设置，也应该清空。

然后再来试试看 SwitchyOmega. 如果不能用，请右键点击 SwitchyOmega 图标，选择导出错误日志以便调试。

**Comment by FelisCatus** [comment]
暂时关掉了。如果有新的信息或者其他人可以确认这个问题，请直接回复。
