### ISSUE TITLE
Firefox版不能导入导出设置

### ISSUE THREAD

**Issue by dupontjoy** [FelisCatus/SwitchyOmega#1241]
如题, 不能导入导出设置

另外: 
有没有可能支持订阅多个List呢?

**Comment by FelisCatus** [comment]
见 #1167 ，似乎是 Firefox 的问题，更新 Firefox 即可修复。

可以订阅多个 List. 具体方式是创建多个自动切换情景，然后把这几个情景串联起来。

**Comment by dupontjoy** [comment]
好的, 我试试看
