### ISSUE TITLE
哪位大神帮忙看一下，我XX-net设置不了，按照教程一步步来的，但是设置不成功

### ISSUE THREAD

**Issue by dannie1995** [FelisCatus/SwitchyOmega#1243]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega项目与XXNet无关
