### ISSUE TITLE
empty options page

### ISSUE THREAD

**Issue by oz42** [FelisCatus/SwitchyOmega#1245]
Chromium Version 61.0.3163.100: suddenly the option page is completely empty. I also cannot switch between proxies from the menu.

**Comment by FelisCatus** [comment]
Please try right clicking on the SwitchyOmega icon and select "Save error log". Then upload the log here.

**Comment by celeron533** [comment]
I met this before. Just wait after several seconds and then try again.

**Comment by oz42** [comment]
The menu is garbeled, so I cannot save a log.

**Comment by FelisCatus** [comment]
@oz42 Is the SwitchyOmega icon on the browser toolbar (NOT the options page) still there? If so, please right-click on that icon and choose Save error log. You don't need the options page for that.

If that also doesn't work, please go to Debug Add-on and drop into the Console to see if there are any errors.

**Comment by oz42** [comment]
I just tried, but there is no "save log", just:

- options
- remove from Chromium
- remove from Chromium menu

**Comment by oz42** [comment]
BTW, browser version has changed meanwhile:
Version 62.0.3202.62

**Comment by FelisCatus** [comment]
Okay. Let's try this.

1. Open Extensions page in Chromium (`chrome://extensions/`)
2. Enable "Developer Mode" on the top-right corner.
3. Under Proxy SwitchyOmega, click on `background.html`.
4. Select the "Console" tab in the new window opened.
5. Copy & paste any error messages you see.

**Comment by oz42** [comment]
background_preload.js:4 Uncaught TypeError: Cannot set property 'log' of null
    at background_preload.js:4
    at background_preload.js:37
log_error.js:4 Uncaught TypeError: Cannot read property 'log' of null
    at window.onerror (log_error.js:4)
omega_target.min.js:8424 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
    at new BrowserStorage (omega_target.min.js:8424)
    at background.js:210
    at background.js:459
log_error.js:4 Uncaught TypeError: Cannot read property 'log' of null
    at window.onerror (log_error.js:4)

**Comment by oz42** [comment]
Tried workaround:
1. deleted profile directory, created new profile. No luck.
2. uninstalled Chromium and installed Chromium Portable 62.0.3202.62 64 bit. Now everything works as expected.

**Comment by FelisCatus** [comment]
Then it seems `localStorage` was null on your previous Chrome version... But why?

Looks like a problem with Chromium that should be fixed with an upgrade/reinstall.
