### ISSUE TITLE
切换回国内网站，出现下面提示

### ISSUE THREAD

**Issue by tauyyy** [FelisCatus/SwitchyOmega#1246]
Access Denied
Description: You are not allowed to access the document you requested.
新浪博客出现图片显示不全，不知何故？

SwitchyOmega 2.5.4
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
很有可能是代理服务器的问题，和switchyomega关系不大

**Comment by FelisCatus** [comment]
代理服务器或者网络问题，与 SwitchyOmega 无关。
