### ISSUE TITLE
显示尚未链接

### ISSUE THREAD

**Issue by Glory-Mr-R** [FelisCatus/SwitchyOmega#1247]
SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by FelisCatus** [comment]
具体发生了什么？请描述下您想要做什么事情（例如访问什么网站），本来应该怎么样，实际上出现了什么情况，哪里显示什么，越详细越好。

**Comment by Glory-Mr-R** [comment]
想要上谷歌网站，却一直显示尚未连接，我确信是按教程来的，一直都可以使用外网，昨天用软件杀了下毒，外网就无法连接了，请您修复下，谢谢


荣耀

**Comment by FelisCatus** [comment]
用软件杀毒的时候该不会把您的代理软件也杀掉了吧……总之这是代理服务器问题，与 SwitchyOmega 无关。 SwitchyOmega 只负责配置浏览器。

**Comment by Glory-Mr-R** [comment]
没有，应该是屏蔽了电脑本身的一些设置，但我不知道在哪？插件是没有问题的，若是方便，远程帮在下调试下可好


荣耀

**Comment by Glory-Mr-R** [comment]
代理服务器该如何修复呢

**Comment by celeron533** [comment]
代理服务器的实现和排错不属于本项目。
