### ISSUE TITLE
Doesn't open .onion and .i2p domains in Chromium-browsers.

### ISSUE THREAD

**Issue by M-O-Z-G** [FelisCatus/SwitchyOmega#1249]
Hi, recently compared **SwitchyOmega** with **SwitchySharp** and **FoxyProxy** on **Dragon** and **Vivaldi** browsers. Unfortunately, SwitchyOmega doesn't open **.onion** and/or **.i2p** domains. Or I miss something with it? No this problem with extensions outlined above.

**Comment by celeron533** [comment]
Have you set the rules such as URL pattern correctly?

**Comment by FelisCatus** [comment]
Does it not open `.onion` domains even if you select "proxy" from the dropdown menu?

If it works with the Proxy Profile, then feel free to add `*.onion` and `*.i2p` to Auto Switch rules and select your proxy profile for those rules. You may add any additional URLs if you want.

Or it can be the other way around -- for example, setting the default to proxy and create rules for websites that you want to use direct connection. Anyway, there shouldn't be any particular issue that is preventing SwitchyOmega from opening these URLs, but you need to make sure your configuration specifies that these URLs should go through your proxy.

**Comment by FelisCatus** [comment]
This seems to be related to remote DNS. Make sure you use `SOCKS5` proxy types if you are on Tor. See also #1295.
