### ISSUE TITLE
xxnet自动切缺失

### ISSUE THREAD

**Issue by tsungtse** [FelisCatus/SwitchyOmega#1250]
如题目所示，在代理选项中没有xxnet自动切换选项

SwitchyOmega 2.5.4
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega只是一个代理切换工具，和XXNet无关。
