### ISSUE TITLE
代理问题

### ISSUE THREAD

**Issue by Jeffbluz** [FelisCatus/SwitchyOmega#1251]
设置了代理服务器，但是代理服务没有启动，这个时候浏览任意网页都会提示无法连接代理服务器。

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://detectportal.firefox.com",
    "level": "warn"
}
```

**Comment by nopyhe** [comment]
It's expected.

**Comment by FelisCatus** [comment]
#1233.

**Comment by satanson** [comment]
@Jeffbluz  I have something need your help, can we talk via gmail or wechat, My email is ranpanf@gmail.com, and wechat is satanson_
