### ISSUE TITLE
[应用选项]点击无效

### ISSUE THREAD

**Issue by dupontjoy** [FelisCatus/SwitchyOmega#1252]
Nightly 2017-05-15
Omega 2.5.6

改动情景模式后, 点击[应用选项]没有效果

**Comment by FelisCatus** [comment]
2017-05-15 版本太旧了，请换到最新的 Nightly 再试试看。

改动情景模式后，按下应用选项，如果没反应的话，此时立即右键点击工具栏中 SwitchyOmega 的图标，选择保存错误日志，然后将错误日志上传到这里。

**Comment by FelisCatus** [comment]
暂时关掉了。如果有新的信息请直接回复。
