### ISSUE TITLE
基于 IP/路由表 的代理切换

### ISSUE THREAD

**Issue by waymao** [FelisCatus/SwitchyOmega#1253]
看Wiki中说SwitchyOmega不能支持路由表、基于 IP 或者地理位置的切换。

可是 通过PAC提供的 dnsResolve 和 isInNet 函数，按理说应该让浏览器可以通过将目标地址进行解析以实现基于IP或者GEOIP的自动切换。

不知是否已经实现 or 可以实现...

**Comment by FelisCatus** [comment]
这类切换应该交给路由表之类更底层的去解决， PAC 做这个性能太低，还有各种 DNS 请求泄露的问题，也没办法给出比较完善的方案。如果您确实需要这样的功能， SwitchyOmega 中可以新建 PAC 情景模式，里面可以输入任何 PAC 脚本，包括 `dnsResolve`. SwitchyOmega 不是不支持这些功能，只是没有提供任何特殊的图形界面（例如下拉框选项），因为弊大于利。此外，就算真的做了这种切换条件，因为 DNS 只有 PAC 可用而 Chrome 扩展不能用，所以图标显示的颜色也会出错，总之坑太多了……

顺便说一句，在 DNS 劫持/污染的环境下（比如中国大陆）， `dnsResolve` 返回的结果也并不一定是真实结果，基本上不能用来做路由依据。而如果只根据 URL 切换到 HTTP 代理，就无须做任何 DNS, 而是直接把域名发给代理服务器在那边解析。而路由表之类更底层的实现可以将 DNS 请求也经由 VPN 发送到 DNS 服务器所以可以回避此问题。
