### ISSUE TITLE
每次重启FF 57 beta之后，代理从“auto switch”切换到“直接连接”

### ISSUE THREAD

**Issue by zjuerkzhang** [FelisCatus/SwitchyOmega#1254]
SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by FelisCatus** [comment]
也许是 #1054?

**Comment by hicqu** [comment]
报告一个类似的问题：当设置 firefox 为启东时“打开之前的标签页”，而那些之前的标签页需要被auto switch判定为走代理时，重启 firefox 那些标签页会不走代理，只有刷新一下，才会走代理。

**Comment by FelisCatus** [comment]
@hicqu 那个是不同的问题，见 #1233
