### ISSUE TITLE
情景模式图标区分不够明显

### ISSUE THREAD

**Issue by arayinfree** [FelisCatus/SwitchyOmega#1256]
自动切换时,情景模式的变化有点小.是不是可以增加明显点的变化?

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
已有类似issue。
所以你的建议？

**Comment by FelisCatus** [comment]
如有建议请在 #107 提出。
