### ISSUE TITLE
ff56下Basic Authentication总是401

### ISSUE THREAD

**Issue by tornadocs** [FelisCatus/SwitchyOmega#1257]
firefox56_x64下访问Basic Authentication的网站时，不会出现登录对话框，直接显示401。禁用Proxy SwitchyOmega插件(v2.5.6)即恢复。

**Comment by FelisCatus** [comment]
请换 Firefox Nightly 最新版本再试。

这不太像是 SwitchyOmega 的问题，因为 SwitchyOmega 只处理 Proxy Authentication ，不应该处理网站的 Authentication 的。

**Comment by tornadocs** [comment]
升级到57后没有这个问题了，谢谢
