### ISSUE TITLE
点击图标无法弹出完整的菜单

### ISSUE THREAD

**Issue by logtee** [FelisCatus/SwitchyOmega#1258]
困扰好久了,设备是rMBP 2015 13寸
点击图标风大概率,菜单无法完全弹出,只显示一部分,需要多次点击才能弹出完整的菜单
https://ws1.sinaimg.cn/large/6066e886gy1fktgaxmiwij20b40dwabc.jpg
完整的菜单是这样的
https://ws1.sinaimg.cn/large/6066e886gy1fktge9zv0vj209g0ui3zu.jpg

**Comment by FelisCatus** [comment]
这个问题只能等 Chrome 修…… https://bugs.chromium.org/p/chromium/issues/detail?id=428044
