### ISSUE TITLE
使用auto-switch情景模式，手动添加*.google.com进入规则列表之后，依然每次都弹出“资源未加载"

### ISSUE THREAD

**Issue by Chen-Su** [FelisCatus/SwitchyOmega#1260]
SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
先确认未加载的资源真的是`google.com`这个域下的吗？

**Comment by FelisCatus** [comment]
资源未加载时，点开弹出菜单，选择那一项目，看域名是不是 `*.google.com` 下的。如果不是，把那些也加入规则。如果是的话，那就是单纯的网络问题或者网速慢。
