### ISSUE TITLE
为特定的窗口或标签页使用不同的情景模式

### ISSUE THREAD

**Issue by xu1sec** [FelisCatus/SwitchyOmega#1262]
虽然可以用自动切换模式，但毕竟是按固定的域名规则切换的，有时候需要对特定的页面使用全局模式，而另一些页面使用直连模式。能不能添加这个功能？

**Comment by yfdyh000** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E6%8C%89%E7%85%A7%E7%AA%97%E5%8F%A3%E6%88%96%E8%80%85%E6%A0%87%E7%AD%BE%E9%A1%B5%E6%9D%A5%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E5%90%97
