### ISSUE TITLE
百分浏览器无法使用浏览器的自带翻译了

### ISSUE THREAD

**Issue by 1608637229** [FelisCatus/SwitchyOmega#1264]
排除了下发现是switchyOMEGA的锅，开了这个插件就提示无法翻译此网页内容。关了这个插件就好了。是有冲突吗？

**Comment by FelisCatus** [comment]
首先我不是很清楚百分浏览器的翻译功能是怎么实现的，不过基本上和代理设置有关吧……

试试看开直接连接模式能不能翻译，如果能翻译那大概只需要把合适的网址加到自动切换里选择直接连接就可以了。可能需要抓包来确定翻译使用的是什么 URL. 如果直接连接模式都不能翻译那我就不知道百分浏览器那边是什么情况了，多半就是百分浏览器自己的问题。
