### ISSUE TITLE
对*开头的域名匹配做优化？

### ISSUE THREAD

**Issue by mopperwhite** [FelisCatus/SwitchyOmega#1265]
现在的pac脚本好像是用正则表达式一个一个匹配……
因为目前大部分记录都是*开头的域名匹配，如果用类似tire树的数据结构优化一下会不会更快？

比方说 *.google.co.jp => jp|co|google

存储的时候是以树存储的
```JSON
{
    ".": null,
    "com": {
        ".": null,
        "google": {
            ".": "+proxy_us"
        }
    },
    "jp": {
        ".": "+proxy_jp_1",
        "co": {
            ".": null,
            "google": "+proxy_jp_2"
        }
    },
    "cn": "DIRECT"
}
```

查找的时候就把域名splite(".")然后沿着树找下来

**Comment by mopperwhite** [comment]
然后现在的自动切换好像没办法正常处理*.i2p的域名……

**Comment by FelisCatus** [comment]
之前也有人提过，不过每次 PAC 调用似乎并不是性能瓶颈。

相比而言，加载 PAC 的时候反而有明显的延迟，可能和编译 JS 有关。因此，在加载 PAC 的时候直接创建一个很大的对象也许会让加载的时候变得更卡。

如果有性能分析或者对比之类的，那么我可以考虑下。

**Comment by mopperwhite** [comment]
@FelisCatus 试着[写了个脚本测试了一下](https://gist.github.com/mopperwhite/afa66b0bd8d2a38dc96e149e0e4e154f)

1000个URL测试
800个域名
(不过大部分URL都是在example.com下的)

结果是这样

> TIRE: 
> PARSE:	5684369 ns
> EVAL:	4340718 ns
> 
> REGEX: 
> PARSE:	1852082 ns
> EVAL:	360812706 ns

为了方便计时跑在了nodejs上

**Comment by mopperwhite** [comment]
@FelisCatus 手写了序列化的部分结果变成负优化了
这里的URL列表长度是5000

> TIRE: 
> SIZE:	37700
> CONVERT:	0.010151874 s
> LOAD:	0.005130302 s
> RUN:	0.017841983 s
> 
> REGEX: 
> SIZE:	59426
> CONVERT:	0.003792928 s
> LOAD:	0.0015003 s
> RUN:	1.60605638 s
> 
> TIRE (with optimized serialization): 
> SIZE:	33205
> CONVERT:	0.013077718 s
> LOAD:	0.005263025 s
> RUN:	0.015665708 s

确实如果到5000次都只有1s差距的话不会有太大提升……
https://gist.github.com/mopperwhite/331e8deac18144460275ce8a0d57c37a

然后因为example.com在域名接近尾部的地方而测试URL全是*.example.*可能1.6s还要砍一半

**Comment by mopperwhite** [comment]
虽然感觉用处不大还是试了下把tire树转成条件表达式……
至少不需要生成整个数据结构应该会快一些

https://gist.github.com/mopperwhite/a72e687e1663d8c50826652422a7f98b

> TIRE: 
> SIZE:	37700
> CONVERT:	0.009881389 s
> LOAD:	0.005264619 s
> RUN:	0.015410538 s
> 
> REGEX: 
> SIZE:	59426
> CONVERT:	0.003852467 s
> LOAD:	0.001443064 s
> RUN:	1.697115908 s
> 
> TIRE (with optimized serialization): 
> SIZE:	33205
> CONVERT:	0.012923046 s
> LOAD:	0.005590391 s
> RUN:	0.016353819 s
> 
> TIRE (if): 
> SIZE:	44662
> CONVERT:	0.010897673 s
> LOAD:	0.003247221 s
> RUN:	0.080046444 s

查了下chrome的PAC似乎是需要每次都eval一下……
这是对每条URL判断之前eval一次函数的结果

> TIRE: 
> SIZE:	37700
> CONVERT:	0.009810068 s
> EVAL:	1.930479137 s
> 
> REGEX: 
> SIZE:	59426
> CONVERT:	0.004313481 s
> EVAL:	2.045499155 s
> 
> TIRE (with optimized serialization): 
> SIZE:	33205
> CONVERT:	0.01123125 s
> EVAL:	1.952477896 s
> 
> TIRE (if): 
> SIZE:	44662
> CONVERT:	0.009168697 s
> EVAL:	0.297710613 s

**Comment by mopperwhite** [comment]
等等……如果用条件表达式那不还是O(n)吗……

**Comment by FelisCatus** [comment]
感谢性能测试…… Chrome 的 PAC 脚本只会执行数次，之后会调用已经加载的函数，所以是可以做预先加载的优化的。每次 `eval` 一下没有必要。还有这个测试太悲观了， `*.example.com` 的出现位置太靠后了，感觉可以试试看不同的 URL.

当然最后也是最重要的问题是，考虑到各个因素，每个 URL 应该不会超过 0.5s ，实在是收益不大，用户也几乎感觉不到差异。感觉对 SwitchyOmega 而言，做这些优化真是不太值得。如果还有进一步的测试欢迎继续探讨，不过实现这类优化在 SwitchyOmega 项目的优先级应该会非常低吧。
