### ISSUE TITLE
如何设置可以使得所有非大陆IP走代理？

### ISSUE THREAD

**Issue by Fezreal** [FelisCatus/SwitchyOmega#1267]
surge之类的话， 就有geo ip模块

**Comment by Fezreal** [comment]
ssr的windows客户端也有非geo ip的类似实现， 是根据IP段控制的。

**Comment by Fezreal** [comment]
https://www.zhukun.net/archives/8054

**Comment by celeron533** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/887#issuecomment-250890415

**Comment by Fezreal** [comment]
... 我都忘了   尴尬
