### ISSUE TITLE
SwitchyOmega 能不能 网站 打开超时 则自动开启代理 ? 并自动添加规则

### ISSUE THREAD

**Issue by sgrjyb** [FelisCatus/SwitchyOmega#1268]
发现重复了 , 改一下

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36

**Comment by 1608637229** [comment]
@FelisCatus,借楼说句话。百分浏览器就是和chrome差不多的浏览器（或者说chrome增强版）。测试了chrome同样不能翻译。直接连接可以翻译。暂时把那两个网址加入了直接链接了。好像2.55版本并没有问题。

**Comment by 1608637229** [comment]
@FelisCatus,不知道是gfwlist的锅还是2.56这个版本的锅，反正谷歌翻译的网址明明没有被墙却会被自动识别加入到走代理的通道。测试方法，关掉你的翻墙软件，随便找一个没被墙的英文网站，chrome浏览器右键的翻译成中文用不了。打开ssr就能翻译了。或者把谷歌翻译的网站加入直接连接也好了。

**Comment by FelisCatus** [comment]
@sgrjyb 由于 PAC 限制，做不到。这种功能更适合代理软件。

@1608637229 应该是 gfwlist 问题，请到那边报告。
