### ISSUE TITLE
自动切换功能不生效，直接连接也不可用

### ISSUE THREAD

**Issue by TrillStones** [FelisCatus/SwitchyOmega#1269]
自动切换功能不生效，直接连接也不可用，只有用系统代理的时候才能上youtube（本身我使用了vpn，使用safari是能正常上youtueb的）

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by FelisCatus** [comment]
最简单的方式就是看 系统代理 究竟是什么设置，然后在 SwitchyOmega 里也做同样的设置，就绝对能用了。

另外，有 VPN 就没必要设置 SwitchyOmega 了吧？
