### ISSUE TITLE
在火狐下使用多添加几个代理就会出现显示不了的情况

### ISSUE THREAD

**Issue by hackd0g** [FelisCatus/SwitchyOmega#1270]
<img width="170" alt="default" src="https://user-images.githubusercontent.com/33395732/32415770-ce19fc50-c279-11e7-95c2-0040c1fc1085.png">

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by celeron533** [comment]
Chrome下偶尔会有这个问题，可能是由于性能不足，稍后片刻再去点击看看~~~

**Comment by FelisCatus** [comment]
请问每次点击都会这样，还是有一定概率这样？打开以后一直这样还是过一会就会加载出来？

下次出现这种状况后，请关闭弹出窗口，然后立即右键点击图标，选择导出错误日志，然后上传到这里。

**Comment by hackd0g** [comment]
目前已经好用了  就是偶尔会出现这个问题。

**Comment by FelisCatus** [comment]
请先试试看 v2.5.9 版本，这个版本有可能修复此问题。如果没有修复，请提供截图和导出日志。
