### ISSUE TITLE
某一域名下所有连接都使用代理

### ISSUE THREAD

**Issue by hantuo** [FelisCatus/SwitchyOmega#1271]
如果有这个选项，可以省去很多很多规则的添加（比如 *.s3.amazonaws.com ）。从防止跟踪的角度，也提升了安全性。
建议：

- 在“切换规则”中加入这个选项，可每个规则单独配置 -- 该匹配规则所引用连接均使用该配置
- 在自动下载更新的规则列表中加入全局配置 -- 该列表中全部规则均使用该规则
- 对于主动点击的链接，可以有默认的行为（如不继承或不继承父域名配置，或新标签不继承），或支持配置

大家有什么样的考虑，欢迎讨论。

**Comment by celeron533** [comment]
PAC不支持这样的功能啊

**Comment by FelisCatus** [comment]
见 [常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E6%8C%89%E7%85%A7%E7%AA%97%E5%8F%A3%E6%88%96%E8%80%85%E6%A0%87%E7%AD%BE%E9%A1%B5%E6%9D%A5%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E5%90%97) 。
