### ISSUE TITLE
避免“重复”添加规则

### ISSUE THREAD

**Issue by hantuo** [FelisCatus/SwitchyOmega#1272]
问题：
在“N个资源未加载”和“添加条件”两个菜单中，未提示即有规则中已存在相同的条目，会造成“重复”添加规则，虽然在后台数据结构中已经去重，但会使a) 用户体验上的重复添加 b)自定义规则和自动获取列表中的规则重复（这两者之间没有做去重）

建议：
- 将“N个资源未加载”改为“N个资源未加载（M已添加）”，并在弹出对话框中自动禁用和不勾选已添加的规则
- 将“添加条件”改为“添加条件（已有规则）”，弹出对话框不变

**Comment by FelisCatus** [comment]
规则列表由于大部分人用的是 AutoProxy 规则，和通配符并不等效，又很难做，而且没办法改规则列表里的项目。 已经添加的还有 1) 直接连接 2) 相同目标情景模式 3) 不同目标情景模式 三种情况，造成太多 corner case 和判断逻辑。最后，全检查一遍性能太低了。

我个人觉得还是算了……这里对用户体验的影响并不是很大，而且如果都是自定义条件而非规则列表，用户有没有注意到重复区别不是很大。反而是太复杂的处理规则会使得用户对将要进行的操作和结果没有明确预期，不值得啊。
