### ISSUE TITLE
Trouble shooting when browser is automated to open and close

### ISSUE THREAD

**Issue by cellofello36** [FelisCatus/SwitchyOmega#1273]
Dear Support,

I am running a VPS and have 3 proxies I am using. Some software I am running is requiring my browser to open and close. 

I would like to know if SwitchyOmega can be configured to open via a different proxy everytime the browser is reopened, and how this can be achieved. A userguide as to how this can be achieved or some support from your team would be hugely appreciated.

Regards

Chris

<img width="1021" alt="screen shot 2017-11-07 at 11 12 09" src="https://user-images.githubusercontent.com/33451628/32491034-1399b0c0-c3ad-11e7-82ca-461d56bd3a17.png">

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

**Comment by FelisCatus** [comment]
I don't think this can be done. I think you would be better off using your own PAC script, and PAC scripts can be imported to SwitchyOmega via New Profile > PAC Profile.
