### ISSUE TITLE
firefox 57上貌似不起作用

### ISSUE THREAD

**Issue by EdwardAutumn** [FelisCatus/SwitchyOmega#1275]
我开了auto switch访问一个不走代理的网站(默认直接连接)，但是它依然是走的代理，然后我发现是我VPN开了全局的问题，但是在Chrome上没有这个问题，即使你开了全局，设置不走代理它就不会走代理，然后添加网站走代理的也没有走代理，很尴尬

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by EdwardAutumn** [comment]
看了一下代理设置原来是要把使用系统代理改成自动检测，火狐到处是坑啊

**Comment by franklinyu** [comment]
@FelisCatus 在 UI 上提醒一下火狐用户，或者在 Wiki 上写一下？这个太坑了……

**Comment by yfdyh000** [comment]
@EdwardAutumn 有这个说法？我的Firefox代理设置是“不使用代理服务器”，一切正常。

**Comment by yfdyh000** [comment]
@franklinyu 发现是个“坟”帖，可能已有变化。

**Comment by franklinyu** [comment]
@yfdyh000 这个 issue 的意思是，哪怕装了 SwitchyOmega，火狐的设定会 override SwitchyOmega 的设定。你如果在火狐上设置「不使用代理」，那就没办法在 SwitchyOmega 中设置「使用系统代理」。

**Comment by yfdyh000** [comment]
@franklinyu "你如果在火狐上设置「不使用代理」，那就没办法在 SwitchyOmega 中选择「使用系统代理」。" 确实存在。

https://bugzilla.mozilla.org/show_bug.cgi?id=1398900 可能相关。

**Comment by franklinyu** [comment]
那條 bug report 下面好像有人不認為這是個 bug……
