### ISSUE TITLE
能增加 解析域名IP 规则匹配吗

### ISSUE THREAD

**Issue by hcwhan** [FelisCatus/SwitchyOmega#1277]
你好
注意到现在有个 IP地址字面量 匹配, 好像只能匹配直接的IP地址形式
能增加 DNS解析域名 匹配IP模式吗
现在在用域名IP匹配只能通过PAC 然而PAC匹配结果不能体现出来 不习惯 

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by celeron533** [comment]
PAC不支持直接解析域名到IP

**Comment by FelisCatus** [comment]
见 #1253.
