### ISSUE TITLE
任何网站都无法打开，选项都打不开。

### ISSUE THREAD

**Issue by lyyx0000** [FelisCatus/SwitchyOmega#1278]
Proxy For Chrome 1.0.0.0
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega 项目，我不清楚 Proxy For Chrome 1.0.0.0 到底是啥。

**Comment by FelisCatus** [comment]
SwitchyOmega 可以在这里下载： https://github.com/FelisCatus/SwitchyOmega/releases
