### ISSUE TITLE
Do Password Protected HTTPS Proxies Work on Chrome?

### ISSUE THREAD

**Issue by ilyaigpetrov** [FelisCatus/SwitchyOmega#1280]
Hello.
In your and in the extension I develop myself I can't get password-protected HTTPS proxies to work.
Do they ever worked or are they as broken as socks authed proxies?  
HTTP proxies work.  
Platform: Chrome.
HTTPS-proxies I test do work (not with extension) in a trial version of Proxy Switcher for Windows.

**Comment by celeron533** [comment]
From the SwitchyOmega settings page, if you select a HTTPS proxy, you can see a small locker on the right hand-side which indicates there could be authenticated.

**Comment by ilyaigpetrov** [comment]
@celeron533 Have you ever used https proxies in SwitchyOmega yourself? Do they work in principal or maybe they are broken as socks proxies?

**Comment by FelisCatus** [comment]
They work in principle. I believe I tried with Squid before and it worked for me. I haven't tried with any other HTTPS proxy servers.

A quick way to test is to set the HTTPS proxy WITHOUT specifying the credentials in SwitchyOmega. If the proxy works, then you should see a popup from Chrome asking for username and password. Try filling it in and see if you can visit websites.

The credentials settings in SwitchyOmega can only provide the username and password to Chrome, thus avoiding the popup. SwitchyOmega does not do more than that. It does not implement any authentication or protocol. If you cannot see a popup, or you cannot visit any website even if you input the correct credentials, then SwitchyOmega won't work for you either.

**Comment by ilyaigpetrov** [comment]
Thanks, @FelisCatus, that was the answer I needed.
