### ISSUE TITLE
请问可以实现双重代理么？

### ISSUE THREAD

**Issue by JuanMao1997** [FelisCatus/SwitchyOmega#1281]
感谢开发如此好用的代理扩展！

我使用的是chrome 2.5.6版，

计算机上有两个代理软件布置在两个不同的端口上，

请问可以设置switchyomega# **同时使用**这两个代理么？

是虚拟情景模式么？ 

不知道我表达的是否清楚，

期待您的解答！

谢谢！

**Comment by moonfruit** [comment]
配置两个“情景模式“，使用“自动切换”，配置好规则，不同的域名走不同的代理

**Comment by FelisCatus** [comment]
能进行切换，不同网址使用不同代理。

至于双重代理，我不清楚 OP 想要表达什么意思。如果说是随机选用两个代理之一，或者先尝试某个代理再尝试另一个，需要用 PAC 脚本或 PAC 情景模式使用。如果说是代理套代理，浏览器本身并不支持此功能。
