### ISSUE TITLE
SO連接本地ip時不能連通的bug

### ISSUE THREAD

**Issue by gogonkt** [FelisCatus/SwitchyOmega#1282]
設了psi 和xxnet兩個代理，連到192.168.1.x:8085 時連不通，非要把本地運行的psi 關了才可以連通。把iIP加到SO的白名單中也不行。而用 autoproxy-ng時就不會出現，請修正此問題，感謝!

測試: firefox 56.0 / 57 beta, SwitchOmega, AutoProxy-ng, windows 7, xxnet 安裝在另一電腦，psi裝在本機

All the best
Erik

**Comment by FelisCatus** [comment]
Psi 是什么？如果是个软件的话，这个软件会不会改 Firefox 或者系统的代理设置？

Firefox 的代理机制会优先使用代理，如果 Firefox 选项或者系统设置里有代理，即使 SwitchyOmega 切换到直接连接也没有用。这个似乎是没办法修复的。

**Comment by celeron533** [comment]
PSI好像是`赛风`
