### ISSUE TITLE
能给情景模式设个文件夹么？

### ISSUE THREAD

**Issue by moonfruit** [FelisCatus/SwitchyOmega#1285]
能给情景模式设个文件夹么？
设置的情景模式太多了，导致按钮点开的下拉菜单太长了，时不时还会出现只显示一个小框的问题。

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3260.2 Safari/537.36

**Comment by FelisCatus** [comment]
小框的问题是 OS X 上 Chrome 自己的问题，请关注 Chromium 项目的相关 Issue.

情景模式太多的情况，可以将一些不常用的情景模式重命名成下划线`_`开头。下划线开头的情景模式不会在菜单显示。
