### ISSUE TITLE
关于aotu switch模式下的规则问题

### ISSUE THREAD

**Issue by thisisjin** [FelisCatus/SwitchyOmega#1286]
似乎使用autoswitch模式，所有的网站采用proxy或者direct都需要自己选择来添加一遍？
那样的话，添加了github的gfwlist也起不到作用?
另外。aotu switch模式下

规则列表规则 | (按照规则列表匹配请求)
-- | --

这个的默认设置应该是选择proxy还是direct？
![image](https://user-images.githubusercontent.com/22115417/32938189-4b4e5f3c-cbb6-11e7-80aa-6759979a290a.png)

**Comment by lindaiyu99** [comment]
![20171119151825](https://user-images.githubusercontent.com/13499588/32988332-f26592c2-cd3c-11e7-8e95-27a779481461.jpg)

**Comment by FelisCatus** [comment]
规则列表是绝对能用的，不过配置起来需要注意在表格中启用规则列表规则，并且选择合适的情景模式。正如 @lindaiyu99 所说。
