### ISSUE TITLE
Stopped working on Firefox

### ISSUE THREAD

**Issue by psamim** [FelisCatus/SwitchyOmega#1288]
Error:

SwitchyOmega 2.5.6
Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://ocsp.digicert.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
What are you trying to do? What is the expected outcome? What actually happened?

**Comment by w1ndy** [comment]
Same here, the extension stopped working after a while. Although I can open the menu, "add condition" submenu, and options page, I cannot make any modification to the settings, such as switching proxies and adding rules.
I tried to modify the settings on the options page and click the apply button. After a while, an error turned up in the debug console:
```
Error: Promised response from onMessage listener at @moz-extension://8ac55b31-3b2e-474f-b302-a9586eb0112c/js/background.js:403:3 went out of scope
 Possibly unhandled rejection: {}
```

**Comment by w1ndy** [comment]
I just enabled add-on debugging and inspected SwitchOmega. The log is filled with error messages like these
```
Error: Attempt to postMessage on disconnected port             omega_target_chromium_extension.min.js:4987:71
Unchecked lastError value: Error: Invalid tab ID: 107                  ExtensionCommon.jsm:407
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached                  log_error.js:10
```

**Comment by FelisCatus** [comment]
Seems like SwitchyOmega wrote too much logs to the point that new logs cannot be written. I can see what I can do here.

**Comment by w1ndy** [comment]
Thanks!
Felis Catus <notifications@github.com>于2017年12月26日 周二上午11:39写道：

**Comment by FelisCatus** [comment]
I'll reopen this to track the issue of `postMessage on disconnected port` and maybe a way to ignore it in the logs.

**Comment by FelisCatus** [comment]
No actually, another issue would be better. Opened #1334.

**Comment by FelisCatus** [comment]
v2.5.9 released with the fix.
