### ISSUE TITLE
Can't access webpage suffix with *.dll

### ISSUE THREAD

**Issue by davidweiguo** [FelisCatus/SwitchyOmega#1289]
SwitchyOmega 2.5.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by celeron533** [comment]
Does the address included in the rule?
Have you tried to use global proxy mode to access the webpage?

**Comment by FelisCatus** [comment]
Closing this for now. Please reply and reopen if you have more information.
