### ISSUE TITLE
建议改进情景模式“auto switch”的功能，可快速更换auto规则的代理方式。

### ISSUE THREAD

**Issue by lindaiyu99** [FelisCatus/SwitchyOmega#1290]
建议添加快捷选项，可以快速更换auto switch中的代理方式。

例：auto swich情景下，使用的v2ry代理出现问题，可以快速更换为xxnet或ss，不再需要进入omega的设置。

非常感谢你的工作！

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by celeron533** [comment]
你可以建三个auto switch规则分别对应三种代理，这样可以一键切换

**Comment by lindaiyu99** [comment]
谢谢，可能确实要改变一下使用习惯了。

**Comment by FelisCatus** [comment]
虚情景模式似乎可以解决这个。建立一个虚情景模式叫“代理”之类的，然后指向 v2ry. 在自动切换中，所有需要代理的都指向“代理”情景模式即可。这样的话，如果 v2ry 失效，可以在菜单中将 “代理”重新指向 xxnet 之类的。
