### ISSUE TITLE
Can't get contents from ultrasurf 17.0x

### ISSUE THREAD

**Issue by flydragon** [FelisCatus/SwitchyOmega#1291]
hi, 
I've met a problem shown as below:
SwitchyOmega  can't get response contents from UltraSurf 17.0x(2 or 4) (webpage show nothing but blank), but works fine with UltraSurf 16.03. 
but if I disable SwitchyOmega  and set firefox proxy setting directly, it's OK! 
so there must be something wrong with SwitchyOmega  or ff58... I don't know...

thanks a lot!

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by FelisCatus** [comment]
First, try selecting the proxy profile from the menu instead of Auto Switch mode. See if that helps.

Could you please share a screenshot of your SwitchyOmega settings (the proxy servers section) and a screenshot of your Firefox proxy settings which you did manually? There must be some differences.

**Comment by flydragon** [comment]
I've try selecting the proxy profile from the menu, but it still doesn't work. 
The screenshots of my proxy settings are shown as below:

![18540321164219](https://user-images.githubusercontent.com/698614/33159271-63c94852-d04c-11e7-9e68-058fc9f7d010.jpg)
![22](https://user-images.githubusercontent.com/698614/33159295-9d704272-d04c-11e7-8ac4-7e50143114bb.jpg)

**Comment by FelisCatus** [comment]
Can I also see the screenshot of your **Firefox proxy settings* page please? As you have said, setting firefox proxy settings directly would work. In that case, I need to compare your SwitchyOmega settings with your Firefox settings.

**Comment by flydragon** [comment]
![33](https://user-images.githubusercontent.com/698614/33465239-a60075ac-d681-11e7-91ce-e1f4a9ce4ae7.jpg)

**Comment by FelisCatus** [comment]
As shown in your Firefox proxy settings, your proxy is an HTTP proxy. Make sure to select `HTTP`, not `SOCKS5`, in SwitchyOmega.

**Comment by flydragon** [comment]
Yes, it works. Thank u! I think may something changed in US17, socks5 works fine before.
