### ISSUE TITLE
SwitchyOmega 2.5.6不可用

### ISSUE THREAD

**Issue by huamao** [FelisCatus/SwitchyOmega#1292]
SwitchyOmega 2.5.6在新版的FireFox上不可用，请尽快支持。感谢

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://www.chnfree.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
请尝试最新 Nightly 版本，然后看看是否修复。

**Comment by huamao** [comment]
最新 Nightly 版本如何获取？

**Comment by huamao** [comment]
是安装FireFox的Nightly版而不是安装SwitchyOmega的Nightly版本吗？

**Comment by FelisCatus** [comment]
Firefox 的 Nightly 版. 简单来说，在这里可以找到全语言全平台的下载列表 https://www.mozilla.org/en-US/firefox/nightly/all/

**Comment by huamao** [comment]
好的，谢谢！
