### ISSUE TITLE
无法识别跳转页面的超时

### ISSUE THREAD

**Issue by Delostik** [FelisCatus/SwitchyOmega#1293]
不知道我的标题是不是准确……
在Chrome中，比如我在google点击了连接example.com，而example的链接是无法直接访问的，那么会先跳转到google的一个redirect页面，然后跳转到Example.com，最后switchyomega提示超时，可以选择proxy方式。
但是在firefox中，会卡死在google的跳转页面，不会提示任何超时……

感谢

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by FelisCatus** [comment]
这感觉像是和 Firefox 的实现有关，也许 Firefox 检测到跳转，不会直接跳转而是后台去访问那个目标页面？总之这不是 SwitchyOmega 能控制的啊。
