### ISSUE TITLE
FX57 使用一段時間後無法添加規則或是切換

### ISSUE THREAD

**Issue by delphinuz** [FelisCatus/SwitchyOmega#1294]
Firefox57。使用大約半小時或1小時後，無法添加新的規則，按扭沒反應。此時切換proxy/direct/auto也無反應。

disable再enable也沒用，只能重新開啓firefox。

另外規則裡 *. 無效。像已添加 *.aaa.com，但 *.bbb.aaa.com無效，必需再為  *.bbb.aaa.com添加規則。

**Comment by Delostik** [comment]
我遇到了同样的问题。
但是似乎很多其他的插件用了一段时间之后有也有这种问题，会不会是浏览器的问题……

**Comment by kmvan** [comment]
Same with louzhu.
Need to restart ff.

**Comment by ConnersHua** [comment]
同样遇到

**Comment by FelisCatus** [comment]
这倒是很奇怪， Disable 再 Enable 按理来说扩展不是应该已经重启了么？如果是扩展本身的问题，那应该已经重置了才对。

感觉像是 Firefox 问题……

**Comment by FelisCatus** [comment]
另外規則裡 *. 無效。像已添加 *.aaa.com，但 *.bbb.aaa.com無效，必需再為 *.bbb.aaa.com添加規則。

如果使用的是 Host Wildcard （域名通配符）， `*.aaa.com` 应该会适用于 `ccc.bbb.aaa.com` ，不需要另外添加规则了。注意只对 Host Wildcard 有用，而对 Url Wildcard 等无效，请尽量避免使用其他类型的规则。

**Comment by delphinuz** [comment]
試著使用smartproxy也有類似的問題，只是發生的時間比較晚些。

像是 *.blogspot.com 就一直無法成功。switchyomega每次也是顯示 *.aaa.blogspot.com 而不是 *.blogspot.com。若是另一個網頁  bbb.blogspot.com，switchyomega又要求加入另一個 *.bbb.blogspot.com規則。

目前只有遇到  *.blogspot.com會發生。

**Comment by FelisCatus** [comment]
@delphinuz SwitchyOmega 给出的建议完全只根据网页 URL 生成，仅供参考。在网络不稳定的情况下，有时候即使规则已经生效，通过代理访问，仍然会出现无法加载或者加载慢的情况，此时给出的建议可能会重复，敬请注意。

**Comment by FelisCatus** [comment]
问下这边各位，用的是 Firefox Quantum 吗？以及，麻烦试下最新版 Firefox Nightly ，还会出现这样的问题吗？
