### ISSUE TITLE
 SwitchyOmega doesn't forward DNS requests via proxies

### ISSUE THREAD

**Issue by suhr** [FelisCatus/SwitchyOmega#1295]
SwitchyOmega 2.5.6
Mozilla/5.0 (X11; Linux x86_64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by FelisCatus** [comment]
On Firefox 58 it should forward DNS requests. If you have any testing results that suggests any DNS leaks, please reopen.

**Comment by suhr** [comment]
I open https://check.torproject.org/ and see:

> Congratulations. This browser is configured to use Tor.

But when I open https://3g2upl4pq6kufc4m.onion/ (duckduckgo in tor):

> Хмм. Нам не удаётся найти этот сайт. (Can't find this website)
> Мы не можем подключиться к серверу 3g2upl4pq6kufc4m.onion. (Can't connect to 3g2upl4pq6kufc4m.onion)

Meanwhile, in FoxyProxy everything works fine. But SwitchyOmega is opensource addon with a superior UI, and I'd really like to use it.

If there're some other ways to proof that SwitchyOmega indeed doesn't forward DNS on my machine, let me know.

**Comment by FelisCatus** [comment]
I can confirm SwitchyOmega sends the right instruction to Firefox to use remote proxy. Firefox should take care of the rest. I believe someone used Wireshark which can tell you whether DNS requests are sent directly. I personally has no experience on that though so I cannot help you further on that.

Also, are you using HTTP/HTTPS/SOCKS5? These three protocols are the ones with remote DNS support. If you are using Tor, then SOCKS5 should just work for you. Please keep in mind that SOCKS4 DOES NOT come with remote DNS.

**Comment by suhr** [comment]
> Please keep in mind that SOCKS4 DOES NOT come with remote DNS.

Thank you. With SOCKS5 it actually works.

**Comment by FelisCatus** [comment]
@suhr You are welcome! And thanks for the translation.
