### ISSUE TITLE
Chrome Canary 下不可用

### ISSUE THREAD

**Issue by gzzhanghao** [FelisCatus/SwitchyOmega#1297]
Chrome Canary 下调用 chrome.settings.onChange 时报错：

```
Uncaught TypeError: Error processing argument at index -1, conversion failure from undefined
    at ChromeOptions.watchProxyChange (omega_target_chromium_extension.min.js:4660)
    at background.js:274
    at background.js:459
```

SwitchyOmega 版本：2.5.6
Chome Canary 版本：64.0.3276.0

**Comment by gzzhanghao** [comment]
对应代码在：

https://github.com/FelisCatus/SwitchyOmega/blob/e432687831ef9fbeb8d03a932a37fee5ace646f2/omega-target-chromium-extension/src/module/options.coffee#L128

经查是 chromeApiPromisifyAll 对 chrome.proxy.settings 对象调用了 Object.create 方法导致，此时可以通过 proxySettings.__proto__.onChange 正常访问。

**Comment by FelisCatus** [comment]
已修复， v2.5.7 发布中。

**Comment by FelisCatus** [comment]
v2.5.8 已修复。
