### ISSUE TITLE
请教一下各位大神这个问题怎么解决比较好？

### ISSUE THREAD

**Issue by nongxi** [FelisCatus/SwitchyOmega#1298]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by FelisCatus** [comment]
什么问题？这里不是论坛，是 SwitchyOmega 项目的 bug 反馈和列表之类的。如果不是 bug ，只是要讨论，请移步其他论坛。
