### ISSUE TITLE
Firefox quantum 長時間使用後插件無反應比如添加修改更換規則之類，重啟瀏覽器即可恢復

### ISSUE THREAD

**Issue by octavianus7** [FelisCatus/SwitchyOmega#1301]
SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://fonts.gstatic.com",
    "level": "warn"
}
```

**Comment by octavianus7** [comment]
[OmegaLog_1511805343180.txt](https://github.com/FelisCatus/SwitchyOmega/files/1506985/OmegaLog_1511805343180.txt)

日誌

**Comment by FelisCatus** [comment]
很像是和 #1294 一样的问题。因为很多人汇报说其他扩展也这样，那么我怀疑是 Firefox 自己的问题。总之如果有更多信息，请到 #1294 讨论吧。
