### ISSUE TITLE
多个规则相同的PAC文件，只是本地代理的端口不同，如何合并？

### ISSUE THREAD

**Issue by yyysuo** [FelisCatus/SwitchyOmega#1302]
多个本地代理，端口不同，用SwitchyOmega建了多个PAC类型的情景模式，规则都一模一样，1个400多K，SwitchyOmega加载起来有点慢了，在SwitchyOmega现有功能里面，可以做到只保留1份PAC文件,还可以方便的切换本地代理吗?
我尝试过用代理服务器模式，但是下面只有不代理的地址列表功能；也尝试过auto switch模式，不管是AutoProxy格式还是Switchy格式，我的PAC都是不生效的。

**Comment by celeron533** [comment]
可以建一个 Virtual Profile 作为中间层

**Comment by yyysuo** [comment]
@celeron533 
貌似虚拟情况模式不能满足要求。我的需求是不放弃PAC，把PAC中的规则和代理分开，某个网址或者IP是否走代理，不是由SwitchyOmega控制，而是由PAC文件控制，在SwitchyOmega建立多个代理，指向PAC文件中的同1个代理变量，我通过在SwitchyOmega中切换代理，来控制PAC文件中采用的代理服务器。

**Comment by yyysuo** [comment]
表达的可能不是很清楚，举个例子吧。
PAC情景模式A代理：127.0.0.1:1000
PAC情景模式B代理：127.0.0.1:1100
PAC情景模式C代理：127.0.0.1:1200

A/B/C 3个PAC情景模式规则完全相同。代理的切换通过在SwitchyOmega中切换A/B/C 3个PAC情景模式来实现。这样SwitchyOmega中3个PAC情况模式中的规则部分是重复的，我的需求是把A/B/C/ 3个PAC情况模式相同的规则部分独立出来，只留下1份PAC规则来决定哪些网址和IP走代理（不由SwitchyOmega来控制），而走哪个代理由SwitchyOmega来控制。

**Comment by FelisCatus** [comment]
SwitchyOmega 中 PAC 情景模式就已经是终点了，应该是没什么办法了。估计你最好的办法就是用 3 个 PAC 情景模式。当然，你可以写点脚本之类的，从一份模版 PAC 文件生成三份对应不同代理的 PAC 文件。这个用 `sed` 之类的会很简单。
