### ISSUE TITLE
为什么使用这个之后，网站登录ip显示为8.8.8.8？

### ISSUE THREAD

**Issue by ljm1447669873** [FelisCatus/SwitchyOmega#1305]
SwitchyOmega 2.5.8
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by ljm1447669873** [comment]
设置direct的网站也是8.8.8.8

**Comment by celeron533** [comment]
这是你的代理服务器的设置，和switchyomega无关
