### ISSUE TITLE
怎样维护一个自己的规则列表

### ISSUE THREAD

**Issue by Mr-LiuDC** [FelisCatus/SwitchyOmega#1308]
请问怎样维护一套自己的GFW规则列表啊？

我看gfwlist.txt里面的内容应该是加过密，SwitchyOmega可以解析出来，

我想根据自己需要也来建立一个像gfwlist加密的规则列表，我该怎么做啊？谢谢。

@FelisCatus

**Comment by yfdyh000** [comment]
base64编码

**Comment by Mr-LiuDC** [comment]
Thanks @yfdyh000
