### ISSUE TITLE
 SwitchyOmega 不提供代理服务器、VPN等网络服务。

### ISSUE THREAD

**Issue by Smith199306** [FelisCatus/SwitchyOmega#1309]
SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by Smith199306** [comment]
SwitchyOmega 不提供代理服务器、VPN等网络服务。

**Comment by FelisCatus** [comment]
这本来就是个软件项目，并不是代理服务器提供商之类的……
