### ISSUE TITLE
只有 pac怎么使用。

### ISSUE THREAD

**Issue by LJacki** [FelisCatus/SwitchyOmega#1310]
SwitchyOmega 2.5.8
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Comment by FelisCatus** [comment]
新建 PAC 情景模式，然后粘贴 PAC 脚本内容，或者输入 PAC 网址即可。
