### ISSUE TITLE
selenium chrome session no longer catch proxy change

### ISSUE THREAD

**Issue by NajiJzr** [FelisCatus/SwitchyOmega#1311]
I was using the extension for my selenium code where I open a chrome session using its chrome driver. Your extention is the ONLY solution that worked with me which have been said [here](https://askubuntu.com/questions/853357/proxy-configuration-for-google-chrome).
After your last version It doesn't work at all now and I'm in troubles now. 
I'm using Ubuntu 16.4,
can you relate to why it stopped working ?

**Comment by 0xicl33n** [comment]
Same here, Manjaro Linux.

My proxy server is privoxy and i can load the privoxy config page on firefox just fine. Sometimes it will go through and sometimes it wont. 


```

Chromium | 62.0.3202.94 (Developer Build) (64-bit)
-- | --
Revision | 4fd852a98d66564c88736c017b0a0b0478e885ad-
OS | Linux
JavaScript | V8 6.2.414.42
Flash | (Disabled)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

```

**Comment by FelisCatus** [comment]
Could you please provide more details? For example, what did you try to do and what was different than expected? In case you are trying to set up a proxy, can you try visiting `chrome://net-internals/#proxy` and see what is shown there? Do you also have any other extension that controls proxy settings?

**Comment by FelisCatus** [comment]
Closing this for now. Please reply and reopen if you have more information.
