### ISSUE TITLE
Startup profile seems to not be working

### ISSUE THREAD

**Issue by zmorris85** [FelisCatus/SwitchyOmega#1313]
Go into Options
Go to Interface
Select [System Proxy] as Startup profile
Open Chrome and select another proxy
Close Chrome
Open Chrome

Expected: Chrome to launch with the [System Proxy] selected
Actual: Chrome launched with the other proxy I had switched to

Note: After looking at this, it looks like this works if I choose to **Quit** Chrome, but I would expect the Startup profile to be loaded when launching a new window

SwitchyOmega 2.5.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega does not provide per-window proxy settings due to technical limitations. If you want to have two windows with different profiles open, you can try creating two different "Persons" in Chrome and install SwitchyOmega separately on each.
