### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by YonYYXU** [FelisCatus/SwitchyOmega#1314]
Options << Options#applyProfile [
    "system"
]
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]
Options << Options#patch [
    {
        "+auto switch": [
            {
                "color": "#99dd99",
                "defaultProfileName": "direct",
                "name": "auto switch",
                "profileType": "SwitchProfile",
                "rules": [
                    {
                        "condition": {
                            "conditionType": "HostWildcardCondition",
                            "pattern": "internal.example.com"
                        },
                        "profileName": "direct"
                    },
                    {
                        "condition": {
                            "conditionType": "HostWildcardCondition",
                            "pattern": "*.example.com"
                        },
                        "profileName": "proxy"
                    }
                ]
            },
            0,
            0
        ]
    }
]
Options << Options#patch [
    {
        "+proxy": [
            {
                "bypassList": [
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "127.0.0.1"
                    },
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "::1"
                    },
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "localhost"
                    }
                ],
                "color": "#99ccee",
                "fallbackProxy": {
                    "host": "<secret>",
                    "port": "<secret>",
                    "scheme": "http"
                },
                "name": "proxy",
                "profileType": "FixedProfile"
            },
            0,
            0
        ],
        "+Localhost": [
            {
                "profileType": "FixedProfile",
                "name": "Localhost",
                "bypassList": [
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "127.0.0.1"
                    },
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "[::1]"
                    },
                    {
                        "conditionType": "BypassCondition",
                        "pattern": "localhost"
                    }
                ],
                "color": "#d497ee",
                "revision": "1602cfb6940",
                "fallbackProxy": {
                    "scheme": "socks5",
                    "port": "<secret>",
                    "host": "<secret>"
                }
            }
        ]
    }
]
Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]
Options << Options#applyProfile [
    "Localhost"
]
Options << Options#updateProfile [
    [
        "Localhost"
    ]
]
Options << Options#renameProfile [
    "Localhost",
    "Proxy"
]
Options << Options#applyProfile [
    "Proxy"
]
Options << Options#applyProfile [
    "Proxy",
    {
        "update": false
    }
]
Options << Options#updateProfile [
    [
        "Proxy"
    ]
]

SwitchyOmega 2.5.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36

**Comment by FelisCatus** [comment]
What's the error? What did you try to do and what was different than expected?
