### ISSUE TITLE
firefox57.0(64位)经常不显示按钮

### ISSUE THREAD

**Issue by joeonehe** [FelisCatus/SwitchyOmega#1315]
![default](https://user-images.githubusercontent.com/31063444/33695487-972abe8c-db38-11e7-87ae-e287188bca67.png)

如图所示，按钮显示空白，且不可点击。

![default](https://user-images.githubusercontent.com/31063444/33695511-b6a9525a-db38-11e7-890c-91f5e9f66a5f.png)
自定义的代理按钮，长时间处于不可点击状态。

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by techstay** [comment]
我情况和你差不多，有时候能看到按钮但是无法点击

**Comment by meijialun** [comment]
啊，我chrome也一样

**Comment by FelisCatus** [comment]
请试下 Firefox Nightly 然后看问题是否修复。

**Comment by FelisCatus** [comment]
现在怎么样了？

**Comment by meijialun** [comment]
Chrome65没回第一次打开都还是老一样的情况

**Comment by celeron533** [comment]
觉得是浏览器来不及解析js内容
我SSD的机器几乎没有这个问题，然而另一个hdd的机器很常见这个问题

**Comment by FelisCatus** [comment]
打开时如果是空白的话，请右键点弹窗内，选择 Inspect Element ，然后切换到 Console 看看是否有错误信息。

**Comment by FelisCatus** [comment]
先关闭了。如果有错误信息请重新开启。
