### ISSUE TITLE
设置的Burp本地代理没作用

### ISSUE THREAD

**Issue by lxzmads** [FelisCatus/SwitchyOmega#1316]
使用Burp开了本地8080端口的代理想抓取流量包，一直页面载入错误。

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
Burp 文档上说明的端口和协议是什么？（也可以给个链接或者截图）
实际上配置的 SwitchyOmega 端口和协议又是什么？（可以截图）

**Comment by lxzmads** [comment]
原来SwitchOmeha设置的是Sock5,改成HTTP发现可以正常代理。同类问题我已经看到了，谢谢！
