### ISSUE TITLE
打开浏览器第一次点击SW菜单无法完整显示内容

### ISSUE THREAD

**Issue by meijialun** [FelisCatus/SwitchyOmega#1318]
打开浏览器第一次点击SW菜单无法完整显示菜单的内容，必须再点击一次才行。每次重启后这个问题必定重现。已经有好几个月了。

SwitchyOmega 2.5.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by FelisCatus** [comment]
求个截图？

**Comment by FelisCatus** [comment]
请先试试看 v2.5.9 版本，这个版本有可能修复此问题。如果没有修复，请提供截图和导出日志。

**Comment by Fezreal** [comment]
2.5.9版本还是会这样。

**Comment by FelisCatus** [comment]
@Fezreal 请提供截图和导出日志，谢谢。截图的话，打开弹出菜单然后截图即可。导出日志可以在图标上右键然后选导出日志，然后上传到这里。

**Comment by Fezreal** [comment]
@FelisCatus 
![tim 20180119110705](https://user-images.githubusercontent.com/6703674/35133021-0ad30302-fd09-11e7-9017-7d9f6b6f4efd.png)

[OmegaLog_1516331267418.txt](https://github.com/FelisCatus/SwitchyOmega/files/1645182/OmegaLog_1516331267418.txt)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by FelisCatus** [comment]
看上去也似乎没啥问题，怎么会这样呢……

总之问下是第一次打开菜单会这样，还是一直这样？如果是第一次打开这样的话，打开浏览器之后等多久再点菜单可以恢复？

是否开启有自动清理 Cookies / 缓存之类的设置或者装类似的插件？是否有使用系统垃圾清理软件（比如 CCleaner? ）

**Comment by Fezreal** [comment]
chrome仅仅装了3个扩展 , lastpasss   switchyomega  uBo 
不是一直都会这样的，偶尔会，没办法稳定重现。

**Comment by FelisCatus** [comment]
首先，您报告的问题应该和 OP 不是同一个问题， OP 是 Firefox 平台启动时遇到的问题。

至于您的问题，很抱歉我之前从来没遇到过或者见到过这样的报告，而且在没法稳定重现且日志为空的情况下，我真的很难着手调试、重现和修复这个问题。要说如果 SwitchyOmega 有什么不同的话， SwitchyOmega 是在打开菜单的时候会访问 localStorage 以及和 background 通信。据您所说，在资源不足的情况下，也许会遇到什么情况导致通信不成功？

总之，目前还有最后一个调试方式，就是在出现此问题的时候不要关闭弹窗，而是右键在弹窗内的任意位置（不是图标上）点击，然后选择 Inspect ，打开控制台，然后切换到 Console 看是否有任何错误输出。如果有的话请复制到这里。如果什么都看不到，那么我估计我也没办法了。

**Comment by FelisCatus** [comment]
先关闭了，如果有错误信息请重新开启。
