### ISSUE TITLE
Proxying based on http request and path

### ISSUE THREAD

**Issue by c0debreaker** [FelisCatus/SwitchyOmega#1319]
Is this possible?

If request is http://www.example.org, use the defined proxy ip address.
If request is http://www.example.org/getlocal, bypass proxy and let dns or /etc/hosts do its job.

Thanks!

**Comment by FelisCatus** [comment]
Yes. It is possible. In Auto Switch profile, you can create a URL Wildcard condition that says `http://www.example.org/getlocal` and select `Direct Connection` as the result. Then, create another condition with `http://www.example.org/*` and select a proxy profile.

For more information, please refer to help in Auto Switch.

**Comment by c0debreaker** [comment]
Ok, I'll try it. Thanks!
