### ISSUE TITLE
unbantu下chrome桌面版无法安装插件

### ISSUE THREAD

**Issue by caidwang** [FelisCatus/SwitchyOmega#1320]
chrome版本号我尽快告知。
但是现在的问题是我不能科学上网所以也访问不了chrome web store

**Comment by FelisCatus** [comment]
请在  https://github.com/FelisCatus/SwitchyOmega/releases 下载扩展安装包。

如果是网络问题不能安装，此问题无法修复。如果是其他问题，请告诉我你具体进行了什么操作，结果发生了什么错误/与预期不一样的情况。
