### ISSUE TITLE
关于自动切换模式下的图标问题，希望改成以前那样。

### ISSUE THREAD

**Issue by falseen** [FelisCatus/SwitchyOmega#1321]
自从升级到SwitchyOmega之后，一直有一个问题困扰着我，那就是自动切换模式下的图标问题。
就像这个Issues中描述的那样  https://github.com/FelisCatus/SwitchyOmega/issues/107
现在最大的问题是当你打开一个网址的时候，假如这个网站无法访问，那你就无法知道这个网站是走的代理还是没走代理，因为在无法打开的情况下它们的图标是一样的。这个问题说大不大，说小也不小。可能是个人习惯问题吧 ，如果实在不行，我就只能用回旧版了。

**Comment by falseen** [comment]
发现一个很尴尬的问题，用回旧版之后打开网页的速度明显变慢了很多。具体原因不明。

**Comment by FelisCatus** [comment]
无法访问时，图标颜色也还是按照规则的匹配结果来显示的。使用代理是有彩色（默认蓝色，可修改），没有使用代理是灰色。

**Comment by falseen** [comment]
@FelisCatus 但是我这里的情况是，无法访问时图标就一直都是灰色的，不会变化。

**Comment by FelisCatus** [comment]
@falseen 360极速浏览器不在本项目支持范围内，但可能凑巧能用……之前记得有人说换新版（测试版之类的）可能可以支持动态切换图标，但我记不清了……
