### ISSUE TITLE
想使用多个规则列表但是搞不懂该怎么设置.求点帮助

### ISSUE THREAD

**Issue by shinji-ikari** [FelisCatus/SwitchyOmega#1322]
情景模式有3个. 
1. ssh-d  (代理服务器)
2. GoAgent  (代理服务器)
3. auto switch   (自动切换模式)
auto switch里面设置   
规则列表规则--(按照规则列表匹配请求)--ssh-d,  规则列表格式--autoproxy ,  用的是gfwlist.txt  .

问题是没在autoswitch 里面找到可以自己添加另一个规则的地方,不是一个两个网站,而是一个文档.

https://github.com/feliscatus/switchyomega/issues/179
看过这个issue之后还是没懂该怎么弄.

目的是：代理规则gfwlist+自定义规则, 自定义规则可以随时点右上角的SO图标--添加条件来增加代理网站.
代理模式可以随便切换ssh-d或者GoAgent而不受到影响.因为有时候ssh-d会挂掉.....

感觉自己都说的有点蒙了....SO用起来感觉没autoproxy那么简易?   
没找到相关设置的指引文档之类的.可能是搜索能力太差.请问有没有相关的页面可以翻看?

**Comment by shinji-ikari** [comment]
尝试设置了一个  
4. ziyong  (自动切换模式)
然后  规则列表规则--(按照规则列表匹配请求)--auto switch  , 规则列表格式--autoproxy,  规则列表正文--这里面是从FF 的autoproxy里面到处的自定义规则.

最后发现.1-3的模式都正常用.  切换到4的时候就无法正常打开google....
求解....

**Comment by wenliyang** [comment]
使用虚情景模式

https://github.com/FelisCatus/SwitchyOmega/issues/739

**Comment by shinji-ikari** [comment]
看完弄完感觉好复杂....不过貌似是可以了.
代理服务器2个,   goagent,  ssh-d
虚拟情景1个, visual
自动切换模式3个, gfwlist-goagent,   gfwlist-ssh-d,    ziyong.
代理服务器设置好放着,  
自动切换模式3个如下设置:
gfwlist-goagent 中 规则列表规则--goagent.规则列表格式-autoproxy,列表网址-gfwlist
gfwlist-ssh-d  中 规则列表规则--ssh-d.规则列表格式-autoproxy,列表网址-gfwlist
ziyong  中 规则列表规则--visual.规则列表格式-autoproxy,规则列表正文--填上导出的自定义规则.

SO右上角选择使用  ziyong模式,  需要切换的时候点SO 选择 visual旁边的小箭头切换gfwlist-goagent或者gfwlist-ssh-d.
--------------
大概是这样了....感觉真有点复杂....
如果可以的话.还是希望能 规则通用, 模式随意切换跟autoproxy一样简单点吧....

另外就是最好能增加一个模式隐藏的设置或者按钮. 这样点击SO图标切换的时候可以少显示一些模式出来.界面上比较简洁吧.

总之感谢.大概是符合使用需求了.

**Comment by FelisCatus** [comment]
情景模式名称前加上下划线`_`即可在菜单中隐藏。

SwitchyOmega 目前支持这种使用场景的方式就是通过虚情景，如果有任何在这个基础上的改进请提出。但是 SwitchyOmega 中每个规则都必须有一个目标情景模式，不会有脱离情景模式的“通用”规则存在，这一点不会改变。
