### ISSUE TITLE
在线恢复，使用github的地址，提示备份文件格式错误

### ISSUE THREAD

**Issue by mrdulin** [FelisCatus/SwitchyOmega#1323]
![image](https://user-images.githubusercontent.com/17866683/34067627-3475ecaa-e266-11e7-8a67-59a9c0d10ba9.png)

**Comment by FelisCatus** [comment]
请使用 raw 链接，不要使用 blob 链接。 raw 链接就是 GitHub 显示文件的页面右上角的一个按钮。

blob 链接指向的是网页（HTML），而不是这个文件本身，所以不符合格式。

**Comment by mrdulin** [comment]
@FelisCatus 知道了，谢谢
