### ISSUE TITLE
每次冷启动火狐后，代理选项都会变成系统代理

### ISSUE THREAD

**Issue by nxuem** [FelisCatus/SwitchyOmega#1324]
而不是自动切换模式

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
我感觉可能是由于开了自动清空 cookies 或者之类的，见 #1054. 请先确认是不是这个情况。如果是这个情况，暂时可以通过添加到例外规则来解决，如 #1054.
