### ISSUE TITLE
其他设置->右键菜单中，可检查网页元素所使用的代理。 无法看到菜单选项

### ISSUE THREAD

**Issue by FatherOfGod** [FelisCatus/SwitchyOmega#1327]
界面->其他设置->"右键菜单中，可检查网页元素所使用的代理。"，勾选该选项后，无法在浏览器中右键看到此选项。

SwitchyOmega 2.5.8
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by FelisCatus** [comment]
必须右键点击链接、图片、视频之类的，具有不同 URL 的资源方可有效。对于页面本身或者文字等内容无效。
