### ISSUE TITLE
刨除pac，怎么让chrome代理认证上网？

### ISSUE THREAD

**Issue by gokusleepy2** [FelisCatus/SwitchyOmega#1328]
请问，如果我不需要自动代理，仅仅是chrome 代理主机+端口+用户名+密码，怎么通过JS实现chrome设置？

**Comment by FelisCatus** [comment]
只需在 SwitchyOmega 中建立代理情景模式，然后填写需要的信息即可。在图标弹出菜单中，请选择这个代理情景模式本身，不需要使用自动切换功能。这样的话不会生成 PAC, 性能也基本没什么损失。
