### ISSUE TITLE
白名单和更智能的自动切换

### ISSUE THREAD

**Issue by wavebit** [FelisCatus/SwitchyOmega#1329]
大家好
我之前使用的是SwitchySharp,现在切换到SwitchyOmega。
自动切换配置的规则是https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
现在问题是打开一些网站经常提示有未加载的资源（一般是国外的），即使是国内的一些网站，每次都要手动添加规则。不知道怎么配置才能更智能些，比如遇到无法加载的资源时自动走代理，或者是配置白名单规则，国内直连，国外走代理服务器？

**Comment by celeron533** [comment]
以前有人问过类似的问题。资源未加载有很多原因，有时候只是网速缓慢或者对方服务器一时抽风。。。全都搞成自动也会导致奇怪的问题

**Comment by wavebit** [comment]
那么白名单呢？

**Comment by FelisCatus** [comment]
白名单完全可行，只需要在自动切换中，把默认规则设置成使用代理模式即可。然后针对不需要经过代理的网址，添加规则时，只需要选择“直接连接”模式即可。

**Comment by wavebit** [comment]
有没有与黑名单https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt对应的白名单文件？

**Comment by FelisCatus** [comment]
@wavebit 所有用户都可以制作和发布，但具体有谁做了，发布在哪里，我是不知道的……最好去论坛之类的地方问问看。

**Comment by wavebit** [comment]
好的
