### ISSUE TITLE
功能请求：对于socks5代理启用dns代理

### ISSUE THREAD

**Issue by RevolverOcelotA** [FelisCatus/SwitchyOmega#1331]
功夫网会进行dns投毒。

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://icons.duckduckgo.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
在 FF 版本号超过 20170918220054 的版本下，此功能已经启用。在之前的版本，此功能无法实现。如果您使用的版本没有 SOCKS5 远程 DNS 支持，建议安装最新 Nightly 版。
