### ISSUE TITLE
can not  apply changes when change proxy ip

### ISSUE THREAD

**Issue by Infixz** [FelisCatus/SwitchyOmega#1333]
SwitchyOmega 2.5.6
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
What happens when you press the button? If it doesn't save, could you please right-click on the SwitchyOmega icon and select `Save error log` and then upload the error log here?

**Comment by FelisCatus** [comment]
Please try v2.5.9 first. It may fix your problem. If not, please export the log in v2.5.9 as described above.

**Comment by Infixz** [comment]
nothing happen when I press that happer. After restart firefox 57 it works again, so when it happened again I will report the error.

**Comment by FelisCatus** [comment]
Closing this for now. Please re-open when it happens again.
