### ISSUE TITLE
pac代理IP 优选

### ISSUE THREAD

**Issue by my123456github** [FelisCatus/SwitchyOmega#1336]
若同一pac 代理里多个 ip代理,如var proxy = "socks5 ip1; socks5 ip2; proxy ip3; proxy ip4; proxy 127.0.0.1:1080;";
1, 若前几个代理失效了,此 pac 代理基本上不能启用后面的有效的 IP代理,
2, 若多个代理 ip 都有效, 但是前面的 多个代理 IP 很慢很卡,后面即使有后快的代理 ip, 也不能启用后面极速的代理 ip.

**Comment by celeron533** [comment]
#1335 请不要重复提问

**Comment by my123456github** [comment]
知道了,谢谢.

**Comment by my123456github** [comment]
已删除重复的问题了.

**Comment by FelisCatus** [comment]
返回多个代理服务器的情况， Chrome 本身决定如何从列表中选择，此问题与 SwitchyOmega 无关。

如果您觉得 Chrome 的选择机制还有待改进，请到 Chromium 项目提交 Issue.

**Comment by my123456github** [comment]
谢谢.
