### ISSUE TITLE
自动切换模式下Google账号登录不了的问题，点击Next没有任何反应

### ISSUE THREAD

**Issue by qu0423** [FelisCatus/SwitchyOmega#1337]
测试了火狐57，Chrome63，Opera49，都出现自动切换模式下Google账号登录不了的问题，点击Next没有任何反应，切换到全局代理一切正常

![2017-12-27_174156](https://user-images.githubusercontent.com/9220139/34377814-c8a9bd96-eb2d-11e7-8803-18314c51415c.png)

**Comment by celeron533** [comment]
你的自动代理切换列表没有覆盖到该网页需要的资源。
至于这个列表的内容。。。其实是和SwitchyOmega没有多大关系的

**Comment by FelisCatus** [comment]
规则列表问题，请到规则列表维护者那边反馈。
