### ISSUE TITLE
bootmarks and settings of chrome browser can't sync via SwitchyOmega anymore

### ISSUE THREAD

**Issue by WeiqiChenCN** [FelisCatus/SwitchyOmega#1338]
Hi, thank you for your plugin of chrome browser, which has been helping me a lot.

I noticed a for long time, I can access google.com with the help of SwitchyOmega. That's normal. But it seem that the chrome browser can't sync its Bookmarks via SwitchyOmega.

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36

**Comment by WeiqiChenCN** [comment]
Hi? Is anyone bothered by this problem?
SwitchyOmega can proxy your browsing traffic, also can proxy your chrome's setting traffic before.
But now, It only can proxy your browsing traffic, but not for chrome browser itself anymore.
If you want to sync the bootmarks and settings of chrome browser, you need a “Transparent agent” or "System proxy", which is very not convenient...

**Comment by FelisCatus** [comment]
If you are using Auto Switch, try selecting the proxy profile and let it stay for a while to see if bookmarks can be synchronized. If not, then there is no way to fix it.

If bookmarks can be synchronized in proxy profile but not Auto Switch, then you need to add the relevant URLs to your switch rules. The special page `chrome://net-internals` may give you some hints on what URLs are requested as part of synchronization. If you are using a rule list, you can also let them know and suggest adding those URLs.

**Comment by chenwq3** [comment]
Problem resolved!
Thanks for the tip about `chrome://net-internals` !!
Here is the solution, add additional proxy rules:
```
*.googleapis.com +proxy
*.googleusercontent.com +proxy
```

Best Regards,
Weiqi Chen.
