### ISSUE TITLE
Gmail邮箱无法显示邮件正文中的图片。

### ISSUE THREAD

**Issue by xyf0754** [FelisCatus/SwitchyOmega#1339]
浏览器版本 ：chrome 版本 63.0.3239.84（正式版本） （32 位）

操作系统：windows 10 64位

翻墙工具：shadowsocks 4.06 

问题：当使用 Proxy SwitchyOmega 插件时gmail邮箱无法现实正文中的图片。禁用插件shadowsocks使用全局代理则不会出现这个问题。
 

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by celeron533** [comment]
可能是你的规则列表有问题

**Comment by FelisCatus** [comment]
规则列表或者代理服务器问题，与 SwitchyOmega 无关。如果您觉得您订阅的规则列表没有覆盖那些资源，请向规则列表维护者反馈。
