### ISSUE TITLE
窄屏页面中个别下拉列表给遮挡不能选择问题

### ISSUE THREAD

**Issue by agutools** [FelisCatus/SwitchyOmega#1341]
如题，附图：
https://img.vim-cn.com/56/90bf3a249d7d16637af6c55317bfc6f09ee36b.jpg 

SwitchyOmega 2.5.9
Mozilla/5.0 (Android 4.4.4; Mobile; rv:57.0) Gecko/57.0 Firefox/57.0

**Comment by agutools** [comment]
横屏：
https://img.vim-cn.com/fd/b49f51ed8e16e21bcced4e19a05a464faf4989.jpg

**Comment by FelisCatus** [comment]
感谢反馈。我需要一点时间考虑下这个应该怎么办。

**Comment by neozhang** [comment]
在 Windows 10 的多显示器场景下，也会出现类似的问题。
https://www.dropbox.com/s/ov14lrzbol0kpiy/proxyswitchomega_win_multi_display.PNG?dl=0

**Comment by FelisCatus** [comment]
@neozhang 这个是浏览器渲染的问题吧……那上面的一行字原本应该是 tooltip （鼠标悬停在图标上显示），我还从来没看到过显示在弹出窗口的情况。不管怎么说，这不是 SwitchyOmega 可以控制的。所以用鼠标悬停在图标上来查看就好，点击之后的那一行就无视吧。

**Comment by neozhang** [comment]
@FelisCatus 不是的，这个在我的笔记本显示器上是正常的，但是到外接的显示器上，因为分辨率不同，所以界面就渲染出错了。

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by FelisCatus** [comment]
@neozhang 这应该是 Firefox 对于 popup 的宽度测量不正确，建议去 FF 那边开 Issue.

**Comment by agutools** [comment]
马上测试，没问题！谢谢！！  ^_^
https://img.vim-cn.com/22/ecf1415c5b57f7fbc0f4b3317cd13ecc78d5ff.png
