### ISSUE TITLE
View onedrive.live.com HSTS error

### ISSUE THREAD

**Issue by richard-2017** [FelisCatus/SwitchyOmega#1343]
View onedrive.live.com ,use switchyomega and shadowsocksr , set proxy in switchomega 127.0.0.1 port:1080, auto-switch mode, display  HSTS error. When I  use SSTap with global proxy ,  I can view onedrive.live.com. I don't know why this happended.  Do I set switchomega incorretly?

**Comment by FelisCatus** [comment]
This is unrelated to SwitchyOmega.
