### ISSUE TITLE
无法加载google系网站某些资源  比如图片 加载不全

### ISSUE THREAD

**Issue by irpan730** [FelisCatus/SwitchyOmega#1344]
无法加载google系网站某些资源  比如图片 加载不全

SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by FelisCatus** [comment]
规则列表或者代理服务器问题，与 SwitchyOmega 无关。如果您觉得您订阅的规则列表没有覆盖那些资源，请向规则列表维护者反馈。
