### ISSUE TITLE
请问，如果是带有密码的socks5代理，密码在哪填写？

### ISSUE THREAD

**Issue by kuroidark** [FelisCatus/SwitchyOmega#1346]
请问，如果是带有密码的socks5代理，密码在哪填写？

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by FelisCatus** [comment]
见 [常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8D%E6%94%AF%E6%8C%81-socks5-%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E5%AF%86%E7%A0%81%E8%AE%A4%E8%AF%81%E5%90%97)。
