### ISSUE TITLE
Proxy doesn't turn off

### ISSUE THREAD

**Issue by noeferrero** [FelisCatus/SwitchyOmega#1347]
SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36

**Comment by FelisCatus** [comment]
* What are you trying to achieve?
* What did you do? Please describe in detailed steps
* What did not work as expected? What's the expected result and actual result?
