### ISSUE TITLE
根据IP段确定是否走代理

### ISSUE THREAD

**Issue by Fezreal** [FelisCatus/SwitchyOmega#1349]
[chn_ip.txt](https://github.com/FelisCatus/SwitchyOmega/files/1624821/chn_ip.txt)

怎么把这个应用到SwitchyOmega内？
我直接复制粘贴到‘不代理的地址列表’发现无法生效。

**Comment by FelisCatus** [comment]
见[常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#switchyomega-%E8%83%BD%E6%94%AF%E6%8C%81%E8%B7%AF%E7%94%B1%E8%A1%A8%E5%9F%BA%E4%BA%8E-ip-%E6%88%96%E8%80%85%E5%9C%B0%E7%90%86%E4%BD%8D%E7%BD%AE%E7%9A%84%E5%88%87%E6%8D%A2%E5%90%97)。
