### ISSUE TITLE
firefox Quantum 57.0.4(64位)版本无法使用SwitchyOmega自动模式

### ISSUE THREAD

**Issue by ID-8765** [FelisCatus/SwitchyOmega#1351]
firefox Quantum 57.0.4(64位)版本无法使用SwitchyOmega自动模式，在自动模式下，无法正常访问想要访问的网站。

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://show.re.taobao.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
请重启浏览器，选择自动切换模式，然后随便访问几个有问题的网站，然后右键点击 SwitchyOmega 图标，选择导出日志然后上传到这里。

**Comment by FelisCatus** [comment]
这个问题还能重现吗？
