### ISSUE TITLE
Can not  browse the google website! 

### ISSUE THREAD

**Issue by NANOHUNT** [FelisCatus/SwitchyOmega#1353]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by FelisCatus** [comment]
The problem is usually with your network and/or proxy server, not SwitchyOmega.
