### ISSUE TITLE
Intensive logging of messages written to localStorage

### ISSUE THREAD

**Issue by va511e** [FelisCatus/SwitchyOmega#1358]
Hi

I am running SwitchyOmega on Firefox 57.0.4 and almost every second, I believe due to rules that are triggered by the requests started from the opened webpages, there is a logging message written to extension local storage. This keeps trashing my hard drive, writing all in all almost 500MB of data every 10 minutes.

I could detect this by doing a strace over the Firefox local storage process that accumulates the data. 

The message in the "log" field is:

Options << Options#applyProfile [    "rule based"][26]</ChromeOptions</ChromeOptions.prototype.setMonitorWebRequests/</<@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:4981:71[33]</WebRequestMonitor</WebRequestMonitor.prototype.setTabRequestInfo@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:6545:22[33]</WebRequestMonitor</WebRequestMonitor.prototype._tick@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:6304:13[26]</ChromeOptions</ChromeOptions.prototype.setMonitorWebRequests/</<@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:4981:71[33]</WebRequestMonitor</WebRequestMonitor.prototype.setTabRequestInfo@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:6545:22[33]</WebRequestMonitor</WebRequestMonitor.prototype._tick@moz-extension://534d5279-42b

Is there an option to turn off this logging or to to stop this kind of message being generated? Thank you.

**Comment by FelisCatus** [comment]
Could you attach a full log by right clicking on the icon and click on "Save error log"? Thanks.

Basically each request should not generate any logs unless something is going very very wrong.

**Comment by va511e** [comment]
Please find attached the log file. [OmegaLog.txt](https://github.com/FelisCatus/SwitchyOmega/files/1671263/OmegaLog.txt) As far as I can see the log is spammed with the following lines that get appended every second:

[26]</ChromeOptions</ChromeOptions.prototype.setMonitorWebRequests/</<@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:4981:71
[33]</WebRequestMonitor</WebRequestMonitor.prototype.setTabRequestInfo@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:6545:22
[33]</WebRequestMonitor</WebRequestMonitor.prototype._tick@moz-extension://534d5279-42b0-4807-87c2-b7156d059d67/js/omega_target_chromium_extension.min.js:6304:13

**Comment by FelisCatus** [comment]
See #1334. But anyway, I do believe there is a 5MB limit enforced for localStorage, which should not trash 500MB of your data. I will first get #1334 fixed but I would love to hear your findings on what files are growing.
