### ISSUE TITLE
sock5代理为什么没有填写密码的地方

### ISSUE THREAD

**Issue by bqf9979** [FelisCatus/SwitchyOmega#1359]
没有密码我没办法使用,很多用户都是

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.104 Safari/537.36 Core/1.53.4549.400 QQBrowser/9.7.12900.400

**Comment by celeron533** [comment]
#1354
