### ISSUE TITLE
无法打开其他网站

### ISSUE THREAD

**Issue by zockparty** [FelisCatus/SwitchyOmega#136]
使用SwitchyOmega 2.2.9 ，配合goagent v3.23后，目前可以打开Google系列网站，但是Facebook，Youtube等都无法打开。

SwitchyOmega 2.2.9
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36

**Comment by zockparty** [comment]
添加之后，仍然只能访问google，其他的还是不行

**Comment by FelisCatus** [comment]
@zockparty 请参考 GoAgent 教程，导入那边提供的配置备份文件。

**Comment by zockparty** [comment]
导入之后还是没有改善。。。

**Comment by zockparty** [comment]
找到问题了，建议与我有一样情况的参考文章：
http://blog.csdn.net/leos_blog/article/details/41013853#reply
