### ISSUE TITLE
不能开始

### ISSUE THREAD

**Issue by cybermay** [FelisCatus/SwitchyOmega#1360]
登陆百度账号 可以满速下载 用分享给别人(加密分享)的链接 自己下载(账号退出了)   不能开始

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36

**Comment by celeron533** [comment]
意义不明

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega ，如果反馈的是其他扩展的问题请去其他扩展。
