### ISSUE TITLE
自动模式下，google.com不走代理

### ISSUE THREAD

**Issue by SuTree** [FelisCatus/SwitchyOmega#1363]
RT,最近一段时间，google.com在自动模式下不走代理，手动添加条件走pac规则才能正常访问
为啥不识别呢？自动模式下已添加gfwlist规则

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36

**Comment by sunshineplan** [comment]
我是打开gmail或者其他google服务时，有部分链接加载超时，涉及的域名如下：
https://fonts.googleapis.com
https://www.google-analytics.com
https://fonts.gstatic.com
https://ssl.gstatic.com

规则用的是https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt，照理这些都在列表里面是要走代理的，实际感觉没走代理。我使用全局代理打开没问题，所以代理服务器肯定是ok的。


SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by celeron533** [comment]
当你访问google的时候，自动代理规则有没有命中？
![image](https://user-images.githubusercontent.com/3608762/35607111-91373746-068d-11e8-978d-e20d5feffba6.png)

**Comment by FelisCatus** [comment]
先看看图标颜色以及悬停看是否确实使用了代理吧。

**Comment by AshiakerWang** [comment]
> https://www.google-analytics.com
> 这个我这也是常显示没有代理成功
> 
> 找到原因：似乎是广告屏蔽插件导致的
> 把它们加入插件白名单就不会提示了

感谢，已经解决。
