### ISSUE TITLE
Sorry for this stupid question,but.... I just fail to set SwitchyOmega for using expressVPN (chrome)

### ISSUE THREAD

**Issue by wishpeace** [FelisCatus/SwitchyOmega#1364]
Not using PAC. Just trying to set it up like it's used to be---- I was using shadowsocks and it was fine like this
![qq 20180130185204](https://user-images.githubusercontent.com/35957304/35562552-b2261ab6-05ee-11e8-9f38-2add556083ef.png)
![qq 20180130185316](https://user-images.githubusercontent.com/35957304/35562601-dc55dd3a-05ee-11e8-80e0-9a00cfa10e30.png)

Now it's not fine when using express VPN. I'm not good at computer . I don't know how to fill in the proxy server and port now----- 127.0.0.1 :1080 doesn't work . So I open the  diagnostics file and find this.
![qq 20180130184613](https://user-images.githubusercontent.com/35957304/35562298-e6106918-05ed-11e8-8f17-230bf58005c0.png)
...and fill it in....
![qq 20180130184007](https://user-images.githubusercontent.com/35957304/35562374-254fbe1c-05ee-11e8-9dc0-c5241665a3d7.png)
Well , then ....
![qq 20180130185500](https://user-images.githubusercontent.com/35957304/35562700-25827428-05ef-11e8-8d4a-d0410c8aa7d8.png)

It works well when chosen direct link, well it's the same as turning SwitchyOmega off, isn't it....
![qq 20180130184057](https://user-images.githubusercontent.com/35957304/35562470-71f97096-05ee-11e8-9a9d-eb88ba97dad1.png)
I know it might be stupid...Anyone help me plzzzzzzzzzzzzzzzzzzzz....

**Comment by celeron533** [comment]
VPN和web代理不是同一种东西。

**Comment by FelisCatus** [comment]
本项目是代理切换软件，和 VPN 无关。
