### ISSUE TITLE
Mozilla Firefox support is highly experimental!

### ISSUE THREAD

**Issue by yotoobo** [FelisCatus/SwitchyOmega#1365]
SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
Well yeah, it is still considered experimental but it will work most of the time, hopefully.

Once everything settles a bit, I will remove the warning.
