### ISSUE TITLE
优先级的问题，图标上显示未加载资源数量的问题，切换规则问题

### ISSUE THREAD

**Issue by zgxhlee** [FelisCatus/SwitchyOmega#1366]
此款软件不错，不过还有几个问题能改善的话就更好了，如下：
1.重要问题-优先级的问题：当switchyomega切换到系统模式时，应该完全休眠-抛弃控制权，这样任何代理软件都可以用(比如浏览器代理)，否则一修改其他软件的代理，就产生冲突，每次都要手动重启switchyomega，很不方便。
2.未加载资源：因该增设自动加载模式，每次都手动选很麻烦
3.未加载资源重启视频问题：每次添加未加载资源，switchyomega都自动重启视频，影响观看，因该及时更新。
4.切换规则能不能添加组，比如同一网站的域名可以添加到一组

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FelisCatus** [comment]
同一网站的域名可以直接写一个 `*.example.com` 匹配所有，也可以在同一条规则里写 `a.example.com|b.example.com` 自己用竖线分隔。

系统模式确实是放弃控制权的，只检查代理服务器变化而不设置代理服务器。如果还有冲突那基本就是 Chrome 问题。注意，其他扩展未必会放弃控制权，所以要先装其他扩展，再安装 SwitchyOmega ，这样平时 SwitchyOmega 优先，而选择系统模式时 SwitchyOmega 放弃控制，其他扩展可以设置代理。
