### ISSUE TITLE
是这样设置的吗？我的似乎没用。

### ISSUE THREAD

**Issue by 123ysys** [FelisCatus/SwitchyOmega#1369]
![photo_2018-02-04_17-55-06](https://user-images.githubusercontent.com/27964272/35776370-34052abe-09d6-11e8-8174-1dda0d64734b.jpg)

**Comment by celeron533** [comment]
完全错误。你需要安装shadowsocks客户端

**Comment by 123ysys** [comment]
已解决了，谢谢。

**Comment by 123ysys** [comment]
![8](https://user-images.githubusercontent.com/27964272/35785418-34a7c14a-0a5b-11e8-95f2-d5aee19a431f.jpg)

**Comment by FelisCatus** [comment]
请点击图标，然后选择 Shadowsocks ，随便输入个网址看是否能连接，如果不能，请咨询服务商。
