### ISSUE TITLE
The plugin can't work well 

### ISSUE THREAD

**Issue by keymao** [FelisCatus/SwitchyOmega#137]
the autoswitch mode can't work.  It sent no request to the goagent any more  after it works well for a long time(about 6 hours).

SwitchyOmega 2.2.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
Closing this issue for now. Please provide additional information based on the questions above if you want to reopen it.
