### ISSUE TITLE
Not work Bypass List

### ISSUE THREAD

**Issue by ernestosu16** [FelisCatus/SwitchyOmega#1370]
it does not work
Bypass List
```
<local>, 10.0.0.0/8, 192.0.0.0/8
```

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0

**Comment by FelisCatus** [comment]
What doesn't work? What URL did you try and what happened?

Also, just a reminder, the bypass list should be one entry per line, not comma-delimited.

**Comment by ernestosu16** [comment]
it works, it is delimited by a comma. Change
10.0.0.0/8
192.0.0.0/8
.ecc.cu
.gcc.cu
.inet
