### ISSUE TITLE
打开国内的网站，走的直连，还一直弹未加载项目，换了手机网络还是一样，明显是插件的问题

### ISSUE THREAD

**Issue by ibule** [FelisCatus/SwitchyOmega#1372]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36

**Comment by ibule** [comment]
走的直连 没走自动规则都这样

**Comment by ibule** [comment]
你可以试试 打开知乎就是这样的  一直弹文加载数字 一直到几百多

**Comment by ibule** [comment]
Adblok引起的哈，Adbolk拦截部分广告，然后这边Proxy SwitchyOmega就会一直未加载数字一直走，关掉对网站的拦截就好了，然后清理一下DNS，Chrome清理DNS是，页面直接输入chrome://net-internals/#dns，大家有的注意一下哈。

**Comment by ibule** [comment]
麻烦作者测试一下，现在又不行了，关了广告插件还是一直提示加载未完成

**Comment by celeron533** [comment]
你需要看看是哪些项目没有加载完成。有时候你的系统底层（网络层、驱动层，hosts文件等）还有一层广告过滤软件

**Comment by celeron533** [comment]
你可以看一下是哪些内容“加载未完成”？是否影响使用？

**Comment by FelisCatus** [comment]
未加载的资源列表会如实汇报没有加载的项目，但 SwitchyOmega 有代码会检测一些常见去广告扩展屏蔽的资源，不会显示。如果关了广告插件还是一直提示加载未完成，那么应该就是网络或者操作系统层面的问题，这个 SwitchyOmega 无法修复。
