### ISSUE TITLE
自行选择smart-router，导致网页打不开

### ISSUE THREAD

**Issue by kolarnold** [FelisCatus/SwitchyOmega#1373]
自行选择smart-router，导致网页打不开。。

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by celeron533** [comment]
smart-router是什么？规则列表吗？
