### ISSUE TITLE
 A network error occurred when updating.

### ISSUE THREAD

**Issue by ram-maanikonda** [FelisCatus/SwitchyOmega#1374]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by celeron533** [comment]
Updating?

**Comment by FelisCatus** [comment]
What did you do? What is the expected result? What actually happened?
