### ISSUE TITLE
希望增加功能

### ISSUE THREAD

**Issue by xfangbao** [FelisCatus/SwitchyOmega#1376]
访问某域名的时候可以添加条件，但是一个页面当中有很多隐藏的加载域名，能不能有个办法把所有的域名都列出来添加条件？

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3346.9 Safari/537.36

**Comment by celeron533** [comment]
记得图标上会显示未加载资源数量的啊

**Comment by xfangbao** [comment]
考虑到设置白名单的时候，有些网域会被代理加载从而在数量里显示不出来。代理加载速度过慢。所以才觉得这个功能用来筛选白名单很必要。

2018年2月19日 下午1:14，"Allen Zhu" <notifications@github.com>写道：

**Comment by celeron533** [comment]
我记得图标上显示的资源未加载的数字满足以下条件之一：
1. 直接拒绝连接或者返回值不正确
2. 一定时间（如15秒）后仍未响应的

所以开了白名单后资源加载慢并没有很好的解决办法 #550

**Comment by xfangbao** [comment]
那就试试吧加载时间超时设置为1s咯


感谢提供思路。






On Tue, Feb 20, 2018 at 10:51 AM +0800, "Allen Zhu" <notifications@github.com> wrote:












我记得图标上显示的资源未加载的数字满足以下条件之一：

直接拒绝连接或者返回值不正确
一定时间（如15秒）后仍未响应的



所以开了白名单后资源加载慢并没有很好的解决办法 #550

**Comment by FelisCatus** [comment]
思考了一下，这个项目应该不会做所有域名的这种功能。如果要查看加载的资源建议使用 Chrome 开发者工具之类的。如果有其他问题请另外开 Issue.
