### ISSUE TITLE
Setup SwitchyOmega to resolve domain names on (SOCKS) proxy server

### ISSUE THREAD

**Issue by tharrrk** [FelisCatus/SwitchyOmega#1379]
Hi. Is it possible to setup this add-on to resolve domain names on the proxy server? I'm most interested in SOCKS (ssh -D) and could not find this setting. Currently testing with Firefox 56.0.2 (cannot upgrade until other plugins' issues are resolved) and add-on version 2.5.10
Thanks for such a brilliant piece of software!

**Comment by celeron533** [comment]
It's Firefox's behavior. In Chrome, it is always resolve DNS on socks5 server side.
#1295 
https://github.com/FelisCatus/SwitchyOmega/issues/1172#issuecomment-327982852

**Comment by tharrrk** [comment]
Thanks for pointing to that thread.
This seems to answer my question:
"Please update to latest Nightly build (>= 2017-09-18) and latest SwitchyOmega >= 2.5.4 for remote DNS."
So the patch on FF side seems to make it to nightly builds but was not backported to 56 or ESR. And since there seems to be no way for an extension to check whether the new object-based response is supported other than by checking version number it won't work with ESR anyway either.

Since I cannot upgrade to quantum yet, we can close this.
