### ISSUE TITLE
无法通过本地socks5隧道

### ISSUE THREAD

**Issue by kdlsw** [FelisCatus/SwitchyOmega#1380]
SwitchyOmega版本是2.5.9, chrome版本64.0.3282.167, win10 专业版 16299
用shadowsocks开了socks5的代理隧道，127.0.0.1，端口1080。迅雷等其他软件可以顺利通过隧道来实现代理。SwitchyOmega在proxy情景模式中设置了socks5 127.0.0.1 1080，但没办法成功进入隧道，shadowsocks日志是完全空的，但选择系统代理的话，就可以正常使用。请问如何调试解决？

**Comment by FelisCatus** [comment]
有迅雷的话可能是 #557，其他软件可能是使用 HTTP 方式连接的。请试试看 SwitchyOmega 里也设置成 HTTP 类型代理。另外请检查是否有其他扩展冲突（比如其他代理设置或者去广告扩展）。建议禁用 SwitchyOmega 以外所有扩展再试，还不行请重新开启这个 Issue.
