### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by qiangjiangct** [FelisCatus/SwitchyOmega#1382]
通过SwitchyOmega的情景模式不能打开任何网站，选择系统代理可以。
下图分别为配置的截图和chrome://net-internals/#proxy的截图。
希望您能帮我解决问题，谢谢。
![set](https://user-images.githubusercontent.com/31383937/36519868-e5fdf7aa-17c8-11e8-9979-f33524a02540.PNG)
![eer](https://user-images.githubusercontent.com/31383937/36519882-f0ce0ec2-17c8-11e8-8dc0-d70365c0430d.PNG)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by celeron533** [comment]
请先确认代理服务器能正常工作

**Comment by qiangjiangct** [comment]
代理服务器能正常工作，然后呢？

**Comment by celeron533** [comment]
因为从chrome的debug信息可以看出代理已被成功设置，switchyomega的任务已经完成（也没有被其他扩展程序比如unblockYouku抢走代理权）。。。后续发生了什么就不知道了

**Comment by FelisCatus** [comment]
这边可以确认 SwitchyOmega 确实已经设置了代理，协议端口和服务器都与配置完全相同。

如果还是不能访问网络，可以检查下协议、端口是否正确之类的。关于这一点请参考对应的代理服务器或代理软件说明书，或者去相应的论坛提问。 SwitchyOmega 只是一个配置工具，并不清楚你那边具体需要什么配置才能正常使用。
