### ISSUE TITLE
chrome 64.0.3282.186（正式版本） （32 位）经常ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by xinip** [FelisCatus/SwitchyOmega#1385]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

经常ERR_CONNECTION_CLOSED，socks5 代理，用firefox用代理就很正常，

**Comment by FelisCatus** [comment]
可能是 #557.

**Comment by xinip** [comment]
刚刚发现在SwitchyOmega 2.5.9的时候才会有问题，在2.5.8的时候是可以正常上网的，是不是2.5.9改了什么不兼容的代码，导致无法正常上网

**Comment by FelisCatus** [comment]
SwitchyOmega 只是个设置工具，不处理网络协议。即使有故障，也是只会出现代理设置不正确或者没有设置代理的情况，而不会出现协议的问题。
