### ISSUE TITLE
Button does not change proxy setting

### ISSUE THREAD

**Issue by ch4les** [FelisCatus/SwitchyOmega#1388]
Hi,
I used to use a different FF extension to (simply) switch between 'direct' and 'manual proxy', and after Mozilla changed in 57, I couldn't use that one any more.  I thought yours looked good, but it doesn't seem to work, whatever I do.
Maybe I'm missing something?
If I change the proxy via the FF Options page/tab, your icon doesn't change to reflect what I've done, either.
thanks,
Charles

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://www.emailorganizer.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
First, please DO NOT use the FF Options page to set your proxy. SwitchyOmega cannot control that and cannot detect any changes there. Please make sure "System Proxy" is selected on that page.

In SwitchyOmega, modify the proxy profile as needed and make sure to select that profile from the dropdown that opens from the SwitchyOmega icon in the toolbar. Then, visit any website to see if it works. Note that Firefox looks into extension settings, Firefox settings and system settings and will use a proxy if it finds one anywhere, so even if you select Direct Connection in SwitchyOmega, Firefox may still use the system proxy settings. To work around that, please make sure to clear your system proxy (e.g. Internet Explorer settings) AND the proxy in Firefox's own settings.

Hope that helps.

**Comment by FelisCatus** [comment]
Closing due to no response. Please re-open with more details.
