### ISSUE TITLE
疑似chrome快捷键劫持

### ISSUE THREAD

**Issue by liutianfang** [FelisCatus/SwitchyOmega#1389]
ctrl+w（关闭标签页）快捷键只能使用一次，重置SwitchyOmega规则后，ctrl+w功能正常

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega 提供一个 Alt+Shift+O 的快捷键，此快捷键完全由 Chrome 控制，可以换成其他快捷键。 SwitchyOmega 不劫持/监听键盘。此问题应该与 SwitchyOmega 无关。
