### ISSUE TITLE
总是资源未加载

### ISSUE THREAD

**Issue by fnatictreo** [FelisCatus/SwitchyOmega#1390]
微博页面的秒拍视频，总是无法加载观看
插件显示X个资源未加载，添加条件后依然显示X个资源未加载，并且无法观看视频。

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:58.0) Gecko/20100101 Firefox/58.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://localhost:8085",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
这应该是网络问题，或者其他系统级别的去广告软件拦截请求导致的。 SwitchyOmega 会如实回报所有未加载的资源，是否进行添加条件等操作应该取决于实际情况。

**Comment by fnatictreo** [comment]
@FelisCatus 没有系统级别的去广告软件，只有firefox上的去广告插件

**Comment by celeron533** [comment]
>但是禁用插件，依然是未加载

所以看起来不是SwitchyOmega的问题喽？
