### ISSUE TITLE
输入PAC网址时提示下载情景模式数据时出错

### ISSUE THREAD

**Issue by et999927** [FelisCatus/SwitchyOmega#1391]
输入PAC网址时提示下载情景模式数据时出错

SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36

**Comment by FelisCatus** [comment]
请检查 PAC 网址是否正确（必须是脚本文件，不能是网页之类的，尤其注意 GitHub 需要使用 raw 链接而不是某个页面）， PAC 网址是否能通过代理访问等。

可以把 PAC 网址直接贴在地址栏里回车，看是否能正常访问。如果访问的结果是个脚本就好，如果是网页说明网址有问题，请更正再试。
