### ISSUE TITLE
可否添加一个查看当前域名使用规则的功能

### ISSUE THREAD

**Issue by fuwu1245** [FelisCatus/SwitchyOmega#1394]
比方说
打开`www.google.com`的时候，会显示当前网站是走代理的
打开`www.baidu.com`的时候，会显示当前网站是没有走代理的
这样也方便判断是否需要在自定义规则中添加当前网站

**Comment by celeron533** [comment]
鼠标悬停图标。

**Comment by fuwu1245** [comment]
如LS所言。。。
