### ISSUE TITLE
插件不能翻墙了

### ISSUE THREAD

**Issue by LQYWwi** [FelisCatus/SwitchyOmega#1396]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.119 Safari/537.36

**Comment by celeron533** [comment]
这只是个代理切换插件，翻墙只是应用环境。所以你的问题和这个插件的关系不大
