### ISSUE TITLE
需登录的代理服务器第一次打开时需弹框

### ISSUE THREAD

**Issue by yaohwu** [FelisCatus/SwitchyOmega#1397]
## 情景：

使用的代理服务器A需要登录，在SwitchyOmega配置中已经输入过了登录名和密码，如果浏览器刚打开时不是使用的此场景A，那么切换成A场景是可以正常使用的。
但是如果场景A是默认的场景，那么第一次打开浏览器总是会提示输入A的登录名和密码。如果不输入，那么就切换成成了 Auto Switch场景。

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

**Comment by FelisCatus** [comment]
Chrome 本身的设计导致先加载代理再加载 SwitchyOmega ，因此无法去掉弹窗。

至于启动的时候使用什么场景，可以在 选项页面>界面>切换选项中强制指定。可以选择代理 A, 那么 SwitchyOmega 就会在启动的时候用代理 A.
