### ISSUE TITLE
作者能否在“设定 - 界面 - 切换选项”里面增加一个复选框“兼容模式”？

### ISSUE THREAD

**Issue by cqhtyi** [FelisCatus/SwitchyOmega#140]
作者能否在“设定 - 界面 - 切换选项”里面增加一个复选框“兼容模式”？
意思就是说，在 打开新标签/关闭当前标签的时候，或者其他扩展释放代理权限之后，
强制将Proxy SwitchyOmega“的情景模式”设置为“自动切换”或者其他模式，
这样是否就可以与其他扩展兼容？
比如ADfree.Player.Offline，在更改代理之后，Proxy SwitchyOmega 就停留在了“PAC模式”，
之前使用Proxy SwitchySharp的时候，这方面的兼容性还是比较好的。

**Comment by FelisCatus** [comment]
Please upload the settings backup file to https://gist.github.com and paste the link here.

**Comment by FelisCatus** [comment]
设置里有一个“撤消其他扩展对代理的更改”的选项，本来是计划解决这个问题的。

但是目前这个选项并没有完全做好。等我有空了就抽点时间看看。

**Comment by cqhtyi** [comment]
感觉作者的回复！新年快乐！

**Comment by FelisCatus** [comment]
v2.1.10 做了点改进，不知道有没有用，可以试试看。

如果不行的话建议卸载 ADfree.Player.Offline 扩展后重新安装以提高其优先级。

**Comment by cqhtyi** [comment]
已更新至 v2.1.10 ，在优先级较低的情况下，确认无效。

**Comment by kafan15536900** [comment]
Adfree dev 内部已新增兼容模式切换:switchCompatibleMode(),需要手动进入扩展控制台运行切换

2015-01-02 0:11 GMT+08:00 cqhtyi <notifications@github.com>:
