### ISSUE TITLE
建议有个远程dns的开关

### ISSUE THREAD

**Issue by Genion** [FelisCatus/SwitchyOmega#1400]
自动切换下添加条件和gfw列表中走代理dns是本地的。用全局模式后才走代理工具的dns
我用whoer.net/zh查看的

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by celeron533** [comment]
先关闭chrome的网页预读

**Comment by Genion** [comment]
设置里都关了，可能是这个网页有问题吧，用cloudxns，dnspod检测都是正常走的是代理工具设置的Google dns。

**Comment by FelisCatus** [comment]
Chrome 里 SOCKS5 代理始终是远程解析，没法开关。但是，有一个问题可能导致 DNS 泄露，见 https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87
