### ISSUE TITLE
用户名

### ISSUE THREAD

**Issue by softxiang** [FelisCatus/SwitchyOmega#1403]
SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0

**Comment by softxiang** [comment]
socks5没有用户名，只有密码要怎么设置，火狐插件里面必须要先输入用户名，下面的密码才生效，服务器用shadowsocket搭建

**Comment by FelisCatus** [comment]
如果你问的是 Shadowsocks 之类的，那么密码需要在对应的客户端软件里设置，并不是在 SOCKS5 上的。
