### ISSUE TITLE
在chrome SwitchyOmega 2.5.9的时候才会有问题，在2.5.8的时候是可以正常上网

### ISSUE THREAD

**Issue by xinip** [FelisCatus/SwitchyOmega#1404]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36

经常ERR_CONNECTION_CLOSED，socks5 代理，用firefox用代理就很正常，
刚刚发现在chrome SwitchyOmega 2.5.9的时候才会有问题，在2.5.8的时候是可以正常上网的，是不是2.5.9改了什么不兼容的代码，导致无法正常上网

**Comment by woyounai** [comment]
SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

相同配置在使用自动切换模式mac 上没有问题，到了win上面 ，socks5 代理经常ERR_CONNECTION_CLOSED错误

**Comment by taojin0505** [comment]
2.5.10问题依旧。用2.5.8可以正常上网，但是会自动升级到2.5.9，然后就不可以。
报错：A few resources failed to load due to issues with your network, proxy server or the webpage.

系统，Debian Stretch。
chrome：Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by FelisCatus** [comment]
首先，这里可以下载旧版 SwitchyOmega: https://github.com/FelisCatus/SwitchyOmega/releases

要定位这个问题，首先禁用其他所有扩展，然后安装 2.5.8，然后打开 `chrome://net-internals/#proxy` 然后复制页面上的文字。然后升级到 2.5.9/2.5.10 然后再刷新 `chrome://net-internals/#proxy`，复制页面上的文字。请比对两者是否相同。如果不相同，请将这两个文件分别以附件形式上传到这里。如果两者相同，那么 SwitchyOmega 的任务已经完成，剩下的不是 SwitchyOmega 的问题。

@taojin0505 的情况，麻烦在错误界面点 DETAILS 然后再截图，谢谢。

**Comment by FelisCatus** [comment]
由于长时间无回复，暂且关闭。如果有尝试过或者导出日志请重新开启。
