### ISSUE TITLE
疑似引起页面和部分扩展程序崩溃

### ISSUE THREAD

**Issue by Starnightray** [FelisCatus/SwitchyOmega#1406]
部分页面（tieba，chrome设置页，twitter，weibo，视频网站，还有一些使用了flash的页面，常常还连带google搜索页）经常性崩溃，崩溃频率（崩溃发生距离打开页面的时间差）与打开这类页面的个数呈正相关。
    同时，还有一部分扩展程序（以Adblock Plus为最频繁，其他如Tampermonkey和Google在线编辑也出现过）也会发生崩溃。
    在停用过后这类现象（就目前观察来看）不复存在。
    有一个共同点是使用了flash？
    在最近的一段时间出现，尚且不明是不是在版本更新后，但是至少2月份及之前没有出现

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by FelisCatus** [comment]
Flash 自身对 PAC 的支持有问题，  SwitchyOmega 无法解决。

但至少 Google 主页不应该崩溃。我怀疑这个问题和 SwitchyOmega 并不直接相关，而是因为启用 SwitchyOmega 后占用了更多内存 / CPU 才引发的。

无论如何，建议提交崩溃报告给 Chrome.
