### ISSUE TITLE
不知原因崩溃

### ISSUE THREAD

**Issue by yyy123zc** [FelisCatus/SwitchyOmega#1408]
﻿Options << Options#applyProfile [
    "Smart-Router"
]
Options << Options#updateProfile [
    [
        "Smart-Router"
    ]
]
Options << Options#updateProfile []
Options << Options#applyProfile [
    "system"
]
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]

使用的是XX-Net，不知具体情况，开启chrome就是错误。

SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by FelisCatus** [comment]
如果 XX-Net 崩溃了，那么和 SwitchyOmega 无关，请到那边反馈。如果 Chrome 崩溃了，那么也不是 SwitchyOmega 的问题，请提交崩溃报告给 Chrome.
