### ISSUE TITLE
不关闭浏览器直接关机会导致配置文件丢失

### ISSUE THREAD

**Issue by guagua0** [FelisCatus/SwitchyOmega#1409]
代理ip和自动代理网址都会丢失，目前用的猎豹浏览器，暂时不清楚其他浏览器会不会这样

**Comment by celeron533** [comment]
这个可能是浏览器自生的问题。。。

**Comment by FelisCatus** [comment]
猎豹浏览器不在支持范围内，而且这个问题肯定是浏览器本身的问题， SwitchyOmega 无法修复。
