### ISSUE TITLE
错误日志

### ISSUE THREAD

**Issue by ysz223** [FelisCatus/SwitchyOmega#1411]
Options << Options#applyProfile [
    "自动切换"
]
Options << Options#updateProfile [
    [
        "自动切换",
        "__ruleListOf_自动切换",
        "GFWed",
        "direct"
    ]
]
Options << Options#updateProfile []
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
您的错误报告已经收到，关于您的问题，已经在其他 Issue 分别解答。

**Comment by ysz223** [comment]
感謝！
