### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by AdamGreenhill** [FelisCatus/SwitchyOmega#1414]
Hi,
I've been looking for a proxy switcher like this for Firefox Quantum for a while now, I didn't see a support/donation button anywhere? Could you please advise on how I can support this project?

Thanks,
Sentient

**Comment by FelisCatus** [comment]
We are not accepting donations at the moment. I will let you know once we do. No plans in the near future though.

For now, the best way to support this project is to contribute or recommend it to others. We also need help on issue management, bug fixing, refactoring, etc. and we would appreciate it if you can help or tell your friends about it.

**Comment by FelisCatus** [comment]
I will leave #131 open just in case someone wants to subscribe and get updates.
