### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by sorayuki-winter** [FelisCatus/SwitchyOmega#1415]
if i open a web and do nothing, the memory will continuously leak and it is not very quickly，but for a long time it will eat all my free memory (5G). when the memory is leaking, open a new tab can clear leaked memory.

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by FelisCatus** [comment]
Any snapshot or captures please? That could help a lot.

**Comment by FelisCatus** [comment]
SwitchyOmega 2.5.16 released with the new `browser.proxy.onRequest` API on Firefox. Please upgrade to FF 60+ and latest SwitchyOmega. If you still observe this issue, please open a new issue with heap dump or recording.
