### ISSUE TITLE
HTTPS proxy requests do not have Server Name Indication (SNI)

### ISSUE THREAD

**Issue by henrypijames** [FelisCatus/SwitchyOmega#1416]
I had a Caddy web server configured to function both as a normal (HTTPS only) web server and as a HTTPS proxy at the same time, and it worked fine with SwitchyOmega. Then, in order to enhance security, I changed the server configuration so it would only accept HTTPS connections for a certain domain name (via the Server Name Indication extension of TLS), but not HTTPS connections for other domain names, nor HTTPS connections to the literal IP address(es) of the server. In other words, assuming my server has the IP address of `1.2.3.4` and two domain names `example.com` and `secret.example.com`, both resolving to the same IP address of `1.2.3.4`. In the new configuration the server only accept HTTPS requests for `https://secret.example.com/`, but reject requests for `https://example.com/` and `https://1.2.3.4/`:

https://github.com/mholt/caddy/issues/2068

After this change, the normal HTTPS web server part works as intended, but the HTTPS proxy part no longer works. Apparently, even though `secret.example.com` is specified in the SwitchyOmega profile, the HTTPS proxy requests do not use SNI and therefore get rejected.

To be fair, this is probably not SwitchyOmega's fault, because using Chrome without SwitchyOmega, but with the command line parameter `--proxy-server=https://secret.example.com` doesn't work either (haven't tested Firefox, but probably the same). So the problem exist in the underlying browser(s). It may take forever to fix this problem in the browsers, but in the meantime maybe SwitchyOmega can find a way to intervene and add the proper SNI to the HTTPS proxy requests? After all, this *should* work because it is exactly why SNI was introduced in the first place.

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by FelisCatus** [comment]
SwitchyOmega is a configuration tool and it just sends proxy settings to the underlying browser. SwitchyOmega does not handle protocols on itself. So unfortunately, we cannot work around that problem.
