### ISSUE TITLE
Linux 插件不稳定问题

### ISSUE THREAD

**Issue by ysz223** [FelisCatus/SwitchyOmega#1417]
1、启动浏览器时，无法加载自定义首页；
2、运行过程中，经常遇到打不开网页的问题，也经常出现系统资源占用过高的现象。
3、本次错误日志如下：

> Options << Options#applyProfile [
>     "自动切换"
> ]
> Options << Options#updateProfile [
>     [
>         "自动切换",
>         "__ruleListOf_自动切换",
>         "GFWed",
>         "direct"
>     ]
> ]
> Options << Options#updateProfile []
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: https://services.disconnect.me",
>     "level": "warn"
> }
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: http://ocsp.comodoca.com",
>     "level": "warn"
> }
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
>     "level": "warn"
> }
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: https://tiles.services.mozilla.com",
>     "level": "warn"
> }

SwitchyOmega 2.5.10
Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://tiles.services.mozilla.com",
    "level": "warn"
}
```

**Comment by taojin0505** [comment]
我的Debian Stretch下，chrome 65,2.5.9.，2.5.10完全不可用

**Comment by ysz223** [comment]
在 Debian 9.4 最新穩定版中使用 最新穩定版的 chrome ，昨天測試了一下，可以使用，但是有死機的現象，掉包也明顯，又重新用回最新穩定版的 Firefox 了。

**Comment by FelisCatus** [comment]
我一直是在用 Linux 的，已经用了几年还没有遇到这类的问题。目前是 Linux + Chrome 65 以及 Firefox 59.

经常打不开网页这一点不是 SwitchyOmega 的问题，更可能是网络原因等。

首页的问题见 #1405. 请勿重复报告问题。

SwitchyOmega 本身没有平台相关代码，不存在 Linux 版本特别不稳定/不兼容之类的情况，请理解。如果遇到崩溃建议去对应浏览器访问。另外， Chrome 问题和 Firefox 问题请各位分开报告，并提供版本和错误日志。
