### ISSUE TITLE
Quick domain filter option seems to be broken

### ISSUE THREAD

**Issue by 1Poochh** [FelisCatus/SwitchyOmega#1418]
Once you click on the SwitchyOmega extension button,  you will get a list of profiles.  At the bottom it will show the domain you are on and allow you to configure a configuration for that domain.  That seems to be broken.

This is the feature I am talking about: https://drive.google.com/file/d/1Q2fNgdZuUhRpP8GQqKORjuddrBy_Yrgd/view?usp=sharing

Once you select something for a domain, auto-switch disappears even though it should be there.  This overwrites your profile config.  It took me a long time to figure out what happened, but then I found it.  

I switched the domain quick filter on to one of my profiles to direct (that was the only option I could see that wasn't a profile).  I then switch my main profile to auto-switch.  The issue is direct overrides my auto-switch so I wasn't going through my tunnel.

I kept messing with it an finally got the domain quick switch option auto-switch to show and I clicked on that and click on the profile to be auto-switch and thing are back to normal.  It seems likely a bug not showing auto-switch with the quick domain switch feature all of the time.

SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36

**Comment by FelisCatus** [comment]
This is answered in #1412. Again, sorry for the confusion.
