### ISSUE TITLE
Firefox 刚启动时一段时间内代理设置未被应用

### ISSUE THREAD

**Issue by ysz223** [FelisCatus/SwitchyOmega#1419]
开发者您好，

关 Llinux 的 Firefox 问题，在这之前有过反馈，也很感谢您的回复，由于之前没有更详尽地说明使用环境，在这里做一些补充。该页面是点击插件设置页面自动跳转的，我就不再归类了，望理解。

1、Debian 9 + Firefox 59，Firefox 是官方网站已经编译好的最新稳定版，放在 /home/用户名/.local/ 下；

2、同时使用的插件有 Decentraleyes、HTTPS Everywhere、uBlock Origin、Disconnect、SwitchyOmega 和 ImTranslator；

3、浏览器使用的是自定义首页，启动 Firefox 之后，一直无法载入，过了一段时间，出现连线已逾时的页面，手动点击重试时可以正常打开页面，新开启分页时，也可以打开网站。

4、本次错误日志如下：

> 
> Options << Options#applyProfile [
>     "自动切换"
> ]
> Options << Options#updateProfile [
>     [
>         "自动切换",
>         "__ruleListOf_自动切换",
>         "GFWed",
>         "direct"
>     ]
> ]
> Options << Options#updateProfile []
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: wss://push.services.mozilla.com",
>     "level": "warn"
> }
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: http://ocsp.pki.goog",
>     "level": "warn"
> }
> ERROR: {
>     "event": "proxyScriptLog",
>     "message": "Warning: Proxy script not initialized on handling: http://ocsp.comodoca.com",
>     "level": "warn"
> }
> Options << Options#updateProfile [
>     "__ruleListOf_自动切换",
>     "bypass_cache"
> ]
> Options << Options#updateProfile [
>     "__ruleListOf_自动切换",
>     "bypass_cache"
> ]

5、如果该问题不是插件本身的问题，请您指教该如何修正，感谢！

SwitchyOmega 2.5.10
Mozilla/5.0 (X11; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://ocsp.comodoca.com",
    "level": "warn"
}
```

**Comment by taojin0505** [comment]
我系统和你一样，请问下你chrome下可以使用吗？我在chrome，chromium下都不可以

**Comment by ysz223** [comment]
@taojin0505 昨天安装了 chrome 没问题，由于相比之下资源占用比 Firefox 高，有几个插件总在抢权限，也出现了死机现象，又卸载了。你具体是怎么不能用？建议把错误日志反馈给开发者。

**Comment by FelisCatus** [comment]
最近这样的问题很多，我在这里统一回答了吧。 Firefox 也好 Chrome 也好，加载扩展这个过程本身就需要一定时间。而 SwitchyOmega 加载完成后才可以设置代理选项。在这期间，发生的所有网络请求，都使用的是系统的代理设置等。因此，此问题无法由 SwitchyOmega 修复，请理解。另外，浏览器本身不会愿意设计成等待所有扩展加载完毕才发送网络请求，那会使得启动过慢，所以也请不必去 Firefox/Chrome 项目反馈此问题了，他们不会改的。

要绕过这种问题，只能通过尽量不关闭浏览器而是最小化、缩小到托盘、用系统休眠而不是重启之类的方式绕过。 Chrome 上已知可以安装一个后台应用，并设置成让后台应用始终运行来实现即使窗口关了，浏览器进程还在的效果。

P.S. 如果有其他问题，请另开 Issue 反馈，这里不是论坛，请不要讨论和原主题无关的其他问题。反馈问题请提供详细的版本信息和错误日志，以及发生的现象，不要直接说“不能用”。

**Comment by ysz223** [comment]
感謝開發者詳盡的說明，我的疑惑是，在同一個系統以及安裝同樣插件的前提下，chrome 在第一次啟動時可以毫無壓力地加載自定義首頁，為什麼 Firefox 卻不可以？您也是使用 Linux+Firefox，可不可以實際測試一下？謝謝！

**Comment by yfdyh000** [comment]
> 另外，浏览器本身不会愿意设计成等待所有扩展加载完毕才发送网络请求，那会使得启动过慢，所以也请不必去 Firefox/Chrome 项目反馈此问题了，他们不会改的。

可以观望 https://bugzilla.mozilla.org/show_bug.cgi?id=1378459
