### ISSUE TITLE
自动切换功能在开机后第一次访问被墙网站时不起作用

### ISSUE THREAD

**Issue by wavebit** [FelisCatus/SwitchyOmega#1421]
你好
我用的代理是shadowsocks windows v4.0.6，SwitchyOmega是自动切换模式。
每天第一次访问被墙网站时总是一直处于正在连接状态（要过几分钟的时间才能打开，关闭后再次访问同样的网站还是要等几分钟的时间），只有把shadowsocks启用系统代理（代理模式全局）并且SwitchyOmega也要改为系统代理才能顺利打开被墙网站。之后在把shadowsocks和SwitchyOmega的设置改回去(shadowsocks关闭系统代理，SwitchyOmega使用自动切换)，又能很快地打开网站。

以下是一些配置截图
![1](https://user-images.githubusercontent.com/11334491/38121080-a3e262a4-33ff-11e8-8832-901217ea2dfb.PNG)
![2](https://user-images.githubusercontent.com/11334491/38121082-a5a91baa-33ff-11e8-8a2b-726ae87f2c09.PNG)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by FelisCatus** [comment]
见 #1419.

**Comment by FelisCatus** [comment]
另外，如果改成全局模式才能访问，然后再改成自动切换也能访问了，那一般是因为缓存，也就是说部分资源可能没有被规则列表覆盖。具体可以第一次打开时稍等然后点击 SwitchyOmega 图标，点击未加载的资源查看并添加规则。如果是规则列表的问题请到规则列表那边反馈。

**Comment by wavebit** [comment]
谢谢，经过几天的观察我发现就是你说的问题。

**Comment by lianyaohuhhh** [comment]
@wavebit 您好，请问问题解决了吗？我也遇到了一模一样的问题，不知道如何解决，谢谢

**Comment by wavebit** [comment]
> @wavebit 您好，请问问题解决了吗？我也遇到了一模一样的问题，不知道如何解决，谢谢

没有解决
