### ISSUE TITLE
Feature request:Per-tab profiles.

### ISSUE THREAD

**Issue by pthfdr-42** [FelisCatus/SwitchyOmega#1422]
Sometimes you only need a proxy for certain tabs, as the provider usually has a rate limit on traffic.

SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.40 Safari/537.36

**Comment by FelisCatus** [comment]
See [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#can-you-add-support-for-tab-based-or-window-based-switching).
