### ISSUE TITLE
用插件无法上http的网址

### ISSUE THREAD

**Issue by stevesjtu** [FelisCatus/SwitchyOmega#1424]
选择代理服务器情景模式、“系统代理“情景模式，又或禁用插件，都可以上http网址。唯独在插件中使用“直接连接”就不能上http网址。（https网址无影响）
请问是哪里的问题？

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by FelisCatus** [comment]
请保持“直接连接”选中，然后打开 `chrome://net-internals/#proxy` 然后把页面上的内容复制到这里。

**Comment by stevesjtu** [comment]
@FelisCatus 
`chrome://net-internals/#proxy `页面下这样
> Effective proxy settings
> Use DIRECT connections.

**Comment by FelisCatus** [comment]
SwitchyOmega 已经提供给了 Chrome 正确的设置。如果还有问题的话一般是系统或者网络环境问题，我个人建议查看是否安装广告拦截或者之类的可能影响网络请求的软件。总之与此项目无关。
