### ISSUE TITLE
PAC Mode on Firefox

### ISSUE THREAD

**Issue by Rictusempra** [FelisCatus/SwitchyOmega#1426]
https://bugzilla.mozilla.org/show_bug.cgi?id=1409878
With this API landed, it shall be possible.

Also you may like this as well: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/dns/resolve

**Comment by FelisCatus** [comment]
Thanks for the heads up. I will try the new API once I have more time.

Just one thing, even if we are using the API, we still can't `eval` in background page, therefore we can't support PAC profiles. Or did I miss something?

**Comment by Rictusempra** [comment]
@FelisCatus 
I'm not sure. You'd better check this as well
https://github.com/mdn/webextensions-examples/tree/master/proxy-blocker

**Comment by FelisCatus** [comment]
@Rictusempra Thanks for the link. That extension registers a PAC file bundled in the extension source code, but does not evaluate a PAC file from user input. I'm closing this in favor of #1456 for the new proxy API.

**Comment by Librazy** [comment]
FYI, it is possible to use [browserSettings](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserSettings/proxyConfig) API to configure Firefox to use PAC **url**, it didn't support data: but file: is available. We can use download API to save external scripts and then use file: url, as a workaround for PAC script support. I don't know whether requesting `browserSettings` permission affects AMO reviews, but it shouldn't matters.

**Comment by Librazy** [comment]
As `proxy.settings` lands on firefox 60 (#1451), we may support PAC **url** through that. We may support PAC file by saving it using download API then use it as a file: url (data: url is not supported but file: works).
