### ISSUE TITLE
Can I pack SwithyOmega with user settings for personal use??

### ISSUE THREAD

**Issue by Gabirel** [FelisCatus/SwitchyOmega#1428]
Like this one: https://stackoverflow.com/questions/47587369/is-there-a-way-to-set-chrome-extension-settings-using-selenium (Unfortunately, it seems nobody knows how to do that)

I wanted to do that with extension enabled. However, I can't do that since the `chrome driver` is **NOT THAT POWERFUL**.

 So, I am asking if I can pack `SwithyOmega` with user settings. 
If it's possible, how could I do that? like what file name or one json file?

**Comment by celeron533** [comment]
You can export and import profiles

**Comment by Gabirel** [comment]
Yes, I know that. But I don't have any access to the extension settings when I'm under headless mode.

You mean export the profile to the SwitchyOmega and pack it again？

**Comment by FelisCatus** [comment]
What exactly do you want to achieve? If you want to set up proxies for a headless browser, I would suggest using the Chrome command-line to pass in the proxy settings. That way is much much cleaner IMO and does not depend on SwitchyOmega.

**Comment by Gabirel** [comment]
Yes, it's proxy I need. But I need PAC mode for the proxy. That's a little bit hard to do that without SwichyOmega

**Comment by shiquanwang** [comment]
need the same feature.
I use puppeteer and want to enable switchyomega for a headless chrome and set pac proxy

**Comment by FelisCatus** [comment]
You can set up your profiles as you wish on SwitchyOmega, and then export a certain profile as PAC script. That script is then reusable without SwitchyOmega. There is a certain command-line option that  a PAC URL, which can be `file:///path/to/your/pac/file` for local files.

See: https://peter.sh/experiments/chromium-command-line-switches/#proxy-pac-url

Let me know if that helps.
