### ISSUE TITLE
The requested URL /_gh/ was not found on this server.

### ISSUE THREAD

**Issue by syb518cn** [FelisCatus/SwitchyOmega#143]
HI,I used Google Chrome and Proxy SwitchyOmega 2.2.9

This is a problem code for my computer:
/
Error: Not Found
The requested URL /_gh/ was not found on this server.
/
HELP!
THANKS！

SwitchyOmega 2.2.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
This is a problem with GoAgent and has nothing to do with this project.
