### ISSUE TITLE
希望能在edge上能用到SwitchyOmega扩展

### ISSUE THREAD

**Issue by wingmancn** [FelisCatus/SwitchyOmega#1430]
建议：很喜欢SwitchyOmega，chrome和FIREFOX上我都在用。希望能在edge上也能用到它୧( “̮ )୨✧
谢谢先

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36

**Comment by celeron533** [comment]
Duplicated to #589

**Comment by QiaoYueMeng** [comment]
确实，Edge浏览器需要一个类似的代理软件！
