### ISSUE TITLE
弹出菜单中内置情景模式名称未翻译

### ISSUE THREAD

**Issue by huijiewei** [FelisCatus/SwitchyOmega#1433]
![image](https://user-images.githubusercontent.com/7017860/38622576-0bfdf3a0-3dd6-11e8-986a-a0347ebe4730.png)

如图，direct 没有翻译过来

**Comment by celeron533** [comment]
可以发个pull request?

**Comment by meteormatt** [comment]
可能翻译没提取

**Comment by FelisCatus** [comment]
请问是什么浏览器，浏览器和 SwitchyOmega 版本各是多少？另外，请问浏览器的语言/系统语言设置是怎么样的？

这个可能是个 bug ，之前是有翻译的。

**Comment by huijiewei** [comment]
@FelisCatus Chrome 浏览器，版本 66.0.3359.139（正式版本） （64 位）
Proxy SwitchyOmega 2.5.9
macOS 10.13.4
环境都是中文

**Comment by FelisCatus** [comment]
已确认为新弹出菜单重构导致的 bug. 待修复。

**Comment by celeron533** [comment]
@FelisCatus 辛苦啦
