### ISSUE TITLE
选项同步 存在逻辑错误

### ISSUE THREAD

**Issue by osdu** [FelisCatus/SwitchyOmega#1435]
新设备开启选项同步会自动将云端覆盖，导致所有设备的设置被同步修改成当前新设备的设置。

**Comment by FelisCatus** [comment]
请试试看新设备不要开启同步，而是先在 Chrome 上登录，让 Chrome 自动下载 SwitchyOmega 并且加载选项。

**Comment by osdu** [comment]
@FelisCatus 建议同步的时候保留几个历史版本，并加入时间戳或者UUID。

**Comment by FelisCatus** [comment]
@osdu 由于 Chrome 扩展同步服务本身的限制，基本上没办法实现这样的功能……很抱歉，这边我就先关掉了。

**Comment by siaimes** [comment]
@FelisCatus 我今天也遇到这个了，因为代理软件不支持全局代理。所以使用GitHub的文件安装了SwitchyOmega，然后点击选项同步中的启用同步。结果所有服务器，客户端的记录全部被覆盖掉成了SwitchyOmega自动生成的配置。这里难道没有逻辑问题吗？毕竟，你说的先登陆chrome这个，对于不支持全局代理的情况是没办法完成的。
