### ISSUE TITLE
Rules for child URLs inside page on the certain domain

### ISSUE THREAD

**Issue by eugene20237** [FelisCatus/SwitchyOmega#1438]
Hello! How to enable proxy for various EXTERNAL resources (javascripts, css, etc) on the page with the specific domian? I want the entire page to be fully loaded with a proxy.

**Comment by inferrna** [comment]
Also vote for options for this.

**Comment by inferrna** [comment]
Just found https://github.com/FelisCatus/SwitchyOmega/issues/508
So, the question is - why not to control proxies like uMatrix controls connections?

**Comment by FelisCatus** [comment]
Merging to #508. And in reply to @inferrna, the short answer is that you cannot return a proxy though the web request blocking API, compared to blocking or changing the web request itself.
