### ISSUE TITLE
手机firefox上提示代理服务器被拒绝

### ISSUE THREAD

**Issue by 123ysys** [FelisCatus/SwitchyOmega#1439]
我设置的代理服务器是127.0.0.1，这在电脑上好用，但是手机上不行，不知是什么原因。

**Comment by celeron533** [comment]
你的手机上有没有代理程序在监听？估计没有。这个和switchyOmega关系不大

**Comment by 123ysys** [comment]
@celeron5330 有的，有一个影梭。

**Comment by 123ysys** [comment]
@celeron533 有的，有一个影梭

**Comment by celeron533** [comment]
如果是android手机，上面的ss实现是通过套一层VPN来截获所有流量的。windows版一旦进程起来后就会在本地监听端口。所以你不能在手机上这么用

**Comment by 123ysys** [comment]
那我该怎么用呢？😂求教。

**Comment by celeron533** [comment]
不需要SwitchyOmega，直接启动SS即可

**Comment by 123ysys** [comment]
ok
