### ISSUE TITLE
希望 代理服务器-不代理的地址列表 默认配置私网地址

### ISSUE THREAD

**Issue by Septembers** [FelisCatus/SwitchyOmega#144]
```
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
```

**Comment by FelisCatus** [comment]
嘛，私网地址也不一定不用代理访问吧……
比如使用公司的代理访问公司网络下的某台内部服务器，这个是完全有可能的。

我只能说考虑做一个选项或者之类的功能。默认设置虽然也很方便，但如果这不是用户想要的话，用户很难发现是这个原因。所以……估计结论是只能让用户主动选择使用了。
