### ISSUE TITLE
Socks5没有输入用户名密码的选项？

### ISSUE THREAD

**Issue by Var-iazioni** [FelisCatus/SwitchyOmega#1440]
Why？

**Comment by celeron533** [comment]
[常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8D%E6%94%AF%E6%8C%81-socks5-%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E5%AF%86%E7%A0%81%E8%AE%A4%E8%AF%81%E5%90%97)

**Comment by Var-iazioni** [comment]
工具确实是好工具。。。可惜了。。
