### ISSUE TITLE
using subnets in exclusion list like 10.0.0.0/8 still sends the traffic via http proxy

### ISSUE THREAD

**Issue by DmitryFrolovTri** [FelisCatus/SwitchyOmega#1441]
SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

**Comment by DmitryFrolovTri** [comment]
Sometimes it is important to ensure that any traffic requested from an IP or a subnet is going via proxy. IT is not possible to achieve that with SwitchyOmega

**Comment by DmitryFrolovTri** [comment]
I noticed that when enabling advanced options IP lever it is specifically said that if IP used then it would be routed via proxy but if a website is on that IP the rule won't match. 
I need new type of rule that take into account just the IP of resource. 
Also the Bypass list seems to ignore that a resource is located on the IP range that is supposed to be sent direct. 

So there is no way  to allow full subnets to be routed directly. Neither in Bypass list  nor in the autoswitch.   

If host that I am trying to reach has IP of 10.0.0.1 and Bypass list has 10.0.0.0/8 it means that this host should access internet directly. 

Reasoning - If I have a corporate VPN that handles some subnets, and some resources in the same domain some of which have internal IP address and some other that have external IP address. I can't get those to work with SwitchyOmega, unless I list everyone of the resources that uses internal IP.  

Behaviour I need:
1) in the Bypass list if I specify 10.0.0.0/8 then ALL sites that have this IP shoud be routed directly. 
2) if 127.0.0.1 is specified that would match localhost and 127.0.0.1

I am happy if you introduce a "local networks" section that achieve that or changes the behaviour of the "Bypass list" 

I didn't understand why we treat localhost different then it's IP 127.0.0.1 or ::1 if we use IP in the bypass or IP lever list. 

Is there some limitation in Chrome to have this option working like it does on other proxy settings? IE system settings, proxifier.com settings, firefox?

**Comment by FelisCatus** [comment]
See #703. In short, we haven't implemented any DNS requests in SwitchyOmega due to various concerns. However, you can use the `dnsResolve()` function by creating a PAC Profile if you absolutely need it. Combining the feature request to #703.
