### ISSUE TITLE
用SwitchyOmega 自动替换模式后，无法上网，切换到直接连接或系统代理才可以上网。 报"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED"

### ISSUE THREAD

**Issue by tanquan** [FelisCatus/SwitchyOmega#1442]
用SwitchyOmega 自动替换模式后，无法上网，切换到直接连接或系统代理才可以上网。
报"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED"

Chrome 版本 65.0.3325.181（正式版本） （64 位）
SwitchyOmega 版本 2.5.9

**Comment by tanquan** [comment]
[OmegaProfile__.pac.20180419.txt](https://github.com/FelisCatus/SwitchyOmega/files/1926813/OmegaProfile__.pac.20180419.txt)

**Comment by FelisCatus** [comment]
首先，请试一下切换到全局代理模式是否能正常使用。然后，切换到自动切换模式，访问一个网址，然后右键点击工具栏中 SwitchyOmega 图标，然后点导出错误日志。

如果方便的话，请切换回直接链接模式，打开 `chrome://net-internals/#events` ，然后切换到自动切换模式，查看那个页面是否有 PAC 相关错误消息。如果有，请复制到这里。如果没有，试试看访问一个网址，再查看那个页面是否有错误消息。（注意：错误数量可能会比较多，请耐心查看和筛选。）

**Comment by tanquan** [comment]
按照您提供的步骤排查，发现与安全软件有“冲突”。关闭安全软件后，自动替换模式、直接连接或系统代理 都恢复正常了。 谢谢！
