### ISSUE TITLE
Not connect to proxy server

### ISSUE THREAD

**Issue by hghofraniha** [FelisCatus/SwitchyOmega#1443]
Hi,
  I can connect to proxy server by FireFox Settings but cannot connect to proxy server through SwitchyOmega in both proxy and autoswitch.

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: wss://ff.kis.v2.scr.kaspersky-labs.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
First, please check if your proxy server is working correctly and the port, host and scheme matches your proxy server's. Try disabling SwitchyOmega and directly fill in Firefox's own proxy settings and see if it works.

If it works in Firefox proxy settings but does not work in SwitchyOmega, please take a screenshot of both settings and upload it here. In addition, please right-click on SwitchyOmega icon in the toolbar and select "export error logs" and upload it here.
