### ISSUE TITLE
google is a pain

### ISSUE THREAD

**Issue by necron-ninety-nine** [FelisCatus/SwitchyOmega#1444]
SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://ocsp.pki.goog",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
This is SwitchyOmega, not Google. If you have issues with Google, please submit your feedback to Google support.
