### ISSUE TITLE
可否提供切換的功能在設定頁面中

### ISSUE THREAD

**Issue by webeasyplay** [FelisCatus/SwitchyOmega#1447]
可否把圖片中這個清單功能加入到
chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/ui的界面中

![image](https://user-images.githubusercontent.com/12272185/39096677-e0f620b6-4685-11e8-959e-a6d87a5c9fc5.png)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

**Comment by FelisCatus** [comment]
抱歉，我想先请问下为什么要把这个放在设置页面中？请完整描述下应用场景和理由，我看看怎么解决这个问题。
