### ISSUE TITLE
如何设置子页面的域名通配……

### ISSUE THREAD

**Issue by wysn10** [FelisCatus/SwitchyOmega#1448]
唔 我不确定表达的是否正确
比如【http://120.37.140.42/tc-tct.douyucdn.cn/dyliveflv1/312410rqXJX3YoBS_900.flv?wsAuth=a8811f30d2849e96b3ebe086322da86a&token=web-douyu-999317-312410-39588b1fa14bb878e27825d50f728801&logo=0&expire=0&did=b055c5d4a72a10ec235a2ed600011501&ver=2018042311&pt=1&dispatch_from=ztc10.58.132.97&utime=1524484717463】
我要怎么样才能只匹配【/tc-tct.douyucdn.cn/】这段网址

**Comment by FelisCatus** [comment]
这个可以用网址通配符规则 `*/tc-tct.douyucdn.cn/*` 来匹配。请注意选取“网址通配符”而不是其他规则类型，比如域名通配符。
