### ISSUE TITLE
完整网址限制被手动屏蔽后的检测

### ISSUE THREAD

**Issue by hendeliao** [FelisCatus/SwitchyOmega#1449]
RT，当我手动屏蔽完整网址限制后，可以在设置页直接获取当前的网址来判断我是否屏蔽，抑或是有更好的办法直接获取？总之最好自动检测到底有没有完整网址限制啦。

**Comment by FelisCatus** [comment]
抱歉，我没有看懂“手动屏蔽完整网址限制”指的是什么，“在设置页直接获取当前的网址”又是怎么操作……

能麻烦您详细说下，比如说做了哪些步骤，实际得到了什么结果，但您希望它变成什么样吗？

**Comment by hendeliao** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-%E5%AE%8C%E6%95%B4%E7%BD%91%E5%9D%80%E9%99%90%E5%88%B6

这个帖子，在插件设置里出现的那个地方，可以加一个判断，因为我自己已经把这个限制给手动关掉了，但是提示依然在。

**Comment by FelisCatus** [comment]
扩展没有办法检测这个行为，抱歉了……无视这个提示就好……
