### ISSUE TITLE
希望每个Chrome窗口的设置可以不同

### ISSUE THREAD

**Issue by kice** [FelisCatus/SwitchyOmega#145]
习惯了打开N多的页面(Ctrl+T)的人来说，用窗口(Ctrl+N)进行分组管理是很方便的。例如：国外页面一个窗口，国内的又一个。但是浏览国外页面需要代理，加上用了代理之后国内页面加载很慢，需要不停得切换。就希望能否每个页面情景可以不相同。

**Comment by FelisCatus** [comment]
此功能无法在 PAC 脚本中实现，因此无法支持。
