### ISSUE TITLE
Firefox 60 beta 16 失效

### ISSUE THREAD

**Issue by Remonli** [FelisCatus/SwitchyOmega#1451]
beta 15 正常, beta 16 fail 了.

SwitchyOmega 2.5.10
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by ghcsd** [comment]
Nightly 61（2018-04-26）也失效了，不清楚是否为同一问题。

Nightly 经 mozregression 测试，定位到
[Bug 1455755 Move browserSettings.proxyConfig to proxy.settings](https://bugzilla.mozilla.org/show_bug.cgi?id=1455755)

**Comment by huangyedoushi** [comment]
Firefox更新到60.0b16发现proxy switchyomega出问题了，Nightly版也是。望大神尽快更新！

**Comment by daiheitan** [comment]
@celeron533

**Comment by celeron533** [comment]
@daiheitan 为什么点我名啊 :rofl:

**Comment by turbidsoul** [comment]
我也有同样的问题，启动浏览器代理选择系统代理，改成自动，也不能行，重启浏览器后代理还是选择的系统代理
[OmegaLog_1524894268369.txt](https://github.com/FelisCatus/SwitchyOmega/files/1957341/OmegaLog_1524894268369.txt)

**Comment by daiheitan** [comment]
@celeron533 等你修复= =，你不是contributer吗

**Comment by ufo1024k** [comment]
我的也一样升级到60.0b16后就失效了。

**Comment by qinly** [comment]
+1

**Comment by Asteroids89** [comment]
+1，帮你们呼叫一下F大
@FelisCatus 盼修复，谢谢！

**Comment by maryjeck** [comment]
+1

**Comment by retaw** [comment]
+1

**Comment by FelisCatus** [comment]
感谢反馈，我尽快修复这个。

**Comment by FelisCatus** [comment]
v2.5.11 已经修复。
