### ISSUE TITLE
高分主屏和低分副屏下，工具栏图标 popup.html 中列表的鼠标 hover 效果，比鼠标实际位置向下偏移。

### ISSUE THREAD

**Issue by pfdgithub** [FelisCatus/SwitchyOmega#1452]
运行 Chrome 于高分辨率主屏幕，系统屏幕 125% 倍缩放，工具栏图标 popup.html 中列表的鼠标 hover 效果，一切正常。
拖拽 Chrome 至低分辨率副屏幕，系统屏幕 100% 倍缩放，工具栏图标 popup.html 中列表的鼠标 hover 效果，比鼠标实际位置向下偏移，越向下偏移量越大。
怀疑是由于计算鼠标位置时，沿用了主屏幕的 125% 倍缩放，造成了偏移。

![image](https://user-images.githubusercontent.com/3262762/39393166-8fbd0426-4af4-11e8-95e0-8b161dfbe760.png)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36

**Comment by FelisCatus** [comment]
这个是 Chrome 的问题，建议到 Chrome 那里反馈。与 SwitchyOmega 无关。 SwitchyOmega 的弹出菜单是基于网页的，而网页渲染（以及鼠标点击等事件）是 Chrome 处理。
