### ISSUE TITLE
自动切换模式下chrome无法登陆谷歌账户

### ISSUE THREAD

**Issue by erickwoc** [FelisCatus/SwitchyOmega#1453]
如图所示
![_ _20180429114142](https://user-images.githubusercontent.com/16463312/39403057-5458bb78-4ba3-11e8-9393-9fd4a163cfaf.gif)
只有切换成全局代理才能正常登录/同步谷歌账号

系统信息：
```
[11:28]eric~$ uname -a
Linux eric-PC 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux
```

**Comment by FelisCatus** [comment]
这个可能是因为您使用的规则没有覆盖合适的 URL. 请检查您的规则是否涵盖了 Google 登录所需要的所有 URL ，或者如果您在使用规则列表，请到规则列表那边反馈。

关于具体需要覆盖哪些 URL ，可能会比较难判断，建议看 `chrome://net-internal/#events` ，或者必要时抓包。

**Comment by erickwoc** [comment]
添加规则
```
*.googleapis.com +proxy
```
后便可正常登陆

[这是在规则列表那边提交的issue](https://github.com/gfwlist/gfwlist/issues/1056)

**Comment by wakaka2333** [comment]
楼上正解，刚刚添加规则以后正常同步了
