### ISSUE TITLE
Use browser.proxy.onRequest if possible

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#1456]
See: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy/onRequest

**Comment by Rictusempra** [comment]
@FelisCatus It this is ever implemented, Firefox branch of this extension will become completely different from Chrome and no way back.

**Comment by FelisCatus** [comment]
v2.5.16 released with the new API (Firefox ONLY).

**Comment by waingt** [comment]
> after firefox upgrde to 100.0.1,direct connection and system proxy behavior rollback to #1212 and #2213

@shixudong2020 
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo
"direct": don't proxy the request. If this value is given, all other properties of this object are ignored. However, this setting doesn't override any [proxy set by the user](https://support.mozilla.org/en-US/kb/connection-settings-firefox)

https://support.mozilla.org/en-US/kb/connection-settings-firefox
Choose _No proxy_ in _Connection Settings_ will solve this problem
