### ISSUE TITLE
希望添加根据规则自动切换情景模式的功能

### ISSUE THREAD

**Issue by PelloZhang** [FelisCatus/SwitchyOmega#1458]
希望添加根据规则自动切换情景模式的功能，比如我在公司的出口ip是 x.x.x.x 那么就自动切换为“公司情景”，当我在家的出口ip是 y.y.y.y 或者不是 x.x.x.x 那么就自动切换为“家庭情景”

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by FelisCatus** [comment]
见  #197, 没有比较合适的方式实现，需要各种 hack 而且工作量很大……
