### ISSUE TITLE
Error while trying to renaming profile

### ISSUE THREAD

**Issue by gas3** [FelisCatus/SwitchyOmega#1459]
SwitchyOmega 2.5.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://eu-west-1.signin.aws.amazon.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
Can you try renaming the profile again, and then export the logs by right-clicking on the SwitchyOmega icon on the toolbar? Thanks in advance.
