### ISSUE TITLE
能否在popup上添加重新下载pac的按钮

### ISSUE THREAD

**Issue by ayanamist** [FelisCatus/SwitchyOmega#146]
我的pac脚本是自己的程序生成的，提供http服务供Chrome来下载。
每次修改规则的时候，都需要修改完了，进Options页面，找到对应的pac规则那一项（如果上一次是这个Profile的话，会自动打开这个Profile，这一步可以不用做），然后点Download Profile Now。
不知道能不能在popup添加一个刷新按钮，点一下，就相当于Download Profile Now的效果？

**Comment by FelisCatus** [comment]
Closed in favor of #148.
