### ISSUE TITLE
auto rule

### ISSUE THREAD

**Issue by zappbrannigan34** [FelisCatus/SwitchyOmega#1460]
How to set use proxy if direct not connect?
->try direct->if not connect try proxy

**Comment by FelisCatus** [comment]
This isn't quite possible for Chrome extensions, but you can enable auto switch and add rules for all URL patterns that you need a proxy. There is also a quick way to do that. When a webpage fails to load, click on the SwitchyOmega icon and select "failed resources", which allows you to add resources to auto switch.

**Comment by zappbrannigan34** [comment]
This is not "auto". Please add auto check. In "frigate lite" its realised. It says "accepted without proxy" or "flag country"
