### ISSUE TITLE
ftp协议不走socks5 

### ISSUE THREAD

**Issue by qq906907952** [FelisCatus/SwitchyOmega#1462]
ftp:// 开头的地址一律不走socks5 直接报无法连接

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/39674110-a4c171aa-5179-11e8-8bde-54ea54f9e7a2.png)

**Comment by FelisCatus** [comment]
Chrome 原生不支持，见 https://bugs.chromium.org/p/chromium/issues/detail?id=226929
