### ISSUE TITLE
三個問題反饋

### ISSUE THREAD

**Issue by delphinuz** [FelisCatus/SwitchyOmega#1463]
1使用一段時間後，addon的按鈕就無法作用，按了沒反應。
2連線速度比直連慢很多。
3經常發生整個firefox很卡，切換分頁都卡，關閉後恢復正常。

**Comment by QIEXXII** [comment]
+1 
我的连接速度也很慢。我同时比较了Firefox+SwitchyOmega和Chrome+SwitchyOmega，使用的同一份配置文件(完全相同)，Firefox上面访问要代理的地址要比Chrome更慢的多。

**Comment by FelisCatus** [comment]
1: 感谢反馈。下次按了没反应的时候，请立即右键点图标，选导出日志，然后上传到这里。
2: 更像是和 Firefox 的网络实现有关，而和 SwitchyOmega 无关。
3: 见 #1392.
