### ISSUE TITLE
如何在浏览器中指定http代理服务器header

### ISSUE THREAD

**Issue by diyijing** [FelisCatus/SwitchyOmega#1464]
我自己是否能通过SwitchyOmega实现?
如下
curl -H "My-Header: {value}" -x [{ProxyIP}]:{port} myip.ipip.net

**Comment by celeron533** [comment]
搭配其他插件？

**Comment by diyijing** [comment]
了解有这样的插件吗?

在 2018年5月8日，上午7:44，Allen Zhu <notifications@github.com<mailto:notifications@github.com>> 写道：


搭配其他插件？

**Comment by FelisCatus** [comment]
SwitchyOmega 不修改请求内容，所以此功能无法通过 SwitchyOmega 实现。 Chrome Extensions API 理论上可以实现这样的功能，但具体哪个扩展有这种功能我不清楚。

这里仅供 SwitchyOmega 的 Issue 跟踪。我个人建议到相关论坛提问，可能效率更高一些。

**Comment by celeron533** [comment]
> 了解有这样的插件吗?
网上搜都有，不要伸手
https://chrome.google.com/webstore/search/modify%20headers?_feature=5stars
