### ISSUE TITLE
Problem with SOCKS5 authorization

### ISSUE THREAD

**Issue by f242** [FelisCatus/SwitchyOmega#1465]
When i switch proxy type to SOCKS5 authorization icon (lock) on the right disappears

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by celeron533** [comment]
Chrome does not support SOCKS5 authentication
https://bugs.chromium.org/p/chromium/issues/detail?id=256785

**Comment by f242** [comment]
@celeron533 https://chrome.google.com/webstore/detail/proxy-helper/mnloefcpaepkpmhaoipjkpikbnkmbnic
![image](https://user-images.githubusercontent.com/10371194/39737420-9a924a46-528d-11e8-9ca9-0558421e3ecb.png)

**Comment by FelisCatus** [comment]
There are just too many questions about SOCKS5 auth. Shall we put some explanation inside SwitchyOmega so people can easily get that information? We can keep the padlock icon, but show a popup stating that why it is not possible when clicked.

**Comment by celeron533** [comment]
@FelisCatus Or make the padlock icon gray with a tooltop and popup message when clicked
