### ISSUE TITLE
ERR_TUNNEL_CONNECTION_FAILED

### ISSUE THREAD

**Issue by rsalars1** [FelisCatus/SwitchyOmega#1469]
I'm trying out SwitchyOmega under ubuntu 16.04 chrome and I can't seem to connect to some proxies that I know are good.  I have everything entered correctly, including ports and passwords, but get the following error when I try out various profiles and proxies:

This site can’t be reached
The webpage at    https://feedly.com/i/my, (etc, for any and all webpages)   might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by FelisCatus** [comment]
Could you please also check the protocols you've entered for those proxies? It can be the case if HTTP proxy is entered as SOCKS etc. Also, make sure that you only enter the proxy in the first row, which should be enough for most cases, and the protocol is the protocol of the proxy, not the URLs you want to visit.
