### ISSUE TITLE
能否显示一下链接信息和数据传输信息，有的时候不知道连上没有啊？

### ISSUE THREAD

**Issue by idodoyo** [FelisCatus/SwitchyOmega#147]
SwitchyOmega 2.2.10
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
想要显示什么呢？

**Comment by FelisCatus** [comment]
这个 issue 也已经很久了，虽然我到现在都没有明白究竟是什么意思……如果有什么要补充的，请留言回复。
