### ISSUE TITLE
Warning: Proxy script not initialized on handling - Firefox 59.0.2 Linux

### ISSUE THREAD

**Issue by gregoliver** [FelisCatus/SwitchyOmega#1471]
Hi,

I randomly get these errors from sites using socks5.

ERROR: {
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://ocsp.digicert.com",
    "level": "warn"
}

The majority of the time (99%), the error is all google sites, but this time it is digicert.

Is this harmless - in other words, if the proxy is rejecting for whatever reason, it is not falling back to non-proxy correct?  I have tried to packet capture it from my laptop, but have not caught it "doing the wrong thing" yet - I just wanted to make sure - I tunnel in to Level3 (our colo facilities) to get on our corporate network and just want to make sure.

Thanks for the switcher - it is awesome!

-Greg

**Comment by FelisCatus** [comment]
This is most likely harmless but some requests do go through direct connection when the extension is still initializing. Luckily, this may be solved on Firefox later when we switch to the new proxy API.
