### ISSUE TITLE
Proxy username and password authentication

### ISSUE THREAD

**Issue by dotmcduffie** [FelisCatus/SwitchyOmega#1472]
How would one separate proxy settings and proxy authentication in such a way that a user may authenticate to a group of proxies? 
For example,  a separate page that would allow the user to enter username and password credentials.
Is it possible to achieve by modifying the code within the omega-target section of code?

**Comment by FelisCatus** [comment]
This is possible by creating a PAC script profile that contains multiple proxies and switching logic. There is one unified entry per PAC profile.

Right now, SwitchyOmega does not offer a way to set authentication across proxies. You may find #235 interesting, which tracks (and offers a temporary solution) for batch proxy profile creation.
