### ISSUE TITLE
The Link of "Direct" Missing Sometimes

### ISSUE THREAD

**Issue by alexxyjiang** [FelisCatus/SwitchyOmega#1473]
Hi,
When using the SwitchyOmega, it turns out sometimes the "Direct" option is hidden and is not clickable. It could be recovered via rebooting the browser, and I'd like to have this fixed.

SwitchyOmega 2.5.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

**Comment by FelisCatus** [comment]
Hi, when it happens again, could you please right click on the popup and click on "Inspect Element", and then copy any error messages on the "Console" tab? Thanks in advance.
