### ISSUE TITLE
部分切换规则重启后不见了

### ISSUE THREAD

**Issue by symant233** [FelisCatus/SwitchyOmega#1476]
开发者你好.
老早就碰到了这个问题,在Auto Switch下,对域名指定规则(如proxy或直连)
但是有的网站设定了之后重启(也没具体试过不知道是重启chrome还是电脑..)比如dlsite.com(不要笑我)
也有可能是我规则太多了.. 我规则估计有四五百条...
希望得到回复.

**Comment by symant233** [comment]
最近打开后连Google都不自动切换Proxy了...
是什么原因导致Omega经常"忘记"Auto-Switch里的规则呢..

**Comment by FelisCatus** [comment]
首先，如果您使用的是漏斗图标的那个选项，那个添加的是临时规则，重启后就会失效。关于增加说明文字的问题见 #515.

页面不能正常打开的情况，请确认自动切换中的规则已经设置为使用代理。页面本身的代理，可以鼠标悬停在 SwitchyOmega 图标上确认，具体因为哪些规则，而使用了什么代理。而页面中的元素（例如脚本）如果加载不出，请在“未加载的资源”列表中确认，并适当添加代理规则。如果是代理服务器或者网络原因导致的问题，与本项目无关。

**Comment by symant233** [comment]
请问在图示里的规则都是临时的么?(这些规则我都是用漏斗图标的那个选项添加的)
如果是的话如何快速添加永久规则呢?
![image](https://user-images.githubusercontent.com/25316350/42459056-a60b9488-83cd-11e8-9742-b859867edaa8.png)

**Comment by FelisCatus** [comment]
在这里显示的规则都是永久的，用加号图标的那个选项添加的都会出现在这里。而用漏斗（`example.com`）那一项添加的是临时规则。
