### ISSUE TITLE
建议能把页面内走代理的 “主机域名” 都列出来，并在右键上加上快捷入口

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#1477]
目前SO的logo上悬停鼠标，只显示浏览器地址框里的域名是否走代理的状态，实际上，比如 facebook.com，还必须加上 *.fbcdn.net 否则就无法正常浏览 fb 的网站。
那么建议，
第一，如果能提示这个页面内还有多少 url 也是被 wall 或者 走代理的，相当直观有效，比如除了 facebook.com 主域名，还包括 fbcdn.net ，也可能这个页面里还有 google或twitter 被ban的主机，如果都能显示出来更方便，也是对普通使用者一种教育 -- 并不是主域名走代理就一切 ok 了，还有其他主机需要添加。
第二，建议能把访问错误的 url 也挪到 logo 的右键菜单上，因为开启了
 “快速切换” 之后，左键就被占用只能用来切换，只能看到某些页面里有访问错误的 url 的提示数字，但不能一键添加这些网站。

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by Justsoos** [comment]
补个图，能把这些网页内访问所有网址，通或断都有显示，列到这个鼠标 on logo 弹出的菜单下也是蛮好的，让用户能一目了然网页内都有那些域名，那些被屏了，那些可能是钓鱼的 iframe 内置的，那些是用户没想到需要加入屏蔽（反GFW）列表的：
![default](https://user-images.githubusercontent.com/3480043/40883512-8941fa8a-6731-11e8-9775-275480e9a7d8.png)

**Comment by InoriHeart** [comment]
个人觉得第一条加一个显示全部连接的开关
有时候一些网站不支持 ADBlock，这种情况我是在 chrome 开发者工具找到广告网址 在 host 那边屏蔽的
所以有这个开关大概找起来更方便些？

**Comment by Justsoos** [comment]
@InoriHeart  对，其实这就是从 uBlock，Privacy Badger借鉴的，但前两者太笨重了，SwithyOmega 本质上信息流控里就带这些信息，能放出来很轻量级，也配合产品特色。

**Comment by FelisCatus** [comment]
快速切换的问题见 #328.

虽然对于脚本之类的没什么办法，但是如果有元素或者 iframe 显示不出来的话，在上面右键选择“检查元素代理”（忘了是不是这个翻译）即可。

由于性能和保持产品简洁的原因考虑，我希望“页面内的资源”这个概念还是仅限于弹出菜单内就好。在 tooltip 里显示性能实在太差了，还需要做排版，还要兼顾不要遮挡了规则路径和最终代理地址等重要信息，实在太困难了，望谅解。
