### ISSUE TITLE
Proxy Settings synced when no browser sync enabled

### ISSUE THREAD

**Issue by gregoliver** [FelisCatus/SwitchyOmega#1478]
Hi getting this from the Settings screen :

Syncing (Experimental)

You have uploaded a copy of your options on another device via syncing. 

I do not have syncing enabled anywhere - is this just a bug that it is being displayed?

Thanks

-Greg

**Comment by FelisCatus** [comment]
@gregoliver It could be the case that you've enabled and disabled it before. In that case, feel free to override the remote copy.
