### ISSUE TITLE
PAC 远程URL / 本地PAC文本 相关问题

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#148]
目标：保证切换到PAC情景模式尽量可以立即使用，同时也能保证PAC更新及时。

理想的实现方式：

1. 对于 `file:///` 的本地文件作为URL，直接使用。
2. 如果有下载好的本地文本，使用下载好的本地PAC文本。
 * 同时，尝试在后台下载 URL 。下载完毕后如果有更新，将新的PAC文本缓存到本地，重复步骤2。
3. 否则直接把 URL 丢给浏览器处理，可能会触发网络请求，有一定延迟。

**Comment by ayanamist** [comment]
我个人倾向，在填了pac的url后，就清空内容，只设url，目前的行为，如果文本框里有内容（默认是有的），然后又填了url，但不点download，则生效的是文本框里的内容，而不是pac的url。但此时文本框又disable不能编辑了。这个逻辑比较隐晦。

**Comment by FelisCatus** [comment]
@ayanamist 感觉像是界面上的 bug 。正确行为应该是修改 URL 时自动清空本地PAC文本。这个我也一并修复吧。

**Comment by FelisCatus** [comment]
v2.2.11 已经修复，现在应该按照理想方案了。

此外，PAC选项界面也进行了改进，现在可显示最后更新的时间。
