### ISSUE TITLE
sometimes in firefox menu is empty

### ISSUE THREAD

**Issue by f242** [FelisCatus/SwitchyOmega#1482]
SwitchyOmega v.2.5.11
Firefox x64 v.61b6
![2018-05-19-19-32-49](https://user-images.githubusercontent.com/10371194/40270808-5a7261b8-5b9c-11e8-8690-692d303a98b5.gif)

**Comment by FelisCatus** [comment]
I believe this is an issue with Firefox or with your graphic card driver rather than SwitchyOmega. As you can see, the HTML part is already there, just not properly drawn until updated. I'd suggest trying your luck at Bugzilla first.

**Comment by f242** [comment]
but problem only with this plugin
