### ISSUE TITLE
在原本需要使用HTTP代理上网的环境中，“系统代理”模式无效

### ISSUE THREAD

**Issue by bitching** [FelisCatus/SwitchyOmega#1485]
原本就需要使用HTTP代理服务器proxy.mydomain方可上网，IE代理已设置好，可正常浏览网页。
使用“系统代理”模式则无法打开网页，需要新建一个代理模式将proxy.mydomain填进去，或者将Firefox本身的“网络代理”选项改为“使用系统代理设置”方可浏览网页。
![default](https://user-images.githubusercontent.com/12702029/40410758-1947ae98-5ea1-11e8-9b88-345c7072b401.png)

SwitchyOmega 2.5.11
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by FelisCatus** [comment]
SwitchyOmega 无法读取真正的“系统代理”设置，所以当选择“系统代理”的时候实际上 SwitchyOmega 会放弃对代理的控制权，从而允许系统或者其他扩展发挥作用。因此，会有这样的限制存在。此问题无法修复。

**Comment by ls696** [comment]
这个问题我也发现了
