### ISSUE TITLE
chrome store 还是老版本

### ISSUE THREAD

**Issue by WinLinKer** [FelisCatus/SwitchyOmega#1486]
chrome store 还是老版本，2.5.9，请作者看下

**Comment by celeron533** [comment]
确实是这样...
![image](https://user-images.githubusercontent.com/3608762/40478159-eb34b11a-5f7a-11e8-8f74-417954f3f74d.png)

![image](https://user-images.githubusercontent.com/3608762/40478167-f0c4487a-5f7a-11e8-9b0e-645cc7aeec5a.png)

**Comment by celeron533** [comment]
不过从commit history上看来，似乎后面两个版本主要是针对firefox的修改以及部分翻译修正？

**Comment by FelisCatus** [comment]
后面的版本都是 Firefox 相关的更新，因此暂时没有在 Chrome Web Store 发布新版本。先关闭了，有新功能的时候自然会更新。
