### ISSUE TITLE
我想咨询一下，just some question

### ISSUE THREAD

**Issue by githublet** [FelisCatus/SwitchyOmega#1487]
那个自动切换怎么回事？
what about auto switch？
是不是仅把翻墙的配置一下就行了？
can we just set the URL witch I want proxy，other direct？
为什么满足翻墙规则的也加载不了？
why can‘t surf even satisfy the rules，and add rules again and again？

**Comment by celeron533** [comment]
1. 这个扩展本意只是代理切换，和翻墙其实没有关联，只是最近被广泛用于这个用途
2. 自动切换的规则要你自己写

**Comment by githublet** [comment]
我的意思是，自动切换的规则有点难用了。
按理说只要把墙外的设置一下就好了嘛，比如google等设置protxy，可是百度也需要设置直连，csdn也需要设置直连。。。
不设置就会N个资源未加载，搞不懂啊！

**Comment by celeron533** [comment]
你需要gfwlist，请在google自行搜索

**Comment by githublet** [comment]
可能你没理解我的意思。。。
gfwlist我shadowssocks里面有，但是那个一个比较慢的过程，仅protxy情况下再过滤一次，所以我希望直连有更好的效果，就是说我没有设置protxy的网站都走直连。
问题在于我访问内网的时候需要设置明确指出直连才能加载全部

**Comment by celeron533** [comment]
shadowsocks关闭系统代理，然后在switchyomega里加载gfwlist

![image](https://user-images.githubusercontent.com/3608762/40524177-abfac0c0-600b-11e8-9fd9-a11f7348415f.png)

**Comment by wenliyang** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList

Wiki里有教程
