### ISSUE TITLE
[Feature Request] Proxy API Support

### ISSUE THREAD

**Issue by zero77** [FelisCatus/SwitchyOmega#1488]
Can you please ad support for gimme proxys and/or get proxy list free, they both have a free apt that provides socks4, socks5, http and https all from the APIs.

https://gimmeproxy.com/api/getProxy
https://gimmeproxy.com

https://api.getproxylist.com/proxy
https://getproxylist.com

So users can add a new proxy within the add-on without having to go and find one, unless users want to, in that case they can as normal.

Thanks

**Comment by celeron533** [comment]
It looks out of scope.

**Comment by FelisCatus** [comment]
Sorry, out of scope.
