### ISSUE TITLE
PAC模式下状态图标的显示问题

### ISSUE THREAD

**Issue by 046569** [FelisCatus/SwitchyOmega#149]
当前图标代表的似乎是情景模式,也许用户更希望看到图标亮时使用了代理,没亮的时候就是直连,更直观些.
相比之下,使用的是哪个情景模式并不那么重要.

SwitchyOmega 2.2.10
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
PAC 模式下，扩展并不能判断切换结果。
