### ISSUE TITLE
开启自动模式无效。

### ISSUE THREAD

**Issue by penn-z** [FelisCatus/SwitchyOmega#1490]
SwitchyOmega 2.5.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by FelisCatus** [comment]
请具体说一下是什么情况。比如说，全局代理模式是否能正常使用？如果能正常使用，请确定自动切换模式的规则或者规则列表设置正确。如果全局代理模式都不能使用的话，请检查代理服务器协议、主机、端口是否设置正确，代理服务器是否正常工作。

**Comment by penn-z** [comment]
@FelisCatus  全局模式下下可以。规则的话是根据https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt更新的。
代理服务器协议、主机、端口均正常。Chrome下的自动模式有效，Firefox失效。

**Comment by penn-z** [comment]
@FelisCatus 解决了。谢谢你的回答。我设置模式时错了。
