### ISSUE TITLE
Difference between Auto Switch and Bypass list.

### ISSUE THREAD

**Issue by lefebvresam** [FelisCatus/SwitchyOmega#1492]
What is the difference between Auto Switch and Bypass list? I see Bypass list are url's which are not going to the proxy and directly resolved and routed by the Ethernet interfaces. But is Auto switch not doing the same? Basically a list of url's which are not resolved and routed by the proxy? Or are they resolved but not routed by the proxy when they are in the bypass list?

**Comment by FelisCatus** [comment]
@lefebvresam The functionalities overlaps a lot, but everything is handled locally. The only difference is that the bypass list uses different syntax and will be handled by Chrome if a proxy profile is used directly. This is done mainly as a backward compatibility thing. If your rules can be fully expressed using switch rules, feel free to do it there.
