### ISSUE TITLE
Permissions question: Why access to all websites?

### ISSUE THREAD

**Issue by subdavis** [FelisCatus/SwitchyOmega#1493]
What does SwitchyOmega require access to all websites for?  I like this extension a lot, but it seems pretty unreasonable that a web extension that doesn't modify page content should have access to see everything I do.

Would it be possible to make this access optional and granted on-the-fly via the https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions API?

Also, what is the background page for?  It seems wasteful that an extension that simp!ly manages the browser's proxy settings should need to run background processes.  Could the background page be made event-driven such that the browser can effectively sleep it when it isn't in use?  See https://developer.chrome.com/extensions/background_pages `persistent: false` option.

Thanks!

**Comment by FelisCatus** [comment]
@subdavis For both of your questions, SwitchyOmega needs those to provide the feature of changing icon color / tooltip to indicate the profile used for the current tab. SwitchyOmega also has an optional feature to monitor failed sources. The feature itself is explained in the options page.

Also, SwitchyOmega needs access to URLs to be able to download WPAD, or whatever PAC URL / rule list URL you provide.

I'd happily accept a PR to make URL permissions on demand based on WPAD, PAC / rule list downloading AND/OR request monitoring. A event driven background page is not really possible without a big change though.

If you'd like to use SwitchyOmega only as a settings tool, then I personally would recommend that you use all the UI features to configure the switch rules, but export the PAC script (through the options page) for standalone usage. In this way, you can get the best of both worlds.
