### ISSUE TITLE
";" comments in rule list get removed 

### ISSUE THREAD

**Issue by doadin** [FelisCatus/SwitchyOmega#1494]
Chrome 66
SwitchyOmega 2.5.9

**Comment by FelisCatus** [comment]
What do you mean they get removed? They are comments and should be removed any way.

**Comment by doadin** [comment]
a line wrote like:
`;thisisacomment` 
gets removed after navigating away from the Switch rules edit source code in a auto switch profile.

the thisisacomment is usually some kind of text category so I can find and edit entries easily.(or that was the goal) so your saying comments are not permanent? why have any kind of comment support if it just goes away?

**Comment by doadin** [comment]
from the wiki:
`[SwitchyOmega Conditions]
; A line starting with semi-colon is a comment line, ignored by the parser.`

says the parser ignores it not removes it.

**Comment by FelisCatus** [comment]
@doadin Got it. Thanks for the explanation.

The recommended way to leave a note of each rule is to put a `@note foobar` directive in a line directly above each rule. The parser would actually parse and preserve such notes, and make them editable through the table-based editor.

As for comments, they indeed get ignored by the parser. When you switch to the table-based editor, SwitchyOmega needs to parse your rules and present them in a row-by-column way. And when you return to the editor, SwitchyOmega regenerates the rule list from the structure so the original formatting is lost forever. I apologize for the inconvenience, but having a parser that preserves and manipulates the original structure is too much for SwitchyOmega.

I'll update the wiki to reflect the `@note` part.

**Comment by doadin** [comment]
thanks!

**Comment by FelisCatus** [comment]
Wiki updated. Thanks again for taking the time to report this.
