### ISSUE TITLE
打开代理显示网络连接错误

### ISSUE THREAD

**Issue by HLSDG** [FelisCatus/SwitchyOmega#1495]
打开proxyee-down之后，新开网页都是网络连接失败，浏览器是360极速浏览器，选择系统代理之后恢复正常，配置是从github上下载导入的，原因不知，望解决。

SwitchyOmega 2.5.6
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器本身的问题，或者设置的问题，与本项目无关。
