### ISSUE TITLE
cant connect google

### ISSUE THREAD

**Issue by BrianStar** [FelisCatus/SwitchyOmega#1496]
SwitchyOmega 2.5.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36

**Comment by FelisCatus** [comment]
Network errors or proxy servers issues are out of scope of this issue tracker.
