### ISSUE TITLE
autoSwitch不好用

### ISSUE THREAD

**Issue by stark76621240** [FelisCatus/SwitchyOmega#1498]
为什么我用autoSwitch模式什么网址都打不开了？

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by FelisCatus** [comment]
切换规则或者规则列表问题，与此项目无关。
