### ISSUE TITLE
"自动切换模式"下选择"域名通配符"类型并使用通配符(*)配置条件时, 疑似未走代理而是同"直接连接"

### ISSUE THREAD

**Issue by zh-five** [FelisCatus/SwitchyOmega#1499]
@FelisCatus 我非常喜欢这个插件, 发现了一个疑似bug的东东. 奉上我的测试, 希望对插件的优化有所帮助

# 1.测试环境
系统:     macOS 10.13.4 (17E202)
浏览器: chrome 版本 67.0.3396.62（正式版本） （64 位）
SwitchyOmega : 版本 2.5.9

# 2.测试思路
-- 我有一个网站一共有3个环境: 开发环境, 仿真环境和线上环境. 每个环境的页面都会再head里输出特有的标识, 用于判断当前访问的页面到底是访问那个环境的.
-- 自己搭建了一个代理服务器(192.168.6.24:3133), 代理到开发环境
-- 不断修改SwitchyOmega代理配置, 检查代理效果

# 3.测试结果
## 3.1 直接使用"代理服务器"模式, 成功访问到开发环境
系统hosts配置: 无
代理服务器配置:

　网址协议　|　代理协议　| 代理服务器　 |　代理端口　
:---------|:---------|:-----------|:---------
(默认)　   |SOCKS5    |192.168.6.24|3133      

## 3.2 "自动切换模式" + "域名通配符" + 条件中未使用通配符, 成功访问到开发环境

　条件类型　|  　条件设置　  |　情景模式　
:---------|:-------------|:---------
域名通配符　|tmall.v5ip.com|开发环境　　

注: 修改系统的hosts不影响访问

## 3.3 同3.2 只是增加一条记录, 并在条件中使用通配符, 不能总是访问到开发环境

　条件类型　|  　条件设置　  |　情景模式　
:---------|:-------------|:---------
域名通配符　|tmall.v5ip.com|开发环境　　
域名通配符　|*.sjbly.cn    |开发环境　　

发现规律:
- 切换代理模式后的第一次访问是开发环境, 再刷新页面或点击链接则不是开发环境了
- chrome里显示的头信息显示走了代理(Remote Address: 192.168.6.24:3133), 但页面内容和head头标识不是开发环境
- 实际访问的页面, 同系统的hosts配置.例如系统hosts配置到仿真环境, 页面实际就是仿真环境, 但显示走了代理

**Comment by celeron533** [comment]
> 切换代理模式后的第一次访问是开发环境, 再刷新页面或点击链接则不是开发环境了

关闭预读试一试？

![image](https://user-images.githubusercontent.com/3608762/41017883-b0f40a14-6989-11e8-956c-4569d3ab30e7.png)

**Comment by FelisCatus** [comment]
这看上去像是 DNS 问题，见 [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87).

SwitchyOmega 生成一个确定的 PAC 脚本，此 PAC 脚本对于相同的 URL 总是返回相同的结果。另外，  SwitchyOmega 只负责代理设置，不负责网络请求和协议本身。如果有遇到这类结果不总是一致的问题，请第一时间怀疑缓存 / DNS 等。

**Comment by zh-five** [comment]
@celeron533 感谢你的建议, 不过我关闭预读后测试,情况没有变化

**Comment by zh-five** [comment]
@FelisCatus 感谢回复. 我按 FAQ. 里的方法处理, 也就是 @celeron533 截图所示. 问题没有得到解决. 
另外我有个疑问, 以下两种配置,差别为就是第二种使用了通配符,其它的所有环境都是一样的, 第一种正常, 第二种则有问题, 这个通配符到底影响到什么了呢?

　条件类型　|  　条件设置　  |　情景模式　
:---------|:-------------|:---------
域名通配符　|tmall.v5ip.com|开发环境　

　条件类型　|  　条件设置　  |　情景模式　
:---------|:-------------|:---------
域名通配符　|*.v5ip.com|开发环境

**Comment by FelisCatus** [comment]
说真的我不觉得这两种配置有什么不同，除非网页上还有其他 `xxx.v5ip.com` 的子域名资源或者 `v5ip.com` 的域名资源。建议使用开发者工具查看具体有哪些请求，并记得每次清空缓存再实验。
