### ISSUE TITLE
「导出PAC文件」的文件名

### ISSUE THREAD

**Issue by xinhugo** [FelisCatus/SwitchyOmega#150]
界面左上角「导入/导出」→「导出PAC文件」，导出的内容虽然是所有情景模式的规则，但文件名却是「OmegaProfile_（情景模式名称）.pac」。

**Comment by FelisCatus** [comment]
这个应该不是问题，本来导出的就是当前所使用的情景模式的PAC文件。（当然，也包括了所引用的所有情景模式，否则将无法使用。）

**Comment by xinhugo** [comment]
原来如此。
