### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by liCN** [FelisCatus/SwitchyOmega#1500]
FirefoxESR 60.0.1 ，似乎使用 SSR 和 V2ray下，默认的gfwlist更新会失败导致代理失效

SwitchyOmega 2.5.11
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://raw.githubusercontent.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
本来规则列表更新失败就是这样的……但一旦规则列表下载成功一次以后就可以正常使用了。

下次出问题时候，请到选项页面的自动切换下面，确认下规则列表正文。如果存在下载成功过，但是由于自动更新导致规则列表正文变成了空或者乱码之类的情况，请重新开启此 Issue 并说明具体情况，我会看看有没有办法检测。
