### ISSUE TITLE
Auto switch failure with error messages below

### ISSUE THREAD

**Issue by ruruex** [FelisCatus/SwitchyOmega#1501]
The webpage at https://www.google.com might be temporarily down or it may have moved permanently to a new web address.
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

[OmegaLog_1527949067688.txt](https://github.com/FelisCatus/SwitchyOmega/files/2065058/OmegaLog_1527949067688.txt)

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by FelisCatus** [comment]
See #1474. tldr, I need a PAC export to debug these issues.
