### ISSUE TITLE
socks proxies password option

### ISSUE THREAD

**Issue by ProN00b** [FelisCatus/SwitchyOmega#1502]
there seems to be no way to set a password for socks proxies? please fix.

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by FelisCatus** [comment]
See [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#why-cant-i-use-usernamepassword-authentication-for-socks-proxies).
