### ISSUE TITLE
Firefox 的浏览器控制台总是出现 “No matching message handler for the given recipient.” 的错误提示。

### ISSUE THREAD

**Issue by ghcsd** [FelisCatus/SwitchyOmega#1503]
Firefox 的浏览器控制台`（Ctrl+Shift+j）`每隔几秒就出现如下错误提示：
> No matching message handler for the given recipient.  MessageChannel.jsm:914

经过排查怀疑
`browser.runtime.connect` API 中 extensionId 可能没有正确设置为 Firefox 扩展清单中的 ID。
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/connect#Parameters
我尝试将
https://github.com/FelisCatus/SwitchyOmega/blob/533a91964ca7014613988a6d04ddbff17729de40/omega-target-chromium-extension/src/module/switchysharp.coffee#L7
`dpplabbmogkhghncfbfdeeokoefdjegm`  改为 `switchyomega@feliscatus.addons.mozilla.org`
就没再出现类似错误提示。

由于没有太过深入了解扩展的工作原理。
不清楚这么做有什么副作用，还请大佬看看。

另外
https://github.com/FelisCatus/SwitchyOmega/blob/533a91964ca7014613988a6d04ddbff17729de40/omega-target-chromium-extension/src/module/switchysharp.coffee#L11
是否应为 `if not @port? and not @_monitorTimerId` ?

环境：Firefox 57、Nightly 62.0a1 + Proxy SwitchyOmega 2.5.11

**Comment by FelisCatus** [comment]
@ghcsd SwitchyOmega 会不停地发消息看是否存在 SwitchySharp ，如果存在则进入升级相关的逻辑。这段逻辑在 Firefox 上是无意义的，因为不存在 Firefox 版 SwitchySharp. 当时做迁移的时候并没有把这段代码去掉，但此错误信息确实也无害。

如果有一种更优雅的方法判断是否需要发这个消息的话，那么我愿意接受这样的 PR. 尝试几次以后就放弃的方式是不能接受的（因为用户可能会新安装/启用 SwitchySharp）。另外我也希望能尽量避免检测 UA 或者类似的 hack 来判断是否为 Firefox. 欢迎提出建议。

第二个问题，这里应该没有任何差别。

**Comment by ghcsd** [comment]
@FelisCatus 看代码逻辑是定时器5秒刷一次，
但很多时候感觉 2-3 秒就刷一次了，
有时打开浏览器控制台做调试，一直被刷屏，蛮烦躁的。
如果在后台忘记关控制台一段时间甚至导致内存泄漏。。

前段时间截的图。
![image](https://user-images.githubusercontent.com/32384764/41197859-11cd682e-6c9d-11e8-827d-6bcf2d6d4d9b.png)

**Comment by ghcsd** [comment]
应该可以通过 manifest.json 清单固定两环境某些字段判断
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getManifest
通过 `chrome.runtime.getManifest().applications.gecko` (Chrome 大概是非必要项吧？) 判断是否为 Firefox 环境

**Comment by FelisCatus** [comment]
第一个， Firefox 和 Chrome 打包的都有这个字段，或者说我更希望能打一个通用包（除了部分权限不同）。

第二个总感觉很强行啊，但也不是不能考虑吧……

**Comment by ghcsd** [comment]
Firefox 有个官方 API `chrome.runtime.getBrowserInfo()`
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/getBrowserInfo
可惜是异步的，不清楚使用这个对现有代码改造代价大不大。

**Comment by yfdyh000** [comment]
可以 `await browser.runtime.getBrowserInfo();` 转同步。
先 `(window.browser && browser.runtime.getBrowserInfo)`

**Comment by FelisCatus** [comment]
@ghcsd @yfdyh000 这个方法就是我之前说需要避免的。比如判断 `Firefox` 这个 productName ，会没办法处理 Nightly 或者 Firefox 的 fork. 同理我也不想去判断 `vendor == "Mozilla"` 之类的东西。

按照 @ghcsd 一开始的建议，我直接 `location.href.substr(4) == 'moz-'` 了。

**Comment by FelisCatus** [comment]
行，手滑了，测试不充分，我背锅。等 2.5.14 修。

**Comment by FelisCatus** [comment]
2.5.14 已经发布， @ghcsd 麻烦试一下吧。

**Comment by ghcsd** [comment]
@FelisCatus 👌已验证修复。
