### ISSUE TITLE
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED after chrome upgrade to 67.0.3396.62

### ISSUE THREAD

**Issue by hansen0730** [FelisCatus/SwitchyOmega#1505]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by FelisCatus** [comment]
See #1474
