### ISSUE TITLE
[Feature Request] Fallback logic in generated pac script

### ISSUE THREAD

**Issue by qjebbs** [FelisCatus/SwitchyOmega#1506]
Hi, thanks a lot for your amazing extension.

Could you add fallback logic in generated pac script, like

```js
var FindProxyForURL = function (init, profiles) {
    return function (url, host) {
        "use strict";
        // user selected default scene as shown in below image
        var fallback = "+V2Ray \u81ea\u52a8\u5207\u6362";
        var result = init,
            scheme = url.substr(0, url.indexOf(":"));
        do {
            // to keep extension robust to bad return values from user defined pac
            if (!result || profiles[result]) result = fallback;
            result = profiles[result];
            // pass the fallback value to user defined pac
            if (typeof result === "function") result = result(url, host, scheme, fallback)
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result
    }
}(/*...*/)
```
Consider we have following rule (as shown below): all url goes to a user defined pac script first (here I use it to define Hosts), if the user pac doesn't match anything, it returns to the default scene, to keep gfwlist work.

![image](https://user-images.githubusercontent.com/16953333/40954320-abd47e3e-68b6-11e8-807f-242320b843f8.png)

Now I have Host PAC like this:

```js
var FindProxyForURL = function () {
    let hosts = [
        "example.org 127.0.0.1:1081"
    ].map(h => {
        let info = h.split(' ');
        return {
            domain: info[0],
            proxy: "PROXY " + info[1]
        }
    });
    return function (url, host, scheme) {
        var fallback = scheme ? "+V2Ray \u81ea\u52a8\u5207\u6362" : "DIRECT";
        if (isPlainHostName(host)) return fallback;
        for (let conf of hosts) {
            if (
                host == conf.domain ||
                (conf.domain.indexOf('*') != -1 && shExpMatch(host, conf.domain))
            ) return conf.proxy;
        }
        return fallback;
    }
}();
```

It all works as expected, but I have to change this part If I change the default scene.

`var failback = scheme ? "+V2Ray \u81ea\u52a8\u5207\u6362" : "DIRECT";`

I am very looking forward you can add fallback logics, which make the extension robust to user defined pac script, and benefits my use case a lot (Don't need to modify codes if I change the default scene).

My code would be more simple if the feature is implemented:

```js
var FindProxyForURL = function () {
    let hosts = [
        "example.org 127.0.0.1:1081"
    ].map(h => {
        let info = h.split(' ');
        return {
            domain: info[0],
            proxy: "PROXY " + info[1]
        }
    });
    return function (url, host, scheme, fallback) {
        fallback = fallback || "DIRECT";
        if (isPlainHostName(host)) return fallback;
        for (let conf of hosts) {
            if (
                host == conf.domain ||
                (conf.domain.indexOf('*') != -1 && shExpMatch(host, conf.domain))
            ) return conf.proxy;
        }
        return fallback;
    }
}();
```

Thank you in advance!

**Comment by qjebbs** [comment]
Just found I can use virtual scene to solve my problem, but fallback logic is still the better solution. 😁

**Comment by FelisCatus** [comment]
For SwitchyOmega, PAC profiles are considered terminal, just like proxy profiles. Therefore, please allow me to reject any requests that tampers with the return value of a PAC profile, considering the vast amount of issues that it would create (such as loops, non-existent profiles, etc.).

For the record, #12 tracks another kind of fallback logic.

**Comment by qjebbs** [comment]
hmm..understand, thanks again for your great extension.
