### ISSUE TITLE
SwitchyOmega的自动切换模式突然不能用了 ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

### ISSUE THREAD

**Issue by Zprince2000** [FelisCatus/SwitchyOmega#1507]
把所有情景模式都删了, 新建个如下空白的切换模式都不行.
但是如果指定直连或者代理模式就没问题.

[SwitchyOmega Conditions]
@with result

* +direct

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by FelisCatus** [comment]
See #1474.
