### ISSUE TITLE
chrome 浏览器没有连接本地 proxy

### ISSUE THREAD

**Issue by systemio2011** [FelisCatus/SwitchyOmega#1508]
在 chrome 浏览器中单击 google.com 的书签, 没有触发到 shadowsocks 本地代理的连接, 通过
netstat -anb|findstr 1080 的命令查看, 没有新的连接产生. 

重新启动机器后, 此问题解决, 看起来有些情况下此插件不工作了. 

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by FelisCatus** [comment]
下次不行的时候，能麻烦鼠标悬停在扩展图标上，然后看显示的内容是什么吗？尤其是，最终显示使用的是代理还是 DIRECT?

另外，如果显示的是 DIRECT ，麻烦到选项的自动切换下面看看规则列表的正文是否还完好。
