### ISSUE TITLE
规则条目较多时，操作卡顿

### ISSUE THREAD

**Issue by xinhugo** [FelisCatus/SwitchyOmega#151]
某个情景模式（自动切换模式）的规则较多时，操作卡顿。

在线规则列表的规则较多时，没有卡顿问题。

**Comment by FelisCatus** [comment]
现在怎么办？我已经优化过很多次了……
~~不然干脆把编辑界面换成纯文本吧，绝对不卡~~

只能减少一些界面元素了吗？或者放弃 Angular 自己用 jQuery 写？这个好像也不行。

**Comment by FelisCatus** [comment]
说起来，您那边有多少条规则呢？说个数字作为参考吧？

**Comment by xinhugo** [comment]
GAE组：798条。

这是我的备份：https://drive.google.com/file/d/0B7HMX9RBftW3NmZ3UElsc3ktZjg/view?usp=sharing

**Comment by FelisCatus** [comment]
还是等 #80 吧……估计无论怎么优化， 798 条也还是没办法的。

**Comment by xinhugo** [comment]
好的，谢谢。
