### ISSUE TITLE
SwitchyOmega AutoSwitch mode doesn't work some day, error info "ERR_MANDATORY_PROXY_CONFIGURATION_FAILED"

### ISSUE THREAD

**Issue by Zprince2000** [FelisCatus/SwitchyOmega#1510]
But it works if use direct or proxy mode.
I also tried deleting all profiles, create a new and only switch profile like below, still not work.

[SwitchyOmega Conditions]
@with result

+direct

SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36

**Comment by FelisCatus** [comment]
See #1474.
