### ISSUE TITLE
代理模式中，登陆不了chrome账号

### ISSUE THREAD

**Issue by arvinlee2015** [FelisCatus/SwitchyOmega#1513]
SwitchyOmega 2.5.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by arvinlee2015** [comment]
When I use SwitchOmega, I can not login chrome

**Comment by celeron533** [comment]
目前在chrome浏览器里，用户登陆时网络流量仅通过系统代理，chrome内部的代理插件无效
