### ISSUE TITLE
How to add a second-level domain?

### ISSUE THREAD

**Issue by Antecer** [FelisCatus/SwitchyOmega#1514]
I test it as

```
*id.heroku.com
^id\.heroku\.com
*://id.heroku.com/*
```
all of them do not work!
i do not want set it to
```
*.heroku.com
```
because i can open the url(`dashboard.heroku.com`) with direct

**Comment by FelisCatus** [comment]
What type of conditions are you using? I'd suggest using the domain wildcard condition and set the pattern to `*id.heroku.com`, if you intend to match `foobarid.heroku.com`. Keep in mind that each web page can contain more resources which may or may not fall under the same domain. You will need to have enough rules to cover all resources on the page.

Note that you can also put two separate rules, one with `dashboard.heroku.com` that goes direct, and then another `*.heroku.com` that goes to another profile. The rules are evaluated from the top to the bottom.
