### ISSUE TITLE
Traffic flows through a random proxy

### ISSUE THREAD

**Issue by 2NuFyeat4PZt** [FelisCatus/SwitchyOmega#1515]
I have a number of proxy profiles defined (~60). I see RSTs in Wireshark from the proxy that's set (and set to reject), but traffic flows via another proxy. The proxy used is seems to have been chosen at random.

The OmegaLog contains:
Options << Options#applyProfile [
    "Frapr005"
]
Options << Options#updateProfile [
    [
        "Frapr005"
    ]
]
Options << Options#updateProfile []
Options << Options#applyProfile [
    "Lab - Viprion3/4-xnet"
]
Options << Options#updateProfile [
    [
        "Lab - Viprion3/4-xnet"
    ]
]
Options << Options#applyProfile [
    "Lab - Viprion3/4-xnet"
]
Options << Options#updateProfile [
    [
        "Lab - Viprion3/4-xnet"
    ]
]

"Lab - Viprion3/4-xnet" was the VIP set. Traffic flows through a proxy which is neither that or frapr005, frapr004.

SwitchyOmega 2.5.11
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by 2NuFyeat4PZt** [comment]
I have IE, Chrome and Firefox installed. IE is configured using a PAC; Chrome and Firefox have SwitchyOmega installed. Chrome is working as expected. Firefox has no other network related extensions.

Firefox does send some traffic to the SwitchyOmega proxy, which is actually a VIP; the load balancer is (currently) configured to reject; after 10 seconds of being knocked back, Firefox starts using the proxy IE is currently attached to through the PAC. WPAD is also configured in the network, pointing to the PAC file.

**Comment by FelisCatus** [comment]
Sorry, I didn't see that you're using Firefox. Firefox would try to get all proxies from all sources and try them one by one. This isn't something that I can change on SwitchyOmega's side.
