### ISSUE TITLE
What's the recommended way to use a direct connection for a specific site?

### ISSUE THREAD

**Issue by Qwerty-Space** [FelisCatus/SwitchyOmega#1517]
Hello, 

So, there are some websites (https://www.dominos.co.uk) that don't work if I use a proxy.  Is it recommended to add them to the bypass list, or to auto switch mode?

**Comment by FelisCatus** [comment]
Hi,

You can do either. The switch rules are better supported in terms of SwitchyOmega features, but the bypass list still supported for the sake of consistency with other browser / system proxy dialogs.

**Comment by Qwerty-Space** [comment]
Thank you.
Where can I send feature requests?
