### ISSUE TITLE
你们有没有这种扩展显示问题

### ISSUE THREAD

**Issue by yjd** [FelisCatus/SwitchyOmega#1519]
浏览器：CentBrowser

启动空白标签时设置Omega为直接连接
![2018-0614_092444](https://user-images.githubusercontent.com/6856740/41386652-1d7d8a12-6fb5-11e8-8a4f-fce6866645a7.png)

然后关闭浏览器再重开就会这样
![2018-0614_092503](https://user-images.githubusercontent.com/6856740/41386667-338135a2-6fb5-11e8-8d84-dcc277912908.png)

点击恢复设置就会这样，Omega的图标跑隐藏里了
![2018-0614_092519](https://user-images.githubusercontent.com/6856740/41386679-40185ba6-6fb5-11e8-8055-be9a32ea066c.png)

但如果从第一步把Omega设置为系统代理(第二项)就没有这种现象。

**Comment by celeron533** [comment]
“恢复”的意思是，不启用新的代理设置工具（SwitchyOmega），继续使用当前的代理设置

**Comment by yjd** [comment]
@celeron533
主要是如果这样设置会导致其他扩展的图标混乱或被隐藏掉。

**Comment by celeron533** [comment]
这是chrome的行为，和switchyomega无关

**Comment by yjd** [comment]
@celeron533 那明白了。谢谢！
