### ISSUE TITLE
Https * wildcard still being sent to proxy using Auto Switch

### ISSUE THREAD

**Issue by c0debreaker** [FelisCatus/SwitchyOmega#1522]
When I call `https://www.example.com/edge` and `https://www.example.com/flight`, I want it to be sent to our proxy server.
However, when I call `https://www.example.com/*`, I want to DIRECT connection.

I tried it but going to https://www.example.com/app, it still went to our proxy

Here is the screenshot of my Auto Switch rule - https://i.imgur.com/ERQ5btA.png

**Comment by c0debreaker** [comment]
I think it's now working after I changed it to URL Wildcard instead of Host.

**Comment by c0debreaker** [comment]
I was wrong, URL Wildcard didn't help :(

**Comment by c0debreaker** [comment]
I figured out a way. So here's what I did. In Switchy Omega, I updated the rule by changing it to host wildcard and removed `https://` string. What I have there is just `www.example.com`. It is set to DIRECT. Then I created a nodejs proxy middleware that will handle the path. If path is /edge or /flight, I have a code that will forward it to a config to use https-proxy-agent. Other path will be served by my normal Express web server which is my application running locally.

**Comment by FelisCatus** [comment]
Full URL matching is no longer possible for https:// URLs as of Chrome 52. See https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-Full-URL-Limitation

Therefore, this is no longer possible in SwitchyOmega unless the command-line flag is used (if not yet disabled by Chromium).

By the way, a warning would show on the top of the profile options page if you attempt to use these rules in your Switch Profile.

**Comment by c0debreaker** [comment]
My solution worked. Is it ok though?
