### ISSUE TITLE
AutoSwitch not work.

### ISSUE THREAD

**Issue by justdark** [FelisCatus/SwitchyOmega#1523]
[Direct] work good.
[proxy] work good.
[auto switch] not work at all, even I create a new Switch Profile without any rules, I can't get to any website although the default is [Direct]

SwitchyOmega 2.5.14
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by FelisCatus** [comment]
What happens if you use auto switch? Is there an error code? See also #1474.

**Comment by justdark** [comment]
yes，ERR_MANDATORY_PROXY_CONFIGURATION_FAILED error. 
Do you know how to fix it on mac?

**Comment by FelisCatus** [comment]
From the previous discussion, it is highly likely to be an issue with Chromium. Please first export a PAC script from your (probably empty) Switch Profile via the options page. Then, try that script without SwitchyOmega by following this comment: https://github.com/FelisCatus/SwitchyOmega/issues/1474#issuecomment-396016815

Let's continue the discussion on #1474.
