### ISSUE TITLE
有时候右上角的图标会完全消失

### ISSUE THREAD

**Issue by sm0731** [FelisCatus/SwitchyOmega#1524]

**Comment by celeron533** [comment]
什么浏览器

**Comment by sy703016789** [comment]
浏览器是chrome  版本 67.0.3396.87 (正式版本) (64 位元)  
![image](https://user-images.githubusercontent.com/37198586/41757024-1544b966-7612-11e8-85a3-f70fbb61ab9a.png)

**Comment by sy703016789** [comment]
变成了淡黄色 基本上看不见......

**Comment by FelisCatus** [comment]
选项页面中可以设置各个情景模式的颜色。左侧选择一个情景模式，然后单击中间情景模式名字左边的色块即可。

**Comment by sm0731** [comment]
哦 是这样啊 谢谢啦~

Felis Catus <notifications@github.com> 于2018年6月26日周二 上午11:06写道：
