### ISSUE TITLE
DNS proxy on autoswitch mode

### ISSUE THREAD

**Issue by Dees7** [FelisCatus/SwitchyOmega#1525]
Hello. 
My provider sniff dns and block before opening page. I set
network.proxy.socks_remote_dns

and if manualy change proxy all ok. 
But if I check "auto switch"  then dns sent directly.

Is it possible change  proxy before dns resolve?

SwitchyOmega 2.5.14
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://sovetnik.market.yandex.ru",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
SwitchyOmega would first determine whether a URL should go through a proxy. If so, the proxy is used and all DNS requests should be done remotely, for HTTP, HTTPS and SOCKS5. If not, direct connection is used. If I understand Firefox correctly, `network.proxy.socks_remote_dns` WOULD NOT change anything if SwitchyOmega is used.

In this process, SwitchyOmega ONLY tells Firefox what proxy to use, and whether to use remote DNS or not only if a proxy is used. It does not implement any network internals. Especially, it does not make the DNS requests itself. Therefore, I don't think it is possible to handle your case. With that being said, you may try to add all the URLs that your provider probes to the switch rules and see if that helps.
