### ISSUE TITLE
使用规则列表后，设置页面卡顿

### ISSUE THREAD

**Issue by dodying** [FelisCatus/SwitchyOmega#1526]
使用的规则是 [gfwlist](https://github.com/gfwlist/gfwlist)
保存并更新规则后，在该页面会卡顿

希望不要显示规则和PAC的具体内容，一般来说，也没有人会手动编辑的吧

SwitchyOmega 2.5.14
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by celeron533** [comment]
我这边没有这个问题啊
`Version 66.0.3359.181 (Official Build) (64-bit)`

**Comment by dodying** [comment]
试试这个备份吧

[OmegaOptions.bak.txt](https://github.com/FelisCatus/SwitchyOmega/files/2122577/OmegaOptions.bak.txt)

**Comment by dodying** [comment]
好吧，那能隐藏规则列表正文吗

**Comment by FelisCatus** [comment]
感谢反馈，卡顿问题应该不是由于此文本框内容引起的，而是由于 SwitchyOmega 更新列表后需要刷新页面和选项。此问题暂无解决方案。
