### ISSUE TITLE
Pac Profile Shown one or more resources failed.

### ISSUE THREAD

**Issue by mehediustc15** [FelisCatus/SwitchyOmega#1528]
I have created a pac profile by using this http://ftp.ustclug.org/light/https.pac URL. Its working well in my lab Computer but its not working properly in my laptop. It was working nice before in my laptop before. When i try to open youtube or facebook its shown one or more resources filed. What can i do regarding this situation.

**Comment by FelisCatus** [comment]
If the website works just fine, you can safely ignore these warnings. You can even disable all such warnings in the options page. If not, you may try to modify your PAC script to cover those URLs.

By the way, SwitchyOmega allows you to use your PAC Profile as one of the results in Switch Profiles. Therefore, if you need some rules that only make sense on your laptop, you can consider adding these rules to a Switch Profile, and set the default profile to your PAC Profile. In this way, those rules will be evaluated first.
