### ISSUE TITLE
ipv6规则

### ISSUE THREAD

**Issue by QwertyJack** [FelisCatus/SwitchyOmega#1529]
需求：ipv6地址单独分配一个通道

自动切换模式->条件类型，新增“ipv6”，如果解析到ipv6地址，则匹配这个规则。

**Comment by QwertyJack** [comment]
目前可以做到吗

**Comment by celeron533** [comment]
PAC应该做不到这个

**Comment by QwertyJack** [comment]
@celeron533 
`shExpMatch(dnsResolve(host), "*:*")` 貌似可行，然而我的win7不行
ref: http://desrablog.blogspot.com/2009/04/creating-pac-to-auto-config-ipv6-proxy.html

**Comment by FelisCatus** [comment]
SwitchyOmega 基于 URL 来判断规则，不支持先进行 DNS 解析再判断。可以试试看使用 PAC 情景模式，然后用 `dnsResolve` 手动解决。请注意这样的话，解析是在本地进行，也就是说 ISP / 网络管理员可能可以对此 DNS 的结果进行劫持等，甚至包括强行返回 IPv4 地址等。并且，返回结果同时有 IPv6 和 IPv4 时，浏览器未必会使用 IPv6 的地址。

**Comment by QwertyJack** [comment]
判断规则里不是有ip字面吗？难道说ip字面不适用于域名？

**Comment by FelisCatus** [comment]
IP 字面只适用于字面量。也就是说， `http://[::1]/` 这样的，直接使用 IP 地址的网址。
