### ISSUE TITLE
能否支持在一条规则中同时设置多种切换条件(and或者or之类的)

### ISSUE THREAD

**Issue by SwordRays** [FelisCatus/SwitchyOmega#1530]
1、能否支持一条规则中同时设置多种切换条件，比如在按域名切换的基础上增加按时间切换。
应用场景：qq.com
晚上在家可以直连，不需要代理
周一至周五白天在公司，需要通过代理才能访问。
那么就需要一条规则：周一-周五的9:00AM-5:30PM时对该域名通过代理访问。
现有的切换规则似乎只能在多种切换条件中选择一种，实现不了这种需求。

SwitchyOmega 2.5.14
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FelisCatus** [comment]
选项>界面>切换选项 下可以解锁高级切换条件。解锁后，可以使用当前小时数作为条件。
