### ISSUE TITLE
配置导出报错

### ISSUE THREAD

**Issue by chuixifeng** [FelisCatus/SwitchyOmega#1531]
![default](https://user-images.githubusercontent.com/22932752/41818681-372d5a12-77e6-11e8-83b3-c28c08acdb3d.png)

SwitchyOmega 2.5.14
Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://duckduckgo.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
我这里无法复现，建议更新 Firefox. 如果更新还不能解决，建议换 Beta 或者 Nightly 版再试。

直说的话，感觉不像是 SwitchyOmega 的问题。

**Comment by chuixifeng** [comment]
谢谢哈，我的代理少，只是想给不会设置的同学直接用，现在麻烦的也可以弄好。我用portableapp  便携版firebox一般保持最新，有可能跟这个有关吧。

**Comment by FelisCatus** [comment]
好的，建议去 Firefox portable 那边反馈。
