### ISSUE TITLE
火狐浏览器开启代理没有效果

### ISSUE THREAD

**Issue by zmyspc** [FelisCatus/SwitchyOmega#1533]
改成全部代理或者自动切换都失效，导出的同样代理配置在谷歌浏览器一切正常。

SwitchyOmega 2.5.14
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: http://ocsp2.globalsign.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
改成全部代理的时候访问网页有任何错误信息吗？还是会使用直接连接？

如果无论选什么都是直接连接，请右键点击 SwitchyOmega 图标，选择保存错误日志，然后上传到这里。

**Comment by SpaceEggs** [comment]
把 Network Proxy 设置成 no proxy。
选项在 Options -> General -> Network Proxy

**Comment by FelisCatus** [comment]
Firefox 上的 SwitchyOmega v2.5.16 已经发布。这个版本使用了新的 API, 应该可以修复大部分问题。以上反馈的一切问题，请在新版本下测试是否修复。如果没有修复，请告知，并提供错误日志。注意：之前版本的任何错误信息和日志均已无效，请在新版重新导出。
