### ISSUE TITLE
Does not Ressolve DNS through socks5

### ISSUE THREAD

**Issue by Mojtaba-Shafaei** [FelisCatus/SwitchyOmega#1534]
Please add an option to enable/disable [proxy dns when using socks] .
FoxyProxy and proxySwitcher have this option.

SwitchyOmega 2.5.15
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by FelisCatus** [comment]
SwitchyOmega on Firefox always tells Firefox to use remote DNS for consistency with Chrome. #1355 tracks the feature request to disable remote DNS on FIrefox.
