### ISSUE TITLE
Firefox中的SwitchyOmega的CPU占用莫名的很高

### ISSUE THREAD

**Issue by artemith** [FelisCatus/SwitchyOmega#1535]
我同时使用Chrome和Firefox版的SwitchyOmega。firefox有时候的CPU占用率很高，这时候停止SwitchyOmega后CPU占用率就会降下来，而Chrome则不会发生此问题。

我的电脑是Win10, CPU: i7-6700HQ, 内存16G

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by lkebin** [comment]
Duplicate of #1392
