### ISSUE TITLE
都安装好了，但是还是显示ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by MaggieHee** [FelisCatus/SwitchyOmega#1539]
![_20180704193948](https://user-images.githubusercontent.com/37926578/42275215-1e0a1ef6-7fc2-11e8-903f-8cea6183da5d.png)
![_20180704193954](https://user-images.githubusercontent.com/37926578/42275217-1f0a466e-7fc2-11e8-945e-fc32c40e20d0.png)
![_20180704193958](https://user-images.githubusercontent.com/37926578/42275219-20473ae6-7fc2-11e8-9e33-d51070003661.png)

**Comment by FelisCatus** [comment]
代理服务器问题，与本项目无关。另外，建议删除第二张图片以防止您的服务器地址泄露。
