### ISSUE TITLE
在mac下翻墙的速度非常慢，控制台很多错误

### ISSUE THREAD

**Issue by leiyong316** [FelisCatus/SwitchyOmega#154]
![image](https://cloud.githubusercontent.com/assets/2143362/5598864/1f95c28a-92f8-11e4-945c-3b9031b7bb18.png)

SwitchyOmega 2.2.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
GoAgent 问题与本项目无关。

**Comment by leiyong316** [comment]
请问下在mac下的使用方法不是结合goagent吗？ 之前用的switchySharp是要结合goagent的。 如果我的方法使有误，请问在mac下如何使用才正确

**Comment by FelisCatus** [comment]
@leiyong316 您的配置方法完全正确，但网络请求慢等问题是 GoAgent 本身的问题。
