### ISSUE TITLE
[feature]在auto-switch模式下, 不能设置默认情景模式为"系统代理"

### ISSUE THREAD

**Issue by yinxin630** [FelisCatus/SwitchyOmega#1540]
![image](https://user-images.githubusercontent.com/6939365/42370046-4d391074-813e-11e8-928b-37ab3df96bdd.png)
![image](https://user-images.githubusercontent.com/6939365/42370060-583d1bf0-813e-11e8-97e9-afcd7456adb5.png)

期望该处可以设置为"系统代理"

**Comment by FelisCatus** [comment]
见 [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E4%B8%AD%E4%B8%8D%E8%83%BD%E9%80%89%E6%8B%A9%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86).
