### ISSUE TITLE
Different proxy configuration for private mode

### ISSUE THREAD

**Issue by exelents** [FelisCatus/SwitchyOmega#1541]
Dear developers,
I would like to to turn on different proxy in private mode window, but when I change it, it's also changed in "usual mode" window. Can you change this behaviour, to allow user turning on different proxies in private and usual modes? 

SwitchyOmega 2.5.15
Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
```
{
    "event": "proxyScriptLog",
    "message": "Warning: Proxy script not initialized on handling: https://cdn.ghostery.com",
    "level": "warn"
}
```

**Comment by FelisCatus** [comment]
This is tracked in #10. This is not going to happen soon though, due to the large amount of code changes required.

One way to work around this issue would be to install SwitchyOmega in another [Firefox Profile](https://developer.mozilla.org/en-US/Firefox/Multiple_profiles).
