### ISSUE TITLE
if a proxy fails it goes directly to internet instead of stopping with error.

### ISSUE THREAD

**Issue by rezad1393** [FelisCatus/SwitchyOmega#1545]
in new version (I think it is the new version fault because I have not seen this before) if a proxy is not working, say it process is killed, then now the request goes direct to internet, instead of saying proxy is not working as before.
this makes debugging proxy errors hard.
EDIT never mind it seems it was temporary.
I dont know why that happened.

SwitchyOmega 2.5.16
Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by FelisCatus** [comment]
I can't reproduce this on my side with Nightly 63.0a1 (2018-07-08). Firefox refuses to load the page if the proxy cannot be reached:

> The proxy server is refusing connections
> Firefox is configured to use a proxy server that is refusing connections.

I'm also interested in how this can be tested. One thing that you may try is to select your proxy profile directly in the popup and then visit `example.com`. Then kill your proxy process and refresh the page. It should show you the error above. Keep in mind the your browser may cache pages and resources so it may be necessary to reload or force-reload.

Could you please ensure that proxy is set to `No proxy` in the Firefox preferences, and no other proxy-controlling extensions are installed? Some Ad-blocking extensions may also use the proxy API and you can disable all other extensions just to be sure. If that does not help, could you please also try the latest Nightly build?
