### ISSUE TITLE
SOCKS4 broken after update Firefox to version >=60.0

### ISSUE THREAD

**Issue by rignatev** [FelisCatus/SwitchyOmega#1548]
After update Firefox from v. 59.0.3 to 61.0.1 the SOCKS4 stopped working.
Without extension SOCKS4 works fine.

Workaround.
1. Choose any non SOCKS4 profile in SwitchyOmega dropbox.
2. Set SOCKS4 server and port in the Firefox proxy settings.
3. Restart Firefox.
4. Before use profile with SOCKS4, switch to predefined profile [System Proxy] and open any URL. The URL will open through SOCKS4 server that you entered in the Firefox proxy settings.
5. Now you may use you SwitchyOmega profile with SOCKS4.
6. You may disable SOCKS4 in the Firefox proxy settings and SwitchyOmega profile with SOCKS4 will still work.

Before each Firefox startup, you need to perform steps 1,2,4 to SwitchyOmega profile SOCKS4 to work.
If you set SOCKS4 server and port in the Firefox proxy settings, but firstly open URL with SwitchyOmega profile SOCKS4, SOCKS4 will not work with [System Proxy] too, until you restart the Firefox.

SwitchyOmega 2.5.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by FelisCatus** [comment]
Fixed in v2.5.18.
cc @rignatev @anon88841

(Also, sorry for the delay. I had been busy with some personal matters in the past few weeks. Thanks again for letting me know about the issue.)
