### ISSUE TITLE
auto switch problem

### ISSUE THREAD

**Issue by yanboyang713** [FelisCatus/SwitchyOmega#155]
when I use PAC, The rule host willcard *.iqiyi.com does NOT working. If manual change to PAC, does is working. 

SwitchyOmega 2.2.11
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
I can't understand you. Please use your native language (e.g. Chinese?).

**Comment by FelisCatus** [comment]
Closing this issue because I just can't understand you. Please make your self clear next time.
