### ISSUE TITLE
設定多組 Proxy servers

### ISSUE THREAD

**Issue by delphinuz** [FelisCatus/SwitchyOmega#1551]
SwitchyOmega只有一个Proxy server，能否像smartproxy可設定多個，然後手動切換某一個？

若可以使用多個proxy server，能否加上像負載平均的功能，比如不同tabs或每次不同的連線切換到不同的proxy server(隨機、按順序、依domain指定等）？

**Comment by FelisCatus** [comment]
可以在选项界面上新建多个代理情景模式，每个情景模式可以填一个不同的代理服务器。自动切换可以根据网址来选择使用哪个，也可以手动在弹出菜单里切换。

负载平均、不同tabs等无法实现。

随机代理可以通过新建一个 PAC 情景模式实现。具体请自行网上查找范例 PAC 脚本。

**Comment by delphinuz** [comment]
作者可能誤會了。

比如有三個代理，而目前是自动模式，當連到某站需要代理時，可以選擇A代理。若A代理故障，那可“直接”選擇B或C代理，但無論選擇A/B/C都是在auto模式。

目前的方式，是需要再進入設定，再修改自動模式的代理，比如A改到B。

情景模式是依網址選擇代理(比如A，而且也非自動模式)，但如果代理A故障了，必需再進入設定改為其它代理，無法直接由addon上更換另一個代理。

**Comment by celeron533** [comment]
PAC可能不支持这样的特性

**Comment by delphinuz** [comment]
因為在smartproxy有看到這樣的用法，才想說是否switchyomega也可以加入。

這樣會方便很多，因為隨時可以手動切換代理。

**Comment by FelisCatus** [comment]
见 #578. 在实现这个功能之前，可以试着用[这个办法](https://github.com/FelisCatus/SwitchyOmega/issues/578#issuecomment-138049915) 来手动指定一系列代理服务器。或者可以用在自动切换里用虚情景模式代替代理模式，至少改起来方便一些，可以直接在弹出菜单里改。
