### ISSUE TITLE
希望作者大大可以添加这个设置

### ISSUE THREAD

**Issue by 22332333** [FelisCatus/SwitchyOmega#1552]
希望对于“新打开的网页/新标签页” 可以添加一个设置
“新打开网页默认为XXXX情景模式”
这样的话，打开某些网页速度就不会变慢了。

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5702.400 QQBrowser/10.2.1893.400

**Comment by celeron533** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#can-you-add-support-for-tab-based-or-window-based-switching
