### ISSUE TITLE
Proxy not used for addons.mozilla.org

### ISSUE THREAD

**Issue by Glandos** [FelisCatus/SwitchyOmega#1553]
Since the last releases of Firefox and/or SwitchyOmega, the proxy settings is not used anymore for addons.mozilla.org.

I know that Firefox has a special workflow for some pages, that may forbid the extension to set the proxy.
I don't know if it is linked to Firefox or SwitchyOmega. I'll try to do some tests during the day.

SwitchyOmega 2.5.16
Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by Glandos** [comment]
OK, I confirm that it worked in 2.5.15, but not in 2.5.16.
This is maybe not the fault of this extension. But the API is not OK for being used behind a real blocking proxy.

**Comment by Glandos** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1476570

**Comment by FelisCatus** [comment]
Seems the fix is committed targeting mozilla63. I'd expect the fix to land soon.

Also, feel free to try this on Firefox Nightly and let them know whether it works or not.

**Comment by FelisCatus** [comment]
Fixed upstream for 62. Beta / Nightly builds may be required.

**Comment by Glandos** [comment]
Yes. That was quite a quick fix from Mozilla.
