### ISSUE TITLE
"外部情景模式" 选项的 bug

### ISSUE THREAD

**Issue by pexcn** [FelisCatus/SwitchyOmega#1554]
![11](https://user-images.githubusercontent.com/4590439/42759584-1426428a-893a-11e8-9ade-70d4ef50aac6.png)

每次取消勾选 "在弹出菜单中显示菜单项，以导入其他应用提供的代理设置。" 这个选项，过一段时间它就会自动勾选上。

**Comment by FelisCatus** [comment]
@pexcn 请问下是否有在另外的设备开启选项同步？请试试看在这个设备上禁用选项同步。

**Comment by pexcn** [comment]
@FelisCatus 笔记本和台式机都开启了选项同步，不过台式机我已经很久没有开机了。
刚刚开了检查了下，现在两台设备的 "在弹出菜单中显示菜单项..........提供的代理设置" 都是取消勾选状态。

**Comment by FelisCatus** [comment]
直接把选项同步禁用掉试试看。另外，下次变回去之后，请立即右键点击 SwitchyOmega 图标然后导出错误日志，上传到这里。多谢！

**Comment by pexcn** [comment]
好的

**Comment by pexcn** [comment]
又出现了，附上 log: [OmegaLog_1531898236015.txt](https://github.com/FelisCatus/SwitchyOmega/files/2204780/OmegaLog_1531898236015.txt)

@FelisCatus

**Comment by FelisCatus** [comment]
多谢，不过错误信息本身看不出什么问题，我需要点时间自己试试看能否复现以及复查代码。

**Comment by pexcn** [comment]
@FelisCatus 我重置了SwitchyOmega, 然后这个问题暂时没出现了。但是 "在弹出菜单中显示菜单项..........提供的代理设置" 这个选项还是会偶尔自动勾选。

**Comment by FelisCatus** [comment]
已复现，修复中。

**Comment by pexcn** [comment]
感谢。
