### ISSUE TITLE
用 SwitchyOmega 自动替换模式后，无法正常上网，开全局模式再切换到系统代理才可以正常上网。 报"ERR_CONNECTION_CLOSED"

### ISSUE THREAD

**Issue by oliwill** [FelisCatus/SwitchyOmega#1555]
用 SwitchyOmega 自动替换模式无法正常上网，开全局模式再切换到系统代理才可以正常
[OmegaLog_1531746257107.txt](https://github.com/FelisCatus/SwitchyOmega/files/2197876/OmegaLog_1531746257107.txt)
上网。
报"ERR_MANDATORY_PROXY_CONFIGURATION_FAILED"

Google Chrome 版本 67.0.3396.99（正式版本） （64 位）
SwitchyOmega 版本 2.5.15

163267: NONE
PROXY_CONFIG_CHANGED
Start Time: 2018-07-16 21:06:05.279

t=16231 [st=0]  PROXY_CONFIG_CHANGED
                --> old_config =
                       PAC script: data:application/x-ns-proxy-autoconfig;base64,LypPbWVnYVByb2ZpbGUqImRpcmVjdCIqdW5kZWZpbmVkKi92YXIgRmluZFByb3h5Rm9yVVJMPWZ1bmN0aW9uKGluaXQscHJvZmlsZXMpe3JldHVybiBmdW5jdGlvbih1cmwsaG9zdCl7InVzZSBzdHJpY3QiO3ZhciByZXN1bHQ9aW5pdCxzY2hlbWU9dXJsLnN1YnN0cigwLHVybC5pbmRleE9mKCI6IikpO2Rve3Jlc3VsdD1wcm9maWxlc1tyZXN1bHRdO2lmKHR5cGVvZiByZXN1bHQ9PT0iZnVuY3Rpb24iKXJlc3VsdD1yZXN1bHQodXJsLGhvc3Qsc2NoZW1lKX13aGlsZSh0eXBlb2YgcmVzdWx0IT09InN0cmluZyJ8fHJlc3VsdC5jaGFyQ29kZUF0KDApPT09NDMpO3JldHVybiByZXN1bHR9fSgiKyIseyIrIjpmdW5jdGlvbih1cmwsaG9zdCxzY2hlbWUpeyJ1c2Ugc3RyaWN0IjtpZigvKD86XnxcLil5b3V0dWJlXC5jb20kLy50ZXN0KGhvc3QpKXJldHVybiIrcml4Y2xvdWQiO3JldHVybiJESVJFQ1QifSwiK3JpeGNsb3VkIjpmdW5jdGlvbih1cmwsaG9zdCxzY2hlbWUpeyJ1c2Ugc3RyaWN0IjtpZigvXjEyN1wuMFwuMFwuMSQvLnRlc3QoaG9zdCl8fC9eOjoxJC8udGVzdChob3N0KXx8L15sb2NhbGhvc3QkLy50ZXN0KGhvc3QpKXJldHVybiJESVJFQ1QiO3JldHVybiJTT0NLUzUgMTI3LjAuMC4xOjEwODE7IFNPQ0tTIDEyNy4wLjAuMToxMDgxIn19KTs=
                --> new_config =
                       PAC script: data:application/x-ns-proxy-autoconfig;base64,LypPbWVnYVByb2ZpbGUqImF1dG8gc3dpdGNoIioxNjRhMzI4MzRjZiovdmFyIEZpbmRQcm94eUZvclVSTD1mdW5jdGlvbihpbml0LHByb2ZpbGVzKXtyZXR1cm4gZnVuY3Rpb24odXJsLGhvc3QpeyJ1c2Ugc3RyaWN0Ijt2YXIgcmVzdWx0PWluaXQsc2NoZW1lPXVybC5zdWJzdHIoMCx1cmwuaW5kZXhPZigiOiIpKTtkb3tyZXN1bHQ9cHJvZmlsZXNbcmVzdWx0XTtpZih0eXBlb2YgcmVzdWx0PT09ImZ1bmN0aW9uIilyZXN1bHQ9cmVzdWx0KHVybCxob3N0LHNjaGVtZSl9d2hpbGUodHlwZW9mIHJlc3VsdCE9PSJzdHJpbmcifHxyZXN1bHQuY2hhckNvZGVBdCgwKT09PTQzKTtyZXR1cm4gcmVzdWx0fX0oIisiLHsiKyI6ZnVuY3Rpb24odXJsLGhvc3Qsc2NoZW1lKXsidXNlIHN0cmljdCI7aWYoLyg/Ol58XC4peW91dHViZVwuY29tJC8udGVzdChob3N0KSlyZXR1cm4iK3JpeGNsb3VkIjtyZXR1cm4iK2F1dG8gc3dpdGNoIn0sIithdXRvIHN3aXRjaCI6ZnVuY3Rpb24odXJsLGhvc3Qsc2NoZW1lKXsidXNlIHN0cmljdCI7aWYoLyg/Ol58XC4peW91dHViZVwuY29tJC8udGVzdChob3N0KSlyZXR1cm4iK3JpeGNsb3VkIjtpZigvXmludGVybmFsXC5leGFtcGxlXC5jb20kLy50ZXN0KGhvc3QpKXJldHVybiJESVJFQ1QiO2lmKC8oPzpefFwuKWV4YW1wbGVcLmNvbSQvLnRlc3QoaG9zdCkpcmV0dXJuIitwcm94eSI7cmV0dXJuIkRJUkVDVCJ9LCIrcml4Y2xvdWQiOmZ1bmN0aW9uKHVybCxob3N0LHNjaGVtZSl7InVzZSBzdHJpY3QiO2lmKC9eMTI3XC4wXC4wXC4xJC8udGVzdChob3N0KXx8L146OjEkLy50ZXN0KGhvc3QpfHwvXmxvY2FsaG9zdCQvLnRlc3QoaG9zdCkpcmV0dXJuIkRJUkVDVCI7cmV0dXJuIlNPQ0tTNSAxMjcuMC4wLjE6MTA4MTsgU09DS1MgMTI3LjAuMC4xOjEwODEifSwiK3Byb3h5IjpmdW5jdGlvbih1cmwsaG9zdCxzY2hlbWUpeyJ1c2Ugc3RyaWN0IjtpZigvXjEyN1wuMFwuMFwuMSQvLnRlc3QoaG9zdCl8fC9eOjoxJC8udGVzdChob3N0KXx8L15sb2NhbGhvc3QkLy50ZXN0KGhvc3QpKXJldHVybiJESVJFQ1QiO3JldHVybiJQUk9YWSBwcm94eS5leGFtcGxlLmNvbTo4MDgwIn19KTs=
[Uploading OmegaLog_1531746257107.txt…]()
[Uploading OmegaLog_1531746257107.txt…]()

**Comment by FelisCatus** [comment]
到底是 ERR_CONNECTION_CLOSED 还是 ERR_MANDATORY_PROXY_CONFIGURATION_FAILED?

如果是 ERR_CONNECTION_CLOSED，这不是 SwitchyOmega 问题，是和网络和代理环境有关，很可能需要调整下自动切换规则。

如果是 ERR_MANDATORY_PROXY_CONFIGURATION_FAILED, 看 #1474 的讨论来定位问题。
