### ISSUE TITLE
the plugin crashes often

### ISSUE THREAD

**Issue by stevengpn** [FelisCatus/SwitchyOmega#1557]
the plugin crashes often
崩溃频繁

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by celeron533** [comment]
有详细信息吗？？？

**Comment by stevengpn** [comment]
如何拿？这是我可以看到的所有信息

**Comment by FelisCatus** [comment]
建议直接把崩溃报告提交到 Chrome ，谢谢。
