### ISSUE TITLE
希望大佬可以更新一下扩展图标的内圈外圈都可以更改颜色

### ISSUE THREAD

**Issue by 22332333** [FelisCatus/SwitchyOmega#1558]
SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5702.400 QQBrowser/10.2.1893.400

**Comment by celeron533** [comment]
一直就能更改
#1220

**Comment by 22332333** [comment]
左上角色块貌似只能修改里面小圆的颜色,希望也能设置外圆的颜色

**Comment by celeron533** [comment]
外圈是切换规则，里圈是情景模式，都能换颜色

**Comment by 22332333** [comment]
求解如何修改外圈的颜色.....

**Comment by FelisCatus** [comment]
在选项页面的左侧选择您的代理情景模式，然后点击上方的色块修改颜色。

另外，表示“直接连接”的灰色无法修改，见 #115. 不过，您可以另外新建一个空的代理情景模式来代替直接连接。
