### ISSUE TITLE
SwitchyOmega 的快捷键能禁用吗?

### ISSUE THREAD

**Issue by pexcn** [FelisCatus/SwitchyOmega#1559]
![dis](https://user-images.githubusercontent.com/4590439/42933667-e7e5d632-8b77-11e8-9fdb-e00833072ad1.png)

默认是开启的，有什么办法可以禁用呢？

**Comment by celeron533** [comment]
右边叉叉点掉没用吗？

**Comment by pexcn** [comment]
@celeron533 没用，似乎没办法禁掉...

**Comment by FelisCatus** [comment]
我这边也是点叉可以清除，但实际上并没有保存，刷新以后又回来了。这看来是 Chrome 本身的问题了，建议去 Chromium 反馈。

暂时而言，如果比较碍事，请把快捷键改成非常长的、自己永远不会按的一个组合。

**Comment by pexcn** [comment]
好的，其实不碍事，只是这个功能用不到，单纯地想去掉而已 :)

**Comment by pexcn** [comment]
Redirect to: https://bugs.chromium.org/p/chromium/issues/detail?id=865873
