### ISSUE TITLE
无法访问wikipedia

### ISSUE THREAD

**Issue by zhangxiongguo** [FelisCatus/SwitchyOmega#156]
为什么我设置好了代理规则还是无法访问wikipedia？

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.65 Safari/537.36

**Comment by FelisCatus** [comment]
@zhangxiongguo 您设置了什么样的规则？可以截图或上传设置文件备份。

**Comment by FelisCatus** [comment]
如果没有任何截图或设置文件备份的话，我估计是搞不定了……也许哪位神明能猜出为什么您那边不行吧。
