### ISSUE TITLE
使用体验极差

### ISSUE THREAD

**Issue by CaoBaoWang** [FelisCatus/SwitchyOmega#1560]
输入密码帐号密码的弹出框一闪就回去了，无法登录，使用体验极差

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36

**Comment by celeron533** [comment]
http proxy 账号密码？

**Comment by CaoBaoWang** [comment]
![Uploading image.png…]()

 是弹这个框的时候，经常自动弹回去，根本来不及点登录，然后也用不了

**Comment by CaoBaoWang** [comment]
![default](https://user-images.githubusercontent.com/18046025/42978047-4ec61756-8bfd-11e8-9676-7b0eddd46ca1.png)

**Comment by CaoBaoWang** [comment]
或者根本就不弹出来

**Comment by FelisCatus** [comment]
Chrome 本身的问题，无法修复。

但是，您可以在 SwitchyOmega 里，在代理情景模式的右侧，点击锁的图标来预先填写用户名密码。填写正确的情况下，不会显示弹窗，会自动完成代理认证。（注意：即使这么设置了， Chrome 刚启动而 SwitchyOmega 尚未加载的时候还是可能会提示，直接点取消即可。此问题同样无法修复。）

**Comment by CaoBaoWang** [comment]
好的，有办法上网就行  多谢
