### ISSUE TITLE
此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by moerfutin** [FelisCatus/SwitchyOmega#1562]
删除重建，仍然这么提示。。。请求修复～

![image](https://user-images.githubusercontent.com/9960618/42995881-90ee1eb6-8c44-11e8-9f8b-aef8f525cca6.png)

**Comment by FelisCatus** [comment]
由于 Chrome 同步存储的限制，每个键下面可以存储的数据量有限。此问题没有比较直接的办法修复。

如果规则数量实在是太多，建议分开到几个不同的自动切换情景模式。

**Comment by moerfutin** [comment]
可否提供一个接口，给第三方同步平台？

Felis Catus <notifications@github.com>于2018年7月23日 周一12:54写道：

**Comment by FelisCatus** [comment]
#1381.
