### ISSUE TITLE
Mac chrome无法使用

### ISSUE THREAD

**Issue by huachenzhang** [FelisCatus/SwitchyOmega#1563]
Mac chrome无法使用

代理协议：SockS5
代理服务器：127.0.0.1
代理端口:23475

SwitchyOmega 2.5.6
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by FelisCatus** [comment]
请问是无法访问任何网页吗？显示什么错误代码？

如果显示的是 Proxy Connection Failed 之类的，请确认代理情景模式里服务器地址、端口号、协议填写正确，并且代理服务器正常运作。如有问题可以截图。

如果只是某些网页打不开，建议检查代理服务器情况、自动切换中的规则或者规则列表。

**Comment by dayfuaim** [comment]
The same problem:
Chrome Beta 68.0.3440.75
Mac OSX 10.10.5

But error is "CONNECTION TIMEOUT".

How to solve it?

**Comment by FelisCatus** [comment]
CONNECTION TIMEOUT is something caused by your network, proxy server or settings. It is not something SwitchyOmega can fix.
