### ISSUE TITLE
[recommendation] virtual profile at top

### ISSUE THREAD

**Issue by xuefer** [FelisCatus/SwitchyOmega#1564]
virtual profiles are mainly use for auto switch settings in which we don't have to changing each rule.
this means once virtual profile is used, it is accessed frequently in switchy omega menu. e.g.: switch virtual  @ slow to profile vpn1 or vpn2 etc
i don't think someone may want more virtual profile than actual profile. but i'm using more than 10 actual profiles with 2~3 virtual profile, i have to scroll down to locate virtual profiles after which is expanded, i have to scroll down again to select what target i want it to use.
then i think, why not list virtual profile at the top? for someone don't like it they don't even make virtual profile

**Comment by FelisCatus** [comment]
I'm closing this in favor of #607 which tracks customized profile ordering.

Before that is implemented, you can prefix your actual profiles with `_` (underscore) so that they won't show up in the popup menu. I think this would definitely help here.

**Comment by xuefer** [comment]
underscore help a lot but i don't think so. custom order is requested 3 years ago but never implemented, having virtual sorted at top is a lot easier to implemented using javascript Array.sort(function(a, b) { return .........} ); whoever use virtual profiles want them to be at top, at least before actual profiles, or do we have to wait for another 3 years. that's sad
