### ISSUE TITLE
Friefox访问Google会出现概率性卡住不访问网站的情况

### ISSUE THREAD

**Issue by megaslx** [FelisCatus/SwitchyOmega#1565]
表现情况是通过访问Google时firefox不提示正在连接Google，要过十几秒钟到二十多秒才会提示正在连接，并正常加载、显示页面。奇怪的是其他走omega的网站，比如youtube等等，就从来不会出现这个问题，chrome上也从来没碰到过这样的情况

**Comment by FelisCatus** [comment]
感觉不太像是 SwitchyOmega 的问题，可以试试看这些操作：

1. Google 是开启 Firefox 之后打开的第一个网站吗？如果是的话，可能需要等 SwitchyOmega 完全加载完成。可以试试看先打开其他网站再打开 Google.
2. 可以试试看打开网页 http://google.com/asdkfjasdfjlasdf （应该会直接显示404），看速度如何。
3. 打开开发者工具再打开 Google ，看各个请求的加载情况。有可能有的资源不需要代理也能访问，只是速度非常慢，可以试着添加到自动切换规则里。

**Comment by megaslx** [comment]
1、不是第一个访问的网站，这个问题并不只出现在刚打开firefox的情况下，而是随机出现每次访问Google网站的时候，即使设置所有连接都走代理，一样卡住
2、开发者工具里面看不到任何的请求，不知道firefox在做什么，但是程序又没死，开其他标签页访问其他网站，需要或者不需要代理的都一切ok

**Comment by ghcsd** [comment]
可能由于 Firefox 的 OCSP 证书状态查询服务器连接不通造成的。
尝试在 about:config 关闭它，

> security.OCSP.enabled

设置值为 0。

**Comment by FelisCatus** [comment]
根据以上反馈，我这边应该可以确认不是 SwitchyOmega 的问题了。如果需要继续分析问题，需要一位对 Firefox 网络请求实现机制比较熟悉的开发者。

另外，倒是值得试试看更新 Firefox 到最新版，甚至换 Beta / Nightly 版本。
