### ISSUE TITLE
如何为 自动切换模式 选择系统代理

### ISSUE THREAD

**Issue by 22332333** [FelisCatus/SwitchyOmega#1566]
求大佬告知...好像只能选择直连和自定义的情景模式吗

**Comment by FelisCatus** [comment]
见 [FAQ](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E5%9C%A8%E8%87%AA%E5%8A%A8%E5%88%87%E6%8D%A2%E4%B8%AD%E4%B8%8D%E8%83%BD%E9%80%89%E6%8B%A9%E7%B3%BB%E7%BB%9F%E4%BB%A3%E7%90%86)
