### ISSUE TITLE
能否实现多级代理串联

### ISSUE THREAD

**Issue by zky999** [FelisCatus/SwitchyOmega#1567]
我想让SwitchyOmega管理我的2个代理，一个是Fiddler（必须让网络流量经过127.0.0.1:8888），用于web debbuging，同时我还想让同一个网络session又经过我设置的另外一个“科学上网”代理服务器，因为我调试的是被墙的网站。是否能实现这样的功能？

**Comment by celeron533** [comment]
不能。你把流量交给第一个代理后，后续的操作由这个代理决定

**Comment by FelisCatus** [comment]
SwitchyOmega 是代理设置工具，具体代理实现由浏览器实现。
