### ISSUE TITLE
希望在弹出菜单中增加列出当前标签的所有请求域名

### ISSUE THREAD

**Issue by ghcsd** [FelisCatus/SwitchyOmega#1568]
一个页面 “主域名” 可能不需要添加代理，
但子资源域名可能需要，
增加列表显示能方便地增删规则条件，
也能方便地知道该页面哪些资源域名匹配了代理规则。

参考 `uBlock Origin` 扩展的设计，
具体建议如下图所示。
![screenshots](https://user-images.githubusercontent.com/32384764/43142283-a7d43ab8-8f8a-11e8-8f16-ce88d29465cc.png)

希望作者能考虑一下。

补充修改：
关于上图“删除条件”按钮，
由于域名有可能被通配符、正则、甚至是订阅列表规则所匹配，
应该改正为 “编辑条件” 按钮，
点击该按钮后，可以像 “添加条件” 按钮一样，
弹出另一个 “弹出菜单”，
并显示匹配该条域名地规则（可能有多条），
以便删除、备注或编辑使用某一个情景模式该条件规则。

**Comment by FelisCatus** [comment]
感谢建议，设计图已经收到。

关于跟踪完整域名的需求见 #664. 我还是希望弹出菜单能只照顾最常见的使用场景，更复杂的请求分析可以使用开发者工具来进行，规则的自定义也可以通过添加规则按钮或者编辑选项的方式来实现。

弹出菜单功能做得太多只会越来越卡，这个是之前用户反馈很多的问题，并且做过很多次优化。为了达到更精确地跟踪这种不是特别常用的用例而做这么多设计上和代码上的调整，然后让弹出菜单变得很卡，我目前觉得得不偿失。

#1242 跟踪了“修改条件”的需求。注意这个需求本身是有可能做的，只是目前还在考虑中。

由于两部分都已经分别有 Issue 了，而且即使做也会分别完成，所以这个就关掉了。请关注 #664 #1242.
