### ISSUE TITLE
Does not auto start with selected mode "auto switch"

### ISSUE THREAD

**Issue by Taomyn** [FelisCatus/SwitchyOmega#1569]
I have set the default start mode to "auto switch", but on first start up of Chrome (v68), it always starts as "system". I have Chrome set to remember my last session, but I always run with "auto switch".

**Comment by FelisCatus** [comment]
There could be an error when applying "auto switch" so SwitchyOmega falls back to system.

Please right-click on the SwitchyOmega icon and then "Save error log" to get a log file that can be attached here.

**Comment by FelisCatus** [comment]
This could be #1593, which is now fixed.
