### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by xwj1003** [FelisCatus/SwitchyOmega#157]
可以设置一个代理链, 里面有代理1,代理2,代理3...代理n, 直接连接
系统会判断代理1能否使用,如果连接连接不上,就用代理2, 代理2连不上就用代理n, 最后就是不用代理直接连接.
以后就可以缓存读取

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by ynyounuo** [comment]
类似 #6  #73 
这种自动检测自动记录规则说起来容易做起来难，而且很容易有各种各样的问题

**Comment by xwj1003** [comment]
现在很多代理不稳定,可能有时候能连上有时候连不上.
我可能会设置N个代理, 组成一个代理链, 系统判断一下代理1是否可用, 如果不可用就自动换一个.
我的要求是不需要自动记录规则.
这样做是为了减少来回换代理的麻烦.

**Comment by rgw5267** [comment]
不知道cow是否满足你的要求。https://github.com/cyfdecyf/cow

**Comment by xwj1003** [comment]
楼上的介绍看了一下,很方便, 都不用自己设置哪些网站需要代理. 反正连不上的都通过代理走.

**Comment by chujiu-xiong** [comment]
可以用虚情景模式手动切换，虚情景模式在下拉菜单有个下拉列表，里面就是你添加的服务器和直接连接，只要在auto switch里将代理设为这个虚情景模式就可以在下拉菜单一键切换当前可用的代理服务器。

**Comment by FelisCatus** [comment]
先关闭这个了。如果真的决定要做的话可能是按 #152 做。
