### ISSUE TITLE
请作者进来看看。

### ISSUE THREAD

**Issue by tea1111980** [FelisCatus/SwitchyOmega#1570]
![image](https://user-images.githubusercontent.com/16295097/43310500-4d55d33a-91ba-11e8-87d8-0ed8afeb667b.png)

能不能把这里面的下拉选项类，改成平铺的模式，这样点一下就可以临时添加走代理还是走直连。
你如果弄成下拉选项形式的话，这样点起来不方便，有时还会点错。

望请修改，谢谢！

**Comment by FelisCatus** [comment]
经过考虑，决定不支持此功能。抱歉。

如果怕点错，可以使用快捷键 `Alt+Shift+O` 打开弹出菜单然后立即按 `T` 即可展开此项目。

**Comment by tea1111980** [comment]
好吧
