### ISSUE TITLE
Memory consuming errors

### ISSUE THREAD

**Issue by dklunarian** [FelisCatus/SwitchyOmega#1571]
> Error: Attempt to postMessage on disconnected port omega_target_chromium_extension.min.js:4735:70
> 	postMessage resource://gre/modules/ExtensionChild.jsm:220:13
> 	postMessage resource://gre/modules/ExtensionChild.jsm:179:9
> 	postMessage self-hosted:983:17
> 	[26]</ChromeOptions</ChromeOptions.prototype.setMonitorWebRequests/</< moz-extension://b01cd98e-594c-4aff-ad36-0b50efbdb345/js/omega_target_chromium_extension.min.js:4735:70
> 	[38]</WebRequestMonitor</WebRequestMonitor.prototype.setTabRequestInfo moz-extension://b01cd98e-594c-4aff-ad36-0b50efbdb345/js/omega_target_chromium_extension.min.js:6815:22
> 	<anonymous> self-hosted:985:17
> 	[38]</WebRequestMonitor</WebRequestMonitor.prototype._tick moz-extension://b01cd98e-594c-4aff-ad36-0b50efbdb345/js/omega_target_chromium_extension.min.js:6574:13
> 	<anonymous> self-hosted:981:17
> 
> Unchecked lastError value: Error: Invalid tab ID: 44 omega_target_chromium_extension.min.js:4720
> 	[26]</ChromeOptions</ChromeOptions.prototype.setMonitorWebRequests/</< moz-extension://b01cd98e-594c-4aff-ad36-0b50efbdb345/js/omega_target_chromium_extension.min.js:4720:13

The above errors infinitely pop and will eventually consume all memory, which lead to crash.

Version: 2.5.17

**Comment by FelisCatus** [comment]
Thanks for the reports. I'll look into the error logs.

One thing -- is it certain that error logs in WebExtensions keep consuming memory? Any docs that we can look into?

**Comment by FelisCatus** [comment]
This particular error should be cleaned up as of v2.5.19. Please let me know if you see other errors.
