### ISSUE TITLE
PAC-Profile script gives no 'alert'

### ISSUE THREAD

**Issue by lllaffer** [FelisCatus/SwitchyOmega#1573]
My PAC-Profile/Script
	
	function FindProxyForURL(url, host) {
	      alert('url: \'' + url + '\', host: \'' + host + '\'');
	      return "PROXY localhost:8080";
	}
	
is shurely working; - when I change the port, the browser cant't connect anymore.

Acc. to https://github.com/FelisCatus/SwitchyOmega/issues/845
this should work, but don't receive any 'alert' ... ???

Any idea, what I am missing !?

I'm working on
	Win 7 32
	Chromium 67.0.3396.99	

thnx for your appreciated work on SwitchyOmega.

**Comment by lllaffer** [comment]
I was missing:

 https://serverfault.com/questions/738565/how-to-debug-pac-file-in-chrome-without-alert-function

thnx to the author

**Comment by luke-zhang123** [comment]
SwitchyOmega debug pac proxy
https://serverfault.com/a/1118197/995325
