### ISSUE TITLE
为什么使用shadowsocks的时候，Chrome使用SwitchyOmega时，浏览器不能登录翻墙

### ISSUE THREAD

**Issue by Apathy94** [FelisCatus/SwitchyOmega#1574]
如题

**Comment by FelisCatus** [comment]
Shadowsocks 问题请到相应论坛讨论。 SwitchyOmega 是代理设置软件，不是翻墙软件。

**Comment by Apathy94** [comment]
@FelisCatus 我问的就是SwitchyOmega的设置问题，而不是代理软件的问题。如果我的问题给你造成麻烦，真的抱歉！

**Comment by FelisCatus** [comment]
这里仅供讨论 SwitchyOmega 项目开发相关的问题，不是论坛。与具体代理软件、网络环境相关的问题，不在这里的讨论范围内。代理端口号、服务器等如何设置，请参考代理软件相关文档。如果还有问题建议去其他社区提问。
