### ISSUE TITLE
您的浏览器不支持 socks5 代理认证！如有问题请联系您的浏览器支持，请勿反馈此问题给 SwitchyOmega.

### ISSUE THREAD

**Issue by zhouyanjie666** [FelisCatus/SwitchyOmega#1575]
您的浏览器不支持 socks5 代理认证！如有问题请联系您的浏览器支持，请勿反馈此问题给 SwitchyOmega.

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by celeron533** [comment]
“请勿反馈此问题给 SwitchyOmega”

**Comment by wangzhenjjcn** [comment]
@gzdzss 
![微信图片_20220217062003](https://user-images.githubusercontent.com/1842578/154367077-56818dfb-1e47-4fca-99e9-13501c8128a8.png)
