### ISSUE TITLE
firefox直接连接依然会使用系统代理

### ISSUE THREAD

**Issue by goodbee** [FelisCatus/SwitchyOmega#1576]
firefox中，选择直接连接，还是会走系统代理啊
chrome里面，就会绕过系统代理，行为不太一致啊

SwitchyOmega 2.5.17
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Comment by celeron533** [comment]
因为chrome和firefox的实现机制不一样啊

**Comment by FelisCatus** [comment]
Firefox 已知问题，建议去 Bugzilla 反馈。 SwitchyOmega 无法修复。
