### ISSUE TITLE
希望增加通过复制原有Profile创建新Profile选项

### ISSUE THREAD

**Issue by Daymond** [FelisCatus/SwitchyOmega#1577]
部分提供商会提供好几个服务器供选择，一个一个手动添加实在是太低效了……
希望开发者能够注意到，谢谢！

SwitchyOmega 2.5.17
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by FelisCatus** [comment]
见 #832. 另外见 https://github.com/FelisCatus/SwitchyOmega/issues/235#issuecomment-84976970 的方式，可以批量导入。
