### ISSUE TITLE
为何*.*amazon.com就无效呢?

### ISSUE THREAD

**Issue by xwj1003** [FelisCatus/SwitchyOmega#158]
`*.amazon.com` 有效, 为何 `*.*amazon.com` 就无效呢?

`*.*amazon.com` 是为了匹配类似这样的域名 `*.images-amazon.com`

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by xwj1003** [comment]
星号被你们过滤了.应该是
星号.amazon.com 有效, 为何 星号.星号amazon.com 就无效呢?

**Comment by ynyounuo** [comment]
走网址通配符（URL Wildcard）然后用这个规则：
    `*://*.*amazon.com`

**Comment by FelisCatus** [comment]
已经确认！感谢您提供这么详细的错误报告。这是域名规则处理的问题，等下我加几个测试再修复一下。

**Comment by FelisCatus** [comment]
代码里已经修复了，不过离下次版本发布还有一点时间。暂时推荐用 `*amazon.com` 这样的规则代替（我感觉差不多），等下次发布后应该可以正常使用了。

**Comment by FelisCatus** [comment]
v2.1.12 已经修复。

**Comment by xwj1003** [comment]
测试通过, :+1:
