### ISSUE TITLE
Scrapoxy integration

### ISSUE THREAD

**Issue by fabienvauchelles** [FelisCatus/SwitchyOmega#1580]
Hello,

Should it be a good idea to integrate [Scrapoxy.io](http://scrapoxy.io) into the plugin ?

We could start many proxies from you plugin.

Best regards,
Fabien

**Comment by celeron533** [comment]
Or fork it then do more developments? (remember to keep GPL license)
😋

**Comment by FelisCatus** [comment]
At this moment, we are not interested in integrating any proxy provider into the project.

However, please feel free to recommend SwitchyOmega as part of the solution, with clear indication that SwitchyOmega is an independent project and cannot provide support for any proxy service. Also, feel free to distribute configuration backup files ready for importing in SwitchyOmega.

You may also create a fork of SwitchyOmega, under GPL. See LICENSE.
