### ISSUE TITLE
Host wildcard match doesn't work for matches without a period

### ISSUE THREAD

**Issue by prashantv** [FelisCatus/SwitchyOmega#1582]
If I use a host wildcard like `*.prod` to use a proxy, things work fine. However, if I add a similar wildcard for `*-prod`. the matcher doesn't seem to get used.

I've set up the following rules:
![image](https://user-images.githubusercontent.com/140159/43730738-2deeaa54-9961-11e8-83a9-416d4f71c7dd.png)

Here are logs from `chrome://net-internals` for a name ending in `.prod` vs a name ending with `-prod`:

`name.prod`:
```
t=41757 [st= 0] +HTTP_STREAM_JOB_CONTROLLER  [dt=42]
                 --> is_preconnect = false
                 --> url = "http://name.prod/"
t=41757 [st= 0]    HTTP_STREAM_JOB_CONTROLLER_BOUND
                   --> source_dependency = 41250 (URL_REQUEST)
t=41757 [st= 0]   +PROXY_RESOLUTION_SERVICE  [dt=1]
t=41758 [st= 1]      PROXY_RESOLUTION_SERVICE_RESOLVED_PROXY_LIST
                     --> pac_string = "SOCKS5 192.168.87.3:8127;SOCKS 192.168.87.3:8127"
t=41758 [st= 1]   -PROXY_RESOLUTION_SERVICE
t=41758 [st= 1]    HTTP_STREAM_JOB_CONTROLLER_PROXY_SERVER_RESOLVED
                   --> proxy_server = "SOCKS5 192.168.87.3:8127"
```

We see that my SOCKS proxy was used.

If I use `name-prod`, no proxy server is used:
```
t=4215 [st=   0] +HTTP_STREAM_JOB_CONTROLLER  [dt=2256]
                  --> is_preconnect = false
                  --> url = "http://name-prod/"
t=4215 [st=   0]    HTTP_STREAM_JOB_CONTROLLER_BOUND
                    --> source_dependency = 41757 (URL_REQUEST)
t=4215 [st=   0]   +PROXY_RESOLUTION_SERVICE  [dt=1]
t=4216 [st=   1]      PROXY_RESOLUTION_SERVICE_RESOLVED_PROXY_LIST
                      --> pac_string = "DIRECT"
t=4216 [st=   1]   -PROXY_RESOLUTION_SERVICE
t=4216 [st=   1]    HTTP_STREAM_JOB_CONTROLLER_PROXY_SERVER_RESOLVED
                    --> proxy_server = "DIRECT"
```

**Comment by FelisCatus** [comment]
First, make sure that the "profile" column is set to your proxy profile (NOT direct) for both rules.
If that still doesn't work, please click on the "Export PAC" button on the Switch Profile and upload it here. (Feel free to change the domain names before you export to protect your privacy. But please keep the syntax & form of the wildcard.)

**Comment by FelisCatus** [comment]
Actually -- it occurred to me just now -- do you by any chance have `<local>` in the bypass list of your Proxy Profile (NOT Switch Profile)? That will cause all domain names *without a dot* to be bypassed.

**Comment by FelisCatus** [comment]
Closing due to no response. Let me know when you've checked the proxy profile.
