### ISSUE TITLE
Performance Issue

### ISSUE THREAD

**Issue by nestlelatte** [FelisCatus/SwitchyOmega#1583]
After restored from gfwlist.bak, I manually added about 20 domain rules in auto switch profile.
It will cause 10s initial connection waste caught in development tools>network>timing.
It only appeal at the first time open the website which is on custom rules after open browser.
I tried disable all other extensions, still goes.

Using SwitchyOmega 2.5.15 and CentBrowser 3.5.3.50 based on Chromium 67.0.3396.99
![image](https://user-images.githubusercontent.com/36766521/43749952-bd416170-9a28-11e8-8fac-568758d3eca6.png)

**Comment by nestlelatte** [comment]
btw, 2.5.15 it not the only version have this problem. I think it happens for a long time.

**Comment by FelisCatus** [comment]
Chrome needs some time to compile and run the PAC script before the first connection. This is normal but you may want to trim down the rules a little bit.
