### ISSUE TITLE
代理设置问题

### ISSUE THREAD

**Issue by xingyanlxy** [FelisCatus/SwitchyOmega#1584]
经常自动更改设置至默认，导致无法翻墙

SwitchyOmega 2.5.15
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

**Comment by 4LangX** [comment]
SwitchyOmega version : 2.5.18
Google Chrome : Version 68.0.3440.106
