### ISSUE TITLE
https 只能用域名方式访问代理？

### ISSUE THREAD

**Issue by FormosaZh** [FelisCatus/SwitchyOmega#1586]
不是很了解代理软件的内部运作，但是发现很多https代理只能以域名方式来使用，如果将域名换成ip方式则会访问出错，比如某https代理abc.com解析后的ip是123.123.123.123：

**https abc.com:443         ---                               依此设置成功代理
https 123.123.123.123:443            ---               依此设置代理错误**

另外很多下载软件不支持https域名方式的设置，造成无法使用这种代理，一直很疑惑，搜索了相关关键词，但依旧没有搞明白，希望大神能帮助解答一下这是何故？

**Comment by celeron533** [comment]
PAC的工作原理就是这样的，不带解析过程的，只接受请求的原始地址

**Comment by flyingwhitewhale** [comment]
HTTPS其实就是HTTP OVER TLS，为了实现TLS，就必须涉及证书的交换及数据的加密，所以必然只能用域名格式，同时还必须为域名签发绑定证书才能正常工作。

**Comment by FormosaZh** [comment]
@flyingwhitewhale 非常感谢！
看来要去学习一下https了，那IDM等下载软件不能使用这种域名格式的问题，我是通过把https代理加进在线pac文件解决的，因为不幸得是发现idm不支持本地文件方式file://*.pac，虽然最终可用了，但开一堆软件，繁琐的很，可有什么更好方法？
