### ISSUE TITLE
pac file "profile download issue"

### ISSUE THREAD

**Issue by haybeseret** [FelisCatus/SwitchyOmega#159]
I am working with pac file , lets say for the demonstration that it is configured to  "http://192.168.90.1/proxy.pac"

it seem that either i have pressed the download profile or it's downloaded it automatically.

I have ran into a situation where i was at the airport and got blocked by the airport NAC Protal, so the output of what i have seen in the "downloaded" profile was "access denied".
Now when I have  returned to the office, working with the same pac profile, i was not able to surf.
When i looked at it  i saw that if i press "download profile" it did not worked (due to the current "profile" that was there with "access denied")  and also could not surf from that same reason.

I have to configure "direct connection" then download the profile, and only then return to my pac profile.

I think that the program should not use any proxy in order to the pac file (i,e Go direct when a pac profile is configured) because the pac file usually available with out any proxy configured.

SwitchyOmega 2.2.10
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
```
[2] Unhandled rejection:
 TypeError: Cannot read property 'replace' of null
    at Object.module.exports.exports.requestFromUrl (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_pac.min.js:12496:27)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:85:37
From previous event:
    at new Promise (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:1972:37)
    at CustomBindingsObject.getAsync (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3117:12)
    at ChromeStorage.get (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:4144:25)
    at ChromeOptions.Options (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target.min.js:10321:34)
    at new ChromeOptions (chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/omega_target_chromium_extension.min.js:3403:48)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:179:13
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/js/background.js:366:4
```

**Comment by FelisCatus** [comment]
PAC downloads are also network requests, so they are passed through the configured proxy by the browser. I don't think there's another way to bypass proxies for them, expect modifying the PAC script itself and return direct for the URL of itself.

The easiest solution would be to clear the PAC URL field and just use the downloaded script in the textarea. However this solution won't works if the script is frequently updated and you need to download the updates.

A more complex solution would be setting the default profile of a switch profile to the PAC profile. Then you can add any rules you want in the switch profile, effectively creating a combination of the two profiles. This enables you to add a condition like `http://192.168.90.1/proxy.pac` and use direct profile for it. Also, such configuration allows "overriding" the PAC script for certain websites as a bonus.

P.S. I think I should also consider some sniffing on the downloaded PAC scripts, and filter out things that are obviously not PAC scripts, such as webpages, images, and so on.

**Comment by haybeseret** [comment]
Thing is that on regular I.E pac is not being downloaded via it's own
configuration, it's a paradox.
It was working well in the old version of the extension.
I cannot edit the pac content, for some reasone.

**Comment by FelisCatus** [comment]
The PAC script content can only be edited after you clear the "PAC URL" field.

**Comment by FelisCatus** [comment]
An update is coming soon that includes a new sanity check of the downloaded content. Hopefully it won't attempt to run the airport portal code as PAC scripts again.

**Comment by FelisCatus** [comment]
v2.3.20 is released with the content checking implemented.
Please let me know whether it works for you, @haybeseret
