### ISSUE TITLE
firefox 62.0b16 涉及到远程DNS的问题

### ISSUE THREAD

**Issue by cdtsuipo** [FelisCatus/SwitchyOmega#1590]
### SwitchyOmega version / SwitchyOmega 版本

2.5.18

### Browser version & OS version / 浏览器名称、版本及操作系统版本
windowns10 ,firefox 62.0b16 (64-bit)

### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.firefox 更新到了62.0b16 
2.貌似 Proxy DNS when using SOCKS v5 功能在使用switchomega时失效，之前版本只要是走switchomega的域名DNS都是走的代理,不管是否勾选此选项，现在只在firefox内手动设置代理，并勾选此选项，DNS才会走代理。
3.在V2RAY客户端可以看出，所有网站都在本地解析后才提交代理的。V2RAY没更新过配置，所以排除V2RAY的问题。

#### Expected behavior / 期望发生的情况

规则生效后，所有走代理的域名都开启远程DNS

**Comment by cdtsuipo** [comment]
经查，家里电脑同样的系统配置、同版本的FIREFOX，2.5.17版本的switchomega无此问题

**Comment by FelisCatus** [comment]
选择的是 SOCKS4 还是 SOCKS5? 请问降级 Firefox 但是保持 2.5.18 是否也有此问题？

**Comment by cdtsuipo** [comment]
先择的SOCKS5，降级firefox到61无效，降级到2.5.16就恢复了

**Comment by FelisCatus** [comment]
这就很诡异了，之前的 bd06fac3b3176e27f6418723570f6a55a55a9f51 改的是去掉了 SOCKS4 的远程 DNS (因为大部分 SOCKS4 代理不支持 SOCKS4a)，并没有影响 SOCKS5 才对。

能提供一下设置备份文件吗？（选项>导入导出>备份设置）我这里试一下看能否重现。

**Comment by cdtsuipo** [comment]
可能和firefox也有关系，现在SwitchyOmega已经升到了2.5.19了，配合正式版的firefox 61.0.2 ，没有这个问题了，我不知道配置文件还有用不..至于为什么之前的退回到正式版firefox无效，可能和不是清洁安装有关。
[OmegaOptions(1).zip](https://github.com/FelisCatus/SwitchyOmega/files/2312936/OmegaOptions.1.zip)

**Comment by cdtsuipo** [comment]
这就很奇怪了，我印象中没有刻意更改过...查看了一下设置，目前的2.5.19是设定是用的socks5。看来问题应该就是这个选项了。那这个问题就解决了。
