### ISSUE TITLE
Profile切换不生效

### ISSUE THREAD

**Issue by cockcrow** [FelisCatus/SwitchyOmega#1591]
### SwitchyOmega version / SwitchyOmega 版本

Version 2.5.18

### Browser version & OS version / 浏览器名称、版本及操作系统版本

Google Chrome Version 68.0.3440.106 (Official Build) (64-bit)

macOS High Sierra 10.13.4 (17E202)

### Problem description / 问题描述

代理切换无效

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. 访问 http://httpbin.org/ip DIRECT
2. 切换 Profile 使用代理

#### Expected behavior / 期望发生的情况

返回 IP 变化

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

实际返回 IP 相同

**在BASH确认了代理可工作，Firefox FoxyProxy 插件也可以工作**

**Comment by cockcrow** [comment]
另外，原先在切换Profile时页面会自动刷新，现在页面没有自动刷新

**Comment by Gabirel** [comment]
拥有同样的问题，望修复

**Comment by liupeng0518** [comment]
相同问题

**Comment by Soulcrzkc** [comment]
第一次切换有效但之后不管怎么切都回不去了。。。切成系统代理才能回去但之后不管怎样都无效

**Comment by notwhy** [comment]
从昨天下午开始mac开始遇到相同问题，使用了google同步，window无异常，卸载google  卸载SwitchyOmega 重启mac均无用，switchyomega点击切换页面无刷新，无法正常使用。

**Comment by xiaomodao** [comment]
= = 同样问题

**Comment by cockcrow** [comment]
临时手动降版本 Version 2.5.15

**Comment by xiaomodao** [comment]
手动降版本 Version 2.5.15
已解决

**Comment by notwhy** [comment]
手动降版本 Version 2.5.15
已解决

**Comment by 4LangX** [comment]
@notwhy 2.5.18的备份导出功能有问题，请问降级操作是直接暴力卸载2.5.18，然后直接安装的2.5.15么？

**Comment by notwhy** [comment]
@4LangX 是的 移除最新版 然后GitHub下载2.5.15.crx 手动安装

**Comment by FelisCatus** [comment]
已确认是版本更新问题。排查中。

**Comment by FelisCatus** [comment]
#1593.
