### ISSUE TITLE
Startup Profile doesn't work under Chrome 68

### ISSUE THREAD

**Issue by Gabirel** [FelisCatus/SwitchyOmega#1592]
### SwitchyOmega version / SwitchyOmega 版本
`2.5.18`

### Browser version & OS version / 浏览器名称、版本及操作系统版本
`Google Chrome` : `Version 68.0.3440.106 (Official Build) (64-bit)`
`OS` : `Arch Linux`

### Problem description / 问题描述
Startup profile doesn't work. `System proxy` is currently the default option. It will be the same no matter what I do.

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤
Change the startup profile.

#### Expected behavior / 期望发生的情况
Expecting my favorite to be set as the default.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
`System proxy` is the default.

**Comment by zzqxztc** [comment]
Hi, I think 2.5.18 has bugs.
You may try downgrading to an older version 2.5.15..

**Comment by FelisCatus** [comment]
#1593
