### ISSUE TITLE
导出功能失效

### ISSUE THREAD

**Issue by cskeleton** [FelisCatus/SwitchyOmega#1594]
发布规则列表、导出情景模式、生成备份文件，这些功能都失效了。

angular.min.js:127 ReferenceError: saveAs is not defined

SwitchyOmega 2.5.18
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by nemozqqz** [comment]
同样无法导出，Failed to load lib/FileSaver/FileSaver.min.js

**Comment by oldfish96** [comment]
+1

**Comment by shenthought** [comment]
+1

**Comment by Jack-ban** [comment]
+1

**Comment by 0x24bin** [comment]
+1

**Comment by myGod0rz** [comment]
18版本尽是bug，PAC，自动切换也都挂了，现在退回15版正常，chrome[68.0.3440.106 (Official Build) (64-bit)]

**Comment by FelisCatus** [comment]
Fixed in 961cdadc.

**Comment by FelisCatus** [comment]
v2.5.19 已经修复。
