### ISSUE TITLE
从2.5.9更新到2.5.18后自动切换模式不能使用

### ISSUE THREAD

**Issue by q4263186** [FelisCatus/SwitchyOmega#1595]
如题，更新为2.5.18后直接用代理服务器模式没问题，但更换为自动切换
模式后效果仍停留在上个代理服务器模式，退回2.5.9后问题没有了。

SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3521.2 Safari/537.36

**Comment by zhuoqi-chen** [comment]
I have the same problem!

**Comment by hot36952** [comment]
我这边的情况是，自动切换按照已有规则切换没有问题，但遇到手动切换临时规则时，则无法打开网站，切换到相应模式也无法打开，需要切换到相应模式并关闭chrome再重新打开才能生效。

**Comment by myGod0rz** [comment]
一样的问题，切换profile不起作用，从市场装的，都是自动更新，刚试了下16版本也不行，退到15版本目前正常，还以为最近升了chrome【68.0.3440.106 (Official Build) (64-bit)】的锅。
老话说，没毛病，别虾球升级。

**Comment by FelisCatus** [comment]
#1593
