### ISSUE TITLE
无法导出备份

### ISSUE THREAD

**Issue by PalmerChia** [FelisCatus/SwitchyOmega#1598]
点击生成备份文件，发布规则列表，导出pac，这些按钮点击没有反应，可以导入

SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by myGod0rz** [comment]
+1

**Comment by xmoer** [comment]
确实是缺少了文件 FileSaver.min.js

**Comment by FelisCatus** [comment]
见 #1594.
