### ISSUE TITLE
自动切换模式，chrome报错

### ISSUE THREAD

**Issue by zhenghongzhi** [FelisCatus/SwitchyOmega#160]
version:2.2.11
chrome:39.0.2171.71
错误代码：ERR_MANDATORY_PROXY_CONFIGURATION_FAILED
直接连接或GoAgent模式都没问题

**Comment by aekt5716** [comment]
我这边也是

**Comment by zhenghongzhi** [comment]
@aekt5716 我导出了一份配置，然后重新导入以后好了，你试试

**Comment by cicku** [comment]
Sorry dude I introduced a wrong rule to the gfwlist.

**Comment by FelisCatus** [comment]
似乎是生成PAC挂了，请在设置的自动切换情景模式下，点击导出PAC按钮，并将结果上传到这里。

**Comment by FelisCatus** [comment]
亲，你们都这样把我骗来修 bug，连一份 PAC 导出文件都不给……

你们这样让我很难办的有没有……

**Comment by duchengyao** [comment]
出现了相同的问题
最后发现是我的PAC文件不完整>_<
