### ISSUE TITLE
点击工具栏的图标需要点击两次才能显示菜单（火狐浏览器62.0b17 (64 位）

### ISSUE THREAD

**Issue by wuzhidexiaoming** [FelisCatus/SwitchyOmega#1600]
SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by FelisCatus** [comment]
第一次点击的时候显示什么？有错误信息吗？

**Comment by wuzhidexiaoming** [comment]
@FelisCatus 不好意思啊，这么久才回。😂当时的情况是，点了一下，弹出方框（大概有完整菜单方框的一半大小）但是不显示具体设置内容，点击第二次才正常显示。不过，现在已经没问题，完全能正常使用。
