### ISSUE TITLE
v2.5.18 has a bug

### ISSUE THREAD

**Issue by shentr** [FelisCatus/SwitchyOmega#1602]
![bug](https://user-images.githubusercontent.com/10665938/44307437-20e46280-a3d5-11e8-8b35-5af5519057cf.jpeg)
![bug](https://user-images.githubusercontent.com/10665938/44307442-55581e80-a3d5-11e8-9112-8d540069bcb4.jpeg)

**Comment by xmoer** [comment]
And missing files: FileSaver.min.js

**Comment by FelisCatus** [comment]
#1593
