### ISSUE TITLE
用了一段时间就无效了

### ISSUE THREAD

**Issue by 1079870326** [FelisCatus/SwitchyOmega#1604]
切换代理无效，必须卸载重新设置，才能生效。

SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5702.400 QQBrowser/10.2.1893.400

**Comment by FelisCatus** [comment]
#1593
