### ISSUE TITLE
PAC 网址错误的时候，CPU会持续100%

### ISSUE THREAD

**Issue by cloverzrg** [FelisCatus/SwitchyOmega#1605]
情景：
我有两台设备，
一台是win10，pac地址是http://127.0.0.1:1080/pac?t=20180818013639182
一台是macos，pac地址是http://127.0.0.1:1089/proxy.pac

在使用win10的时候，当更新pac的时候，会一直处于解析代理的状态，而且也无法上网，cpu持续100%

SwitchyOmega 2.5.18
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by FelisCatus** [comment]
访问错误的 PAC 网址，会下载到什么？也许那个脚本比较长，或者没法正常编译？

**Comment by FelisCatus** [comment]
如果什么都下载不到的话， Chrome 可能会尝试反复下载或者用其他方式来获取 PAC 内容，此问题不在 SwitchyOmega 的范围内。建议去 Chromium 反馈问题。

**Comment by cloverzrg** [comment]
重现：
新建一个pac模式，地址填一个错的地址；新建一个auto-switch模式，默认情景模式选择刚才新建的pac模式；然后使用该模式，cpu就会持续100%
