### ISSUE TITLE
[Feature Request]部分设置的可选同步

### ISSUE THREAD

**Issue by zodiacg** [FelisCatus/SwitchyOmega#1606]
我同时在多地、多机使用SwitchyOmega，由于网络环境不同我设置了多个虚情景模式来维持规则的一致性。

但是目前SwitchyOmega的设置同步是连“当前选择的情景模式”和“虚情景模式对应的实际代理模式”这些设置一同同步的，使得在往返家中和工作场所时需要手动进行调整切换。以及在工作场所中由于台式机和笔记本的网络环境略有不同，转个身都需要动手改一下设置

希望能够强化设置同步功能，有选择性的同步设置来简化操作。

SwitchyOmega 2.5.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by FelisCatus** [comment]
见之前的讨论。 https://github.com/FelisCatus/SwitchyOmega/issues/695#issuecomment-175708170
