### ISSUE TITLE
错误提示怎么消失了？

### ISSUE THREAD

**Issue by FormosaZh** [FelisCatus/SwitchyOmega#1607]
版本 2.5.15时会用问号图标提示“注意:其它代理正在控制当前代理设置”，为啥这版给取消了？对于喜欢在各种不同代理间切换其实很有帮助作用，谢谢！！！

SwitchyOmega 2.5.19
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.42 Safari/537.36

**Comment by FelisCatus** [comment]
请先看一下各个扩展的安装情况，确认另一个控制代理设置的扩展已经安装并启用，并且 SwitchyOmega 必须在其之后安装。（不确定的情况下，请重装 SwitchyOmega 以获得优先级。）

注意 SwitchyOmega 选项页面的“通用”设置中，必须勾选“冲突”下方的复选框“在弹出菜单中显示菜单项，以导入其他应用提供的代理设置。”

然后， SwitchyOmega 必须处在“系统代理”情景模式下（不能是直接连接、自动切换或代理情景模式等。）此时，在另一个扩展那边选择应用代理设置。此时 SwitchyOmega 应该就会有问号提示。

如果没有显示的话，请点开菜单看下。如果还是没有，请打开 `chrome://net-internals/#proxy` 页面，确认设置是否确实是由另一个扩展所设置的，并把内容复制到这里。然后请右键点击图标，选择“导出错误日志”，然后上传到这里。

**Comment by WBinyv** [comment]
现实的是这些：
PAC script: data:application/x-ns-proxy-autoconfig;base64,ZnVuY3Rpb24gRmluZFByb3h5Rm9yVVJMKHVybCwgaG9zdCkgewp2YXIgRD0iRElSRUNUOyIsIFAgPSAiSFRUUFMgd3d3Lm5haWR1by53aW46NDQzMDsiOwogICAgdmFyIEggPSB7CiAgICAgICAgImdvb2dsZWFwaXMuY29tIjoxLAogICAgICAgICJnb29nbGVjb2RlLmNvbSI6MSwKICAgICAgICAiZ29vZ2xldXNlcmNvbnRlbnQuY29tIjoxLAogICAgICAgICJnZ3BodC5jb20iOjEsCiAgICAgICAgImdzdGF0aWMuY29tIjoxLAogICAgICAgICJnbWFpbC5jb20iOjEsCiAgICAgICAgImdvb2dsZWdyb3Vwcy5jb20iOjEsCiAgICAgICAgImdvby5nbCI6MSwKICAgICAgICAiZ29vZ2xlcmF0aW5ncy5jb20iOjEsCiAgICAgICAgInRlc3QtZ2dmd3pzLXByb3h5LmNvbSI6MSwKICAgICAgICAidC5jbyI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5oayI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS50dyI6MSwKICAgICAgICAiZ29vZ2xlLmNvLmpwIiA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmtyIiA6MSwKICAgICAgICAiZ29vZ2xlLmNvLnRoIiA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS52biIgOjEsCiAgICAgICAgImdvb2dsZS5jb20uc2ciOjEsCiAgICAgICAgImdvb2dsZS5jb20ubXkiOjEsCiAgICAgICAgImdvb2dsZS5jb20ucnUiOjEsCiAgICAgICAgImdvb2dsZS5hZSIgICAgOjEsCiAgICAgICAgImdvb2dsZS5jb20uc2EiOjEsCiAgICAgICAgImdvb2dsZS5jby5pbiIgOjEsCiAgICAgICAgImdvb2dsZS5jb20ubnAiOjEsCiAgICAgICAgImdvb2dsZS5kZSIgICAgOjEsCiAgICAgICAgImdvb2dsZS5jb20ua3ciICAgIDoxLAogICAgICAgICJnb29nbGUuY29tLmNvIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmZyIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLnVrIiA6MSwKICAgICAgICAiZ29vZ2xlLml0IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmdyIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnB0IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmVzIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmlsIiA6MSwKICAgICAgICAiZ29vZ2xlLmNoIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnNlIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm5sIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmJlIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmF0IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnBsIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnB0IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmVzIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmZpIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm5sIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmh1IiA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS50ciI6MSwKICAgICAgICAiZ29vZ2xlLnJvIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmRrIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm5vIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5hdSI6MSwKICAgICAgICAiZ29vZ2xlLmNvLm56IiA6MSwKICAgICAgICAiZ29vZ2xlLmNhIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbSIgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5teCI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5iciI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5hciI6MSwKICAgICAgICAiZ29vZ2xlLmNsIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5wZSI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5lZyI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5wYSI6MSwKICAgICAgICAiZ29vZ2xlLmx0IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmJpIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnBuIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmxpIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5uZiI6MSwKICAgICAgICAiZ29vZ2xlLnZnIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm13IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmZtIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnNoIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNkIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm1zIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmNyIiA6MSwKICAgICAgICAiZ29vZ2xlLmx2IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmllIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmdnIiA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmplIiA6MSwKICAgICAgICAiZ29vZ2xlLnByIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5weSI6MSwKICAgICAgICAiZ29vZ2xlLmdtIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnRkIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS51YSI6MSwKICAgICAgICAiZ29vZ2xlLmNvLnZlIiA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS50ciI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5tdCI6MSwKICAgICAgICAiZ29vZ2xlLmNvbS51eSI6MSwKICAgICAgICAiZ29vZ2xlLmhuIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvbS5uaSI6MSwKICAgICAgICAiZ29vZ2xlLmdsIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmt6IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnNtIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLm11IiA6MSwKICAgICAgICAiZ29vZ2xlLmFzIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnV6IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnJ3IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmN6IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnJ1IiAgICA6MSwKICAgICAgICAiZ29vZ2xlLnJzIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLm1kIiAgICA6MSwKICAgICAgICAiZ29vZ2xlLmNvLmlkIiAgICA6MSwKICAgICAgICAiZ29vZ2xldGFnbWFuYWdlci5jb20iICAgIDoxLAogICAgICAgICJhY2NvdW50cy55b3V0dWJlLmNvbSIgICAgOjEsCiAgICAgICAgImdvb2dsZS5jb20udGoiOjEsCiAgICAgICAgInRoaW5rd2l0aGdvb2dsZS5jb20iOjEsCiAgICAgICAgImdvb2dsZXRhZ21hbmFnZXIuY29tIjoxLAogICAgICAgICJhbmRyb2lkLmNvbSI6MSwKICAgICAgICAid2lraW1lZGlhLm9yZyI6MSwKICAgICAgICAiZ29sYW5nLm9yZyI6MSwKICAgICAgICAidGVuc29yZmxvdy5vcmciOjEsCiAgICAgICAgIndpa2lwZWRpYS5vcmciOjEKICAgIH07CiAgICB2YXIgciA9IGhvc3QubWF0Y2goLyhbXi5dKlwuKFthLXosQS1aXSp8Y29tXC5bYS16XSp8Y29cLlthLXpdKikpJC8pWzFdOwogICAgaWYociAmJiBILmhhc093blByb3BlcnR5KHIpKSB7CiAgICAgICAgaWYoaG9zdCA9PSAic2Nob2xhci5nb29nbGUuY29tIiB8fCBob3N0ID09ICJzY2hvbGFyLmdvb2dsZS5jb20uaGsiIHx8IGhvc3Q9PSJzY2hvbGFyLmdvb2dsZXVzZXJjb250ZW50LmNvbSIpewogICAgICAgICAgICByZXR1cm4gIkhUVFBTIHd3dy56aGlmdS5zdHJlYW06NDQzOyIKICAgICAgICB9ZWxzZSBpZihob3N0ID09ICJtdGFsay5nb29nbGUuY29tIiAgKXsKICAgICAgICAgICAgcmV0dXJuIEQ7CiAgICAgICAgfWVsc2V7CiAgICAgICAgICAgIHJldHVybiBQOwogICAgICAgIH0KICAgIH1lbHNlewogICAgICAgIHJldHVybiBEOwogICAgfQp9
我不知道是不是，但我现在选择的是“系统代理”且可以通过其他代理访问google

错误日志：
Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []

（我没有给这台电脑的switchy omega导入任何文件，只是用它来试验）

**Comment by FelisCatus** [comment]
要调试这个问题，需要 SwitchyOmega 的错误日志。请先进行操作以复现问题（比如把 SwitchyOmega 设置成系统代理，然后在另一个扩展程序里选择应用代理情景模式之类的）。然后右键点击图标，选择“导出错误日志”，然后上传到这里。

**Comment by FormosaZh** [comment]
1，已经装好其它代理扩展，比如：http://dwz.cn/512Lteae
2，打开 chrome://net-internals/#proxy 页面，观察 Effective proxy settings 的变化:
     分别更改代理提供的“智能、一直、关闭”功能后，Effective proxy settings 的确显示有所改变
3，最后安装 SwitchyOmega 2.5.19 ，卸载后再安装 SwitchyOmega 2.5.15 （手工拖拽安装），
     采用默认设置，检查“通用”设置中的两个复选框（网络请求和冲突）都已经勾选；
     以下是错误报告的区别：

2.5.19 在选择”系统代理“时，改变其它代理的设置时，未出现？号图标，错误报告如下，少了很多内容：

Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]    

2.5.15 在选择”系统代理“时，改变其它代理的设置时，此版能出现？号图标，错误报告正常如下：
Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "pac_script",
        "pacScript": {
            "data": "function FindProxyForURL(url, host){return 'DIRECT';}",
            "mandatory": false
        }
    }
}

**Comment by FelisCatus** [comment]
多谢，我这边需要一些时间来复现这个问题。

**Comment by WBinyv** [comment]
谢谢啦

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
