### ISSUE TITLE
旧版chrome无法使用

### ISSUE THREAD

**Issue by safari5S** [FelisCatus/SwitchyOmega#1608]
版本31.0.1650.63 忘记设置更新，自动更新后情景模式无法切换，管理设置界面也进不去了。求助

**Comment by celeron533** [comment]
设置系统层面的代理后让chrome自动更新

**Comment by safari5S** [comment]
就是不想升级chrome才过来问的，这个插件必须要更新到最新版才能用吗？能否重新下个旧版打上去？因为有很多链接都自动转换都没有备份，所以不想重新弄。@celeron533

**Comment by FelisCatus** [comment]
我估计现在已经没有办法再去测试 Chrome 31 了……如果可以的话，可以试试看右键点图标，然后导出错误日志，然后上传到这里吗？我可以看看是不是很容易修复的问题。

另外，旧版的 SwitchyOmega 可以在这里下载： https://github.com/FelisCatus/SwitchyOmega/releases

建议试试看哪一个版本开始没法正常使用。

**Comment by safari5S** [comment]
@FelisCatus 我是从8月20自动更新后不能用的之前的都还行。我进不了管理页面没有看见右键有导出错误日志的按钮。谢谢你我试试下个旧版的。

**Comment by FelisCatus** [comment]
@safari5S 是右键点击 SwitchyOmega 在浏览器工具栏上的那个图标哦，不需要进入选项页面。菜单项可能是叫保存错误日志或者是 "Save error log", 请仔细找一下。

**Comment by FelisCatus** [comment]
那就很麻烦了，也许保存错误日志的那个功能也不能用了……

最后还有一个办法是打开右键点击图标，选择管理，然后启用扩展开发者模式（可以在 Chrome 的扩展管理页面右上角？附近找一下一个勾选框），最后点击 SwitchyOmega 下面的 `background.html`，选择“控制台/Console”，然后把错误内容复制到这里。

**Comment by safari5S** [comment]
Uncaught Error: Invalid value for argument 1. Property 'contexts.0': Value must be one of: [all, page, frame, selection, link, editable, image, video, audio, launcher]. extensions::schemaUtils:34
Uncaught TypeError: Cannot read property 'stack' of null log_error.js:5
Uncaught ReferenceError: Promise is not defined omega_target_chromium_extension.min.js:5400
Uncaught ReferenceError: OmegaTargetChromium is not defined background.js:6

是这样的

**Comment by FelisCatus** [comment]
如果只是这样的话也许还能修复。我试着在分支上做了一下兼容，请试试看能不能用。

请到 Circle CI 上的[这个链接](https://circleci.com/gh/FelisCatus/SwitchyOmega/tree/feature%2Fchrome-31)，注册一个账户，然后点状态为 SUCCESS 的最新的版本（数字最大的那个），然后选 Artifacts （×），下载 Chromium 版的 zip 文件。这样下载的文件是一个未签名的测试版，可以在扩展管理页面启用开发者模式并刷新后，把 zip 文件拖动到这里安装。
（* 注意：必须注册才能看到 Artifacts 标签，否则只能看到 Test Summary 等。）

如果测试通过的话，我会把这些改动合并进去，下个正式版本开始应该可以恢复兼容。

**Comment by FelisCatus** [comment]
……我正好发布了一个新版本，顺手合并了下。可以试试看直接安装 v2.5.20 ，不需要去下载测试版了。

**Comment by safari5S** [comment]
@FelisCatus 你上面给的那链接我也是打开是空白的，可能真的是浏览器版本太低了。不过自动跟新后可以用了。谢谢你了
