### ISSUE TITLE
I can't browse the Internet by proxy.

### ISSUE THREAD

**Issue by merckliu** [FelisCatus/SwitchyOmega#161]
![1](https://cloud.githubusercontent.com/assets/7918720/5606150/b384f38a-945b-11e4-8164-23154d85c865.png)
Direct connection
![2](https://cloud.githubusercontent.com/assets/7918720/5606151/b39e916e-945b-11e4-8de6-a6f39aef96a1.png)
Automatic switching

I have no idea what makes it happened. it worked very well before.

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by zhenghongzhi** [comment]
See this if it will help
>我导出了一份配置，然后重新导入以后好了，你试试

**Comment by merckliu** [comment]
Thanks，有效。

**Comment by cicku** [comment]
Sorry guys I accidentally imported a wrong rule to the list yesterday.
