### ISSUE TITLE
外部情景模式的BUG

### ISSUE THREAD

**Issue by WBinyv** [FelisCatus/SwitchyOmega#1610]
我尝试了很多种办法，包括（用其他代理插件来挤switchy omega，勾选“显示弹出菜单项以从其他应用程序导入代理设置”， 勾选“显示高级条件类型解锁新型高级但复杂的开关条件”等），但都无法使他显示出“外部情景模式“的选项，我该怎么做？

在以前，我可以做到。但我前几天重装了系统后重新安装插件就不行了，我在另一台电脑上也不行

求大佬帮助

**Comment by FelisCatus** [comment]
请查看 https://github.com/FelisCatus/SwitchyOmega/issues/1607#issuecomment-415224116 所说的调试方案，如有问题请在那边回复。
