### ISSUE TITLE
Enable quick switch at startup

### ISSUE THREAD

**Issue by SongRb** [FelisCatus/SwitchyOmega#1612]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Google Chrome 70.0.3532.2 (Official Build) canary (64-bit)
Windows 10 Pro 64 bit 17134.228

### Problem description / 问题描述
Quick switch option can not be written into config.

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. Launch browser after start up
2. Right click SwitchyOmega icon and select enable quick switch
3. Click apply settings
4. Reboot and relaunch browser
5. Right click SwitchyOmega

#### Expected behavior / 期望发生的情况
Enable quick switch option should now be selected

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
Enable quick switch option isn't selected

![image](https://user-images.githubusercontent.com/15308237/44698628-5236ef80-aab3-11e8-98e8-ca4a373bba9a.png)

**Comment by FelisCatus** [comment]
Does it work if you select Enable Quick Switch in the options page (instead of the context menu)?

If that won't work either, please select the "Save error log" item from the context menu (as shown in the screenshot above) and upload the resulting file here.

**Comment by SongRb** [comment]
Actually, each time I click "Enable Quick Switch", I will be redirected to the option page and click "Apply Changes".  This option is enabled indeed, but will be reverted after chrome restarts.

**Comment by FelisCatus** [comment]
Thanks for the reply.

Quick Switch requires at least 2 profiles to be placed in "Cycled Profiles". On the options page > Interface, make sure to drag and drop two profiles into the "Cycled Profiles" list (for example, your proxy profile and the `direct connection` profile. Make sure the save the changes afterwards.

If that still doesn't work, I would need the error log and a backup file of your options to move forward.
