### ISSUE TITLE
chrome 浏览器不支持 socks5 代理认证,建议支持密码认证

### ISSUE THREAD

**Issue by githubwanghui** [FelisCatus/SwitchyOmega#1615]
SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by celeron533** [comment]
[常见问题](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8D%E6%94%AF%E6%8C%81-socks5-%E7%9A%84%E7%94%A8%E6%88%B7%E5%90%8D%E5%AF%86%E7%A0%81%E8%AE%A4%E8%AF%81%E5%90%97)

**Comment by celeron533** [comment]
#1614

**Comment by ad2248** [comment]
你应该去chrome建议

**Comment by xiaominggpT7890** [comment]
不支持需要修改浏览器内核，市面上有修改好的。搜索 easybr指纹浏览器。
