### ISSUE TITLE
600/602有时候是604问题

### ISSUE THREAD

**Issue by dlssx** [FelisCatus/SwitchyOmega#1617]
删除ip.txt，设置IP6等方法都试过了，还是上不去，现在连XXnet都打不开了，懵逼，求助

SwitchyOmega 2.4.6
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by FelisCatus** [comment]
XXNet 问题，与 SwitchyOmega 无关。
