### ISSUE TITLE
During chrome stratup it seems all entries are loaded or refreshed not only the current one

### ISSUE THREAD

**Issue by geertn444** [FelisCatus/SwitchyOmega#1619]
### SwitchyOmega version / SwitchyOmega 版本

2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本

Chrome Portable v68.0.3440.106

### Problem description / 问题描述
I have different proxy.pac locations, example:

PROFILE1: http://server1/proxy.pac
PROFILE2: http://server2/proxy.pac
PROFILE3: http://localhost/proxy.pac

I am running with active profile PROFILE1 for example.
When stopping and starting Chrome, i see Chrome doing requests to my localhost (profile3, although it is not current) and server2.

When i remove profile3, and restart, no request is arriving.

This can be confusing when troubleshooting proxy.pac issues, because it seems Chrome might load another proxy.pac as the one currently selected.
Also localhost was currently my WPAD download locations, and i was wondering: where are the proxy.pac requests coming from , while i should only see /wpad.dat requests.

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

#### Expected behavior / 期望发生的情况

When starting Chrome, only load the "current" previous selected profile.

**Comment by FelisCatus** [comment]
To see which PAC is used by Chrome, use `chrome://net-internals/#proxy` to check the active settings. This is the definite answer and works regardless of what extensions are used.

For the requests: SwitchyOmega would attempt to download all downloadable profiles (PAC / rule lists) on startup and at regular intervals. Such caching is required for using PAC profiles in switch profiles, etc. and helps SwitchyOmega to behave consistently, even if the PAC file is sometimes unreachable. Please note that such downloading behavior is NOT directly linked with which profile is currently applied.

If you would not want ANY updates to happen at all, please set the update interval to `Never`, which also disables updates on startup. The setting can be found at Options > General > Download Options.
