### ISSUE TITLE
menu popup is slow

### ISSUE THREAD

**Issue by tonyluj** [FelisCatus/SwitchyOmega#162]
First of all, the brand new UI is great, especially the setting UI.
But the menu slow down the speed of changing proxy. After clicking the icon, it has to speed hundreds ms to popup.
I think that speed it up make it more convenient.
Thinks a lot to supply such convenient app.

SwitchyOmega 2.2.11
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by nsznsznsz** [comment]
我也这么觉得 点一下有差不多一秒的延迟才出来

**Comment by FelisCatus** [comment]
我之前做了一下性能分析，不过没发现明显的瓶颈……也不知道究竟是DOM比较卡，还是扩展内通信比较卡……

完全不知道该怎么办啊……

**Comment by FelisCatus** [comment]
经过使用开发者工具的时间线分析，页面加载时的脚本执行时间过长（75%以上），而扩展内通信并不造成显著延迟。主要目标：减少过多的脚本行为。考虑将一些内容移出 Angular.

此外，有一个页面资源的加载时间过长（`omega_profile_select.html`），应该将页面集成到JS中。

**Comment by FelisCatus** [comment]
或者真的别在 popup 里用 angular 了……感觉会特别卡。

**Comment by FelisCatus** [comment]
目前而言，这里优化性能的优先级是最高的。关于弹出菜单的其他改进，应该尽可能推迟到优化完成后再进行。

**Comment by butaixianran** [comment]
我觉得吧，这个问题有个简单办法搞定：提供个选项，让用户把“未加载资源”相关的功能，完全关掉。

现实是，平时上网都是去常用网站，这个功能完全用不上。需要用的时候，必定是发现某个不常用的页面打不开了，才会去要修改规则。

这时候，用户自己再去开启这个功能，刷新页面，添加规则。

这样，平时，大家只用常用网站，就没有卡界面的问题。

现在大家觉得卡界面不能忍受，是因为goagent经常挂，即使常用网站，也要经常切换  虚情景。那么卡太多次就不耐烦了。

**Comment by FelisCatus** [comment]
@butaixianran 未加载资源相关功能一直可以在选项中关闭。弹出的界面中也有提示这一点。

不过，弹出菜单的性能问题并不在于此。

**Comment by FelisCatus** [comment]
[v2.4.3 版本](https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.4.3)重制了一个新的弹出菜单实现，希望能快一点。目前此版本还在测试中，有兴趣的话可以直接点链接下载安装。有问题请及时回报。

**Comment by FelisCatus** [comment]
v2.4.4 已经大幅提高加载速度，大家可以自己试下。
