### ISSUE TITLE
可以记录日志吗？ how to save log？

### ISSUE THREAD

**Issue by chainofhonor** [FelisCatus/SwitchyOmega#1621]
自动切换的方式比较慢，请问可以记录日志哪些域名使用了代理吗？
我直接把域名添加到规则里面，这样能加速访问
The method of automatic switching is slow. Could you log which domain names use the proxy?
I added the domain name directly to the rule, which speeds up access.

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega 不记录访问的 URL ，所以没有日志。代理服务器的使用情况可以在 Chrome 的调试页面看到，也支持搜索： chrome://net-internals/#events
