### ISSUE TITLE
pinterest 连不上

### ISSUE THREAD

**Issue by line222** [FelisCatus/SwitchyOmega#1622]
其他网站正常，就是pinterest连不上，
显示：600:gae_exception:'600:fetch gae fail' https://www.pinterest.com/gae_exception:'600:fetch gae fail' https://www.pinterest.com/gae_exception:'600:fetch gae fail' https://www.pinterest.com/

求解答

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36

**Comment by celeron533** [comment]
switchy omega只是个代理设置软件，你提到的问题`600:fetch gae fail`看起来是xx-net的问题，和switchy omega 无关啊

**Comment by line222** [comment]
求指导，完全不知道这个怎么设置。
那个怎么能够设置后，连接pinterest

**Comment by FelisCatus** [comment]
代理服务器问题，与此项目无关。
