### ISSUE TITLE
Chrome 69 forbid install crx from local.

### ISSUE THREAD

**Issue by GalaxyScape** [FelisCatus/SwitchyOmega#1623]
## 问题
Chrome 69 因为*安全问题* **禁止**从本地安装crx文件。
[项目网站](https://www.switchyomega.com/download/)所提供的本地安装方法已经失效了，希望作者能够更新一下网站内容。

目前好像只能在开发者模式解压crx文件安装。

请问还有其他解决方案吗？

PS:
    谷歌现在这样做再加上墙的存在，Firefox版本用起来感觉更加省心一点 -_- 。

**Comment by celeron533** [comment]
网上也没搜索到相关的解决办法，可能是因为chrome69刚出来的缘故，估计将来会有些隐藏开关或者flag能再次允许本地安装？

**Comment by celeron533** [comment]
Perhaps you could try this:
https://stackoverflow.com/a/11879334

> 1. Settings-Icon > Tools > Extensions
( the 'three horizontal-bars' icon in the top-right corner )
> 2. Drag and drop the "crx" extension file onto the Extensions page from [step 1]
( .crx file should likely be in your Downloads directory )
> 3. Install

> Thanks :) this works even with Chrome's new policy of not accepting extensions other than those from Chrome Web Store. ("Extensions, apps, and user scripts can only be added from the Chrome Web Store.") – Igor Popov Sep 8 '12 at 9:54

**Comment by FelisCatus** [comment]
`switchyomega.com` 不是本项目网站，与本项目无关。本项目没有网站。

我这边暂时也不知道怎么才能正常安装，如果有人能写一个具体的步骤，我愿意更新到下载页面的说明上。但那个网站并不是我能控制的。
