### ISSUE TITLE
Is there anyway to automatically use proxy for failed web requests for resources

### ISSUE THREAD

**Issue by Daniyal-Javani** [FelisCatus/SwitchyOmega#1624]
SwitchyOmega already has a feature called failed resources and we can enable it in general tab with:
`Show count of failed web requests for resources in the current tab.`

Is there any way to use proxy for these failed resources automatically?

**Comment by Dees7** [comment]
In you can select "Default" proxy in auto switch profile.

**Comment by Daniyal-Javani** [comment]
> In you can select "Default" proxy in auto switch profile.

It just pass all traffic through the proxy

**Comment by FelisCatus** [comment]
There was some discussion about this and the short answer is no. The browser only asks SwitchyOmega once regarding what proxy should be used for each request. SwitchyOmega does not make the requests and cannot control the network internals.
