### ISSUE TITLE
[Direct] uses proxy from Connection Settings

### ISSUE THREAD

**Issue by Dees7** [FelisCatus/SwitchyOmega#1628]
### SwitchyOmega version / SwitchyOmega 版本
Version 2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
FireFox 62.0 (64-bit)

### Problem description / 问题描述
Profile [Direct] uses proxy from Connection Settings

#### Steps to reproduce issue / 重现错误所需步骤

1. about:preferences
2. Network Proxy [Settings]
3. (*) manual.  and set any proxy.
4. SwitchyOmega select [Direct] 

#### Expected behavior / 期望发生的情况
Not use Proxy at all

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
Used Proxy from FireFox settings.

**Comment by FelisCatus** [comment]
This is a known bug in Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=1398900

If someone wants to contribute to Firefox, please feel free to create patches with tests. Closing this because there is no way for SwitchyOmega to work around this.
