### ISSUE TITLE
新建PAC情景模式

### ISSUE THREAD

**Issue by dengbowen98** [FelisCatus/SwitchyOmega#1629]
PAC情景模式不能选择，标明红色字体：由于技术限制,PAC 情景模式无法在 Mozilla Firefox 上工作!

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by FelisCatus** [comment]
Firefox 的问题。这边没办法修复。

**Comment by AnyWAT** [comment]
可在Firefox 自身的网络设置——自动代理配置的 URL（PAC）处设置，仍支持 IE11（或Chrome ） 不再支持的本地PAC

**Comment by FelisCatus** [comment]
是的，如果用户单独使用 PAC 文件的话，建议使用那个选项。但是 SwitchyOmega 作为 WebExtension 暂时是没办法支持 PAC 文件，以及自动切换里调用 PAC 文件之类的用例了。
