### ISSUE TITLE
chrome69版本冲突？

### ISSUE THREAD

**Issue by ilovemywas** [FelisCatus/SwitchyOmega#1633]
chrome更新到69版本后，跟此插件好像有冲突？有些国内网站加载非常慢，去掉此插件后恢复正常，或者换回chrome老版本问题解决

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by Mrcooder** [comment]
嗯，我的 Autoproxy 失效了

**Comment by celeron533** [comment]
Windows 7 + Chrome 69 目前没有遇到这个问题

**Comment by FelisCatus** [comment]
不像是 SwitchyOmega 的问题。

**Comment by 43256305** [comment]
有人说禁用HTTPS Everywhere可以，但是不知道怎么禁用，汗

**Comment by AnyWAT** [comment]
左键右上角3个点——更多工具——扩展程序 chrome://extensions/
