### ISSUE TITLE
ubuntu系统使用chrome翻墙之前还好好的，现在突然不能翻墙了，下面是出错的log，麻烦帮忙分析一下

### ISSUE THREAD

**Issue by zzb2760715357** [FelisCatus/SwitchyOmega#1639]
SwitchyOmega 2.3.19
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by zzb2760715357** [comment]
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。
这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

您可以查看以下域名，并根据实际情况确定是否对其使用代理。

**Comment by FelisCatus** [comment]
我重复一遍，这些问题可能是由您的网络、代理服务器或网站本身引起的。这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

这里仅供讨论 SwitchyOmega 相关问题。如有代理相关问题请去其他论坛等地方求助。
