### ISSUE TITLE
goagent error, ValueError: sample larger than population

### ISSUE THREAD

**Issue by vedardcn** [FelisCatus/SwitchyOmega#164]
Hi I found goagent doesn't work and there is upgrade remind for switchysharp. So, I download and upgrade to SwitchyOmega. disabled switchysharp as well. 
But goagent still doesn't work. I tried to uploader and can't connect to google cause it is prohibited by China government. 
When I run goagent.exe and google browser, it showed "ValueError <sample larger than population",>
Any advice for it? Thank you so much!

**Comment by FelisCatus** [comment]
This is a problem with GoAgent and has nothing to do with this project.
