### ISSUE TITLE
ipv6如何设置匹配规则？

### ISSUE THREAD

**Issue by Lengsir** [FelisCatus/SwitchyOmega#1640]
一般代理都是ipv4的，而我有时会用到ipv6，比如上bt.byr.cn，但是白名单匹配规则里没有ipv6的各项示例，我也试过几种方式，依然没法匹配，请问如何设置才能让代理跳过整个ipv6？
![image](https://user-images.githubusercontent.com/24917950/46248242-9702cd00-c449-11e8-840c-7c08437f33f4.png)

**Comment by FelisCatus** [comment]
我记得 `::/0` 匹配所有 IP 地址，应该可以用这个。注意这只对单独使用该情景模式的时候才生效，对自动切换模式无效。（自动切换模式下， SwitchyOmega 只能看到 URL ，而不负责把 URL 解析成 IP 地址，所以没办法判断 `example.com` 是否是一个 IPv6 网站。）
