### ISSUE TITLE
Feature request: auto download backup file for 10/15/20/etc mins/hours

### ISSUE THREAD

**Issue by kz159** [FelisCatus/SwitchyOmega#1641]
As title says, i would love to have this feature for autoprovisioning, PAC scripts are good, but i need to sync ALL my profiles for 5-10 workers(manually typing my local server, download backup) and its quite a pain.

**Comment by FelisCatus** [comment]
I believe web hooks (#534) will offer a better and more general solution to this. I apologize if that issue has been around like forever, but you're welcome to help by creating a Pull Request.
