### ISSUE TITLE
firefox 的 network.dns.disablePrefetch 带来的无法访问DNS污染网站问题--算不上解决了

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#1642]
chrome 配合 SwitchyOmega 也有这个问题。
firefox 这个问题极为严重，代理规则和代理服务器全部配置正确， `network.dns.disablePrefetch = false`的情况下，**第一次打开google 等 dns 被污染网站，需要等一分钟，或者等待后，显示无法打开**，估计就是 dns 默认缓存时间 60 秒。
将 `network.dns.disablePrefetch = true` 后，问题解决。
搜了一下，貌似没有人在google搜索结果，或本issues下明确留下这个知识库内容。因此发此贴。

**Comment by Justsoos** [comment]
又用了几天，各种问题。暂时放弃 firefox + SwitchyOmega了，还是Chrome好用些。

**Comment by FelisCatus** [comment]
现在可以搜索到了，因为不是 SwitchyOmega 的问题所以我就关掉这个了。
