### ISSUE TITLE
 'Resources not loaded' even I have added these resources to the scenario mode

### ISSUE THREAD

**Issue by SouWilliams** [FelisCatus/SwitchyOmega#1644]
The switchomega always prompts me 'Resources not loaded' even I have added these resources to the scenario mode.

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

![image](https://user-images.githubusercontent.com/6127395/46516052-1f45ff80-c89a-11e8-9b1e-a2c1057bae05.png)

![image](https://user-images.githubusercontent.com/6127395/46516085-4997bd00-c89a-11e8-9819-d7aaaee29d6c.png)

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/46516816-5a4a3200-c89e-11e8-8e25-be5a579c0288.png)

**Comment by FelisCatus** [comment]
You would almost never want to send `127.0.0.1` to the remote proxy and I believe what @AnyWAT has suggested will work.
