### ISSUE TITLE
【选项同步】功能的问题！

### ISSUE THREAD

**Issue by tea1111980** [FelisCatus/SwitchyOmega#1645]
注：我把 SwitchyOmega 简称为 SO

在SO的【导入/导出】选项里，有一个【选项同步】的功能，这个功能我刚才试了一下，极为不好用，还把我以前配置的规则全部同步清掉了。 

这功能我也是在当时还未使用前就开启了的，而且我用SO已经有很长一段时间了，为什么现在在Chrome canary （64 位）版本里，却无法同步呢？

我用其它版本的浏览器，比如 Chrome Dev 版本也试过，同步下来的都是默认初始化的选项，那个英文写的Auto Proxy 或 Proxy 的设置，并不是我之前保存到【云端同步】上的数据。（从第一次启用【选项同步】功能时，我就一直没动过它。直到这次，我想把它以前保存到云端上的数据设置，同步到我现在新装的两个版本Chrome浏览器上时，同步过来的却是经过初始化之后的云端数据设置，被同步到了新的浏览器上。之前我保存的云端数据设置去哪了？这个同步设置功能开启之后，我就一直没有去动它。）

同步过程：
1. Chrome 稳定版 -----> canary 版 （同步到 canary 上的SO设置，只有一个情景模式（ 实际上有两个情景模式 ）的代理，这个代理是我自己之前就建立好的（到这里为止同步功能是正常的），但是之后除了这个代理设置之外，还有一个自动规则没有被同步过来。）

然后，我再从 canary 版 同步到 Chrome Dev 版，如下：

2. canary 版 -----> Chrome Dev 版（注意：此时canary版里已经包括有我从Chrome 稳定版同步过来的其中一个内容，这个跟上面的情况完全不同，这个直接就同步成初始化状态了（也就是说在云端上保存的同步设置，已经不是我之前保存在云端上的同步设置了 ）。也就是说我上面同步到 canary 版的内容，一个都没有从 canary 版里，同步到 Chrome Dev 版的SO里。）

请问，以上问题是怎么回事？

>. &nbsp;&nbsp;&nbsp; SwitchyOmega 我重装过，也没起作用。（只同步到了情景模式：代理规则，没有
>.  &nbsp;&nbsp;&nbsp; 同步到自动代理规则 ）
>.
>.
>.
>.  &nbsp;&nbsp;&nbsp; 好像同步功能又正常了，但是以下这种情况的情景模式无法同步，能否想想其
>.  &nbsp;&nbsp;&nbsp; 它方法代替一下？
>.  &nbsp;&nbsp;&nbsp; 
>.  &nbsp;&nbsp;&nbsp; 
>.  &nbsp;&nbsp;&nbsp; 我想到一个替代的方法，就是自己隔一段时间，在SO上做一次本地文件的
>.  &nbsp;&nbsp;&nbsp; 备份，然后恢复配置的时候直接恢复这个备份的本地文件。
>.  &nbsp;&nbsp;&nbsp; 如果是这样的话，那这个云端同步备份的功能就失去它本身的意义了。
>.  &nbsp;&nbsp;&nbsp;  你考虑一下吧。
>.

<font size="24px" color="red" font-family="宋体">**### 建议：**</font>
我现在又看了一下同步机制，提示我 【 此情景模式使用存储空间过多，因此无法进行同步。】
这个问题，我有一个建议望采纳一下：

可不可以把这个自动规则匹配的情景模式，将里面匹配的地址弄成MD5编码 或 SHA-1、SHA-256等中的任意一种编码来进行匹配呢？

这样匹配起来的速度快很多，而且存再多规则到里面也不用担心存储空间过多的问题。

或者将自动规则匹配的情景模式里面的数据，【分段】存放于不同的存储区域，使用时，只需要用以上编码来集合调用里面的数据，而不是把规则存储于同一区域，最终导致里面的数据过大而变得不好用呢。

比如：随便拿个内网地址举例哈

>192.168.1.1-1 <----这是第一次存储的区域，大小为10KB
>192.168.1.1-2 <----这是同一地址下第二次存储的区域，大小为100KB
       .
       .
       .
192.168.2.1-1 <---- PS：类似于这样的文件，里面存放的都是规则清单，上面也是。
192.168.2.1-2
.....
··
最高单个规则文件存储大小10KB----100KB 或至多 200KB之间，或者你有更好的合适大小。
现在我情景模式里面的自动规则文件，大小为530KB左右，在增删改时就已经卡得不要不要的啦。
··

以此类推，当某个存储区域、某个被存储的规则文件，已经达到了500KB 或 更高存储大小的时候（可分割），此时再去更改里面的数据内容，就会明显感到卡顿，也不利于云端同步备份。

如果是已经分段存储了的话，则只需要更改192.168.1.1-1 或 2 那些只存有10KB左右数据的规则文件，这种方法显然不用把那些不需要增删改的地址也列出来，以此能减少无关条目的加载时间。

也就是说限制单个规则文件的大小，并且把规则文件分段存放 和 处理，只要超过被限制的文件大小就开始自动分割成段，使用MD5编码 或 SHA-1、SHA-256等中的任意一种编码，进行内容的匹配并可分段调用。

这样就可以流畅增删改了，再也不会因为提示单个存储区域里单个规则文件里数据量过大，而在更改时有卡顿的现象了，也利于云端同步备份，同时可以增删改更多的地址条目了。

你觉得这个方法可行不？

我只是按用户的思路提供了一下建议，我不是程序员，也不会编程，但这并不影响我提供思路呀。你说我说的对吗？
@FelisCatus 

呵呵，大概就是这样一个情况。望回复。谢谢！

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by FelisCatus** [comment]
见 #548. 分隔是可行的，但是容易制造区块1更新了但是区块2没有更新之类的一大堆特殊情况，所以处理起来会很费力。目前我暂时没有时间去做一个万全的解决方案。
