### ISSUE TITLE
Hosts defined in /etc/hosts are not resolved

### ISSUE THREAD

**Issue by trickytibo** [FelisCatus/SwitchyOmega#1646]
Hosts defined in /etc/hosts are not resolved by SwitchyOmega => DNS failed

Configuration : 
SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0

**Comment by celeron533** [comment]
DNS may also resolved via the remote proxy server. It will not look local hosts def.

**Comment by FelisCatus** [comment]
In HTTP/HTTPS/SOCKS proxies, the domain names are sent to the remote proxy server as-is. SwitchyOmega cannot change this behavior. If you'd rather use direct connections for some of the things in hosts, please feel free to put them in the bypass list OR add an Auto Switch rule for those domains and point them to `[Direct Connection]`.
