### ISSUE TITLE
自动切换无法访问google

### ISSUE THREAD

**Issue by kobebryantlin0** [FelisCatus/SwitchyOmega#1648]
SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.15 Safari/537.36

**Comment by AnyWAT** [comment]
与其说与此扩展有关，不如说与代理直接相关😜
![default](https://user-images.githubusercontent.com/37962734/46901166-0adcb500-cee1-11e8-97e1-c803c09e2ece.png)

**Comment by ugksoft** [comment]
wj这种东西就不要截屏出来了,再说wj这种太差了,太不稳定了,就算拿来应急,都不太靠谱
不说网络本身引起的稳定, 至少后台,肯定是没技术,又想"搞宣传",是糊乱折腾的, wj,fg等,有时更新就是糊搞的,更新出来的版本完全连不上,老版本反而能连上, IT业的, 自己顺手抓只肉鸡, 不是IT的,买个vps, 同事,家人一起用,
一般,99.999999%是用来Google的, IT业的,任何和技术有关的东西,只能是google才能找到
艳红家,只有广告和骗子

用了这几年,只有偶尔情况, 是插件引起不能代理, 重开浏览器,或是切换到其它模式,再切换到自动模式,就能恢复正常 (HTML,JS这些东西,是脚本,又费资源,本身就不能保证100%稳定的,所以不是插件引起的,是firefox/chrome插件实现方式问题,即体制问题 )

**Comment by AnyWAT** [comment]
再说wj这种太差了,太不稳定了🤣 https://github.com/DrayChou/twitter-tools/issues/1#issuecomment-431546997
