### ISSUE TITLE
建议：Proxy Profile 下支持添加多台服务器

### ISSUE THREAD

**Issue by mcdawang** [FelisCatus/SwitchyOmega#165]
公司内网有台代理服务器，所以使用的 内网IP:PORT，回家后需要本机开代理端口改为 127.0.0.1:PORT，每次需要手工切换比较麻烦。
希望能像以前用PAC那样，添加多台服务器后第一个服务器不通自动尝试使用第二个。
能提供顺序/轮询设定更好，轮询在内网共享时比较有用，多台机器同时连接同一线路的代理服务器容易拥堵。

**Comment by FelisCatus** [comment]
如果真的需要用的话，暂时可以建立一个 PAC 模式，内容为以下即可。可以设置多个代理服务器，且可以和自动切换配合使用。

```
function FindProxyForURL(url, host) {
  return "192.168.1.1:8888;127.0.0.1:8888";
}
````

**Comment by mcdawang** [comment]
谢谢，解决了问题。

```
function FindProxyForURL(url, host) {   return “PROXY 192.168.1.1:8888;PROXY 127.0.0.1:8888"; }

```

**Comment by FelisCatus** [comment]
先关闭这个了。上面已经提了一种解决方式，而另一种可能的解决方式是 #152 。我想，要做的话可能也是做 #152 吧……那么先关闭这个了。
