### ISSUE TITLE
Feature Request: Proxy settings per Chrome Window

### ISSUE THREAD

**Issue by nomennescio** [FelisCatus/SwitchyOmega#1650]
I have multiple proxies, and I would like to be able to have different proxy configurations per Chrome Window. Can you add a feature to support that?

**Comment by AnyWAT** [comment]
![image](https://user-images.githubusercontent.com/37962734/46894344-b6b4df00-cea6-11e8-9fd0-621d070b140a.png)

**Comment by FelisCatus** [comment]
Unfortunately, I [cannot](https://github.com/FelisCatus/SwitchyOmega/wiki/FAQ#can-you-add-support-for-tab-based-or-window-based-switching). I wish I could though.

**Comment by nomennescio** [comment]
Thanks for the clarification
