### ISSUE TITLE
能不能让浏览器重开,也稳定在指定模式上啊, 现在有时是在选择模式上,但大多会恢复到自动档

### ISSUE THREAD

**Issue by ugksoft** [FelisCatus/SwitchyOmega#1652]
问题1,
能不能让代理,永远在一个模式上,默认是自动档上面, 但强制选择VPN点后, 关闭chrome,再打开
大部分情况下是恢复成自动档了,只有少数还在VPN上,  支持一下吧, 不然很容易打开时,忘记模式

问题2 附带问题
"此情景模式使用存储空间过多，因此无法进行同步。"这个问题还没解决啊
我的规则,有400多个域名, 以前好像有一阵子你解决了,最近又出这问题了
不过问题不大, 大不了,多台电脑,定时的手工拷导一下列表

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

**Comment by AnyWAT** [comment]
貌似圈出部分？
![default](https://user-images.githubusercontent.com/37962734/46915701-9e95aa80-cfe1-11e8-92e4-977e7e25ac6c.png)

**Comment by celeron533** [comment]
我猜测你的第一个问题是由第二个问题导致的
我日常使用过程中没有超容量问题，所以每次开启Chrome的时候也都能正常的读取上次的选择

**Comment by ugksoft** [comment]
谢谢, 发完这消息,我也发现这个选项了, 一忙忘了来关闭这个问题了,事实上,你应该让这个当前模式成默认(
当前模式,应该叫上次模式,才对吧)

其它的话, 自从插件改名以来,速度比以前慢多了,响应速度慢, 要是在平板之类的垃圾配置上,浏览器开起来要好一会儿才会插件才会加载完成

有时好电脑上,浏览器工具栏上,插件的图标,点一下,没弹出代理列表的菜单,或是只弹出几个项目, 10个菜单项,只显示2-3项

没其它问题,免费用的,不苛求你一定改进还是其它的, 还是感激你提供梯子辅助工具的
要不是怕你被拉去挖煤,不然我很想建议你提供一个捐助的二维码的

**Comment by ugksoft** [comment]
叔啊,不要么敏感,我不是来钓鱼的,苏匪去死
