### ISSUE TITLE
无法批量代理cloudfront.net，只能一个一个的添加

### ISSUE THREAD

**Issue by freewind** [FelisCatus/SwitchyOmega#1653]
`cloudfront.net`资源的域名一般有4级，switchyomega每次提醒我添加的rule形式如下：

```
*.d6vtbcy3ong79.cloudfront.net
```

![image](https://user-images.githubusercontent.com/333781/46932197-28488500-d081-11e8-9d26-cebda28c8d5e.png)

为了避免每次添加，我自己加上了：

```
*.cloudfront.net
*.*.cloudfront.net
```

但是都不起作用，每次还是会提示有新的需要添加，非常麻烦。我想了解一下你们是否考虑到了多级域名的情况并做了正确的处理？

**Comment by almas1992** [comment]
我也遇到了这种情况，明明添加了，设置里也显示有添加，可还是不起作用

**Comment by FelisCatus** [comment]
`*.cloudfront.net` 会做正确的事情，匹配所有多级别的域名。

然而，就算添加了，如果由于网络或者代理服务器原因仍然会提示在“未能加载的资源”列表下，此时不用进行任何操作。可以试试看刷新页面之类的。

**Comment by freewind** [comment]
这个issue都没有确认一下就关闭了？这个问题从几个月前开始使用就存在，如果说刷新页面有用的话，那么已经刷新几千次了，也没见起作用啊

**Comment by 123wuyu** [comment]
失效了

**Comment by AnyWAT** [comment]
如是 Socks5:1080代理，试试几乎不见“未加载资源”的白名单 https://github.com/MatcherAny/whitelist.pac

**Comment by celeron533** [comment]
![image](https://user-images.githubusercontent.com/3608762/49653986-8c7c3980-fa71-11e8-8122-cc2e4965214b.png)
![image](https://user-images.githubusercontent.com/3608762/49653994-94d47480-fa71-11e8-894a-f842b2baae92.png)

我这边没有问题（那个测试地址和代理服务器是假的，所以肯定没有页面）
