### ISSUE TITLE
有没方法将GET和POST分开？

### ISSUE THREAD

**Issue by ztjal** [FelisCatus/SwitchyOmega#1654]
GET的时候用这个代理，POST的时候用另一个代理。
因为GET的时候想经过一个有缓存的代理，POST的时候就没必要了。

**Comment by ugksoft** [comment]
一般不需要这样的需求吧,你什么应用啊,什么网啊, 举个例子,大家也好想想你这个是什么奇怪的用途,
如果只是临时要求GET不缓存,你可以F12以后, 把disable cache关掉, 然后F12不要关掉
不过,远端cdn,cacheXX之类的方式缓冲,你就没办法了,现在基本上只能花钱向(比如找cdn的小伙,让他帮忙查一下上级ip)找到真IP,然后,修改hosts表,强制给真IP提交数据方式

我到更希望有一个firefox上 hack插件, 可以自己POST 数据包, 现在偶尔需要时,只能用burp,还要装java这垃圾货不说,不管java还是burp,跑起来也真慢

**Comment by ztjal** [comment]
当前是所有连接至一个nginx作静态缓存代理，但POST时实在没必要走nginx，直接连接更好。
就这样，没什么大事。

**Comment by celeron533** [comment]
PAC没有这样的功能

**Comment by FelisCatus** [comment]
我可以确认 PAC 没有这样的功能。  Firefox 上倒是有可能做，不过我觉得做一个用例不广，而且不同浏览器上不一致的功能有点太坑，还是放弃了。另外自己做一个扩展， POST 的时候返回直接连接，然后其他情况交给下一个扩展来解决，倒是可行……
