### ISSUE TITLE
Using 'https://' in the server address causes the proxy to silently fail and use the system proxy

### ISSUE THREAD

**Issue by scottvallanced2d** [FelisCatus/SwitchyOmega#1655]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Mac OSX 10.13.6
Chrome 69.0.3497.100

### Problem description / 问题描述
When using a HTTPS proxy putting 'https://' in the server address causes the proxy to silently fail and use the system proxy instead.

#### Steps to reproduce issue / 重现错误所需步骤

Use a HTTPS proxy. Enter the server address with a prepended 'https://'

#### Expected behavior / 期望发生的情况

The configured proxy is used.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

The configured proxy is not used, but no errors are displayed and the proxy icon for the configured proxy is shown as active.

**Comment by FelisCatus** [comment]
I believe you've hit https://github.com/FelisCatus/SwitchyOmega/wiki/Chromium-Full-URL-Limitation

The tracking bug to update the colors, etc. to match what actually happened is tracked in #972.
