### ISSUE TITLE
on ubuntu 18.04: "extension blocked by administrator"

### ISSUE THREAD

**Issue by cytar** [FelisCatus/SwitchyOmega#1657]
Hello,

i'm unable to use the extension anymore, (always disabled)
And when trying to reinstall from chrome webstore:
Proxy SwitchyOmega (extension ID "padekgcemlokbadohgkifijomclgjgif") is blocked by the administrator.

**Comment by hajnalmt** [comment]
It was the google chrome administrators who shut it off :(
