### ISSUE TITLE
可否自定义服务器显示位置的排序功能

### ISSUE THREAD

**Issue by issuessss** [FelisCatus/SwitchyOmega#1659]
可否对服务器自定义排序,按照我排序的方式显示.
因为服务器太多,Switch Profile显示在最下面, 查获点击都比较麻烦.
目前来看,感觉显示顺序是Proxy Profile,Virtual Profile, Switch Profile.
只有同类的是可以通过改名字来排序.
可否只按名字来排序? 
或者按照Switch Profile>Virtual Profile>Proxy Profile顺序来显示?

SwitchyOmega 2.5.20

**Comment by AnyWAT** [comment]
😜代理服务器名称前按你想要的排序，以序号开始。。。如
1 WuJie
2 GoGo
。。。
不就打破了原来的（按字母）排序：
GoGo
WuJie
。。。

**Comment by AnyWAT** [comment]
代理服务器、自动切换模式均可分别合并同类项：代理协议及端口一致者，可命名（名称如何？）为一种代理服务器或自动切换模式，减少。。。
