### ISSUE TITLE
自动切换代理 对有些网站（无需代理但设置了代理）没切换到代理模式

### ISSUE THREAD

**Issue by me2** [FelisCatus/SwitchyOmega#166]
类似twitter等本身需要代理才能访问的地址没问题，但对有些无代理也能访问的网站，虽然设置好启用代理模式，鼠标移动到SO图标（自动模式）上也看到对该网站启用了代理，但实际没启用，还是直接访问了。

先是访问的效果感觉没变化，然后去查看代理的流量显示，发觉实际没启作用。

**Comment by FelisCatus** [comment]
请告知设置的情况，以及需要具体访问什么网站。

**Comment by me2** [comment]
我的情景模式有3个，antiAD、us和自动切换，其中的us是我的shadowsocks代理。（图1）
[URL=http://www.imagebam.com/image/b97532379634485][IMG]http://thumbnails109.imagebam.com/37964/b97532379634485.jpg[/IMG][/URL] 

经常遇到一楼情况的网站有kickass.so和www.twitch.tv等，这两个网站添加到自动切换的设置是：域名通配符 -  条件设置是*.kickass.so和www.twitch.tv，平时SO使用自动切换模式。

默认设置为自动切换模式的时候，访问kickass.so（这网站直接访问偶尔能开偶尔不能直接开）会跳转到www.dnserror.cn。但如果先选为US代理访问，等页面打开正常以后再改回自动切换模式，然后无论在当页怎么操作都能正常代理访问。而且鼠标移动到chrome的SO图标也会正常显示为(图2）：
SwitchyOmega::自动切换
*.kickass.so => us
SOCKS5 127.0.0.1:1081
[URL=http://www.imagebam.com/image/3f9886379634489][IMG]http://thumbnails111.imagebam.com/37964/3f9886379634489.jpg[/IMG][/URL] 

访问http://www.twitch.tv/的时候，大部分时候工作正常，用着没改任何设置，偶尔发觉视频很慢，本机看不出问题，远程到服务器看ss的流量，发觉流量没走。这时候如果本机类似上面一样切换一下SO从US再切回自动代理模式，流量就又开始走了。

再次感谢，插件非常好用，辛苦了。

**Comment by FelisCatus** [comment]
非常感谢您详细的报告。这个问题可能是由于生成PAC和匹配不一致导致的。建议在自动切换模式下（图1的那个界面），点击右上角导出PAC按钮，并将结果上传到这里。我看看是否是这个问题。

**Comment by FelisCatus** [comment]
此外，在不能正常访问时，请保持自动切换模式（不要来回切换），然后打开 `chrome://net-internals/#proxy`，并将内容复制到这里。

**Comment by me2** [comment]
最近http://kickass.so/一直访问正常，想出问题来反馈都不能，咳。等再现问题的时候我回来反馈的。

**Comment by FelisCatus** [comment]
没事，我这边也先调试下吧，也许能发现什么。

**Comment by FelisCatus** [comment]
暂时先关闭这个了……如果再次发现问题的话另外开 issue 吧。
