### ISSUE TITLE
不能自动切换

### ISSUE THREAD

**Issue by yeyingaaa** [FelisCatus/SwitchyOmega#1664]
选择auto switch，使用了github上的GFWList，访问google，显示直接连接（PS：同样的配置，昨晚能正常切换，今天重启了系统，就不能切换到代理了，手动切换代理，可以正常访问）

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

**Comment by AnyWAT** [comment]
😂显示直接连接且不能访问，左键点击 SwitchyOmega 图标——（底部的）选项——（左侧）情景模式：auto switch——改“直接连接且不能访问”的那行从“直接连接”到“XXX代理”——（左下底部）应用选项

**Comment by yeyingaaa** [comment]
谢谢小哥哥，你真棒

**Comment by AnyWAT** [comment]
更快：右键点击 SwitchyOmega 图标——选项

**Comment by yeyingaaa** [comment]
小哥哥，啥都没变，今天又好了，哈哈哈哈

> 更快：右键点击 SwitchyOmega 图标——选项
