### ISSUE TITLE
[Feature Request] 代理继承

### ISSUE THREAD

**Issue by RedTailBullet** [FelisCatus/SwitchyOmega#1669]
在autoswitch模式下，当设置某一网站走某个代理后，这个网站的下属（后续）链接仍然走URL对应模式。

我是想能不能在某一网站走代理后，这个网站的后续请求也走代理。

我的想法是DOM构建完成后，扫描网页上的链接并添加到一个临时列表。或者对发出的请求进行拦截。不知道能不能做到。

**Comment by FelisCatus** [comment]
由于[PAC限制](https://github.com/FelisCatus/SwitchyOmega/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%AF%B7%E9%97%AE%E5%8F%AF%E4%BB%A5%E6%94%AF%E6%8C%81%E6%8C%89%E7%85%A7%E7%AA%97%E5%8F%A3%E6%88%96%E8%80%85%E6%A0%87%E7%AD%BE%E9%A1%B5%E6%9D%A5%E5%88%87%E6%8D%A2%E4%BB%A3%E7%90%86%E5%90%97)，此功能无法实现。
