### ISSUE TITLE
不同场景下按钮的显示区分度不够大

### ISSUE THREAD

**Issue by lilymarcus** [FelisCatus/SwitchyOmega#167]
比如，使用自动模式，或者指定使用代理模式，或者自动模式时通过了代理或者没通过代理，这几种情况下按钮的显示区分度太小，不是很直观。

switchysharp的图标相对来说倒更直观一点。

SwitchyOmega 2.2.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
见 #107
