### ISSUE TITLE
和shadowsocks冲突

### ISSUE THREAD

**Issue by ttbadr** [FelisCatus/SwitchyOmega#1671]
装了ss翻墙，自动切换配置里默认情景模式是直连，直连模式的流量不走ss，只有选择系统代理才能走ss，自动切换中选择情景模式里能否加上系统代理的选项？

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

**Comment by celeron533** [comment]
#1585
