### ISSUE TITLE
feature: a log for connections error WITH error codes

### ISSUE THREAD

**Issue by rezad1393** [FelisCatus/SwitchyOmega#1675]
can you add this so we can see the actual connection errors for failed connections in a log?

**Comment by FelisCatus** [comment]
SwitchyOmega is not the best tool to *debug* requests. I'd recommend using the Chrome Developer Tool (F12 on Windows/Linux) under the Network tab. If you want a full list of all network events happening across Chrome, you can also try `chrome://network`. There is no need for SwitchyOmega to reinvent the wheel.

**Comment by rezad1393** [comment]
I meant passive error collection instead of active one.
so that the user can see all the connections that failed with errors maybe in a log.
