### ISSUE TITLE
可配置忽略某些资源无法请求的提示

### ISSUE THREAD

**Issue by cn-src** [FelisCatus/SwitchyOmega#1679]
比如用某些广告过滤工具，其阻止了 google-analytics.com 下的 js 分析器，SwitchyOmega 会有数字提示，我想忽略这种提示，这些追踪 js 即便不加载也不影响正常使用。

因此希望能有提示忽略的自定义配置。

SwitchyOmega 2.5.20
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36

**Comment by cn-src** [comment]
非浏览器插件性质的广告过滤器，有类似防火墙的功能，所以会有这种情况存在。

**Comment by FelisCatus** [comment]
了解，合并到 #1674.
