### ISSUE TITLE
是否能支持傲游浏览器

### ISSUE THREAD

**Issue by 2270995274** [FelisCatus/SwitchyOmega#1680]
### Browser version & OS version / 浏览器名称、版本及操作系统版本
Maxthon Version: 5.2.5.4000
OS: 6.1.7601.Service Pack 1
IE: 8.0.7601.24000

**Comment by AnyWAT** [comment]
貌似不支持😂 
https://blog.mimvp.com/article/21108.html https://cdn-blog.mimvp.com/wp-content/uploads/2017/01/liu-lan-qi-she-zhi-dai-li-cha-jian-shang-wang-de-tu-wen-jiao-cheng-09.png
