### ISSUE TITLE
能不能对“由于网络原因而未加载的资源 ”自动启用代理？

### ISSUE THREAD

**Issue by wanglongbiao** [FelisCatus/SwitchyOmega#1681]
我一般是用自动切换模式，有时候某个网站会出现“由于网络原因而未加载的资源 ”，这时候把未加载的资源选择使用代理就可以了
我想问下，能不能自动化这个操作？

**Comment by kookpua** [comment]
我遇到过有些国内资源被自动代理了 加载不了  这个时候你怎么切换成直连？

**Comment by FelisCatus** [comment]
见 #550.
