### ISSUE TITLE
在QQ浏览器里，选择直接连接，也会通过IE的代理设置进行连接

### ISSUE THREAD

**Issue by qqgmail** [FelisCatus/SwitchyOmega#1682]
在QQ浏览器里，选择直接连接，也会通过IE的代理设置进行连接
这个直接连接能真的直接连接吗，不要任何代理

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.26 Safari/537.36 Core/1.63.5221.400 QQBrowser/10.0.1125.400

**Comment by celeron533** [comment]
可能是QQ浏览器自身的实现和chrome不太一样

**Comment by FelisCatus** [comment]
首先， QQ 浏览器并不在支持范围内，如果碰巧能用或者碰巧不能用，那我也没什么办法。

倒是可以试试看 `chrome://net-internals/#proxy` 然后看看页面上写的是否是 DIRECT 之类的。如果不是，我怀疑是扩展冲突，试试看禁用其他扩展。如果是 DIRECT 但是还是不能用，请向您的浏览器开发者反馈。
