### ISSUE TITLE
There seems to be a conflict with phpmyadmin

### ISSUE THREAD

**Issue by Elypha** [FelisCatus/SwitchyOmega#1683]
Hi,

I searched but did not find some problems related to this. So I tried to post this as an issue.

When I login to my phpmyadmin page, an error occurred which read 

> Failed to set session cookie. Maybe you are using HTTP instead of HTTPS to access phpMyAdmin.

My web has a strict (full-site) SSL and I am right visiting a https url. The cookie on that page is enabled in Chrome. However, that phpmyadmin page works well on Edge. Then I tried the Private Browsing mode on Chrome. Surprisingly it worked. So I turned to check the plugins by disabling them and trying login the page. Finally I found if I disabled SwitchyOmega, I would be able to login to phpmyadmin successfully.
I tried all the modes in SwitchyOmega including No-proxy, System-proxy, Force-proxy, etc, and they didn't work. The only effective way is to disable it.

This is not enough to say the problem is in SwitchyOmega. As I am using Chrome 72, which could also be the cause but I'm not sure about it. So if you are using Chrome stable and phpmyadmin, maybe you can check it to help the project. Many thanks to you.

This is my web server version:

Database

- Server: Localhost via UNIX socket
- Server type: MySQL
- Server connection: SSL is not being used Documentation
- Server version: 8.0.11 - Source distribution
- Protocol version: 10
- User: root@localhost
- Server charset: UTF-8 Unicode (utf8)

Web

- nginx/1.14.1
- Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id:
- PHP extension: mysqli curl mbstring
- PHP version: 7.2.6

phpmyadmin

- Version information: 4.8.3

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3620.0 Safari/537.36

**Comment by Elypha** [comment]
I should have provided with some logs, sorry but I don't know how to get those logs. 
Please tell me what do I need to provide and I'll post them as soon as possible.

**Comment by celeron533** [comment]
Please set SwitchyOmega to direct connection and try again

**Comment by Elypha** [comment]
> Please set SwitchyOmega to direct connection and try again

Thanks, it worked. Actually I tried direct connection but it didn't work before I posted this issue. Anyway, as long as it goes well.
