### ISSUE TITLE
使用SwitchyOmega后重启电脑后常用的网站都需要重新登录，这是为什么

### ISSUE THREAD

**Issue by xiaogeneral** [FelisCatus/SwitchyOmega#1687]
**比如常用的github 公司内网的一些网站，使用了该插件后每次重启电脑再访问这些网站时，都需要重新登录，怎么解决呢**

**Comment by xiaogeneral** [comment]
> A10 7300
> 作者：ANTIBili_MC
> https://www.bilibili.com/read/cv268057/
> 出处： bilibili

链接打不开。。。

**Comment by celeron533** [comment]
@QGB please do not post unrelated contents

**Comment by FelisCatus** [comment]
很多网站都会记录上次登录的 IP ，然后 IP 不同就要重新登录了。由于使用代理服务器会改变请求发出的 IP ，所以就会有这种情况。此问题与 SwitchyOmega 无关。
