### ISSUE TITLE
b站子页面打不开

### ISSUE THREAD

**Issue by Hickoo** [FelisCatus/SwitchyOmega#1688]
没开启代理软件的情况下，是自动切换的，b站首页能打开，二级页面打不开比如https://www.bilibili.com/v/technology/

**Comment by FelisCatus** [comment]
感觉是规则的设置问题，如果只使用域名规则（而不是网址规则） `www.bilibili.com` 然后设置其使用直接连接应该就可以了。如果规则是在某个规则列表里，请向规则列表维护者反馈。此问题不是 SwitchyOmega 项目本身的故障。

**Comment by zqhjl** [comment]
> 感觉是规则的设置问题，如果只使用域名规则（而不是网址规则） `www.bilibili.com` 然后设置其使用直接连接应该就可以了。如果规则是在某个规则列表里，请向规则列表维护者反馈。此问题不是 SwitchyOmega 项目本身的故障。

请问我按照提示把*.bilibili.com  *.bilivideo.com  *.yfcdn.net  *.yfp2p.net  *.yfscdn.net  *.bilivideo.cn  *.bilivideo.com都设置成了直接连接规则，但刷新后仍然会报错“failed resources”，点开后却还是上面那些我已经添加进规则里面的地址。这是为什么呢？
