### ISSUE TITLE
怎么设置代码服务器的帐号密码？

### ISSUE THREAD

**Issue by magicismight** [FelisCatus/SwitchyOmega#169]
怎么设置代码服务器的帐号密码？
在选项里面没有找到这一项，代理服务器的高级设置里面也没有

**Comment by FelisCatus** [comment]
代理服务器的用户密码可以在代理情景模式下，填写端口的文本框右侧，点击带有锁图标的按钮来设置。

只支持HTTP/HTTPS类型代理。如果是其他类型代理，那一格会显示为空。

**Comment by magicismight** [comment]
谢谢
就说怎么一直没找到，我用的是socket代理
socket不能填写帐号密码很头疼
还要用xshell再转一次，如果后面能加这样一个功能就太好了

**Comment by FelisCatus** [comment]
@magicismight 由于Chrome的限制，扩展是做不到这个的。如果真的需要可以去 Chrome 那边要。
