### ISSUE TITLE
代理服务器

### ISSUE THREAD

**Issue by vio1etus** [FelisCatus/SwitchyOmega#1692]
我只是想提个意见, 能不能加一个可以设置 指定域名 切换 指定代理结点 的功能呀, 比如: 我访问Pandora, 只在美国有服务, 我想当我每次访问它的时候,可以自动切换到我shadowsocks里面的美国结点

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36

**Comment by celeron533** [comment]
1. switchyomega和shadowsocks是两款完全不同的软件，不存在互操作
2. 你可以开两个shadowsocks，其中一个跑美国节点，然后在switchyomega中吧pandora指向这个

**Comment by AnyWAT** [comment]
貌似 shadowsocks 可以指定某节点
