### ISSUE TITLE
[news] Microsoft's new Edge browser will support Chrome extensions

### ISSUE THREAD

**Issue by celeron533** [FelisCatus/SwitchyOmega#1699]
https://www.engadget.com/2018/12/10/microsoft-edge-chrome-extensions/

Because new Edge will use Chromium as its core.

**Comment by Eskibear** [comment]
Beta version from https://www.microsoftedgeinsider.com/en-us/

Its extension marketplace has only a limited amout of extensions for the moment. Any plan to support the brand-new Edge?
