### ISSUE TITLE
追加192.168.1.0/24到不代理的地址列表

### ISSUE THREAD

**Issue by SOE-121** [FelisCatus/SwitchyOmega#1700]
在任何情况下192.168.1.0/24都应该直连，建议追加到新建代理服务器和通过备份文件恢复选项的不代理的地址列表。
问题的来源是我尝试播放一个局域网视频，文件名中包含"xhamster.com"字样,被gfwlist域名通配符匹配到了代理服务器上面，我以为是nginx的问题，找了半天bug。。

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0

**Comment by celeron533** [comment]
1. PAC 代理机制不会解析域名，所以他看到什么就是什么
2. 看来GFWList的通配符不小心把你的地址匹配了
3. 你可以在SwitchyOmega里面新建一个SwitfhProfile，然后手工添加一条本地规则，剩下的还是走GFWList即可
