### ISSUE TITLE
Rule Name and View All

### ISSUE THREAD

**Issue by ianpgall** [FelisCatus/SwitchyOmega#172]
Love the new version/UI, but there's one thing preventing me from using it. I have a list of server names and IPs that I added to the old version's rules. When I needed to access a server, I looked it up and found the IP, then used the IP in the browser. In the new version, there's no "name" for a rule...just an IP...so I have no way of doing a lookup. Is there any way to get the "name" back into the UI and data? An IP has no meaning to me and I can't find anything in the new UI.

Also, just a suggestion - maybe it would help some people (including me) if there was a way to view all rules from all profiles. It's definitely not hard to look through all my profiles to find the rule needed, but the old version just showed all of them by default. I don't think that's a good idea for this new version to show them all by default, but the ability would be nice.

Thanks!

**Comment by FelisCatus** [comment]
For now, you can write the domain along with the IP in the condition details, like `example.com|93.184.216.34`. This works for both wildcard and regex rules. Doing so also allows you to use domain names in addition to IPs.

I am considering about adding the rule name/description back. But it might be an option which is turned off by default (unless upgrading from SwitchySharp).

For the view of all rules in all profiles... I'm not convinced enough to add that feature. First, people separate rules in different profiles for a reason. For example, if they group rules by category, they only have to look rules up in the relevant profile. For them, separating actually speeds up look-up. What's more, I believe if all rules could fit in one view, they can also fit in one profile. If multiple auto-switch profiles does not work for you, there's nothing that stops you from just using only one, provided that you can also sort rules manually to keep everything in place.

**Comment by FelisCatus** [comment]
Please see #1089 for the proposed rule name UI.
