### ISSUE TITLE
使用 shadowsocks Chrome 打开网页缓慢

### ISSUE THREAD

**Issue by resuly** [FelisCatus/SwitchyOmega#174]
使用SwitchyOmega连接本地的shadowsocks 后经常浏览器卡顿，常常打开一个页面加载数据之前要等好几秒。
起初以为是代理服务器的问题，但是重新安装老版的proxy-switchysharp 问题解决

Chrome版本 39.0.2171.95 m

**Comment by FelisCatus** [comment]
请在新版和旧版运行的时候，分别打开`chrome://net-internals/#proxy`页面（切换后可以刷新一下），然后将分别的结果复制到这里。

**Comment by resuly** [comment]
十分抱歉，经过排查应该是运行商的网络不稳定造成的
