### ISSUE TITLE
卡

### ISSUE THREAD

**Issue by zhangyubaka** [FelisCatus/SwitchyOmega#175]
切换会卡,同时也有时打不开

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
卡的问题目前还在优化。不过“有时打不开”是什么情况？请具体说说。

**Comment by zhangyubaka** [comment]
使用的是Goagent,打开Google会出现时间过长打不开,或者直接白屏,需要刷新才可以

**Comment by FelisCatus** [comment]
看来是 GoAgent 的问题，请到那边项目反馈。

至于卡顿问题，目前还在分析中，可以参考 #162 相关的说明。
