### ISSUE TITLE
Chrome隐身窗口无法使用插件中的HTTPS代理登录信息，需要手动输入

### ISSUE THREAD

**Issue by wx00** [FelisCatus/SwitchyOmega#1751]
### SwitchyOmega version / SwitchyOmega 版本
SwitchyOmega 2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Chrome Version 72.0.3626.109 (Official Build) (64-bit)
Windows 10 Pro 1803 (build 17134.556)

### Problem description / 问题描述
打开隐身窗口后，第一次使用每个需要认证信息的 HTTPS 代理时都需要手动输入登录信息，不关闭隐身窗口的情况下，成功连接以后无需再次输入。

#### Steps to reproduce issue / 重现错误所需步骤
(What did you do? / 你做了什么？)

上次使用隐身窗口用到 HTTPS 代理的时间较远，不确定期间还有什么操作有影响
- Windows 10 1709 ->1803
- Chrome ??(69+) -> 72
- 其他插件的安装/设置变动

#### Expected behavior / 期望发生的情况
使用隐身窗口时和普通窗口一样自动使用已保存的代理信息连接，无需手动输入登录信息。

**Comment by celeron533** [comment]
这应该是chrome的“特性”吧

**Comment by wx00** [comment]
没有仔细看 Chrome 更新历史…虽然报 issue 之前粗略看了一下没看到有啥关于隐身模式代理的变动…

**Comment by AnyWAT** [comment]
使用隐身窗口时和普通窗口一样，使用代理扩展控制代理，勾选代理扩展的”在隐身模式下启用“即可。

**Comment by wx00** [comment]
> 貌似没使用过需要认证信息的 HTTPS 代理。隐身窗口时和普通窗口一样，使用代理扩展控制代理，勾选代理扩展的”在隐身模式下启用“即可。

没有帮助…
我上面已经说了在隐身窗口用了…那肯定是已经选了在隐身模式启用的…

**Comment by wx00** [comment]
新版本（不知道是 Chrome 还是 SwitchyOmega 的更新）已经修复了
