### ISSUE TITLE
SRR连接正常，配置switchyomega代理和端口，一连接就变成下载文件了

### ISSUE THREAD

**Issue by Scheinin** [FelisCatus/SwitchyOmega#1757]
**switchyomega**的代理**地址**和**端口**都配置，一打开需要代理的网址就下载文件，SSR GUI能看见流量的使用

SwitchyOmega 2.5.15
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36

**Comment by FishOrBear** [comment]
清除浏览器缓存了吗

**Comment by Scheinin** [comment]
@FishOrBear 是我把SS和SSR弄错了，谢谢
