### ISSUE TITLE
【CRX_HEADER_INVALID 】Unable to install from the crx file

### ISSUE THREAD

**Issue by hibayesian** [FelisCatus/SwitchyOmega#1766]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
MacOS Mojave 10.14.3
Chrome 73.0.3683.75

#### Steps to reproduce issue / 重现错误所需步骤

1. 从release页面下载了2.5.20版本的crx文件
2. 打开Chrome浏览器，打开扩展程序页面
3. 拖动crx到扩展程序页面
4. 出现CRX_HEADER_INVALID提示，无法正常安装

#### Expected behavior / 期望发生的情况
期望正常安装

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
安装失败

**Comment by Phantom1003** [comment]
So do I!

**Comment by hibayesian** [comment]
> So do I!

把crx文件重命名为.zip，解压出来，将_metadata文件夹重命名为metadata，再在Chrome浏览器的扩展程序界面把整个文件夹打包成crx文件，即可安装。

**Comment by Phantom1003** [comment]
Well... It does not work yet, I install successfully, but after few minutes it notice me it broken... :(

**Comment by hibayesian** [comment]
> Well... It does not work yet, I install successfully, but after few minutes it notice me it broken... :(

是要用Chrome把整个文件夹打包成crx，不是从目录安装。如果选择了从目录安装，当文件夹被移动或删除时，就会提示插件broken。

**Comment by KsRyY** [comment]
Thanks

**Comment by Phantom1003** [comment]
My method is using the old version.... :/

**Comment by siaimes** [comment]
@hibayesian 你好，按照你说的，使用chrome重新打包之后，可以安装，但是无法启动。chrome提示此拓展程序可能已损坏，并且留了一个修复按钮，但是点击之后没有反应。

另外我有2个疑问：
1. 这样安装之后如果能正常使用，那么是否可以自动更新新版本？
2. 我记得17年还是什么时候，我下载crx安装是可以直接安装的，为什么现在却不行了呢？是否因为chrome更新导致不兼容呢？如果是不兼容导致的，是否考虑更新switchyOmega以适应chrome呢？

**Comment by xingkongs** [comment]
我试过了更改后缀名 .zip 然后打包，结果一直奔溃，之后试了几个版本的crx 2.5.11安装成功

**Comment by siaimes** [comment]
我之所以纠结这个是因为代理软件不支持全局代理，所以没有switchyOmega之前浏览器上不了谷歌商店。后来我的解决方案是[以socks5方式启动chrome](https://www.chromium.org/developers/design-documents/network-stack/socks-proxy)，然后安装好switchyOmega！

**Comment by AnyWAT** [comment]
> 代理软件不支持全局代理

貌似只是代理软件没有设置系统代理的功能，知道其代理协议及端口，手动设置即可？

**Comment by siaimes** [comment]
是的，switchyOmega做的就是这个事，但是现在讨论的是没有switchyOmega怎么办。我用trojan做代理，这是一个比较新的代理协议，他只开了一个端口没有全局代理功能。没有switchyOmega之前我找到的最简单的方法就是[以socks5方式启动chrome](https://www.chromium.org/developers/design-documents/network-stack/socks-proxy)，当然也可以用profixier之类的但是没必要了。




> > 代理软件不支持全局代理
> 
> 貌似只是代理软件没有设置系统代理的功能，知道其代理协议及端口，手动设置即可？

**Comment by siaimes** [comment]
> > 代理软件不支持全局代理
> 
> 貌似只是代理软件没有设置系统代理的功能，知道其代理协议及端口，手动设置即可？

是的，switchyOmega做的就是这个事，但是现在讨论的是没有switchyOmega怎么办。我用trojan做代理，这是一个比较新的代理协议，他只开了一个端口没有全局代理功能。没有switchyOmega之前我找到的最简单的方法就是[以socks5方式启动chrome](https://www.chromium.org/developers/design-documents/network-stack/socks-proxy)，当然也可以用profixier之类的但是没必要了。

**Comment by AnyWAT** [comment]
> 现在讨论的是没有switchyOmega怎么办

> 没有switchyOmega之前我找到的最简单的方法就是。。。

> 只是代理软件没有设置系统代理的功能，知道其代理协议及端口，手动设置

简单 or 不简单？

**Comment by nAnderYang** [comment]
> > So do I!
> 
> 把crx文件重命名为.zip，解压出来，将_metadata文件夹重命名为metadata，再在Chrome浏览器的扩展程序界面把整个文件夹打包成crx文件，即可安装。

安装完成 很快就提示 此扩展程序可能已损坏。而不能使用.

**Comment by luweitest** [comment]
> > So do I!
> 
> 把crx文件重命名为.zip，解压出来，将_metadata文件夹重命名为metadata，再在Chrome浏览器的扩展程序界面把整个文件夹打包成crx文件，即可安装。

没用的，重新打包会报另一个crx_required_proof_missing错误。只能用开发者模式，加载解压后的文件夹
