### ISSUE TITLE
I can't upgrade the gfwlist !! Why? Chrome39

### ISSUE THREAD

**Issue by madqxy** [FelisCatus/SwitchyOmega#177]
i upgraded the gfwlist successfully at first time, but it can not work in this week. there is a red tag on the top with the words "下载情景模式数据时出错".

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查代理服务器是否工作正常。如果全局代理模式可以使用，那么可以在全局代理模式下更新规则列表。

**Comment by madqxy** [comment]
还是网络被堵的太厉害了……设置无误，你的方法也尝试还是不行。昨天突然又好了……
