### ISSUE TITLE
socket5 不支持用户名密码

### ISSUE THREAD

**Issue by DLive** [FelisCatus/SwitchyOmega#178]
socket5 不支持用户名密码，
是否可以支持？多谢

**Comment by FelisCatus** [comment]
扩展是没办法给 socks 代理服务器提供用户名密码的，因为 Chrome 本身不支持。如果真的需要可以去 Chrome 那边要。

**Comment by FelisCatus** [comment]
有关 Chrome 不支持 SOCKS5 代理认证的问题，可以参考这里： https://code.google.com/p/chromium/issues/detail?id=256785

**Comment by tldzyx** [comment]
[一个或许能用的方案](https://github.com/FelisCatus/SwitchyOmega/issues/1136#issuecomment-323279609)

**Comment by FelisCatus** [comment]
抱歉，您提出的那个解决方案并不是针对此问题的。具体讨论见那边。
