### ISSUE TITLE
需要重启网页问题

### ISSUE THREAD

**Issue by nncy** [FelisCatus/SwitchyOmega#1789]
请问我现在每访问一个网页。插件就显示，想要访问此网站，需要重新加载此插件。是什么原因呢？

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by celeron533** [comment]
猜测
1. 和其他代理设置扩展冲突
2. 扩展使用非正规途径安装，没有认可的签名，所以没有被浏览器信任

**Comment by nncy** [comment]
您好。确实是冲突问题，我chrome用switch omega,桌面端用proxifer来代理steam。请问这样有什么解决方法吗？

**Comment by celeron533** [comment]
proxifer 工作在浏览器之外，应该不是他的问题

**Comment by nncy** [comment]
嗯。我现在发现虽然omega图标显示需要重启网页，但实际是可以使用的。谢谢。
