### ISSUE TITLE
[功能]希望支持多个规则订阅

### ISSUE THREAD

**Issue by mzhboy** [FelisCatus/SwitchyOmega#179]
有时候gfwlist没有覆盖到某些网址，我就自己弄了个规则，然后推上去。firefox的pan插件允许订阅多个规则，很方便。所以希望SwitchyOmega能够支持订阅多个规则
![default](https://cloud.githubusercontent.com/assets/5281193/5680007/f0121082-9841-11e4-83b3-d033622acdd3.PNG)

**Comment by FelisCatus** [comment]
可以再建立一个自动切换情景模式，然后将那个的默认情景模式设置成旧的自动切换即可，这样就相当于串在一起用了。

**Comment by mzhboy** [comment]
收到，希望您能够把这种用法加入wiki

**Comment by FelisCatus** [comment]
嘛，我可能会考虑把常用的配置场景总结到一篇文章里，不过现在我还没有太多时间。
