### ISSUE TITLE
可以集成到，shadowsocks-chromeapp 里面吗？还是必须配合两个一起使用

### ISSUE THREAD

**Issue by Adgeros** [FelisCatus/SwitchyOmega#1792]

**Comment by celeron533** [comment]
为什么一个代理服务器管理工具一定要和翻墙联系起来呢？

**Comment by Adgeros** [comment]
> 为什么一个代理服务器管理工具一定要和翻墙联系起来呢？

客户想这么用，我也苦恼

**Comment by AnyWAT** [comment]
> 客户想这么用，我也苦恼

貌似XX-Net。。。软件目录下有个 SwitchyOmega 目录，内有：
OmegaOptions.bak
SwitchyOmega.crx
本地安装扩展、导入本地的备份文件以恢复所有选项。

**Comment by Adgeros** [comment]
> > 客户想这么用，我也苦恼
> 
> 貌似XX-Net。。。软件目录下有个 SwitchyOmega 目录，内有：
> OmegaOptions.bak
> SwitchyOmega.crx
> 本地安装扩展、导入本地的备份文件以恢复所有选项。
> 这是楼主的事，没有版主神马事😂

没懂

**Comment by AnyWAT** [comment]
客户想这么用，无非想免除自己下载扩展安装文件并动手设置？

> 本地安装扩展、导入本地的备份文件以恢复所有选项。

当然还得有操作步骤说明文件才完整。

**Comment by Adgeros** [comment]
> 客户想这么用，无非想免除自己在线（下载）安装扩展并动手设置？
> 
> > 本地安装扩展、导入本地的备份文件以恢复所有选项。
> 
> 当然还得有操作步骤说明文件才完整。
> 更省事：连浏览器也一道，解压即用。。。https://github.com/Alvin9999/new-pac/wiki （没有SS版，只有SSR版）
> 
> > 还是必须配合两个一起使用
> 
> 未必，不使用代理扩展也可。https://github.com/shadowsocks/shadowsocks-windows

我就是想把那个代理的抽出来，别的自动代理之类都可以不要
