### ISSUE TITLE
 每次开启chrome，SwitchyOmega都会弹出

### ISSUE THREAD

**Issue by kituo** [FelisCatus/SwitchyOmega#1799]
每次开启chrome，SwitchyOmega都会弹出 ，之前没有出现过这种情况。最近突然出现，重装插件并不能解决问题，求教。

![image](https://user-images.githubusercontent.com/30134945/57152645-a5153380-6e06-11e9-9b20-1e8e457c21ca.png)

**Comment by AnyWAT** [comment]
稀奇古怪（没遭遇😂）。卸载插件——浏览器清理。。。——关闭浏览器（再系统清理）——启动浏览器再安装插件
