### ISSUE TITLE
关于自动切换

### ISSUE THREAD

**Issue by fsaimon** [FelisCatus/SwitchyOmega#180]
第一次用自动切换，发现好像所有的网站都走代理了、、、比如百度什么的，百度IP是我代理的IP，，可是显然百度不该走代理啊、、不知道是不是我设置问题

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2267.0 Safari/537.36

**Comment by FelisCatus** [comment]
既然不知道是不是设置问题、、、那干嘛不上传下设置备份、、或者截个图也好啊、、你光说不能用我怎么帮你啊、、晕

**Comment by fsaimon** [comment]
不好意思
http://pan.baidu.com/s/1k2MHS
这是备份= =（我找了半天没找到怎么在这里上传附件，，，
![image](https://cloud.githubusercontent.com/assets/9132227/5691599/5e5a6ada-990a-11e4-9789-b72893210380.png)
（自动切换基本是默认配置、、、


PS：我觉得图标方面其实做得很好，挺好用，一目了然

**Comment by FelisCatus** [comment]
你默认情景模式设置的也是本地SS啊……如果想默认走直接连接，匹配规则的走代理，那么默认情景模式应该设置成直接连接才对吧。
