### ISSUE TITLE
SwitchyOmega stopped working in Firefox

### ISSUE THREAD

**Issue by noamshan** [FelisCatus/SwitchyOmega#1803]
### Browser version & OS version / 浏览器名称、版本及操作系统版本
Firefox 66.0.3 (64-bit)

### Problem description / 问题描述

SwitchyOmega stopped working in firefox:
![image](https://user-images.githubusercontent.com/20840912/57193073-1ad0ea80-6f40-11e9-8dcb-4accdfd5f5f4.png)

see:
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct

**Comment by Zhang-Junzhi** [comment]
Same problem here. I am using Firefox 60. Mozilla seems to have started add-on signing requirement on all add-ons regardless of which version the user is using.

**Comment by AnyWAT** [comment]
？https://github.com/FelisCatus/SwitchyOmega/issues/1800#issuecomment-489385478

**Comment by Zhang-Junzhi** [comment]
> ？[#1800 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/1800#issuecomment-489385478)

Wow. This helps. I toggled the pref and now the add-on is working. Thanks for sharing.

**Comment by noamshan** [comment]
Turns out it was a firefox bug. Fixed after upgrade to 66.0.4.
