### ISSUE TITLE
建议增加一个“直接返回(reject)”情景模式

### ISSUE THREAD

**Issue by d9394** [FelisCatus/SwitchyOmega#1807]
就是有些网站或URL我不想去访问，此时如果选择proxy和直接访问都会把请求转发过去不太合适，所以建议在switchyomega里增加reject功能，对于此类匹配的URL由switchyomega直接返回404或200状态码让浏览器不再等待该请求

SwitchyOmega 2.5.20
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by celeron533** [comment]
PAC脚本做不到这一点。

**Comment by Phuker** [comment]
可以把这类资源的代理服务器地址设置到127.0.0.1，端口设为一个没有运行服务的端口号，例如 127.0.0.1:0 ，127.0.0.1:2 这种，就会连接失败，起到屏蔽的目的
我这边测试 PAC 也可以用这种方法屏蔽特定资源：

    PROXY 127.0.0.1:0

**Comment by d9394** [comment]
> 
> 
> 可以把这类资源的代理服务器地址设置到127.0.0.1，端口设为一个没有运行服务的端口号，例如 127.0.0.1:0 ，127.0.0.1:2 这种，就会连接失败，起到屏蔽的目的
> 我这边测试 PAC 也可以用这种方法屏蔽特定资源：
> 
> ```
> PROXY 127.0.0.1:0
> ```

是个办法
