### ISSUE TITLE
chrome工具栏菜单显示问题

### ISSUE THREAD

**Issue by newcl** [FelisCatus/SwitchyOmega#181]
点击chrome工具栏上插件的按钮，最顶端的“直接连接”有的时候显示不全，只能显示最下面的一条。

SwitchyOmega 2.2.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
Mac OS X 操作系统下的 Chrome 弹出窗口显示不正常为已知的 Chrome 问题，与本项目无关。
