### ISSUE TITLE
crx离线安装错误chrome 74.0.3729.131 64 bit

### ISSUE THREAD

**Issue by nAnderYang** [FelisCatus/SwitchyOmega#1810]
我重新安装了系统后，没有这个软件我连接不上google。
这下载的文件安装总是提示错误不能被安装。
提示程序包无效“CRX_HEADER_INVALID”.

能否重新编译一个？谢谢

**Comment by elegracer** [comment]
不要用最新的版本，下次新的版本试试

**Comment by nAnderYang** [comment]
我换了个方式 上去市场上下载了

**Comment by kuchaguangjie** [comment]
降版本 到 chrome 71, 可以 安装 本地 .crx 文件.
从这里可以下载 旧版本: https://www.slimjet.com/chrome/google-chrome-old-version.php

**Comment by zipswich** [comment]
Still get "CRX_HEADER_INVALID" with the latest CRX file.
![image](https://user-images.githubusercontent.com/6095671/61476122-4fa6e800-a95a-11e9-85e5-66913e44f5f4.png)
Unable to access the chrome store, and this is the reason to install SwitchyOmega.   Hope an update will fix it.

**Comment by elegracer** [comment]
@zipswich 
Use the second latest version will solve this issue.

**Comment by zipswich** [comment]
Thank you, @elegracer 
I have decided to use system proxy, so I no longer need to configure browser proxy.
