### ISSUE TITLE
Unable to connect to the proxy server

### ISSUE THREAD

**Issue by mockee** [FelisCatus/SwitchyOmega#182]
设置无误，从 SwitchySharp 切换过来后选择 Auto Switch mode 就无法使用了
所有需要走代理的网页提示 `Unable to connect to the proxy server`

SwitchyOmega 2.2.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
请先切换到代理情景模式，检查并截图配置。然后打开 `chrome://net-interals/#proxy` 页面，检查实际使用的代理配置，并将文字复制到这里。

如果代理配置和之前设置的不一样，可能就是升级的时候配置升级错误了。那么请告知之前SS的时候的设置是什么样的，以便修复问题。

**Comment by FelisCatus** [comment]
我要给你们跪了……求一点详细的错误报告就那么难么。这软件配置那么复杂，如果你只是说一句挂了，我怎么知道是哪里怎么挂了啊……

**Comment by mockee** [comment]
@FelisCatus 误会了。前段时间刚好休假，信件堆积比较严重，应该是漏掉了，抱歉今天才看到。

重新卸载安装了下，代理情景模式下 HTTP 默认添加了与 SS 时相同的代理：

![screen shot 2015-01-24 at 17 22 43](https://cloud.githubusercontent.com/assets/176544/5886955/06bd3bca-a3f2-11e4-8361-14e36eb7464e.png)

但无论是使用代理还是 Auto Switch 都会提示 `Unable to connect to the proxy server`。直接使用代理时 `net-internals/#proxy` (`s/interals/internals`) 显示的代理与设置的一致：

![screen shot 2015-01-24 at 17 38 20](https://cloud.githubusercontent.com/assets/176544/5886963/58bdcc28-a3f2-11e4-9052-0a56d7b2b37b.png)

Auto Switch 下 PAC script 比较大，我保存后放到 Dropbox 了：
https://www.dropbox.com/s/ve4bl2u8vlsx0to/auto_switch_proxy_pac.txt?dl=0

另外在 Auto Switch 下利用插件的导出功能导了一份 PAC：
https://www.dropbox.com/s/b47epi3wqjatdcz/OmegaProfile_Auto_Switch.pac?dl=0

希望会有帮助

**Comment by FelisCatus** [comment]
我用配置检查过，无论是代理模式还是自动切换，返回的代理服务器地址是一样的，都是 HTTP `10.8.0.1:8118`。这样的话我推荐检查这个代理服务器是否可以能正常工作（比如，可以试试看 telnet 10.8.0.1 8118）。此外，确定代理服务器是 HTTP 类型，而不是 SOCKS 代理吗？

此外，推荐设置 (default) 一行的代理，而不要设置 `http://` 一行的代理，否则 `https://` 的网址不会走代理。 Scheme 一栏设置的是网址的协议，而不是代理本身的类型。

**Comment by mockee** [comment]
@FelisCatus 只设置 `default` 代理，其他 `use default` 后好了:)
btw, `http://` 一行的代理是从 SS 升级过来后自动填写的

:beers:

**Comment by FelisCatus** [comment]
我准备关闭这个了，升级前后差别比较大，如果没选中 use same proxy 的话升级过的结果不一定是对的……但也没什么好办法。
