### ISSUE TITLE
Feature proposal: SOCKS5 over TLS

### ISSUE THREAD

**Issue by hanayashiki** [FelisCatus/SwitchyOmega#1838]
为了加速翻墙，将 SS 的 server 和 local 分别部署到国外和国内，利用 socks5 连接国内的 local 服务器，满足手机和电脑的连接需求。
但是现在 socks5 出现了能连接某些网站，而不能连接其它一写网站的奇特现象，估计是 GFW 针对 明文的 socks5 进行了域名阻断，而且阻断设备布置到了国内网络。
防止阻断的一个方法就是对 socks5 利用 tls 进行加密。此功能在 ShadowRocket 上已有实现（Socks5 over TLS），但是在 SwitchyOmega 只支持 Socks5。希望能添加支持 tls 传输的功能，非常感谢。

**Comment by celeron533** [comment]
1. switchyomega 只是一款代理服务器切换软件，和翻墙无关。
2. switchyomega 的核心其实是PAC，不支持代理协议的转换。
