### ISSUE TITLE
无法播放该视频文件。(错误代码: 224003)

### ISSUE THREAD

**Issue by hxse** [FelisCatus/SwitchyOmega#1839]
测试链接: https://www.fembed.com/v/2w9m5e4jlv6
测试环境: chrome
用SwitchyOmega来播放就会出现报错
用浏览器自身的代理就能正常播放

**Comment by AnyWAT** [comment]
> 用SwitchyOmega来播放就会出现报错

SwitchyOmega 只是代理扩展，控制是否、怎样使用代理，本身并无代理服务器。此说法貌似不太。。。

> 用浏览器自身的代理就能正常播放

貌似此说法也不合适。（禁用SwitchyOmega 的前提下）如代理软件未运行、或运行了但未启用系统全局代理，不如说直接连接更合适；如运行了且启用了系统全局代理，则系统代理才合适。“直接连接”与“系统代理”均在SwitchyOmega 内有选项。

> 测试链接: https://www.fembed.com/v/2w9m5e4jlv6

经测试，直接连接可正常，或SwitchyOmega 选用自动代理，且 *.fembed.com *.fvs.io *.hlsmp4.com 三者走直接连接也正常。（如果有扩展 HTTPS Everywhere 貌似得禁用才正常。）

> 无法播放该视频文件。(错误代码: 224003) 

貌似与SwitchyOmega 无关，只是没能正确使用。。。

![image](https://user-images.githubusercontent.com/37962734/59935235-f2fdfd80-947f-11e9-86e0-5581e703570f.png)
