### ISSUE TITLE
关于“自动切换”的一些UI问题

### ISSUE THREAD

**Issue by xloger** [FelisCatus/SwitchyOmega#184]
前几天刚换成SwitchyOmega的，用的感觉不错。但是自动代理模式里我很难根据图标判断当前网页是否处于代理之中，刚刚比较了一下发现虽然有两个图标，但很难辨认，希望作者能换个更让人舒适的图标。

SwitchyOmega 2.2.11
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by xloger** [comment]
Should I speak English ?

**Comment by xloger** [comment]
=。=刚刚看了下反馈表，已经有人提了。。。
不过我觉得没必要弄复杂，比如自动模式我觉得直接用那个循环的图标就好，然后自动模式但并未代理就是灰色的，这样就很好了。

**Comment by FelisCatus** [comment]
这个问题还是在 #107 集中讨论吧。
