### ISSUE TITLE
Safari版本

### ISSUE THREAD

**Issue by wangsijie** [FelisCatus/SwitchyOmega#186]
期待什么时候能考虑出一个Safari版本的。

SwitchyOmega 2.2.12
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
经过一番调查（谷歌），我发现 Safari 没有自己的代理设置，也就是说是使用系统代理设置。

而系统代理设置不太可能做，因为需要原生代码。我先准备关闭这个了。

**Comment by Jeff1995** [comment]
Safari 14貌似支持了直接移植chrome/firefox插件，不知道有没有开放代理api

**Comment by SuvanCheng** [comment]
但，很期待
