### ISSUE TITLE
切换代理的建议

### ISSUE THREAD

**Issue by subgb** [FelisCatus/SwitchyOmega#187]
现在的切换还是不够方便，

我预设了六七个情景模式，常用只是其中的2个外加1个自动切换，
我可以在选项里开启 [快速切换] 功能，虽然切换选中的情景时很快速，但此时若想使用其它情景时就很麻烦了。

还有是使用使用键盘快捷键打开SwitchyOmega菜单，然后用鼠标移过去点（好麻烦），或者使用键盘的上下箭头在一堆情景中选择（一般要眼睛看着选到第几个了才行，很难盲选）。

我想说，可不可以在菜单弹出后，获取到键盘按键？比如情景从上到下自动编号1到9（另外设置里请增加情景模式的排序），9之后就不管了，按对应数字自动切换情景。按数字0就直接连接，字母s就使用系统代理。

SwitchyOmega 2.2.12
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
v2.2.13 增加了很多键盘快捷键，弹出菜单下按 ? (问号)键查看帮助。0,S,1-9都按 @subgb 的方案设定了。

关于排序问题，同种类型的情景模式是按字母顺序排的，所以不妨改改名字，在前面加点字母或数字前缀什么的。
