### ISSUE TITLE
白名单模式下颜色问题

### ISSUE THREAD

**Issue by pzh200707** [FelisCatus/SwitchyOmega#1879]
白名单模式
![image](https://user-images.githubusercontent.com/26104496/63702896-7b22c980-c85a-11e9-98c6-f0faec3f4834.png)
无论国内网页还是国外网页，均为内黄外绿，百度显示内地ip，谷歌为香港ip，靠外环颜色无法区别有没有走代理。

希望解决下颜色问题

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36

**Comment by pzh200707** [comment]
发现该问题为pac情景模式+自动切换模式会出现。
已换成自动切换模式+规则列表设置，问题已解决

**Comment by laoasl** [comment]
> 发现该问题为pac情景模式+自动切换模式会出现。
> 已换成自动切换模式+规则列表设置，问题已解决

可是白名单貌似只能用pac , 咋办?

**Comment by pzh200707** [comment]
> > 发现该问题为pac情景模式+自动切换模式会出现。
> > 已换成自动切换模式+规则列表设置，问题已解决
> 
> 可是白名单貌似只能用pac , 咋办?

可使用https://github.com/neko-dev/gfw_whitelist
