### ISSUE TITLE
Refresh Current Tab not working on Profile change

### ISSUE THREAD

**Issue by krgaurav94** [FelisCatus/SwitchyOmega#188]
I had been using proxy Switchy Sharp for quite a long time, recently I upgraded to Omega. I set the option to refresh current tab on profile change and applied the changes but the page is not reloading on profile change. I restarted the chrome also still no effect.
![screenshot from 2015-01-12 14 01 06](https://cloud.githubusercontent.com/assets/4548181/5700408/d4910dda-9a63-11e4-8d7b-b41c2867f895.png)

SwitchyOmega 2.2.12
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
Another issue caused by variable shadowing. Sorry for my carelessness.

The fix should be released with the next release.

**Comment by FelisCatus** [comment]
v2.2.13 is released with the fix.
