### ISSUE TITLE
SwitchyOmega 下拉菜单显示不正常

### ISSUE THREAD

**Issue by edwinhuish** [FelisCatus/SwitchyOmega#1880]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Chrome 64bit 76.0.3809.100
Win10 1903 ( OS 内部版本 18950.1000 )

### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

无法点击chrome的 SwitchyOmega 弹出的下拉菜单不正常。无法显示已经设置的规则。 当遇到无法加载的资源也没有一键添加规则的菜单按键。

如下图。
![image](https://user-images.githubusercontent.com/5207925/63737448-0a5eca00-c8b9-11e9-8f77-c3596b9416f5.png)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

错误出现所需步骤未知。

一直都是正常使用，从一开始设置好后基本没有怎么再去动过它，除了提示有资源无法加载时，点击加入规则。

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

尝试过多次卸载，重新从 Google 网上应用店安装，重启电脑，问题依旧。

**Comment by edwinhuish** [comment]
使用 Chrome 的开发者模式加载版本 2.5.19 后正常

**Comment by edwinhuish** [comment]
打开几个页面后，又不正常了，出现同样的问题，无论时什么网站，甚至空白页，也无法正常显示下拉菜单。

扩展程序页面显示这些错误：

![image](https://user-images.githubusercontent.com/5207925/63738310-ee105c80-c8bb-11e9-8681-3099c562882a.png)

**Comment by paulzhn** [comment]
+1，有同样的问题

**Comment by jackton** [comment]
+1 一样的问题

**Comment by edwinhuish** [comment]
@paulzhn @jackton  已找到解决方法， 只要将下面这个 GFWLIST 链接清空后就能恢复正常，具体原因未知。。

![image](https://user-images.githubusercontent.com/5207925/64007696-37c0a780-cb47-11e9-9a8c-8cda1206dfe8.png)

**Comment by asxsa** [comment]
+1，有同样的问题，最近才出现的

**Comment by edwinhuish** [comment]
@asxsa 有没有尝试我的解决方法？我这边删除规则列表网址就能恢复正常。

**Comment by xdxiaodong** [comment]
@edwinhuish 我也遇到了同样的问题，但是你删除了规则列表的话不是就没法使用自动切换了吗

**Comment by xdxiaodong** [comment]
@edwinhuish 我遇到了同样的问题，但是尝试了你说的删除规则列表网址之后，问题还是没解决。

**Comment by edwinhuish** [comment]
@xdxiaodong 我这边删除了规则列表的网址之后，倒是大部分情况下都正常了，偶尔一两个网站还是会出现这个问题。

**Comment by Chenastron** [comment]
没有用

**Comment by xiaolugu** [comment]
+1，chrome83以来的问题

**Comment by CCCAUCHY** [comment]
> @paulzhn @jackton 已找到解决方法， 只要将下面这个 GFWLIST 链接清空后就能恢复正常，具体原因未知。。
> 
> ![image](https://user-images.githubusercontent.com/5207925/64007696-37c0a780-cb47-11e9-9a8c-8cda1206dfe8.png)

这哪个界面?

**Comment by AnyWAT** [comment]
情景模式——Auto Switch
