### ISSUE TITLE
用css写了个图标供参考

### ISSUE THREAD

**Issue by subgb** [FelisCatus/SwitchyOmega#189]
新版本用下来，感觉图标很难理解当前使用模式，我觉得主要原因是内圈和外圈的颜色基本占据相同比重，没有重点，容易搞混内外圈颜色的含义。

我的想法是自动切换这个状态的可以想象成一个背景色，占很少的空间，而把结果颜色作为前景色占据主要部分。

还有内外圈之间最好留一条透明缝隙，这样当两个颜色较接近时不至于糊成一团。

我拿css做了几个图标，可以参考下
![111](https://cloud.githubusercontent.com/assets/612446/5705638/cabd36f6-9ab5-11e4-9cdc-b578976b0013.PNG)

几个风格只是边框大小的区别而已

完整页面的链接：
https://rawgit.com/subgb/065d85b973d32c2a1a2a/raw/65ec8c213b1cae18159ecaa2ce365f49500a9059/gistfile1.html

**Comment by FelisCatus** [comment]
图标问题统一到 #107 讨论吧。
