### ISSUE TITLE
Google Chrome 76, 77出现跳过pac bug

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#1893]
1，最近经常出现pac被完全忽略--SwitchyOmega在pac模式下（最容易重现bug，全局也会出现，但几率小）Chrome 直连网站的情况，查log查不出来
2，找到相关解释：
https://bugs.chromium.org/p/chromium/issues/detail?id=839566#c40

至今Version 77.0.3865.90 (Official Build) (64-bit) 
还频繁出现pac被跳过直连现象。

**Comment by Justsoos** [comment]
懒得去给官僚chrome开发者们提意见了，累了。发到这里是个线索作用。close了

**Comment by celeron533** [comment]
我这边也时常出现，心累。只能手动切换一下代理再切回来。
