### ISSUE TITLE
PAC优先级问题，会导致的困扰

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#1896]
https://github.com/shadowsocks/shadowsocks-windows/issues/2047
这个 issue 提到了，这几天也遇到这个问题。即：

- pac文件遇到相同规则定义的地址，如果存在@@，会忽略||，直接走直连
- 在pac文件头部加入的||会被尾部的@@同地址规则覆盖

这对于相当大的pac文件来说，维护和处理逻辑都有点负担。
也就是说：

- 如果你要增加一个走代理的||网站，先要**全文正则**过滤找到同地址@@并删除它
- 而相反，你要释放一个要直连网站@@，不需要考虑pac中是否存在相同规则，随便加在pac文件任何位置都可以

这对于很多设置 user-rule 的软件，其实只是简单把 user-rule 放到pac文件rules顶部来说，是一个逻辑陷阱。
嗯，我是被某几个软件陷阱了才发现这个问题。

**Comment by celeron533** [comment]
这个是PAC自己内部的javascript的逻辑问题，和switchy omega没有关系

**Comment by Justsoos** [comment]
直觉上pac既然是js，应该可以内置一个列表优先级/正则过滤，重建唯一uri dict 的小代码段的。
方便在pac文件最上面直接修改 user define rules
只是对这方面没啥研究。

**Comment by celeron533** [comment]
@Justsoos 
曾经的逻辑是把内置的网址列表和自定义的列表放在一起，然后交由后续的逻辑函数进行匹配。悲剧的是如果有相反的条目出现（比如内置列表直连abc.com但是自定义列表要求代理abc.com），具体选用那一条规则，取决于判断逻辑的实现（可能：列表规则行出现的先后顺序，列表规则在二次处理后进入dictionary, hashtable的顺序，不重复域名list覆盖最后一次读取记录等）
比较理想的实现方式是类似于iptables的分段判断：
对于一个地址，先在自定义列表中使用判断逻辑，如果有命中（代理或不代理），返回结果。若未命中，则去内置列表进行二判。
