### ISSUE TITLE
SwitchyOmega只能访问谷歌，不能访问其他网站。

### ISSUE THREAD

**Issue by cf7180560** [FelisCatus/SwitchyOmega#191]
我下载的SwitchyOmega的版本为2.2.13，SwitchyOmega只能访问谷歌，不能访问其他网站。

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或代理软件问题与本项目无关。如果是 GoAgent 等项目，请去对应项目反馈。
