### ISSUE TITLE
大文件通过代理自动就断了

### ISSUE THREAD

**Issue by damnhe** [FelisCatus/SwitchyOmega#193]
下载44K左右连接被重置，用FireFox的代理没有这个问题 
用的socks5 proxy

环境 Fedora21 + chrome Version 39.0.2171.95 (64-bit)

**Comment by FelisCatus** [comment]
代理服务器问题或 Chrome 问题与本项目无关。

不过既然 Firefox 行的话……那么应该是和 Chrome 的网络实现有关了吧，不过我对这些也不明白啦。可以去 chromium 项目问问看。
