### ISSUE TITLE
https代理不会带上Proxy-Authorization

### ISSUE THREAD

**Issue by xxxsen** [FelisCatus/SwitchyOmega#1936]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
浏览器版本 版本 78.0.3904.108（正式版本） （64 位）
操作系统 debian 10

### Problem description / 问题描述
配置了https代理的用户名密码后, 浏览器发起请求并不会带上 Proxy-Authorization 请求头

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. 填写https代理的用户名密码选项
2. 设置某个页面的代理为https代理
3. 刷新页面

#### Expected behavior / 期望发生的情况
请求头中带上Proxy-Authorization

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
并没有带上相应的请求头

**Comment by zxc111** [comment]
参考这个 issue [https://github.com/FelisCatus/SwitchyOmega/issues/560](url)
当 server 返回 407 之后就会带上Proxy-Authorization

**Comment by xxxsen** [comment]
很多时候https代理都不想别人知道这是一个代理，所以有没办法配置之后就直接带上，而不是等407呢？

**Comment by zxc111** [comment]
目前来看至少SwitchyOmega不行，或者有什么特别的技巧我没有掌握....
可以尝试修改下源码

**Comment by wzshiming** [comment]
server 返回 407 还是一样, 后续不会继续请求.

**Comment by erichuang1994** [comment]
> server 返回 407 还是一样, 后续不会继续请求.
> 代理是有效的, 我设置 https_proxy使用 curl
> chrome 和 firefox 都一样

+1
