### ISSUE TITLE
做一个彻底的重置选项

### ISSUE THREAD

**Issue by aizhouyi** [FelisCatus/SwitchyOmega#1938]

**Comment by aizhouyi** [comment]
![Screenshot_20191211_193558](https://user-images.githubusercontent.com/57656655/70618634-50fce800-1c4e-11ea-9523-b75bad88df54.png)
就是这样的，有什么好办法吗

**Comment by yfdyh000** [comment]
你说的是浏览器的自动填表历史
https://support.google.com/chrome/answer/142893

**Comment by aizhouyi** [comment]
哇，谢谢，67版本之后的表单这个已经砍掉了，我找了大半天找到了，非常感谢你的回答。谢谢！！！
