### ISSUE TITLE
can't download pac

### ISSUE THREAD

**Issue by silenthk** [FelisCatus/SwitchyOmega#194]
无法导出PAC文件

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
究竟是下载（从URL更新），还是导出（从自动切换导出PAC）？

**Comment by silenthk** [comment]
情景模式，导出PAC文件，只有在开启goagent，开启swithcygmega代理模式才能下载，谢谢。

--------- 原始邮件信息 ---------
发件人: "FelisCatus/SwitchyOmega" <reply@reply.github.com>
收件人: "FelisCatus/SwitchyOmega" <SwitchyOmega@noreply.github.com>
主题: Re: [SwitchyOmega] can't download pac (#194)
日期: 2015/01/14 17:51:59 (Wed)

究竟是下载（从URL更新），还是导出（从自动切换导出PAC）？

**Comment by FelisCatus** [comment]
意思是那个导入/导出里那个按钮？那个是导出当前情景模式的PAC的，在直接连接模式显然什么都导不出。建议使用每个情景模式右上角的导出PAC按钮。
