### ISSUE TITLE
将*.gstatic.com添加到切换规则后，无效

### ISSUE THREAD

**Issue by hitrust** [FelisCatus/SwitchyOmega#195]
将*.gstatic.com添加到切换规则后，该csi.gstatic.com无效，

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
请截图自动切换的设置界面。

**Comment by hitrust** [comment]
![default](https://cloud.githubusercontent.com/assets/3360631/5738116/7257883a-9c23-11e4-9422-d1ccd4dffe97.JPG)

**Comment by FelisCatus** [comment]
看着不像是有问题啊，点“导出PAC”试试看，然后把结果上传到这里。（可以先把规则列表规则那里的勾去掉再导出，这样结果文件小一些）。

**Comment by hitrust** [comment]
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+\u81ea\u52a8\u5207\u6362", {
    "+\u81ea\u52a8\u5207\u6362": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)google\.com\./.test(host)) return "+GoAgent";
        if (/(?:^|\.)google.*\.com$/.test(host)) return "+GoAgent";
        if (/(?:^|\.)sourceforge\.net$/.test(host)) return "+GoAgent";
        if (/(?:^|\.)sf\.net$/.test(host)) return "+GoAgent";
        if (/(?:^|\.)wikipedia\.org$/.test(host)) return "+GoAgent";
        if (/(?:^|\.)google-analytics\.com$/.test(host)) return "+GoAgent";
        if (/(?:^|\.)gstatic\.com$/.test(host)) return "+GoAgent";
        return "DIRECT";
    },
    "+GoAgent": function(url, host, scheme) {
        "use strict";
        if (host === "[::1]" || host === "localhost" || host === "127.0.0.1") return "DIRECT";
        return "PROXY 127.0.0.1:8087";
    }
});

**Comment by FelisCatus** [comment]
PAC 文件应该没问题，刚才测试过 gstatic.com 下的所有域名都已经匹配。确定不是 GoAgent 的问题吗？

**Comment by hitrust** [comment]
我再查看一下，谢谢回答。
