### ISSUE TITLE
GFWList更新失败

### ISSUE THREAD

**Issue by ipfans** [FelisCatus/SwitchyOmega#196]
在使用 https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt 作为规则列表时，点击“立即更新情景模式”时始终出现“下载情景模式数据时出错。”

SwitchyOmega 2.2.13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.69 Safari/537.36

**Comment by FelisCatus** [comment]
如果网络状况不好，请先切换到代理模式再下载。
