### ISSUE TITLE
请求增加对新版edge浏览器的支持。它也是chromium内核，优点是同步数据不用FQ。

### ISSUE THREAD

**Issue by cekxm** [FelisCatus/SwitchyOmega#1966]
如题。

**Comment by zhanglhz** [comment]
可以在Edge里打开Chrome 官方的扩展程序页面。在页面顶端可以看到提示，直接安装即可。
![image](https://user-images.githubusercontent.com/8307604/72593529-29312c00-3940-11ea-8c37-414a31526275.png)

只是这个扩展还没在Microsoft Store的认证，安装后可以正常使用。
![image](https://user-images.githubusercontent.com/8307604/72593635-64cbf600-3940-11ea-8c91-35ab995f8bff.png)

**Comment by cekxm** [comment]
真的可以。谢谢回复。
