### ISSUE TITLE
希望可以上架 Microsoft Edge Addons catalog

### ISSUE THREAD

**Issue by wordlesswind** [FelisCatus/SwitchyOmega#1967]
我明白 [Microsoft Edge(Chromium)](https://www.microsoft.com/edge) 支持直接从 [Chrome 网上应用店](https://chrome.google.com/webstore) 上安装 [Proxy SwitchyOmega](https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif)。

但是我们都知道 **Chrome 网上应用店** **不能**在中国大陆的网络环境中**直接访问**。

而 Microsoft Edge(Chromium) 目前作为 Microsoft Windows 10 **内置浏览器**，其市场占有率是**可观的**。

#### 就 Microsoft Edge Addons catalog 本身而言

- [全面开放上架权限](https://blogs.windows.com/msedgedev/2019/12/16/get-started-extensions-addons-microsoft-edge-chromium/)
- 能够在中国大陆流畅地访问

因此希望作者可以将 Proxy SwitchyOmega 上架至 Microsoft Edge Addons catalog 。

#### 文档
[Publish An Extension - Microsoft Edge Development | Microsoft Docs](https://docs.microsoft.com/microsoft-edge/extensions-chromium/publish/publish-extension)

#### 相关 issue
#589 
#838 
#842 
#889 
#930 
#1016 
#1025 
#1058 
#1430 
#1437 
#1656 
#1699 
#1788 
#1821 
#1874 
#1891 
#1966

**Comment by yfdyh000** [comment]
作者一年多没出现了，所以你的期待短期内无法达成。

软件是GPL协议，_也许_ 可以自行上传来申请上架。

**Comment by wordlesswind** [comment]
> 作者一年多没出现了，所以你的期待短期内无法达成。
> 
> 软件是GPL协议，_也许_ 可以自行上传来申请上架。

对于许可证这边没有涉猎，不敢乱动手。

**Comment by celeron533** [comment]
给作者发一封邮件问问，我记得这几年他很忙所以开始咕咕咕了

**Comment by zhezh** [comment]
在edge的设置里允许从其他商店安装 可以直接安装使用了
我的edge是 版本 81.0.416.16 (官方内部版本) beta (64 位)



![Snipaste_2020-02-26_09-31-08](https://user-images.githubusercontent.com/29795174/75303120-c2762b00-587a-11ea-83e2-339c53e99b45.png)

**Comment by shunner** [comment]
所以这是谁干的？

**Comment by wordlesswind** [comment]
> 所以这是谁干的？https://microsoftedge.microsoft.com/addons/detail/dijmmgblneagkcdganednabkbgjmceoe?hl=en-US

看这姓名，不像是作者干的？
总不可能连 Microsoft 帐户都没有吧？

**Comment by wordlesswind** [comment]
> 所以这是谁干的？https://microsoftedge.microsoft.com/addons/detail/dijmmgblneagkcdganednabkbgjmceoe?hl=en-US

https://github.com/FelisCatus/SwitchyOmega/issues/2004#issuecomment-667794533

**Comment by huanghe2015** [comment]
> 
> 
> > 所以这是谁干的？https://microsoftedge.microsoft.com/addons/detail/dijmmgblneagkcdganednabkbgjmceoe?hl=en-US
> 
> [#2004 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/2004#issuecomment-667794533)

由于链接已失效，后来访问者请忽略。

**Comment by WXZhao7** [comment]
微软商店上架的那个我试了下，貌似打包的有点问题，我在linux的dev版中明显比chrome版卡，而且开启同步会失败（chrome版的同步在edge上依旧可以运行，好评！）
未来打算全平台换成edge，开发者快回来鸭！

**Comment by huanghe2015** [comment]
> 
> 
> 微软商店上架的那个我试了下，貌似打包的有点问题，我在linux的dev版中明显比chrome版卡，而且开启同步会失败（chrome版的同步在edge上依旧可以运行，好评！）
> 未来打算全平台换成edge，开发者快回来鸭！

我也很无奈，我是基于最新发布版打包的。
