### ISSUE TITLE
目前列表中只包含自定义情景和”[直接连接]“，未包含”[系统代理]“，建议增加。

### ISSUE THREAD

**Issue by danyang685** [FelisCatus/SwitchyOmega#1977]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Chrome 79

### Problem description / 问题描述

“自动切换模式”情景下，未提供针对条件的”[系统代理]“情景模式

#### Steps to reproduce issue / 重现错误所需步骤“

(What did you do? / 你做了什么？)

1. 新建一个“自动切换模式”情景
2. 新建一个“条件”
3. 为条件选择”情景模式“

#### Expected behavior / 期望发生的情况
”[系统代理]“可以被选择为一个”情景模式“

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
目前列表中只包含自定义情景和”[直接连接]“，未包含”[系统代理]“，建议增加。

**Comment by celeron533** [comment]
#1566

**Comment by danyang685** [comment]
了解，谢谢！
