### ISSUE TITLE
可不可以给个 basic auth 的选项

### ISSUE THREAD

**Issue by n0wa11** [FelisCatus/SwitchyOmega#2]
English Title: Allow basic auth for proxies.

可不可以给个 basic auth 的选项？如果还没有的话。

现在的情况是，返回 401 错误后，chrome 会弹出对话框。不过，这可能成为 gfw 下一个监测特征。以后可能需要密码错误就返回 400，才能不被发现。

**Comment by markhuang1212** [comment]
> v2.2.3 已经支持～

想问一下这个功能是否已经支持，如果支持的话如何使用，因为在现在的版本里默认还是要等407之后才会发送用户名密码
