### ISSUE TITLE
extension can not be loaded without VPN connection / 插件在没翻墙成功之前不能加载

### ISSUE THREAD

**Issue by Whospakka** [FelisCatus/SwitchyOmega#200]
extension can not be loaded without VPN connection / 插件在没翻墙成功之前不能加载

**Comment by FelisCatus** [comment]
可以到这里下载： https://github.com/FelisCatus/SwitchyOmega/releases

**Comment by Whospakka** [comment]
不是下载的问题， 是安装好之后重启显示extension不能被加载， 进入扩展管理器后显示，程序已经损坏。但是VPN连接后好像就没有这个问题。

**Comment by FelisCatus** [comment]
似乎和 Chrome 有关，可以试试看新建一个干净的 Chrome 用户数据文件夹，然后看是否还有损坏的问题。也可以试着更新 Chrome 。
