### ISSUE TITLE
插件不生效

### ISSUE THREAD

**Issue by DoTime** [FelisCatus/SwitchyOmega#2002]
国内网站总是会跳转国外的域名, 使用pac和自动模式都有这个问题,代理使用的灯.
在灯不能连接时候, 国内网站也不能连接.
总体感觉为所有的站点都走代理.

SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Comment by AnyWAT** [comment]
貌似灯使用了系统全局代理，修改灯设置。。。此乃致插件不生效所在。
Win10系统：开始——设置——网络和 Internet ——代理，检查并关闭各开关

**Comment by DoTime** [comment]
![image](https://user-images.githubusercontent.com/15666939/76158964-8c785700-6156-11ea-8990-66469790fa14.png)
![image](https://user-images.githubusercontent.com/15666939/76158973-a9ad2580-6156-11ea-8a17-d314346e33d3.png)

记得ss也是会在本地开一个端口,

**Comment by AnyWAT** [comment]
代理软件控制系统全部流量，插件 SwitchyOmega 选择“系统代理”或禁用插件。
代理软件不控制系统全部流量，插件 SwitchyOmega 
1、新建情景模式——代理服务器，名称（如 SS SSR 为例）协议与端口如图

![image](https://user-images.githubusercontent.com/37962734/76159682-ec263080-615d-11ea-9d47-e378b02e5bd5.png)

2、新建情景模式——自动切换模式，名称（如 Auto...) 如图

![image](https://user-images.githubusercontent.com/37962734/76159768-a3bb4280-615e-11ea-9ac4-e71f34fb6aef.png)

运行 SS，不控制系统代理，由插件 SwitchyOmega 控制，在浏览器内想使用全局就选1、建立的。。。
如想自动选择，就选2、建立的。。。
这样插件不会不生效

**Comment by AnyWAT** [comment]
变化名称、协议、端口，如法炮制“灯”的浏览器内全局及自动代理

**Comment by DoTime** [comment]
终于找出来是这个插件给冲突了:Surfingkeys
还在找如何禁用
![image](https://user-images.githubusercontent.com/15666939/76160303-fb0fe180-6163-11ea-9b11-36a6e9455c49.png)
https://github.com/brookhong/Surfingkeys/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%B8%8E%E5%85%B6%E5%AE%83%E4%BB%A3%E7%90%86%E6%8F%92%E4%BB%B6%E5%A6%82switchyomega%E5%86%B2%E7%AA%81
添加
settings.setProxyMode='clear'
这个设置貌似没生效
