### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by tower1229** [FelisCatus/SwitchyOmega#201]
自动切换模式下，代理和非代理模式的图标区别不是很醒目，忙起来的时候希望扫一眼就能知道是不是走的代理，可以改进下

**Comment by zhoudianyou** [comment]
支持一下  确实  时这样  我都不知道 那个网站   走代理 ，      那个没走代理，确实需要改进一下 +1

**Comment by FelisCatus** [comment]
见 #107.
