### ISSUE TITLE
设置加入pac白名单后会很卡顿

### ISSUE THREAD

**Issue by newone14** [FelisCatus/SwitchyOmega#2019]
pac白名单地址https://pexcn.me/daily/pac/whitelist.pac
设置pac模式后拓展会很卡顿 影响chrome启动速度

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36

**Comment by AnyWAT** [comment]
设置加入pac白名单后会很卡顿——貌似与本插件无关，只是代理的锅？

**Comment by newone14** [comment]
谢谢提供pac我修改下试试

**Comment by newone14** [comment]
修改后不卡了
