### ISSUE TITLE
Suggestion: Add one min in PAC Download Frequency 

### ISSUE THREAD

**Issue by airhuman** [FelisCatus/SwitchyOmega#202]
RT
15 mins seems a little long...

**Comment by FelisCatus** [comment]
Oh really? Is there a real-world example of a PAC script that get updated **every minute** ?

**Comment by airhuman** [comment]
I do

**Comment by FelisCatus** [comment]
Are you using PAC scripts generated by automatic tools? You can always force updating of the PAC script by re-selecting the PAC profile in the dropdown menu, even if it is already selected. Doing so would start re-downloading in the background, and the new downloaded script will come into effect in less than one minute. This would probably be what you actually want.

Adding an option for one update per minute is trivial in implementation, but I'm not going to do that for the following reasons:

* You can always do a manual update conveniently when you want to (via the method above), and
* Downloading PAC at such interval would cause network issues, and
* PAC scripts must be compiled and executed before they can be used, which means much memory and CPU usage, at least in Chrome. Executing such a process every minute would slow the device down so much that you probably can't surf the internet without lagging.

I'm closing this issue for now, but the discussion is still open. Feel free to add more context (and detailed use cases) if you really need the feature.
