### ISSUE TITLE
微软应用商店里的SwitchyOmega不是官方发布的吧？

### ISSUE THREAD

**Issue by mdlenoir** [FelisCatus/SwitchyOmega#2027]
以前用Chrome，需要在Google应用商店下SwitchyOmega，但是没装SwitchyOmega就不能打开应用商店，不打开应用商店就不能安装SwitchyOmega这样的循环问题。现在换EDGE感觉也挺好的，同步也不需要翻墙，希望作者能够把SwitchyOmega也发布到微软的应用商店上。
https://microsoftedge.microsoft.com/addons/detail/dijmmgblneagkcdganednabkbgjmceoe?hl=zh-CN

**Comment by AnyWAT** [comment]
> 但是没装SwitchyOmega就不能打开应用商店

没装SwitchyOmega 以前开启代理软件的系统全局代理就能打开应用商店了。

**Comment by jjj201200** [comment]
名为“edge ext”的发布者是经过恶意修改后再发布的版本，具体详见：https://github.com/bilibili-helper/bilibili-helper-o/issues/695
我也才发现尽然连SwitchyOmega也遭殃了

**Comment by maidmeow4** [comment]
Then we should report that extension to Microsoft ...

**Comment by SJH114488406** [comment]
已经举报了，不知道作者是不是也在等微软解决

**Comment by FelisCatus** [comment]
See https://github.com/FelisCatus/SwitchyOmega/issues/2004#issuecomment-667794533
