### ISSUE TITLE
It can't work after update

### ISSUE THREAD

**Issue by M-Kepler** [FelisCatus/SwitchyOmega#203]
更新之后就用不了了，原来那个右下角有个绿色的叉

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
用不了了？具体是什么情况？

**Comment by M-Kepler** [comment]
我没有删除旧版，旧版的右下角有个绿色的叉，后来我删了旧版和新版重新在商店下载switch旧版，重新上传.bak文件就ok了。谢谢你的插件! 在2015年01月16日 20:36 ，FelisCatus写道： 用不了了？具体是什么情况？ — Reply to this email directly or view it on GitHub.
