### ISSUE TITLE
为什么不加一个自动根据网址是否可用来切换代理的功能？

### ISSUE THREAD

**Issue by liangwenrong** [FelisCatus/SwitchyOmega#2036]
1、遇到一些url，它不在gfwlist名单内所以走直连模式，但是它又是一个需要走代理才能访问的url，而且这些url还经常变化以至于很难被gfwlist或者个人名单收录完整。
2、为了应对上面描述的情况，是否存在一种根据响应时间来自动切换代理的功能？如果有请告诉我谢谢。
如果木有，是否可以实现呢？每当访问一个url，如果这个url是直接连接，而且在设定的时间内（比如5s）还没有响应，则判断为需要切换代理，通过切换预先设好的代理进行代理访问。
伪代码
/
if(url isTypeOf 直接连接){
  setTimeout(
    if(连接不上)
      切换指定代理
  ,5s)
}

这个判断应该不难，觉得有必要吗？你们怎么看

**Comment by yfdyh000** [comment]
扩展设置的是PAC。扩展检测连接可用性，会影响浏览器速度（所以Google正研究取消这种API），以及误判（比如网站挂掉了。数据包重复发送了。其他情况），总之不是太容易。

我记得有些代理软件有这类功能。或者用大陆网站/IP绕过、其他连接都走代理的模式。gfwlist年久失修了。

**Comment by xezun** [comment]
这也是一个设计原则问题，除非是已知，否则不应该替用户做主，因为自动重复请求有一定的危险性，例如在涉及资产的操作时，重复请求有可能会导致双倍的资产损失。

**Comment by tea1111980** [comment]
> 这也是一个设计原则问题，除非是已知，否则不应该替用户做主，因为自动重复请求有一定的危险性，例如在涉及资产的操作时，重复请求有可能会导致双倍的资产损失。

恩，对的。。话说 你这图标 像一个快递公司的，忘了叫啥名了。哈。。
