### ISSUE TITLE
twitter自动退出

### ISSUE THREAD

**Issue by yhhm** [FelisCatus/SwitchyOmega#206]
这两天昨天和今天，登录twitter后总是自动退出，而且无法再次登入。有时候重启电脑或隔一段时间可以再次登陆上，但保持时间都非常短。

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器问题或 Twitter 问题，与本项目无关。

**Comment by yhhm** [comment]
谢谢！

2015-01-17 17:20 GMT+08:00 FelisCatus <notifications@github.com>:
