### ISSUE TITLE
The latest release version in this repo is 2.5.20 while the version in chrome store is 2.5.21.

### ISSUE THREAD

**Issue by hongyi-zhao** [FelisCatus/SwitchyOmega#2065]
Hi,

The latest release version is 2.5.20 while the version in chrome store is 2.5.21. See here fore more info:
https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif

Why the latest release version in this repo is lower than the one appeared in chrome store?

**Comment by FelisCatus** [comment]
Answered in #2007.
