### ISSUE TITLE
https 代理不生效 

### ISSUE THREAD

**Issue by chenke0123** [FelisCatus/SwitchyOmega#2076]
设置了https ,http代理，只有http神效，https不能正确访问总提示"代理服务器出现问题，或者地址有误。..."
用curl访问缺正常。
我的代理服务器使用的是nginx  + ngx_http_proxy_connect_module 模块 代理本身服务器设置没问题。因为我用windows系统代理设置后，用chrome访问正常，但通过SwitchyOmega 设置的https 就不行。
通过对nginx日志查看发现完整一条日志："st:2020-07-12T10:03:12+08:00|^|unix_timestamp:1594519392.121|^|ip:10.101.80.2|^|status:400|^|up_addr:-|^|up_status:-|^|user: -|^|request:\x16\x03\x01\x02\x00\x01\x00\x01\xFC\x03\x03\x89\x11\xA6\x8D9\xD5\xB4\xB7\xAARF\xDC\x0B\x7F\xE0\xC4/n\xD1\xCEE\x89\xAC\x5C>\xEE(\xCA\xB9Z\x10\xF4 s\xF9+\xAF'T\xC4\x06\xD8\xED\x12\x98E1\xB8\x94G\x88\xAA?\xE7\xC9\x18\x81\xA8\x04\x0C\x0C\xB8u\xEC.\x00 \xEA\xEA\x13\x03\x13\x01\x13\x02\xCC\xA9\xCC\xA8\xC0+\xC0/\xC0,\xC00\xC0\x13\xC0\x14\x00\x9C\x00\x9D\x00/\x005\x01\x00\x01\x93\xDA\xDA\x00\x00\x00\x17\x00\x00\xFF\x01\x00\x01\x00\x00|^|reqbody:""|^|referer:-|^|ua:-|^|byte:154|^|forwarded:-|^|upstream_response_time:-|^|request_time:0.012|^|server_name:localhost|^|host:localhost|^|hostname:ce83e90118c5|^|server_protocol:-|^|request_method:-|^|request_uri:-|^|bytes_sent:303|^|gzip_ratio:-|^|sent_http_tid:-|^|sent_http_rid:-|^|sent_http_uid:-|^|scheme:http|^|remote_port:49205|^|content_length:-|^|X-Request-Id:0012ra5ebsoc651uajv0|^|csi:-|^|crp:-|^|content-type:text/html|^|Location:-|^|upstream_name:null"

但用curl发现访问的日志是：“st:2020-07-12T10:13:28+08:00|^|unix_timestamp:1594520008.181|^|ip:10.101.80.2|^|status:200|^|up_addr:-|^|up_status:-|^|user: -|^|request:CONNECT www.baidu.com:443 HTTP/1.1|^|reqbody:""|^|referer:-|^|ua:curl/7.55.1|^|byte:4807|^|forwarded:-|^|upstream_response_time:-|^|request_time:0.173|^|server_name:localhost|^|host:www.baidu.com|^|hostname:ce83e90118c5|^|server_protocol:HTTP/1.1|^|request_method:CONNECT|^|request_uri:-|^|bytes_sent:4807|^|gzip_ratio:-|^|sent_http_tid:-|^|sent_http_rid:-|^|sent_http_uid:-|^|scheme:http|^|remote_port:50424|^|content_length:-|^|X-Request-Id:001300idvf7jt29p93og|^|csi:-|^|crp:-|^|content-type:-|^|Location:-|^|upstream_name:null”

求助大神 给点思路，为何SwitchyOmega  设置的https代理就不行，有么有什么替代插件？
 

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by chenke0123** [comment]
设置问题，已经自行解决了！

**Comment by okchenyi** [comment]
兄怎么解决的，我也遇到这个问题？

**Comment by chenke0123** [comment]
> 兄怎么解决的，我也遇到这个问题？

SwitchyOmega 设置的时候http和https代理都用一个端口  nginx
