### ISSUE TITLE
建议恢复SwitchySharp下拉菜单里“新建规则”一项

### ISSUE THREAD

**Issue by myvpn** [FelisCatus/SwitchyOmega#208]
有很多网站并没有在AutoProxy和在线规则列表中，需要手动添加，现版本添加这些网站实在太麻烦，用户还需要回到选项中逐项添加，反不如在旧版SwitchySharp方便，旧版SwitchySharp只要在对应的网页下点击图标，再点选“新建规则”就可完成了，但现在的新版本我找不到这个方便的功能，是新版本省略了此功能还是我不会使用？谢谢。
![001](https://cloud.githubusercontent.com/assets/10575272/5789723/52c8edca-9eb1-11e4-81ff-d23fd5268d8e.jpg)

**Comment by FelisCatus** [comment]
![screenshot5](https://cloud.githubusercontent.com/assets/912649/5791790/38ac89d6-9f2b-11e4-9471-5e7388b8af88.png)

我这里显然是有的（图中带有+号的一项），你那边为什么没有我也不知道。不过如果真没有……那最好截个图来看看。

**Comment by myvpn** [comment]
![aaaaa](https://cloud.githubusercontent.com/assets/10575272/5811269/0ce54e68-a08f-11e4-9206-d69f68774acf.jpg)

**Comment by FelisCatus** [comment]
您正在使用的是“系统代理”，并非自动切换模式，所以当然也不能添加规则。切换到自动切换模式后即可。此外，该功能仅在正常网页的标签页中可用，在扩展选项页面以及新标签页面等不可用（因为显然不能设置这些页面所使用的代理）。
