### ISSUE TITLE
mac下Microsoft Edge设置成自动切换模式会导致浏览器崩溃

### ISSUE THREAD

**Issue by yinxufeng** [FelisCatus/SwitchyOmega#2085]
### SwitchyOmega version / SwitchyOmega 版本
2.5.21

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Microsoft Edge 84.0.522.49 (官方内部版本) (64 位)    
macOS 10.15.5

### Problem description / 问题描述
SwitchyOmega设置为自动切换，在浏览器地址栏输入任意两个字符，浏览器崩溃
设置为系统代理，则不会

**Comment by danielyang1009** [comment]
same issue in windows 10

**Comment by yinxufeng** [comment]
更新了v2ray-core后好了，不知道是不是跟这有关

**Comment by yinxufeng** [comment]
不知道为什么又好了

**Comment by FelisCatus** [comment]
See https://github.com/FelisCatus/SwitchyOmega/issues/2004#issuecomment-667794533
