### ISSUE TITLE
problem in goagent 

### ISSUE THREAD

**Issue by Sadafdar** [FelisCatus/SwitchyOmega#209]
i have a problem in using goagent in china. for the first time when i install it, it was working fine. then after 24 hours it is not working, Facebook and you tube are failed to be opened. what should i do now?

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
This is the project page for SwitchyOmega, not GoAgent.
