### ISSUE TITLE
请问这个项目还维护吗

### ISSUE THREAD

**Issue by flyerH** [FelisCatus/SwitchyOmega#2095]
我看作者好像说因为个人家庭原因没有精力维护，有没有考虑其他人合作或者接手呢
目前遇到了问题想提pr也没人review

**Comment by G-BlueSummer** [comment]
看代码也在更新，但是没有新的release

**Comment by yfdyh000** [comment]
无人维护，代码是翻译平台自动更新。
可以自己维护分支。

**Comment by flyerH** [comment]
> 无人维护，代码是翻译平台自动更新。
> 可以自己维护分支。

代码还好，主要是
