### ISSUE TITLE
你好，打开facebook之类的都出现错误哦

### ISSUE THREAD

**Issue by zlc420** [FelisCatus/SwitchyOmega#210]
打开www.gmail.com出现如下错误：
Error: Not Found

The requested URL /_gh/ was not found on this server.

但是打开mail.google.com就没事。是DNS的问题么？

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.146 Safari/537.36

**Comment by FelisCatus** [comment]
GoAgent 问题与本项目无关。
