### ISSUE TITLE
about safari14

### ISSUE THREAD

**Issue by czzt1** [FelisCatus/SwitchyOmega#2100]
apple will support WebExtensions API in safari14,so Is it possible to implement SwitchyOmega on safari14?

**Comment by ericboehs** [comment]
Any news on this?

**Comment by czzt1** [comment]
> Any news on this?

No,but I have read apple's page about safari14,seems like apple doesn't provide proxy api.

**Comment by ericboehs** [comment]
I was able to find a sufficient solution using a proxy.pac file. The benefit is it works in all browsers and no extension is needed.

**Comment by czzt1** [comment]
> I was able to find a sufficient solution using a proxy.pac file. The benefit is it works in all browsers and no extension is needed.

thanks for your reply,I used pac file in safari successful,your advice is very useful.
