### ISSUE TITLE
[Info] SwitchyOmega

### ISSUE THREAD

**Issue by fatshi** [FelisCatus/SwitchyOmega#211]
自从升级之后发现这个代理插件的响应速度明显慢了很多，这个对于稍有强迫症的我实在是煎熬~

望作者能在下一版中改进一下，争取达到“丝般顺滑”的效果~

最后，对作者的奉献精神表示由衷的敬意，此致敬礼~

SwitchyOmega 2.2.13
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by FelisCatus** [comment]
关于响应速度这一点，希望能够详细说明。是哪里卡了？

* 界面上：下拉菜单的弹出速度？在下拉菜单选择项目后的反应速度？选项页面的加载速度？或者编辑自动切换的时候？
* 行为上：使用自动切换模式时，第一次加载网页前的“处理PAC脚本”所需时间？每个网页加载所需的时间？图标颜色改变需要的时间？

希望能详细说明具体的场景，以及更新前后大概延迟相差多久。如果和设置有关的话，还请附上设置备份文件，以便分析性能。谢谢！

**Comment by maxxc0m** [comment]
Plugin Switch Omega
