### ISSUE TITLE
颜色区分太不明显

### ISSUE THREAD

**Issue by chenxiaoyu3** [FelisCatus/SwitchyOmega#212]
有无proxy的颜色区分太不明显了，看得累。

一个灰色的边（或屎黄色的边），中心大灰绿色的点，比较难分辨。可以把点变小点，颜色区分大一点

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by xlqstar** [comment]
我也这么觉得，蓝色，绿色，灰色都好接近

**Comment by FelisCatus** [comment]
关于图标请参考 #107 的讨论以及建议。
