### ISSUE TITLE
Add socks5h support?

### ISSUE THREAD

**Issue by mitnk** [FelisCatus/SwitchyOmega#2131]
As said in https://github.com/urllib3/urllib3/issues/1035:

> In a proxy string, socks5h:// and socks4a:// mean that the hostname is
resolved by the SOCKS server. socks5:// and socks4:// mean that the
hostname is resolved locally.

Could we add the option of `socks5h`?

Thanks a lot for this project!

**Comment by mitnk** [comment]
Ah, seems this is related to #2130
(close them together when resolved?)

**Comment by yfdyh000** [comment]
It sounds a little different, delegates control to the agent instead of dealing with the extension.
The protocol does not seem to be universally supported.

There is no active development.

**Comment by mitnk** [comment]
@yfdyh000 yeah, looks like so :(

No sure it is [fixed](https://github.com/FelisCatus/SwitchyOmega/blob/403bde5678da300614ee24e2e65393ff22e33db3/omega-target-chromium-extension/src/js/omega_webext_proxy_script.js#L52) or [not](https://github.com/FelisCatus/SwitchyOmega/blob/403bde5678da300614ee24e2e65393ff22e33db3/omega-target-chromium-extension/src/module/proxy/proxy_impl_listener.coffee#L78), closing issue.
