### ISSUE TITLE
can't use Google search

### ISSUE THREAD

**Issue by AndyLee-Github** [FelisCatus/SwitchyOmega#215]
Hi ，
    我不能用谷歌搜索，其他正常。

     当我用谷歌搜索的时候， 它没有反应或者 显示404. 不知道是不是因为我升级造成的。 我升级之前Google搜索很正常。

非常感谢你们所做的！

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器问题与本项目无关。
