### ISSUE TITLE
localhost代理不了

### ISSUE THREAD

**Issue by anwar211** [FelisCatus/SwitchyOmega#2157]
新建代理服务器127.0.0.1 端口：8080
代理localhost时会有一个强制临时选择直连模式，而不是我选择的代理服务器

Chrome 版本 88.0.4324.150（正式版本） （64 位）

**Comment by PMExtra** [comment]
![image](https://user-images.githubusercontent.com/11289158/107746747-4d348c00-6d51-11eb-99c0-3d0b9df282a9.png)
请检查设置

**Comment by anwar211** [comment]
> ![image](https://user-images.githubusercontent.com/11289158/107746747-4d348c00-6d51-11eb-99c0-3d0b9df282a9.png)
> 请检查设置

![image](https://user-images.githubusercontent.com/61727188/107871720-1db38a00-6edf-11eb-9266-bd250302c418.png)
![image](https://user-images.githubusercontent.com/61727188/107871723-273cf200-6edf-11eb-923a-c36a6dcb8f9f.png)
设置应该没错呀，以前用的好好的
火狐浏览器没事，就谷歌会变成直连

**Comment by anwar211** [comment]
> ![image](https://user-images.githubusercontent.com/11289158/107746747-4d348c00-6d51-11eb-99c0-3d0b9df282a9.png)
> 请检查设置

![image](https://user-images.githubusercontent.com/61727188/107871786-afbb9280-6edf-11eb-9407-ddbd08232da6.png)
这是火狐的

**Comment by anwar211** [comment]
还望大佬指点一二😭

**Comment by PMExtra** [comment]
不代理的地址列表，你列表里有 localhost 它就不会代理 localhost 啊……

**Comment by anwar211** [comment]
> 不代理的地址列表，你列表里有 localhost 它就不会代理 localhost 啊……

全删了设成loopback,也是一样会直连
