### ISSUE TITLE
angular-spectrum-colorpicker.git  not found

### ISSUE THREAD

**Issue by cnsuer** [FelisCatus/SwitchyOmega#2168]
npm run deps

Fatal error: Failed to execute "git ls-remote --tags --heads https://github.com/Jimdo/angular-spectrum-colorpicker.git", exit code of #128
remote: Repository not found.
fatal: repository 'https://github.com/Jimdo/angular-spectrum-colorpicker.git/' not found

**Comment by Franinc** [comment]
line 37 of `/omega-web/bower.json`

change
`"angular-spectrum-colorpicker": "~1.3.5",`
to
`"angular-spectrum-colorpicker": "git://github.com/powwowinc/angular-spectrum-colorpicker.git",`

**Comment by cnsuer** [comment]
thank you very much!

**Comment by huanghe2015** [comment]
Used at building Edge extension. #2004
`"angular-spectrum-colorpicker":"https://github.com/powwowinc/angular-spectrum-colorpicker.git",`
