### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by rescue1** [FelisCatus/SwitchyOmega#217]
Windows 7, Chrome Version 39.0.2171.95 dev-m.

Cannot install from Google Chrome store. Package install failed either.
An error has occurred. Network_Failed. Cannot install from this website.

**Comment by FelisCatus** [comment]
Network issues are not related to this project.

**Comment by rescue1** [comment]
Well, I fixed this problem by updating Chrome. It's the Chrome version problem.
