### ISSUE TITLE
使用反馈

### ISSUE THREAD

**Issue by mayhuny** [FelisCatus/SwitchyOmega#218]
1.感觉界面有点卡顿，没有老版本流畅
2.界面友好程度有待提升
3.个人觉得这种工具在满足功能的情况下还是以方便操作为第一前提，实现功能的同时越少操作越好
4.还是发自内心的感谢您提供如此美好的工具，谢谢！

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.101 Safari/537.36

**Comment by FelisCatus** [comment]
感谢反馈。如果可以的话请多提一点具体的建议，谢谢。

1. 请指出具体的卡顿位置和大致情况。
2. 请提一两个可以使界面更友好的改进。
3. 可以说说看如何减少不必要的操作。
4. 你们的支持是我前进的动力，不需要太多感谢的话语，只要更多人能提供意见和建议，这个项目一定会做得更好。

**Comment by mayhuny** [comment]
1.卡顿主要表现在情景模式切换时，可能我的列表有点多。
2.切换规则是否可以增加网址分类，因为有的网站走流量比较多。
3.添加条件如果可以将新版与老版结合更好，例如，我要添加网址：www.google.com，新版本直接是将www.google.com
加入列表，老版本却是可以修改成*.google.*加入列表。
新版的列表间距、字体大小是否可以调整一下，考虑一下低分的笔记本，谢谢！


在 2015年1月22日 上午1:15，FelisCatus <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
1. 下个版本情景模式切换的速度将会有显著提高。代码已经写好了，预计今天或者明天就能发布新版。
2. 对于某个网页 *以及网页内的所有资源* 使用某个代理是[技术上难以达成的，具体见说明](https://github.com/FelisCatus/SwitchyOmega/issues/270#issuecomment-73453478)。
3. 添加条件是可以选择类型或者更改内容的。弹出菜单的默认规则是 *.google.com ，已经可以满足大部分需求。如果需要匹配任意位置，在弹出菜单或选项中选择网址通配符，然后就很容易修改了。
4. 列表间距和字体大小已经调整过很多次了，也针对不同的屏幕宽度优化过，但默认值不可能满足所有人要求。但所幸在页面上按 Ctrl+减号 缩小页面到适当比例即可，这会同时缩小间距和字号。代码不能控制页面的缩放，所以必须用户手动调节，我所能做到的只是确保在不同比例下都能正常显示而已。

**Comment by FelisCatus** [comment]
v2.3.2 已经发布。更新后，切换情景模式应该会比以前快很多。

**Comment by mayhuny** [comment]
感谢！！新年快乐~

在 2015年2月9日 下午4:34，FelisCatus <notifications@github.com>写道：
