### ISSUE TITLE
这个需要有人接手了，都三年没更新了.....

### ISSUE THREAD

**Issue by tudnew** [FelisCatus/SwitchyOmega#2180]
### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

**Comment by cool-delete** [comment]
商店的话 5个月前还有更新的 不过作者不知道做什么了 仓库都没有任何活动记录

**Comment by flyerH** [comment]
确实，可惜作者联系不上，难道真的要重新造轮子吗

**Comment by cool-delete** [comment]
我打算迁移到[SmartProxy](https://github.com/salarcode/SmartProxy)了 跟那边的作者也提了[#176](https://github.com/salarcode/SmartProxy/issues/176) 作者答应会尽快做出可以导入SwitchyOmega的链接记录
