### ISSUE TITLE
连接模式不能保存

### ISSUE THREAD

**Issue by hezlog** [FelisCatus/SwitchyOmega#2193]
在新版本chrome中，每次启动都会重新回到默认模式（系统代理），不能记忆上次的连接模式。

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36

**Comment by hezlog** [comment]
重新安装chrome解决！

**Comment by hezlog** [comment]
重新安装chrome解决！

**Comment by AnyWAT** [comment]
设定——界面——切换选项——初始情景模式
