### ISSUE TITLE
SwitchyOmega Freeze Firefox Proton UI When in Bad Network Condition

### ISSUE THREAD

**Issue by byzod** [FelisCatus/SwitchyOmega#2197]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Firefox Developer Edition 90 beta 12 / Windows 10 20H2

### Problem description / 问题描述
SwitchyOmega freeze firefox's new UI (Proton) when under bad network connection (afaik packet loss & TCP RST), this only happens on Proton UI so it affect firefox 89+ only

Packet loss & TCP RST is very common in country that don't have full network access, especially those who use VPN, for example China. This bug affects millions of people

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. Download Firefox 89+ (for example FDE [90b12](https://ftp.mozilla.org/pub/devedition/candidates/90.0b12-candidates/build1/win64/en-US/firefox-90.0b12.zip)), extract it or install it
2. Download [SwitchyOmega 2.5.20 at AMO](https://addons.mozilla.org/en-US/firefox/addon/switchyomega/) and install it. Skip the tutorial, and set to `auto switch` mode with the SwitchyOmega button
3. Download bad network simulator [Clumsy ](https://github.com/jagt/clumsy/releases/tag/0.3rc3)
4. Start firefox, then start clumsy
5. In clumsy, there're many `functions`, check the `Drop` box, set chance(%) to `20`. and check `Set TCP RST` box, set chance(%) to `20`. Then click `Start` button
6. Open 5~10 web pages that have many multimedia contents, for example [youtube](https://www.youtube.com/), [deviantart](https://www.deviantart.com/), [reddit](www.reddit.com/), [imgur](https://imgur.com/)

#### Expected behavior / 期望发生的情况
You open too many pages at once so they load slow than usual but after few seconds of loading, they've done successfully, nothing special happens.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
The firefox UI response is slow, laggy, even freeze at all

**Comment by aur3l14no** [comment]
Same.

**Comment by chenshaoju** [comment]
Same here with Firefox 90.0.2 with Proxy SwitchyOmega 2.5.20。

**Comment by whenov** [comment]
Possibly related Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1718719

**Comment by byzod** [comment]
Fixed in [firefox 93](https://bugzilla.mozilla.org/show_bug.cgi?id=1382886)
