### ISSUE TITLE
自动切换模式规则设置缺少系统代理选项

### ISSUE THREAD

**Issue by binhong87** [FelisCatus/SwitchyOmega#220]
自动切换模式的配置中，切换规则无法设置使用系统代理，只能选择直接连接。
如图：
![image](https://cloud.githubusercontent.com/assets/4192051/5856328/30d96526-a27d-11e4-8efa-7cd8c92149b5.png)

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
见 #170.
