### ISSUE TITLE
自动切换模式无法观看youtube.

### ISSUE THREAD

**Issue by solostn** [FelisCatus/SwitchyOmega#221]
如果使用系统代理模式，可以观看。但是感觉浏览变得比较慢。
如果使用自动代理模式，youtube能进页面，读取也正常，但就是视频一直黑屏，无法播放。
如果强制使用goagent代理模式，可以播放。。。。

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by FelisCatus** [comment]
GFW List 问题与本项目无关。可以试着用开发者工具找找看对应的请求。（不过也不一定能找到，毕竟是 Flash ……）

我个人推荐用 https://www.youtube.com/html5 试试看，这个浏览器代理支持会好一些。

**Comment by xdb1984** [comment]
> 如果使用系统代理模式，可以观看。但是感觉浏览变得比较慢。 如果使用自动代理模式，youtube能进页面，读取也正常，但就是视频一直黑屏，无法播放。 如果强制使用goagent代理模式，可以播放。。。。
> 
> SwitchyOmega 2.2.14 Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

你这问题解决了吗？自动模式youtube确实看不了视频，一直转圈圈；非自动模式选定一个点是可以的。
自动模式和非自动模式都是相同的站点，但是自动模式不行。
