### ISSUE TITLE
Direct connection in Firefox does not have the expected effect 

### ISSUE THREAD

**Issue by NICOLE1224** [FelisCatus/SwitchyOmega#2213]
### SwitchyOmega version / SwitchyOmega 版本

2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0

### Problem description / 问题描述

Direct connection in Firefox does not have the expected effect and is actually 
equivalent to and system proxy. I tried the same configuration in Chrome 
and he was able to achieve my expected results (bypassing the system proxy 
settings when direct connection was selected).

I'm not familiar with English, so I hope the translator's results won't confuse you.

**Comment by waingt** [comment]
@shixudong2020 @NICOLE1224 
See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/proxy/ProxyInfo
"direct": don't proxy the request. If this value is given, all other properties of this object are ignored. However, this setting doesn't override any [proxy set by the user](https://support.mozilla.org/en-US/kb/connection-settings-firefox)

https://support.mozilla.org/en-US/kb/connection-settings-firefox
Choose _No proxy_ in _Connection Settings_ will solve this issue
