### ISSUE TITLE
图标不支持retina

### ISSUE THREAD

**Issue by Arcious** [FelisCatus/SwitchyOmega#223]
图标不支持retina

SwitchyOmega 2.2.14
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by Arcious** [comment]
绿点图标不支持retina,菜单里面的图标是支持retina的 ![screen shot 2015-01-23 at 12 31 18 pm](https://cloud.githubusercontent.com/assets/9977832/5869856/c57abf80-a2fb-11e4-9a0e-a3acb5c11396.png)

**Comment by FelisCatus** [comment]
见 #41。菜单里的图标是字体，所以好像没这个问题……
