### ISSUE TITLE
Plesse support a web translation service 

### ISSUE THREAD

**Issue by klaernie** [FelisCatus/SwitchyOmega#225]
Could try to integrate a web translation service like weblate (http://hosted.weblate.org)? That should make it trivial to integrate new languages and obtain new translators.

**Comment by FelisCatus** [comment]
Cool. I'll try to integrate one when I have time.

**Comment by FelisCatus** [comment]
SwitchyOmega is now on Weblate! Many thanks to the Weblate project.

[![Translation status](https://hosted.weblate.org/widgets/switchyomega/-/287x66-white.png)](https://hosted.weblate.org/engage/switchyomega/?utm_source=widget)
