### ISSUE TITLE
有没有想过搞一个安卓版的？

### ISSUE THREAD

**Issue by rainfall-breeze** [FelisCatus/SwitchyOmega#2256]
### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1.
2.
3.

**Comment by huanghe2015** [comment]
这只是个扩展，不要奢求太多。

**Comment by woshilaiba** [comment]
android上使用  yandex browser 是可以安装 这个扩展的

**Comment by porsche613** [comment]
In [IceRaven](https://github.com/fork-maintainers/iceraven-browser), based on [Firefox for Android](https://github.com/mozilla-mobile/fenix), you can search and Install SwitchyOmega directly.

In [Fennec F-Droid](https://f-droid.org/zh_Hant/packages/org.mozilla.fennec_fdroid/), [Mull](https://f-droid.org/zh_Hant/packages/us.spotco.fennec_dos/), and [Firefox for Android Nightly](https://www.mozilla.org/zh-TW/firefox/channel/android/#nightly), you need to [turn on their development options](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/) and find a Custom Addons Collection(built in IceRaven, etc.) to install it.

**Comment by rainfall-breeze** [comment]
I mean, would you make an app which could realize these functions：
1. one proxy for some apps and another for others
2.  auto switch by some rules
3.  the users can custom rules and proxies
it is very similar to your project, just change the web to apps

我的意思是，您可以做一个app，用以实现一下功能
1. 一个服务器来代理一些应用，同时另一个服务器来代理其他应用
2. 能够通过一些规则来自由切换服务器
3. 用户可以自定义规则和服务器
这和你们的项目非常相似，只是把对网站的代理改为对应用的代理

**Comment by yfdyh000** [comment]
> I mean, would you make an app which could realize these functions：
> 
> 1. one proxy for some apps and another for others
> 2. auto switch by some rules
> 3. the users can custom rules and proxies
>    it is very similar to your project, just change the web to apps
> 
> 我的意思是，您可以做一个app，用以实现一下功能
> 
> 1. 一个服务器来代理一些应用，同时另一个服务器来代理其他应用
> 2. 能够通过一些规则来自由切换服务器
> 3. 用户可以自定义规则和服务器
>    这和你们的项目非常相似，只是把对网站的代理改为对应用的代理

1. 作者弃坑多时。
2. 不是同一套技术架构，完全不同。
3. 使用SagerNet等App，自行添加代理，并配置路由-outbound。相关方法请自行摸索。

**Comment by porsche613** [comment]
> This issue seem to be of the same matter as [this one](https://github.com/FelisCatus/SwitchyOmega/issues/2096) It's still relevant.
> 
> @porsche613 , could you specify which user and collection to pick to get the add-on working or should it be made on an individual basis?

The [issue](https://github.com/FelisCatus/SwitchyOmega/issues/2096#issuecomment-727533184) you mentioning:
Custom add-ons account is `16201230`,
Custom add-ons collection is `What-I-want-on-Fenix`,

It's still working for now (2023/01/28). By the way, not only in Nightly, custom add-ons installation are available in Beta channal after version 108.x.

The add-on works very stable, almost perfect except the UI would mess on small screen, tested on Firefox for Android Beta/Nightly, Fennec F-Droid, Mull, IceRaven and a new Firefox for Android derivatives [SmartCookieWeb-Preview](https://github.com/CookieJarApps/SmartCookieWeb-Preview), for almost a year.
