### ISSUE TITLE
SwitchyOmega在最新的Chrome浏览器上无法使用

### ISSUE THREAD

**Issue by zhangyunbo1994** [FelisCatus/SwitchyOmega#2260]
### SwitchyOmega version / SwitchyOmega 版本
Version 2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Chrome
Version 97.0.4692.99 (Official Build) (x86_64)
MacOS 12.1

#### Steps to reproduce issue / 重现错误所需步骤

(What did you do? / 你做了什么？)

1. 谷歌浏览器提醒我re-launch以更新到最新版本, 于是重启浏览器
2. 重启后发现原本正常工作的SwitchyOmega变得无法工作 -- 不能访问任何网页。
3. 降级谷歌浏览器，依旧无法解决问题
4. 在本机安装火狐浏览器，安装SwitchyOmega插件，发现在火狐浏览器上面工作的很好。

#### Expected behavior / 期望发生的情况
SwitchyOmega可以在最新的谷歌浏览器上正常工作。

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）
SwitchyOmega可以正常配置设置等，
但是不能在谷歌浏览器上正常工作。 -- 不能访问任何网页。

**Comment by ShellyShen1019** [comment]
请问解决了吗？

**Comment by AnyWAT** [comment]
Version 2.5.20——现在2.5.21
导出配置，卸载再装？
