### ISSUE TITLE
添加网速限制功能

### ISSUE THREAD

**Issue by 0400H** [FelisCatus/SwitchyOmega#2262]
截止当前在Chrome市场中并未发现有插件具有网速限制功能。
目前的网速限制方式是进入开发者模式对某个网页进行设置，该设置异常繁琐且无法限制全局网速。

希望提供全局、网页或域名的网速限制功能，防止Chrome上传或者下载时挤占所有的带宽，从而使得依赖互联网络的应用得以正常运行。

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

**Comment by yfdyh000** [comment]
Chrome扩展API不支持。
可用fiddle限速。或者试试cFos等QoS方案。

**Comment by 0400H** [comment]
> Chrome扩展API不支持。 可用fiddle限速。或者试试cFos等QoS方案。

是否可以通过在HOST上安装程序（如上文提到的Fiddle）作为中间层并提供接口以供SwitchyOmega（前端）使用的方法来实现该功能？
前中后端分离，在实现feature时具有更强的灵活性。

**Comment by yfdyh000** [comment]
> > Chrome扩展API不支持。 可用fiddle限速。或者试试cFos等QoS方案。
> 
> 是否可以通过在HOST上安装程序（如上文提到的Fiddle）作为中间层并提供接口以供SwitchyOmega（前端）使用的方法来实现该功能？ 前中后端分离，在实现feature时具有更强的灵活性。

你直接用SwitchyOmega转发到指定的代理端口就可以，由服务程序决定如何传输和传输速度。

**Comment by 0400H** [comment]
> > > Chrome扩展API不支持。 可用fiddle限速。或者试试cFos等QoS方案。
> > 
> > 
> > 是否可以通过在HOST上安装程序（如上文提到的Fiddle）作为中间层并提供接口以供SwitchyOmega（前端）使用的方法来实现该功能？ 前中后端分离，在实现feature时具有更强的灵活性。
> 
> 你直接用SwitchyOmega转发到指定的代理端口就可以，由服务程序决定如何传输和传输速度。

有道理。可以选择并搭建一个Bridge（支持网速限制，Cache等复杂功能）以对接前端和后端。
