### ISSUE TITLE
HTTP3 compatibility issues

### ISSUE THREAD

**Issue by lxsq** [FelisCatus/SwitchyOmega#2264]
### SwitchyOmega version / SwitchyOmega 版本
2.5.20

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Firefox 96.0
Ubuntu 20.04 LTS
Linux 5.11.0-43-generic

### Problem description / 问题描述
I notice with the proxy on, the browser falls back to HTTP/2. Would there be support for HTTP/3 anytime soon?
![image](https://user-images.githubusercontent.com/98205617/153711206-a8426d0c-dfd7-44d3-9939-a1662405727c.png)
![image](https://user-images.githubusercontent.com/98205617/153711225-44e7576d-0d01-40cb-b499-9a4776bfd79b.png)

**Comment by yfdyh000** [comment]
你试试不用扩展用浏览器设置，如果也这样就是代理的问题。

**Comment by lxsq** [comment]
> 你试试不用扩展用浏览器设置，如果也这样就是代理的问题。

火狐设置里直接填SOCKS5代理也不行，估计是浏览器内核不支持HTTP3或者UDP本身的socks代理。

**Comment by koalabearguo** [comment]
请问这个问题解决了吗？我现在搭建了一个同时支持的的HTTP2和HTTP3的代理，在插件中设置HTTPS代理时，只会使用HTTP2代理，并不会用HTTP3协议链接服务器。当用chrome直接连接服务器时，可以看到浏览器已经使用了HTTP3协议了，这是chrome的问题，还是插件的问题?

```
PC(chrome)<====internet====>HTTP2/HTTP3 PROXY SERVER
```
