### ISSUE TITLE
自动情景模式能不能支持自动切换到“系统代理”

### ISSUE THREAD

**Issue by mhqs007** [FelisCatus/SwitchyOmega#227]
考虑到目前有些别的扩展（比如ADfree）会和switchyomega抢代理控制权。
这样就能根据规则，自动切换了。
 #69.的问题也就解决了。

**Comment by FelisCatus** [comment]
这个事情涉及到 PAC 脚本生成，目前没有可靠的解决方案。（当然，楼主提的方案也很有创造性……可惜技术上没那么简单。）
