### ISSUE TITLE
使用自动代理的时候，能通过图标显示当前是否使用代理

### ISSUE THREAD

**Issue by w3324776** [FelisCatus/SwitchyOmega#228]
使用自动代理的时候，能通过图标显示当前是否使用代理

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by FelisCatus** [comment]
图标已经显示了……

**Comment by w3324776** [comment]
选自动切换代理，有的页面是有用代理的，有的没有，就是想通过图标显示能明确看出来，我现在用的是360浏览器，选自动切换代理，图标都是 灰圈里面是填充绿色，每个页面都一样

**Comment by FelisCatus** [comment]
旧版的 360 浏览器不在支持范围内。如果需要使用此功能，请下载测试版 360 浏览器。

**Comment by w3324776** [comment]
现在用的就是最新的7.3测试版的

**Comment by w3324776** [comment]
以前 proxy switchysharpe 那个就会，选自动代理的时候，没有代理的时候是灰色的，有代理就蓝色的

**Comment by FelisCatus** [comment]
之前在 Twitter 上另一位用户说用 360 极速浏览器版本 8 就可以，其他版本好像不行。
