### ISSUE TITLE
Long profile name breaks UI when using Virtual Profile

### ISSUE THREAD

**Issue by hexchain** [FelisCatus/SwitchyOmega#229]
If name of the chosen profile for a virtual profile is too long, the dropdown handle will be pushed down, which looks bad.

Example:
![deepinscreenshot20150125120851](https://cloud.githubusercontent.com/assets/529520/5890194/1dd09caa-a48b-11e4-8c05-bdf634c640a2.png)

(Square block reflects exact text length.)

EDIT: version info
SwitchyOmega 2.3.0
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.12 Safari/537.36

**Comment by hexchain** [comment]
That was quick! Thank you.

**Comment by FelisCatus** [comment]
But that's not gonna be shipped until the next minor release (which should be v2.3.1).

**Comment by hexchain** [comment]
That's not a problem. ;-)

**Comment by FelisCatus** [comment]
This should be fixed as of v2.3.1.

**Comment by hexchain** [comment]
Confirmed, thanks.
