### ISSUE TITLE
No access to Mail-Appliance

### ISSUE THREAD

**Issue by mystolz** [FelisCatus/SwitchyOmega#230]
Hi,

after upgrade to SwitchyOmega from ProxySharp, I dont have access to my local address https://192.168.115.61

https://192.168.115.61 is exepted

If I use the system proxy settings there also have an exeption for https://192.168.115.61 it works, but it dosen't work with SwitchyOmega

Regards
Helge

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by FelisCatus** [comment]
Please provide a screenshot of the upgraded Proxy Profile with focus on the bypass list section.
It is also recommended to do a PAC export on the profile you are using, especially when you are using Auto Switch.

**Comment by mystolz** [comment]
how can I send you a screenshot?
Reply from the mail dosen't work

**Comment by FelisCatus** [comment]
The issue tracker allows attach images via the Web interface. Or you can just upload to another public image hosting service and paste the link here.

**Comment by mystolz** [comment]
![25-01-_2015_15-28-18](https://cloud.githubusercontent.com/assets/10695359/5891953/f04e0f78-a4ae-11e4-8967-32e39432a49b.jpg)

**Comment by FelisCatus** [comment]
One more question: Does the problem happen when you use Mit Proxy itself, or when using Auto Switch? Or both?

**Comment by mystolz** [comment]
I have the on both settings

**Comment by FelisCatus** [comment]
Yeah I know that. But I'm asking about your current profile, as selected in the popup menu. Does selecting Mit Proxy trigger the problem? Or, does selecting Auto Switch?

**Comment by mystolz** [comment]
The current profile are "Mit Proxy"

**Comment by FelisCatus** [comment]
I just tried the same bypass pattern as yours. It seems that addresses in the `192.168.115.0/24` range is not tunneled through any proxy, which should be the right behavior.

May I ask for your further help by checking the URL `chrome://net-internals/#proxy` and copy any text on that page? That page should show the effective proxy settings.

**Comment by mystolz** [comment]
Effective proxy settings

Proxy server: 192.168.115.254:8080
Bypass list: 
  <local>
  192.168.115.0/24
  *.stolz.de*

**Comment by mystolz** [comment]
If I use the system proxy settings, I have this settings:

Effective proxy settings
Proxy server: firewall.stolz.de:8080
Bypass list: 
  *.stolz.de
  192.192.168.115.*
  https://192.168.115.254:4444
  <local>
Source: SYSTEM

Original proxy settings
(1) Auto-detect
(2) Proxy server: firewall.stolz.de:8080
    Bypass list: 
      *.stolz.de
      192.192.168.115.*
      https://192.168.115.254:4444
      <local>
Source: SYSTEM

**Comment by FelisCatus** [comment]
Your system bypass list contains a few more entries that is not covered in the SwitchyOmega settings, such as `https://192.168.115.254:4444`. Does copying the following list to your "Mit Proxy" help?

```
  *.stolz.de
  192.192.168.115.*
  https://192.168.115.254:4444
  <local>
```

**Comment by mystolz** [comment]
??? this works. But why?

Are 192.168.115.0/24 not ok?

**Comment by FelisCatus** [comment]
I think the real issue is that 192.168.115.61 must be visited though the proxy, while you thought it shouldn't. Things like this is related to your network and can't be explained without knowledge about the local subnet.

I'm going to close this issue since copying the system bypass list worked in this case.
