### ISSUE TITLE
Support SOCKS5H

### ISSUE THREAD

**Issue by DUOLabs333** [FelisCatus/SwitchyOmega#2300]
This is just a request to support SOCKS5H, which allows DNS queries to go through a SOCKS5 proxy.

**Comment by Alumniminium** [comment]
Chrome uses socks5h by default

**Comment by DUOLabs333** [comment]
I was referring to Firefox.

**Comment by Alumniminium** [comment]
its the same for firefox

**Comment by DUOLabs333** [comment]
No, because I'm trying to use SwitchyOmega for Tor, and trying to go to an onion address fails, because it does not resolve it.
