### ISSUE TITLE
The program does not work via proxy!

### ISSUE THREAD

**Issue by risksoft** [FelisCatus/SwitchyOmega#2307]
SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36

**Comment by GEkuL** [comment]
@risksoft please close the issue it's not relevant anymore

the addon is not a proxy itself, it's just a helping tool to conditionally forward your browser traffic into proxy server
