### ISSUE TITLE
能不能出个系统的教程资料，我想用shadowsocks搭建内外socks服务

### ISSUE THREAD

**Issue by ilovebamboo** [FelisCatus/SwitchyOmega#231]
SwitchyOmega 2.3.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega 项目，并非 shadowsocks 项目。具体的代理配置我确实不懂。毕竟 SwitchyOmega 只是用来更改浏览器设置的一个小小的环节而已……

**Comment by ilovebamboo** [comment]
汗。

**Comment by celeron533** [comment]
几乎所有的SS教程都推荐SwitchOmega/ProxySharp作为Chrome系浏览器的代理管家，然而有太多人误解，以为SwitchOmega和SS是共同开发的。。。
另外我也见到有些无良的代理服务网站公然宣称：“使用我们开发的SwitchOmega来连接到SS”。

**Comment by FelisCatus** [comment]
@celeron533 那么，是哪家呢？

**Comment by celeron533** [comment]
@FelisCatus 都是些个人开的SS服务器，规模很小。所谓的站点只不过是个wordpress页面，记录了售价和服务器信息。当时也就撇到一眼，具体是哪家，严打期间是否存活至今都不得而知了。宣称自己开发了SO估计也让小白用户一种“技术强劲”的错觉。

**Comment by ilovebamboo** [comment]
其实我更喜欢简单的东西。
