### ISSUE TITLE
“刷新页面以启用此扩展”

### ISSUE THREAD

**Issue by GyouzaRu** [FelisCatus/SwitchyOmega#2319]
每打开一个网页，都无法直接使用该扩展，点击扩展图标后之后提示“刷新页面以启用此扩展”。
刷新后可以正常使用，但是每一个网页都需要重新刷新操作，非常恼人。
之前没有碰到过该问题。

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54

**Comment by AnyWAT** [comment]
貌似：扩展程序——详情，不是如图而是“在特定网站上”？
![image](https://user-images.githubusercontent.com/37962734/184463486-adedb14e-dd70-4f67-9958-1cf091f3db86.png)

**Comment by GyouzaRu** [comment]
> 貌似：扩展程序——详情，不是如图而是“在特定网站上”？ ![image](https://user-images.githubusercontent.com/37962734/184463486-adedb14e-dd70-4f67-9958-1cf091f3db86.png)

已解决！非常感谢，的确就是这个原因。
