### ISSUE TITLE
仅仅提个建议

### ISSUE THREAD

**Issue by WillieCn** [FelisCatus/SwitchyOmega#232]
暂时没有出现什么异常，只是有个建议啊，以前的那个SwitchySharp的图标可以让人一眼认出当前是否处于走代理状态，现在的图标有点分不清，不用鼠标指着他就不知道当前网站是否在走代理，希望将各个状态的图标明显区别开来，或者是我没找到在哪里可以设置的么。

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by FelisCatus** [comment]
见 #107.
