### ISSUE TITLE
It is useless for google webpage translate

### ISSUE THREAD

**Issue by Yesaye** [FelisCatus/SwitchyOmega#2328]
### SwitchyOmega version / SwitchyOmega 版本
2.5.21

### Browser version & OS version / 浏览器名称、版本及操作系统版本
Chrome Version106.0.5249.91（x64）

### Problem description / 问题描述
Google shuts down Translate service in China recently, so google translate for webpage is useless, maybe it's not proxy by SwitchyOmega

#### Steps to reproduce issue / 重现错误所需步骤
visit a english website，and mouse right click switch translate this page to Chinese, it don't work by use SwitchyOmega to proxy.
but if I proxy by windows system, it work.

**Comment by XIU2** [comment]
这是 Chrome 浏览器的问题。我抓包检查过，全页翻译前，Chrome 会强制直连访问一次 `translate.googleapis.com`，而这次直连是**不受扩展控制**的，因此你将该翻译接口域名添加到 SwitchyOmega 使其走代理是**无效**的。

而这次直连过后，直到浏览器关闭前就不会再这么干了，而**后续的 POST 翻译流程环节，都可以正常受扩展控制走代理**了。

|||
--|--
内置 谷歌翻译 + SwitchyOmega 扩展 | = 不可用
内置 谷歌翻译 + 系统代理设置 | = 可用
内置 谷歌翻译 + Hosts | = 可用
谷歌翻译 扩展 + SwitchyOmega 扩展 | = 可用

具体看我写的这篇文章：https://zhuanlan.zhihu.com/p/576932998

**Comment by GEkuL** [comment]
@XIU2 to get helped, please, use english
