### ISSUE TITLE
搞什么东东，Facebook神马的全都打不开

### ISSUE THREAD

**Issue by ICRabbit** [FelisCatus/SwitchyOmega#233]
代理图标显示Facebook网站没有通过代理。

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查全局代理模式下是否能正常访问。如果不能，请检查代理服务器工作情况。

如果希望针对某地区网络现状来设置自动切换模式，只对某些特定网站使用代理，请参考 GFW List 相关使用说明，如GoAgent提供的教程。如果不知道该如何设置，可以[导入这个备份文件](https://switchysharp.googlecode.com/files/X_GFWList.bak)作为起点。（注意导入后需要重新设置代理服务器）
