### ISSUE TITLE
当代理服务器存在，但实际不可用时，“不代理的地址”的连接异常缓慢 / Unusually slow connections to "non-proxy addresses" when the proxy server exists but is not actually available

### ISSUE THREAD

**Issue by wordlesswind** [FelisCatus/SwitchyOmega#2347]
### SwitchyOmega version / SwitchyOmega 版本

2.5.21

### Browser version & OS version / 浏览器名称、版本及操作系统版本

Google Chrome Dev 110.0.5478.4

Windows 11 22H2 or Arch Linux

### Problem description / 问题描述

当代理服务器存在，但实际不可用时，“不代理的地址”的连接异常缓慢

Unusually slow connections to "non-proxy addresses" when the proxy server exists but is not actually available

#### Steps to reproduce issue / 重现错误所需步骤

1. 使用 [Fndroid/clash_for_windows_pkg](https://github.com/Fndroid/clash_for_windows_pkg)
2. 通过 [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) 连接至 Clash for Windows 的本地代理服务器。
3. 填写“不代理的地址列表”，例如 `www.example.com`。
4. 访问 `www.example.com`。

---

1. Use [Fndroid/clash_for_windows_pkg](https://github.com/Fndroid/clash_for_windows_pkg)
2. Connect to Clash for Windows' local proxy server via SwitchyOmega.
3. Fill in the "List of Unproxy Addresses", e.g. `www.example.com`.
4. Visit `www.example.com`.

#### Expected behavior / 期望发生的情况

正常加载 `www.example.com`。

Load normally `www.example.com`.

#### Actual (or suggested) behavior / 实际发生的情况（或建议修改后的行为）

由于代理服务器存在但不可用，导致 `www.example.com` 加载缓慢。
这似乎是 Google Chrome 在某次更新后出现的变化，预期行为应该是：无论代理服务器是否可用，“不代理的地址”的连接都应当是直接加载的。

Slow loading of `www.example.com` due to the proxy server present but not available.
This seems to be a change in Google Chrome after a certain update, and the expected behaviour should be that connections to "non-proxy addresses" should be loaded directly, regardless of whether the proxy server is available or not.

**Comment by AnyWAT** [comment]
使用 Clash for Windows 端口1080，还好。。。
![image](https://user-images.githubusercontent.com/37962734/208809975-adede58c-9f99-479e-ab90-66adcad1a728.png)

**Comment by wordlesswind** [comment]
> 使用 Clash for Windows 端口1080，还好。。。

那也许是我其他扩展程序干扰了？
我现在状况是比较奇怪的，如果 Clash for Windows 的本地代理服务器不可用，即便我选择“系统代理”甚至“直接连接”，都会出现相同情况。

**Comment by AnyWAT** [comment]
Clash for Windows 用全局或规则
系统代理即自动填写——地址：127.0.0.1 端口：1080
可以试试 psiphon3 式的系统代理手动设置——地址：
http=127.0.0.1:1080;https=127.0.0.1:1080;socks=127.0.0.1:1080
端口：留空

**Comment by wordlesswind** [comment]
似乎与 Proxy SwitchyOmega 无关。
