### ISSUE TITLE
如何填写sock5的代理密码呢？

### ISSUE THREAD

**Issue by sukinga** [FelisCatus/SwitchyOmega#236]
没找到对应填密码的地方。。
特意注册一个git的账号来问问题。。

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
由于 Chrome 浏览器限制， SOCKS5 代理不能设置用户名密码。关于这一点请到 Chromium 项目反馈。
