### ISSUE TITLE
自动切换模式根本就不行啊

### ISSUE THREAD

**Issue by kuerck** [FelisCatus/SwitchyOmega#237]
SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.91 Safari/537.36

**Comment by learningendless** [comment]
我感觉翻墙很顺利哈，比以前爽多多了

2015-01-27 20:48 GMT+08:00 kuerck <notifications@github.com>:

**Comment by FelisCatus** [comment]
请注意自动切换模式需要经过一定的设置才可以使用。

如果希望针对某地区网络现状来设置自动切换模式，只对某些特定网站使用代理，请参考 GFW List 相关使用说明，如GoAgent提供的教程。如果不知道该如何设置，可以[导入这个备份文件](https://switchysharp.googlecode.com/files/X_GFWList.bak)作为起点。（注意导入后需要重新设置代理服务器）
