### ISSUE TITLE
WARNING: extension injects malicious script into all pages

### ISSUE THREAD

**Issue by ivanstus** [FelisCatus/SwitchyOmega#2374]
### Problem description

Extension injects malicious script.

See https://gist.github.com/ivanstus/37494f19612c90ebeb999538c9f30dd0

**Comment by xpufx** [comment]
Where in this repo is that?

**Comment by ivanstus** [comment]
Extension from Chrome Web Store is clean.
Extension from Microsoft Edge Store by third-party publisher is modified with malicious script injection.
My apologies, issue closed.

**Comment by mateuszdrab** [comment]
The malicious extension dijmmgblneagkcdganednabkbgjmceoe	Proxy SwitchyOmega appears to have been removed from the market place now.
