### ISSUE TITLE
快捷键

### ISSUE THREAD

**Issue by vvami3** [FelisCatus/SwitchyOmega#238]
SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.117 Safari/537.36
我觉得有个快捷键切换代理选项会更加好用

**Comment by FelisCatus** [comment]
按快捷键 Shift+Alt+O 可弹出菜单，然后在菜单里按下问号就能查看每个情景模式的热键了。当然，如果嫌按两次还不够快，也可以去设置里开启快速切换，这样只要按 Shift+Alt+O 就足够了。
