### ISSUE TITLE
希望在情景模式中增加一个系统代理

### ISSUE THREAD

**Issue by weeeins** [FelisCatus/SwitchyOmega#2390]
<img width="530" alt="image" src="https://github.com/FelisCatus/SwitchyOmega/assets/104344128/0336e03a-23dd-4aac-a772-ade48b973b3b">

可以在情景模式中增加一个系统代理的选项吗？

有一个需求，本机有公司的代理VPN，有些网页需要走公司VPN访问，其他网址我想走自己的VPN访问，
公司提供的VPN，没有本地代理端口，没有办法配置到插件里面，但是选择系统代理就可以通过公司VPN访问公司的特定网址

SwitchyOmega 2.5.20
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.35

**Comment by march1993** [comment]
没有本地端口那就是系统路由，选择直连连接就是系统路由了

**Comment by weeeins** [comment]
OK，谢谢
