### ISSUE TITLE
弹出菜单键盘导航

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#24]
English title: Keyboard navigation in the popup menu.

现在的弹出菜单还不能用方向键或者 tab 键选择项目，不是很方便。之后可以试试看做这个，顺便加上默认快捷键，就相当于实现快捷键操作了。

For now, the popup menu items cannot be navigated using arrow keys or tab. We can add this feature later so that switching profiles without mouse would be possible.

**Comment by WayneXuan** [comment]
虚拟情景模式和临时规则的弹出列表不能用JK键导航
建议增加一个键绑定(比如空格),弹出子列表并设置焦点,然后用JK选择子项

另外用T键弹出临时规则时也应该能用JK选择子项

**Comment by FelisCatus** [comment]
回车可以打开菜单项目的弹出列表，用 TAB 键和 SHIFT+TAB 键可以在子项目中切换。

**Comment by WayneXuan** [comment]
回车可以打开临时规则弹出列表,但是虚拟情景模式的弹出列表怎么办?

**Comment by FelisCatus** [comment]
选中虚拟情景模式的时候 TAB 然后回车即可。
