### ISSUE TITLE
记录 Proxy 密码的问题

### ISSUE THREAD

**Issue by gaocuo** [FelisCatus/SwitchyOmega#240]
Chrome 有个很讨厌的问题，就是无法记录 Proxy 的用户名密码，很多运营级的 Proxy 都会加上用户名密码，因此，每次弹出输入用户名密码的窗口还没法记录输入过的内容就很麻烦了。

原本我使用的是 https://chrome.google.com/webstore/detail/proxy-auto-auth/ggmdpepbjljkkkdaklfihhngmmgmpggp  这个插件来帮助存储密码自动输入的，在没有使用 Switchy 之前，它可以正常工作，但是使用了 switchy 以后，还是会出现输入密码的框，虽然可以点击取消让 proxy-auto-auth 继续工作，但是感觉还是不流畅。如果 Switchy 可以加入proxy-auto-auth就很完美了。

SwitchyOmega 2.3.0
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2285.2 Safari/537.36

**Comment by FelisCatus** [comment]
这个功能已经做了，在输入代理地址和端口的右侧有一个小锁图标的按钮。

**Comment by ynyounuo** [comment]
PAC Mode 如果能行的话，麻烦也添加小锁吧

**Comment by FelisCatus** [comment]
@ynyounuo 相关讨论见 #190 ，我已经在努力做了。

**Comment by learningendless** [comment]
这个项目跟后来的GreatAgent是什么关系啊？GreatAgent不是GoAgent的后续版本吗？现在出来个SwitchyOmega，这都是什么关系啊

2015-01-29 18:59 GMT+08:00 FelisCatus <notifications@github.com>:

**Comment by FelisCatus** [comment]
@learningendless: 本项目和 GoAgent 等项目无关。SwitchyOmega 是设置软件，不是代理软件或翻墙软件。

@ynyounuo 提醒一下， PAC 的用户名密码已经能设置了。如果你之前已经看到了就无视我吧。
