### ISSUE TITLE
配置浏览器代理规则不生效

### ISSUE THREAD

**Issue by Nick-Nice** [FelisCatus/SwitchyOmega#2416]
配置浏览器代理且http://127.0.0.1:8899/可以正常打开
<img width="820" alt="image" src="https://github.com/FelisCatus/SwitchyOmega/assets/53433576/33252bb1-e4dc-44fc-8364-8cde028083ae">

配置规则
1、127.0.0.1:3000 https://local-qa.com。 https://local-qa.com并不能打开本地启动的服务

2、https://local-qa.com 127.0.0.1:3000 反过来配置亦是如此

在第二种配置方式下配置全局代理情景模式选用系统代理就可以生效 ， 但是使用浏览器代理怎么都无法生效。

不知这种情况是否有人遇到，是否有解决办法不使用全局代理只使用浏览器代理呢

SwitchyOmega 2.5.21
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36

**Comment by AnyWAT** [comment]
说的啥哟？链接与非链接的文本之间得有个空格
