### ISSUE TITLE
能不能提供一个简洁的界面?

### ISSUE THREAD

**Issue by xwj1003** [FelisCatus/SwitchyOmega#242]
我的切换规则是在是太多, 但是你们的界面是一行一条规则,就导致有页面显示过大.我希望改成用textarea来存储规则.一行里的"条件设置"可以存储多个条件.可以用分号或者一行一条
比如:
域名通配符  *.x1.com;*.x2.com;*.x3.com;
域名通配符  *.x4.com
                    *.x5.com
                    *.x6.com;

**Comment by FelisCatus** [comment]
见 #80.
