### ISSUE TITLE
自动切换可用系统代理

### ISSUE THREAD

**Issue by yige-yigeren** [FelisCatus/SwitchyOmega#2421]
如题，希望能添加该功能

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.188

**Comment by AnyWAT** [comment]
将系统代理的协议、端口设置为某情景模式，再添加与该情景模式配套的AutoSwitch。。。
系统代理经常会影响系统。。。一般不要开启？
