### ISSUE TITLE
建议选项中 “默认情景模式” 新增一个“系统代理”的选项

### ISSUE THREAD

**Issue by junxy** [FelisCatus/SwitchyOmega#243]
`直接连接` 会导致系统设置的 PAC 失效

BTW: UX 设计好赞！

**Comment by FelisCatus** [comment]
可以新建一个情景模式，把系统的 PAC 设置复制进来。技术上做不到在自动切换中直接读取系统代理。

**Comment by junxy** [comment]
Oh. Yeah :+1:
