### ISSUE TITLE
插件自动关闭

### ISSUE THREAD

**Issue by mushroom927** [FelisCatus/SwitchyOmega#2440]
最近每天笔记本开机打开chrome，然后就发现上不去，看了一下插件竟然被关闭了；然后手动打开，用着正常，再开机既然又被关闭，另一台win10笔记本，相同google账户却没这个问题。

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by AnyWAT** [comment]
![image](https://github.com/FelisCatus/SwitchyOmega/assets/37962734/7baf120d-6689-4ec3-8aa3-cc63e7e049af)
神马关闭，无非此处被设置成“直接连接”而已？

**Comment by mushroom927** [comment]
不是，这里是正常的。我的意思是chrom上这个插件图标都没有了，要再进插件管理再打开。
![issue](https://github.com/FelisCatus/SwitchyOmega/assets/55771167/c16e37b5-4aa8-434b-a672-2e9c0ce487af)

**Comment by AnyWAT** [comment]
系统上的国产杀毒、卫士、管家之类干的？

**Comment by mushroom927** [comment]
我从来不装这些国产流氓，连QQ、微信都没装呢。

之前一直都正常，就最近突然出现，最近只折腾过油猴，但也不确定是否和这个有关系。
因为油管广告拦截adblock被识别出来了，试了一下油猴上的广告加速脚本。好像是从那之后没多久出现这个问题了，但即使禁用油猴广告加速脚本，还是有这个问题。除了每次要手动开启一下，其他也用着正常，搞不明白。

**Comment by xianyuli** [comment]
是的，启用Proxy SwitchyOmega之后，重启浏览器，Proxy SwitchyOmega又会被自动禁用，需要手动启用

**Comment by AnyWAT** [comment]
试试：备份 Proxy SwitchyOmega 后卸载它，重启浏览器后再次安装它，从备份恢复。。。

**Comment by xianyuli** [comment]
> 我从来不装这些国产流氓，连QQ、微信都没装呢。
> 
> 之前一直都正常，就最近突然出现，最近只折腾过油猴，但也不确定是否和这个有关系。 因为油管广告拦截adblock被识别出来了，试了一下油猴上的广告加速脚本。好像是从那之后没多久出现这个问题了，但即使禁用油猴广告加速脚本，还是有这个问题。除了每次要手动开启一下，其他也用着正常，搞不明白。

我的问题找到了，是因为我最新更新了另外一个代理软件，所以那个软件获得了网络代理的优先权，我卸载之后Proxy SwitchyOmega已经正常使用

**Comment by mushroom927** [comment]
> 我的问题找到了，是因为我最新更新了另外一个代理软件，所以那个软件获得了网络代理的优先权，我卸载之后Proxy SwitchyOmega已经正常使用

感谢分享！在你的提示之下，我也又去逐一查看了每个插件，发现有个隐藏ip 的插件上次无意间打开了，关闭之后就正常了。再次感谢🙏
