### ISSUE TITLE
I can't download profile for autoswitch mode when I use goagent mode plz fix it 

### ISSUE THREAD

**Issue by gloryming** [FelisCatus/SwitchyOmega#248]
SwitchyOmega 2.2.14
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
This should be a network issue or problem with GoAgent. You can try to apply the GoAgent profile and visit the URL to the rule list directly in your browser. Make sure that succeeds before you blame SwitchyOmega.
