### ISSUE TITLE
“直接连接”选项消失

### ISSUE THREAD

**Issue by kingdom017** [FelisCatus/SwitchyOmega#249]
有时候点开的时候最上方的“直接连接”选项会消失
![79c4447b-37c4-4701-8955-1172bbea775c](https://cloud.githubusercontent.com/assets/7686144/5986046/d7932306-a927-11e4-9f83-c40d6cf25419.png)

SwitchyOmega 2.3.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by FelisCatus** [comment]
Mac OS X 下 Chrome 弹出窗口显示不正常的情况，是已知的 Chrome 浏览器故障，与本项目无关。建议到 Chrome 那边反馈。
