### ISSUE TITLE
auto switch没有系统代理

### ISSUE THREAD

**Issue by 380561016** [FelisCatus/SwitchyOmega#2496]
有的网站需要用系统代理才能打开

SwitchyOmega 2.5.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by 380561016** [comment]
已解决

**Comment by sungod-one** [comment]
请问你如何解决的呢

**Comment by AnyWAT** [comment]
将系统代理的协议、端口设置为某情景模式（代理服务器），再添加与该代理服务器配套的AutoSwitch。。。
