### ISSUE TITLE
自动切换的时候不能看出一个URL是否走了代理

### ISSUE THREAD

**Issue by hheedat** [FelisCatus/SwitchyOmega#250]
旧版在自动切换的时候，走代理和不走代理的图标是不一样的
走的时候会亮成蓝色，不走的时候则是灰色
现在自动切换模式下，走和不走代理，显示的都是绿色，有时候会照成一些不方便，希望能做些区别

SwitchyOmega 2.3.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
图标应该已经做了显示，请看外圈颜色。
