### ISSUE TITLE
Old laptop works, new laptop just passes the direct IP

### ISSUE THREAD

**Issue by truthsword** [FelisCatus/SwitchyOmega#2502]
Working fine on Win10 laptop. but new W11 laptop, I get direct connection only. I exported settings from W10 to W11 PC and it looks the same, but fails to give me proxy IP.

I'm using LibreWolf browser (Firefox fork), and I vaguely remember having to tweak about:config on the W10 PC... so maybe that is the problem. But I can't recall the setting I changed, and Google has been unhelpful. Does this sound familiar? Appreciate any help.

BTW, I also have this running on a W11 desktop, but no luck here.

**Comment by SadPencil** [comment]
I had the same problem. And then I realized that the switchy omega extension provided by Firefox Add-Ons has lower version than the latest release (v2.5.20). Uninstalling the extension and re-installing it from GitHub Release solves my problem.

**Comment by truthsword** [comment]
Maybe that was it. In the meantime, I copied my Firefox profile from a working installation to the new laptop, and all is now well. Presently I'm on **v2.5.20resigned1**
