### ISSUE TITLE
FEAT: autoswitch 功能提升，衍生资源走同样的 rule

### ISSUE THREAD

**Issue by JooDye** [FelisCatus/SwitchyOmega#2503]
### Browser version & OS version / 浏览器名称、版本及操作系统版本
Google Chrome / Version 126.0.6478.55 (Official Build) (64-bit) / Debian 12 x86_64 Linux 6.1.0-12-amd64

### Problem description / 问题描述
我设置了 *.bilibili.com 用 Direct ，但其实无论是视频播放还是其他资源的加载，其实都走了 Default （即 proxy），能否做成 *.bilibili.com 下所有资源都走 Direct？
![image](https://github.com/FelisCatus/SwitchyOmega/assets/33674169/1b0ad545-551e-448d-a348-6fbe43acb7b0)
![image](https://github.com/FelisCatus/SwitchyOmega/assets/33674169/67d2bd36-3145-4cbc-a3fa-dbc1caba7f60)
![image](https://github.com/FelisCatus/SwitchyOmega/assets/33674169/13b81a94-d816-4713-8b3d-cfe3baa712a1)

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

#### Steps to reproduce issue / 重现错误所需步骤
autoswitch rule: 默认走代理，命中规则走 Direct，然后开一个 tab （或者匿名窗口，让 switchy omega 能在匿名模式下使用），访问走 Direct 的网站，能看到网页如上图所示

#### Expected behavior / 期望发生的情况
以 *.bilibili.com 走 Direct 的规则为例，其所有衍生资源都走 Direct，使用体验是即使关掉我的梯子，autoswitch 模式下该走 direct 的网页都能正常显示

**Comment by AnyWAT** [comment]
貌似有黑、白名单之分。。。如果【规则列表网址】为 https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
即为黑名单，【默认情景模式】应为 Direct 【规则列表规则】应为 proxy
白名单如 https://github.com/breakwa11/gfw_whitelist

**Comment by AnyWAT** [comment]
明白你的意思了——你不用 GFW list 而自建列表。。。
刚试了下，按 Default = Proxy 设置了 *.bilibili.com 用 Direct 并退出终止了代理，是可以（关掉梯子而）正常浏览的。。。（另外2项是提示未加载资源而点击再自动添加的）
![image](https://github.com/FelisCatus/SwitchyOmega/assets/37962734/42ddc386-2afd-4a85-b24f-074c1af1eb44)

> 让 switchy omega 能在匿名模式下使用

不是有这个？
![image](https://github.com/FelisCatus/SwitchyOmega/assets/37962734/d0aec69d-5296-4514-8ba1-187296ac6bdc)
