### ISSUE TITLE
使用代理与不使用代理时，图表的区别太不明显

### ISSUE THREAD

**Issue by potato-zyg** [FelisCatus/SwitchyOmega#251]
例如我访问微博的时候是不使用代理的，而我访问facebook时，经过代理，但是在这两种模式下图表的区别太不明显，希望能够更改，谢谢

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
见 #107.
