### ISSUE TITLE
点击button后界面

### ISSUE THREAD

**Issue by liuan** [FelisCatus/SwitchyOmega#252]
点击插件图标出现的选择列表，可以最大化的自定义不？ 最好就可以只留下直接连接和GoAgent两个选项，选项，反馈什么的，都可以自定义删除，这些一般都用不着。
多谢了。

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36

**Comment by FelisCatus** [comment]
请用快速切换功能，谢谢。

**Comment by liuan** [comment]
多谢～ 这个功能真是太酷了～
