### ISSUE TITLE
使用公网IP作为代理的话不管加不加密码，隔一段时间就被各种乱七八糟的IP连接了

### ISSUE THREAD

**Issue by 8RedBulls** [FelisCatus/SwitchyOmega#2528]
SwitchyOmega 2.5.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0

**Comment by AnyWAT** [comment]
与此扩展何干？不会是代理软件开启了系统代理？

**Comment by 8RedBulls** [comment]
干,被人当肉鸡了，我这VPS都是自己装的MSDN的win7，估计是开始的时候端口全开被人干了，现在只开几个端口就没事了....
![3e967f41e7fc70dcc0b42ba94515684](https://github.com/user-attachments/assets/5d26ab1b-5efe-438d-97d7-d8d06068abd9)

**Comment by AnyWAT** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232
