### ISSUE TITLE
SwitchyOmega-dns远程解析bug，翻墙网址会向本地dns提交dns解析，本地dns会返回错误的ip，从而会记录谁几时登陆了某网址！

### ISSUE THREAD

**Issue by SwitchyOmega-dnsbug** [FelisCatus/SwitchyOmega#253]
SwitchyOmega-dns远程解析bug，翻墙网址会向本地dns提交dns解析，本地dns会返回错误的ip，从而会记录谁几时登陆了某网址！
试验环境，
1，A机器xp，原版，
2，安装有wireshark，截获dns数据
3，本地设置114.114.114.114dns
4，chrome浏览器，安装SwitchyOmega，设置127.0.0.1:65500的socks5代理
5，shadowsocks代理。
截获步骤：
一、
1，无论设置SwitchyOmega自动代理，gfwed，登陆youtube.com，youtube可以打开，说明选择了正确的远程dns解析ip
2，wireshark，抓取数据包。
3，wireshark，分析中包含，有114返回的错误ip
![123](https://cloud.githubusercontent.com/assets/10794158/5991448/3b712acc-aa2b-11e4-9299-921960c241c1.jpg)

结论：说明浏览器向远程ip和本地dns都发送了dns解析请求，但是只选择了远程的dns解析ip，但是同时本地的114上会有，某时间点本机所在外网ip请求了youtube。com的记录。如果倒查就爆菊了。

如果某人不想让某人知道自己上了某网址。那么这样就无法实现。
如果不想发送本地dns请求就要将dns设置成空，那么就不会去本地发送dns解析。但是问题又来了，如果在自动模式下，未翻墙网址就打不开了。

综上所述：
我的意思就是说能不能设置成翻墙dns解析走远程，强制不发送dns本地解析。谢谢开发者！

**Comment by FelisCatus** [comment]
应该是 Chrome 浏览器问题，和本项目无关。

关于这个问题，我写了[一点相关的信息](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy)，供各位参考。

**Comment by liaoyaoheng** [comment]
@FelisCatus 正常的话，dns是否同样直接使用代理？谢

**Comment by celeron533** [comment]
@liaoyaoheng 正常情况下所有dns请求过代理

**Comment by liaoyaoheng** [comment]
@celeron533 chrome 45的话应如何设置？已关闭预加载，其他需要关闭吗？谢

**Comment by celeron533** [comment]
@liaoyaoheng 
我都没有勾选

![image](https://cloud.githubusercontent.com/assets/3608762/10045940/a99f84ba-6238-11e5-873a-96d04d948aa3.png)
