### ISSUE TITLE
流量偷跑

### ISSUE THREAD

**Issue by hu6360567** [FelisCatus/SwitchyOmega#254]
1. 貌似还是会有流量偷跑，比如通过http://tv.sohu.com/sports/cbalive/ 看CBA直播的时候，会有流量没有从代理出去
2. 另外能否通过DNS本地解析？如果解析IPV6地址，则不走代理；如果是IPV4地址，则走代理

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by FelisCatus** [comment]
1. Flash 插件会有不遵从浏览器代理设置的问题。这是已知的Chrome和Flash的问题，与本项目无关。
2. 本项目只是设置软件，不进行网络相关的操作。应该也做不到进行 DNS 请求。

**Comment by FelisCatus** [comment]
P.S. 可以在代理情景模式的“不代理的地址列表”中添加`::/0`一行来是所有 IPv6 地址不经过此代理。

**Comment by hu6360567** [comment]
但是对通过域名访问的网页，仍然无法使用该规则

**Comment by FelisCatus** [comment]
@hu6360567 那我也没办法了，毕竟是靠 Chromium 提供的 API 来做这个事情……
