### ISSUE TITLE
进无法找到该页的网站无法为该网站选择代理规则浏览

### ISSUE THREAD

**Issue by cikenerd** [FelisCatus/SwitchyOmega#255]
比如我打开twitter.com，如果不翻墙的话会显示无法找到该页。这个时候我希望为这个网站添加规则那我就必须切换到能用的代理把这个网站打开然后再为这个网站添加规则。

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36

**Comment by FelisCatus** [comment]
我这里是可以在"This webpage is not available"之类的错误页面上使用弹出菜单添加的。如果你那边确实不能，请在页面加载错误时，点开弹出菜单并截图。另外，以防万一，请告知所使用的浏览器。

**Comment by cikenerd** [comment]
感谢回复，刚刚试了以下windows下面google-chrome是能够添加的，但是linux（linuxmint，google-chrome）下也是不能添加的。之前用的是360极速浏览器。

**Comment by FelisCatus** [comment]
我这里 Linux + Chromium 40~42 均测试正常。如果你的电脑上不能用，请给出详细的浏览器版本号。以及，考虑到 Chrome 的网络诊断服务可能影响结果，请给出错误页面的截图。

此外，360极速浏览器不在支持范围内。如果能用就能用，不能用我也没办法。

**Comment by cikenerd** [comment]
版本 40.0.2214.94 (64-bit)
![](http://www.tu265.com/di-ae292b8369d95c03fbb21169154d60d6.png)

**Comment by FelisCatus** [comment]
你好，在“系统代理”情景模式下，无法添加规则。请使用自动切换规则后再试。
