### ISSUE TITLE
chrome商店提示: 此扩展程序未遵循 Chrome 扩展程序的最佳实践，因此已无法再使用。

### ISSUE THREAD

**Issue by AsserHong** [FelisCatus/SwitchyOmega#2554]
### Problem description / 问题描述

(Please provide as much detail as possible. We recommend the following format.)
(请尽可能多提供一些细节。我们推荐使用下面的格式。)

操作系统：
windows
chrome版本：
131.0.6778.205（正式版本） （64 位）
chrome 商店提示：
此扩展程序未遵循 Chrome 扩展程序的最佳实践，因此已无法再使用。

#### Steps to reproduce issue / 重现错误所需步骤
访问chrome商店，打开

(What did you do? / 你做了什么？)

#### Expected behavior / 期望发生的情况
proxy-switchyomega仍可支持

**Comment by AnyWAT** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232

**Comment by AsserHong** [comment]
> [#2513 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232)

thx a lot
