### ISSUE TITLE
2024.12.23谷歌浏览器强制关闭该插件

### ISSUE THREAD

**Issue by ouengai** [FelisCatus/SwitchyOmega#2556]
2024.12.23谷歌浏览器强制关闭该插件，提示“此扩展程序未遵循 Chrome 扩展程序的最佳实践， 因此已无法再使用。”。

**Comment by AnyWAT** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232

**Comment by ouengai** [comment]
> [#2513 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/2513#issuecomment-2218665232)

谢谢！

**Comment by Wings168** [comment]
可以进管理页详情界面，强制打开

**Comment by devishell** [comment]
使用 edge 未遇到此情况
