### ISSUE TITLE
你好，是否可以增加当前页面是否正在使用代理的提示？

### ISSUE THREAD

**Issue by simonsww** [FelisCatus/SwitchyOmega#256]
你好，总体使用体验不错，不过目前缺少一个当前页面是否正在使用代理的，还是使用直连的提示，可以将插件图标进行变化，换一种图标。比如google商店里的红杏插件，如果在使用插件中，会图标会变绿色，未使用插件会变灰色。

因为有这样的应用场景：我只需要对某些域名进行代理，但有时候，我设置了规则，但不知道是否已经生效了或者我浏览页面的时候，需要知道当前页面是否使用的代理通道。

希望你能明白我的意思。

SwitchyOmega 2.3.0
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
您好，请确认是否正在使用自动切换模式，而不是全局代理模式。如果扩展正常工作，自动切换模式下图标会根据当前页面变化。

如果自动切换无法正常工作，请告知您的设置（截图或导出备份文件）。

**Comment by simonsww** [comment]
可以了，我使用最新版，换了个ss客户端就正常了。
