### ISSUE TITLE
你好，是否为bug？

### ISSUE THREAD

**Issue by simonsww** [FelisCatus/SwitchyOmega#257]
我使用了自动切换情景，使用shadowsocks，sock5代理。

勾选了GFW规则，打开百度首页，但是抓包发现对于GFW未匹配到的域名，竟然也是走代理通道，为什么不是走直接连接？
比如请求里有一个URL，http://s1.bdstatic.com/r/www/cache/static/jquery/jquery-1.10.2.min_f2fb5194.js
对于未知的域名连接，插件应该是直接连接，这样才能提供更好的连接速度吧，只需要对需要代理的请求进行代理即可。

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
这两个问题应该都是和自动切换的设置有关，请移步 #256 讨论。
