### ISSUE TITLE
能否考虑添加切换代理的快捷键

### ISSUE THREAD

**Issue by Mark-Shine** [FelisCatus/SwitchyOmega#259]
在使用中，经常需要用到切换代理。

SwitchyOmega 2.3.1
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by FelisCatus** [comment]
见 #238。快捷键都已经支持那么久了，还是有人在问吗……

也许是时候做一个快捷键提示了。
