### ISSUE TITLE
about settings backup/restore

### ISSUE THREAD

**Issue by Twilight** [FelisCatus/SwitchyOmega#260]
what does the revision field mean? I'm writing my own config generation script.

anyway, simply using "revision": "0" does work, I'm just wondering

**Comment by FelisCatus** [comment]
The revision field is [a timestamp-based hexadecimal number](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-pac/src/utils.coffee#L2-L4) representing the last modification time to a given profile. This is used to select the newer version in case of conflict (e.g. between the local and synced copy.)

You can get the revision based on the current datetime using `new Date().getTime().toString(16)`. However, as you have pointed out, that is not required for creating a backup file. Using `"0"` will work fine in most cases. After importing, the revision field will be updated (with correct value) whenever the profile is changed.

**Comment by Twilight** [comment]
thanks for your clearification
