### ISSUE TITLE
Proxy Java Applet requests

### ISSUE THREAD

**Issue by cpiment** [FelisCatus/SwitchyOmega#261]
Hi,

I have detected that requests made from a Java Applet are not proxified using the Auto Switch option. Is there any way to override that behaviour?

Thanks for the terrific extension!

Regards,
Carlos

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by FelisCatus** [comment]
I don't think Java Applets use Chrome network internals. Therefore they follow system (environment) proxy settings. This, of course, cannot be controlled in Chrome, and thus is not affected by extension-provided settings.

You may want to set the system proxy to a PAC file functionally identical to the Auto Switch mode. Such a PAC file can be exported using the "Export PAC" button on the Auto Switch options page.
