### ISSUE TITLE
导入goagent配置卡死

### ISSUE THREAD

**Issue by testlxf** [FelisCatus/SwitchyOmega#263]
导入goagent配置卡死。不知是什么原因。以前是可以的。

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
最近配置导入的代码有变动过，可能是bug。这类情况比较难调试，不过建议在导入卡死后，打开弹出菜单并选择“错误日志”功能，应该可以获取到一个日志文件，然后把日志文件上传到 https://gist.github.com

**Comment by FelisCatus** [comment]
暂时先关闭了。这个问题似乎是个例，而且没有提供配置和错误日志的情况下实在是不知道发生了什么。

此外GoAgent项目或者其他试图导入GoAgent配置的用户从没反映过这类问题……我导入过没发现问题。怀疑和之前的特定设置有关，或者之前配置已经损坏。

如果有详细信息请重新开启此 issue.

**Comment by testlxf** [comment]
先不管它了。现在goagent已不能用了。改用影梭了。
2015年2月21日 上午11:00于 "FelisCatus" <notifications@github.com>写道：
