### ISSUE TITLE
选自动切换模式，使用代理和没使用代理，颜色不会变化

### ISSUE THREAD

**Issue by jaytin** [FelisCatus/SwitchyOmega#265]
SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by jaytin** [comment]
然后各个代理的颜色不知道哪里改

**Comment by in-out** [comment]
点profile左边的颜色那里就能调出调色盘
