### ISSUE TITLE
在切换情景模式时，当前网页会自动刷新

### ISSUE THREAD

**Issue by mczoden** [FelisCatus/SwitchyOmega#266]
在切换情景模式时，当前网页会自动刷新

假设SwichyOmega工作在某一非auto switch模式下，
这时，用户配置了一条新的auto switch规则，并需要切换到auto switch，
所在网页会自动刷新一次，
这可能导致一些会话中断并重连，这是用户所不期望的。
SwitchSharp不会出现自动刷新的状况。

BTW，非常感谢开发者的奉献精神。

SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
这都是可以设置的。你看看用户界面选项那里的“当更改情景模式时刷新当前标签”有没有勾选。如果有的话就取消选中吧。

**Comment by mczoden** [comment]
问题已解决，非常感谢！
