### ISSUE TITLE
安装了之后，我的网络设定出现问题。chrome和IE无法下载了，但可以浏览网站。

### ISSUE THREAD

**Issue by GOGOGOPAL** [FelisCatus/SwitchyOmega#267]
Windows 7 ultimate正版操作系统，
使用最新版Chrome和IE,
在安装了switchyomega之后，我留意到我IE connection之中多出了三个DIAL/VPN：QeeYou, QeeYou2, QeeYou3.
当时还是正常，我还可以下载东西，浏览网页也是无所谓，但是我重启电脑之后，无法连接我本身的wifi，我无奈之下只好把这三个拨号和VPN删除，然后还是无法连接WIFI，于是我便用连接线直接连接上网，上网了之后，我disable了switchyomega但没有删除，然后把这三个QeeYou，2，3分别删除。结果现在出现的状态就是我可以连接我本身的WIFI了，很奇怪我网页是能打开，但都无法下载东西了。
请求帮助！
谢谢！

**Comment by FelisCatus** [comment]
SwitchyOmega 并不含有任何本地代码，也不修改系统设置，更不会添加VPN……

您这种情况肯定是因为安装了别的软件。（按照名字来看，是“奇游网游加速器”？）所以当然，禁用或者删除 SwitchyOmega 也没用的，因为那根本就不相关。

**Comment by GOGOGOPAL** [comment]
那是我搞错了，抱歉。麻烦你了。
