### ISSUE TITLE
在自动切换模式下会被部分网站检测出使用了代理

### ISSUE THREAD

**Issue by lyonlion** [FelisCatus/SwitchyOmega#270]
同一个HTTP代理服务器，如果直接用情景模式能正常突破该网站对于代理的检测

但是在自动切换模式下就会被检测出使用了代理

希望能改进一下这个

**Comment by FelisCatus** [comment]
部分网站的服务器似乎会要求网页本身，以及某些网页资源来源于同一个 IP 。正如楼主所说，解决方式是对于这些资源全部使用同一个代理。

但从技术角度而言，如果要求扩展保证这一点，实际上就是要求扩展对于同一个标签页的所有资源使用相同的代理服务器。由于扩展的原理是生成 PAC 脚本，而 PAC 脚本中只能获取请求URL，而不含标签页信息，也不含 HTTP headers （比如可能有用的 Referer），从而无法实现此功能。

chrome.webRequest 可以获取很多关于网络请求的信息，也可以修改/重定向/取消网络请求，但却无法指定其使用的代理服务器。

所以我想这里的结论是，扩展不太可能完成这样的任务。一个可能的备用方案是，找出某个网站所有的资源请求（通过F12开发者工具，或者`chrome://net-internals/#events`，或者利用扩展），然后设置自动切换模式，让这些资源和网页本身都走某个情景模式的代理。当然，这样会比较麻烦，但至少做得到。
