### ISSUE TITLE
自动升级到2.3.2，代理无法链接到服务器

### ISSUE THREAD

**Issue by ChristineXYS** [FelisCatus/SwitchyOmega#271]
忽然发现无法链接到服务器。

SwitchyOmega 2.3.2
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
1. 请检查代理服务器工作情况，并检查代理服务器设置是否存在问题。
1. 可以查看 `chrome://net-internals/#proxy` 页面内容，并将那边显示的内容复制到这里。

**Comment by droid-Q** [comment]
同样的问题，求解，Effective proxy settings

PAC script: data:application/x-ns-proxy-autoconfig;base64,LypPbWVnYVByb2ZpbGUqIlx1MDAyZnU4MWVhXHUwMDJmdTUyYThcdTAwMmZ1NTIwN1x1MDAyZnU2MzYyXHUwMDJmdTZhMjFcdTAwMmZ1NWYwZiIqMTRiN2IyMTY3

总是显示找不到代理服务器。

**Comment by FelisCatus** [comment]
请问情况如何了？如果问题仍然存在，请提供以上信息以供分析，并重新开启此issue.
