### ISSUE TITLE
关于状态栏的快捷菜单请大家提出各自的意见和需求

### ISSUE THREAD

**Issue by Tback1** [FelisCatus/SwitchyOmega#273]
我现在是启用了wall和ss两种代理，让后设定了自动代理，另外开了一个虚情景做切换。

![image 2](https://cloud.githubusercontent.com/assets/8872546/6126244/79747218-b159-11e4-8cc9-b04316ac7a6f.png)

问题是，最开始我我如果用着自动切换做默认，让后某个代理暂时速度不理想了，我要在ss和wall之间切换的时候，这逻辑居然不是切换代理，而是去切换虚情景。反正我都不知道怎么去描述这个逻辑，虽然我用的挺舒坦，可是真有点不符合UI逻辑啊，明明是切换自动切换的代理，结果要去切换一下虚情景的设置。而且这个设置对以前的一个问题里的某个强制不走代理的问题没有解决。

总的来说，我还是觉得逻辑很混乱。虽然我自己已经习惯了。不过既然邮件列表在说这个问题，我觉得还是发出来大家讨论一下改进的办法，尤其是现在要出firefox版本。对比autoproxy，在逻辑上的混乱真的是缺乏竞争力啊

**Comment by FelisCatus** [comment]
行吧，多讨论一下是好事。尽管如此，我需要先说明，这个项目不是翻墙软件，只是代理设置软件。竞争目标也许一开始就不是 AutoProxy ，而是 FoxyProxy 等软件。讨论如何使得UI更易用、逻辑更简明是好事，但也要注意到翻墙最多只是一种可能的使用场景，不要所有事情都从翻墙出发，影响了其他使用场景就好。

**Comment by Tback1** [comment]
autoproxy也没自带fq啊？最多也就是创作了最广为流传的订阅列表，omega不也用了这玩意不是？

就是因为不是只考虑fq所以才有白名单无法实现的描述在前面。
而且不管怎么说，浏览器里的代理管理本质不就是哪些网页走这个代理 哪些走另外一个 哪些不代理么？

难不成还要跟公司配置一样 做端口级别的匹配过滤？抢ISA饭碗？

而且话说回来，fq不是全部但是至少是主流用途对吧？

要我说的话现在的逻辑我用起来也没多大问题了，也就是学习成本高了一点，上手慢一些，配置里手工调教的成本高一些，很多切换得每次进去手工再改改，复杂的部分包括PAC都能基本上依靠omega自身解决了。

但是上手难度大，，真是omega追求的？

想想auto proxy，在Firefox19就停止了支持与开发，结果呢，到现在fox
proxy也没法取代他，用户自己fork代码修改支持到了35，nightly40都还能用。

我的感受还是一个代理，auto proxy和omega没区别，多个代理切换auto proxy全胜。

如果有更好的omega切换逻辑或者配置方法，请不吝赐教，我要赶紧学会。谢谢




2015年2月10日 下午8:12于 "FelisCatus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
@Tback1 您先别激动，我说这些也只不过是为了尽可能避免招来过多主观性太强的评论而已，绝对没有针对您的意思。您刚才提出的大部分观点我都赞同，所以您和我争论这个也没什么意义。

但后半段您都是在抱怨 omega 上手难度大，不如 auto proxy ，这感觉有点太宽泛，并不能对项目起到建设性的作用。目前可能是没有什么“更好的omega切换逻辑或者配置方法”，但这正是这个 issue 需要讨论并实现的。

评述 AutoProxy 的成功之处，或者指摘 SwitchyOmega 的有所不足，都是非常欢迎的。像之前的讨论“AutoProxy 这一点做得非常好，想想怎么整合到 SwitchyOmega 的现有模型中，或是废除现有模型中存在的概念混乱”都是很好的，而且相信大家也看到了一些成果了。为了达成更简洁易用的目的，我们这次要在之前的基础上，更激进一点。当然，也不用激进到“SwitchyOmega 该全盘否定，完全做成 AutoProxy 的翻版最好”啦 :) 。

我需要再一次说明，项目最开始的规划和代码实现基本都只有我一个人在做，有所考虑不周，或者脱离了实际都是有可能的。虽然之前有过很多的讨论，但也只改进了一部分而已。目前我的建议是，您不妨畅所欲言，提出您认为最合理的解决方案，然后再让我将其变成现实。

**Comment by Tback1** [comment]
​@FelisCatus
​ 是有点激动了。不过没感觉你针对我，只是chrome上的代理配置软件一直是个短板，这么多年都干不过firefox，老是用着两个浏览器挺烦人的，好不容易看着omega有希望了，当然希望这独苗能prefect不是。

就怕独苗因为没竞争就裹足不前了啊。

说实话，有些东西靠文字静态描述真是已经感觉词不达意了，我不知道​@FelisCatus
​ 你有在使用firefox作为备用浏览器不？如果你用过autoproxy的代理切换，我想其实你应该能明白我的意思。

下面我放个图再表达一下我的想法把

在 2015年2月14日 上午10:37，FelisCatus <notifications@github.com>写道：

**Comment by Tback1** [comment]
看看邮件回复能带图不。直接传图又抽风了。如果没有晚点我再试试。

综合图上说的，其实omega大部分autoproxy的快捷菜单的功能已经实现了。真的就是逻辑混乱的问题。

其实要改的真的还就是自动切换和虚情景在快捷菜单的逻辑问题。真不用涉及其他了。改菜单，不改核心逻辑，小猫你就从了把

在 2015年2月14日 下午6:42，thresh14 <thresh14@gmail.com>写道：

**Comment by Tback1** [comment]
![image 2](https://cloud.githubusercontent.com/assets/8872546/6199439/757a2608-b47e-11e4-98e7-df9a3df1713b.png)

**Comment by FelisCatus** [comment]
根据图片，用文字整理一下几个改进建议。主要目的在于整理建议，评论仅供参考，不作为最终结论。

1. “默认代理” - 算是之前讨论过很久的问题了，大致就是虚情景的功能，但比虚情景清楚一些。这里的建议是自动切换模式有一个“默认代理”的概念，在一个地方设置所有“使用代理”规则的代理。
2. 添加规则改进 - 主要建议是添加规则可以再简单一点、并且在有“默认代理”的前提下，允许直接设置一条规则使用代理，而无须手动填写规则类型、通配符以及结果情景模式。其实这一点和 SwitchySharp 开始加入的“临时规则”有点像，但是是永久的。
3. 自动模式、全局模式、禁用代理 - 其实 SO 里直接连接情景模式等于“禁用代理”，直接使用某个代理情景模式或虚情景等于“全局模式”，而自动模式就是自动切换了。
  * 我是觉得既然菜单上第一级都有了、还去不掉，那就不用另外做了。功能上等同，而说法各自有各自的好处吧，至少我是觉得直接选择使用某个代理情景模式挺清楚的。

虽然之前说过了，但为了作为参考，我就再罗嗦一次好了。这里的主要模型冲突是：

* AutoProxy 对于一组规则使用一个代理。这组规则类似Switchy系列的“规则列表”，只有匹配和不匹配两种模式。对于匹配的规则统一选择使用哪个代理。
* Switchy 系列没有分规则组，而是每个规则都分别设置结果情景模式。这个设置确实很灵活，但在需要统一代理的情况下非常不方便，其中一种典型应用场景就是经过防火墙（对于无法直接访问的需要使用代理，其他则不需要代理，至于代理是什么其实这里并不关心）。

我认为，简单的、局限于菜单的改进不能满足用户需求，因为每个规则分别设置结果的现状会引起太多设计上的不便，很多整体设置代理的操作难以实现，即使实现了也会造成概念上的混乱。（设置界面分别设置结果情景模式，而菜单里当做统一默认代理切换？）

所以我是想说，我们迈进一步，直接拥抱类似AutoProxy的单结果模型吧。既然单结果模型有挺多使用场景，而且单结果模型在“规则列表”部分已经取得了成功，那么为什么我们不能将其引入自动切换呢？

提议：自动切换可选择使用“统一结果”模式。此模式开启时，每条规则的结果只能是“匹配”或者“不匹配”。对于所有匹配规则，统一设置其结果情景模式。类似规则列表，这种模式只能有两种结果。这种模式在下拉菜单等位置可以进行相对快速的切换设置（比如更改默认代理、快速添加使用默认代理的规则之类的。）

模式的名称还有待商榷，且和原先的自动切换做成两种不同情景模式还是做成选项，有待讨论决定。但无论结果是什么，我希望提供一份备份文件，里面提供了这种自动切换风格的设置，可以直接用。

**Comment by Tback1** [comment]
既然是单结果模型，要不我们这样考虑一下，虚情景模式本来就是SO的特色。自动切换反而是一个妥协后的产物，要不咱们把自动切换给砍掉。直接用虚情景代替掉。以后的所有配置就改为规则分组到某个情景下，每个虚情景都能允许切换的功能即可，至于自动切换的结果是匹配规则走哪个代理或者不走哪个代理，用户请随意，这样是不是才比较符合SO灵活的本意？

我的意思就是SO现在的逻辑混乱本质上就是分层不足造成的，既然本意的模型不愿意采用组的模式，那就直接对应情景模式不就好了么？

@FelisCatus 你觉得这样会不会更符合switchy系列的本意?也能让学习曲线不那么陡峭？
等于是快捷菜单就只有
1、不走代理 
2、虚情景代理1
3、虚情景代理2

n、虚情景代理n

让后在每个需情景里自己配置需要的自动代理方式和虚情景匹配的代理。
白名单、黑名单什么的统一为不同的虚情景即可。

**Comment by FelisCatus** [comment]
抱歉我是真没看懂……按照您的建议，虚情景要有哪些功能？一个虚情景含多个规则，相当于一个规则组？

**Comment by Tback1** [comment]
主要是我的确没看过你的模型定义，很多词汇要表达的意思真有点难传达。

还有、请别用您好不？亚历山大~~

每一个虚情景不包含多个规则，只提供
1 这个虚情景对应某proxy。
2 这个虚情景下默认的自动识别。（或者是理解为每个虚情景都是一种自动切换？）
没了。

**Comment by FelisCatus** [comment]
那么“默认的自动识别”又是什么？一下子就出现了好多我看不懂的词……而且既然虚情景不包含多个规则，又怎么理解成自动切换？

好吧，且不说这个提议如何，我倒是觉得虚情景才是妥协，而自动切换才是SO特色。虚情景这个概念，给用户带来太多困惑：“这是用来干什么的？”，“为什么这个可以解决一次更改多个规则的问题？”，以及您说的“明明是切换自动切换的代理，结果要去切换一下虚情景的设置”。相比之下自动切换一直都是简单易懂(“满足条件则使用对应情景模式”)，尽管对于“一组规则=>任意代理”之类的场景还有待优化。

虚情景在技术层面上的意义是要大于非技术层面的，它能保证多条规则代理切换的高效率，也能与现有的脚本生成配合良好。所以之前的讨论中我也提到过，这个可以为“自动切换统一结果”之类的，或是类似的改进铺路。正如“自动切换附带的规则列表”一样，这类应用在技术上也能明确地实现。技术细节在此我不多讨论了，总之我想说的观点是虚情景在概念上太复杂不利于用户学习，然而在技术上还算有用。

所以我的建议是，把虚情景当做中间步骤或者垫脚石吧。我们下一步，需要超越虚情景，做得更好才行。我们需要更容易上手且更高效的模型。我之前的建议算是针对“一组规则=>任意代理”的这种常见情景进行优化的一次尝试，但大家也可以提出反对意见或者其他方案。

当然，如果能把虚情景这个概念“改造”或者怎么弄得可以用，自然也是好的。只是想说我们真不必拘泥于虚情景来做类比。如果 @Tback1 能在不提及虚情景的前提下，简洁但具体地说明下那个构想，我觉得讨论就可以更进一步，而且这样在看这个issue但不清楚“虚情景”概念的其他人也会更加友好。你觉得呢？

**Comment by Tback1** [comment]
算了，我只能承认我还是习惯auto的规则组的模式。接下来SO我就还是尽量少点规则用把。复杂了，按照一条规则一个情景的配置，真心伤不起。实在不行了反正前端还有ISA，直接ISA走转发分配算了。

说白了我还是希望在一条规则一个情景之上实现规则分组，至于这个分组是多个自动切换来分组还是多个虚情景来分组。这个我觉得都行，只要不要一套分组居然是两个平行的层级都来操作都可以。

要么就多个自动切换，每个对应一套代理。
要么就多个虚情景，每个对应一套代理。

**Comment by Tback1** [comment]
最后我再补一个一条规则一个情景无法实现的事情

我在公司的内网，走外网的页面大概有300条规则，走公司的内网大概有200条规则。
只有一个情景模式。还有两个虚情景模式（一个内网，一个外网）。
网管今天说外网代理挂了，重新配了一个socket出来，请大家自行切换，时间紧，也没空给你写pac，有空网关大爷说了，boss的配置都还没搞定，没空理你。

怎么快捷切换？200条手工全来？还是访问网页就手工去切换？

虚情景依然解决不了一部分要切换一部分不要这个问题。因为虚情景下不能带一队名单啊。只能一次全改

**Comment by Tback1** [comment]
我又去看了前面的issus，你也不同意么个情景模式自带一队“切换规则”

我说的就是这玩意。

![Image of Yaktocat](http://drp.io/ofP)

http://drp.io/ofP

还有临时代理功能蛮好，不要砍掉。

**Comment by FelisCatus** [comment]
@Tback1 你举的那个例子我没懂……既然已经有一个外网的虚情景模式了，那调整下目标不就行了？或者更简单的，既然某个代理服务器挂了，那么把那个代理情景模式里面的服务器地址和端口改成新的不就行了？

**Comment by Tback1** [comment]
我到底要讨论一个什么问题
============

@FelisCatus 关键是你的虚情景(或者自动分组)里不能带“切换规则”，如果可以，虚情景就等于是一种分组。

**就是因为没有，所以那个例子里的300走代理A，200走代理B都只能在自动切换的“切换规则”这个“组”里。**

所以我说实际上实现不了。

你想想，另外一个issus你不也是告诉另外一个提issus的朋友说，只能用虚情景全部切换，或者点一下蓝色按钮全部切换。糟糕就糟糕在全部切换。实际上是一部分切换一部分不切换。

**所以我希望在设计里能把这样的“切换规则”分开**：

1. 要么每个情景模式带“切换规则”，有问题了我直接改这个情景模式的服务器和端口。
1. 要么就允许多个“自动切换”的情景模式，我配置这些“自动切换”。

或者你要定义这样的多个“自动切换”叫做**虚情景**或者**别的什么好称呼**都可以，我不在乎这称呼是什么，

我只关注****本质的，情景模式能不能带上“切换规则”，进行一个实质上的分组。**

如果还是坚持一个情景模式一个规则，我的确认为向上面的300代理A，200代理B除了手工，别无他法，最多我选择500代理A全切换，200代理B我手工再改回来。

我还是很担心你前面说的那句 
> “Switchy 系列没有分规则组，而是每个规则都分别设置结果情景模式。”

那从根本上来说，只能在自动切换里实现的“切换规则”本质上对于这个问题是无解的。

另外
==

通过这个问题讨论本身，其实我也在改变我关注的焦点。

最开始我也的确是认为不便捷仅仅是逻辑混乱的问题，砍掉平行的多余部分就能解决。

**但是最后我在每次实验配置让后提出情景问题的时候，才发现，其实还是模型没有分组这个逻辑本身的问题。因为从本质上说，计算机并不是人脑，并不能进行模糊的逻辑判断，只是高速重复某一行为罢了，那同类行为分组，同类数据归类这一逻辑在计算机的设计哲学里是必然的。**

就如同数值分析101课程最基本的一点就是告诉我们不同数据的处理方式，这也是一种分类。
毕竟混杂了不同类型数据的数组是不存在的，那玩意叫结构体，而且结构体本身也是一种打包后的元素。

所以我希望 @FelisCatus 能够接受分类的观点，本质上这并不会让SO变得不够灵活。相反在大量重复处理（计算机本身不就是干这事的么?）的情况下，这才是一种灵活

**Comment by Tback1** [comment]
当然，如果你有如何用现有的虚情景搭配自动切换这一约束条件下实现的方案，请告知我，那我觉得SO我就没什么遗憾了。界面的问题，我大部分时间和调试器打交道，简洁实用就别无所求了

**Comment by FelisCatus** [comment]
> “Switchy 系列没有分规则组，而是每个规则都分别设置结果情景模式。”

描述现状，不代表拘泥于现状。我只不过是把主要矛盾暴露出来，仅此而已。无论你之前提的建议，还是之后要求的分组方案，本质上都是与这一点相违背的。 **因此，我认为需要改变或者拓展的正是“每个规则都分别设置结果情景模式”这一点。**

多个自动切换从 SwitchyOmega 的最开始就支持了。然而，要让多个自动切换同时起效，是需要配置“锁链”的。（即A自动切换的结果为B，B自动切换的结果为C，……）这一点对于很多用户而言并非显而易见的，而且概念上也并不是很清楚。而且，最终是要在菜单里选择“A”这个情景模式，而非直观的“A+B”之类的。

如果多个自动切换可以友好一些，自然可以部分解决分组的问题。但是，这种分组是一种人为的分组，而不是按照“结果”分类的分组。要做到简单修改每个分组的情景模式，我是觉得还需要统一结果，或者至少的，把类似蓝色按钮的功能做到弹出菜单里。

之前用户也提了很多这样的应用，如按照结果分组、按照网站类别分组等自己认为合适的组合方式。我觉得这是一个可以接受、且已经可以实现的方案，唯一欠缺的是把这个方案能够以很好的方式呈现给用户，而不是让用户自己重新发现“锁链”这种事情。为此，需要概念上或者界面上的改进。我认为这可以是Plan B.

**Comment by Tback1** [comment]
我昨晚上洗澡的时候也想起了多个自动切换无法同时生效的问题，但是我没有想出一个解决方案，或者我认为上次的虚情景本身就应当是用来解决这个的，即虚情景可以包含多个自动切换规则，这也体现了虚的本意，即实际上不存在这么一个情景，而是多个自动切换的综合，调整的时候更改某一自动切换并不影响其他自动切换。

但是现在的方案反而是虚情景在自动切换之下的样子？

我没有明白按照  结果  分类是怎样的。

是以什么作为结果的标准么？或者说结果这个词在程序框架里是特定的什么？我没有看出来有结果导向的因素啊？

另外你的意思是你还是同意要分组，只是分组的依据不同么？

是这样的么？
2015年2月16日 下午1:22于 "FelisCatus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
我个人同意分组，并且提议多个自动切换作为一种可能的解决方案（每个自动切换就是一个分组）。

因此最终结果会有点像是多个自动切换的综合，正如你所说，也许需要某种比自动切换更大的概念。而虚情景从出发点来说，是模仿或代替一个情景模式，所以说不是用来解决这个问题的。

另一个问题在于，现在的自动切换是完整的，并不只是一条条规则，还有默认（所有规则都不匹配时使用的）情景模式。要综合多个自动切换，就必须在综合时去掉这些自动切换的默认情景模式。这会让组合的概念更加复杂。

P.S. 结果：在 SwitchyOmega 现有的设置模型中，每条规则有条件和“结果”两部分。条件是通配符等等，而“结果”是设置的情景模式。如 `*.example.com` 使用“Shadowsocks代理”。其中“Shadowsocks代理”是结果。Switchy 系列中规则（即条件和结果）组成自动切换。再一次，这是为了讨论现有模型而做的说明，仅仅是描述了现有的设置模型而已。请把它当做一种参考，而非把它当做今后的设计决策或强制要求。

**Comment by Tback1** [comment]
嘿，那你考虑一下把虚情景作为多个自动切换组成的一个超级情景如何？

我又回去看了一下
https://github.com/FelisCatus/SwitchyOmega/issues/47
还有
https://github.com/FelisCatus/SwitchyOmega/issues/32

当时提到了一个超越集的存在。
我觉得虚情景用来模拟一个其他的情景这定义是浪费了虚情景的这个概念，虚其实可以表示第二维，表示一种超越。用来做超越集不错啊

另外，我试着按照你的逻辑重新搭了一个代理定义文件。我觉得是我错了。

我通过嵌套在里面解决了这样一个问题，只是列表维护特别麻烦，得特别小心。还有就是添加快捷菜单的时候的问题了。

现在我的结构如图
![1](https://cloud.githubusercontent.com/assets/8872546/6216555/52b62972-b646-11e4-88fc-137f60665cfb.png)

似乎回到了问题的起点，要么内在设置没问题了。既然我认为我自己错了，不是内核模型的错误，是我本身没有用SO实现分组，那说明这个问题就还只是菜单本身名词定义导致的模糊。

所以我最后建议，

--------------------------------------------------------------------
必做！！！！！
把自动设置放上去，放到区域1，在基本代理和虚情景之间分一条虚线作为区域2
区域3留给虚情景，区域4是设置及其他

区域1就是系统的代理模式
区域2是基础代理
区域3是很麻烦的一个概念，就是虚情景快速切换一组基础代理的对应规则
区域4balabalabal

选作：如果虚情景是按照这个配置的想法用的话，那其实可以将区域2做二级菜单折叠，就叫做基础代理
区域3叫做规则组快速切换？？（或者干脆就不折叠把，只不过要写个教程，说明后面的的下拉菜单切换的其实是快速切换这个虚情景对应基础规则对应的所有条目）。
---------------------------------------------------------------------
这个操作就只是把自动切换放到了上面，这样菜单的分组概念就形成了，改动代价也不大。你觉得如何？

截图拼凑效果如下

![2](https://cloud.githubusercontent.com/assets/8872546/6216668/2aa10848-b647-11e4-884d-8224e9e81c96.png)

**Comment by Tback1** [comment]
哦，补充一句：如果你愿意将虚情景作为多个自动切换的集合的话，那把自动切换砍掉，区域3换车多个自动切换就行了。

**Comment by FelisCatus** [comment]
1. 自动切换提前到代理情景模式之前。既然自动切换很常用，放上面也好一点。
2. 现在菜单的空间比较紧张，而且菜单的展开速度有点慢，需要再优化下。所以和菜单相关的修改会稍微推后一些……

**Comment by Tback1** [comment]
那要考虑限制自动切换的数量为1，万一有人建立多个自动切换怎么办？

**Comment by Hs-Yeah** [comment]
其实我觉得虚情景模式的名字改一下，比如叫做代理选择器什么的，同时提示用户这是在自动切换和代理服务器之间的中间层（一开始我以为是在自动切换之上）。

同时在 UI 上将情景模式分为三组：
+ 将代理服务器这些情景模式分在一组，作为基础代理；
+ 代理选择器，也就是虚情景模式分在一组，用于选择使用哪个基础代理；
+ 自动选择分在一组，所有针对网址的条件规则添加在自动选择中，满足规则就导向代理选择器，代理选择器指定需要走哪个基础代理。

这样，自动切换在最高层，代理选择器在中间层，基础代理在最底层。用户在使用时先建设好基础代理，然后在使用时通过代理选择器选择需要走的代理服务器，发现有需要走代理的网址时就添加规则到自动切换。

当然，满足规则时可以跨过代理选择器，直接导向基础代理；同时，代理选择器也可以导向其他代理选择器或自动切换以实现链式筛选。

这应该没有改变代码逻辑，不过从用户角度来说，只需要改动一下 UI 就能很好的将使用逻辑表达清楚了。

如果用 AutoProxy 的语言来说的话，自动模式就是最顶层的自动切换，全局模式就是基础代理或者没有链式筛选的代理选择器，禁用模式就是直接连接。

**Comment by DailyShana** [comment]
我就来吐槽lz为什么要把事情搞复杂。。。
lz使用代理的方式都被autoproxy套住了。。。

**Comment by Tback1** [comment]
因为我是autoproxy的脑残粉啊
