### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wzwcn** [FelisCatus/SwitchyOmega#274]
能直接在下拉菜单中设置当前域名是否启用代理才方便，现在得自己一个一个增加规则太麻烦了

SwitchyOmega 2.3.2
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by FelisCatus** [comment]
下拉菜单里是可以设置的。有任何问题吗？
