### ISSUE TITLE
升级后的问题和建议（按功能列表序）

### ISSUE THREAD

**Issue by StrollStars** [FelisCatus/SwitchyOmega#275]
1.配置文件同步可否支持第三方空间？
2.网址协议匹配的是网址，代理协议匹配的是代理服务器提供的协议类型，这样理解对吧？那对于Tor这样提供多种协议的可有推荐设置？
3.自动切换的条件类型，显示帮助没有反应。
4.自动切换匹配规则时自上而下，规则列表可与自定义规则同时启用（以优先级顺序匹配），是这样吗？
5.同样的设置，手动切换能够登录谷歌帐户，自动切换速度慢且容易出错。
6.如果同时打开匹配不同规则连接不同代理的网页，是否会各自网页走各自的代理，还是都走后一个代理？
7.即使手动切换到代理，访问百度还是直接连接，可能匹配了GFWList规则，这是不是扩展处理上存在问题？
8.自动切换在匹配“||”开头的GFWList规则时是不是存在问题，在列表中却没应用相应代理？
PS：建议能够写份中文说明，放在网站或者扩展里。

**Comment by FelisCatus** [comment]
3 => 已经确认是 bug 导致，非常抱歉，下一个小版本就会修掉。

1. 可能可以，但目前没有支持的计划。我还是觉得开发量太大了，而且既然扩展已经自己有同步机制了，再去费精力整合第三方的网络存储确实有些超出扩展应该做的范围了。而且支持了一家就会有人再提议另一家……到最后 80% 以上的代码都用来处理各种网盘的问题了，实在是……
2. Tor 推荐只使用 SOCKS5 代理，足够使用了。
3. 如上所述，待修复
4. 规则按照从上到下顺序，其中规则列表的优先级顺序如界面所显示，是在最后的默认规则之前，其他所有自动切换规则之后。规则列表内部的顺序由规则列表决定。
5. 如果正在使用 GFW List 请直接向 GFW List 项目反应。如果是手动设置的规则，请确定规则有效且包括页面中加载的其他资源。
6. 各自走各自的。
7. 不，直接切换到代理的话不会使用规则列表和自动切换。如果您实际观测到的行为不一致，请提供一些详细信息并提交错误报告。
8. 严格按照 GFW List 规则列表逻辑进行匹配。以下为 GFW List 中这类的规则的相关说明，仅供参考：

> ||example.com
> Matching: http://example.com/foo
> Matching: https://subdomain.example.com/bar
> Not matching: http://www.google.com/search?q=example.com
> Match the whole domain and second-level domain no matter http or https, used when site's IP is blocked.

**Comment by FelisCatus** [comment]
3 => 已经修复，等待下一次更新发布。（目标版本 v2.3.3 ，预计发布时间：24小时以内。）

**Comment by zamen40** [comment]
I dont know quite how to do much on git hub but anyways, would there be a way to auto setup profiles??
at gatherproxy.com, its down atm you can download aa .txt of proxies that go ip:port would there a be a possible way to make it so that it would make a profile for each one and check each one whether it worked or not and if i didnt, remove that profile?

**Comment by FelisCatus** [comment]
@zamen40 That should be another issue. Please open a new issue on Github.

**Comment by FelisCatus** [comment]
v2.3.3 已经发布。现在可以正常查看切换条件帮助了。

**Comment by StrollStars** [comment]
1.如果网盘会带来那么多问题还是算了。
2.确实测试Tor在http(s)下存在问题。
3.已修复。
4.谢谢告知。
5.这个问题比较复杂，我发现登录谷歌帐户重定向太多，这个问题可能我们需要交流下怎么处理比较好。因为有两个问题：一、频繁切换规则加大开销降低速度；二、重定向期间的网址不易捕获。
6.谢谢告知。
7.重测发现规则设置问题，打扰了抱歉。
8.重测发现规则设置问题，打扰了抱歉。
PS：再请教个自动切换模式问题。若因匹配自动切换到A情景模式，而A情景模式中又排除该地址，最后结果是不是不使用A情景模式中的代理？

**Comment by FelisCatus** [comment]
5: 用 `chrome://net-internals/#events` 可以轻松截获所有请求，之后自己设置切换规则或提交给 GFW List 都很方便

PS: 这个项目的设计目标之一是，一个情景模式对于同样的请求返回同样的结果，无论直接或者间接（组合）使用。如果某个请求的中间结果是A情景模式，则其最终结果和直接选择A情景模式相同。
也就说，正如您所说，假如A情景模式“不代理的地址列表”匹配了该请求，结果是不使用代理。无论是直接还是间接使用了A。
