### ISSUE TITLE
Improve menu “Add Condition”

### ISSUE THREAD

**Issue by syswow** [FelisCatus/SwitchyOmega#276]
现在， 打开一个网站 比如  www .example.com ； 添加的条件是 *.www.example.com 。
可否改进为 *.example.com

**Comment by FelisCatus** [comment]
之前想过，不过后来觉得有点坑……关键在于基础域名是什么概念的问题。

* www.example.com => `*.example.com` 段数3，基础段数2（1段顶级域名），没有问题
* www.google.co.uk => `*.google.co.uk` 段数4，基础段数3（2段顶级域名）
* google.co.uk => `*.google.co.uk` 段数3，基础段数3（2段顶级域名）
  * 这两种情况，如果不特殊处理 .co.uk ，可能会错误地生成 `*.co.uk` 这种匹配规则，这显然没有意义。

那么问题就来了，如何处理 .co.uk 之类的呢？要在代码里维护一个列表？而且现在新的顶级域名也出了很多，列表很难及时更新。

另外当然我也在想，去掉子域名后的网站可能完全是两个概念，比如 internal.example.com 可以在公司内直接访问，而 www.example.com 则属于外部网站，必须使用公司提供的代理服务器访问。这样的情况下，如果访问 internal.example.com 失败，提示用户添加的是 `*.example.com` 规则的话，就意义不大了……

目前的虽然并不是最方便的，但至少 1. 它总是对的 2. 如果用户想去掉中间一段可以手动删除（而如果默认删除了的话用户加回来一段很不方便，且会误判）。

总之我认为这个改进可以有，但还需要经过仔细讨论，确定正确的做法是什么再去实现。

**Comment by FelisCatus** [comment]
我想了想，觉得可以按照以下规则判断：

* 如果最前面的一段是`www`，去掉`www`后再进行处理。
* 域名的最后一段始终为顶级域名
* 对于只有两段、或去掉`www`后只有两段的域名自然没有岐义（如`example.com`=>`*.example.com`）
* 对于三段以上的域名，若倒数第二段长度为1或2，则认为是顶级域名的一部分，如`google.co.uk`或`google.co.jp`之类的，保留最后三段。
* 域名的倒数第二段如果长度为3以上，则认为其并非顶级域名（如`a.example.com`），保留最后两段（`*.example.com`）。

注意：这个算法可能会将`example.t.co`之类的误判为两段顶级域名，生成的规则是`*.example.t.co`。（但实际上应该为`*.t.co`，因为 `t.co`是Twitter的短网址服务，是一个独立网站而非顶级域名）。但这种情况下，生成的比实际的要长，而非比实际的要短，所以用户可以很方便地删除其中一段。

**Comment by syswow** [comment]
用这些规则，我测试了几个比较长网址，没有什么问题，看起来还不错。:smirk:

**Comment by FelisCatus** [comment]
v2.3.6 已经采用“基础域名”算法。感谢您的建议。

**Comment by syswow** [comment]
:+1:

**Comment by FelisCatus** [comment]
测试用例： i2.wp.com
应得结果： `*.wp.com`
实际结果： `i2.wp.com`

这似乎是误判了吧……考虑到两层顶级域名只出现在和国家顶级域名组合的情况，而国家顶级域名都是2个字符，因此修正规则如下（粗体字为新增）：

* 对于三段以上的域名，若倒数第二段长度为1或2， **且最后一段长度为1或2** ，则认为是顶级域名的一部分，如`google.co.uk`或`google.co.jp`之类的，保留最后三段。

**Comment by FelisCatus** [comment]
感觉问题还很大，比如 `.com.cn` 等情况，并非是长度为2的……看来要重新考虑了。

**Comment by FelisCatus** [comment]
引用 @bitweng 的[评论](https://github.com/FelisCatus/SwitchyOmega/issues/302#issuecomment-75371728)：

> 我研究了下域名后缀的构成，http://www.iana.org/domains/root/db ，发现是这样的：
> 一是 type就是generic(有一两个是sponsored和generic-restricted)，直接就是com、co 等这些；
> 二是 country-code域，如 cn、uk这些；
> 三是 generic+country-code, 如com.cn、co.uk。

> 思路可以这样，维护两个域名列表，A为generic,B为country-code。
> 比如这个 www.google.co.uk, 解析时：
> 先拿uk从B中查找，如果找不到，则生成的过滤结果是 *.co.uk。
> 若找到了，继续拿co从A中查找，如果从A中找不到co,则生成的过滤结果是 *.co.uk。
> 如果从A中找到了co，那么最后得到的过滤结果肯定是三段的 *.google.co.uk 。
> 
> 又比如 abc.i2.wp.com这个，先拿com从B中查找，肯定是找不到的，那么生成的过滤结果就是 *.wp.com了。
> 至于域名列表，可以用个脚本抓取，每一个新版本抓一次，更好的改进办法，还可以继续思考的。

**Comment by FelisCatus** [comment]
以及， @bitweng 的建议的问题在于……一大堆新的 generic TLD 正在来袭。以`.wedding`为例，其归类为 generic ，但比如`wedding.cn`并非 generic + country-code 共同作为一个域名的范畴。

在这里我建议我们使用 [Public Suffix List](https://publicsuffix.org/) 的数据。（ GreaseMonkey 也在使用这个数据源，效果还不错。）

当然唯一的问题在于这个列表很长……而且要想办法弄进源代码里去。

**Comment by FelisCatus** [comment]
或者干脆就用[这个npm模块](https://www.npmjs.com/package/public-suffix)搞定。

**Comment by syswow** [comment]
@FelisCatus 
还有几个可以参考下，对比一下它们的效率 [publicsuffixlist.js](https://github.com/gorhill/publicsuffixlist.js) , [tld.js] (https://github.com/oncletom/tld.js). 

采用了TLD，这件事就很方便啦，eg: getDomain("abc.abc.abc"). :smiley: 

如果打算自己实现放进源代码的话，我觉得也不错。可以不用做的那么全面，应该有一个getDomain()就行了。刚看了一下[PHP版的实现] (http://pear.php.net/package/HTTP_Request2/docs/latest/__filesource/fsource_HTTP_Request2__HTTP_Request2-2.2.1HTTPRequest2CookieJar.php.html#a431), 我们也可以简洁实现这个功能。

所以剩下的就是效率问题了。 :smile_cat:

**Comment by syswow** [comment]
@FelisCatus 现有的判断方法把 www.google.com.sg, 识别为 com.sg了。

**Comment by LakeChan** [comment]
建议直接让用户来选择

**Comment by FelisCatus** [comment]
v2.3.8 已经改用 tld.js 进行识别。
