### ISSUE TITLE
如何对网页内引用的资源也使用代理？

### ISSUE THREAD

**Issue by hukangha** [FelisCatus/SwitchyOmega#278]
访问一个网站时，将该网站的domain加入到规则，那么这个网址会以代理访问，
但是如果这个网址里面引用了一些无法连接的资源，那么这些资源依然是无法正确显示的。
有时候还有会造成网页的排版错误
然后我去swithcyOmega中，希望找到一个选项，对某些domain的网页内的全部资源使用代理。
但是这个选项在swithcyomega中未找到。
不知道实现该功能是否是可以实现的？

还有一个方法是自动检测无法连接的资源并对其进行代理，不过这个似乎不容易实现。

**Comment by FelisCatus** [comment]
技术上很难，具体见 #218

自动检测无法连接的资源：很麻烦但理论上很可行，见 #6.

**Comment by hukangha** [comment]
之前了解到chrome是每个tab一个进程的，
那可不可以不使用URL的方式判断是否代理，而是以chrome的PID或者tab来判断？
比如 当一个tab内的地址栏中的url 符合“全部使用代理”规则时，对该tab的进程进行全局代理？

**Comment by FelisCatus** [comment]
PAC 脚本没那么高端的……只有网址等少量信息可以作为判断条件，不可能获取具体哪个标签页或者窗口，更不用说操作系统相关的进程信息了。

**Comment by FelisCatus** [comment]
v2.3.6 已经能做到部分检测被墙网站了，[见说明](https://github.com/FelisCatus/SwitchyOmega/issues/6#issuecomment-74818135)。
