### ISSUE TITLE
HTTPS 代理有 BUG

### ISSUE THREAD

**Issue by chigix** [FelisCatus/SwitchyOmega#281]
HTTP 代理使用正常，但对于 HTTPS 的地址无法代理，我的配置是：

Http: 10.0.0.186:8084
Https: 10.0.0.186:8084
（上述IP为示例IP，所建为符合 HTTP 1.1 标准的 反向代理服务器）

而这个配置在之前的 SwitchySharp 上是可以正常使用的。

注：反向代理服务器是通过 HTTP CONNECT METHOD 声明来自动建立 HTTPS 隧道的。我在代理服务器上收不到 HTTPS 建立隧道的请求信息，收到的已经是客户端发出的 加密信息。

SwitchyOmega 2.3.2
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1902.0 Safari/537.36

**Comment by FelisCatus** [comment]
看上去像是代理类型和网址类型搞混了。 SwitchyOmega 除了网址类型以外，还开始支持代理本身的类型（如一个 HTTPS 代理可以处理`http://`和`https://`两种网址）。如果无须根据网址类型选择不同的代理，则只填写“默认”网址的一行配置即可（但注意请正确选择代理本身的类型）。

如果还不明白的话，请截图一下代理情景模式的设置界面（当然，可以把地址改成示例地址）。

**Comment by chigix** [comment]
那同时支持 HTTP/HTTPS 双协议混合的 反向代理服务器应该怎么选？虽然是全部走 HTTPS 可以成功完成代理任务，但是本身是 HTTP 的连接强行走 HTTPS 隧道的话，会降低 HTTP 连接的效率啊。而且你的 Omega 的 HTTPS 代理有点奇怪，并不发出 CONNECT 请求报头

就是非常简单的，如下代理模式，如何使用 Omega 来完成设置？
![1](https://cloud.githubusercontent.com/assets/2692787/6188800/da2b20b6-b3cf-11e4-8c03-daeaf5424a3d.png)

**Comment by FelisCatus** [comment]
![image](https://cloud.githubusercontent.com/assets/912649/6198201/ed5fc00e-b430-11e4-8c6e-973bf9b3eaa7.png)

我感觉您想复杂了，根据您的截图，像这样最简单的设置难道不行吗？（前提是没有使用高级按钮进行复杂的设置）。

如果还不行，可能确实真的需要更复杂的设置。代理服务器的请求相关都是由Chrome实现，所以只要“有效设置”和之前完全一致，那么行为自然也就会完全一致，无须多虑网络和协议相关情况。

既然 SwitchySharp 上是行的，那么麻烦切换回 SwitchySharp ，确认可以正常使用后，访问 `chrome://net-internals/#proxy` 页面，并将页面上的内容（即“有效设置”）复制到这里，我来说说如何在 SwitchyOmega 进行对应的设置。做了对应的设置以后肯定就可以用了。

**Comment by chigix** [comment]
真的不一样，有图有真相：

SwitchySharp 中的设置及 chrome 代理有效设置截图如下：
![2](https://cloud.githubusercontent.com/assets/2692787/6199347/3041f23c-b479-11e4-8b01-2d6fa9230442.png)
![1](https://cloud.githubusercontent.com/assets/2692787/6199348/3162fa08-b479-11e4-8432-86025f47be9d.png)

SwitchyOmega 中的设置及 CHROME 代理有效设置截图如下：
![3](https://cloud.githubusercontent.com/assets/2692787/6199351/58c2718c-b479-11e4-9552-99cac2ce9b65.png)
![4](https://cloud.githubusercontent.com/assets/2692787/6199353/5e2f0770-b479-11e4-9e0d-376ee46a2776.png)

而如果 SwitchyOmega 中分开 设置 HTTP 与 HTTPS，CHROME 代理有效设置如下：
![5](https://cloud.githubusercontent.com/assets/2692787/6199359/b92f6336-b479-11e4-99ed-4c7e895a5976.png)
![6](https://cloud.githubusercontent.com/assets/2692787/6199360/c8c2962e-b479-11e4-84fb-b79acc109eec.png)

所以真的不一样，设置 HTTPS 代理的时候，你的地址里还带上了一个 HTTPS，所以这一点上和 SwitchySharp 行为不同

**Comment by FelisCatus** [comment]
我们先将 SwitchySharp 那个有效设置的截图简称为目标设置。这也是我们设置将达到的目标。

1. 第一次设置： SwitchyOmega 只设置默认有效设置时，只有一条有效设置，即所有网址使用相同代理服务器。在 HTTP 和 HTTPS 网址协议上应该和目标设置等效，因此这样设置即可。无须进行更复杂的设置。
2. 第二次设置：您的那张图里很明确地设置了对于 `https://` 网址使用 HTTP**S** 类型代理服务器。“你的地址里还带上了一个 HTTPS”正是因为“你明确选择了使用HTTPS类型”。将这一行的代理服务器类型改成 HTTP 即可和目标设置完全相同。

再说明一次，HTTPS类型代理是完全不同的一种东西。HTTPS代理是一种代理类型，而非“网址协议”。

归根结底还是 SwitchyOmega 的设置过于强大过于复杂了，而且它不会防止您做错误的设置，不会检查代理类型是否真的和所设置的相符。所以我说对于一般用户而言真的没有必要去点展开高级设置，又繁琐又容易出错。
