### ISSUE TITLE
选项同步中允许使用本地强制覆盖云端版本

### ISSUE THREAD

**Issue by chenall** [FelisCatus/SwitchyOmega#282]
目前选项同步功能,如果两台电脑都在用,并且配置不一样的话就只能使用先上传到服务器的那个.

能不能改进一下,

1. 可以强制使用使用本地的覆盖服务器上的
目前只能强制使用服务器覆盖本地的,即使我导出配置,然后覆盖,再导入配置还是提示只能从服务器下载覆盖本地的.

2  可能的话可以智能一些,把两个不同的配置合并在一起.

**Comment by FelisCatus** [comment]
我是觉得既然是两台设备在用不同的设置，那么没有什么特别好的方法了。建议两台设备都开启同步，且对于两台设备上不同的配置，建立不同的情景模式，然后各自用各自的情景模式即可。相同的部分则可以共享同一个情景模式。

1: 使用本地的覆盖服务器的是一个好想法，技术上也可行，我准备支持这个，尽管这个对于您的问题帮助不会太大。
2: 最可靠的合并方式是“两份选项没有同名的情景模式”，即 `a1a2a3 + b1b2b3 => a1a2a3b1b2b3`。对于同名情景模式，再智能也终究是“合并”，且不说合并算法如何、怎样解决冲突，结果终究不太可能是用户想要的。所以，就算有了“智能合并”，还是建议您像我上面说的一样，不同设备使用不同情景。

**Comment by chenall** [comment]
我的操作过程,,
刚开始两电的配置是一样的
后面我修改了其中一台的设置,另一台并没有及时同步,我也手工修改了一下,这样就出现了冲突.

另外一点就是如果我是用导入功能导入的配置,因为上面已经出现冲突也只能使用服务器上的配置.

所以才需要有本地覆盖服务器配置的功能,我想使用我之前备份的配置为准.

期待下一个版本.谢谢

**Comment by FelisCatus** [comment]
两台设备上做完全一样的更改，结果应该不会冲突的吧？尽管后更改的会自动覆盖先更改的，但毕竟内容是一样的……

**Comment by chenall** [comment]
我现在用导出功能导入一份配置,到另一台电脑上导入..

现在两台电脑配置一样了,但是已经不能使用同步功能.

># 选项同步 (测试中)
>> 您已经通过其他设备上传了一份选项用于同步。
>
>您可以将云端的选项下载到此设备使用。
>一旦选择下载，**此设备上的设置和情景模式将会被覆盖**。

**Comment by FelisCatus** [comment]
现在导入任何选项都会直接禁用同步，因为实在是难处理。可能可以判断一下完全相同，但是……
既然要的是一样的，那直接下载覆盖就是了，何必折腾导入备份文件呢……

**Comment by chenall** [comment]
两边的都和服务器上的不一样,都是一样的提示.
目前看来还是提供一个使用本地的强行覆盖服务器的配置功能好了.

**Comment by FelisCatus** [comment]
嗯，好。

**Comment by linyehui** [comment]
本来想来感谢作者，然后提点建议的，发现已经有了类似的讨论，顺便说下我的观点，
最简单实用的还是：提供本地强行覆盖服务器的功能。

如果有上传功能，再加上好的习惯，已经够用了。
智能合并属于优化体验，但难免遇上多台设备交错修改，合并不了，还是要手工合并。

代码入库时的冲突，程序员应该经常会遇到，目前都没有那个合并算法能解决所有冲突。
简单够用就好，智能合并这个可以慢慢优化，先做能合并的，一旦不能合并就要求用户自己选择覆盖还是放弃。

**Comment by FelisCatus** [comment]
为了让这里讨论的主题更清楚，修改了下标题。目前而言，强制覆盖是最高的优先级。

**Comment by FelisCatus** [comment]
修复已经提交，请等待下次更新发布。（预计版本号： v2.3.9 ，发布时间：24小时内）

**Comment by FelisCatus** [comment]
v2.3.9已经修复。

原先显示冲突时，只能使用云端配置覆盖本地的。但此次更新后，同一个界面右下角新增了“删除云端版本”链接，点击即可删除之前的同步选项。该操作不影响本地选项，清空后变为未开启同步状态，可重新开启。
