### ISSUE TITLE
正在下载代理脚本

### ISSUE THREAD

**Issue by t123yh** [FelisCatus/SwitchyOmega#283]
每次启动Chrome时都会显示一段时间的“正在下载代理脚本”，使用的是GoAgent，仅仅在使用自动切换代理时才会出现此种情况，如果使用“直接连接”及“GoAgent”均不会出现这种情况。

SwitchyOmega 2.3.3
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by FelisCatus** [comment]
出现此现象是因为 Chrome 在使用PAC脚本的时候存在编译和初始化过程。根据自动切换规则数量和设备配置性能等因素，该阶段的时间可能长或者短。

这方面已经做了不少优化了，但仍然不可避免地会有点延迟。因此，这个我就关掉了。
