### ISSUE TITLE
无法删除情景模式

### ISSUE THREAD

**Issue by binaijing** [FelisCatus/SwitchyOmega#284]
如图所示，我要删除goagent的情景模式，删不掉。
可以确认的是goagent的情景模式没有被其他任何情景模式或者切换规则使用。
![default](https://cloud.githubusercontent.com/assets/5078268/6200197/8a4846bc-b4a8-11e4-8970-3a798bea4f16.jpg)

**Comment by syswow** [comment]
“以下情景模式使用。。”  但下面的框里没有显示任何情景。

**Comment by FelisCatus** [comment]
请截图 AutoSwitch 情景模式设置，谢谢。只需切换规则中的“规则列表”和“默认规则”一行，其余内容可自行涂黑，保护隐私。

以及如果真的删不掉，可以建立一个虚情景然后替代 GoAgent 即可。我要说的是，这个貌似是 bug 引起的，这条建议最多也只是能凑合用而已，不解决深层问题……如果急着用的话可以这样做。

**Comment by binaijing** [comment]
![default](https://cloud.githubusercontent.com/assets/5078268/6267567/0d4a4b48-b880-11e4-809d-14bf4af2a24d.png)

**Comment by syswow** [comment]
![screenshot 2015-02-19 22 05 44](https://cloud.githubusercontent.com/assets/10815286/6267963/9b5b7792-b883-11e4-9755-e68fa5cefcf2.png)
@binaijing  这个AutoSwitch里面的规则都没有用到GoAgent 吗？如果都没有的话，那就是bug了。

**Comment by binaijing** [comment]
![default](https://cloud.githubusercontent.com/assets/5078268/6268074/b93c7c74-b884-11e4-8107-1f29481e5180.png)
![Uploading 无标题.png . . .]()
都没有啊，我确定把关于goagent的全部删掉了或者改掉了

**Comment by FelisCatus** [comment]
感觉像是 bug ，传配置文件吧。导出配置文件后上传到 https://gist.github.com ，我来看是不是有问题。

**Comment by binaijing** [comment]
怎么传 https://gist.github.com？导出来是bak后缀的文件

**Comment by FelisCatus** [comment]
似乎是有一个叫`Preload`的自动切换模式删除时，其对应的规则列表未删除。不知道是什么情况……

我建议是重新新建一个名字为`Preload`的自动切换模式（建立后应该会自动关联之前没删掉的那个规则列表），保存选项，然后再试着直接删除Preload。删除后试导出错误日志，也许能有什么线索。

**Comment by binaijing** [comment]
按照上面的办法新建Preload，删除Preload，然后就可以删除goagent了，解决了~~

**Comment by FelisCatus** [comment]
我想是很久之前的一个bug，当时删除自动切换时不会删除附带列表。如果是那个时候删的话，附带的列表可能会残留到现在。但现在再删应该不会有问题了……暂时关闭了吧。
