### ISSUE TITLE
只能打开谷歌  其他被防火墙封闭的网站均打不开

### ISSUE THREAD

**Issue by ophxasd** [FelisCatus/SwitchyOmega#286]
youtube  什么的网站都打不开 只能打开谷歌

SwitchyOmega 2.3.4
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题与本项目无关。
