### ISSUE TITLE
auto-switch rule list

### ISSUE THREAD

**Issue by jsjain007** [FelisCatus/SwitchyOmega#287]
i have add some of the website for the use of proxy but auto  switch feature seems not to be working since it is still using the direct connection instead of proxy . 
for eg -  i add filestream.me as 
https://members.filestream.me/*   or 
*members.filestream.me/

but none of them is detected for proxy in switchsharp omega please help . 
thanks in advance

**Comment by syswow** [comment]
try this  *.members.filestream.me
I think SwitchyOmega current didn't support rule that put the ' * ' at the end of domain.

**Comment by jsjain007** [comment]
then using the one you said will it put the proxy for whole domain of filestream or only for filestream.me
and not members.filestream.me/# ?

**Comment by syswow** [comment]
> then using the one you said will it put the proxy for whole domain of filestream or only for filestream.me and not members.filestream.me/# ?

it will put the proxy for whole domain of **members.filestream.me**

***

And if you just want to put proxy for pages under one domain, simple:  **members.filestream.me** , no need ' * '

@FelisCatus  Aha, Actually, I didn't go deep into SwitchyOmega source code, I don't know how to implement this feature.

**Comment by jsjain007** [comment]
i tried    members.filestream.me  as u said but it didnt worked . also i tried *members.filestream.me
didnt worked either . i even restarted my browser .

**Comment by jsjain007** [comment]
also if i do the same in switch rules list it works but not working in rule list area .

**Comment by FelisCatus** [comment]
Rule list editing is not recommended unless you are familiar with one of the formats provided. Either stick to switch rules, or if you just want to edit the switch rules as text, please use the "edit source" button on the switch rules section.

If you really, really intend to hand-craft a rule list, these are the things you want to check:

* Select the right profile to use with rule lists in the switch rules table, on the row with "rule list rules"
* Select the format you want to use for your rule list. AutoProxy and [Switchy rule lists](
(https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format) have their own format and rules, which are NOT identical to conditions in the table.

Give detailed screenshots about the above settings when in doubt.
