### ISSUE TITLE
可代理资源列表这个功能办的到吗

### ISSUE THREAD

**Issue by Loticyang** [FelisCatus/SwitchyOmega#288]
火狐的autoproxy有这个功能,

很多时候在线列表规则不够用,

这个时候就需要这样的一个功能  增添规则,

当然,扩展自带的"添加条件"是不够的,因为许多网站有很多其他的网站需要调用

还有能不能加一个导入本地txt规则(autoproxy格式) 的功能 

SwitchyOmega 2.3.4
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by FelisCatus** [comment]
见 #6。

P.S. 如需导入，可在自动切换模式中使用规则列表，将 AutoProxy 文件内容直接粘贴进去即可。

**Comment by Loticyang** [comment]
规则列表点击左键无粘贴选项,无法粘贴啊

**Comment by FelisCatus** [comment]
点击 **左键** 当然没有粘贴选项，因为粘贴一般都是在 **右键** 菜单里的吧……

请复制文件的内容（文字），而非直接复制文件本身。如果遇到问题可以截图上传。

**Comment by Loticyang** [comment]
![360 20150215184018203](https://cloud.githubusercontent.com/assets/8101717/6202967/24946cd4-b542-11e4-8c47-936461657abb.png)

**Comment by Loticyang** [comment]
好吧,我搞定了,谢谢

在 2015年2月15日 下午6:32，FelisCatus <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
v2.3.6 已经能做到可代理资源列表了，[见说明](https://github.com/FelisCatus/SwitchyOmega/issues/6#issuecomment-74818135)。
