### ISSUE TITLE
使用代理后无法正常登陆某些国内帐号

### ISSUE THREAD

**Issue by Hunterzzzz** [FelisCatus/SwitchyOmega#290]
斗鱼，微博一直登录不上，关闭代理后就正常了

SwitchyOmega 2.3.4
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by syswow** [comment]
国内的网站不需要代理，而且有时它们会限制境外IP访问的。

**Comment by FelisCatus** [comment]
……所以这到底和这个项目有什么关系？代理服务器是其他人提供的，设置是自己弄的……
