### ISSUE TITLE
SOCKS5 Authentication 

### ISSUE THREAD

**Issue by 4Head** [FelisCatus/SwitchyOmega#291]
Why is there a Authentication window for http and https proxys but not for SOCKS5?
The SOCKS5 Proxy I use needs an Authentication.

**Comment by FelisCatus** [comment]
SOCKS Authentication is [not implemented in Chrome](https://code.google.com/p/chromium/issues/detail?id=256785) and therefore cannot be done in SwitchyOmega.

**Comment by cwaffles** [comment]
I noticed that Proxy Helper (https://github.com/henices/Chrome-proxy-helper) allows authentication for various types. Would it be possible to look into that code and duplicate the functionality?

Chrome store page: https://chrome.google.com/webstore/detail/proxy-helper/mnloefcpaepkpmhaoipjkpikbnkmbnic?hl=en

**Comment by FelisCatus** [comment]
@cwaffles They [don't have](https://github.com/henices/Chrome-proxy-helper/issues/2) SOCKS Authentication either. And the developer points to [exactly the same Chromium issue](https://code.google.com/p/chromium/issues/detail?id=256785) for explanation.

Let's face it: Chromium doesn't support SOCKS5 Authentication and thus no extensions can implement it. I would suggest starring [that particular issue in Chromium](https://code.google.com/p/chromium/issues/detail?id=256785) or add your comment there.

**Comment by cwaffles** [comment]
SOCKS over SSH feels like a poor solution, as client reconnects are finicky, but it'll have to do for now then.

**Comment by raykai** [comment]
Proxy Helper (https://github.com/henices/Chrome-proxy-helper) Now has Socks5 Authentication !!!

**Comment by FelisCatus** [comment]
@raykai Any reference please? I checked [their relevant issue](https://github.com/henices/Chrome-proxy-helper/issues/2) and code and didn't find any updates on this.

**Comment by enervated** [comment]
I just want to add that the Proxy Helper extension does _not_ support SOCKS5 authentication, despite the claim made a couple posts above.

**Comment by tldzyx** [comment]
[I use it through pac and it's working](https://github.com/FelisCatus/SwitchyOmega/issues/1136#issuecomment-323279609)

**Comment by FelisCatus** [comment]
No it's not. Please see the discussions there.
