### ISSUE TITLE
情景模式希望添加排序功能。

### ISSUE THREAD

**Issue by a8l1vy** [FelisCatus/SwitchyOmega#292]
1. 情景模式有好几种，我希望把常用的排到上边。不常用放下边。好自由切换。现在的排序凡是pac的情景模式都排序到下边了。
2. 新的确实不如旧的好用。比如我要把pac的改成http代理模式的。就得把旧的pac情景模式删除，再添加新的情景模式。太麻烦了。不如原来的Proxy SwitchySharp的手动配置和自动配置修改方便。
3. 顺带说个，刚安装好教程第4步还是第5个步骤根本无法点，显示问题。按钮都不见了，哪里都无法点击。刷新了就好了，但没法看完教程。
4. 我的chromium用的是chrome-win32.zip
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/316723/

SwitchyOmega 2.3.6
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2308.0 Safari/537.36

**Comment by a8l1vy** [comment]
第三个问题可能是个例，自定义chrome用户配置位置，再一次安装后，教程可以全部点击完。

**Comment by FelisCatus** [comment]
1: 界面太难做……
2: 可以使用虚情景。此外 PAC 改成 HTTP 是可以直接在脚本里写`function FindProxyForURL() { return "HTTP 127.0.0.1:8888"; }`的。
3: 似乎是代码的问题。我之前稍微修了下。
