### ISSUE TITLE
ADBlock屏蔽的资源误判为“资源没有加载”

### ISSUE THREAD

**Issue by myonlylonely** [FelisCatus/SwitchyOmega#293]
资源没有加载的提示是个好改进，但是应该将ADBlock等去除广告软件的屏蔽纳入考虑，不然几乎每个页面都会提示有资源没有成功加载。或者至少提供一个选项关闭提示。

SwitchyOmega 2.3.6
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2307.4 Safari/537.36

**Comment by FelisCatus** [comment]
选项里是可以关闭的，不过我当然还是希望能搞定 ADBlock 相关问题。我应该已经检测其他扩展屏蔽请求相关的错误了，但可能还有些不完善，等我找个 ADBlock 自己试试看吧。

**Comment by myonlylonely** [comment]
可能是个偶然现象。我重新试验了下，目前暂时没有问题了。抱歉，关闭这个问题吧。

**Comment by FelisCatus** [comment]
我要重新开启这个 issue 。似乎这种情况还是存在的，刚才我自己测试过。

**Comment by FelisCatus** [comment]
v2.3.7 已经搞定。
