### ISSUE TITLE
这个扩展好像最近更新了,有几个地方不是很懂过来请教一下

### ISSUE THREAD

**Issue by Loticyang** [FelisCatus/SwitchyOmega#294]
![360 20150218135425984](https://cloud.githubusercontent.com/assets/8101717/6243152/e0955fa2-b776-11e4-8d8d-4eb3b1f29622.jpg)
![360 20150218135520375](https://cloud.githubusercontent.com/assets/8101717/6243155/e5652026-b776-11e4-9ed9-5775c0b940d7.jpg)

SwitchyOmega 2.3.6
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by Loticyang** [comment]
我用的是360安全,这个右键菜单是指的什么呢?  能不能顺便介绍一下本次更新的内容

**Comment by FelisCatus** [comment]
在网页上某个图片上右键菜单选择“检查该元素使用的代理”即可查看图片而非网页本身使用的代理。适用于图片不在同一个域名之类的情况。

这次的主要更新：[检测网页中未加载的元素并提示代理](https://github.com/FelisCatus/SwitchyOmega/issues/6#issuecomment-74818135)。

**Comment by Loticyang** [comment]
点开以后会显示 X个资源未加载------------------这是不是就相当于autoproxy的可代理资源列表的功能?

**Comment by FelisCatus** [comment]
@Loticyang 对，大致就是那个功能。

**Comment by Loticyang** [comment]
太好了,就等着这个功能就可以放弃firefox了,
另外--------------
gfwlist的规则文件大概100K左右,对浏览器的性能影响怎么样,

原来autoproxy的大规则是很拖火狐的启动速度的,有时候还会卡,

chrome多进程有没有这个问题,    要是多占一点资源倒是无所谓

谢谢!

**Comment by FelisCatus** [comment]
我不知道，你可以试试看。有些人说会卡，另一部分人则说不卡。反正我是不怎么卡啦……而且新版优化的也算是不错，除了加载时和访问第一个网页时会有点延迟，其他的不太影响使用。

**Comment by Loticyang** [comment]
在一些国内的网站也会显示未加载的项目

**Comment by FelisCatus** [comment]
@Loticyang 未加载不代表一定需要代理。可能是网络原因、或者网站服务器本身的问题等等。也可能是由于 AdBlock 等扩展，这个见 #293 ，正在紧急修复中。

**Comment by Loticyang** [comment]
刚刚看到38min前已经放出v2.3.7-----------

大过年的还这么忙,多谢,也祝你新年快乐
