### ISSUE TITLE
图标上的数字是什么意思？

### ISSUE THREAD

**Issue by Magicloud** [FelisCatus/SwitchyOmega#295]
抱歉作为issue提出，大概看了一下，没找到说明。

**Comment by syswow** [comment]
@Magicloud 
在当前页面中，加载失败的链接的数量。

**Comment by Magicloud** [comment]
多谢。那数字似乎还是有点出乎意料，我再观察观察……

**Comment by syswow** [comment]
这样可以更加方便的添加条件了。 :smile:

**Comment by liongmagezi** [comment]
真的是*加载失败*的数量？

**Comment by FelisCatus** [comment]
@liongmagezi 如果您觉得对于某些请求存在误判，请给出一个网站以供分析问题，最好再详细说一下情况。

**Comment by liongmagezi** [comment]
@FelisCatus 刚从`Proxy SwitchySharp`转到`Proxy SwitchyOmega`，对这个数字很好，我还以为是成功的连接数之类的。
