### ISSUE TITLE
页面瞬间发出大量请求的处理

### ISSUE THREAD

**Issue by Tiers** [FelisCatus/SwitchyOmega#296]
打开豆瓣就出现CPU占用20+ chrome卡死的问题 而且该拓展程序图标处出现1000+的小黄数字 疑似BUG?

SwitchyOmega 2.3.6
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by syswow** [comment]
Hi, @Tiers 
麻烦上传Error Log， 我刚试了豆瓣，没有问题。

**Comment by FelisCatus** [comment]
我只能想到两种可能，一种就是真的有那么多请求（比如豆瓣网站上有“若失败则重新加载”的死循环），另一种则是 Chrome 那边做错了什么。
但此外，也不排除和其他扩展冲突的情况……建议检查广告屏蔽扩展等。

**Comment by Tiers** [comment]
@syswow 已卸载= = 卸载后一切正常

**Comment by Tiers** [comment]
@FelisCatus 卸载之后啥事没了= = 应该不是广告屏蔽问题 难道是豆藤?

**Comment by syswow** [comment]
@Tiers 你再装下试试，作者之前更新了一个新版本。

**Comment by FelisCatus** [comment]
谁知道有什么……到现在为止我确实没碰到别人有这类情况。那么很大概率会是“豆藤”的问题。
我只能说，如果真不能用，可以去选项里把检测请求这个选项关掉然后重启浏览器即可。不影响正常使用。

此外，我准备去加一个上限，如果超过多少请求则不显示或者短期内不跟踪请求了。这能有效应对网站或者其他扩展错误行为的情况。

**Comment by syswow** [comment]
@FelisCatus  我这边有个问题，全局代理GoogleDrive，SwitchyOmega显示50+ 。

**Comment by Tiers** [comment]
@FelisCatus @syswow  重装后打开豆瓣依然卡死  试了下卸载豆藤 目前还没发现卡死 可是为什么之前都可以兼容 也就是说两者不兼容去其一即可 但是问题出现在两天前 按拓展更新时间豆藤最近一次更新是1月23 Omega最近一次好像跟问题出现时间相符 因此我怀疑更多可能是Omega的问题 另附上错误报告Options << Options#applyProfile [
    "system"
]
Options << Options#updateProfile [
    [
        "system"
    ]
]
Options << Options#updateProfile []
external proxy:  {
    "levelOfControl": "controllable_by_this_extension",
    "value": {
        "mode": "system"
    }
}
Options << Options#applyProfile [
    "system",
    {
        "proxy": false,
        "system": true,
        "reason": "external"
    }
]

**Comment by syswow** [comment]
@Tiers Hi, 我刚装了 豆藤测试了，没有问题，SwitchyOmega也没有数字显示。我的Chromium是Version 40.0.2214.111 Ubuntu 14.04 (64-bit)。去广告我装的ublock，你试下看看。
因此，我觉得应该是豆藤和去广告的问题吧。

**Comment by Hs-Yeah** [comment]
Chrome for Mac 42.0.2305.3 dev (64-bit) + SwitchyOmega 2.3.7 + Adblock Plus + 豆藤，打开豆瓣不卡，没数字

**Comment by Tiers** [comment]
@syswow  我的chrome跟你一样的版本 广告是AdBlock AdBlock最近更新2 13 怎么感觉可能性不是很大

**Comment by Tiers** [comment]
@Hs-Yeah 我打开豆瓣也不卡 但是打开哪个电影的详细页面就卡死了

**Comment by Hs-Yeah** [comment]
@Tiers 打开了两个电影的详细页面，看了长评、讨论，都没有问题

**Comment by Tiers** [comment]
@syswow  @FelisCatus 有没有可能是我改了google hosts的原因

**Comment by syswow** [comment]
@Tiers HI
我已经重现你的问题了。我SwitchyOmega的数字已经600+了。 等下我上传个视频。
我认为可以肯定的是
1。 和google代理有关。
2。 和豆藤
3。 和SwitchyOmega
装上豆藤，我把连接切换成 全局代理(shadowsocks)之后，就开始这样了。
豆藤会链接国内的资源网盘，这样会发送很多请求，因为用了代理那些请求相当于从国外发往国内，一般这些访问，国内的网盘会限制访问次数和速度。这样下来SwitchyOmega就把那些请求当作 失败资源了。 豆藤不断的请求，SwitchyOmega不断的计数，结果很快就能突破1000+。:smile:  
@FelisCatus 我们可以限制计数上限，或者相同资源的不重复计数，再然后实在连不上就放弃那个链接请求算了， 你觉得呢？

**Comment by FelisCatus** [comment]
1. 解决方案我之前说过了：加一个上限，如果超过多少请求则不显示或者短期内不跟踪请求了。这能有效应对网站或者其他扩展错误行为的情况。（比如一个页面最多跟踪100个错误。）
2. 但是我要说这毫无疑问是豆藤的问题，做了无限的重试请求，不管有没有SO，必将消耗大量系统和网络资源。 SwitchyOmega 只不过是把问题暴露了而已。在我做第一点的同时，我建议 @Tiers 去豆藤报个bug，告诉他们不要无限重试。

**Comment by FelisCatus** [comment]
3: 以及， @Tiers 先去选项界面把跟踪网络请求关掉吧，然后重启Chrome就能暂时解决。等我更新了再通知您。

**Comment by Tiers** [comment]
@FelisCatus 已取消请求 现在一切正常 多谢 我去豆藤反应下

**Comment by Tiers** [comment]
@syswow 多谢 取消请求已解决问题

**Comment by Hs-Yeah** [comment]
今天我也遇到豆瓣页面 SwitchyOmega 计数无限增加的情况了，应该就是跟 @FelisCatus 说的一样，是豆藤无限重试请求的缘故

**Comment by FelisCatus** [comment]
已经可以确认是豆藤的问题了。而且CPU占用是由于豆藤发出大量网络请求的原因，和SO并不相关。SO上那个数字标签看着碍眼，但几乎没有任何性能问题。没有SO的时候，大量网络请求也会消耗那么多资源（这一点已经由其他豆藤用户确认过了），但没有任何提示，因此反而发现不了这个问题。

**Comment by FelisCatus** [comment]
v2.3.8 已经设置单个 tab 请求跟踪上限为 1000 。
