### ISSUE TITLE
add about page

### ISSUE THREAD

**Issue by syswow** [FelisCatus/SwitchyOmega#298]
Hi, @FelisCatus 
现在SwitchyOmega 无法看到当前的版本。不是很方便的确定所用的是否是最新的。
建议把版本信息加进Menu， 或者Option里。 :smile:

**Comment by Loticyang** [comment]
早就想说了

**Comment by FelisCatus** [comment]
既然提出来了，那我再多说点吧。现在的软件缺少一个“关于”界面，无论是版本号、贡献者列表还有什么的都没地方显示。要做就一起做了吧……

**Comment by FelisCatus** [comment]
v2.4.2 已经添加“关于”页面，可以在选项页面点击左上角 SwitchyOmega 字样查看。

v2.4.2 Added an about page on the options page. It is accessible through the top-left link that reads "SwitchyOmega".
