### ISSUE TITLE
System proxy selection

### ISSUE THREAD

**Issue by Rurik19** [FelisCatus/SwitchyOmega#299]
Why there isn't a choise "System proxy" in menus in auto switch and in site filter menu?

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 YaBrowser/14.10.2062.12544 Safari/537.36

**Comment by FelisCatus** [comment]
See #289.
