### ISSUE TITLE
Bug: addConditionForDomains(...) 第一个参数未对 IP 地址进行正确处理

### ISSUE THREAD

**Issue by XiaoSK** [FelisCatus/SwitchyOmega#301]
![err](https://cloud.githubusercontent.com/assets/4531292/6305056/6eea349c-b963-11e4-8fce-4a47e2878e22.png)

**问题描述：**
在自动切换模式但不限于该模式下，插件自动检查出访问失败的请求，会做出提示，但提示列表显示对于 IP 地址的提示就不对了。
比如，host 为域名的 www.z.cn 可以正常处理为 *.z.cn ，但是 host 为 IPv4 地址的 74.125.235.200 会处理为 *.74.125.235.200，host 为 IPv6 地址的 2404:6800:400a:801::1001 也会出现处理错误。

**测试情况：**
必现，确认为设计缺陷。

**解决建议：**
对于 IPv4 地址或 IPv6 地址，应该区别于普通域名进行识别并使用不同的提示信息和处理方式。
本人不熟悉 Jade 和 CoffeeScript 就不提交补丁了，希望作者尽快解决这个问题。

**涉及文件包括但不限于：**
popup.coffee
popup.jade

**备注：**
SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
感谢您详细的测试报告。

问题1：以IP地址为基础自动创建规则时，都用的是`*.`加地址。任何自动创建通配符字符串的地方都有这个问题。以及，`popup.jade`里有硬编码`*.`加地址的情况存在，但只对于用户显示，不影响逻辑。这部分也要改。
解决方式：重构移除popup.coffee中的相应代码，迁移到 omega-pac 模块。IPv4/IPv6地址在`Utils.getBaseDomain`已经有判断，但此判断未用于创建规则。抽取判断逻辑，建立一个新的函数。

问题2：`*.z.cn`未匹配`z.cn`？亲自测试，结果并非如此。这部分[有单元测试保证](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-pac/test/conditions.coffee#L113-L115)。
以及我刚才自己试过，没有此问题。类似的，`*.`加IP地址也是能匹配的，尽管规则看上去很难看……

总结：确实是bug但暂时不影响使用。于是不发布紧急修复了，等下个版本一起解决掉吧。

**Comment by XiaoSK** [comment]
Thanks.

**Comment by FelisCatus** [comment]
未加载的资源处 IP 地址现在可以正常添加规则了。但弹出菜单中手动添加条件的表单还是没做修改（主要是考虑到效率问题）。

**Comment by FelisCatus** [comment]
v2.3.12 已经修复。
