### ISSUE TITLE
在ubuntu上编译失败

### ISSUE THREAD

**Issue by syswow** [FelisCatus/SwitchyOmega#303]
@FelisCatus Hi
之前在Windows上编译成功，但现在在Ubuntu14.04上却出错了。
提示信息： https://gist.github.com/syswow/1167244b8811ed7ba66d
请帮忙看下是怎么回事。

**Comment by FelisCatus** [comment]
[This is most likely a problem with the coffeelint package](https://gist.github.com/syswow/1167244b8811ed7ba66d#file-so-build-error-L5).

暂且可以试试看修改 `omega-pac/package.json`，把 `grunt-coffeelint` 限定下版本：

```
...
"grunt-coffeelint": "=0.0.13",
...
```

然后再 `npm install` 试试。

**Comment by syswow** [comment]
改了之后在然后在omega-build， 运行npm run deps，提示少了browserify， 然后sudo npm install browserify才解决问题（不能加-g，不知道为什么）， 但之后又出现问题git clone Permission denied 的问题。
详细log请看：https://gist.github.com/syswow/c643e8ca40334d8de030

**Comment by FelisCatus** [comment]
我记得 README 里应该说过 npm 需要 2.0 以上的吧……

**Comment by syswow** [comment]
恩，我用的不是官方源的nodejs，没注意npm版本只有1.4.28, 
我现在升级npm再试试。

**Comment by syswow** [comment]
@FelisCatus 编译成功，Thanks。
我还有个问题为什么 npm install npm -g. 的结果npm还是原来的版本；npm install -g npm的话才行？

PS： 期间还有个 “npm WARN locking Error: EACCES, open”的错误。要修改权限
    chown -R syswow /home/syswow/.npm

**Comment by FelisCatus** [comment]
先关闭了，看样子不是 SO 这边的问题……
