### ISSUE TITLE
建议加入域名/资源重定向功能

### ISSUE THREAD

**Issue by volltin** [FelisCatus/SwitchyOmega#304]
感谢 @FelisCatus  辛苦开发 :+1: 

建议整合一些 https://github.com/ranjez/Switcheroo/ 的功能，就是对某些域名或者静态资源资源重定向，减少加载失败。

最典型的例子就是如果把```http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js```重定向到```ajax.useso.com```或者```lib.sinaapp.com```，在不翻墙状态下，很多网站打开缓慢甚至功能不正常的问题都可以解决，而且有时候这样比翻墙加载来得更快。

**Comment by FelisCatus** [comment]
想了很久，还是别做这个了吧。归根结底SwitchyOmega还是设置软件，更改请求什么的并非扩展的本意，而且这一步走得太远了。

而且，既然同样的功能其他扩展也可以做，且不需要依赖SO的核心代码，那么就没必要非要集成在一起，对吧？
