### ISSUE TITLE
CPU占用率略大

### ISSUE THREAD

**Issue by likani3** [FelisCatus/SwitchyOmega#307]
现在这个版本发现CPU占用很大，至少我这里是这样的，一般占用了25%，CPU是i5-2450M

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by syswow** [comment]
Hi @likani3 
可以说下你是在访问哪个网页吗？ 我这边测试SO的CPU占用正常。
另外是在页面加载时瞬间占用25%，还是持续25%呢？

**Comment by FelisCatus** [comment]
感觉这边的情况是很难说了……最好有详细一点的报告，或者性能分析之类的。给个Shift+Tab弹出窗口的截图也行啊……

**Comment by FelisCatus** [comment]
这边太长时间没有更新了，并且缺少可以定位问题的关键信息。暂时关闭 issue 了，如有更新请重新开启。
