### ISSUE TITLE
工具栏图标无法明显区分当前网页是直连还是代理

### ISSUE THREAD

**Issue by zzp0** [FelisCatus/SwitchyOmega#308]
不如老版本的图标那样明显，不知是作者有意为止，还是瑕疵？
*不过还是感谢作者的工作* ;-)

**Comment by syswow** [comment]
Hi @zzp0 
#107 已经在讨论这个问题了，现在还没有具体的改进与设计，欢迎给出建议啊。

**Comment by hcwhan** [comment]
我觉得
1.自动切换 : 内圈白 外圈 无适配规则为灰 有适配规则为代理设置色
(意思是内圈白直连为主要 外圈为根据规则连接)

强制某代理模式: 内外圈全为代理设置色 (意思是全走某代理)
3直接连接(无代理): 内外圈全为白
(意思是全直连)

4系统代理: 内圈黑 外圈白
(意思是内圈黑 为浏览器外来控制规则)

白色意味直接连接 有色代表代理

**Comment by hcwhan** [comment]
简单 直接 易懂 双色代表规则适配 单色代表 某种代理

**Comment by FelisCatus** [comment]
请统一在 #107 讨论。
