### ISSUE TITLE
加大 自动规则 的 列宽 或者 当 点击进入 输入框 后 放大 输入面积 

### ISSUE THREAD

**Issue by hcwhan** [FelisCatus/SwitchyOmega#310]
加大 自动规则 的 列宽 或者 当 点击进入 输入框 后 放大 输入面积 
以便 较长正则的编辑

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by hcwhan** [comment]
放大 输入面积  可以做成类似 规则列表正文 样式

**Comment by hcwhan** [comment]
不是强烈需求 只是建议
如果感觉更改量相对需求量没那么大 可以不做
谢谢

**Comment by hcwhan** [comment]
现在的编辑源代码窗口已经很好用了

**Comment by FelisCatus** [comment]
请给一张在您屏幕上的截图，以便估测实际需要的宽度。每个人的字体和屏幕分辨率不同，可能会不太一样……

**Comment by hcwhan** [comment]
![image](https://cloud.githubusercontent.com/assets/7278897/6413135/2813649e-bec7-11e4-845b-6422b5edee4d.png)

**Comment by FelisCatus** [comment]
我感觉是不太能再放大了（以及表达式确实太长了……）。

所以我还是决定不去动这边了。但是您可以使用编辑源代码功能。
以及，我打算把编辑源代码的输入框稍微放大一点。

**Comment by hcwhan** [comment]
嗯是的 编辑源代码 还是很好用的
谢谢了

**Comment by FelisCatus** [comment]
v2.3.8 更新后，点击任何源代码输入文本框后，均会自动加宽。此外， Chrome 还提供了一个手动调整文本框大小的方式：拖动文本框右下角。
