### ISSUE TITLE
有未加载资源时，弹出菜单加载过慢

### ISSUE THREAD

**Issue by marzkto** [FelisCatus/SwitchyOmega#311]
昨天刚刚从Sharp升级到Omega，发现Omega点击拓展图标后几乎延迟了1秒才出现菜单，然而Sharp却几乎没有延迟，请问我需要设置什么吗，谢谢。

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by marzkto** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/211
https://github.com/FelisCatus/SwitchyOmega/issues/162
刚发现我不是一个人啊=-=
下拉菜单界面的弹出时间间隔有1秒。
从其他情景模式切换到自动切换的模式时大概有半秒延迟，而反过来却几乎无延迟

**Comment by netroby** [comment]
Upgrade your chrome to latest version, I can see no problem there.

**Comment by marzkto** [comment]
刚升级了40.0.2214.94
但是下拉菜单的呼出速度并没有明显改善，与其他拓展相比还是慢。
猜测是因为新UI设计导致硬件占用高造成的=-=

**Comment by netroby** [comment]
Latest Version 40.0.2214.115 (64-bit)

**Comment by marzkto** [comment]
换了个32位的40.0.2214.115，和40.0.2214.94表现没什么区别=-=
据说现在很多插件比如支付宝证书什么的都不支持64位的，所以我也从来没用过64-bit版本

目前看起来两者不可兼得啊-_-//

**Comment by Tback1** [comment]
我也出现了这个问题，但是这个问题不是因为代理引起的，而是因为检测未加载资源造成的，但是前面的版本添加检测后，没有出现这个问题。  @FelisCatus  是因为3.27的检测调用上改变了某些流程照成的么？

**Comment by vicentory** [comment]
的确是这样，还可以接受，我以为是电脑配置低的原因。

**Comment by FelisCatus** [comment]
我觉得我需要好好检查一下。正好检测那边的显示要做些改进，就一起做了吧。

**Comment by FelisCatus** [comment]
我重构了下未加载资源的后台处理效率，不知道现在是否快一点了。请试试看 v2.3.8 更新，然后反馈下是否有改善。

如果延迟还是很高的话，那我就只能怀疑 Chrome 本身的开启 port 效率问题了……

**Comment by FelisCatus** [comment]
有没有人更新 v2.3.8 后尝试过？有未加载资源时，弹出菜单是否还有明显延迟？

**Comment by marzkto** [comment]
所谓有未加载资源时的延迟的现象并没注意过。。。现在换回了Sharp，新版设计还是不习惯=-=

**Comment by vicentory** [comment]
更新了，感觉是变快了

**Comment by FelisCatus** [comment]
那就好……

**Comment by FelisCatus** [comment]
[v2.4.3 版本](https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.4.3)重制了一个新的弹出菜单实现，希望能快一点。目前此版本还在测试中，有兴趣的话可以直接点链接下载安装。有问题请及时回报。
