### ISSUE TITLE
所以YouTube用户的头像都显示不了？

### ISSUE THREAD

**Issue by Sirapoy** [FelisCatus/SwitchyOmega#313]
SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与 SwitchyOmega 无关。如果您正在使用 GFW List ，您也可以去那边提交反馈。
