### ISSUE TITLE
"Resource not load" detect not correct

### ISSUE THREAD

**Issue by LakeChan** [FelisCatus/SwitchyOmega#314]
When i open www.google.com.hk and failed to open it,it shows i should add " *.com.hk " to rule list rather than add " *.google.com.hk "

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
Thanks for the report. This is caused by a naive and wrong implementation of the "base domain extraction" algorithm and is already tracked at #276. I will try to fix this in the next version.
