### ISSUE TITLE
unable connect to Google

### ISSUE THREAD

**Issue by randalchai** [FelisCatus/SwitchyOmega#315]
Dear Administrator,

i'm can't to access google webpages since I reinstalled my computer in last year;
but i can open other website(voanews.com and so on) when use swithyomega with goagent.

please help me.

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
This is more likely to be a problem with GoAgent and should be posted on the GoAgent issue tracker instead.
