### ISSUE TITLE
SwitchyOmega button icon

### ISSUE THREAD

**Issue by rjahanbakhshi** [FelisCatus/SwitchyOmega#316]
Hello, 

Thank you for this great chrome extension. One question. What is the number on the SwitchyOmega button icon? It's really irritating because I think there is a notification or something in the chrome. Is it possible to turn it off somehow?

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
This is the count of web requests (of resources in the current tab) that fails to load. You can turn it off in the Options > General > Network Requests if you don't like it.

**Comment by FelisCatus** [comment]
The help text is improved for failed resources in the popup menu in v2.3.8. Also, a button labelled "Manage Network Monitor" is added to the form which can be used to open the relevant options page.

**Comment by rjahanbakhshi** [comment]
OK, Thank you.
