### ISSUE TITLE
代理在隐身窗口下无效

### ISSUE THREAD

**Issue by treblam** [FelisCatus/SwitchyOmega#317]
设置的代理在隐身窗口下无效，记得switchy sharp之前是可以的，omega不支持隐身窗口代理。

**Comment by FelisCatus** [comment]
由于 Chrome 限制，扩展设置的代理设定默认不在隐身窗口生效。如需使用，在`chrome://extensions/?id=padekgcemlokbadohgkifijomclgjgif`这个页面的 SwitchyOmega 图标下方勾选“允许在隐身模式使用”选项即可。
