### ISSUE TITLE
为什么用了omega之后，可以打开谷歌邮箱，但是上不了YouTube之类的网站呢？

### ISSUE THREAD

**Issue by mmmckx** [FelisCatus/SwitchyOmega#319]
你好，
为什么用了omega之后，可以打开谷歌邮箱或者谷歌相关的产品，但是上不了YouTube、脸书、推特之类的网站呢？

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题与 SwitchyOmega 无关。
