### ISSUE TITLE
SwitchyOmega 图标上经常会有数字，代表什么意思

### ISSUE THREAD

**Issue by gao808oriental** [FelisCatus/SwitchyOmega#320]
如题

**Comment by ynyounuo** [comment]
麻烦自己点开看一下

**Comment by iectl** [comment]
昨天我也发现了这个问题，以前都没有出现过，只要打开网页，在每个网页的SwitchyOmega图标上就会出现数字，几十到几千不等，每一个网页上图标显示的数字都不一样，有时还会有增长的情况，然后点开发现在第三行出现以下字体：**个资源下载未加载。然后点击这行字体，就会出现要求添加要求到情景模式的页面选项，即使最后添加条件了，这些数字也始终无法消失。但不影响浏览网页，只是感觉这个图标上的数字看上去很不舒服，请问这是什么 原因呢？

**Comment by ynyounuo** [comment]
# 这是个非常好用的功能，告诉你后台有什么网址被墙或者无法加载，然后可以添加规则
# 这不是个 bug

**Comment by FelisCatus** [comment]
数字表示在当前页面中，加载失败的资源数量。这个只是一个统计功能，反映了网络（或代理服务器）实际工作情况，仅供参考。网络错误本身并非 SwitchyOmega 导致。

如果不喜欢此功能，可以在设置>通用>网络请求中关闭资源检测。

**Comment by FelisCatus** [comment]
```
即使最后添加条件了，这些数字也始终无法消失
```
这个是一个bug导致，在 v2.3.8 中已经修复了。添加条件后再刷新页面，不会错误地统计之前加载失败的项目了。
