### ISSUE TITLE
图标会有数字出现，资源未加载

### ISSUE THREAD

**Issue by nail2049** [FelisCatus/SwitchyOmega#321]
![image](https://cloud.githubusercontent.com/assets/5564959/6410673/1e14cd2c-beac-11e4-9210-08fc0d382d33.png)

![image](https://cloud.githubusercontent.com/assets/5564959/6410680/24042dc2-beac-11e4-9120-9e96a3c6828b.png)

![image](https://cloud.githubusercontent.com/assets/5564959/6410682/28aedc5a-beac-11e4-9da8-3d4c428a8de8.png)

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
数字表示在当前页面中，加载失败的资源数量。这个只是一个统计功能，反映了网络（或代理服务器）实际工作情况，仅供参考。网络错误本身并非 SwitchyOmega 导致。

如果不喜欢此功能，可以在设置>通用>网络请求中关闭资源检测。

**Comment by nail2049** [comment]
非常感谢，虽说不太明白，知道没什么关系就放心了。看到数字标到几千的时候还是很担心的。再次感谢

**Comment by FelisCatus** [comment]
数字如果好几千的话，肯定是页面或者扩展真的发送了好几千个请求。一个其他扩展发送大量请求的例子： #296

**Comment by dongqisheng520** [comment]
我上Google+的时候会出现很多未加载资源，其他网站都不会。
