### ISSUE TITLE
只能上google，其它网站不能上！

### ISSUE THREAD

**Issue by ahonge** [FelisCatus/SwitchyOmega#324]
只能上google，其它网站不能上！

SwitchyOmega 2.3.7
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.93 Safari/537.36

**Comment by FelisCatus** [comment]
网络问题或代理服务器问题，与 SwitchyOmega 无关。
