### ISSUE TITLE
Autoswitch not working

### ISSUE THREAD

**Issue by efrazier** [FelisCatus/SwitchyOmega#325]
I have a proxy (mitmproxy) set up with basic auth. I want to only proxy connections for a few websites and go direct on everything else.  It looked like this would work great with your ext as it is the only one I have seen that supports this logic, but I can't get it to work. The proxy and auth works fine if I select it directly. but a simple host match with *.example.com --> mitmrproxy etc, doesn't work. 

Note, I have had the same exact problem with a simple pac file and I could swear I have read everything Google has to offer on the subject including about .pac file correct mime type, application/x-ns-proxy-autoconfig and that some versions of IE will refuse to load local pac files. 

I am using Windows 7. 

Thanks very much, this is a cool tool if I can get it working fully. 

Eric 

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
Please give a screenshot of your Auto Switch profile (with focus on the switch rules section).

The simple PAC file is another topic though. SwitchyOmega does allow configuring proxy authentication for PAC files, but that would definitely not work with IE because SwitchyOmega can set the proxy settings and provide the username/password only in Chrome. It would be very helpful if you upload the PAC file to https://gist.github.com/ .

**Comment by efrazier** [comment]
![image](https://cloud.githubusercontent.com/assets/3696386/6426699/8aeac46e-bf25-11e4-8062-cceb08a6b89a.png)


I am not as concerned about IE, except that it seems like I am missing something.  The pac file I was trying was super simple: 

function FindProxyForURL(url, host) {
    if (
        localHostOrDomainIs(host, "www.cnn.com")
    ) {
        return "PROXY ip:port";
    } else {
        return "DIRECT";
    }
}

I am not so concerned about getting IE to work regarding auth, my main goal is to not proxy everything under the sun, just select domains. 

Thanks very much,

Eric

**Comment by FelisCatus** [comment]
@efrazier I don't think there's anything wrong with your Auto Switch configuration. What do you mean exactly by "doesn't work"? Does the page fail to load? Or is it the authentication dialog that didn't popup for you?

**Comment by efrazier** [comment]
Sorry, I hate it when people say, "it didn't work" can't believe I did.  The issue is that on auto, the specified site goes to DIRECT.

**Comment by FelisCatus** [comment]
Could you press the "Export PAC" button on the toolbar of the profile "Auto Switch"? It should generate a PAC file which you can upload to https://gist.github.com/ . That would be very helpful. (The result PAC file will not contain any passwords and should be safe.)

**Comment by efrazier** [comment]
https://gist.github.com/efrazier/30d906e345e0e11cb3f8

Thanks.

**Comment by FelisCatus** [comment]
This is a PAC file for the "+custom Proxy" profile itself. What I really need is that of "Auto Switch", as described above. Please first select "Auto Switch" in the left navbar, and then click on the export button.

**Comment by FelisCatus** [comment]
Any updates?

**Comment by FelisCatus** [comment]
I would like to follow up on this issue. Could you just provide the exported PAC file for "Auto Switch" as detailed above? It wouldn't take you a lot of time to do that.

**Comment by FelisCatus** [comment]
I'm closing this issue because it seems abandoned by its original reporter while still lacking important information. Please do reopen if you have more information or questions.
