### ISSUE TITLE
AutoSwitch doesn't kick in

### ISSUE THREAD

**Issue by martzuk** [FelisCatus/SwitchyOmega#326]
When visiting a site, in this case an HTTPS site, the script doesn't kick in until after the page has loaded, clicking cancel on the proxy auth does nothing as the proxy isn't actually used.

SwitchyOmega 2.3.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
AutoSwitch works through PAC scripts, and should be applied as soon as you select it from the popup menu. There shouldn't be anything related to timing.

But, based on your description, it's most likely that the page you are trying to load is NOT sent via the proxy, while at least *one resource contained in the page* is configured to use proxies via the Auto Switch rules. In that case, you may want to double check your switch rules.

Please post a screenshot of your switch rules and the URL of the website in question when in doubt. You may change or mask the domain a little bit to protect your privacy.

**Comment by martzuk** [comment]
URL is https://broadcasthe.net/
Screenshot: https://www.dropbox.com/s/qnui5l2mfaiy8o9/Screenshot%202015-03-01%2016.57.07.png?dl=0

**Comment by FelisCatus** [comment]
Unfortunately I can't reproduce the problem on my computer.

Could you press the "Export PAC" button on the toolbar? It should generate a PAC file which you can upload to https://gist.github.com/ . That would be very helpful.

**Comment by martzuk** [comment]
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+Auto Switch", {
    "+Auto Switch": function(url, host, scheme) {
        "use strict";
        if (/broadcasthe\.net$/.test(host)) return "+lhr01";
        if (/passthepopcorn\.me$/.test(host)) return "+lhr01";
        return "DIRECT";
    },
    "+lhr01": function(url, host, scheme) {
        "use strict";
        if (host === "[::1]" || host === "localhost" || host === "127.0.0.1") return "DIRECT";
        switch (scheme) {
          case "http":
            return "PROXY x.x.x:3128";

          default:
            return "DIRECT";
        }
    }
});

**Comment by FelisCatus** [comment]
This is caused by a wrong configuration in lhr01 and has nothing to do with Auto Switch. Please do not set rows other than "(default)" in the proxy servers settings. Note that "Scheme" is for matching URLs and should not be separately configured unless you want different proxies for HTTP, HTTPS and FTP. Such cases are pretty uncommon, and that's why these rows are hidden by default.

**Comment by martzuk** [comment]
Must've been when I imported from the old version, thanks!
