### ISSUE TITLE
使用SwitchyOmega以后，必须要开goagent才能联网

### ISSUE THREAD

**Issue by rescue1** [FelisCatus/SwitchyOmega#330]
旧版switchysharp，如果没有开goagent，访问大陆境内网站没问题。
新版SwitchyOmega，无论选中是直连还是代理模式，只要goagent没有启动起来，访问任何网络都会连不上。这样家里人用起来很不方便，他们不会用goagent和切换代理模式。

**Comment by FelisCatus** [comment]
首先我就不是很相信选择“直接连接”的时候还会走代理……

倒是不妨试试看，选择“直接连接”，然后打开`chrome://net-internals/#proxy`页面，将那边的内容复制到这里。如果选择“直接连接”时，还在使用代理连接的话，那就只可能是扩展冲突或者SO故障两种可能了。可以使用菜单中的“错误日志”功能来查看SO是否故障，并提交错误日志以供解决问题。

**Comment by rescue1** [comment]
解决了，还是版本冲突的问题。
