### ISSUE TITLE
考虑加入 hosts 代理功能吗？

### ISSUE THREAD

**Issue by Riant** [FelisCatus/SwitchyOmega#332]
非常感谢这个插件给予的开发、测试、各种方便。
配合 Fiddler 舒服极了。

最近遇到另一个插件，Host Switch，团队惊呼神器，可惜两个代理插件不能同时开启。

SwitchOmega 可以考虑加入 Host Switch 类似的功能吗？（https://github.com/shendongming/chrome-host-switch ）

当然其他一些软件也能实现类似功能，不过奈何几乎都是管理 Windows Hosts 文件内容的，切换之后生效会有延迟，始终不爽。
另外，Fiddler 的 Tools 菜单下也有Hosts 工具，切换很及时，奈何开启/关闭切换起来不如他的AutoResponser 方便快捷。

非常感谢。
SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by FelisCatus** [comment]
看了下 Host Switch 感觉挺神的……

关于整合之类的，希望还是看下 #44 的讨论。我还是希望通过协作来解决这类事情，而非把所有功能都弄进SO来。
