### ISSUE TITLE
使用同步功能后出现Syncing is disabled for this profile for using too much storage space

### ISSUE THREAD

**Issue by avkiller** [FelisCatus/SwitchyOmega#333]
多个浏览器同步的时候出现这个问题

假设说我对某个浏览器的同步感兴趣，但是之前服务器上已经有一个copy，此时SwitchyOmega会怎么处理？

**Comment by FelisCatus** [comment]
1. 同步存储空间是有限制的，一些特别大的就是上传不上去，也不用抱怨了。一般来说比较大的PAC脚本什么的会出现这种情况。
2. 见 #282

**Comment by avkiller** [comment]
![qq 20150306092345](https://cloud.githubusercontent.com/assets/4780139/6518572/b057b7d6-c3e2-11e4-872f-1d25097d4e26.png)

几乎每个规则都提示这样

**Comment by FelisCatus** [comment]
我不知道你做了什么，但显然总的存储容量已经用完了，目测新增任何情景模式都会这样了……
这样的话就需要先删掉占用空间比较大的几个情景模式，然后新增的情景模式就能正常同步了。

存储使用情况的界面暂时没有精力做，可关注 #272

**Comment by laike9m** [comment]
+1 很蛋疼啊这个

**Comment by FelisCatus** [comment]
Chrome 扩展选项同步的存储容量是有一个限制的，总共只有100KB。这个限制是由谷歌服务器决定的，对此表示无能为力。遇到这种情况只能把一些比较大的情景模式删掉或者改掉再试了。当然如果不需要自动同步的话可以把同步关掉，改用导入/导出文件的方式等。

**Comment by huageorg** [comment]
如果谷歌有100KB限制的话，那真是蛋痛啊，给个1024KB也满足很多应用设置了。

**Comment by fakhamatia** [comment]
@huangzhuohua 
Its possible to use GitHub gist to sync between ?
