### ISSUE TITLE
自动切换功能建议

### ISSUE THREAD

**Issue by kkwking123** [FelisCatus/SwitchyOmega#334]
自动切换功能，旧版本的SwitchySharp，会有状态提示，提示当前网站是否有在翻墙，但新的omega，无论有没翻墙，图标都是一样的，让我无从判断，是否处在翻墙状态下！

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by xinhugo** [comment]
会显示：当前链接是否使用代理连接的，你可能需要设置颜色。

**Comment by xinhugo** [comment]
同时，要选择某个自动切换模式，鼠标放在上面，会有提示（根据条件切换）。
