### ISSUE TITLE
自动切换情景模式绑定不同代理?

### ISSUE THREAD

**Issue by raidsan** [FelisCatus/SwitchyOmega#335]
一般情况下的情景模式,  并不需要指定哪个网站必须走哪个代理,  只是用代理或不用代理的区别(前端网站设置),   而后端代理设置: 一个代理不通了, 需要手工切换到下一个代理,  
这种情况下, 得设置多个自动切换情景模式, 而其中的网站设置内容(包含很多规则)是相同的, 重复的,  
能不能设置一次网站配置(哪些网站是否使用代理规则, 并不需要指定具体的代理服务器), 然后在多个情景模式里调用, 不同情景模式再绑定不同的代理服务器?

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by xinhugo** [comment]
扩展已经支持：批量设置所有规则的情景模式

**Comment by FelisCatus** [comment]
目前的解决方案是新建一个虚情景模式（比如叫“总代理”），然后在规则的目标都设置成“总代理”。之后“总代理”可以方便地设置使用这个或者那个代理，也能在菜单里快速切换。

**Comment by cryptogun** [comment]
明白了, 虚情景模式就相当于未知数x/接口/界面/pipe/中间件/中间代理类似的作用. 先把自动切换里要翻墙的网址改成未知数x, 再一键把未知数x(虚情景模式)指向SS或者蓝灯. 这就一键批量修改网址规则了.
输入网址-自动切换模式-虚情景模式-SS模式-Internet.
只是`虚情景模式`这名字取得不怎么好, 无法直接读出他的实际用途.
P.S. 可以在自动切换模式里点击`编辑源代码`批量修改替换模式名, 不需要一个个修改累计出来的百多个网址规则.
