### ISSUE TITLE
自动切换相关

### ISSUE THREAD

**Issue by MSG-maniac** [FelisCatus/SwitchyOmega#337]
下一个版本是否能加一个一键选择自动切换。
我的环境是这样的。
家里一个路由。
公司用本机的ss

所以选择自动切换每次都得重新修改规则
127.0.0.1
或者
家里路由器地址

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by nsznsznsz** [comment]
你把那个转向地址设为一个虚情景模式 然后自动切换到那个虚情景模式里 这样你只用改虚情景模式里转向的地址就可以了

**Comment by MSG-maniac** [comment]
OK多谢。
