### ISSUE TITLE
资源添加仍然有未加载提示？

### ISSUE THREAD

**Issue by mysoko** [FelisCatus/SwitchyOmega#338]
新加坡ip

访问github提示这个资源未加载：
![image](https://cloud.githubusercontent.com/assets/75619/6539474/c7d5a9b8-c4af-11e4-91ac-ac127a4c3695.png)

然后添加：
![image](https://cloud.githubusercontent.com/assets/75619/6539486/2bf92d84-c4b0-11e4-80b3-8c95388bce97.png)

仍然不行，请问是什么原因。

SwitchyOmega 2.3.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by learningendless** [comment]
为什么我打开Gmail邮箱，里面的图片都一直是裂的？看不到图，google+上的图绝大多数也都是裂了，有没有什么办法？

2015-03-07 9:54 GMT+08:00 mysoko <notifications@github.com>:

**Comment by FelisCatus** [comment]
比较怀疑是网络问题或者对方服务器问题……那种情况可能走或者不走代理都一样。
