### ISSUE TITLE
大哥，是否可以提供一个支持mac safari中安装的这个软件？

### ISSUE THREAD

**Issue by qq308745107** [FelisCatus/SwitchyOmega#339]
SwitchyOmega 2.3.8
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
之前做过调查，Safari 的扩展功能实在是太有限，应该没有办法实现了吧。以及…… Safari 似乎是使用系统的代理设置的，本身没有代理设置。
