### ISSUE TITLE
导出部分有代码残留.

### ISSUE THREAD

**Issue by zhangyubaka** [FelisCatus/SwitchyOmega#340]
导出至ssrl上方仍然是
; Summary: Proxy Switchy! Exported Rule List
; Date: YYYY/MM/DD
; Website: http://bit.ly/proxyswitchy
应该吧Proxy Switchy和下面的Website更换掉

**Comment by FelisCatus** [comment]
现在导出的列表有两种风格，兼容和新式。新式的话已经加了相应的说明，并链接到本项目。而兼容模式的列表到现在为止写的都还是 Proxy Switchy 。之前的 SwitchySharp 也是用的旧的说明。

因为这个属于注释的一种，所以实际上确实是可以随意修改的。不过嘛……我觉得我懒得改了。反正这是兼容格式嘛，还在用旧的说明也…没什么……的吧？

**Comment by zhangyubaka** [comment]
至少把Website改一下OAO

**Comment by FelisCatus** [comment]
那就把 website 改一下吧。现在默认是链接到[wiki中的规则列表使用帮助](https://github.com/FelisCatus/SwitchyOmega/wiki/RuleListUsage) 页面了。
请等待下次更新发布。（预计版本号： v2.3.9 ，发布时间：待定）

当然，如果想要修改其他说明的话，随时可以手动编辑那个文件。

**Comment by FelisCatus** [comment]
v2.3.9已经修复。
