### ISSUE TITLE
添加条件到情景模式忽略了是否勾选

### ISSUE THREAD

**Issue by ActiveVolcano** [FelisCatus/SwitchyOmega#343]
X个资源未加载 - 添加条件到情景模式

每个域名前面有复选框，下面有文字提示“对所有选中域名使用此情景模式”，但其实不论是否勾选，只要点击添加条件按钮，都会将所有域名添加到情景模式。

**Comment by FelisCatus** [comment]
看来是我做得太急，忘记了……

**Comment by FelisCatus** [comment]
修复已经提交，请等待下次更新发布。（预计版本号： v2.3.9 ，发布时间：待定）

**Comment by FelisCatus** [comment]
v2.3.9已经修复。
