### ISSUE TITLE
备份文件格式错误

### ISSUE THREAD

**Issue by AzureDR** [FelisCatus/SwitchyOmega#344]
在线恢复备份的时候，出现此提示，重装电脑之前明明是很好用的。这有可能是什么问题造成的呢？

**Comment by AzureDR** [comment]
经测试，通过本地备份文件导入也提示“备份文件格式错误”

**Comment by AzureDR** [comment]
经测试，导出空白配置文件，再尝试从此本地备份导入（其实没有任何设置），依然显示备份文件格式错误 T 。T

**Comment by FelisCatus** [comment]
这样的话，把你那份备份文件传上来看看？可以上传到 https://gist.github.com ，然后发个链接过来。

**Comment by helloqingfeng** [comment]
我也遇到了，好着急啊

**Comment by FelisCatus** [comment]
@helloqingfeng 既然着急的话麻烦把备份文件传上来看看啊……不然彼此都是干着急啊……

**Comment by AzureDR** [comment]
@FelisCatus 
重装电脑以后问题解决。

期间，软件安装包、备份文件都是硬盘上的原文件

所以确定不是软件的问题。

**Comment by FelisCatus** [comment]
@AzureDR 好吧，虽然不知道是为什么，但解决了就好了。如果有任何其他问题或者更多信息，请重新开启此 issue 。
