### ISSUE TITLE
在SwitchOmega选项中增加域名通配符并将其情景模式设置为GoAgent，全局设置成自动切换。打开这个域名后仍然是自动模式而不是我设置的GoAgent

### ISSUE THREAD

**Issue by grcpeng** [FelisCatus/SwitchyOmega#346]
在SwitchOmega选项中增加域名通配符并将其情景模式设置为GoAgent，全局设置成自动切换。打开这个域名后仍然是自动模式而不是我设置的GoAgent。

SwitchyOmega 2.3.8
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
鼠标悬停在图标上可以查看具体匹配规则的情况，以及当前页面使用的是哪个情景模式。这里应该会显示某个代理情景模式，或者直接连接。

此外，可以观察图标的颜色。当前页面使用代理时，外圈颜色为那个代理情景模式的颜色。而使用直接连接时，外圈颜色为灰色。

**Comment by grcpeng** [comment]
突然间又好了，谢谢FelisCatus！
