### ISSUE TITLE
Windows7下PAC脚本的proxy变量需要手动修改

### ISSUE THREAD

**Issue by liuyangcharlie** [FelisCatus/SwitchyOmega#347]
忽略下图中浏览器中的PAC文件，这张截图是改过之后的
![win_7](https://cloud.githubusercontent.com/assets/6851070/6632005/3e99cdc2-c96a-11e4-9a42-1c43c4724477.png)
![win_11](https://cloud.githubusercontent.com/assets/6851070/6632016/959d7dbc-c96a-11e4-8456-0362feffda41.png)
![win_12](https://cloud.githubusercontent.com/assets/6851070/6632022/a1daab90-c96a-11e4-99ec-970e0bb71c56.png)
还试过Mac下的编辑PAC脚本的功能，不需要手动修改

**Comment by FelisCatus** [comment]
请问第一张图右下角那个托盘图标和菜单是哪个项目提供的？我看了下，感觉上是那个项目把设置导入到SwitchyOmega中使用，这样的原理。

如果是这样，那么脚本是由那个项目生成的，似乎应该去找那个项目反馈。

**Comment by liuyangcharlie** [comment]
对不起，点错项目了
