### ISSUE TITLE
希望加一个verbose选项

### ISSUE THREAD

**Issue by ztq56** [FelisCatus/SwitchyOmega#348]
如firefox的AutoProxy可以在popup界面看到本页面的请求hit了哪些规则

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by FelisCatus** [comment]
可能可以行，但估计太卡了……如果想知道某个元素使用了哪些规则和代理，可以在那个元素上右键菜单中选择检查该元素使用的代理即可。这时候图标上会显示代理的颜色，悬停可查看匹配规则详情。
