### ISSUE TITLE
类似 gfwlist2pac 的 PAC 生成优化？

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#35]
大致原理是通过判断域名是否在集合中来实现优化。

参考： https://github.com/clowwindy/gfwlist2pac

要整合到本项目中，必须解决以下问题：

1. 原项目是 Python 实现，需要翻译成 JS.
2. 不严格符合 AutoProxy rule list 语义，比如AutoProxy里的关键字规则其实是应用到整个URL的，更像是一个子字符串规则而非域名规则。
3. 用集合的话规则全部都无顺序化了，可能会引发一些其他的问题。
4. 根据 2, 3 来看，只有速度快了是不行的……粗略看下来，gfwlist2pac生成的PAC，所匹配的是原来的一个子集……肯定会有人来抱怨以前能上的某些网站不能上了啊……
5. 好像也只对于 GFW List 这种特别长的有明显作用了，对于小的规则列表和自动切换，则没有明显优化。

所以……暂时来看的话，工作重点应该放在别的方面。

**Comment by humuhan** [comment]
偶然看见了这个gfwlist2pac，不知道作者现在什么态度啊？
本来以为效率影响不大，但是人家毕竟说快乐1900倍.......虽然作者你再三说这个SwichyOmega不是专门翻墙的工具，不过就现在这情况，大部分人用来干啥呢.....

**Comment by FelisCatus** [comment]
现在的主要问题仍然是原项目是Python实现，必须要转成JS才能集成到SwitchyOmega中。当然，这个是需要投入很多时间和精力的。我的意见仍然是希望把工作重点放在其他方面。

决策：若原项目被移植到JS上，我将做相应调研，决定是否集成或作为一个选项。否则根本就没法集成进来，讨论再多也没用。如果有空余时间（可能性很低），我会考虑自己进行移植。

----
P.S. 关于性能：
我毫不怀疑gfwlist2pac能比SO快1900倍，这都是有实验数据证明的。然而，需要注意的是，即使如此差距也在 1000 **us** 以内，对实际使用不会造成重大影响。（与DNS的几百 **ms** 和网页的几秒相比。）

此外，这样的脚本可能会加重生成负担，预加载负担和内存负担。
生成负担：生成PAC脚本的时间可能增加，影响第一次开启扩展或切换情景模式的速度。
编译和预加载负担：影响启动时和添加规则等修改后，访问前几个网站前的预加载时间。（之前的测试似乎印证这一点。）
内存负担：可能加重PAC脚本内存消耗。

而大部分用户反馈的性能问题，  **都集中在生成脚本和预加载的明显延迟上** ，很少有用户反馈加载完毕后访问网页性能差（当然也是因为这里的差别非常小）。所以，实际上的用户体验是更快还是更卡，还真说不定呢……

**Comment by FelisCatus** [comment]
以及：如果真的希望使用gfwlist2pac，不妨用那个项目生成好PAC然后作为PAC情景模式，直接贴进SO中使用。这个是现在就可以做到的事情，只不过没有集成很不方便罢了。这样操作后，可以实际体验下带来的性能变化如何。

**Comment by cicku** [comment]
优不优化并没有太大的提升，Chrome 本身作为一个臃肿的浏览器，低端设备根本跑不了（2G内存以下的终端都算）。所谓的1900倍也没什么参考价值，我真心认为 parse 性能不是问题，反而 OOM 是大问题。

这个问题倒是让我想 SO 的正则匹配性能问题，我没有做测试，但是我认为是否贪婪肯定有区别的，不知道有没有测试数据。

**Comment by FelisCatus** [comment]
@cicku SwitchyOmega 在代码中[使用一个非常简单的方式](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-pac/src/shexp_utils.coffee#L22)将通配符转换为正则表达式，大致就是`?`换成`.`，`*`换成`.*`，其他字符转义。如果有什么更好的优化建议欢迎提出。

我自己做过一个将通配符表达式编译为JS代码的函数，但实际测试下来也只能快2倍，但生成的PAC脚本要大几倍，所以我觉得很不值得，就没有在此项目中采用。

我觉得假如真的有什么优化，也必须是`gfwlist2pac`那种针对性很强的才行。如果按现在的思路把 AutoProxy 表达式转换为通配/正则最后再统一成正则，那么性能很难有质的提高。（关键字表达式除外，那个已经极限优化成`.indexOf`了。）

还是像我之前说过的一样，**执行时**真不是瓶颈。用预加载延迟换，不一定值得。

**Comment by FelisCatus** [comment]
我觉得这个还是偏离了本项目目标，所以关闭了吧……

类似这种需求应该做成插件的形式，交给有时间精力的其他开发者来维护。插件 API 正在筹划中，见 #44 。

**Comment by FelisCatus** [comment]
仔细研究了一下 [Chromium 项目 PAC 解析相关的代码](https://cs.chromium.org/chromium/src/net/proxy/proxy_resolver_v8.cc?rcl=5402cd7f4d105ca765798503fa0aecfe69035ca5&l=382)，发现里面有`--optimize_for_size`和`--noopt`两个 V8 选项。之前由于一些原因， `--noopt` 选项其实是失效的，但[很快就会实际生效](https://bugs.chromium.org/p/chromium/issues/detail?id=639217)。

这样一来 V8 引擎带来的大部分性能优化都会禁用掉，解析性能可能会受影响。之前 gfwlist2pac 声称的 1900 倍性能优势可能需要在加了这两个参数的前提下重新测算下……虽然感觉差距应该还是在 1000 us 这个量级左右。

如果不论绝对值如何，单纯谈效率最优化的话，这样对于 SwitchyOmega 生成的这种大而臃肿的函数更加不利， gfwlist2pac 这种充分利用数据结构的思路表现相对会更出色一些（当然，绝对意义上两者性能应该都降低了）。

（据说配置低的机器上 Crankshaft [都优化不动](https://bugs.chromium.org/p/chromium/issues/detail?id=639217#c16) SO 生成的 FindProxyForURL 函数呢，只会白白浪费内存。）

总之等 Chrome 57 之后我再来测试下，然后顺便看看用户实际反馈卡不卡，更新以后是不是比之前更卡。如果没了优化以后卡得不行，那么我再来回头看这个 Issue 。如果还是没什么区别，那么以上内容就只能停留在纯粹的技术探讨层面了。
