### ISSUE TITLE
我想知道你们克服的联系方式，然后购买你们得VIP，QQ835367357

### ISSUE THREAD

**Issue by ljss008** [FelisCatus/SwitchyOmega#352]
SwitchyOmega 2.3.1
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/31.0.1650.63 Safari/537.36

**Comment by ljss008** [comment]
Please！给个现在的网站连接也可以。

**Comment by Alphmega** [comment]
这个只是一个浏览器插件，并不是提供vpn服务的，楼主理解错误了

**Comment by ynyounuo** [comment]
我快笑出血了！！！哈哈哈哈！！本日最佳！！

**Comment by ljss008** [comment]
有的代理需要帐号密码的不是购买的么，网上免费的代理我也看到拉，不如买的好用啊

**Comment by ljss008** [comment]
http://www.proxy.com.ru/  像这个，，

**Comment by FelisCatus** [comment]
SwitchyOmega 是一个开源、免费、非商业的项目。我们的目标是为浏览器（如Chrome等）提供代理设置功能。项目只是提供一个设置的工具，并不含任何代理服务器地址，无任何收费服务。

* SwitchyOmega 不存在任何VIP服务。本项目提供的软件及其源代码均可免费下载安装，无须注册、无任何使用限制，不存在“高级版”或“收费版”。
  * 目前而言，此项目暂不接受任何形式捐款。（未来可能考虑接受捐款，届时将更新此处说明。）
  * 如有其他人声称可以提供收费版 SwitchyOmega 的服务，请勿轻信，谨防上当受骗。
* 本项目与任何代理服务器或VPN提供商不存在合作关系。如果有提供商推荐使用SwitchyOmega进行浏览器的配置或提供了相关教程等，均为提供商自身行为。
  * 任何人均可推广本项目或制作教程，无论免费或收费、商业与非商业，均无须经过本项目授权。
  * 然而，未经许可不得以本项目的名义进行其他服务或项目的推广。
  * SwitchyOmega 项目并无任何官方或官方推荐的代理服务器，或类似网络服务。
