### ISSUE TITLE
界面太慢了

### ISSUE THREAD

**Issue by ugksoft** [FelisCatus/SwitchyOmega#353]
2.0版本实在太慢了,不是一般的慢
我是i7 2700K,16G,SSD,Win7,64bit

点"圈圈",弹出下拉菜单,就要2秒种
打开配置界面,特别是规则界面,要好几秒,(我自定义规则只有几十条,外加一个autoproxy-gfwlist)

爬墙是关键,其它界面增强,花巧,意义不大,特别是纯靠HTML来撑门面,界面花了,脚本不比bin速度快不上去

右键菜单的项目,希望可以选择关掉,,真要看到某个地址爬墙,直接手工加列表,主页爬墙,还是子页爬墙,区别不是很大,反正数据溜达一圈再回国,反正是慢

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.39 Safari/537.36

**Comment by FelisCatus** [comment]
弹出菜单的加载效率问题见 #162 

右键菜单可以在选项界面设置关闭。

**Comment by ugksoft** [comment]
162中,没有提到如何加快速度,只是"完全不知道怎么办"

关于右键菜单,修改颜色等,这些,本来不会问你,完全是你把界面,改的太花,太慢,
让人用起来很拒绝,很烦躁,这样就算功能放在那里,可能也会变的看不见

**Comment by FelisCatus** [comment]
建议您去 #162 那里，按一下 "Subscribe" 按钮。这样一来，如果关于那个问题有任何更新（比如提出了优化方案，或者某个更新加快了速度），您就可以及时收到通知。

没有人会故意把界面做慢的，但 2.0 版本在一些技术上、架构上用了一些新的思路，所以可能会需要些时间来做优化。目前我确实对此问题没什么头绪，但这个问题总是需要解决的。一个人能做的事情毕竟是有限的，所以我可能会考虑去咨询这方面的专家，或者查阅些优化有关的文档。

**Comment by FelisCatus** [comment]
[v2.4.3 版本](https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.4.3)重制了一个新的弹出菜单实现，希望能快一点。目前此版本还在测试中，有兴趣的话可以直接点链接下载安装。有问题请及时回报。

**Comment by ugksoft** [comment]
en,最近是发现快了一些,不过,好像中间有几天(可能某个版本原因),老是丢配置数据,最近半月左右不丢数据了
是否考虑,把配置数据,定时同步到一个网上备份里,当然优先是google的, 不要同步去艳红那里去
如果有,最好是能够多台电脑,不冲突,比如pc机添加了几个,笔记本也更新从服务器下载新定义了
但笔记本改了其中一个域名的方式,或是添加了了个域名,这时pc机也能更新, 不会错乱

我看其它像adblock等,都没有做这个同步配置功能
要是没有好的空间可选择,或是插件不支持调用google空间之类的(我没写过chrome插件,不清楚是否可以), 那就当我没说

**Comment by FelisCatus** [comment]
丢配置的话检查下使用的垃圾清理软件之类的。之前有报告说 CCleaner 会删除扩展存储的数据，导致配置丢失。

配置同步功能已经做了，在导入/导出界面下可以用。两台设备都需要在 Chrome 中登录谷歌账号。

**Comment by ugksoft** [comment]
en,看到同步功能了,  丢配置,期间,我打死没有使用任何垃圾清理软件,如果使用我,我肯定会怀疑是清理原因,就不会和你说了

暂时没有什么问题,这个贴子,可以关贴了

**Comment by ugksoft** [comment]
附加问一下

" 此情景模式使用存储空间过多，因此无法进行同步。"原因?

我自定义需要代理的域名 246个(自动切换),代理服务器列表5个
外加https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt规则

**Comment by ugksoft** [comment]
点击同步后,提示"此情景模式使用存储空间过多，因此无法进行同步", 
重启chrome,发现还有丢配置问题,我的代理服务器全丢了, 但代理规则表还在
还好我有备份文件,重新导入,再次启动Google空间同步功能, 现在暂时没发现丢配置问题
估计你代码的逻辑错误,检查一下吧,小问题
