### ISSUE TITLE
图标换个颜色吧

### ISSUE THREAD

**Issue by ugksoft** [FelisCatus/SwitchyOmega#354]
图标换个吧

圈圈的颜色太不明显,子菜单的一些图标项目,色彩也太简单

你可以考虑使用深色调,不要太淡,红色,比绿蓝就要明显一些,

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.39 Safari/537.36

**Comment by FelisCatus** [comment]
图标的颜色完全取决于情景模式颜色，而情景模式颜色可以在选项里更改（点击情景模式左上角的颜色选取方块）。
