### ISSUE TITLE
现在经常会打开页面，很多图片出不来，亚马逊美国/英国特别严重，怎么操作都不行

### ISSUE THREAD

**Issue by babanhuang** [FelisCatus/SwitchyOmega#355]
SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器问题或网络问题，与本项目无关。如果图片等资源需要代理服务器才可加载，则可以使用自动检测未加载资源的功能，当图标上出现数字时点击打开菜单，然后点击未加载的资源选项查看。
