### ISSUE TITLE
打开google不是私密链接

### ISSUE THREAD

**Issue by Sakuyaaaaaa** [FelisCatus/SwitchyOmega#356]
SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器问题或网络问题，与本项目无关。

**Comment by Sakuyaaaaaa** [comment]
好的。。。总之3Q
