### ISSUE TITLE
功能建议，很重要

### ISSUE THREAD

**Issue by mapleshadow** [FelisCatus/SwitchyOmega#357]
建议增加一项很重要的功能：
当前网站用的是代理，还是直连，建议在插件上有个颜色区分，或者状态区分，这样用户好区别是否把该网站列入代理或者直连。
目前版本是没区分的。
------------------
另外还有，配置存储空间不能扩容了吗？
考虑出个付费版本，空间可以扩容也行呀

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by SyuTingSong** [comment]
auto switch的时候使用不同的情景模式时是颜色区分的呀

**Comment by mapleshadow** [comment]
不好意思刚发现有区分，鼠标移动到插件上不动，等一会就会显示当前网站走的是什么线路了，谢谢~~应用很棒，就是能扩展存储配置空间就好了，付费也行呵呵。

**Comment by FelisCatus** [comment]
配置存储空间确实是没有办法扩容了。
