### ISSUE TITLE
为什么有的网站不能选择情景模式？

### ISSUE THREAD

**Issue by zhenmeimingle** [FelisCatus/SwitchyOmega#358]
以前的版本每个网站都可以选择点击域名然后选择情景模式，从而加入自动切换列表中。但是现在有的网站行有的网站不行。比如这个http://www.secretchina.com/
谢谢！

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.122 Safari/537.36

**Comment by FelisCatus** [comment]
这个网站看上去并没有任何问题，而且在我这里确实是能添加规则。

如果是偶然情况，建议多试试看。如果可能的话，提供几个其他的网站（能添加的以及不能添加的）。
试试看常用的网站，如谷歌等。

**Comment by FelisCatus** [comment]
这边的情况如何了？

**Comment by hehh2001** [comment]
我这里也是一样的，这个网站是看中国，我很喜欢里面的看言文化版块，的确是打不开，加入自定义规则也不行

**Comment by FelisCatus** [comment]
@hehh2001 您的情况不是和楼主同样的问题，而更像是网络、代理服务器或者目标服务器问题。（注意楼主说的是有些网站中的弹出菜单无法添加规则，与实际的访问无关。）

**Comment by FelisCatus** [comment]
这边太长时间没有更新了，并且缺少可以定位问题的关键信息。暂时关闭 issue 了，如有更新请重新开启。
