### ISSUE TITLE
添加条件下面那个漏斗的配置是保存在哪的？

### ISSUE THREAD

**Issue by catscarlet** [FelisCatus/SwitchyOmega#360]
添加条件下面那个漏斗的配置是保存在哪的？配置了一些网站，本以为是快速添加 自动切换条件 的，结果发现不是。现在开了VPN想直通都不行，很多流量仍然被强制塞到代理里面，又找不到地方删除，很是痛苦。

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
临时规则适合于暂时修改某个网站所使用的规则，保存于内存中，重启后就会清空。
