### ISSUE TITLE
总是提示部分资源加载失败

### ISSUE THREAD

**Issue by k112358** [FelisCatus/SwitchyOmega#361]
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。
这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

您可以查看以下域名，并根据实际情况确定是否对其使用代理。

1 *.weibo.com
1 *.sina.com.cn
0 *.sinaimg.cn
对所有选中域名使用此情景模式：

<-----------------------实际上我选择了相应情景模式并添加条件后，仍然会出现------------------------------>

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by FelisCatus** [comment]
如上所述，这些问题可能是由您的网络、代理服务器或网站本身引起的。
（当然，也可能是因为配置了错误或不必要的代理服务器。）

如果您相信这个属于检测错误（应该比较少发生），那么请详细告知访问哪个网址、什么情况下会出现误报。

**Comment by matthew728960** [comment]
shadosocks-libev+锐速  开启 tcp-fast-open 后开始出现同样的问题，没开前不会出现。

**Comment by FelisCatus** [comment]
@matthew728960 很神奇的发现……然而您说的我一个都不懂，毕竟网络协议和代理服务器的实现细节是不在此项目涉及范围内的，而我也只是个写前端的。如果有任何疑问不妨咨询其他专家。
