### ISSUE TITLE
是否需要协助改进界面部分的设计？

### ISSUE THREAD

**Issue by pengyuwei** [FelisCatus/SwitchyOmega#363]
新的SwitchyOmega的界面感觉比原来的SwitchySharp复杂了很多，变得比过去难以理解了。
我不会前端开发没法参与开发过程，但是不知道你是否需要人来一起改进界面部分的设计？

**Comment by FelisCatus** [comment]
有什么界面或者用户体验的建议，可以直接在这里提出并进行讨论。（但不必急于做具体的设计稿或效果图，那个只会增加彼此的工作量，而收效并不是很好……）

**Comment by WhaleWatching** [comment]
我有帮助这个插件“去 BootStrap”的冲动：）
我会 Angular，倒是想把样式和交互重做一下。

**Comment by FelisCatus** [comment]
@WhaleWatching 最近 Bootstrap 确实是见得太多了，各种“撞脸”。不过我也觉得目前可能不是进行大改版的最佳时机。一方面用户刚刚适应新界面，再改还需要学习成本。另一方面刚从 SwitchySharp 升级来的用户就要连续经历两次大改动了，可能会非常困惑。

不过从做一个扩展的角度来说，功能才是最重要的。即使样式上有那么一点重复感，但只要能满足现在的需要，也是可以接受的。（国外用户对于 Bootstrap 见得更多，但从没有人反馈说要求换主题/样式。）倒是我觉得交互有很多可以改进的余地，这个不妨多探讨一下。

尤其是弹出菜单的交互，希望大家能多出点主意，在提高性能的同时优化体验，是极好的。会 Angular 的话，也应该更容易理解现在遇到的问题。

**Comment by FelisCatus** [comment]
暂时就这样吧……有什么具体的建议欢迎另外开 Issue 提。
