### ISSUE TITLE
关于虚情景的设置

### ISSUE THREAD

**Issue by humuhan** [FelisCatus/SwitchyOmega#364]
相信已经有人问过，很抱歉叨扰这样的问题。
这是一个纯粹翻墙相关的问题。
目前我使用goagent和shadowsocks翻墙，那么摆在眼前的问题是如何将完全相同的一套条件用于两条自动切换规则上。
![image](https://cloud.githubusercontent.com/assets/11542979/6765921/3d9b7de2-d02e-11e4-98e1-58c5fc78dff1.png)

原本我是编辑，记事本替换着弄的。

![image](https://cloud.githubusercontent.com/assets/11542979/6765939/8eadba2e-d02e-11e4-90e7-b625a9075f05.png)

说实话，这样其实也不是特别烦，但是有一天突然就想着不能再方便点吗？于是搜索了一会发现似乎虚拟情景可以用于此目的，但是这个情景在wiki并没有说明，而在扩展设置界面里的简单说明，我也度不太懂。经过一番尝试摸索，没有达到我想要达到的目的。

我也有搜索到这个项目的issue里面有人和作者谈到类似的问题，可惜没有找到，或者我还是没弄明白怎么设置。
————————————————————————————————

抱歉罗里吧嗦的说了一堆，简而言之：
是否有办法将同样的一套切换条件用于两套不同代理的自动切换的情景上去？

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
虚情景的文档没有做好，非常抱歉。

大致思路就是建立一个名称为“翻墙”的虚情景，然后所有自动切换规则都设置成“翻墙”即可。至于翻墙具体使用哪个情景模式，可以在选项里或者菜单里切换。

这样设置以后能快很多。然而这个概念还是很难理解，我也没有指望能在一两行简单的说明里教会别人怎么用。有没有办法把这件事情说明清楚？

或者有没有什么更好的建议呢？不必局限于现有的功能，最好能说说看理想中的设置是怎么样的。

**Comment by Dexcn** [comment]
楼主啊，虚情景模式 绝对能达到你的 "手动新添加的站点自动切换代理" 的目的
gfwlist黑名单里没有的站，你点击并手动添加的时候，选添加到 你建立的虚情景 不就得了。
这样你改变自动切换的默认的代理时（也就是改变虚情景对应的代理时），你添加的所有新站点对应的代理也都相应的改变了。我也天天添加新站点的。

感谢FelisCatus添加这个虚情景模式，帮了我们不少大忙，不用再写详细把这事说清楚了，懂的已经懂了，不过要写的话，我倒是知道最简单怎么写。
另外我还有其他的烦恼，会另发贴提出来。

**Comment by humuhan** [comment]
@FelisCatus 感谢您的回答，第二段话非常清晰明了。像这样的功能，相比描述性的解释，还是举例更为清楚。我认为就把这段话作为例子加入说明的话，大部分人应该就能明白了吧，就我个人来说目前功能已经足够完善了。
（不过。。“迁移到虚情景模式”这个是干嘛的我还是不清楚）

**Comment by Dexcn** [comment]
@humuhan 虚情景模式 就是用来避免你来回替换 +goagent 和 +ss的，有了虚情景，一套站点规则就对应n个代理，再也不用像你那样麻烦的来回替换了。从goagent换到ss的时候，所有你添加的站点全都自动从goagent换成了ss。多方便啊

**Comment by humuhan** [comment]
@Dexcn 恩我已经会了，现在切换很方便

**Comment by FelisCatus** [comment]
我还是先关掉这个好了……举例子虽然也挺好的，但涉及到具体的场景，没那么通用了。而且我也不希望在这里写翻墙什么的。
