### ISSUE TITLE
360 浏览器在页面无法访问时会跳转到自定义错误页面，导致无法添加规则

### ISSUE THREAD

**Issue by Dexcn** [FelisCatus/SwitchyOmega#365]
情形1：如果此网站能访问，但网站内某些元素的地址（比如页面内引用的图片的地址）被墙但不在gfwlist里，那么点SO按钮，点x个资源未加载，就看见添加到各种情景模式的选项了，不错，没问题。

情形2：如果此网站压根就无法访问（被墙且不在gfwlist里），360极速浏览器显示“您访问的网页出错了”，此时点SO按钮，点1个资源未加载，就“无法”看见添加到各种情景模式的选项了，在那个位置显示的按钮变成了“设置网络检测选项”。点了没用，得我自己手动添加。不行，有问题。

求解决问题。

另外建议：
如果是当前网页本身都无法加载的情况，建议直接在点一下按钮出来的第一层列表里就给出“添加当前站点到。。。”的选项，最好是直接添加到虚情景。
如果是当前网页能加载，网页里某些元素不能加载，按钮可以在第一层，也可以在第二层，要是想适应类似我这样的使用者，这整套列表的按钮其实都需要变一下。但不敢因为我们一小部分人的喜欢而惊动FelisCatus进行修改。只喜欢能修复那个“设置网络检测选项”的问题，让我能通过点击来添加当前网页到相应情景，就满足了。感谢白忙之中用心读贴！祝羊年洋洋得意，多赚人民币。

**Comment by FelisCatus** [comment]
真心觉得是 360 那个浏览器的问题……我这里如果网页不能加载，在出现“网页无法加载”的页面（或者过了几秒钟还没加载出来）的时候，确实是可以点资源未加载并添加规则的。

**Comment by FelisCatus** [comment]
说起来，按那个加号的菜单项试试看？那个也能添加，虽然没那么便捷。

**Comment by Dexcn** [comment]
@FelisCatus  感谢回复，而且感谢这么快就回复。
加号按钮，也就是添加条件的按钮，是在该网页能打开的前提下才出现（起码在360极速浏览器上是这样）

**Comment by Dexcn** [comment]
@FelisCatus 我可以举个例子，比如wowgirls.com这个站（只是为了举例方便而已，这种站我是从来不去访问，也从来不知道的），它就被墙且不在gfwlist里。我打开后，点按钮，就没加号按钮。（仍然是360极速浏览器，7.5版的）

**Comment by Dexcn** [comment]
@FelisCatus 好像基本解决了。是这样的：

如果该网页打开缓慢但还在连接，还在转圈，一片空白但还没显示“您的网络好像有问题”，那么点按钮就能出现 加号按钮，而且点未加载资源也一切正常。

如果该网页已经访问失败且访问结束，显示“您的网络好像有问题”，那么此时点按钮就没加号按钮了，点未加载资源会出现“设置网络检测选项”。

但是问题基本解决了，因为我点 “设置网络检测选项”后，虽然立刻跳转到SO的设置选项中的“通用”界面下，但实际上已经“半”生效了，如果此时点“自动切换”界面，会发现当前网站已经被写到“切换规则”里了。

为什么说是“半”生效呢？因为它在你点“设置网络检测选项”时压根没给你选择情景的选项，所以它被写到规则里时匹配的是你上一次选过的情景。你上一次选过goagent，它就给你写成 +goagent。 你上一次选过虚情景，它就给你写成+虚情景。但我最近一向是选择虚情景，所以对我来说没啥大困扰。只是别扭而已。

PS：我用的是360极速浏览器7.5版，下载链接：http://down.360safe.com/cse/360cse_7.5.3.318.exe
应该就是这个浏览器本身的问题了。再次感谢FelisCatus热心回帖，喜欢这一点点小bug能解决。

**Comment by FelisCatus** [comment]
那么请您下载 8.2 版（或者最新测试版）来安装，问题就应该能解决了。（之前有用户反映过类似情况，更新到测试版就解决了的。）

浏览器的问题当然只能在浏览器里解决……

至于点“设置网络检测选项”也能添加规则……感觉这个是比较严重的bug了。

**Comment by FelisCatus** [comment]
点“设置网络检测选项”也能添加规则的bug已经提交修复。不过因为发现问题出在哪里时，v2.3.11都已经发布了，所以估计要再等下一个版本了……请谅解。

至于其他的（尤其是360浏览器的）问题，我仍然一无所知。

**Comment by FelisCatus** [comment]
v2.3.12 已经修复。

**Comment by Dexcn** [comment]
老大，求你不要修复这个bug啊。你一恢复，我们用360极速浏览器（不管哪个版本，用过包括最新版的多个版本）的都不能正常使用Omega来添加不能访问的站点了。 以前有这个bug的时候，网站打不开时点“一个资源未加载”然后点“设置网络检测选项” 然后就能自动把当前网站添加到切换规则（虽然毫无提示，虽然添加到的是上次默认的规则{上次选的是虚情景，它就自动添加到虚情景}，但起码利用这个bug你能添加，现在则完全无法添加了）。

另外360极速浏览器在打不开的网页界面点“一个资源未加载”后不出现添加按钮，只出现“设置网络检测选项”的原因应该是360把打不开的网页进行了劫持。跳到了它设置好的访问错误页面，目的是在这个页面里做一些定制和植入一些热点新闻网址。那么这个劫持后跳到的页面是个错误反馈页面，所以Omega点了之后直接认为网络发生错误就只给了“设置网络检测选项”了。 装foxyproxy代理扩展来在360极速添加当前页面也一样，添加的不是当前页面，而是errorpage的页面了。

希望不要修复这个bug，就是靠这个bug活着的。或者希望能从根本上解决这个问题，彻底的完美的支持360极速浏览器。试过foxyproxy等多个代理扩展都不如Omega，有一个叫everproxy的是根据红杏改的遇到不能访问的网址就提示让自动添加比较方便，可惜好久也不更新了不能用了。目前能用的，唯一比Omega方便，而且方便的比较明显的，是autoproxy的黑仪大螃蟹修改版。不是另一个修改版，著名的有两个修改版，黑仪大螃蟹的应该目前是修改的最好的。但可惜火狐打开网页的速度和流畅度都不如谷歌内核的浏览器高，否则就为了那一个扩展我也绝对离不开火狐的。

**Comment by FelisCatus** [comment]
> 另外360极速浏览器在打不开的网页界面点“一个资源未加载”后不出现添加按钮，只出现“设置网络检测选项”的原因应该是360把打不开的网页进行了劫持。跳到了它设置好的访问错误页面，目的是在这个页面里做一些定制和植入一些热点新闻网址。那么这个劫持后跳到的页面是个错误反馈页面，所以Omega点了之后直接认为网络发生错误就只给了“设置网络检测选项”了。 装foxyproxy代理扩展来在360极速添加当前页面也一样，添加的不是当前页面，而是errorpage的页面了。

这个你让我打算怎么办……感觉正常的方式是比较难弄了，也许要折腾比较久。

> 但起码利用这个bug你能添加，现在则完全无法添加了
抱歉，可能这里确实没考虑到这么多，而且说实话bug挺严重的，并不只是影响360……请给我一点时间，容我想个其他办法。

**Comment by Dexcn** [comment]
是了，不着急，慢慢折腾研究就好，反正也是非盈利项目，应该是你在工作之余在维护和更新的。
其实现在也不是不能添加啊，手动把网址添加到自动切换规则里就好，就是没以前那么方便了，现在人都特别懒了。
 
       另外代理扩展的综合成绩SwitchyOmega肯定是排第一的。就是添加无法访问的新网址到黑名单，还有添加能访问的网址里的被屏蔽的元素到黑名单，这两个功能目前感觉没autoproxy黑仪大螃蟹那个修改版本方便。其他功能是比它胜出的。

       还有我也不是故意要用360极速浏览器，关键是360如果有一个产品是做的不错的话，那么这个产品就是360极速浏览器了，确实比其他谷歌内核修改版的强不少。目前还真离不开，而且用的人非常多啊。

**Comment by FelisCatus** [comment]
为了彻底解决这个问题，我需要装一个Windows操作系统，然后再装一个360极速浏览器，最后还要用360的开发者工具以及Windows开发环境调试半天……结果可能会发现解决方案特别麻烦或者根本不存在。所以不是我说，而是想要支持那些浏览器，要付出太多太多。

之前的SwitchySharp，我就选择了不花精力去支持360之类的，结果也证明我的选择是正确的。然而现在的360极速浏览器更新了很多，兼容性也好了不少。（至少除了少数几个功能以外，都直接支持了，不需要另外修改代码和调试。）再加上很多人对于这个项目抱有很多期待，所以我也只能说：我尽力而为吧。

但至少最近而言，我是真的真的没精力来折腾了。既然不急，那么我准备两个星期以后再开始装Windows系统好了。

**Comment by FelisCatus** [comment]
话说能不能请你们帮我一个忙？在360浏览器跳转到错误页面，并且已经无法添加规则时，在浏览器地址栏里输入`javascript:alert(location.href)`★并回车，看看弹出的地址究竟是什么？如果可以的话截个图？

★特别注意：直接复制粘贴时，`javascript:`部分可能会粘贴不进去，此时需要手动输入`javascript:`（注意冒号）再粘贴后面的内容。

**Comment by ctexlive** [comment]
360极速上对这个js脚本没有任何反应。看来是360极速的问题了。。。

**Comment by ctexlive** [comment]
知道了，需要在ctrl+shift+j chorme自带的开发人员工具，然后输入命令javascript:alert(location.href)
弹出如下窗口
![3601](https://cloud.githubusercontent.com/assets/8100859/7807560/2e211164-03bf-11e5-9860-72f50a1e395d.png)

**Comment by FelisCatus** [comment]
@ctexlive 谢谢啦，我马上看看能否直接解决这个问题。

**Comment by FelisCatus** [comment]
修复了一个比较严重的bug，这个bug曾经导致明明有未加载资源，也可以查看，但不能添加到切换模式中的问题。这个问题对于所有浏览器都存在。所以我之前说了，影响的不只是360浏览器。可惜这个问题我发现得太晚了，可能已经给太多用户造成困扰了。（感谢 @Dexcn 耐心等待我这边发现核心问题，而非催促我发布临时修补。）

此外，特殊处理了 360 浏览器的神奇错误页面（用`lasturl`参数作为该页面URL）。现在可以像普通的页面一样添加规则、临时规则、使用未加载资源等功能了。（感谢 @ctexlive 提供的技术帮助。）

此次更新还未发布，预计周末会有一次更新修复这个问题。届时我也会在 Twitter 上说明下更新情况和兼容性。

**Comment by FelisCatus** [comment]
v2.3.14 已经修复。
