### ISSUE TITLE
自动切换模式比单纯用pac占资源

### ISSUE THREAD

**Issue by Dexcn** [FelisCatus/SwitchyOmega#366]
发现似乎还是pac模式占内存少，比自动切换占用资源少。
1. 能不能设置可以让一个pac供不同代理使用？切换时自动就把pac里的'PROXY *:8087;DIRECT' 里的端口给换了。（Socks5的就自动改成类似'SOCKS5 *:1080;DIRECT']）
我曾经是拿一个pac不断改（往里添加新站点），然后把这个改过的pac粘贴给每一个pac模式的代理。。
2. 能不能一键添加当前站点到这个pac里。既然pac文件的文字内容都能在SO里显示了，添加进去应该不难吧。

**Comment by FelisCatus** [comment]
自动切换占用资源相对多一些，是因为一些缓存、界面相关的处理（比如图标改变颜色）等。而这些功能都是PAC没有的。把PAC当做自动切换用，不是设计的目标。本意这个就是给有PAC脚本的人用的。
所以，PAC还是少做点功能吧……

以及，解析文字或者脚本什么的还是太难做。显示脚本和编辑脚本是完全的两回事。人能一眼就看出应该在哪里增加语句等，但代码不能。更何况有些写的不好的脚本甚至连人类都看不懂……
