### ISSUE TITLE
"[Direct]" Menu item shows briefly then collapses.

### ISSUE THREAD

**Issue by imagegrid** [FelisCatus/SwitchyOmega#367]
"[Direct]" Menu item shows briefly then collapses.

![screen shot 2015-03-23 at 6 47 46 pm](https://cloud.githubusercontent.com/assets/5759599/6791384/591ac270-d18d-11e4-916e-b600b60230d5.png)

SwitchyOmega 2.3.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
This is an known issue with Chrome on OS X, where the popup menu is incorrectly positioned. 
This has nothing to do with this project and cannot be fixed in this project. Please report the issue to the chromium project.
