### ISSUE TITLE
根据用户配置的自动切换规则自动生成 PAC 文件

### ISSUE THREAD

**Issue by glacjay** [FelisCatus/SwitchyOmega#368]
好处：可供同一个系统中的其他程序使用。

为什么要实现在该扩展中？
因为用户通过该扩展可以方便的管理自动切换规则，且在浏览器环境中可以方便的测试网站的可达性。

生成时机：每当用户修改了自动切换规则之后，另加一个自动（比如每小时）或手动（按钮）重新生成的机制。

**Comment by FelisCatus** [comment]
在某个情景模式（如自动切换）的右上角有“导出PAC”的按钮，按一下就能生成了。

由于扩展限制，无法写入磁盘文件，只能提供文件下载，且下载的文件不会覆盖之前的版本。因此无法实现修改后生成和每小时生成，只能手动下载另存。
