### ISSUE TITLE
你好我用的是猎豹的浏览器，我想让这个应用也显示在猎豹浏览器的应用中心里

### ISSUE THREAD

**Issue by yange** [FelisCatus/SwitchyOmega#369]
你好我用的是猎豹的浏览器，我想让这个应用也显示在猎豹浏览器的应用中心里，所以我在猎豹浏览器的提交了应用添加到应用页面的申请，对方人员告诉我说没有扩展包？是什么意思，没有扩展包就不能添加吗？

**Comment by FelisCatus** [comment]
扩展包可以在这里下载： https://github.com/FelisCatus/SwitchyOmega/releases

即使他们不愿意给添加，您也可以自己下载扩展包然后安装。

**Comment by yange** [comment]
对，我今天又试了一下，不用他们应用中心也是可以安装的。就是进到 我的应用页面，然后把下载的CRX扔进去就可以了。
