### ISSUE TITLE
Recovering from file is not work

### ISSUE THREAD

**Issue by mnotw** [FelisCatus/SwitchyOmega#373]
Every time I tried to recover the configuration from .bak file, it just simplely opened another new tab. I don't know which part I was doing wrong, please help me.

**Comment by FelisCatus** [comment]
Any screenshots please? You can also upload the backup file in question to https://gist.github.com/ and paste the link here.

Selecting "Error log" from the icon popup menu can also show you more information about the error. Please check it AFTER you encounter the problem.

P.S. You may also use Chinese here if you like. Just make your self clear.

**Comment by FelisCatus** [comment]
Any updates?

**Comment by mnotw** [comment]
谢谢，这个问题已经解决了
