### ISSUE TITLE
开发者模式安装失败

### ISSUE THREAD

**Issue by raymondgit** [FelisCatus/SwitchyOmega#374]
1）使用SS全局代理可以访问Chrome网上应用店，也可以搜索到Swichy Omega，但是点击「添加」后会提示「网络错误」
2）打开Chrome的开发者模式，直接拖动下载的crx文件到扩展管理页面，安装成功，但是无法启用。Chrome的相关页面说是由于安全原因，禁止了从第三方安装扩展
3）根据百度经验，把crx文件解压，然后在开发者模式下「载入正在开发的扩展程序」，提示「加载扩展程序时出错：无法加载以下来源的扩展程序： ~\Downloads\swichyOmega
Cannot load extension with file or directory name `_metadata`. Filenames starting with `_` are reserved for use by the system.」

**Comment by FelisCatus** [comment]
1 => Chrome Web Store 在某地区访问不稳定，可能需要用代理才能安装。
2 => 由于Chrome限制，确实会出现这种情况。我也没有办法，请理解。
3 => 如果真的要解压安装，请把`_metadata`文件夹删掉，应该就可以加载了
