### ISSUE TITLE
Chrome 中使用 Google 搜索偶尔会显示「未收到数据」

### ISSUE THREAD

**Issue by Fadeoc** [FelisCatus/SwitchyOmega#375]
如题，在显示此页面前通常会很慢，在显示此页面后会自动跳转到 Proxy 的模式，添加了规则也无效。

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36

**Comment by FelisCatus** [comment]
这是网络问题吧……

**Comment by Fadeoc** [comment]
我也不知道:) 也许吧。

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
