### ISSUE TITLE
下拉选项出现的(外部情景模式)是干嘛用的？

### ISSUE THREAD

**Issue by Cumin** [FelisCatus/SwitchyOmega#376]
不太理解这个外部情景模式，运用在什么地方？

SwitchyOmega 2.3.9
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
这个是读取了在其他扩展中配置的代理设置，可以导入到SwitchyOmega中使用。
不知道是用来做什么的话，可以不使用。
