### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by nageshkotthuri** [FelisCatus/SwitchyOmega#378]
SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
?

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
