### ISSUE TITLE
chrome浏览器更新不能自己走代理吗？

### ISSUE THREAD

**Issue by fengrg** [FelisCatus/SwitchyOmega#379]
SwitchyOmega的自动切换很好用，但是我的chrome很久不能更新了。点chrome关于里可以看到检查更新都是失败的。请添加让浏览器本身可以通过代理出去。

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by FelisCatus** [comment]
Chrome 的更新我不是很了解，因为我用的Linux没有自动更新功能。

不过，似乎那个更新功能是一个插件，其代理设置不遵从Chrome设置，而是使用系统的代理设置。请尝试手动到系统设置里改下，然后点更新试试。
