### ISSUE TITLE
mac chrome 下的插件 直接连接这里怎么一直有一个框框 我截图了

### ISSUE THREAD

**Issue by bugyak** [FelisCatus/SwitchyOmega#380]
![image](https://cloud.githubusercontent.com/assets/7711294/6958042/6bf342d4-d938-11e4-8276-581cc9623d54.png)

强迫症实在受不了！
windows下就没！

SwitchyOmega 2.3.9
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2352.0 Safari/537.36

**Comment by FelisCatus** [comment]
感觉是 OS X 下 Chrome 对于焦点的绘制问题……这个样式扩展是不能控制的，唯一的办法就是不要把焦点放在上面，但……
