### ISSUE TITLE
Vivaldi browser support

### ISSUE THREAD

**Issue by sysfu** [FelisCatus/SwitchyOmega#381]
The new but rapidly developing Vivaldi browser does not fully support extensions yet however it is possible to to install ProxySwitchy Omega and configure it via: vivaldi://extensions

If you have some time maybe you want to experiment with support for Vivaldi

**Comment by FelisCatus** [comment]
For your reference, Vivaldi is now mostly compatible with Chromium Extensions. SwitchyOmega can be installed correctly in Vivaldi, but the proxy settings won't work for now.

We have to wait for Vivaldi to implement the `chrome.proxy` APIs correctly for that. There's nothing I can do on SwitchyOmega's side now.

**Comment by yayayau** [comment]
thank you, i'll write it to vivaldi's support

**Comment by celeron533** [comment]
Or any genius port this Chrome version to Vivaldi one? :smiley:

**Comment by FelisCatus** [comment]
According to comments on the Chrome Web Store, SwitchyOmega now runs out of the box on Vivaldi.

**Comment by aryadovoy** [comment]
Hello. Extension does not work properly in Vivaldi with blocked sites. It tried this in Firefox and all is ok.
I've created [topic](https://forum.vivaldi.net/topic/35568/proxy-extensions-don-t-work-exactly), but they passed me to you.
