### ISSUE TITLE
未捕获的异常？

### ISSUE THREAD

**Issue by ayanamist** [FelisCatus/SwitchyOmega#382]
发现有未捕获的异常？
![2015-04-04_132453](https://cloud.githubusercontent.com/assets/406779/6991556/bad15e44-dace-11e4-81a7-627d6eb30abb.png)

![2015-04-04_132537](https://cloud.githubusercontent.com/assets/406779/6991558/c8661400-dace-11e4-9701-58d87762e236.png)

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
好像 tab 先激活再关掉，就会有这种情况……报错并非异常，不影响正常使用。
等下去修下，检查下 `runtime.lastError` 就好。

**Comment by FelisCatus** [comment]
v2.3.10 中已经修复。
