### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by ayanamist** [FelisCatus/SwitchyOmega#383]
似乎有内存泄漏，未监听的事件导致事件消息堆积？

![2015-04-04_132953](https://cloud.githubusercontent.com/assets/406779/6991563/e7543fae-dace-11e4-99b6-e404f2d47a95.png)

![2015-04-04_132835](https://cloud.githubusercontent.com/assets/406779/6991561/e007bb18-dace-11e4-8a4e-bf6e2a185207.png)

![2015-04-04_132912](https://cloud.githubusercontent.com/assets/406779/6991562/e448507a-dace-11e4-8e01-3754d540fbfa.png)

**Comment by ayanamist** [comment]
heap dump
https://dl.dropboxusercontent.com/u/12513386/Heap-20150404T132712.7z

**Comment by FelisCatus** [comment]
感谢，有 heap dump 应该能找出原因了……

**Comment by FelisCatus** [comment]
已经可以确认为 `extensions::event_bindings` 中的`allAttachedEvents`数组内存泄漏。

深层原因：Port对象被弃用前，未取消注册事件监听回调。

这里写代码的时候主观认定如果对象不存在，则事件回调就会自动被回收了。但实际上，对于 Chrome Extension API 自己实现的代码而言则不然，存在全局的`allAttachedEvents`数组，该数组中存放了事件，构成强引用，无法被垃圾回收。

感觉这次挺严重的，但如果不开着 SO 几小时并连续观察内存占用，还真的看不出……这里要感谢 @ayanamist 的报告。

**Comment by FelisCatus** [comment]
嗯……那这样的话，顺便检查下所有的 `.addListener` 调用吧，或许其他地方也有这种问题。

**Comment by FelisCatus** [comment]
v2.3.10 已经紧急修复。
