### ISSUE TITLE
为什么不做个Firefox火狐浏览器的版本的插件？

### ISSUE THREAD

**Issue by pendave** [FelisCatus/SwitchyOmega#384]
为什么不做个Firefox火狐浏览器的版本的插件？

不喜欢Firefox火狐浏览器的Autoproxy 还有 FoxyProxy  都不如 Switchy Omega好用啊！！！

SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by FelisCatus** [comment]
有关讨论和计划，请参考 #102 。
