### ISSUE TITLE
http://3rab-nar.com/

### ISSUE THREAD

**Issue by rostom9** [FelisCatus/SwitchyOmega#387]
SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by rostom9** [comment]
غاحدخننتاغلا

**Comment by FelisCatus** [comment]
Sorry, I can't understand you. Please write your issue in English or use Google Translate.
