### ISSUE TITLE
切换规则同步问题

### ISSUE THREAD

**Issue by lvyilin** [FelisCatus/SwitchyOmega#388]
两个设备都开启了同步，都是似乎无法同步成功，很希望能实现这个牛逼的功能

SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.101 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查是否在Chrome上登录了谷歌账户。由于谷歌服务在某地区不稳定，可能无法正常与同步服务器交互，请试试看全局代理模式。

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
