### ISSUE TITLE
Facebook上的Ultimate Bridge经常掉线，很难加载

### ISSUE THREAD

**Issue by yxtptyx** [FelisCatus/SwitchyOmega#389]
Facebook上的Ultimate Bridge经常掉线，很难加载

SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by FelisCatus** [comment]
网络问题或者代理服务器问题，与本项目无关。
