### ISSUE TITLE
关于导出的PAC文件使用问题

### ISSUE THREAD

**Issue by DreamSeason** [FelisCatus/SwitchyOmega#391]
OSX 10.10.3下，Chrome下正常使用拓展。并将AutoProxy的profile导出PAC。
在系统设置下配置了自动代理，使用的是上面导出的PAC文件。但是无法正确达到想要的代理，原来使用switchysharp的时候同样的方法可正常使用。故有疑问是否导出的PAC文件Safari文件无法正确阅读。对比了一下omega和sharp导出的PAC，发生了很大的变化。

**Comment by iqiancheng** [comment]
sharp导出的PAC可以直接导入给omega用。

**Comment by DreamSeason** [comment]
恩。我想你可能没有理解我的意思。我现在omega是使用的之前sharp的备份文件升级上来的。
只是从sharp跳到omega之后，我个人又添加了一下规则。然后现在希望使用这些规则来帮助Safari实现自动代理的功能，这就需要使用omega的PAC。但是Safari不能正确使用omega所导出的PAC

**Comment by FelisCatus** [comment]
请上传新导出的PAC文件，以便分析问题。（您可以修改其中具体的规则、网址或代理服务器地址等，以保护您的隐私。）

omega 使用了新的一种思路来生成PAC，但语法上不应该造成任何问题。此情况比较可能是bug，最好还是让我看一下吧。

**Comment by DreamSeason** [comment]
恩。百度云共享没啥问题吧。这里似乎只能上传图片文件。
链接: http://pan.baidu.com/s/1sjmcUqp 密码: 8mf2

**Comment by FelisCatus** [comment]
请告知试图访问的网址（完整URL）、应该使用哪个代理服务器，和实际上使用了哪个代理服务器。

**Comment by DreamSeason** [comment]
试图访问www.youtube.com
应该使用socks5 127.0.0.1：1080
实际上不知道使用了什么，就是显示无效打不开。 OSX下显示Apache Default

**Comment by FelisCatus** [comment]
如果页面是空白的，能查看页面源代码吗？这样就知道是页面加载不出还是资源加载不出了。

**Comment by DreamSeason** [comment]
我手动指定了一下https，会出现下面的源码。就是显示Safari连接不到。

**Comment by FelisCatus** [comment]
能否告知PAC的系统设置情况？（可以截图）

P.S. 根据谷歌结果， OS X 似乎不允许使用本地 PAC 文件，必须使用本机服务器来提供PAC地址。[这里的苹果官方说明可供参考](https://support.apple.com/en-us/HT203654)。和这个有关吗？

**Comment by DreamSeason** [comment]
恩。我是这样的。OSX下面开启了Apache，命令式sudo apachectl start
开启了之后我是可以正常访问127.0.0.1或者localhost的。
之后会在/Library/Webservers/Documents/下面放入导出的PAC，在系统设置里面填入下面这个地址。
之前都是这么做的，都是OK的，不过那时候还是switchysharp年代导出的。
![qq20150410-1 2x](https://cloud.githubusercontent.com/assets/3054858/7083327/e1db4784-df92-11e4-86a4-9f583aa9c675.png)

**Comment by FelisCatus** [comment]
好的，我明白了。这里再麻烦您做一个简单的测试，在SS情景模式下，点击导出PAC文件，并且设置使用那个PAC文件。这样导出的PAC文件很短，而且应该无论任何情况下，都使用同一个SS代理。可以用这个试试看，就知道是不是PAC格式有问题了。

**Comment by DreamSeason** [comment]
您好，我按照您说的。只导出了SS的PAC，在Safari下测试发现还是不能够正确使用。这里补充一点我所看到的，似乎Safari不支持SOCKS5这样的类型。所以有很多都是返回的代理值有两个，一个是SOCKS5，一个是SOCKS，后面都是接同一个代理地址和端口。（当然，这个我测试过了，即使添加了还是不行）

**Comment by FelisCatus** [comment]
这两天专门弄了个 OS X 来，测试了很久。以下是结论：

### PAC缓存

PAC文件是有缓存的。这个缓存似乎是在 OS X 系统内部，即使重启 Safari 也没用。但是只要在设置里更改了PAC文件的URL，那么在Safari 中刷新就能立即生效。这个调了很久，才发现规律。

因此，每次改动PAC文件后，应该改下URL。比如`http://127.0.0.1/test.pac`后面可以加上些参数，变成`http://127.0.0.1/test.pac?v=1`，然后每次改了文件就到系统设置里改成`v=2`、`v=3`，依此类推。

之后进行实验的时候，请务必注意这一点。

### SOCKS5

经过实验表明，正如 @DreamSeason 所言， SOCKS5代理必须写成`SOCKS 127.0.0.0:7070`才可使用。为了兼容其他浏览器，可以写成`"SOCKS5 127.0.0.1:7070; SOCKS 127.0.0.1:7070"`这种格式。

我用SwitchyOmega导出的单独的SS代理PAC做了实验，发现只需要更改此一处，即可正常使用。也就是说，除了`SOCKS5`的写法以外，新版PAC完全兼容Safari，可以放心使用。

### 代理无效

这个也算是一个比较坑的地方。

* 当PAC语法不正确的时候，Safari（或者 OS X）会无视此PAC文件，直接使用直接连接，不会报任何错误。此时必须按上述方法改URL才能再次尝试PAC文件。
* 当PAC返回的结果为代理服务器，而该代理服务器无法访问时（比如忘记开SS），这个代理服务器地址会被标记为“无效”。此时浏览器自动变为直接连接，并不会报错说代理服务器无法访问。这个可能需要浏览器重启才会重置。

之前  @DreamSeason 的情况，访问一个墙外的地址，实际上是使用直接访问，所以提示服务器未响应。此错误和PAC或代理服务器无关，但可能是由于PAC或代理其中之一出了问题。

### 结论

* SwitchyOmega 导出的PAC格式并没有大问题，但暂时而言，需要手动替换`SOCKS5`为`SOCKS`方可在Safari中使用。
* 之后生成 PAC 时可以把 SOCKS5 的返回值改为`"SOCKS5 127.0.0.1:7070; SOCKS 127.0.0.1:7070"`这样的兼容格式。相信这个不会太复杂，下个版本应该可以做出来。
* 遇到代理服务器没有正常工作的情况，可能是因为缓存或者标记代理无效等原因，自动变为直接连接。此时检查PAC是否忘记改了，并检查代理服务器是否开启。  **之后切记按上述说明去改下URL，再重启下Safari，再重试。**

**Comment by DreamSeason** [comment]
感谢你的测试。我把你上面的一段读了几遍，并且进行了好多次尝试。但是不理想的是还是没有能够成功，于是想询问一下，你应该也是用apachectl start开启本地服务器然后直接使用127.0.0.1/xxx.pac的代理地址吧？

**Comment by FelisCatus** [comment]
@DreamSeason 是的。

**Comment by FelisCatus** [comment]
我先提交了点代码，实现了之前所说的`"SOCKS5 127.0.0.1:7070; SOCKS 127.0.0.1:7070"`兼容格式。这个修复将会随着下个版本（预计v2.3.11）发布，在此之前请继续手动修改PAC文件。

如果遇到什么问题可以再提，不过我这里测试Safari也不是很方便。况且我这里行，您那边不行的话就弄不清楚了……

**Comment by DreamSeason** [comment]
恩。麻烦您了，最后我把导出的PAC文件直接挂到VPS上了。自动代理那里就不用本地服务器而改用远端的了。是成功的。一番折腾之后，证明了omega除了socks那里需要针对Safari做一些修改之外，别的都是可行的。辛苦了。在这里再次感谢您一直以来的付出，衷心的谢谢。
PS:您还记得您测试机器是10.10.2还是.3 么？如果方便，麻烦告知一下

**Comment by FelisCatus** [comment]
@DreamSeason 按理来说本地服务器和远程服务器应该是一样的。如果不知道如何避免缓存，可以给文件改个名字（当然设置那边也要改）。至于测试的系统版本，对不起我没注意那个……

**Comment by FelisCatus** [comment]
SOCKS5相关兼容代码已经提交，正在等待谷歌应用商店审核通过（预计1小时以内）。

**Comment by FelisCatus** [comment]
v2.3.11 已经添加 Safari 中的 SOCKS5 支持。

**Comment by ylivan09** [comment]
您好，请教怎样把本地的 PAC 文件挂到 VPS 上？

**Comment by celeron533** [comment]
>请教怎样把本地的 PAC 文件挂到 VPS 上

那个人自己在vps上架设了代理，和SwitchyOmega无关
