### ISSUE TITLE
带有 0.0.0.0/0 的 bypass 规则的 Proxy Profile，将其作为 Switch Profile 的 Default 选项后，无法正常访问代理

### ISSUE THREAD

**Issue by AnyOfYou** [FelisCatus/SwitchyOmega#392]

**Comment by AnyOfYou** [comment]
建立 0.0.0.0/0 的 bypass 规则 的 Proxy Profile，想让所有ip地址的网站不走代理，在 SwitchyOmega 单独指定为此 Proxy Profile 时工作正常，但如果将其放到 Switch Profile 的 Default 选项就会出现异常。Switch Profile 中就只有 Default 一条规则也会这样。如果删除 Proxy Profile 中的 0.0.0.0/0 的 bypass 规则就会正常。

**Comment by FelisCatus** [comment]
难道是PAC不然用`isInNet(host,"0.0.0.0","0.0.0.0")`?等我自己试试看再说。

**Comment by FelisCatus** [comment]
经过测试，这里是有不一致的地方。IP的Bypass规则单独使用时Chrome只会匹配IP地址，但在PAC中使用`isInNet`时浏览器会将`host`的域名解析为IP地址再判断是否匹配……

从效率上来说，只匹配IP地址会更好一些。唯一的问题就是，如果这里改了，会不会影响之前这样使用的用户呢？

**Comment by changcen168** [comment]
Changcen168@gmail.com
2015年4月14日 9:05 PM于 "FelisCatus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
@changcen168 ?

**Comment by FelisCatus** [comment]
修复已经提交，正在等待谷歌应用商店审核通过（预计1小时以内）。

**Comment by FelisCatus** [comment]
v2.3.11 已经修复。
