### ISSUE TITLE
为什么一个域名下的资源不是按这个域名的规则处理?

### ISSUE THREAD

**Issue by Yourbee** [FelisCatus/SwitchyOmega#393]
，一个域名下的资源不能使用域名的规则，就是比如flickr是proxy模式，但是里面的照片链接到的资源却还要自己处理一遍，

SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by FelisCatus** [comment]
由于PAC脚本限制，无法得知标签页、请求的资源属于哪个页面等信息，所以无法实现这种模式。

现在的实际情况是，无论页面还是资源都是按URL分别匹配。对于一个页面中的所有资源，如果遇到加载错误等问题，图标上会有数字提示，此时在菜单中可批量添加规则，无须手动逐一设置。
