### ISSUE TITLE
自动切换貌似不能生效？

### ISSUE THREAD

**Issue by Chigogo** [FelisCatus/SwitchyOmega#394]
Goagent自带的PAC 文件解决了大多数的地址切换规则，
而我自己也有一些个人的网址需要添加，所以我的方法是建立两个情景模式：
1，GoAgent模式，直接使用GoAgent 代理，
2，GoAgent PAC 模式，

我使用自动模式，里面这样设置：
自动模式的默认情景模式是GoAgent PAC 模式，
有些规则PAC 里面没有，我手动把这部分网址设置成使用GoAgent模式。

问题是：
这样设置以后，手动设置的网址无效，使用自动模式就如同使用GoAgent PAC 模式。

SwitchyOmega 2.3.10
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.104 Safari/537.36

**Comment by FelisCatus** [comment]
1. 请确定在菜单中选中了自动切换模式。
2. 对于自动切换的规则设置，请提供一张截图以供分析问题。

**Comment by Chigogo** [comment]
好的，截图是这样摆放吗？
![截图](http://649699255-outstorage.stor.sinaapp.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-04-14%2022.08.42.png "截图")

**Comment by FelisCatus** [comment]
在第一个规则中，条件类型为“域名通配符”，因此只需要输入域名部分（如`*.v2ex.com`），不需要`http://`等。注意截图中框为黄色，就是提醒此规则可能存在问题。

此外，请检查下方的规则列表中是否有冲突的规则。

**Comment by Chigogo** [comment]
*.v2ex.com有用的。

不过我当时想的是http代理，https 不用代理。感觉能做这些工具的人都好厉害，界面、设计都很用心。赞！阁下目前高就何职？

**Comment by Chigogo** [comment]
有一点：不知道这两个按钮的差别。（猜测一个是暂时性的规则，一个是永久的规则）
![NONE](http://649699255-outstorage.stor.sinaapp.com/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202015-04-14%2022.26.00%E5%89%AF%E6%9C%AC.png "NONE")

**Comment by FelisCatus** [comment]
下面那个是临时规则。

P.S. SwitchyOmega 并不属于任何一个公司，是属于整个社区的。不只是我一个人在战斗，其他开发者和翻译者都做了很多贡献。而这一切都是免费开源的:-) 我们的目标就是做一个好用的代理设置工具。当然，您也可以参与我们的开发，或者通过提交意见和建议等，协助 SwitchyOmega 做得更好。

**Comment by Chigogo** [comment]
好的！等我学会了Git ，定当肯定竭尽所能！

有你的世界，真好！
