### ISSUE TITLE
Sorting Proxy Selection

### ISSUE THREAD

**Issue by 1h8fulkat** [FelisCatus/SwitchyOmega#395]
It looks like the sort order of the primary selection is All Proxies in alphabetical order then All PACs in alphabetical order.  However, when you look at the site specific selection list, it's all connections in alphabetical order.  Can you please change the primary list to match the site specific list OR (as a feature request) allow me to modify the list order as I could in Proxy SwitchySharp?

**Comment by FelisCatus** [comment]
Are you requesting all the list of profiles to be in alphabetical order? Or ordered by type? Or manual profile sorting?

For your reference, lists to change would include:
* The left navigation menu on options page
* Several dropdown profile selections on options page
* Draggable quick switch list on options page
* The popup menu of the browser action icon
* Dropdowns in the popup menu
* (and maybe more...)

It's generally a good idea to unify the profile order in these places. However, such change must be done carefully in consideration of performance.

**Comment by 1h8fulkat** [comment]
Right now the drop down for the domain in the popup menu sorts all profiles alphabetically.  

![capture](https://cloud.githubusercontent.com/assets/11942449/7166737/a12e9e5e-e37d-11e4-8e16-8cd7b1b43984.JPG)

But the popup list itself sorts the profiles by type THEN by alphabetical order.  

![capture1](https://cloud.githubusercontent.com/assets/11942449/7166748/b13ba29c-e37d-11e4-9719-e054d9121d99.JPG)

The type THEN alphabetical sort style carries through the rest of the extension.

My recommendation would be to change the rest of the lists to just alphabetical or allow for the user to sort the options list how they wish and then that order be reflected throughout the rest of the extension.  Does that make sense?

**Comment by FelisCatus** [comment]
Yes, of course. I just want to add more information about that before we actually start the development.

**Comment by FelisCatus** [comment]
Merging this into #607.
