### ISSUE TITLE
Autoswitch not working

### ISSUE THREAD

**Issue by iloveemma** [FelisCatus/SwitchyOmega#398]
Hi,

I have pretty much the same issue as this person (https://github.com/FelisCatus/SwitchyOmega/issues/325) but his case got solved without an explanation. 

The site that requires a proxy works well when i'm selecting the "proxy" profile directly but it is unable to work when I use the "switch" profile.

Attach some pictures for your ref:

1) Auto switch profile selected
![1](https://cloud.githubusercontent.com/assets/10069989/7156722/95262000-e39b-11e4-9b5f-bf99bd1c4abd.png)

2) Proxy settings: Using http authentication
![2](https://cloud.githubusercontent.com/assets/10069989/7156723/9750c5d8-e39b-11e4-8510-260502986f1b.png)

3) Switch rules
![3](https://cloud.githubusercontent.com/assets/10069989/7156724/99d0b192-e39b-11e4-9a14-b5864bf8d11d.png)

Do you know what am I doing wrong?

**Comment by FelisCatus** [comment]
Please set the proxy server in the first row labelled "(default)". The other three rows below are only meant for separate proxy servers for each URL scheme, and therefore should be left blank (`use default`) in most cases.

Please try clearing the second row and set the proxy server in the first row labelled "(default)" and see if it helps.

**Comment by iloveemma** [comment]
Hi,

Thank you for replying. I did what you mention and clear added the proxy in the first row but it still didn't work.

![3](https://cloud.githubusercontent.com/assets/10069989/7168867/2f07f19c-e3f3-11e4-8871-b8264f24a984.png)

It shows it is using the "switch profile" but it didn't activate the proxy which I'm not sure why. When I switch directly to "proxy profile" the video will play. :(

![4](https://cloud.githubusercontent.com/assets/10069989/7168871/36151fbe-e3f3-11e4-9f93-134caeb3bc69.png)

**Comment by FelisCatus** [comment]
In that case, the video could be from another domain or provided by Flash.

1. If the video is from another domain: Locate that domain by using the F12 developer tool or `chrome://net-internals`. Then add a rule for that domain in SwitchyOmega.
2. Flash is more complicated with regard of proxy settings. I don't know if they actually supports PAC script or not.

Anyway, trying the first solution wouldn't harm.

**Comment by iloveemma** [comment]
I saw some links:

*.eplstarsportsus-lh.akamaihd.net
*.analytics.edgesuite.net

and tried to add them to the "host wildcard" condition type but no go. :(

**Comment by FelisCatus** [comment]
Probably not. Information about the containing webpage is not provided to PAC scripts, leaving the URL as the only condition for selecting proxies. Is there anything special about the particular URL? If so, maybe you could try URL wildcard or regex. If not, I don't think your mission can be accomplished.
