### ISSUE TITLE
建议：换回proxyswitch的切换方式

### ISSUE THREAD

**Issue by lxdlife** [FelisCatus/SwitchyOmega#399]
omega虽然有快捷键，但是太不方便了，我感觉还是点击循环切换比较好。
原因：
绝大多数的人不会使用一个以上的翻墙工具的。所以，要么是正常浏览模式，要么是翻墙浏览模式。通过点击按键循环切换完全没有问题。

SwitchyOmega 2.3.10
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
循环切换的设置在选项>界面>（最下方）快速切换，勾选即可启用。可随意配置。
