### ISSUE TITLE
对自动切换的条件设置建议

### ISSUE THREAD

**Issue by StrollStars** [FelisCatus/SwitchyOmega#400]
知道开发者很辛苦，但还是想提个建议，在合适的时候能够加入。
条件设置目前只支持一条规则，建议能够支持多条，就像其他情景模式的不代理的地址列表那样，这样方便集中统一设置。

**Comment by FelisCatus** [comment]
条件设置中通配符和正则表达式等类型，可以使用`|`分隔，加入多条规则。如域名通配符：`*.example.com|*.example.org`。

**Comment by StrollStars** [comment]
多谢提醒，因为我本身规则就存在嵌套，有点复杂，而且这样的话也不直观，还不如直接编辑源代码。
如果不方便的话，那可否在前面加个复选框，然后勾选多条规则一次性设置呢？

**Comment by FelisCatus** [comment]
规则多选见 #94. 我个人是感觉，如果经常需要更改一组规则的目标情景模式，用虚情景会更合适一些。虚情景可以在新建情景模式窗口中新建。

**Comment by StrollStars** [comment]
嗯，可以实现，谢谢。具体我部署来看。
