### ISSUE TITLE
建议加入情景模式的隐藏功能

### ISSUE THREAD

**Issue by xdujiang** [FelisCatus/SwitchyOmega#401]
某些情景模式只是用于将请求导向其他代理的，比如去广告的一些代理设置，希望在菜单中能够自定义隐藏某些情景模式，或者提供一个关于少用的情景模式的二级菜单，或者添加情景模式的自定义排序功能，否则列表太长不好选择

**Comment by FelisCatus** [comment]
名称以下划线`_`开头的情景模式即隐藏。
