### ISSUE TITLE
Can't not access to youtube

### ISSUE THREAD

**Issue by 7Kev** [FelisCatus/SwitchyOmega#405]
SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.18 Safari/537.36

**Comment by FelisCatus** [comment]
This is almost certainly caused by problem with your network or proxy server and has nothing to do with SwitchyOmega.

**Comment by 7Kev** [comment]
Yes, thx. It seems that the goagent cannot work properly.
