### ISSUE TITLE
设置完全没问题，但就是翻不了强。究竟是怎么回事。。。

### ISSUE THREAD

**Issue by Caryu** [FelisCatus/SwitchyOmega#407]
SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与本项目无关。
