### ISSUE TITLE
不能翻墙了

### ISSUE THREAD

**Issue by shantj** [FelisCatus/SwitchyOmega#408]
今天突然不能翻墙了，goagent版本3.2.3

SwitchyOmega 2.3.10
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与本项目无关。
