### ISSUE TITLE
2x 分辨率图标

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#41]
Title: Extension icons for 2x resolution.

现在有的静态图标应该可以很容易做 2x 的。不过动态图标怎么办呢？
考虑用两个 canvas 分别画 19px 和 38px ？还是只用 38px 的然后缩放？或者检测当前是1x还是2x？

总之暂时不影响使用，有时间再改吧。

**Comment by Tback1** [comment]
我倒是觉得现在的色环做的效果还不错
2014-12-30 下午6:12于 "FelisCatus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
刚才试了一下，先画 38px 的然后缩放，结果比较崩……看来只能 19px 和 38px 各画一份了。

那么问题就来了，究竟怎么检测浏览器是 1x 还是 2x 呢？

**Comment by Tback1** [comment]
我记得chrome本身SDK有一个识别全局分辨率的函数，直接获取应该可以。以1280*720作为1倍和2倍的分界线如何



—
通过 Mailbox 发送

**Comment by FelisCatus** [comment]
@Tback1 主要的问题是在于 Chrome 本身的 UI 绘制是 1x 还是 2x 。这个是由 Chrome 决定，和分辨率有关，但也可以用命令行参数覆盖。和网页的分辨率并没有直接关系……

**Comment by Tback1** [comment]
@FelisCatus 你没理解我说的，我说的是获取全局的分辨率，也就是获取屏幕本身的分辨率。Chrome本身的SDK应该是有这个函数的。1280*720为分界线或者别的分辨率（1920？会不会太高了点）作为分界线来决定1x还是2x。不是指的网页分辨率。

**Comment by FelisCatus** [comment]
@Tback1 和屏幕的分辨率也没有直接关系，主要是要看 UI 绘制。哪怕是 2800 屏幕的分辨率，也有可能图标只占 19x19 的。

**Comment by Tback1** [comment]
那你直接从chrome本身运行的状态函数里获取是1x或者2x的参数不可以么？没开放这个UI接口？​

我对前端谈不上什么经验，以前看过一篇这个
http://www.ui.cn/project.php?act=view&id=23624&p=1&pm=2

不知道能解决你的问题不，不过似乎也没提到相关的参数。

在 2015年1月13日 下午5:15，FelisCatus <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
没看到有这方面接口，因为可能 Chrome 的高分辨率支持也算是在开发中，不算太稳定吧。

我预计这里需要同时绘制 19px 和 38px 的两份图标，然后交给 Chrome 自行选择。看了下别的扩展也是这么做的。

**Comment by Tback1** [comment]
先放一下吧，明天我再问问朋友看有没有人知道这方面的资料
2015年1月14日 下午5:46于 "FelisCatus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
我打算在 v2.3.1 把这个做出来。具体实现方式是 19px 和 38px 都画一份。刚才试过，不算太占内存。

我不准备等新图标设计了，因为图标改了以后对于代码的影响不大。

**Comment by FelisCatus** [comment]
v2.3.1 已经支持高DPI屏幕。

High resolution icons are provided for high-DPI screens as of v2.3.1.
