### ISSUE TITLE
经常性的无法访问

### ISSUE THREAD

**Issue by heartacker** [FelisCatus/SwitchyOmega#410]
无法显示此网页

ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

无法显示此网页

ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

发现根本就不是代理的问题。是这个插件的问题。比如说微博，在自动切换下，我设置了weibo.com为直接连接还是不能连接。只有我设置情景为直接连接才可以。好神奇

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED 这个错误信息指明了是PAC脚本问题。可能包括PAC情景模式的问题，或者自动切换生成的脚本的问题。

对于这种情况，请在选项“自动切换”模式下，点击右上角“导出PAC文件”功能，然后将结果上传到 https://gist.github.com ，再把链接贴到这里，以便分析问题。

**Comment by FelisCatus** [comment]
请问这边如何了？

**Comment by 828768** [comment]
chrome x64代理无法使用,其他人有这现象吗?

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
