### ISSUE TITLE
关于不同前缀的同意系网站的设置问题

### ISSUE THREAD

**Issue by bbcec** [FelisCatus/SwitchyOmega#411]
请容许我先设定一个情景：有同一个网站不同网页，应用了不同的前缀，但除了前缀之外域名是一样的如：(a.example.com)  (b.example.com) (exanple.com)

之前用sharp时,针对这三个网页的情景规则设置是可以在当时所在网页分开进行的，即当我访问(a.example.com)时设置成使用代理的模式，访问(b.example.com)和 (exanple.com)时则使用直接连接的模式
可是今天更新使用了omega时，发现这些网页的前缀被统一去掉了，当我访问(a.example.com)想设置时发现只能设置exanple.com的情景规则，如果设置成代理访问之后就会发现无论是(a.example.com) 还是(b.example.com) 还是(exanple.com)使用的都是代理访问，而我想操作的只是(a.example.com)使用代理访问，剩下的使用直接连接访问。

那么想请问在此情况下我要怎么设置才能实现我的操作目标或是达到使用sharp时的使用效果呢？
谢谢

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by bbcec** [comment]
???请问有解决办法吗？

**Comment by FelisCatus** [comment]
@bbcec 这种情况请手工添加规则（弹出菜单中图标为加号的项目），不要使用临时规则等。相信这种情况只是几个的网站的特例，不会影响整体使用。
