### ISSUE TITLE
设置了虚拟情景模式会导致弹出非常卡顿

### ISSUE THREAD

**Issue by old9** [FelisCatus/SwitchyOmega#412]
设置了两个虚拟情景模式，一个给默认用，一个给 rules 用。其中一共大约有四五十条自定义 rules，外加 gfwlist。
点击图标弹出的 popup 会有很大几率卡在如图所示的状态大约1秒，有时更长。
![image](https://cloud.githubusercontent.com/assets/536624/7288293/ec70e3c6-e991-11e4-880d-b26fd6210003.png)

如果只设置一个虚拟情景模式，此问题有改善；如果不用虚拟情景模式，似乎没有发现明显卡顿。

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
……看起来这边的性能问题比较严重，等下优先调查这个。

**Comment by ACsediment** [comment]
和楼主在使用上存在类似的情况，也是2个虚拟情景和50条左右的自动切换规则。弹出卡1.5秒左右，Chrome任务管理器显示其CPU占用25%（双核四线程的电脑）。

**Comment by Tback1** [comment]
我报告....我现在是一个虚情景,三个代理模式..平均卡2秒........

**Comment by FelisCatus** [comment]
我现在怀疑虚情景那个附加的按钮导致了一些额外的布局开销，尤其是 re-flow 之类的细节。现在真的很忙，等有时间我自己也看一下 Timeline 吧。各位觉得卡的，也可以在图标上右键->审查弹出窗口，然后切换到 Timeline 功能并按Ctrl+R刷新重新加载弹窗，应该就能看到渲染时间的，不妨截个图。

**Comment by FelisCatus** [comment]
我这边无法复现……求各位给个 Timeline 截图吧。

**Comment by FelisCatus** [comment]
v2.4.4 已经大幅提高加载速度，大家可以自己试下。

**Comment by ACsediment** [comment]
@FelisCatus
感谢，您辛苦了！
当年都已经忘了给您Timeline截图了，您居然还记得这个issue！

**Comment by FelisCatus** [comment]
@ACsediment 哈哈，没关系～我一直在努力做得更好，不过这次可别忘记忘记试试新版哦 :-)

**Comment by ACsediment** [comment]
@FelisCatus 经过一段时间的测试，我这边已经没有卡顿的问题了，感谢！！ :+1:
