### ISSUE TITLE
关于自动切换模式的问题反馈

### ISSUE THREAD

**Issue by 9963yjn** [FelisCatus/SwitchyOmega#413]
感觉自动切换模式有问题，我现在用了一个海外代理，当我用自动切换模式，上某些我设定用这个代理的网站时，图片会加载不出来，有些网页会加载的很慢，但是我把自动切换模式切换成全部用这个代理的模式时，网页加载的很快，很流畅。我试过两个不同的代理，都会产生这样的问题，使得带来了一些不便。希望能加以解决，谢谢！（我一直关注并支持着这个产品，从switchysharp到SwitchyOmega，似乎以前用switchysharp时没有遇到这样的问题）

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
关于 GFWList 问题，请到那边反映。如果大部分国外的网页或图片都加载很慢，可以考虑使用白名单而非黑名单。
