### ISSUE TITLE
为什么SwitchyOmega老是绕过代理而直连呢？

### ISSUE THREAD

**Issue by qwIvan** [FelisCatus/SwitchyOmega#414]
![deepinscreenshot20150424161451](https://cloud.githubusercontent.com/assets/7613160/7315443/1dac03e4-eaa0-11e4-8b2a-090e4ae091fc.png)

正常代理的话，Remote Address应该是127.0.0.1

![deepinscreenshot20150424161504](https://cloud.githubusercontent.com/assets/7613160/7315444/2228b890-eaa0-11e4-8303-45edf7bf88d0.png)

**Comment by FelisCatus** [comment]
请确认当前选择了代理情景模式。如果使用自动切换的话，请确保该页面的切换结果为代理情景模式。

请注意一些去广告等使用PAC的扩展可能会覆盖SO的代理设置，造成冲突。
