### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by denistrustepain** [FelisCatus/SwitchyOmega#416]
Extension is not working :(

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by oleksdovz** [comment]
I faced with similar error:
When local pc not able to resolve hostname and  only proxy server which gets request can resolve  by FQDN.

**Comment by FelisCatus** [comment]
@denistrustepain What do you mean by "not working"? Is your proxy server failing? Or is it the profile switching part? What exactly is the issue?

----

@oleksdovz This is by proxy design and has nothing to do with SwitchyOmega, nor does it relate to this issue. I would suggest further reading on how HTTP or SOCKS proxy server work, especially the "remote DNS" part.

**Comment by oleksdovz** [comment]
Will be fine to have resolved hostname on  HTTP or SOCKS proxy  side.  I cannot use SwitchyOmega because Proxy server connected to to internal network via VPN and hostnames are not resolved.
If you need  I can send you logs or something else.

**Comment by FelisCatus** [comment]
@oleksdovz Please allow me to emphasize that SwitchyOmega does not do network internals. Instead, it just tell Chrome to use the proxy server and Chrome does the actual connection. As a result, SO does not have any control over implementation details such as DNS.

If you need to do the DNS on local PC, I think you should try setting up a local proxy server that 1. does the DNS on your PC, and, 2. send the modified request to the target proxy server via VPN. I'm not expert on this. Please try posting your requirements on some forum focused on proxy or network if you need some help on that.

**Comment by FelisCatus** [comment]
I'm gonna close this for now since OP is just stating that "Extension is not working" without providing any details or questions. Please reopen this issue when more information is available.
