### ISSUE TITLE
代理身份认证部分情况下失效

### ISSUE THREAD

**Issue by cnrat** [FelisCatus/SwitchyOmega#417]
设置了HTTPS代理的身份认证信息（用户名+密码）
从日志上看大部分访问都正确无误，但是少量的GET和CONNECT请求会因为没有上送用户名导致服务器返回407错误

这是SwitchyOmega的问题还是Chrome的问题？

**Comment by FelisCatus** [comment]
比较怀疑是Chrome的问题，然而这边很难确认究竟是什么……可以试试看弹出菜单“导出日志”功能，里面应该有关于身份认证的日志（不含用户名密码，可放心上传）。

**Comment by cnrat** [comment]
其实这个事情的背景是，我在VPS上的access日志中发现了大量的443端口扫描，对IP地址分析以后发现居然扫描来源都是省市级出口IP，尝试做GET请求无界XX的站点，担心是GFW的变种扫描形式。因为本身Squid设置了basic auth，所以用fail2ban把所有带407的请求都给ban了，接下去就是发现有误判的情况把自己也给ban了，原因就是发生了不带密码的请求。

不过我查了一下HTTP协议规范，貌似浏览器是出现401/407之后才会主动提供auth上送的，所以我已经把fail2ban的过滤脚本改成了域名黑名单模式，现在运行良好。

这个issue可以算是解决了吧，非常感谢！

**Comment by FelisCatus** [comment]
@cnrat 不用谢！如您所言，这边有人提议过直接发用户名密码，服务器不返回401/407。但浏览器确实是遇到401/407才提供用户名密码的。如果不是这种情况，则SwitchyOmega根本就不会收到Chrome要求提供密码的请求，也就没有办法设置登录。
