### ISSUE TITLE
同步的情景模式缺少规则列表时报错

### ISSUE THREAD

**Issue by LiHaoGit** [FelisCatus/SwitchyOmega#418]
SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.76 Safari/537.36
当我打开云端同步的时候，等同步成功就这样的
![default](https://cloud.githubusercontent.com/assets/7036191/7343679/e25b1416-ecf6-11e4-8989-9837565a2dbe.png)

**Comment by FelisCatus** [comment]
这个问题好像是由于规则列表为空导致的。同步时为了节省空间，并未同步规则列表，而依赖于再次下载。

这里的确是我疏忽了。

**Comment by FelisCatus** [comment]
v2.3.12 已经修复。
