### ISSUE TITLE
自动代理切换不可用

### ISSUE THREAD

**Issue by forda** [FelisCatus/SwitchyOmega#419]
SwitchyOmega 2.3.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by FelisCatus** [comment]
请按照教程设置GFWList等功能。

https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList
