### ISSUE TITLE
能不能把图标颜色设计的显眼一点，连接和不连接差别太小

### ISSUE THREAD

**Issue by firemiles** [FelisCatus/SwitchyOmega#420]
图标颜色对比不够强烈，要仔细观察才能发现当前是否使用了代理，能不能考虑红杏翻墙的配色方案，使用红绿配色，还望采纳。

SwitchyOmega 2.3.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by iqiancheng** [comment]
可以设置：
![](http://qianc.qiniudn.com/switchyOmega-setting-color.png)

**Comment by firemiles** [comment]
很好很强大

**Comment by FelisCatus** [comment]
这里这个取色器虽然确实是可以用的……但不够明显，很多人都看不到这里可以编辑。之前也有很多Issue问怎么修改颜色。
有什么办法做得明显一点，但又不显得突兀吗？
