### ISSUE TITLE
使用自动模式资源项未加载怎么办

### ISSUE THREAD

**Issue by destinyyun** [FelisCatus/SwitchyOmega#421]
SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
未加载的话可以在弹出菜单中添加规则。如果不需要此提示可以在选项中关闭网络检测。
