### ISSUE TITLE
有点小问题，新版的自定义规则怎么不起作用了

### ISSUE THREAD

**Issue by hehh2001** [FelisCatus/SwitchyOmega#423]
有点小问题，新版的自定义规则怎么不起作用了，系统代理是什么意思？我将要代理的网站加入自定义规则无论怎样选，都无法翻墙。

SwitchyOmega 2.3.11
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by hehh2001** [comment]
看中国，大纪元这样的网站，美国之声，都无法加入自定义，打不开，代理是正常的

**Comment by FelisCatus** [comment]
如果这些网址需要代理，请选择一个代理情景模式。代理情景模式是指配置了代理服务器地址、端口等信息的那个情景模式。
