### ISSUE TITLE
有时候直接连接显示不出来。只有一个高度很小的小蓝条。

### ISSUE THREAD

**Issue by minioreo** [FelisCatus/SwitchyOmega#424]
SwitchyOmega 2.3.11
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
这个是 OS X 下Chrome的已知问题（有很多人都遇到了），弹出菜单总是不能正常定位显示，和此项目无关。我建议直接去Chromium项目那边反馈，多几个人关注或提供信息的话，那边就能快点解决了。

**Comment by FelisCatus** [comment]
P.S. 关于这种现象的截图请见 #367 。

**Comment by TimonLio** [comment]
之前用SwitchySharp的时候，从来不会这样，这个菜单列表能改回SwitchySharp的实现方式么？

**Comment by FelisCatus** [comment]
@TimonLio 之前 Chrome 也没这个 bug ，是最近几个月新出来的。虽然之前也有过类似的 bug 就是了……当时无论 SS 还是 SO 都各种弹出菜单显示不出来或者错位。当时也是各种反馈各种抱怨，而我一点办法都没有。
