### ISSUE TITLE
Rule: Switching between System Proxy and custom rule

### ISSUE THREAD

**Issue by DanSchlachter** [FelisCatus/SwitchyOmega#425]
Hello,

when I create a rule in switchyOmega, I somehow can not get the exact same settings as in the system proxy settings.
Therefore, I'd like to create a switching rule between system proxy settings and a custom proxy settings for a certain URL pattern. However, the option is not available / I can't find it.

Thanks
Daniel

**Comment by FelisCatus** [comment]
Such feature is not possible due to browser restrictions and was [discussed in detail some time ago](https://github.com/FelisCatus/SwitchyOmega/issues/289#issuecomment-78969887). Please refer to the exact comment following the link for a definitive answer.
