### ISSUE TITLE
不知道什么情况，明明选择的是自动切换模式，偶尔会变成pac模式？？

### ISSUE THREAD

**Issue by loveser** [FelisCatus/SwitchyOmega#426]
SwitchyOmega 2.3.11
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
可能是安装了其他使用了PAC的扩展，如去广告扩展等，发生了冲突。

可以试着卸载 SwitchyOmega 然后再重新安装，可以提高 SwitchyOmega 的优先级。
