### ISSUE TITLE
希望支持socks5的用户名和密码登陆

### ISSUE THREAD

**Issue by jundota2** [FelisCatus/SwitchyOmega#427]
在vps中安装了dante-server，使用socks协议，需要用户验证。
目前我是使用Proxifier登陆代理的，但是SwitchyOmega的socks5代理选项却没有支持验证用户的登陆方式。
希望能够在以后的版本中添加这种方式的支持。

SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36 LBBROWSER

**Comment by FelisCatus** [comment]
见 #178.
