### ISSUE TITLE
v2.3.12 修复bug后，360极速无法再利用这个bug来添加新站点了。现在是无法添加新站了。

### ISSUE THREAD

**Issue by Dexcn** [FelisCatus/SwitchyOmega#428]
老大，求你不要修复这个bug啊。你一恢复，我们用360极速浏览器（不管哪个版本，用过包括最新版的多个版本，目前在用8.3）的都不能正常使用Omega来添加不能访问的站点了。 以前有这个bug的时候，网站打不开时点“一个资源未加载”然后点“设置网络检测选项” 然后就能自动把当前网站添加到切换规则（虽然毫无提示，虽然添加到的是上次默认的规则{上次选的是虚情景，它就自动添加到虚情景}，但起码利用这个bug你能添加，现在则完全无法添加了）。

另外360极速浏览器在打不开的网页界面点“一个资源未加载”后不出现添加按钮，只出现“设置网络检测选项”的原因应该是360把打不开的网页进行了劫持。跳到了它设置好的访问错误页面，目的是在这个页面里做一些定制和植入一些热点新闻网址。那么这个劫持后跳到的页面是个错误反馈页面，所以Omega点了之后直接认为网络发生错误就只给了“设置网络检测选项”了。 装foxyproxy代理扩展来在360极速添加当前页面也一样，添加的不是当前页面，而是errorpage的页面了。

希望不要修复这个bug，就是靠这个bug活着的。或者希望能从根本上解决这个问题，彻底的完美的支持360极速浏览器。试过foxyproxy等多个代理扩展都不如Omega，有一个叫everproxy的是根据红杏改的遇到不能访问的网址就提示让自动添加比较方便，可惜好久也不更新了不能用了。目前能用的，唯一比Omega方便，而且方便的比较明显的，是autoproxy的黑仪大螃蟹修改版。不是另一个修改版，著名的有两个修改版，黑仪大螃蟹的应该目前是修改的最好的。但可惜火狐打开网页的速度和流畅度都不如谷歌内核的浏览器高，否则就为了那一个扩展我也绝对离不开火狐的。

（昨天还是前天我就把此贴发了一下，但是已回帖的方式发的，而那个我回的主贴很早就被关闭了，所以你可能没看到所以没回复我，重新开帖发一下。如果发重了你可以删除掉。）

**Comment by FelisCatus** [comment]
我重新开了 #365 ，在那边讨论吧。

P.S. 可能有时候会比较忙，没空看 issue tracker ，但回复都有邮件和通知的，不太会漏掉。
