### ISSUE TITLE
cant work

### ISSUE THREAD

**Issue by Light--** [FelisCatus/SwitchyOmega#430]
hi,

sorry, i dont know how to use this extension, when i switched to anto switching mode, even baidu.com cannot reach. I am from China. Can you provide a manual that I can do checking myself? Thanks a lot.

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
A [step-by-step guide](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList) is provided for users in China.

Also, you may use Chinese here if you like.
