### ISSUE TITLE
自动切换模式希望加入failback条件

### ISSUE THREAD

**Issue by Septembers** [FelisCatus/SwitchyOmega#431]
当遇到特定错误时使用failback条件
比如：ERR_CONNECTION_RESET, ERR_CONNECTION_TIMED_OUT等的情况

> 期望模型：
> 　　条件类型：特殊 - failback
> 　　条件设置：ERR_CONNECTION_RESET
> 　　　　　　　ERR_CONNECTION_TIMED_OUT
> 　　　　　　　ERR_CONNECTION_ABORTED
> 　　　　　　　ERR_SSL_PROTOCOL_ERROR

我实质上是希望引入 https://github.com/zizon/switchyd

#73 #9 #6

**Comment by FelisCatus** [comment]
如果每次出错就改一下PAC，会不会卡的飞起？毕竟扩展生成PAC、浏览器编译和执行初始化都需要点时间……

而且要刷新才能用，感觉体验并不会很好。比如产生 ERR_CONNECTION_TIMED_OUT 错误之前，需要等太久太久（以至于SwitchyOmega是设置了5秒的定时器而非依赖此错误）。

还有一个问题就是误判……我觉得作为未加载资源提示是挺好的，但直接加入规则或临时规则可能就要慎重考虑了。

我说以上这些问题，并不是说不做，而是最好讨论一下，考虑清楚再做。
