### ISSUE TITLE
能不能手动执行同步操作

### ISSUE THREAD

**Issue by suzj801** [FelisCatus/SwitchyOmega#433]
不知道为什么，一台电脑能同步，一台电脑就不能，全局翻墙了也不好用。如果能手动同步看到同步失败的原因就好了。

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by FelisCatus** [comment]
由于Chrome扩展同步机制，无法手动进行同步，扩展也看不到同步失败的原因等。非常抱歉。
