### ISSUE TITLE
 N个资源未加载？？？

### ISSUE THREAD

**Issue by leoone** [FelisCatus/SwitchyOmega#435]
Please deliver the answer to this email of mine, thank you very much:
leoonechina@gmail.com

图标每天都在提醒我“N个资源未加载”，每次点了之后，每次都弹出Omega的设置页面，是设定栏的第二项“通用”。这究竟是什么意思？Is it doing that for fun? What the heck am I supposed to do with it???

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

如果无须此提示，请在通用>网络请求中关闭网络情况检测。
