### ISSUE TITLE
Would you explain this for me?

### ISSUE THREAD

**Issue by leoone** [FelisCatus/SwitchyOmega#436]
How to fix this???
Scene Mode:
SwitchOmega::auto switch
*.google.com =>proxy
PROXY 127.0.0.1:8087
url: 
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CB4QFjAA&url=https%3A%2F%2Fgithub.com%2FFelisCatus%2FSwitchyOmega&ei=EYlHVaT5A5OfyATtm4CACw&usg=AFQjCNEwRpif2fBTXC1_vZh72gxLudH92g&sig2=FhiLyBdvZEYAixFG8kq1_A

![google error](https://cloud.githubusercontent.com/assets/12236144/7455773/f51237ba-f2b9-11e4-9793-24e420dc9752.PNG)

And sometimes It reminds me something like I don't have some appid, so I need to edit my init file.

Please kindly answer the questions above in this email： leoonechina@gmail.com, thank you very much!

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by dna1982** [comment]
明显是GoAgent的问题……
SwitchOmega只是一个设置代理服务器插件。

**Comment by FelisCatus** [comment]
GoAgent 问题与本项目无关。
