### ISSUE TITLE
It comes again, here it is:

### ISSUE THREAD

**Issue by leoone** [FelisCatus/SwitchyOmega#438]
![image](https://cloud.githubusercontent.com/assets/12236144/7456834/940309be-f2c2-11e4-9299-67e8ed7ed950.png)

How to fix it, really?

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
This is definitely something wrong with your proxy server (e.g. GoAgent) and has nothing to do with this project. Also, stop spamming the issue tracker.
