### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by leoone** [FelisCatus/SwitchyOmega#439]
![Uploading Over fucking  quota_Suck  bullshit_and  WTF is quota.PNG…]()

How to solve this problem?

Seems you guy have caused more problems than the ones you solved. Prove me wrong.

Leo
leoonechina@gmail.com

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
This is definitely something wrong with your proxy server (e.g. GoAgent) and has nothing to do with this project. Also, stop spamming the issue tracker.
