### ISSUE TITLE
What's this?

### ISSUE THREAD

**Issue by leoone** [FelisCatus/SwitchyOmega#440]
![Uploading Does not have fucking perssion.PNG…]()

![Uploading Over fucking  quota_Suckh bullshit_and  WTF is quota.PNG…]()

![Uploading WTF doesn't exist..PNG…]()

How to solve these problems?

Seems you guy have caused more problems than the ones you solved. Prove me wrong.

Leo
leoonechina@gmail.com

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
This is definitely something wrong with your proxy server (e.g. GoAgent) and has nothing to do with this project. Also, stop spamming the issue tracker.
