### ISSUE TITLE
在哪里可以查看自己现在所用插件的版本号呢？

### ISSUE THREAD

**Issue by xuexiaokang** [FelisCatus/SwitchyOmega#441]
在哪里可以查看自己现在所用插件的版本号呢？主界面上都找不到显示版本号的地方，这样无法知道自己用的是新的还是旧的插件，希望下个版本能添加版本号显示

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
见 #298. 以及……暂时可以用菜单>反馈问题的方式查看版本号，不用真的提交issue。
