### ISSUE TITLE
希望开发情景模式的禁用功能

### ISSUE THREAD

**Issue by shensmart** [FelisCatus/SwitchyOmega#444]
能否像火狐的FoxyProxy一样可以手动的禁用和开启某个情景模式，比如，我在单位需要用我自己的代理访问某些网站，但是回到家了就不需要用代理了，现在的情景模式没有禁用功能，还是不大方便

**Comment by FelisCatus** [comment]
暂时来说，可以新建一个“虚情景模式”，然后把那个代理情景模式替换成虚情景。之后就可以很方便地在菜单中选择虚情景使用哪个代理情景，或者使用“直接连接”了。

禁用功能可以考虑，不过适用的范围不太广，而且不是很常用。如果有更好的解决方案，请及时提出建议。

**Comment by FelisCatus** [comment]
考虑了很多，还是觉得虚情景模式足够了。禁用功能就不做了吧……
