### ISSUE TITLE
Authentication required popup on starting Chrome before SO loads

### ISSUE THREAD

**Issue by mgibson85** [FelisCatus/SwitchyOmega#446]
Hi,

I have an authentication required popup everytime I open chrome with a proxy server enabled.
The proxy server has authentication settings setup. I have tried removing, re-adding but it still occurs. I usually Escape out or quit the prompt, and it uses the proxy settings anyway.

Please advise.

![untitled-1](https://cloud.githubusercontent.com/assets/12297674/7518138/0ab2e146-f4d1-11e4-9022-b57daab0c87a.png)

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega tries to provide your credentials (as filled in SwitchOmega options) to Chrome if authentication is needed. However, the proxy server in question might reject the credentials due to wrong username/password or just because it feels like doing so.

Please check your credentials first to ensure they are correct. Then, see if there are any special characters that might cause issues in Chrome. Besides, things could go wrong with the proxy server and such problems cannot be solved client-side with SwitchyOmega.

**Comment by mgibson85** [comment]
Thanks for your prompt reply. On the Authentication Required prompt I can click the Log In button without entering any credentials and it works. It's more of an annoyance than anything. For whatever reason its not passing credentials first time, and those credentials work fine otherwise I wouldn't be able to just click login and it load the page, using the proxy settings I'm asking it to :)

**Comment by FelisCatus** [comment]
In that case, Chrome issued network requests on start up before SwitchyOmega was even loaded and had a chance to provide credentials. I have no idea about dealing with such requests. Who knows, chances are high that the problem cannot be solved with extensions.

**Comment by xieranmaya** [comment]
我也遇到这种情况，在Chrome运行状态下新建一个带有用户验证的HTTPS代理情景模式，然后切到那个模式，从服务器收到的信息来看，浏览器并没有发送用户名和密码的头部
而这个时候SwitchOmega肯定是已经加载了的

#673

**Comment by xieranmaya** [comment]
我今天测试发现好像是Chrome的问题
我用最新的Canary就可以，但是用Chrome它就不会发
Canary版本 49.0.2607.0 canary (64-bit)
Chrome版本 47.0.2526.106 m
在Mac上也是同样的问题

而且Chrome现在还有另一个问题，就是对HTTPS代理，在弹出账户输入框后输入内容后会立马crash，但HTTP代理不会，也是Chrome上复现，在Canary上不会有这个问题
开发组说在Chrome上这个问题会在v48修复，大概一月低
https://code.google.com/p/chromium/issues/detail?id=570171

**Comment by FelisCatus** [comment]
等更新吧……

**Comment by xieranmaya** [comment]
测试发现即使在SwitchOmega里设置了用户名密码（SwitchOmega已经加载），浏览器第一次使用这个代理时也还是不会发送proxy-auth头部，然后代理服务器返回一个要求验证的头部，下一个请求Chrome才会带上验证信息，这可能是Chrome的问题吧，不知道其它浏览器是怎么处理的，没办法测试
![image](https://cloud.githubusercontent.com/assets/2993947/12111279/0004370a-b3cf-11e5-8734-26c69d193910.png)

**Comment by FelisCatus** [comment]
Chrome 的认证方式就是先照常发送请求，然后如果服务器返回需要验证，再弹窗提示用户输入用户名密码。 Chrome 扩展只能做到帮你自动填写用户名密码，省去那个弹窗而已。

如果要做到直接发 `Proxy-Auth`，需要强行修改每个请求的 HTTP Header ，我觉得是还是不去惹这个麻烦比较好。

**Comment by xieranmaya** [comment]
> Chrome 扩展只能做到帮你自动填写用户名密码

想了解一下这个是如何做到的呢，是拦截请求还是chrome.proxy.*的api提供的功能？

**Comment by FelisCatus** [comment]
https://developer.chrome.com/extensions/webRequest#event-onAuthRequired

用的是 webRequest API 中的`onAuthRequired`事件。根据我的观察，其他类似的扩展也大部分是用的这个。也有的扩展用的`webRequest`中的其他事件，拦截修改请求并加上 HTTP Header.

**Comment by xieranmaya** [comment]
@FelisCatus 多谢~我也去了解一下
