### ISSUE TITLE
不同的平台式有问题啊

### ISSUE THREAD

**Issue by redstoneleo** [FelisCatus/SwitchyOmega#448]
具体可以看这篇帖子
https://github.com/XX-net/XX-Net/issues/347

**Comment by FelisCatus** [comment]
非常感谢，已经在那边回贴建议更多反馈或详情。

然而具体问题的解决需要更多信息，在其他项目遇到此类问题时，请建议用户来此项目提交反馈。抄送或转述一些模糊的问题描述对于问题的解决帮助不大，请理解。

**Comment by redstoneleo** [comment]
我也是在那边看到了，所以贴过来给你看看

**Comment by FelisCatus** [comment]
那边似乎不再更新了。我先关闭这里好了，有任何问题或者新的想法可以继续讨论。
