### ISSUE TITLE
如果SOCKS5代理是有用户名和密码的话，怎样输入用户名和密码？

### ISSUE THREAD

**Issue by beyonder** [FelisCatus/SwitchyOmega#449]
如果SOCKS5代理是有用户名和密码的话，怎样输入用户名和密码？
谢谢

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36

**Comment by FelisCatus** [comment]
见 #178.
