### ISSUE TITLE
建议直接整合autoproxy或者其它代理配置，安装后开箱即用

### ISSUE THREAD

**Issue by leehuabo** [FelisCatus/SwitchyOmega#450]
建议直接整合autoproxy或者其它代理配置；比如使用autoproxy的gfwlist.txt作为规则，用自由门当代理；

当前使用比较麻烦，有很多需要配置，配置完成后还要手工开启auto switch，比较折腾，远不如firefox上的autoproxy简单易用

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
目前来说，仅提供了一个设置好GFW List 的[选项备份文件](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList.bak)和相关教程。关于进一步的集成或默认值，见 #9 。
因为代理服务器的设置问题，无论如何都应该是做不到“开箱即用”了。不过适当地简化下流程还是可以的。
