### ISSUE TITLE
显示资源未加载，弹框点添加条件之后，刷新页面问题依然存在

### ISSUE THREAD

**Issue by wgw0415** [FelisCatus/SwitchyOmega#451]
显示资源未加载，弹框点添加条件之后，刷新页面问题依然存在

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36

**Comment by FelisCatus** [comment]
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

如果无需此提示，可以在选项>通用中关闭检测网络功能。
