### ISSUE TITLE
希望增加自动模式的状态显示

### ISSUE THREAD

**Issue by hongjian1993** [FelisCatus/SwitchyOmega#453]
因为使用的VPS是限制流量的，所以希望在使用auto switch模式时可以实时看出来当前流量走的是“直接连接”还是“代理模式”，以免出现一直走的代理最终造成流量超额却仍不知情的后果。
可以通过插件图标样式或颜色的改变来区分，或者其他的什么办法，只要醒目就好。

SwitchyOmega 2.3.12
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by FelisCatus** [comment]
自动切换模式中，图标的颜色反映当前页面使用的情景模式。灰色边的是直接连接，而彩色边的是代理情景模式。如果觉得颜色不够明显，可以在选项里修改代理情景模式的颜色。
