### ISSUE TITLE
chrome安装扩展之后，会导致无法启动，如何解决？

### ISSUE THREAD

**Issue by zch0071** [FelisCatus/SwitchyOmega#454]
chrome是最新的版本，安装扩展之后，使用的是Shadowsocks作为代理服务器（客户端有2种模式，一种是PAC模式一种是全局模式）。但是正是因为这样会导致冲突，然后chrome就一直启动不了（已停止工作）
如何解决这个问题？

**Comment by FelisCatus** [comment]
SwitchyOmega 和 Shadowsocks 不冲突。此类情况是由Chrome自身问题引起，建议尝试升级或降级Chrome。如果有条件，可以尝试 Chrome Dev 版，再看看问题是否已经修复。

如果还不行，建议您向Chromium项目提交崩溃日志，举手之劳，帮助他们解决问题。
