### ISSUE TITLE
使用sock4/sock5协议怎么输入用户名密码

### ISSUE THREAD

**Issue by lyjdamzwf** [FelisCatus/SwitchyOmega#456]
等了老半天，终于等到了Omega，我用得是ss5服务，为啥用户名密码只支持http/https？？？

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
见 #178.
