### ISSUE TITLE
求助chrome翻译的问题

### ISSUE THREAD

**Issue by ncmon** [FelisCatus/SwitchyOmega#457]
开启GoAgent后设置IE代理默认是禁用代理模式这个时候chrome网页无法翻译，请问怎么添加切换规则可以让chrome开启网页翻译呢，如果把GoAgent模式切换成http://127.0.0.1:8086/proxy.pac 翻译功能一切正常，是不是在规则列表里面没有添加翻译的网址啊.

**Comment by FelisCatus** [comment]
GFWList 问题请到那边反馈。
