### ISSUE TITLE
<local> in bypass list also applies to IPv6 addresses

### ISSUE THREAD

**Issue by zzq1015** [FelisCatus/SwitchyOmega#458]
My proxy supports IPv6. However, this link
`http://[2001:470:1:18::119]/ip/`
will show your real IPv6 address, not going through any proxies

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
Check the bypass list of your proxy profile and make sure it does not apply to IPv6 addresses. (You can upload a screenshot here in case of question.) Also, please apply the proxy profile globally through the menu instead of using Switch Profile.

**Comment by zzq1015** [comment]
There's only one line in bypass list: "<local>"
Changed it to: 
"127.0.0.0/8
localhost
[::1]"
problem solved.
I suggest you to ship the default setting with the three lines above instead of "<local>"

**Comment by FelisCatus** [comment]
Are you sure about that? Chrome states that `<local>` should be equivalent to "127.0.0.1", "::1", or "localhost".

> Match local addresses. An address is local if the host is "127.0.0.1", "::1", or "localhost".
Example: "<local>"

It would be a bug of Chrome if it also bypass all IPv6 addresses.

**Comment by zzq1015** [comment]
Yes. There was only one line "`<local>`"
But I change it to: 
> `127.0.0.0/8`
> `localhost`
> `[::1]`

IPv6 will be proxied again.

**Comment by FelisCatus** [comment]
Thanks for your report then. I think I need to experiment with IPv6 a little bit to see it happens to me. Meanwhile, you can [open an issue in the Chromium project](https://code.google.com/p/chromium/issues/list) and tell them your findings.

**Comment by FelisCatus** [comment]
Let's merge the discussion to #443. Also, #443 links to a Chromium bug that might be related to the problems.
