### ISSUE TITLE
第一次用omega。有些情况不太明白。

### ISSUE THREAD

**Issue by lsq726** [FelisCatus/SwitchyOmega#461]
切换选项
初始情景模式  [直接连接]

自动切换

切换选项
默认情景模式  [直接连接]

这2个情景模式是什么意思？
-------------------------------------

切换选项
默认情景模式  [直接连接] 

这是否代表不在切换规则的网址使用 直接连接？
如果是。

为什么我访问有的不在切换规则的网址。他提示无法加载资源。。得添加这个网址到 直接连接的规则里？

在用sharp的时候。没有遇到这个情况。。

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
初始情景模式： 浏览器启动时，选择的情景模式。一般来说选择“(当前情景模式)”就可以了
自动切换的默认情景模式：所有规则均**不匹配**时使用的情景模式。如果规则基本都是代理情景模式的话，那么默认可以选择直接连接，这样只让一部分网址走代理。

----
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

如果无须此提示，请在通用>网络请求中关闭网络情况检测。有时候可能这些资源需要代理才能访问，那么可以尝试添加代理规则。但有时候是网络或者服务器问题，那就没办法了。

**Comment by lsq726** [comment]
发现跟sharp 在自动切换有点区别。。就是少了
默认规则  All URLs that doesn't match any other pattern 直接连接 切不可删除的规则。

而同样的pac 用omega 就经常 无法访问。。
而sharp则不会
应该。不是网络。代理引起的。

**Comment by FelisCatus** [comment]
SO的PAC生成是一个确定的过程，如果不改配置，结果就一定是一样的，哪个网址是否使用代理都是确定的。凡是偶尔会发生的情况，基本上都要在网络或者代理服务器那边找原因。

**Comment by lsq726** [comment]
说了你不信。同一个bak恢复的。sharp正常。omega经常提示资源无法加载。

只在不走代理的情况下发生。也就是网站不在规则列表中。
应该是走直接连接的情况。而omega提示资源无法加载。当把网站添加到规则中 直接连接 则能正常打开。。
顺便说一下。 ie 设置了 使用自动配置脚本 pac不知道与这个有没有关系。。因为在omega 比sharp 多了个选项就是“系统代理”

**Comment by FelisCatus** [comment]
基本上已经可以确认是网络问题，之前 switchysharp 没有提示是因为旧版本根本没有检测网络请求的功能，自然也没有这方面的提示。碰到这种问题直接刷新应该就能修复。

对于有的网络情况（尤其是网络不稳定或者响应慢的情况），确实误报会比较多，所以我建议直接在通用>网络请求中关闭网络情况检测，不影响正常使用。

**Comment by lsq726** [comment]
恩。有空改回omega，关闭网络监测 试试再反馈。
