### ISSUE TITLE
网页访问失败后，只会显示加载失败的资源列表，不能手动快捷添加规则

### ISSUE THREAD

**Issue by hydream** [FelisCatus/SwitchyOmega#462]
我使用的是360极速8.3 ，假设当访问facebook.com失败后，360 会返回一个错误页面，要求刷新和好搜的界面。

这时，SwitchyOmega只会显示加载失败的资源列表，不能手动快捷添加规则.
提示在使用自动切换情景时，才可以将这些资源添加为切换条件。
当时我本来就一直使用的自动切换情景。

希望在无法访问时，直接能快捷添加规则。谢谢！

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

![tt](https://cloud.githubusercontent.com/assets/11847823/7670112/a6bfb708-fcc9-11e4-89c7-b4742f5c9e7c.png)

**Comment by FelisCatus** [comment]
见 #462. 仍然是似乎只有 360 有这个问题……唉。

**Comment by YouthLin** [comment]
我不是360, 就是Chrome也这样啊，Ubuntu 16.04LTS，Google Chrome	53.0.2785.116 (正式版本) （64 位）
打不开网站时显示的是「在使用自动切换情景时，才可以将这些资源添加为切换条件。」，但之前是可以直接添加的

**Comment by krizex** [comment]
我的chrome今天也遇到了这个问题，之前一直好好的。
chrome版本52.0.2743.116 m  最近这个插件和chrome都没做升级。

**Comment by joeaki1983** [comment]
扑街了，我也是这样，可能是chrome升级引起的？

**Comment by dooear** [comment]
有解决方法么？

**Comment by joeaki1983** [comment]
搞清楚了，是因为swithyomega升级引起的，退回2.3.19版本

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。

**Comment by krizex** [comment]
看样子貌似是这个extension升级了。。。

2016-10-26 21:19 GMT+08:00 joeaki1983 <notifications@github.com>:

**Comment by krizex** [comment]
原来chrome的插件会自动升级呀？

2016-10-26 22:54 GMT+08:00 Felis Catus <notifications@github.com>:
