### ISSUE TITLE
尼玛没有一个线路是可以登进去的！怎么回事？？？？？？？？？

### ISSUE THREAD

**Issue by lililijj** [FelisCatus/SwitchyOmega#463]
SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by yellowvii** [comment]
所以说你想表达什么？

**Comment by FelisCatus** [comment]
SwitchyOmega 是代理设置软件，不提供代理服务器或VPN连接。如果遇到线路问题请直接和您的代理或VPN提供商联系，与本项目无关。
