### ISSUE TITLE
给按钮右击加上快速选项菜单?

### ISSUE THREAD

**Issue by zeiyso** [FelisCatus/SwitchyOmega#464]
你好, 
考虑到现在**左击扩展程序图标按钮出现的菜单的显示速度较慢**, 启用 "快速切换" 功能虽然能很大程度上的解决这个问题, 但是不能适应快速在折腾与使用之间切换的日常...

为此, 请考虑在 ~~```manifest.json``` 的 ```'commands'``` 项中~~**加上转换 "快速切换" 这个功能是否开启的菜单项**, 以实现右击图标就能转换?

**Comment by FelisCatus** [comment]
这个可以考虑。

**Comment by FelisCatus** [comment]
然而 commands 里的项目似乎并不会显示在图标的右键菜单里……我做错什么了吗？请 @zeiyso 赐教……

**Comment by zeiyso** [comment]
抱歉, 是咱弄错了orz 应该是在上下文菜单上加... 类似这样. 

```javascript
chrome.contextMenus.create({
           title: "Menu Title",
           contexts:["browser_action"],
           onclick: doSth
        })
```

https://developer.chrome.com/extensions/contextMenus

**Comment by FelisCatus** [comment]
这个容我考虑一下，毕竟上次加右键菜单的时候抗议很强烈……

**Comment by zeiyso** [comment]
唔, ```contexts:["browser_action"]``` 的话似乎不会在网页右击菜单中出现?

**Comment by FelisCatus** [comment]
原来这个还可以这样用啊，挺好的……我觉得下一个版本可以加上，反正也不占用空间。

**Comment by FelisCatus** [comment]
现在右键菜单里可以勾选/取消快速切换了。此外，原先左键弹出菜单里的"反馈问题"、"错误日志"两个不太常用的项目也移动到右键菜单。

有问题请右键图标->反馈问题。——这种感觉吧。

（此修改暂时未发布，预计这周末会有一次更新。如有意见可以在此前提出。）

**Comment by FelisCatus** [comment]
v2.3.14 已经发布。
