### ISSUE TITLE
切换代理时 经常无法显示 直接连接

### ISSUE THREAD

**Issue by chliul** [FelisCatus/SwitchyOmega#467]
如图
![image](https://cloud.githubusercontent.com/assets/7077748/7712093/b4bedc88-fea1-11e4-8cbd-072f8e639ba3.png)

SwitchyOmega 2.3.12
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36

**Comment by syswow** [comment]
建议改一下标题： “切换代理时 经常无法显示 直接连接”
估计是UI bug。

**Comment by chliul** [comment]
bug虽然不大。。。但是相当恼人。。。＝w＝

**Comment by FelisCatus** [comment]
见 #424
