### ISSUE TITLE
Issues with HTTPS over VPN tunnel

### ISSUE THREAD

**Issue by ILuvFreeSW** [FelisCatus/SwitchyOmega#468]
When using SwitchyOmega to point to a proxy at the other end of an SSL-VPN tunnel, all HTTPS pages cannot be loaded.

The setup is like this:
Chrome browser (with SwitchyOmega) --> OpenVPN tunnel --> Proxy server --> HTTPS web page

The above setup has no problem with loading HTTP pages.
The same setup is tested with SwitchySharp instead and there is no problem.
Tested configuring the Proxy server directly as System proxy and disabled SwitchyOmega in Chrome extension, no problem as well.
When using SwitchyOmega with a Proxy that is on the same side of the browser (ie. does not pass through the OpenVPN tunnel), no problem as well.

So I think the issue most probably is SwitchyOmega is unable to handle nested SSL encryption - HTTPS is SSL over OpenVPN tunnel which is also SSL.  It is disappointing though, that it's predecessor SwitchySharp can handle such scenario but the "upgraded" version can't.

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega works the same way as SwitchySharp when we are considering proxy access. They just pass the configuration to Chrome and Chrome does the actual network internals. Your experience was likely to be caused by wrong configuration in SwitchyOmega as far as I can tell.

Please provide a screenshot of the proxy profile if possible. You may mask or change the server address to protect your privacy.

In most cases, only the `(default)` row should be filled. If you filled in the server in the three rows below, try clearing them (by selecting `(use default)` for protocol) and move the server ip and port to the first row.

**Comment by ILuvFreeSW** [comment]
Thank you for your prompt reply.  Attached is the screenshot of the SwitchyOmega profile:
![image](https://cloud.githubusercontent.com/assets/12522008/7752281/25b8c604-0011-11e5-9d17-0b6ab558c202.png)

And the following is the same profile in SwitchySharp:
![image](https://cloud.githubusercontent.com/assets/12522008/7752293/40239a96-0011-11e5-96e9-706a4b535d25.png)

I note that both config is a bit different because the UI is different.
This is the only profile that I have separate config for different protocol because the FTP uses a different port.  My other profiles are all referenced to default for other protocols.

**Comment by FelisCatus** [comment]
In your case of SwitchySharp, I think it is really the SOCKS5 server that handles your request.

Please try changing the protocol to SOCKS5 in the first row in SwitchyOmega options and see if it works.

If things just don't work for you, you may always export a settings backup file from SwitchySharp and import it to SwitchyOmega for automatic settings migration. Let me know if that helps.

**Comment by ILuvFreeSW** [comment]
Just tried your suggestion, changed the default of the profile in SwitchyOmega to SOCKS5, and the rest of the protocol reference to it.  Unfortunately it still doesn't work.
I then tried importing the exported settings from SwitchySharp into SwitchyOmega, the automatic migration sets this profile to the same config as above so it doesn't work.

After some testing, I figured out to make HTTPS work across the SSL-VPN with SwitchyOmega, I have to default to HTTP and all protocol must reference to the default, ie. cannot have separate config for each protocol:
![image](https://cloud.githubusercontent.com/assets/12522008/7754192/2813746a-001d-11e5-9271-9635b6e07fca.png)

So now I'm curious if there's any program logic difference in the background between this working config and the first config I posted?  On the UI front, the only difference is the FTP port but as far as HTTPS is concerned they are the same.  So why does one works but the other doesn't?
With this "working" config, the issue now is I can't have a different port for FTP.

**Comment by FelisCatus** [comment]
Hey thanks! I can confirm this now. SwitchyOmega (as of 2.3.12) gets confused in this particular setting and clears the proxy settings for `https://` scheme for some reason. A bug fix is coming soon...

Thanks again for your effort and the detailed report.
----

P.S. Does your proxy server really offers FTP proxy on a different port (21)? If not, all `ftp://` requests should go through the HTTP proxy as well. The scheme (which is the beginning of the URL you visit) and protocol (the working mechanism for the proxy itself) should not be confused.

**Comment by FelisCatus** [comment]
Chrome does not like proxy settings with multiple schemes referencing the same proxy server, for whatever reason, and silently ignores the "https://" part (i.e. `proxyForHttps`) without raising a warning or error. Copying the server object however works like a charm.

This is not discovered previously due to the specialty of the particular type of setting. To trigger this problem, the default scheme must be set to an **HTTP** proxy server, while **one and only one** scheme such as `ftp://` must be set to something different. Also, the `ftp://` protocol is not often used and therefore no users have reported similar issues before. Besides, such bugs cannot be discovered using unit tests.

Anyway, a new release containing the fix will be published in 6 hours.

**Comment by FelisCatus** [comment]
Fixed in v2.3.13. Please update to the newest version and confirm the fix.

**Comment by ILuvFreeSW** [comment]
Hi FelisCatus, thank you for the prompt response.  No worries for the report, I'm glad I can contribute. :-)
As for using FTP proxy on a different port, my proxy does allow flexibility in assigning different port number for different protocol.  For ease of remembering, I used default FTP port (21) for active FTP.  But there is no problem in changing it to same port as HTTP as well.

Anyway thanks for coming up with a fix so fast.  I will test it in the next few days to confirm.

**Comment by ILuvFreeSW** [comment]
I have tested it. The HTTPS portion now works fine even with the separate scheme configuration as posted in my first mail.

Unfortunately once I attempt to access an FTP site through SwitchyOmega's proxy setting, Chrome will crash. However I need to qualify that this happens only when I separate the FTP proxy to a different port, if it is using default scheme there is no problem.
Therefore it is not definitive that the fix causes the crash, it may be due to my FTP proxy configuration.  For now, I think we don't need to spend more time to explore further as you pointed out that no other users will use this kind of configuration, so I'm fine to change my FTP proxy to the same port instead.  It is better to dedicate your time to other fixes.

Thanks for your effort in attempt to resolve this.

**Comment by FelisCatus** [comment]
@ILuvFreeSW Please just submit the crash report to Chromium issue tracker. This is not related to SwitchyOmega and can only be fixed in Chromium as far as I know. Besides, I didn't experience such crash during my testing, so upgrading your Chromium to the latest version might help.

**Comment by normanu** [comment]
Sorry for opening this item again, but I find the exact same is happening again in the latest version.
2.5.20

Tunnel works when setting HTTP as Default.
But when changing default to direct and setting proxy for http and https, it does not work.
