### ISSUE TITLE
【问题】不能准确的自动切换

### ISSUE THREAD

**Issue by huanggm** [FelisCatus/SwitchyOmega#469]
当我选择自动切换的时候，比如百度等国内网站应该是直接链接，但是打开很慢，甚至打不开页面，但是我调整到直接链接后，可以瞬间打开页面。对于国外网站也有相同问题。

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by seamus888888** [comment]
这个问题我也有,目前最好的解决方法是,在AUTOSWICHY中自己添加规则,比如BAIDU.COM,直接选择DIRECT

**Comment by FelisCatus** [comment]
自动切换并不是按照网络情况，只是按照原先设定的规则，或GFWList等有专人维护的规则列表而已。如果存在问题，建议到GFWList反馈。

然而，对于 @huanggm 的情况，我比较怀疑自动切换的“默认规则”设置成了代理情景模式而非直接连接。这种错误的配置会导致所有不匹配规则的网址（不需要代理的网址）也使用了代理情景模式，从而导致加载速度慢。请检查下设置，看看是否有这类问题。必要时，可以截图设置发到这里。

**Comment by aslanzala** [comment]
不知道这个问题如何jie解决，今天刚刚出现的，访问国内地址和bing的地址出现问题了
![default](https://cloud.githubusercontent.com/assets/6234644/8018505/dd5b75ee-0c51-11e5-856e-d2661cfb5b45.PNG)

**Comment by FelisCatus** [comment]
@aslanzala 这是明显的代理服务器问题或网络问题，与本项目无关，且与此主题原贴内容无关。
