### ISSUE TITLE
最近出现必须选择系统代理才能用

### ISSUE THREAD

**Issue by spidersq** [FelisCatus/SwitchyOmega#470]
之前一直是可以自动切换的，不知道为什么，最近只能使用系统代理选项，才能正常翻墙，自动切换基本瘫痪。

**Comment by syswow** [comment]
检查一下规则，把log贴上来看看。。

**Comment by seamus888888** [comment]
难道你不会在AUTO SWICHY中,添加规则吗?哪个站翻不出,就添加用GOAGENT规则,看没看软件的各个功能.

**Comment by FelisCatus** [comment]
自动切换并不是按照网络情况，只是按照原先设定的规则，或GFWList等有专人维护的规则列表而已。如果GFWList对于某些网站存在问题，建议到GFWList反馈。

----

@seamus888888 非常感谢您最近对于项目 issue tracker 的贡献，但也希望您在解答问题的同时，也能保持冷静和礼貌的态度。请尽量以讨论问题为主，避免过分的反问和对于提问者的质疑。以上是个人的一些建议，仅供参考。如有不妥之处，您可以随时与我讨论。

**Comment by spidersq** [comment]
啥都没改，现在又好了
