### ISSUE TITLE
有时候按钮显示不全

### ISSUE THREAD

**Issue by okletswin** [FelisCatus/SwitchyOmega#471]
经常选择了启动切换后, 最上边的3个元素不能显示
![image](https://cloud.githubusercontent.com/assets/4360404/7740807/8ca4ae36-ffa9-11e4-92e4-64215074a62b.png)
正确:
![image](https://cloud.githubusercontent.com/assets/4360404/7740827/b1ee11c8-ffa9-11e4-8a1a-07a7feb51ba2.png)

**Comment by FelisCatus** [comment]
见 #424
