### ISSUE TITLE
配置同步是个错误的设计

### ISSUE THREAD

**Issue by ragingfire35** [FelisCatus/SwitchyOmega#472]
打开两个独立的chrome页面a,b.a页面选择goagent代理，b页面自动选择一样的代理。这是程序员想当然的设计。实际我们用的时候是希望a页面使用goagent代理。b页面不适用代理。

   也可以设置个开关，可以选择同步或者不通知选项配置。

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36

**Comment by seamus888888** [comment]
你自己不会用,不要喷,看懂说明书没,什么时候同步的说明是,同一个设备之间是不会同步的?

Your options are automatically synchronized with your other devices.

**Comment by ragingfire35** [comment]
你按我描述的尝试一下就好了。你真有尝试么？




在 2015-05-21 14:17:39，"seamus888888" <notifications@github.com> 写道：


你自己不会用,不要喷,看懂说明书没,什么时候同步的说明是,同一个设备之间是不会同步的?

Your options are automatically synchronized with your other devices.

**Comment by seamus888888** [comment]
所以我说,你把我最后一句,关于同步的英文翻译成中文是什么意思.你就懂,为什么你这样操作是会同步的.我发现不仅英文看不懂,中文你也不懂.

**Comment by ragingfire35** [comment]
同一个设备也会。你是这个程序的作者？看来你真的很适合做一个码农。

**Comment by ragingfire35** [comment]
你自己没看懂我描述的问题罢了。码农通常都这样。我不会怪你的。

**Comment by ragingfire35** [comment]
建议你聘请个客服吧。

**Comment by seamus888888** [comment]
我也不会怪你的

**Comment by ragingfire35** [comment]
问题是你真的同一个Pc上打开两个chorme页面了么？,a页面选中goagent,b页面自动也就切换过去了。这样的场景，我觉得不好。

**Comment by ragingfire35** [comment]
给你建议，你还瞎bb.啥素质。

**Comment by FelisCatus** [comment]
@ragingfire35 @seamus888888 停止无意义的争吵可以吗？我觉得双方对于这个 issue 的描述理解产生了一些误会。

先声明， @seamus888888 并非这个项目的参与者。这里任何人都可以发言的，但请务必保持冷静和互相尊重。本人作为项目拥有者（评论右上角的`Owner`），对于 @ragingfire35 的建议以及 @seamus888888 的参与讨论，都是欢迎的，不会排斥。

言归正传， @ragingfire35 的意思是“每个标签页使用不同的代理”，和所谓的“配置同步”（一台设备上更改选项，会反映到另一台设备上）并不是同一个概念。 @seamus888888 显然误解了这一点。这个只是简单的理解问题，何必互相指责，甚至上升到人身攻击。

然而这个问题由于PAC限制，实际上技术上是不可实现的，所以也自然就没有这么设计。 @ragingfire35 如果觉得比较难理解的话，可以适当了解下 SwitchyOmega 只是设置工具，具体网络和底层操作都需要交给 Chrome 完成。尽管我已经尽力让配置灵活了，但有些做不到的事情终究还是做不到。

注意关闭问题只是表示该问题已经解决，并非关闭评论。如果还有任何技术或其他问题，仍然可以继续讨论，但如果要继续争吵的话，我个人还是建议不要了。
