### ISSUE TITLE
自动切换 无法连接

### ISSUE THREAD

**Issue by letterk** [FelisCatus/SwitchyOmega#473]
直接连接和直接代理均可正常连接

使用自动切换，一切都无法连接

SwitchySharp正常

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

**Comment by letterk** [comment]
附：pac文件
https://gist.github.com/letterk/b8f883395ed52a69e846

**Comment by FelisCatus** [comment]
请清除自动切换中关于`crossdomain`的规则然后再试一次。感觉是正则表达式语法错误，或者规则的类型错误地选择了“通配符”而非“正则表达式”。

**Comment by letterk** [comment]
还真是crossdomain这条规则影响了

在SwitchySharp里确实是通配符
这条规则是一个优酷去广告扩展

**Comment by letterk** [comment]
解决了，重新写了下这条规则为正则就OK了

**Comment by FelisCatus** [comment]
虽然问题解决了，不过感觉比较奇怪……我还是去检查下正则转义相关的内容好了。

**Comment by FelisCatus** [comment]
在SO里补充增加了`\`的转义。这样的话选错规则类型至少不会整个挂掉了，只会规则无效而已。

**Comment by FelisCatus** [comment]
v2.3.13 已经避免了由于正则未转义的错误导致整个PAC崩溃的情况。
