### ISSUE TITLE
127.0.0.1资源未加载

### ISSUE THREAD

**Issue by HeartUnchange** [FelisCatus/SwitchyOmega#474]
总会显示127.0.0.1部分资源没有加载,在proxy中设置了黑名单<local>,难道还有别的设置?

SwitchyOmega 2.3.12
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Comment by FelisCatus** [comment]
127.0.0.1 设置黑名单？也就是说 127.0.0.1 走代理吗？如果是这样的话，似乎不太对，因为 127.0.0.1 本机地址应该不经过代理，否则就是访问代理本机了。

此外，如果访问很多正常页面都这样，会不会是一些去广告扩展把请求重定向到 127.0.0.1 ，或者别的扩展在页面中插入了一些资源请求？

**Comment by HeartUnchange** [comment]
多谢提醒,估计是安装了Adblock的缘故吧,可我在不代理的地址列表添加了<local>,这个不应该可以屏蔽掉127.0.0.1这个内部地址吗?

**Comment by FelisCatus** [comment]
感觉是误判，求网络请求日志……可以打开 F12 的 Network 选项卡，然后刷新下页面，在左上角过滤器中输入 127.0.0.1，然后看看有什么请求。可以把结果截图、导出或者告知实际访问的URL。

**Comment by HeartUnchange** [comment]
![default](https://cloud.githubusercontent.com/assets/8402502/7770838/fdab69a0-00c4-11e5-8e69-fd494fc9b08f.PNG)
![2](https://cloud.githubusercontent.com/assets/8402502/7770840/031751f6-00c5-11e5-9138-d40b466bb9d0.PNG)
![3](https://cloud.githubusercontent.com/assets/8402502/7770842/06d2bd1c-00c5-11e5-92cf-142f7715e3da.PNG)
你看一下这几张能反映问题不,这个现象只出现在观看视频时,模式是auto switch,<br>最后一张是意外收获,就截了图

**Comment by FelisCatus** [comment]
已经确认目标URL。请问都安装了哪些去广告的扩展？除了AdBlock，是不是还有一些专门屏蔽视频网站或者Flash广告的扩展呢？

**Comment by FelisCatus** [comment]
暂时先移除了所有URL包含`://127.0.0.1`的资源未加载报告。如果注意到其他情况或者和去广告有关的误判，请直接留言。

**Comment by FelisCatus** [comment]
v2.3.13 已经忽略`://127.0.0.1`。
