### ISSUE TITLE
其他应用正在控制代理设置。请禁用或者卸载发生冲突的应用。

### ISSUE THREAD

**Issue by vvyoko** [FelisCatus/SwitchyOmega#475]
出现这个提示该怎么办？
我知道是视频广告屏蔽扩展造成的。
现在只能在看视频的时候开启广告过滤扩展，不看的时候关了。
但是这样很不舒服。

按理说广告过滤扩展是顶多是针对部分网址改变代理并不是全局的啊。
switchyomega不能在这种模式下工作吗？
还是这个问题我应该去广告过滤扩展那边反应吗？

顺便问一下多个规则列表的功能是怎么使用的？
我记得好像有这个功能吧，但是一直没找到怎么使用。

**Comment by huanggm** [comment]
好像是浏览器只支持一个代理插件，而不能做到根据网址来切换代理插件。具体可以在设置中查看当前的代理插件是什么，比如：
![default](https://cloud.githubusercontent.com/assets/4965664/7762347/cde0de8a-0065-11e5-9e82-81196bdd1f77.jpg)
然后禁用该插件，启用另一个代理插件。或者删除该插件，启用另一个插件之后，再安装该插件。
不确定对不对，印象中好像是这样的。

**Comment by FelisCatus** [comment]
Chrome 只允许一个扩展控制代理设置，即使部分网页不使用代理，也是进行了设置。不建议在去广告扩展那边反映此问题，因为这个问题并非单独的扩展可以解决的，需要两边进行合作。

关于此问题，有一个[不太完美的解决办法](https://github.com/FelisCatus/SwitchyOmega/issues/44#issuecomment-77325575)。
