### ISSUE TITLE
doesn't work for google translate

### ISSUE THREAD

**Issue by Zane-XY** [FelisCatus/SwitchyOmega#476]
after using the proxy, I can visit https://translate.google.com/, but the browser embedded google translate still doesn't work.

![screen shot 2015-05-22 at 11 11 08 am](https://cloud.githubusercontent.com/assets/2939476/7763917/c41e594e-007a-11e5-9cc0-d07ebda5f5b4.png)

SwitchyOmega 2.3.12
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Comment by okletswin** [comment]
you shoud add *.googleapis.com

**Comment by FelisCatus** [comment]
First, try selecting the proxy profile directly in the popup menu. This would apply the proxy for all web requests. If translation works in this case, you should add all relevant requests(*) to the Switch Profile you prefer. If not, this is likely to be a problem with your proxy server or network.

(*) Relevant requests may include `*.googleapis.com` as pointed out by @okletswin.
