### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by VeeCN** [FelisCatus/SwitchyOmega#478]
显示乱码

SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
……如果是浏览网页乱码，大概是代理服务器问题吧。

如果是说选项页面出现类似`{{xxx}}`的文字，则是选项页面脚本错误。这种情况下，请打开F12开发者工具，刷新页面后，将Console(控制台)选项卡出现的内容复制到这里。

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
