### ISSUE TITLE
我终于知道我的为什么经常性 ”自动却换“模式无法连接了，任何网站都不能上了。得直接连接才可以上网了

### ISSUE THREAD

**Issue by heartacker** [FelisCatus/SwitchyOmega#479]
首先。我们学校是需要认真的。所以。一开机得登录学校的认认证才可以上网。

所以这因为这个原因。导致某些情景模式的配置文件无法更新。

从而导致无法上网。只能却换到直接连接。。
这个时候，我登录了认证系统之后。我就更新一下那个情景模式的配置文件。然后改为自动却换就可以上网了
我觉得是这个文件没有及时更新导致无法上网的缘故。
看图。http://ww4.sinaimg.cn/large/be428b90gw1esgvxya5hej20ww0dsadb.jpg 只要我更新了。然后却换到自动却换就可以上网楽。请问这个是啥问题啊 。谢谢支持。

**Comment by FelisCatus** [comment]
如果你们上网确实是需要那个PAC文件的话，在成功更新一次后，直接清空PAC**网址**并保存。这样一来，那个PAC脚本的内容就会储存在本地，不再需要更新，也不会受到认证系统干扰了。

如果不需要那个PAC，请在“自动切换”中清除所有`zpn`情景模式的引用，而改为自动连接或其他合适的代理服务器（如果需要的话）。
