### ISSUE TITLE
Omega如何在访问某网站失败报告网络有问题时保留添加临时规则的选项？

### ISSUE THREAD

**Issue by ctexlive** [FelisCatus/SwitchyOmega#480]
Omega对正在尝试打开的网站，或者已经正常打开的网站页面，菜单项可以显示添加规则或者临时规则选项。
但对于某些网站已经尝试打开失败，浏览器报告“您的网络好像有问题”等错误时，添加规则的菜单项就消失了。如图。事实上这种情况经常发生，因为有时omega的自动切换不工作（网站本身已经在gfwlist表中，但繁忙时有一定的失败概率），或者这个网站还没被列入代理的情景模式中时，访问失败，需要临时添加规则就没办法了，只能选全局代理模式。
![omega](https://cloud.githubusercontent.com/assets/8100859/7799408/4a11b45a-0338-11e5-9cc2-50162bb7b606.png)
![omega2](https://cloud.githubusercontent.com/assets/8100859/7799410/5228032e-0338-11e5-9823-18eb6a07215a.png)

当按浏览器刷新，在浏览器还在尝试连接过程时就会出现添加规则选项。浏览器尝试连接到失败过程很短，因此需要眼疾手快才能赶在结束之前添加临时规则。挺头疼。希望能持续保存增加规则列表或者提供一个快捷键也行。
![omega3](https://cloud.githubusercontent.com/assets/8100859/7799437/a3e21790-0338-11e5-937c-680a20e75ff5.png)

**Comment by FelisCatus** [comment]
见 #365. 好像 360 浏览器确实有这个问题，加载失败时会跳转到其他网页，这让我很难办……
