### ISSUE TITLE
自动切换模式下默认规则失效

### ISSUE THREAD

**Issue by zhfreal** [FelisCatus/SwitchyOmega#481]
自动切换模式下，未加入规则的域名应该走默认规则，但这可能会失效，然后提示资源未加载。

这个问题不是经常出现和必然出现，但一天还是会出现几次。

SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by zhfreal** [comment]
看了下浏览器的资源加载情况，发现SwitchyOmega提示   ”资源未加载， 你可以检查以下域名。。。“   这个提示有问题，让人很困惑。对加载失败资源提示应该检查的域名，不是该失败资源对应的域名。

**Comment by FelisCatus** [comment]
这应该是网络问题，SO只能检测该资源不能正常加载，但并没有办法判断出究竟是应该添加规则，还是只是单纯的网络错误。

**Comment by zhfreal** [comment]
已经明白这个功能的含义。只是发现SO提示资源未加载的host与chrome本身提示资源加载失败的信息不太符合，反正经常对不上。只好关了这个提示
