### ISSUE TITLE
域名通配符在“自动切换”模式下使用无效

### ISSUE THREAD

**Issue by grcpeng** [FelisCatus/SwitchyOmega#482]
在“自动切换”模式下添加了“域名通配符*.cloudera.com”后，打开含有这个域名通配符的网址`http://community.cloudera.com/?device-view=desktop`，页面是显示不全的。但是如果直接切换到“GoAgent”模式后打开这个网址就不会出现网页显示不全的情况。

SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Comment by FelisCatus** [comment]
这里需要注意一个网页会含有很多资源，而这些资源未必是`*.cloudera.com`都能匹配的。请检查弹出菜单中提示的“未加载资源”项目，并且将合适的内容一键添加到规则中。
