### ISSUE TITLE
太卡了

### ISSUE THREAD

**Issue by francisfly** [FelisCatus/SwitchyOmega#486]
SwitchyOmega 2.3.13
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by FelisCatus** [comment]
希望能够详细说明。是哪里卡了？

* 界面上：下拉菜单的弹出速度？在下拉菜单选择项目后的反应速度？选项页面的加载速度？或者编辑自动切换的时候？
* 行为上：使用自动切换模式时，第一次加载网页前的“处理PAC脚本”所需时间？每个网页加载所需的时间？图标颜色改变需要的时间？

希望能详细说明具体的场景，以及大概的延迟时间。如果和设置有关的话，还请附上设置备份文件，以便分析性能。谢谢！

**Comment by xinhugo** [comment]
如果是规则较多导致卡，「编辑源代码」模式下编辑，就没什么感觉了。

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
