### ISSUE TITLE
facebook

### ISSUE THREAD

**Issue by Mirati** [FelisCatus/SwitchyOmega#487]
SwitchyOmega 2.3.13
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by FelisCatus** [comment]
?

**Comment by FelisCatus** [comment]
I'm closing this now because it seems to be abandoned. Please reopen if you have more details.
