### ISSUE TITLE
在猎豹浏览器的隐私模式下，无法使用

### ISSUE THREAD

**Issue by ljycrystal** [FelisCatus/SwitchyOmega#488]
版本2.3.14为止
1. 如果是原sharp版本的自动切换模式下，直连网页正常打开，但是在需要代理的页面下，则无法请求到页面。如果是直接选择代理模式，则正常
2. 在Omega版本中，在问题如 http://bbs.liebao.cn/thread-311565-1-1.html 的描述。无论是在自动切换还是代理直接模式都一样，所有任何页面都无法打开

**Comment by FelisCatus** [comment]
这大概是猎豹浏览器的bug吧……
而且这个错误页面上具体的错误消息都没有，谁知道是什么问题呢……如果是网络或者代理设置问题，应该会有明显的报错才对。也许是猎豹浏览器崩溃了也说不定？

**Comment by ljycrystal** [comment]
呃，那是无解了？

**Comment by FelisCatus** [comment]
@ljycrystal 不是我这边的bug你打算叫我怎么办……反汇编猎豹浏览器、调试出这个bug，然后再给个修复补丁么？ :smile_cat:

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
