### ISSUE TITLE
我两台电脑的 chrome 如何保持配置同步

### ISSUE THREAD

**Issue by bugyak** [FelisCatus/SwitchyOmega#489]
一台电脑里有外部情景模式
一台电脑里却没有……

**Comment by FelisCatus** [comment]
外部情景模式是当前浏览器中，其他扩展提供的代理设置，所以只在当前浏览器中可用。如果只是需要将控制权交给其他扩展，那么选择“系统代理”即可。
如果希望将外部情景模式保存到SwitchyOmega中使用，则可以点击此菜单项并且为情景模式取名后保存。保存后可以配置同步。
