### ISSUE TITLE
选情景模式的列表经常显示不完整

### ISSUE THREAD

**Issue by TimonLio** [FelisCatus/SwitchyOmega#490]
从直接连接状态点扩展图标展开情景模式的列表超过一半的概率，看不到直接连接的情景模式行
从有代理状态点扩展图标展开列表，想切换回直接连接状态，超过一半的概率，看不到直接连接和系统代理的选项行，只能不停重试只到能看到直接连接的选项以后，才能切得回去

SwitchyOmega 2.3.14
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Comment by FelisCatus** [comment]
见 #424.
