### ISSUE TITLE
CAN NOT USE.

### ISSUE THREAD

**Issue by edwardelric1** [FelisCatus/SwitchyOmega#492]
SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

**Comment by FelisCatus** [comment]
What's the problem?

**Comment by xinhugo** [comment]
@FelisCatus 你是不是遇到机器人了，类似的 Issue 我看到不止一个了。

例如：
https://github.com/FelisCatus/SwitchyOmega/issues/487
https://github.com/FelisCatus/SwitchyOmega/issues/378

**Comment by FelisCatus** [comment]
@xinhugo 右键图标点击反馈问题，就会自动打开Github并生成以下模版（见下方源代码）。如果用户懒得填写问题/建议详情，然后标题再乱填点内容（因为是必填嘛），提交就会变成这种 issue 。

```markdown

<!-- ↑请在此行上方填写问题/建议详情，可用中文↑ -->
SwitchyOmega 2.3.11
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36
```

**Comment by celeron533** [comment]
我觉得提交issue的时候直接跳到github的issue tracker主页就行了，后续操作让用户自己完成，这样有助于排除乱提问题的。

**Comment by FelisCatus** [comment]
@celeron533 :+1:

**Comment by celeron533** [comment]
最近似乎由迅雷引起的问题比较多，导致双方都不能很高效的利用业余时间
我后来又考虑了一下，把‘report issues’菜单跳转到这边的中英文FAQ页面，并在该页面最下方带上github issue tracker链接比较好吧

**Comment by FelisCatus** [comment]
@celeron533 我觉得这个确实要商量一下，最好能跳转到自己设计的页面。那个页面中可以包含一些常见的FAQ内容，并且引导用户描述问题。如果用户选择提交，再附上必要的版本号和浏览器等信息提交到 Github 这里比较好。
那个页面完全可以是静态页面，用 Github pages 就足够，不必担心服务器支出或者稳定性。当然，制作那个页面是需要一定的时间成本的，但我觉得这个是值得的。

可能的问题是： Github pages 会不会被墙？

**Comment by celeron533** [comment]
@FelisCatus 
FAQ的问题我开了个新的ticket， #584
