### ISSUE TITLE
DNS Leak with SOCKS5 Proxy

### ISSUE THREAD

**Issue by mgoku** [FelisCatus/SwitchyOmega#494]
I use SwitcyOmega to connect to SOCKS5 proxy.

When I check my IP via http://ipleak.net/, I found that my ISP DNS is leaked. My connection still using my ISP DNS rather than the SOCKS5 server DNS.

**Comment by simonsww** [comment]
The reason is that you didn't choose the "always require option"

**Comment by FelisCatus** [comment]
I [documented about this in the project wiki](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy), with steps to avoid DNS request leaking. Please refer to that page if you are interested in this topic.
