### ISSUE TITLE
SwitchyOmega中的添加规则是否是临时？

### ISSUE THREAD

**Issue by viewfirst** [FelisCatus/SwitchyOmega#496]
针对当前网站的单独代理模式设置是临时性还是永久性？

**Comment by FelisCatus** [comment]
加号图标的那个添加规则（或“未加载资源”中的添加功能）会将规则加入到自动切换情景模式中的最上方，可以直接前往选项界面确认。

然而，带有漏斗图标以及当前域名的那个菜单项只是临时规则，不会更改选项，重启后自然失效。
