### ISSUE TITLE
系统代理选项，无法翻墙

### ISSUE THREAD

**Issue by 5points** [FelisCatus/SwitchyOmega#498]
我打开shadowsocks，然后插件选择系统代理，则无法翻墙。以前都可以，现在则不行

SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by FelisCatus** [comment]
“系统代理”是使用当前操作系统的代理设置（如IE浏览器的代理服务器选项）。如果需要设置代理请新建代理情景模式。
