### ISSUE TITLE
太慢了.还有好多错误

### ISSUE THREAD

**Issue by ugksoft** [FelisCatus/SwitchyOmega#499]
1.整体太慢了,比老版来说, 你不应该用这种花稍的界面来弄的,所以其它很多地方都慢
2.工具栏菜单弹出一直很慢,你以前说没找到原因,这么久了,还没找到原因?
3.打开代理插件后,Chrome启动慢几个数量级!!!!!
4.很多时候,在下角会提示"正在解析主机...",但ping,是正常的, 或是刚刚打开了这网页,没关chrome,只是关了标签页,重新打开,就提示解析主机  关掉代理插件后,恢复正常
5.很多时候,dns指向问题,一些非常正常,不需要代理的网站,比如mydrivers.com,会"网络复位"错误, 只能切换到强制代理,打开一下,再恢复到自动模式,这时,网站才正常访问(感觉像是内部DNS混乱)

**Comment by FelisCatus** [comment]
您好，问题1、2 您之前都已经[反馈过一次](https://github.com/FelisCatus/SwitchyOmega/issues/353)了，我这边已经非常努力在解决了。
3、 4 是由于 Chrome 的设计，第一次加载PAC脚本存在编译和执行的过程。此处花费的时间和系统及硬件相关，可能会出现明显延迟。
5 是网络问题或代理服务器问题，和 SwitchyOmega 无关。再次说明本项目不做网络细节，不涉及DNS，只是把代理设置交给 Chrome 去处理而已。

此项目是非盈利项目，目前主要贡献者只有一人。我平时需要处理学业和工作上的问题，只能利用空余时间无偿地来为此项目工作。（此项目无任何广告等收入来源，也暂时不接受捐款。）当下正在忙于期末考试复习，如果更新速度较慢还请您理解。此项目完全开源，如果您希望协助，可以参与此项目或推荐其他人加入，共同改进，争取早日满足您的需求。

您正在使用的这个 Issue Tracker 是一个致力于解决问题的、类似论坛的功能，每个人都可以参与讨论和贡献意见。请注意您此时此刻现在正在和开发者、项目其他贡献者以及软件其他用户进行直接交流。——这不同于“用户反馈”功能，没有“客服”会来耐心地为您解答问题。而此 Issue Tracker 目前也大部分是我在维护，每个 issue 我都会仔细回复，并表明分类、如何处理和预计版本号。因此，请避免单纯的抱怨和重复发贴，避免将开发者的精力过多牵涉到这方面来。谢谢您的理解和合作。

**Comment by FrankFang** [comment]
请注意态度。作者没逼着你用，你自己要用，你又没付费，所以，爱用用，不爱就卸载，自己 folk 写一个。

**Comment by ayanamist** [comment]
免费软件就是爱用就用，不爽就滚。没谁用枪指着你非用不可。作者也不欠你任何东西。

**Comment by Snger** [comment]
> "您正在使用的这个 Issue Tracker 是一个致力于解决问题的、类似论坛的功能，每个人都可以参与讨论和贡献意见。请注意您此时此刻现在正在和开发者、项目其他贡献者以及软件其他用户进行直接交流。——这不同于“用户反馈”功能，没有“客服”会来耐心地为您解答问题。而此 Issue Tracker 目前也大部分是我在维护，每个 issue 我都会仔细回复，并表明分类、如何处理和预计版本号。因此，请避免单纯的抱怨和重复发贴，避免将开发者的精力过多牵扯到这方面来。谢谢您的理解和合作。"

支持

**Comment by ugksoft** [comment]
我说态度,你们的态度如何, 同是开发人员,只是方向不同,  实事求是,实话实说, 再说我的话里,没有恶意内容,你们心态问题


关于第5点,绝对不是代理问题,  因为我用bitvise ssh client,可以看到他是否访问了代理,再说我说的很明白,chrome似乎用了一个错误的IP去访问网站,,所以才出现网络复位提示,我不知道这是代理软件问题,还是chrome的bug ,

新增:
代理是否能控制, 比如当代理不能访问(爬墙不稳定,没连上),不让chrome使用历史内容显示(通常显示的非常不完整,ccs,js之类的也丢了,omega提示一堆的代理未成功数字),而是显示代理错误,或是空白不能访问的页面

**Comment by nxtreaming** [comment]
@ugksoft 不要在意上面一些所谓的卫道士们的所批评的态度问题，有错误或者反映慢说明原作者能力或者时间投入上有问题，既然是问题就应该允许别人提出来，总比假装没有问题好。

**Comment by ayanamist** [comment]
楼上两位，我有一个讨债的工作，不知两位是否感兴趣？这种天生一副全世界都欠你的态度，不用来讨债太浪费了。

**Comment by nxtreaming** [comment]
楼上朋友，你根本不明白我说的话的意思，智商低是硬伤啊。

**Comment by FelisCatus** [comment]
@ugksoft 非常感谢您提供进一步的信息。由于您在使用 SOCKS 代理，可以参考[此页面关于 SOCKS 和 DNS 的说明](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy)的中文部分。

如果关闭 DNS Prefetch 后您仍然观察到 DNS 不正常，建议您在 Chrome 中打开 `chrome://net-internals/#events&q=type:HOST_RESOLVER_IMPL_JOB%20is:active` 这个页面，查看关于 DNS 请求的详细信息。

P.S. 回应“新增”部分：此行为不可控。

**Comment by ugksoft** [comment]
发现,当chrome莫名其妙提示"正在解析主机..."时,在net-internals中的dns表,是空白的,明明几秒种前访问了很多网站,chrome也没重开,不可能空白

至于你说的查看网络事件, 我下次遇到同样问题时,去事件时检查一下,有进一步消息,一定贴出来
 ,随机出事的问题,不能想找就找不到, 有时一天遇到好多次,有时几天不出现,

**Comment by ugksoft** [comment]
先报一下dns解析主机时卡着问题

发现随机域名,而实际网页中没有这样的域名存在

ID	Source Type	Description
	8183	URL_REQUEST	http://qilajuule/
	8184	HTTP_STREAM_JOB	
	8185	CONNECT_JOB	
	8187	HOST_RESOLVER_IMPL_JOB	
	8189	URL_REQUEST	http://qvfrgjzqnbaho/
	8190	HTTP_STREAM_JOB	
	8191	CONNECT_JOB	
	8192	HOST_RESOLVER_IMPL_JOB	
	8194	URL_REQUEST	http://lbghbnvw/

**Comment by FelisCatus** [comment]
@ugksoft 那么应该和 SO 无关了……

**Comment by ugksoft** [comment]
终于有RESET了, 帮我看看是什么原因 ,
防止的是mydrivers.com,是可能被gfw复位的,但事实却真是被复位了
在chrome://net-internals中,先停止Capture,然后,在import中,把这个文件导入,就可以看到了

你可以搜索一下"RESET"

http://pan.baidu.com/s/1i33XCUx  密码 d7im

**Comment by ugksoft** [comment]
防止的->防问的

**Comment by ugksoft** [comment]
终于有RESET了, 帮我看看是什么原因 ,
防问的是mydrivers.com,是不可能被gfw复位的,但事实却真是被复位了
在chrome://net-internals中,先停止Capture,然后,在import中,把这个文件导入,就可以看到了

你可以搜索一下"RESET"

http://pan.baidu.com/s/1i33XCUx 密码 d7im
