### ISSUE TITLE
「编辑源代码」方框自动伸缩导致难以编辑

### ISSUE THREAD

**Issue by xinhugo** [FelisCatus/SwitchyOmega#500]
「编辑源代码」模式下：
未选择任何规则时，「编辑源代码」方框是长方形。
一旦选择规则，「编辑源代码」方框将会自动变宽。

如此，CTRL + F 定位规则，将变得不准确。
此问题，影响部分规则，可能与长度有关。

**Comment by FelisCatus** [comment]
之前 v2.3.8 更新加入：点击任何源代码输入文本框后，均会自动加宽。
（此外， Chrome 还提供了一个手动调整文本框大小的方式：拖动文本框右下角。）

现在其实我有点后悔加这种功能了。正如 @xinhugo 所说，用起来可能实际上不是那么方便。
还有就是一行源代码究竟能有多长的问题……由于我自己不怎么用些很长的规则，所以不是很了解。能不能给个源代码编辑的截图呢？（可以涂黑部分代码来保护隐私。）

可能的解决方案：

1. 取消此特性。这样 Ctrl-F 什么的估计能正常用了，而且也不会有太多惊喜了。
2. 保留此特性，但取消平时（未选中）状态下的自动折行。这样无论宽度如何，一行的代码始终会显示成一行，不会导致高度变化。
  * 优点：聚焦后，编辑较长的代码会比较友好。
  * 缺点：会导致未选中时，一行的内容显示不全。

**Comment by xinhugo** [comment]
取消此特性，但扩大固定宽度如何？

我的代理规则，都是公开的，不用打码。
备份：https://raw.githubusercontent.com/xinhugo/Free-List/master/SourceOmegaOptions.bak
其中一个规则列表：https://github.com/xinhugo/Free-List/blob/master/OmegaRules_List_GFW.sorl

一般较长的是正则表达式。

**Comment by FelisCatus** [comment]
想了很久，感觉确实，扩大固定宽度吧……

**Comment by xinhugo** [comment]
感谢

**Comment by FelisCatus** [comment]
v2.3.16 已经修复，更新已经发布。
