### ISSUE TITLE
“老兄，网页崩溃了”的元凶

### ISSUE THREAD

**Issue by juking** [FelisCatus/SwitchyOmega#501]
终于找到了，“老兄，网页崩溃了”的元凶
把这个装上，大约60%的几率新打开的标签页会崩溃，卸了就完全好了
SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2383.0 Safari/537.36

**Comment by FelisCatus** [comment]
崩溃为  Chrome 问题，建议直接去提交反馈报告。此外，也可以尝试使用 Beta 版 Chrome ，看看是否仍然出错。
