### ISSUE TITLE
莫名其妙会切换到外部情景模式

### ISSUE THREAD

**Issue by letterk** [FelisCatus/SwitchyOmega#502]
初始情景设置的自动切换

SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
请检查可能冲突的扩展，如其他代理设置扩展或去广告等使用PAC的扩展。
