### ISSUE TITLE
[Bug report] 给 localhost 设置代理规则不起作用

### ISSUE THREAD

**Issue by foobarjohnny** [FelisCatus/SwitchyOmega#503]
给 localhost 设置代理规则不起作用, 例如代理到 Fiddler.

**Comment by FelisCatus** [comment]
请确认对应的代理情景模式中，“不代理的地址列表”中无`<local>`或`localhost`。

**Comment by foobarjohnny** [comment]
是的, 如你所说, 把 <localhost> 删了就好了. 谢谢
