### ISSUE TITLE
存在严重的内存溢出，占用400M左右的内存也太夸张了吧，能尽快修复吗？

### ISSUE THREAD

**Issue by Chen0719** [FelisCatus/SwitchyOmega#504]
SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by FelisCatus** [comment]
首先，似乎是第一次遇到这种情况……正常来说应该占用内存在 10M 以下。

要帮助修复此问题，请先观察一下有没有特别的现象发生，比如请求计数器数量非常大（几千以上？），或者其他可能与错误有关的情况。

然后，在Chrome中打开`chrome://extensions/?id=padekgcemlokbadohgkifijomclgjgif`，右上角勾选"开发者模式"，然后再点击 SwitchyOmega 扩展下的 background.html ，打开开发者工具。弹出窗口的Profiles选项卡中，可以选中第二项 Take Heap Snapshot ，并点击 Take Snapshot. 此时左侧栏会多出一个 snapshot 项目，内含当时的内存使用情况。请将此项目右键保存，然后上传到网上供开发者分析问题，（记得贴一个链接过来）。

**Comment by nxtreaming** [comment]
这个扩展如此脆弱，大家都为什么用？ 为什么不自己用JS写一个简单的PAC文件来翻墙呢？这样比这个扩展方便太多了。

2015-06-14 22:21 GMT+08:00 FelisCatus <notifications@github.com>:

> 首先，似乎是第一次遇到这种情况……正常来说应该占用内存在 10M 以下。
>
> 要帮助修复此问题，请先观察一下有没有特别的现象发生，比如请求计数器数量非常大（几千以上？），或者其他可能与错误有关的情况。
>
> 然后，在Chrome中打开chrome://extensions/?id=padekgcemlokbadohgkifijomclgjgif，右上角勾选"开发者模式"，然后再点击
> SwitchyOmega 扩展下的 background.html ，打开开发者工具。弹出窗口的Profiles选项卡中，可以选中第二项 Take
> Heap Snapshot ，并点击 Take Snapshot. 此时左侧栏会多出一个 snapshot
> 项目，内含当时的内存使用情况。请将此项目右键保存，然后上传到网上供开发者分析问题，（记得贴一个链接过来）。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FelisCatus/SwitchyOmega/issues/504#issuecomment-111830527>
> .
>



-- 
-----------------------------------------------------
Founder of http://LiveKings.com

**Comment by FelisCatus** [comment]
@nxtreaming 这个 issue 讨论的情况，至今还没有其他用户反映遇到过，而且还没有查明原因，现在下结论是否为时过早呢？

P.S. 是的，自己写一个 PAC 文件完全可行。不过就这个 issue 来说，还是讨论和主题相关的内容比较好。希望大家可以积极帮助OP、也帮助本项目解决问题。

**Comment by Chen0719** [comment]
@nxtreaming 只是反映一下自己遇到的问题，你这是在喷吗？说自己写一个那什么东西，首先我得会写才行吧，小白哪懂那么多。再一个，最初确实是以此扩展来配合GoAgent翻墙才用的它，可这个扩展终归是个代理管理工具，现在更多是用它来配置一些代理IP，对于翻墙GoAgent早已不是第一选择，所以更看重的是它的界面美观度和使用便捷性。

**Comment by Chen0719** [comment]
@FelisCatus 嗯 好的，只那么一次，下次遇到就按照你说的办。目前比较正常，内存占用30M左右，高的时候60M左右。可能是因为昨天开的网页太多，使用代理的页面也比较多，还启用了“当更改情景模式时刷新当前标签”发现后就关掉了，况且当时Chrome也运行了很长时间，Chrome自身内存溢出更严重。当时看到一个扩展内存占用400M多确实吓一跳，商店里的评论也有人反映扩展内存溢出，以为是扩展的问题，才过来反映情况的，行文是带着情绪的，可能太过武断。因为之前还一直在用Sharp，去年Omega刚出不太喜欢它的选项页面，所以装上之后一直处于停用状态，现在有点厌倦了Sharp图标风格，感觉Omega更漂亮一些昨天才决定换的，还发现“系统代理”项有效了，从此就可以很方便地和其他代理工具混用了。

**Comment by FelisCatus** [comment]
@Chen0719 无须道歉。为了做出一个好的产品，用户的意见是非常必要的。而且正如之前所说，此处讨论的目的也是帮助您，同时也是帮助本项目和其他用户解决问题。任何能帮助解决问题的讨论都是应当感谢的。

之前也发生过类似的内存泄漏问题( #383 )，也是在持续开启几小时后才发现的，而且其实泄漏的地点在 Chrome 的代码中……当时正是由于提供了这种导出的 Heap 记录，才能发现并修复那么隐蔽的内存问题。您的情况虽然我还不清楚是怎么回事，但我坦率地承认，如今的很多软件都或多或少存在内存泄漏问题，无论是 Chrome 还是 SwitchyOmega 都无法绝对避免，而您遇到的情况肯定是两者中的其一。

此外，我个人感觉“当更改情景模式时刷新当前标签”此选项并不会导致严重资源占用（只在更改情景模式时会有开销），但在没有 Heap Dump 的情况下我也不能下定论。

如果问题不再出现，自然最好。但如果您希望重现此bug并提交给 Chrome 或 SwitchyOmega 修复的话，可以找个合适的时间开着 Chrome 几小时（期间您可以去吃饭、休息等），回来再导出下 Heap 就好。当然，您也可以打开同一个开发者工具中的 Record Heap Allocations 选项再走，这个会记录内存分配随时间的变化，可以帮助有效地发现这几小时中究竟发生了什么。

**Comment by ACsediment** [comment]
通过chrome自带的任务管理器观察，我正常使用的时候（比如重启扩展后仅仅打开Github到这里）内存在40M左右，每次popup出现的时候会有一次1.5秒左右的卡顿，CPU占用25%（我是双核四线程的U），然后内存达到50M。过段时间慢慢下降到35-40M。

在请求比较复杂的网站，内存占用可以高达200M，有时候会出现点击弹窗彻底卡死（CPU 25%），关闭页面后很久才会自行恢复。

**Comment by FelisCatus** [comment]
@ACsediment 有观测到请求错误计数器（图标上的数字）增长到一个很大的数字的情况吗？

**Comment by 828768** [comment]
这问题确实在,抓了个Snapshot:http://pan.baidu.com/s/1hq90NrA


SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by FelisCatus** [comment]
@828768 感谢您提供的 snapshot 。这个 snapshot 捕获的方式是正确的，并且无任何损坏，可以直接导入。可惜的是这个总共内存才 12.5 MB ，很难解释截图里高达 300MB 以上的占用。

这样的话我就比较怀疑是其他非JS的因素导致的内存占用了。目前怀疑的可能有 canvas （以及GPU绘图相关？），或者 Chrome 自身的本地代码占用内存。

**Comment by 828768** [comment]
這個問題貌似很好復現,瀏覽器長時間不間斷使用就出來了.在此期間,擴展會有"?個資源未加載"這種提示

**Comment by FelisCatus** [comment]
有什么更新吗？任何观察到的现象、性能方面的考虑，或者是其他的 snapshot 都可以。我希望能帮助大家解决这个问题。

**Comment by Chen0719** [comment]
@FelisCatus 
收到你的邮件，第一时间我觉得应该出一点微薄之力了。上次遇到的问题之后再没遇到过，之前你让我搞个快照我觉得可能没必要，就没搞。现在有时间不妨试一试。
Chrome运行超过8个小时，刷了近20分钟的Twitter页面，目测滚图超过500枚而且绝大多数都经过Imagus和Hover Zoom浮了原图，页面开启时长超过两个小时。打开了一个Youtube 1080P页面播放，然后又特意打开了50个站点图片走代理的多图页面。依然无法复现之前遇到的情况，只是50个页面用Stash同时打开的时候内存从39升到了50，确保页面挨个完整加载之后发现降回了38，之后又逐渐降到35，而且这还不单是Proxy SwitchyOmega的内存占用值。http://pan.baidu.com/s/1gd8PST9

Proxy SwitchyOmega 2.3.15
Google Chrome 44.0.2403.157 Stable (32-bit)

自从Chrome宣布要解决内存问题以来，Stable后面陆续更新的几个版本尤其44以后都感觉内存溢出问题明显没有那么严重了，其实这点很早就从Canary45后面的一些版本开始体验出来了。

Chrome越来越好了，或许之前出现的情况并非单单是Proxy SwitchyOmega的问题所导致，现在来看SwitchyOmega简直太强大了，其它代理如DotVPN、Browsec、ZenMate的各国代理都可以在SwitchyOmega上直接保存成PAC模式，这个发现当时简直令我太意外了，如是就保存了这三款扩展的英国代理，配合日本的VPN使用相当给力。

**Comment by FelisCatus** [comment]
@Chen0719 感谢～之前有说过怀疑是非JS的内存占用，现在看来可能确实是这样，而且Chrome已经修复了很多这方面的内存问题。

我准备先关闭这个了，之前遇到问题的各位也试试看升级到 Chrome 44 甚至 Chrome Beta Channel 吧。如果还是有问题，再做 snapshot 就好。
