### ISSUE TITLE
None of the Proxy's seem to work

### ISSUE THREAD

**Issue by thexbasic** [FelisCatus/SwitchyOmega#505]
I just installed the Extension and was grabbing some proxys from hidemyass.com when I noticed, after enabling the profile I always get the same Chrome Error: ERR_PROXY_CONNECTION_FAILED
with HTTP as well as HTTPS proxys configured, I tested about 10 different severs.
Maybe It's just my incompetence of setting this up but I don't think I'ts normal if I can directly ping them via CMD & use them in other programs.
-excuse my english (from germany)

SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by FelisCatus** [comment]
In that case, I think a mis-configuration would be the case. For the Proxy Servers section, only the first row of the table (i.e. `(default)`) should be filled for most of the cases. Select the right protocol for your proxy (which, I think, should be "HTTP".) and fill in the server address and port, and everything should just work. The 3 rows below should be left empty with `(use default)`.

When in doubt, you can always take a screenshot of that section and upload it here. You may mask or zero-out the server address to protect your privacy.

**Comment by pazamit** [comment]
Joining the problem.
configuring the HTTP proxy and select "Use the same proxy server for all protocols"
and can't get access to any site.

Maybe a new version of chrome is causing that.
you should check it out.

10x

**Comment by FelisCatus** [comment]
@pazamit Oh, really? But SwitchyOmega does not have the checkbox labelled "Use the same proxy server for all protocols". Instead, it folds all other schemes by default under "Show Advanced".
Are you talking about the Proxy Configuration dialog of your operating system (maybe in Internet Explorer settings)? Or SwitchySharp (which is another project)?

**Comment by pazamit** [comment]
You are right. I'm using SwitchySharp - the "Support & Bug reports" directs to here.
I also tried SwitchyOmega and I had the same problem.

I'm guessing from the same reason...

**Comment by FelisCatus** [comment]
I would suggest checking your proxy server with other tools than Chrome. A simple curl invocation can help. And you can always try Firefox where the proxy settings and internals are implemented separately.

**Comment by FelisCatus** [comment]
I'm closing this issue because it seems abandoned by its original reporter while still lacking important information. Please do reopen if you have more information or questions.

**Comment by thexbasic** [comment]
Hi, after trying a few alternatives I've come back since this still seems the most promising project.
So, as for the settings, I'll just leave some screenshots of my configuration (the server is definetley a working one, even tested it with a self-written program and the Proxy lib: "Starksoft.Net.Proxy") so feel free to test if yourself :)
I also noticed, if you have currently selected a auto-switch profile but the conditions are errornous and you want to delete the profile, it asks for confirmation but nothing happens.

Config: http://puu.sh/ka7wP/b7cff36026.png

**Comment by FelisCatus** [comment]
Could you please type `chrome://net-internals/#proxy` and check the text there? It should show you the effective proxy settings, in case it is overwritten by some other extensions. You can copy and paste the text.

**Comment by thexbasic** [comment]
Hi, here a picture of the chrome://net-internals/#proxy site: http://puu.sh/kcBmf/ad9576cf50.png

**Comment by FelisCatus** [comment]
In order get more insights about the settings, you can always select `System Proxy` and refresh the page at `chrome://net-internals/#proxy`. Comparing the results with the screenshot above should tell you the difference. If you do notice a difference, I can help you on using the SwitchyOmega options page to achieve the same thing.

**Comment by Trinitron** [comment]
Three years left, and ERR_PROXY_CONNECTION_FAILED and ERR_CONNECTION_TIMED_OUT glitches are still in.  How to set up http proxy only for one host?  For me seens like Switchy don't use my proxy credentials.  And what should i do with failed resources? They are in Auto Switch list already....

**Comment by FlyingThunder** [comment]
none of the servers that are listed seem to work for me aswell - cant connect to any site
