### ISSUE TITLE
能不能算定义颜色啊 ,直接连接与proxy模式

### ISSUE THREAD

**Issue by mtvktvcn** [FelisCatus/SwitchyOmega#506]
能不能算定义颜色啊 ,直接连接与proxy模式

用习惯了sharp,直接连接是灰色,
现在的omega,直接连接和proxy模式,很难分得清啊.

**Comment by xinhugo** [comment]
可以。

单击情景模式左侧的颜色方块，就可以改变颜色。

色码表：[www.ifreesite.com/color/][1]


  [1]: www.ifreesite.com/color/

**Comment by mtvktvcn** [comment]
这个情景模式左侧的颜色方块是指中间那一个点.
以前的sharp整个图片是灰的.如果连接了.就整个变蓝色.比较直观一些.

**Comment by mtvktvcn** [comment]
中间的原点.选择白色 终于容易分辨一点了...

**Comment by xinhugo** [comment]
@mtvktvcn 我和你的不同？颜色方块调整的是外圈的颜色，圆点始终是黑色的。

**Comment by mtvktvcn** [comment]
@xinhugo 我的调整的是内圈的颜色,外圈的不会变.

**Comment by xinhugo** [comment]
@mtvktvcn 不知道什么原因，坐等作者解答。

**Comment by FelisCatus** [comment]
直接连接始终是灰色，暂时无法调整。自动切换时，中心是自动切换模式本身的颜色（可以在自动切换情景中选择），而周围是当前使用的情景模式的颜色（在代理情景模式中选择）。

**Comment by xinhugo** [comment]
明白了，会用了。

**Comment by 477290847** [comment]
我还是不明白

**Comment by xinhugo** [comment]
@477290847 SwitchyOmega 扩展的情景模式，分为 4 种：代理服务器、自动切换模式、PAC 情景模式、虚拟情景模式。

修改扩展图标颜色：
圆点的颜色，修改 **当前使用的** 「自动切换模式」的颜色。
外圈的颜色，修改 **当前使用的** 「代理服务器」的颜色。

**Comment by mtvktvcn** [comment]
@xinhugo 明白了.哈哈.终于理解了.

**Comment by dsonwy** [comment]
懂了
