### ISSUE TITLE
Switch based on "base URL"?

### ISSUE THREAD

**Issue by phoeagon** [FelisCatus/SwitchyOmega#508]
能否以地址栏（或者至少是请求referer匹配）来决定代理？
很多cdn都被墙了，当cdn被域名劫持到其他正常的HTTP服务器时，switchyomega无法正确获知js/css等载入失败

**Comment by FelisCatus** [comment]
PAC 脚本无法获取 URL 以外的信息，所以无法按照当前 tab, main_frame URL 或 Referer 来选择代理。

**Comment by inferrna** [comment]
Did you looking into uMatrix code? For example https://github.com/gorhill/uMatrix/blob/master/src/js/traffic.js Maybe it is also possible to switch proxy by the way like this.

**Comment by celeron533** [comment]
@inferrna It seems that `uMatrix` is similar to `Adblocks` which could <kbd>block</kbd> some URLs.
However, `SwitchyOmega` is a kind of PAC file automation and UI implementation which may not have these features.
