### ISSUE TITLE
使用自动切换模式，打开的网页是移动版而不是桌面版

### ISSUE THREAD

**Issue by grcpeng** [FelisCatus/SwitchyOmega#509]
使用自动切换模式，打开的网页是移动版而不是桌面版

SwitchyOmega 2.3.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by FelisCatus** [comment]
代理服务器问题，与本项目无关。

附：来自GoAgent项目的温馨提示：

> appid 请勿包含 ios/android/mobile 等字样，否则可能被某些网站识别成移动设备。
