### ISSUE TITLE
【不代理的地址列表】功能失效

### ISSUE THREAD

**Issue by bobbai** [FelisCatus/SwitchyOmega#510]
在【不代理的地址列表】里添加地址，但是在实际使用的时候还是会去使用代理

**Comment by FelisCatus** [comment]
估计是格式问题吧，请参考下那边的链接。

**Comment by bobbai** [comment]
链接呢

**Comment by bobbai** [comment]
图片我传不上来，在IE上是生效的，我是从IE里直接copy到SwitchyOmega里面的，它自动把所有的`;`都转换成了换行，这样的格式应该没有问题吧。

**Comment by FelisCatus** [comment]
请参考[关于格式的说明](https://developer.chrome.com/extensions/proxy#bypass_list)。

以及，可以把列表的文字直接贴过来（但不要太长），我可以帮忙看看是什么问题。

**Comment by bobbai** [comment]
meeting.huawei.com
id.honor.cn
*.huawei.com
10.*
www*.huaweidevice.com
bbs*.huaweidevice.com
support.huaweidevice.com
*.huaweimossel.com
*.hwtrip.com
*.huaweisymantec.com
*.hisilicon.com
*.huaweimarine.com
*.smartcom.cc
*.vmall.huawei.com

**Comment by bobbai** [comment]
meeting.huawei.com
id.honor.cn
*.huawei.com
10.*
www*.huaweidevice.com
bbs*.huaweidevice.com
support.huaweidevice.com
*.huaweimossel.com
*.hwtrip.com
*.huaweisymantec.com
*.hisilicon.com
*.huaweimarine.com
*.smartcom.cc
*.vmall.huawei.com

**Comment by bobbai** [comment]
要加双引号？

**Comment by bobbai** [comment]
"meeting.huawei.com","id.honor.cn","*.huawei.com","10.*","www*.huaweidevice.com","bbs*.huaweidevice.com","support.huaweidevice.com","*.huaweimossel.com","*.hwtrip.com","*.huaweisymantec.com","*.hisilicon.com","*.huaweimarine.com","*.smartcom.cc","*.vmall.huawei.com"

这样还是没用

**Comment by FelisCatus** [comment]
我觉得吧……一开始贴的那个格式大致是对的。然而麻烦您说明一下，想要访问什么网站（完整的URL），然后观察到的结果是如何的。

**Comment by bobbai** [comment]
我打开的是一个内网svn地址，我使用自定义的代理设置就打不开，使用系统代理就可以打开

**Comment by FelisCatus** [comment]
@bobai 也就是说，不在您设置的“不代理的地址列表”中吗？那样当然是没效果。

如果在的话请说明完整的URL，以便于分析问题。可以适当地更改网址中的一两个单词以保护您的隐私。

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
