### ISSUE TITLE
Tabbed proxy

### ISSUE THREAD

**Issue by RamiAlHalabi** [FelisCatus/SwitchyOmega#511]
When I was using the older ProxySwitchy extension, I had the impression that each tab was using a separate proxy, whereas in this extension, he proxy changes for all the tabs at once. I am using Chrome.

**Comment by FelisCatus** [comment]
I don't think so. ProxySwitchy is using URL-based proxy as well as SwitchyOmega. Tab-based proxy has never been implemented.
