### ISSUE TITLE
如何识别打开的网站是用了代理？

### ISSUE THREAD

**Issue by koou** [FelisCatus/SwitchyOmega#512]
以前是有个地图，是彩色就是代理了，灰色就是没有代理的。
现在有没有代理都是黑色圆圈，不科学，希望改一下，谢谢！

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36

**Comment by Cumin** [comment]
没代理就一个黑色的圈圈，我觉得挺科学的啊

**Comment by koou** [comment]
但有代理应该就彩色，现在有没有都是黑色

**Comment by Cumin** [comment]
颜色可以自己设定的

**Comment by FelisCatus** [comment]
……黑色圈是系统代理模式，此时并未激活自动切换，也就没有所谓的当前网页是否使用了代理了。

请先切换到任何一个自动切换模式再说吧。
