### ISSUE TITLE
能不能提供一个按时间开启功能 Time-based switch rules

### ISSUE THREAD

**Issue by billmax99** [FelisCatus/SwitchyOmega#513]
现在的omega只是根据规则确定是否启动代理。我还有以下期盼：
1、希望能在上班“时间”自动开启代理功能
2、我有两台电脑，一台在办公室一台在家里，能提供两个配置分别对应两台机子，这样就一对一不用切换也可以。

**Comment by FelisCatus** [comment]
理论上是没问题的，不过设置界面怎么做我还没想好……

**Comment by FelisCatus** [comment]
关于 2: 新建两个（或者两套）情景模式就好，分别使用。或者当然也可以把配置同步关掉，这样就可以各自设置，互不影响了。

**Comment by FelisCatus** [comment]
These condition type are already implemented in `omega-pac`, but no user interface is implemented yet. Creating and editing such rules can be made possible once the UI part is done.

**Comment by FelisCatus** [comment]
[v2.3.18 已经支持星期几和时间条件。](https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.3.18)
[Support for Time and Weekday Conditions is added in v2.3.18.](https://github.com/FelisCatus/SwitchyOmega/releases/tag/v2.3.18)
