### ISSUE TITLE
ERR_CONNECTION_RESET问题

### ISSUE THREAD

**Issue by ugksoft** [FelisCatus/SwitchyOmega#517]
http://pan.baidu.com/s/1c0qARao  密码87w9  (等你下载后,我会取消共享的)

访问非GFWF网站,同样reset问题, 网站不一定,不是天天有,经过n多天,只发现3个, 抓下mydrivers,给你

在前面的贴子后面,也有mydrivers,只是更早时间抓下的

你看看是不是代理引起的

遇上reset后,只能关闭标签页,再打开网页,否则永远是reset

**Comment by FelisCatus** [comment]
已确认和 SwitchyOmega 无关。（无代理实现的相关日志、无PAC错误）

现在而言，比较怀疑和 DNS 解析有关。但我试过了日志中解析出的IP地址，确实是存在的、可以访问的HTTP服务器。难道只是一时的网络或者对方服务器故障？

毕竟我不是专业搞这个的……所以更多情况还是请咨询专家吧。

**Comment by ugksoft** [comment]
我也没找到和so有关的地方,所以才发你看的,  就目前看,最多的是mydrivers(大概3个月里,快有20次了,有时只能关了 chrome才行),cnbeta也有几次(<=5),acznw.com有过1次  , 我的dns是233.5.5.5/6.6.6为主 还加了8.8.8.8/4.4  4个dns  感觉是chrome内部bug, 内部dns预解析模块混乱所致

找不到原因,才发你看看, 你也不明白,那这个贴子就此结贴吧

另:网盘为安全计,我已经取消共享, 里面有我ip之类的数据

**Comment by celeron533** [comment]
或不会是ISP在中间劫持，然后玩脱了？
