### ISSUE TITLE
自动代理经常性的失效，不知道怎么这么难用

### ISSUE THREAD

**Issue by welpher** [FelisCatus/SwitchyOmega#520]
自动代理经常性的失效，不知道怎么这么难用

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与本项目无关。

**Comment by welpher** [comment]
之前的switchsharp没有失败过哦

**Comment by johnhuo** [comment]
这种情况一般先检查检查自己的代理服务器是否正常工作…

**Comment by FelisCatus** [comment]
也可能是之前某设备对于代理服务器的干扰没有这么厉害。

如果方便的话，我建议在 SS 里配置好自动切换，然后再导出备份到 SO 里导入，这样两个扩展设置相同。之后再禁用其中一个启用另一个的情况下分别测试，这样能有效排除各类网络问题的可能。（请注意同时只能有一个启用，否则会互相冲突。）
