### ISSUE TITLE
咨询下如何和其他pac一起使用？

### ISSUE THREAD

**Issue by WuYuKang** [FelisCatus/SwitchyOmega#521]
http://www.lib.whu.edu.cn/web/index.asp?obj_id=150
这是图书馆的校外访问pac
http://proxy.lib.whu.edu.cn/reader/reader.pac
在线的 
如何让可以fq的同时不影响图书馆资源校外访问？

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
先建立一个 PAC 情景模式，输入那个PAC文件的URL，点更新。

然后在自动切换情景模式中，表格最下面一栏设置“默认情景模式”为那个PAC情景模式。这样的话如果规则都不匹配的话，就会使用给定的PAC脚本。

**Comment by WuYuKang** [comment]
十分感谢
