### ISSUE TITLE
Auto switch problems.

### ISSUE THREAD

**Issue by aydarik** [FelisCatus/SwitchyOmega#523]
Auto switch is not working. Icon is changing, but the settings are the ones that have been manually selected.

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by FelisCatus** [comment]
Huh? What do you mean by "the ones that have been manually selected"?

Is the proxy not applied for some URLs? In that case, could you provide the exact URL and related rules?

**Comment by aydarik** [comment]
Okey, I understood the problem. The page I'm looking loads iframe with URL not listed in rule's list and so main page is loading correctly becouse of rule, but frame still continue to use proxy setting, that was manually selected BEFORE auto switch was enabled. Problem was fixed by setting new rule for frame's URL.

**Comment by FelisCatus** [comment]
OK. Cool.
