### ISSUE TITLE
自动代理，有些页面一直显示未加载完毕

### ISSUE THREAD

**Issue by easyinplay** [FelisCatus/SwitchyOmega#525]
chrome44和chrome45使用完扩展自动代理后有的页面一直显示未加载完毕，禁用扩展后正常

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2427.7 Safari/537.36 OPR/32.0.1910.0 (Edition developer)

**Comment by FelisCatus** [comment]
请确保自动切换规则中只针对需要代理的网址设置了代理。如果您正在使用 GFWList ，请确认 GFWList 中相应的规则是否影响了代理切换，并及时向 GFWList 报告问题。

您可以随时使用图标悬停，或在未加载的元素上右键=>“检查该元素使用的代理”来查看部分元素是否使用了代理。如果是的话还可以将鼠标悬停在图标上，在悬停提示中查看具体匹配什么规则。
