### ISSUE TITLE
现在无论我走不走代理，ip都是显示代理后的吗？

### ISSUE THREAD

**Issue by specter119** [FelisCatus/SwitchyOmega#526]
用https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt 自动切换的，自己加了几个正则表达式，发现不好使，上淘宝一直是海外的，学校里需要ip登陆的网站有一个常用的上不去，就是web of science，百度显示我ip在海外。
设置如下：
```
[SwitchyOmega Conditions]
@with result

HostRegex: (^|\.)webofknowledge\.com$ +direct
HostRegex: (^|\.)taobao\.com$ +direct
HostRegex: (^|\.)sci-hub\.org$ +direct

* +direct
```

**Comment by FelisCatus** [comment]
请先确认您在图标弹出菜单中，选择的代理情景模式为自动切换。（也可以选择“直接连接”试试看。）

如果这两个模式选择都不能正常直接连接，请使用图标右键>反馈问题功能。那个功能会打开一个新的Github页面，并且在文本框中填充错误日志和SwitchyOmega版本等必要信息。您可以直接把那个文本框中的内容复制到这里的回复即可，无须创建新的 issue.

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
