### ISSUE TITLE
Config for domain

### ISSUE THREAD

**Issue by mrlinqu** [FelisCatus/SwitchyOmega#527]
How to reset or drop config for domain?

**Comment by FelisCatus** [comment]
What do you mean by config for domain?

If you mean the temporary rules in the popup menu, then restarting Chrome will clear them all because they are, well, temporary.

**Comment by mrlinqu** [comment]
May be worth save the settings for domain? And accordingly, reset this settings?

**Comment by FelisCatus** [comment]
You may want to use the Add Rule option with Switch Profiles, which allows better control and management with all your rules. Temporary rules, however, is not meant for that.

**Comment by FelisCatus** [comment]
I'm closing this. I do plan to add some help text for temporary rules so anybody won't get confused next time. See #515.
