### ISSUE TITLE
关于资源加载失败的问题

### ISSUE THREAD

**Issue by qdwang** [FelisCatus/SwitchyOmega#528]
用SwitchyOmega全局，发现有的资源还是加载失败

比如：\*.live.com
比如：\*.fonts.googleapis.com （http://www.cs.berkeley.edu/~bodik/cs294fa12）

看youtube没问题，而且访问youtube没有资源加载失败的情况，不知道是哪里出错了呢？

**Comment by FelisCatus** [comment]
加载失败了就失败了啊……提示上面已经说了，可能是因为网络问题或者其他的什么原因。

您可以试着把这些都加到规则里，但这个方法只针对需要代理才能访问的资源有效，如果只是单纯的网速过慢就不行了。先不妨试试看吧？
