### ISSUE TITLE
关于学习模式（智能切换模式）的设想

### ISSUE THREAD

**Issue by wdhwg001** [FelisCatus/SwitchyOmega#529]
可以在设置中选择此模式中使用的代理，默认为Direct、系统代理和全部代理设置。
首次开始此模式时，默认所有连接使用Direct。
当该模式启用时，在选取页面所用的代理时，先尝试使用Direct建立TCP连接。
如失败，则依次尝试所有代理，找到第一个可用的，并自动生成对该域名的代理设置。
如成功，则尝试获取该页面，如失败，则依次尝试所有代理，找到第一个可用的后，自动生成对该域名的代理设置。
同时，也可以手动的在按钮菜单中，将本域名添加/移除代理设置。
查了一下，Chrome有提供TCP相关的API，所以这个功能存在相当的可行性。
由于GFWList的过于庞大，所以学习模式拥有非常可观的前景的应该。

**Comment by wdhwg001** [comment]
抱歉，有注意到插件在自动模式下会检测失败的资源加载，但还是希望有自动的学习模式。
另外，TCP连接的尝试如果在多线程/非阻塞的情况下的判断速度要远高于检测失败的资源加载，因为现在GFW一类的大型屏蔽设备变得越来越无脑了，直接砍TCP并污染的情况占了主流，所以预先的学习可以缩短这个相当长的，令人沮丧的等待时间，以及手动点来点去的麻烦。

**Comment by FelisCatus** [comment]
Chrome 的 TCP 连接 API 应该只对 Packaged Apps 可用，对于 Extensions 不可用。

**Comment by iqiancheng** [comment]
可不可以像红杏那样，对于可能被墙的地址，提示是否加入到列表。然后提供一个快速加入到列表的候选项。

**Comment by FelisCatus** [comment]
@iqiancheng 早在 v2.3.6 就可以自动检测未加载的元素了。如有此情况，图标上将显示数字提示，且点击菜单后可以将所有资源一键加入代理。

**Comment by iqiancheng** [comment]
：）您辛苦了
1. 抱歉，以前没有发现。现在终于知道了有这个功能。
2. 我一直没有发现此功能的原因：我一直在使用快速切换模式。

在快速切换模式下，如果能把“将所有资源一键加入代理”加入到右键菜单上就好了～～

**Comment by FelisCatus** [comment]
关于快速切换下的未加载资源问题见 #328.

**Comment by FelisCatus** [comment]
合并到 #550 吧。
