### ISSUE TITLE
没法用,禁止后网页都很慢,卸载就正常.

### ISSUE THREAD

**Issue by avatasia** [FelisCatus/SwitchyOmega#531]
希望提高代码质量,而不是仅仅界面好看.

**Comment by FelisCatus** [comment]
……禁止后网页都很慢？该不会是系统环境中设置了代理，而那个代理服务器本身就很慢吧……既然都禁止了，就几乎不可能是代码质量上（或者性能上）的问题了吧。

如果真的要测试，换成直接连接试试看。直接连接模式不会用任何代理，而且也不生成代理脚本，大部分SO的高级功能都没有，应该不会有任何性能问题才对。如果这样还是很慢，那再来报告吧……

**Comment by FelisCatus** [comment]
抱歉，这个Issue实在是太久没有回复了。如果问题仍然存在，或者有新的信息，请在此评论并重新开启。
