### ISSUE TITLE
无法一键添加被阻挡资源的规则呀。。 右键点击没操作入口

### ISSUE THREAD

**Issue by tanaer** [FelisCatus/SwitchyOmega#532]
SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

**Comment by tanaer** [comment]
一键添加被阻挡的链接功能问题， 右键点击图标 没有操作入口~

**Comment by FelisCatus** [comment]
……请左键点图标。

**Comment by tanaer** [comment]
打开自动切换的时候 左键点击是 切换到下一个代理模式~~    关掉自动切换就可以了 - -！
