### ISSUE TITLE
Authentication Box too fast

### ISSUE THREAD

**Issue by smbenes** [FelisCatus/SwitchyOmega#533]
Using an authenticated proxy. The login and password credential box disappears before user can submit credentials and they must try multiple times before login works.  Appears to be the case for multiple proxies.  Was an issue in SwitchySharp and also in SwitchyOmega.

**Comment by FelisCatus** [comment]
This is an issue with Chrome and cannot be fixed with SwitchyOmega. Please report at the chromium issue tracker.

**Comment by smbenes** [comment]
Thanks - but it only happens when using the SwitchyOmega extension, not with other login/password prompts?

**Comment by FelisCatus** [comment]
You can just configure the credentials in SwitchyOmega, and it can automatically provide them to Chrome when Chrome asks for them. In this way, the popup window will not be shown and the issue can be somehow worked around.

**Comment by FelisCatus** [comment]
You can just configure the credentials in SwitchyOmega, and it can automatically provide them to Chrome when Chrome asks for them. In this way, the popup window will not be shown and the issue can be somehow worked around.

**Comment by FelisCatus** [comment]
You can just configure the credentials in SwitchyOmega, and it can automatically provide them to Chrome when Chrome asks for them. In this way, the popup window will not be shown and the issue can be somehow worked around.
