### ISSUE TITLE
Adblock和switchyOmega冲突了

### ISSUE THREAD

**Issue by 5points** [FelisCatus/SwitchyOmega#535]
打开浏览器，omega突然给我这个提示，请问怎么解决呢？在此谢过了

**Comment by FelisCatus** [comment]
如果是说这个 [AdBlock](https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom)，我自己也在用，经过长期测试，两者并不冲突。所以可能是其他扩展冲突，请试着逐个禁用其他扩展，直到冲突提示消失，以确认具体冲突的是哪个扩展。

也有可能您用的是另一个去广告扩展？如果是这样请给出冲突的扩展名称和谷歌应用商店链接，我可以帮忙看一下。

以下是扩展冲突的通用解决方案，仅供参考：

由于Chrome限制，同一时间只能有一个扩展控制代理设置，一般来说Chrome会优先后安装的扩展。冲突中若SwitchyOmega获得了优先权，则可以切换到“系统代理”模式，从而把优先权归还给其他扩展，从而解决问题。如果此扩展的配置被其他代理相关、或者去广告相关的扩展覆盖，则问题无法解决，只能通过重装SwitchyOmega来提高优先权。

**Comment by 5points** [comment]
我的是adblock的扩展，然后一个是卡巴下载的ADfree.Player.Online
Adblock:https://chrome.google.com/webstore/detail/adblock/gighmmpiobklfepjocnamgkkbiglidom?utm_source=chrome-app-launcher-info-dialog

ADfree.Player.Online:https://chrome.google.com/webstore/detail/adfreeplayeronline/gnpjhfjhgfkohgdklomfbjmnchpenngp?utm_source=chrome-app-launcher-info-dialog

**Comment by FelisCatus** [comment]
测试了一下，应该是 [ADfree.Player.Online](https://chrome.google.com/webstore/detail/adfreeplayeronline/gnpjhfjhgfkohgdklomfbjmnchpenngp) 冲突了。这个扩展含有代理设置相关的功能。

我自己测试的时候，先安装 ADfree.Player.Online ，SwitchyOmega提示冲突。
然后卸载SwitchyOmega并重装，重启浏览器，然后 SwitchyOmega 获得了优先权，ADfree.Player.Online扩展图标上显示`Stop`字样，并且日志中有`No Proxy Permission`和`Skip Proxy Control`记录。
最后将SwitchyOmega设置成系统代理模式，并重启浏览器，则 ADfree.Player.Online 可以正常设置代理了。

P.S. ADfree.Player.Online 设置代理的时机比较奇怪，似乎是在 onBeforeRequest 的时候。（我不太理解技术上这么做的理由，而且他们也没有 issue 之类的可以参考，但不影响冲突之类的。）这使得调试起来比较困难，所以有时候可能不是很清楚。多试试看吧。

**Comment by 5points** [comment]
谢谢你=w=，那我会好好试试的

**Comment by feng0cheng** [comment]
http://bbs.kafan.cn/forum.php?mod=viewthread&tid=1777920&page=1#pid32910502
用这个方法解决了自动切换外部情景模式的问题
