### ISSUE TITLE
google无法搜索任何内容

### ISSUE THREAD

**Issue by lonly197** [FelisCatus/SwitchyOmega#536]
google无法搜索任何内容，一点击搜索就出现如下内容：

We're sorry...

... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.

See Google Help for more information.

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36

**Comment by FelisCatus** [comment]
如果使用了代理，则代理服务器所在的网络似乎存在这种情况。与 SwitchyOmega 无关，请联系代理服务器提供者。
