### ISSUE TITLE
和去除谷歌搜索重定向类脚本冲突

### ISSUE THREAD

**Issue by prodigalsword** [FelisCatus/SwitchyOmega#537]
当该插件和去除谷歌搜索重定向类脚本（如：Direct Google）一起使用时，搜索时页面时常会卡住无法操作，只能F5。

**Comment by FelisCatus** [comment]
如果说的是[这个脚本](https://greasyfork.org/en/scripts/568-direct-google/code)的话，不像是会冲突。
这是一个只在网页中运行的用户脚本，不含任何和扩展和网络请求有关的内容。

而 SwitchyOmega 是一个和代理设置有关的扩展程序，且 SwitchyOmega 不对具体页面做任何修改，不在页面上运行脚本。

P.S. 从那个脚本的源代码上来说，更像是那个脚本本身的效率问题（每次DOM有任何变动时，都会执行一些非常复杂的jQuery查询，且操作涉及整个文档而不仅仅是改变的部分）。关于这一点，先打开F12开发者工具，然后页面卡住的时候在 Script 中按下暂停按钮，就知道具体卡在脚本的哪个位置了。请向该脚本作者反馈该问题。
