### ISSUE TITLE
使用加密代理的时候启动浏览器时会弹出输入密码

### ISSUE THREAD

**Issue by dfc643** [FelisCatus/SwitchyOmega#538]
当使用加密代理的配置或者加密代理的 PAC 的时候。前提是密码已经存储。在启动 Chrome 浏览器的时候会提示输入用户名密码。但是取消后可以继续上网。

在查看代理服务器日志后，以下内容因为没有输入用户名密码被拒绝访问。
> 1437265405.955 TCP_DENIED/407 3948 CONNECT mtalk.google.com:5228 - HIER_NONE/- text/html
> 1437265406.424 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.496 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.496 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.501 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.501 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.501 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265406.531 TCP_DENIED/407 4113 CONNECT apis.google.com:443 - HIER_NONE/- text/html
> 1437265406.593 TCP_DENIED/407 4113 CONNECT ssl.gstatic.com:443 - HIER_NONE/- text/html
> 1437265406.595 TCP_DENIED/407 4113 CONNECT ssl.gstatic.com:443 - HIER_NONE/- text/html
> 1437265406.662 TCP_DENIED/407 4113 CONNECT plus.google.com:443 - HIER_NONE/- text/html
> 1437265406.883 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265406.883 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265406.889 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265406.890 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265406.891 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265406.891 TCP_DENIED/407 4149 CONNECT s2.googleusercontent.com:443 - HIER_NONE/- text/html
> 1437265407.075 TCP_DENIED/407 4113 CONNECT www.gstatic.com:443 - HIER_NONE/- text/html
> 1437265407.130 TCP_DENIED/407 4129 CONNECT clients5.google.com:443 - HIER_NONE/- text/html
> 1437265408.178 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265408.349 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265409.061 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265410.083 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265410.147 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265410.382 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265410.789 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265413.258 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265413.379 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265417.507 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265417.719 TCP_DENIED/407 4129 CONNECT clients2.google.com:443 - HIER_NONE/- text/html
> 1437265417.773 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265417.944 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265418.095 TCP_DENIED/407 4129 CONNECT accounts.google.com:443 - HIER_NONE/- text/html
> 1437265419.947 TCP_DENIED/407 4129 CONNECT clients2.google.com:443 - HIER_NONE/- text/html
> 1437265420.124 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265420.194 TCP_DENIED/407 4113 CONNECT docs.google.com:443 - HIER_NONE/- text/html
> 1437265420.911 TCP_DENIED/407 4113 CONNECT ssl.gstatic.com:443 - HIER_NONE/- text/html
> 1437265421.026 TCP_DENIED/407 4113 CONNECT docs.google.com:443 - HIER_NONE/- text/html
> 1437265422.874 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265423.064 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html
> 1437265423.777 TCP_DENIED/407 4129 CONNECT clients2.google.com:443 - HIER_NONE/- text/html
> 1437265426.312 TCP_DENIED/407 4109 CONNECT www.google.com:443 - HIER_NONE/- text/html

**Comment by FelisCatus** [comment]
合并到 #446.
