### ISSUE TITLE
突然来了个 外部情景模式 是什么鬼？

### ISSUE THREAD

**Issue by cuibty** [FelisCatus/SwitchyOmega#539]
突然来了个 外部情景模式 是什么鬼？

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36

**Comment by FelisCatus** [comment]
应该是安装了其他代理设置相关的扩展。此时“外部情景模式”允许您保存来自那个扩展的代理设置，并集成到 SwitchyOmega 中使用。
