### ISSUE TITLE
SwitchyOmega 乱码怎么回事

### ISSUE THREAD

**Issue by gaoyan1234** [FelisCatus/SwitchyOmega#540]
![20150722163055](https://cloud.githubusercontent.com/assets/10344954/8821280/0d3b7582-308f-11e5-8658-f87727b234f0.jpg)
今天突然这样  这是怎么回事

**Comment by gaoyan1234** [comment]
lib/jquery/jquery.min.js:3 The specified value '!' does not conform to the required format.  The format is '#rrggbb' where rr, gg, bb are two-digit hexadecimal numbers.
lib/jquery/jquery.min.js:2 Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".
lib/jquery/jquery.min.js:2 n.extend.globalEval
lib/angular/angular.min.js:92 EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".

    at eval (native)
    at Function.n.extend.globalEval (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:2538)
    at n.fn.extend.domManip (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:17228)
    at n.fn.extend.append (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:14886)
    at null.<anonymous> (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:16246)
    at n.access (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:2:30124)
    at n.fn.extend.html (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/jquery/jquery.min.js:3:15917)
    at e [as html] (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:25:207)
    at chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular-ui-router/angular-ui-router.js:3891:18
    at J (chrome-extension://padekgcemlokbadohgkifijomclgjgif/lib/angular/angular.min.js:54:373) <main ui-view="" class="col-lg-10 col-sm-9 col-lg-offset-2 col-sm-offset-3 angular-animate ng-scope">lib/angular/angular.min.js:92 (anonymous function)

**Comment by FelisCatus** [comment]
像是扩展冲突。请试着禁用其他所有扩展，并重启Chrome看看问题是否修复。
如果是，逐个启用其他扩展来确定是什么扩展的问题。

**Comment by gaoyan1234** [comment]
禁用了所有扩展都不行  ，但是关闭了shadowsocks后 貌似没有问题了  这是咋回事呢   是shadowsocks 更新后出了问题  还是SwitchyOmega更新后出了问题？

**Comment by FelisCatus** [comment]
能看一下`chrome://plugins`中的插件列表吗？（可以试着禁用一些）
P.S. 请问您是从哪里下载SwitchyOmega安装的？

**Comment by gaoyan1234** [comment]
感觉是我电脑哪个软件的冲突   无论用原生的chrome 还是各种基于此内核的各种游览器  就装这一个扩展 过会都是乱码。同时chrome 44 很多扩展过会儿 就显示“ 此扩展程序可能已损坏” 。 我电脑基本没装啥国产流氓软件 ，刚开机 不运行任何第三方软件都是这样 。我挂代理从官方下的。
![1](https://cloud.githubusercontent.com/assets/10344954/8865476/412fa18e-31e2-11e5-9c63-0f9674cb2a98.jpg)
![2](https://cloud.githubusercontent.com/assets/10344954/8865477/4156a072-31e2-11e5-87e4-8d0c91827976.jpg)

**Comment by gaoyan1234** [comment]
好心和一款glasswie的防火墙软件冲突

**Comment by gaoyan1234** [comment]
可不可能是中病毒了？

**Comment by FelisCatus** [comment]
之前也有其他用户遇到过类似的情况，但因为我没有办法直接调试，所以不知道具体的原因。我个人推测像是有扩展/插件/病毒向扩展页面中插入了脚本的原因。出于安全考虑(CSP)，Chrome会拒绝执行这些脚本，从而导致页面无法正常加载。

请查看您截图中的所有插件，并且禁用**所有**插件，再重启试试看。

P.S. 非常抱歉这么晚回复。工作比较忙，希望理解。

**Comment by FelisCatus** [comment]
请问这边有什么更新吗？正如上面所说，请尝试禁用插件看看问题是否解决。

**Comment by yehuiboy** [comment]
遇到了同样的问题，尝试了许多方法，任然无解。但在chrome45时还是正常，46,47均出现乱码，插件应用无故损坏，修复后，过一会还是损坏。

**Comment by celeron533** [comment]
@yehuiboy , please check the following files if they are missing or overwritten by other programs.
![image](https://cloud.githubusercontent.com/assets/3608762/11930851/0ca7eb54-a822-11e5-91a0-40a92266ffca.png)

extention:
![image](https://cloud.githubusercontent.com/assets/3608762/11930854/11eaff98-a822-11e5-8d4f-6164ecd139b7.png)

language:
![image](https://cloud.githubusercontent.com/assets/3608762/11930857/184051fe-a822-11e5-8cd7-ed8f18bf55a0.png)

**Comment by yehuiboy** [comment]
谢谢你的回答，但是问题没有解决。。。那串字符是对的。。。这怎么办。。。如果有时间能帮忙远程弄一下吗?我留一个邮箱yehuihongkong@163.com或者你留一个。。。？有时间就帮忙试试。。。再次感谢！

**Comment by yehuiboy** [comment]
现在用的是猎豹浏览器，还是chrome内核，旧版Sharp没问题，新版Omega总是乱码。

**Comment by FelisCatus** [comment]
旧版 SwitchySharp 像是用的 manifest 1.0，允许行内脚本和 eval 等不安全的情况，从而被恶意插入了代码也没反应……

@celeron533 提的方法大致是对的，不过具体操作起来比较麻烦，需要打开那个文件夹（以及子文件夹）下的所有html文件，确认其中没有被插入`<script>..广告或恶意代码等...</script>`的内容。这个方式对于普通用户来说比较难……

**Comment by yehuiboy** [comment]
谢谢您的解答，问题已经解决，中病毒了，htm文件被篡改。再次感谢！

在 2015年12月22日 下午3:16，Felis Catus <notifications@github.com>写道：

**Comment by celeron533** [comment]
什么病毒这么恶心啊。。。。全硬盘的文件都改

**Comment by FelisCatus** [comment]
@yehuiboy 解决了就好。
@celeron533 我听说过有一种病毒似乎是只改 html 和 js 文件，用这个作为一种传播途径。楼主很可能也中了招。
