### ISSUE TITLE
mac 下当切换到“系统代理”而全局没有配置代理时提示“无法连接到代理服务器”

### ISSUE THREAD

**Issue by dickeylth** [FelisCatus/SwitchyOmega#541]
Chrome 版本：44.0.2403.89 (64-bit)
mac 信息：10.10.4 (14E46)

当在 SwitchyOmega 中切换到“系统代理”，而全局没有配置系统代理时，访问任何网页提示“无法连接到代理服务器”，请问该如何解决？

**Comment by FelisCatus** [comment]
请在浏览器地址栏中输入`chrome://net-internals/#proxy`，并将页面上的所有内容复制到这里。
我比较怀疑您这种情况是由于其他扩展提供了代理设置，而并不是使用的系统代理。

P.S. 您可以完全不使用“系统代理”功能，而是只使用SwitchyOmega中的代理情景模式或直接连接。

**Comment by dickeylth** [comment]
访问 `chrome://net-internals/#proxy` 的确发现了存在一个之前的本地代理，但是在全局网络里检查该代理配置已经不存在了，感觉是不知为何缓存住了，重启后就 OK 了，多谢！
