### ISSUE TITLE
一切正常，只有SOCKS5代理不能用

### ISSUE THREAD

**Issue by Anikilulala** [FelisCatus/SwitchyOmega#544]
很奇怪的问题，我用shadowsocks+本软件搭建代理
在使用代理连接的时候，shadowsocks linux端会提示socks handshake: socks version not supported进而链接失败
测试HTTP模式的代理是正常工作的
SwitchyOmega为最新版  chrome 44.0.2403.125m

**Comment by FelisCatus** [comment]
我自己用 shadowsocks linux + SwitchyOmega 测试过很多次，应该没什么问题。请确认在代理协议中选择了 SOCKS5 （而非 SOCKS4 或 HTTP）。如果还不行，请提供一张代理服务器设置部分的截图。

**Comment by Anikilulala** [comment]
感谢回复，我发现端口设置为1080时SOCK5端口不能用，错误如上所述，改成其他端口就可以

**Comment by FelisCatus** [comment]
我自己特别测试了一下， shadowsocks 配置中端口改成 `1080` ，然后 SwitchyOmega 中也进行相应设置是没问题的。

也许是系统原因？请检查下 iptables 等是否有相关设置，或者该端口是否被占用。

**Comment by celeron533** [comment]
1080端口可能被占用，我遇到过安装完iTunes后端口被占用的情况。

**Comment by FelisCatus** [comment]
此外关于 SS 可以参考 #557.
