### ISSUE TITLE
无法使用shadowsocks模式和autoswitch模式

### ISSUE THREAD

**Issue by shenxs** [FelisCatus/SwitchyOmega#545]
shadowsocks为2.51版本，本地代理端口127.0.0.1:1080，socks5连接
使用*系统默认代理*模式可以正常使用，所以应该不是shadowsocks的问题，
之前在*chrome43*时可以正常使用
到44版本就突然无法正常使用了

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by shenxs** [comment]
Sorry，已经自己解决了

**Comment by chenrenzhen** [comment]
请问，你是怎么解决的。我也遇上了类似的问题。

使用[System Proxy]没有问题，但是用Profile :: proxy就没办法使用。

使用Profile :: proxy时，chrome://net-internals/#proxy的内容：
Proxy server for everything else: socks5://127.0.0.1:1080
Bypass list: 
  127.0.0.1
  [::1]
  localhost
  192.168.0.0/16
  10.130.0.0/16

**Comment by shenxs** [comment]
我是switch omega的shadowsocks模式中  本地代理IP填错了

**Comment by celeron533** [comment]
@chenrenzhen 猜测把协议换成http能解决问题。在shadowsocks Issue board 关闭之前，clowwindy发现最新版chrome在socks5行为上有变化，导致提前关闭连接。采用http方式后，ss先把http传送到ss_polipo翻译成socks5，然后ss重新把socks5加密收发。

**Comment by chenrenzhen** [comment]
SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by chenrenzhen** [comment]
貌似是我从125升级到157后不能正常使用的。@shenxs @celeron533

**Comment by chenrenzhen** [comment]
@celeron533 

改成这样了，还是不行
Proxy server: 127.0.0.1:1080
Bypass list: 
  127.0.0.1
  [::1]
  localhost
  192.168.0.0/16
  10.130.0.0/16

**Comment by celeron533** [comment]
@chenrenzhen  ![image](https://cloud.githubusercontent.com/assets/3608762/9517186/0b613014-4ce9-11e5-8d3d-061398ce77d2.png)

**Comment by chenrenzhen** [comment]
@celeron533 恩，刚才忘记修改ss的本地端口了，改成http就ok了。谢谢。

**Comment by chenrenzhen** [comment]
@celeron533 但是很奇怪，我开始也试过http，那会儿不行。。。囧

**Comment by FelisCatus** [comment]
见 #557.
