### ISSUE TITLE
gfwlist

### ISSUE THREAD

**Issue by yucesa** [FelisCatus/SwitchyOmega#546]
gfwlist很多次都是未更新 要手动更新后才能使用 能不能提高下这个功能的稳定性
就是如果是未更新 就自动更新下

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查设置>通用中的更新间隔。如果愿意的话可以设置成 15 分钟一次。

此外，在菜单中选择自动切换模式时（即使已经选中），也会触发一次后台更新，也可以试试看。
