### ISSUE TITLE
下拉框的过滤规则似乎无法在设置里看到

### ISSUE THREAD

**Issue by xuefer** [FelisCatus/SwitchyOmega#547]
打开任意网页, 右上角点 omega 图标出来下拉菜单
菜单里点击域名又展开子菜单
子菜单里面就有多个代理设置, 默认是不选任意的
问题1: 选中任意一个代理, 包括DIRECT直连, 之后没有机会"不选择, 按默认规则"
问题2: 选中任意一个代理之后, 在 Option 里怎么也找不到这个设置, 包括 Auto Switch 里也没有, 只能在菜单里设置
这个域名下的设置似乎跟 Auto Switch 不是同一个

**Comment by FelisCatus** [comment]
这个设置是临时规则，见 #515。

如果需要添加到当前使用的自动切换，请使用加号图标的添加规则菜单项。

**Comment by xuefer** [comment]
若是如此，请在几个原则及增加一项”默认”，在哪设置的就在哪恢复，没人第一次使用会自己想到添加规则

**Comment by FelisCatus** [comment]
我知道这个功能很迷惑，现在正在考虑进行一些界面修改和添加帮助以避免，您也可以在 #515 那边提一下建议。这个其实是几年前就引入的功能，当初没考虑好用户体验。直到有人反馈才发现，抱歉了。

另外，临时规则会在重启后失效，不需要手动清除。当初做这个主要就是为了临时换一下代理之类的场景，不过现在看来最好重新考虑一下了。
