### ISSUE TITLE
此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by xiaoyawl** [FelisCatus/SwitchyOmega#548]
请问这个如何解决

**Comment by FelisCatus** [comment]
Chrome 选项同步中，每项设置（对应每个情景模式）的可用空间是有一个上限的。当情景模式中有太多内容（尤其是PAC情景模式和规则列表）时，就会受到此限制。

注意该限制只影响多台设备之间的自动同步。如果您只有一台设备，或者您准备不同设备分别手动设置，则不受影响。您也可以导出选项备份文件，然后发送到另一台设备导入来绕过此限制。

技术上该问题难以解决，因此最可行的办法就是另外新建一个情景模式，并且注意不要使用太多空间。PAC情景模式和规则列表建议使用在线的，这样只会同步网址而不用上传整个列表，很节省空间。
