### ISSUE TITLE
Chrome 升级至 44 后插件经常崩溃

### ISSUE THREAD

**Issue by simonmysun** [FelisCatus/SwitchyOmega#549]
每次重装插件使用不到一小时自己被禁用, 去插件列表查看发现提示 `This extension may have been corrupted. `, 重装插件后可用, 但问题会反复出现. 请问应如何 debug? 

这不是唯一一个升级后崩溃的插件, 但这个最影响我的使用.

**Comment by simonmysun** [comment]
在我这里似乎在特定网址上点击插件图标会引发崩溃. 如 http://taskjs.org/

**Comment by FelisCatus** [comment]
说实话这个我更怀疑是中了病毒，或者是Chrome浏览器检测的问题。不排除有病毒修改已经安装的Chrome扩展并加入恶意代码的可能性。

至于崩溃，基本就是Chrome浏览器的问题了，但考虑到您可能已经中了病毒了，所以我也不建议您直接去Chrome那边反馈了……

如果您要测试的话，建议换一台电脑（或者换一个系统、装一个虚拟机……等等），然后只安装Chrome和SwitchyOmega，就知道是否是扩展和浏览器兼容问题了。此外强烈建议安装杀毒软件并全盘扫描。

**Comment by simonmysun** [comment]
谢谢您的回复. 我这其他设备和系统上都没问题.. 就是一开 Windows 插件被关闭的状态就同步到其他的 Chrome 上了. 

我还是抽空重装系统吧... 

不过有一点是确定的, 我要是一直上 Facebook 是没有事的, 但是去比如 http://taskjs.org/ 等一些地方点一下插件图标就崩溃了.... (别的网址浏览的时候我都没能注意到插件什么时候崩溃, 这个是主动触发的)

**Comment by cnzzr** [comment]
我的电脑遇到了同样的问题，Server 2003 SP2 同时Chrome为最新版本

发现禁用本插件后恢复正常
