### ISSUE TITLE
修改网址后尚未下载更新，因此规则列表已经过时。请使用上方的更新按钮进行下载。

### ISSUE THREAD

**Issue by zhoufenfens** [FelisCatus/SwitchyOmega#551]
最近每天开机打开浏览器就提示这个“修改网址后尚未下载更新，因此规则列表已经过时。请使用上方的更新按钮进行下载。”，老要自己重新下载gfw.txt，奇怪

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by FelisCatus** [comment]
会不会是另一台设备上修改了这个情景模式？

**Comment by zhoufenfens** [comment]
这个是需要把列表变成翻墙可使用。
