### ISSUE TITLE
[Wish] Location aware

### ISSUE THREAD

**Issue by snakyjake1** [FelisCatus/SwitchyOmega#552]
I would like to have my profiles change depending on my location.  For example:  At home I want it to use profile "Home", at work I want to use profile "Work".  Thanks.

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36

**Comment by FelisCatus** [comment]
See #197.
