### ISSUE TITLE
[Question] - Store Proxy Auth

### ISSUE THREAD

**Issue by McBane87** [FelisCatus/SwitchyOmega#553]
Hi,
Thanks for this great Extension/Software.
Unfortunately I can't find any Documentation. So I need to ask a question.
Can I store Proxy Authentication per Proxy? If yes. How?

**Comment by FelisCatus** [comment]
In the `Proxy servers` table on the options page, click on the padlock icon on the rightmost column to input credentials.

Special Note: Authentication for SOCKS proxies are not supported and therefore the button is not shown for these proxies.
