### ISSUE TITLE
脑残 白痴图标，这么久了还不改，还是旧版好

### ISSUE THREAD

**Issue by y723157510** [FelisCatus/SwitchyOmega#554]
不解释，新版图标就是脑残，是否启动了代理都清楚， 最脑残的是正常无代理模式，中间竟然还有个绿点  
搞笑

https://chrome.google.com/webstore/detail/proxy-switchysharp/dpplabbmogkhghncfbfdeeokoefdjegm/reviews
旧版地址 相信能看到我这篇吐槽的都会爬墙

**Comment by FelisCatus** [comment]
您之前[已经提过一次](https://github.com/FelisCatus/SwitchyOmega/issues/134)这个问题了，并且我相信我也说明了此问题在 #107 讨论。
很抱歉，由于我自己时间有限，且项目还有其他问题需要解决，所以这么长时间都没有进行任何实际更改。如果您确实觉得此问题很重要，您可以在 #170 那边询问更新，或者说说自己的意见，问问其他人的看法。在这里使用一些侮辱性的词语来攻击我或者项目，对此问题的解决不会有太多帮助。
新版并没有强制要求更新，所以在此问题解决之前，您可以选择使用旧版。

**Comment by lennylxx** [comment]
If someone is not Playing Nicely Together, you can block him.
You don't need to waste your time on replying to these people.
Just Hack it. Enjoy it. Fuck it.

FYI
https://help.github.com/articles/blocking-a-user/
