### ISSUE TITLE
http://www.redtube.com/

### ISSUE THREAD

**Issue by alallal** [FelisCatus/SwitchyOmega#555]
SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36

**Comment by FelisCatus** [comment]
?

**Comment by cicku** [comment]
应该是汇报 gfwlist 结果弄错地方了，可以关闭了，我来处理。

**Comment by FelisCatus** [comment]
@cicku :ok_hand: Thanks
