### ISSUE TITLE
Failed to prompt certificate authenticate

### ISSUE THREAD

**Issue by vietnguyen09** [FelisCatus/SwitchyOmega#558]
I updated SwtichyOmega yesterday, of course it's working very well but I have problem. 
When I use certificate to authenticate for login in some websites, although I have been 
using direct connection.

I have done some test for make sure that, I've disabled SwtichyOmega and it worked fine 
but the opposite when I enabled.

Thanks for advanced.

**Comment by FelisCatus** [comment]
Please open the page `chrome://net-internals/#proxy`, and copy the text here. And after you re-enable SwitchyOmega, refresh the page and copy the text again so that we can see the difference in proxy settings.

**Comment by FelisCatus** [comment]
Any updates please?

**Comment by FelisCatus** [comment]
Closing this issue now due to no updates. Please reopen if you have more information.
