### ISSUE TITLE
关于SwitchyOmega的鉴权

### ISSUE THREAD

**Issue by ForkPanda** [FelisCatus/SwitchyOmega#560]
在情景模式-代理服务器模式中，要求输入的鉴权（用户密码）是通过什么方式发送的？ 放在了哪里呢？

**Comment by FelisCatus** [comment]
从代理协议角度来说，授权方式与Chrome自带的用户名密码弹窗相同，是通过 HTTP Authorization Header 发送给代理服务器。
Chrome 进行代理请求时，如果代理服务器返回407表示需要登录，则 Chrome 会给 SwitchyOmega 一次提供用户名密码的机会，以代替弹出窗口用户手动输入。 SwitchyOmega 会检查目标代理服务器与设置的代理服务器相符合，然后向Chrome提供用户名密码，之后Chrome继续完成认证协议。如果认证失败或者没有配置用户密码，则Chrome再弹出窗口提示用户手动输入。

如果关心安全性的话，请特别注意以下细节：

* HTTP 代理服务器本身协议上并不安全，其认证协议也有泄露用户名密码的风险。
  * 如果代理服务器提供的是 Basic 类型认证，用户名密码几乎是明文发送。
* Chrome 向 SwitchyOmega 询问用户名密码时，要求的答复为明文用户名密码。此过程中 Chrome 或 SwitchyOmega 都有将明文用户名密码残留在内存中。
  * 注意手动输入也有内存残留问题，且密码可能被键盘记录器盗取。
* SwitchyOmega 将密码明文存储在 chrome.storage 中，且该密码会随扩展设置在多设备之间进行同步，并且谷歌浏览器扩展使用的是谷歌的服务器进行存储和同步。
  * 理论上谷歌可以获取此密码。行政上，谷歌数据中心所在国家或地区的政府可以索取此密码。
  * 如果不信任谷歌，请关闭 SwitchyOmega 的设置同步功能。
* SwitchyOmega 不会尝试加密存储密码，也不会保证用户密码安全。
  * 即使加密存储，在真正提供密码时仍然需要提供明文，甚至在网络上发送明文。
  * 任何物理上能访问您的电脑的人，理论上都可以获取密码，即使密码为加密存储。
  * 因此，与其加密存储密码以造成一种虚假的安全感， SwitchyOmega 选择尊重用户，告知用户可能存在的风险。

如果您真的需要安全，请使用证书认证的 HTTP**S** 代理服务器，并保护好您的证书文件。如果您选择继续使用现在的代理服务器，  **密码一定不要与任何重要的密码，尤其是重要的网络账户（如邮箱或Google账户）的密码相同！** 此警告不仅适用于SO，也适用于任何使用HTTP代理的方式。

个人建议：如果代理服务器密码可以设置，请使用尽可能长的随机密码，并使用 SwitchyOmega 的自动认证功能。假如代理服务器密码长度没有限制的话，建议密码在16位～32位随机字符之间。
