### ISSUE TITLE
谷歌浏览器上安装了 插件 ，但是始终不能通过身份验证。（使用软件是可以正常登陆使用）

### ISSUE THREAD

**Issue by kiandi73** [FelisCatus/SwitchyOmega#562]
SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by FelisCatus** [comment]
请问身份验证是什么？使用的代理软件又是什么？
您可以在回复中详细地描述一下希望达到的目标和实际遇到的问题，也可以上传截图来说明。

P.S. 这里是 SwitchyOmega 项目，一个用于进行代理服务器配置的谷歌浏览器扩展。此项目仅提供设置界面，有关代理服务器或者代理软件的使用问题请与您的服务提供商联系或者参考相应软件说明，谢谢。

**Comment by celeron533** [comment]
类似goagent的代理客户端，由于原生无法支持https，所以很多时候goagent充当man-in-the-middle的角色，即goagent server重新拿自己的证书帮你封装一下你的https。大多数https应用没大问题，但有些客户端会检查https所携带的证书，如果不符，则会拒绝。
另一种可能性是你的代理服务器进了对方的黑名单。

**Comment by huangjianren** [comment]
我有一个是指纹浏览器，是谷歌浏览器的一直身份无法验证登入不进去 这个有插件可以登入进去么？
