### ISSUE TITLE
只显示没有在切换规则列表中的资源加载失败数量

### ISSUE THREAD

**Issue by ng-life** [FelisCatus/SwitchyOmega#563]
启用此选项后，如有（**没有在切换规则列表中的**）资源加载失败，则图标上会显示数字提示。
此时，您可以通过弹出菜单一次设置这些资源使用的情景模式，操作十分便捷。

建议只显示**没有在切换规则列表中的资源加载失败数量**

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by FelisCatus** [comment]
性能上估计不是很可行，不过先记录吧。
