### ISSUE TITLE
SwitchyOmega + shadowsocks + chrome安装版(官网直装) + win10专业版 安装之后可以使用,但是当重启Windows之后就无法使用了.不知道为什么?

### ISSUE THREAD

**Issue by WatsonZ** [FelisCatus/SwitchyOmega#564]
SwitchyOmega + shadowsocks + chrome安装版(官网直装) + win10专业版 安装之后可以使用,但是当重启Windows之后就无法使用了.不知道为什么?

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by celeron533** [comment]
1. 能否调查下是SwitchyOmega不能使用还是SS不能使用？
2. Chrome下其他代理插件情况如何，能否正常使用？
3. 是否安装360或者金山卫士等类似软件？

**Comment by yymyyy** [comment]
#557也是类似故障，但已经关闭了。关闭的理由里提到的#247也已经删除。

也遇到了这个问题，因此把#557的回复在这里重贴一次：
windows10正式版刚发布就使用chrome+switchyomega+shadowsocks的方案，一直正常，今天突然发现自动切换与使用代理的方案不能正常google。因为天天使用google，所以确信昨天还是正常的。仔细看了才发现其他软件都正常，Edge上网dropbox同步都正常，然后试试使用switchyomega的系统代理，确实也是正常，如楼上所说。然后上网搜索才发现这里有人讨论。水平有限只能这样反馈一下了。

**Comment by yymyyy** [comment]
我
1.switchyomega不能说完全失灵，系统代理与直接连接还是正常的。SS完全正常。
2.其他代理插件未测试。
3.未安装国产管家类软件。

**Comment by oe77** [comment]
我这两天也是这个问题，重装了系统能正常使用，但第二天再启动电脑就不能正常使用了！以前都是用Shadowsocks-QT5+win10+SwitchyOmega+chome+SOCKS5能正常使用的，但这两天不知怎么回事，现在找到的唯一解决办法是Shadowsocks-2.5.6+SwitchyOmega+http

**Comment by WatsonZ** [comment]
看了半天也不知道是什么造成的  只好使用mychorme  强迫症真难受  哈哈

**Comment by FelisCatus** [comment]
见 #557.
