### ISSUE TITLE
手动增加的规则能不能归入自动列表规则的情景模式

### ISSUE THREAD

**Issue by wuwenyao** [FelisCatus/SwitchyOmega#565]
手动增加的规则能不能归入规则列表规则的情景模式，规则列表规则很好用，但是实际使用中总会有一些网址并没有纳入。通过手动增加规则来扩展就必须选定一个情景模式，而这个情景模式是定死的，下次切换情景模式时，这些手动增加的规则要一条条改，或者通过文本编辑替换。能不能让手动增加的规则可以有个选项直接使用规则列表规则的情景模式，这样只要改一次就可以换情景模式了。希望作者考虑。

**Comment by FelisCatus** [comment]
可以新建一个虚情景模式，然后使用该情景模式。

**Comment by wuwenyao** [comment]
试过，可以了，谢谢
