### ISSUE TITLE
浏览器插件不能用

### ISSUE THREAD

**Issue by qq907274532** [FelisCatus/SwitchyOmega#566]
浏览器插件配置后 无法翻墙（chrome）

**Comment by celeron533** [comment]
请修改原始问题，加入详细信息

**Comment by FelisCatus** [comment]
请先在扩展图标的下拉菜单中，选择代理情景模式，加载任意网站检查代理服务器是否工作正常。
如果显示无法链接到代理服务器，请检查扩展选项中的设置是否与代理服务器一致。
如果有问题可以截图代理设置部分并发到这里。

（感谢 @celeron533 ）

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
