### ISSUE TITLE
failed to recv data in handshakeReceive2Callback

### ISSUE THREAD

**Issue by Anoneko** [FelisCatus/SwitchyOmega#568]
从几日前起，我的电脑上通过SwitchyOmega的流量不能正常通过Shadowsocks 2.5.1.0，日志中显示为failed to recv data in handshakeReceive2Callback，墙外服务器正常，其他代理走的流量正常(如Proxifier)。

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by celeron533** [comment]
Please refer to: #557 
https://github.com/FelisCatus/SwitchyOmega/issues/557#issuecomment-136226697

**Comment by chrishaly** [comment]
had the same issue too, just change protocol from socks5 to http then proxy works fine

**Comment by earthday** [comment]
卸载迅雷，ok了。
