### ISSUE TITLE
用Shadowsocks，浏览网页经常出现empty response

### ISSUE THREAD

**Issue by chain710** [FelisCatus/SwitchyOmega#569]
用Shadowsocks，浏览网页经常出现empty response

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by celeron533** [comment]
原因是服务器传输到一半的时候TCP连接被断开，但不是reset
使用系统代理直连的时候有这样的问题吗？另外根据网友反映（未确认），迅雷下载插件可能有影响

**Comment by chain710** [comment]
直连的情况下没有问题，机器没有迅雷，chrome也没有其他代理插件。怀疑和网络有关，出问题的是公司网络，在家很正常

**Comment by chain710** [comment]
Proxy server for everything else: socks5://127.0.0.1:8080
Bypass list: 
  127.0.0.1
  [::1]
  localhost

@celeron533

**Comment by FelisCatus** [comment]
如果以上的设置和 Shadowsocks 代理服务器和端口相符合，则不是 SwitchyOmega 的问题。最近很多用户反馈 Shadowsocks 的 SOCKS5 协议不稳定，可以换成 HTTP 协议试试看，也许就能修复。

当然目前来说还是（SS客户端到SS服务器之间的）网络问题的可能性最大。
