### ISSUE TITLE
chrome无法通过switchyomega代理

### ISSUE THREAD

**Issue by MaxYork** [FelisCatus/SwitchyOmega#571]
我使用的代理是shadowsocks，之前一直使用本插件，没有出现问题。但是某天此插件突然无法代理，显示“资源未加载”。检查设置没有任何问题，SS也是正常的，而选择系统代理模式能正常代理。于是我重装chrome之后恢复正常，但是没过几天又出现无法代理的问题。这次我尝试重装chrome也无法修复。同时尝试使用旧的switchysharp也是无法代理的状态。检查SS没有任何问题，可以给其他浏览器正常代理，但是只有chrome不能通过该插件代理（系统代理正常）。这是我遇到的问题，我已经尽可能详细描述，请问有什么解决方法吗？谢谢！

**Comment by celeron533** [comment]
Refer to
#569

**Comment by FelisCatus** [comment]
像是代理设置冲突，请检查 `chrome://net-internals/#proxy` 页面内容并复制到这里。如果那边的代理设置和您在 SO 中的设置不符合，则很有可能是其他扩展设置了代理。
