### ISSUE TITLE
Programmatically change selected proxy

### ISSUE THREAD

**Issue by jodoglevy** [FelisCatus/SwitchyOmega#573]
Is there a way to, from another chrome extension, programmatically change which proxy is selected in SwitchyOmega?

**Comment by celeron533** [comment]
It looks Chrome support messaging between extensions...
https://developer.chrome.com/extensions/messaging#external

**Comment by jodoglevy** [comment]
Yes, that's one of the ways extensions can communicate. But I'm assuming SwitchyOmega already uses some stateful way to "remember" what proxy the user had selected last time (ex, maybe localStorage?).

If so, what is that stateful way? Is there an easy way for me to just change the value stored there?

**Comment by FelisCatus** [comment]
A solution is proposed in #44 with both English and Chinese. However, this feature is only noted and not on the to-do list for now.
We can continue the discussion in English in #44.
