### ISSUE TITLE
更新到chrome45部分网站无法访问

### ISSUE THREAD

**Issue by zhoufenfens** [FelisCatus/SwitchyOmega#576]
您好，更新到chrome45之后发现有些网站配合ss可以继续访问，如google主页，但是有些就不能访问了，如facebook和twitter,google+,今天换成chrome46 beta依然出现相同的问题，使用旧版的Proxy SwitchySharp也没有这个问题，而且浏览器换回chrome44没出现这个问题了，我用的是win10系统，浏览器是32位的，在公司里装的64位貌似没有这个问题。

**Comment by celeron533** [comment]
Works well on my machine. Both win 10 and chrome are 64 bit

```
SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
```

![image](https://cloud.githubusercontent.com/assets/3608762/9687584/ba7cc896-535c-11e5-8783-19f21e4b1ce7.png)

**Comment by zhoufenfens** [comment]
@celeron533 我家里的电脑是32bit的，不知道是不是因为这个问题，公司的电脑是64bit的，没有出现问题.my machine in my house is 32bit。

**Comment by celeron533** [comment]
In addition, please check 迅雷 first. Thunder's browser support may break SO.
Refer to: #557

**Comment by zhoufenfens** [comment]
@celeron533 谢谢！！果然是迅雷的问题，重置了LSP然后重启，问题马上解决了，真是谢谢了。
