### ISSUE TITLE
Problems with configuring SwitchyOmega in Auto Switch mode

### ISSUE THREAD

**Issue by Ralkniv** [FelisCatus/SwitchyOmega#577]
I'd like to configure my Chrome SwitchyOmega (I run my Chrome in portable mode from a USB disk) so that it would automatically load my proxy server (at work -  a must, set by the employer) or connect directly (at home) as needed.

I tried to configure my SwitchyOmega extension in the Auto Switch mode as follows:

Work Profile
Condition Type: Host wildcard
Condition details: = 111.11.111.* (fictitious-example host)
Profile: work proxy

Home Profile
Condition Type: Host wildcard
Condition details: <> 111.11.111.* (fictitious-example host)
Profile: home direct connection, possibly also through VPN

but it doesn't work.

Is there a way to make this function automatically or do I have to always switch the proxy on and off manually? I'm not a very advanced user and the extension doesn't give possible examples how this should be done for it to work...:-)

I hope there is a workaround for this.

**Comment by celeron533** [comment]
Hi @Ralkniv ,
Have you tried the following profile? I wish this may give some help.
![image](https://cloud.githubusercontent.com/assets/3608762/9688153/12cf5178-5360-11e5-8fd2-529ce9887f90.png)

**Comment by Ralkniv** [comment]
Thanks! I've done it the way you suggested. Now at home, can confirm that the direct auto mode works OK. Will test automation for the work's proxy on Monday, and will give you (and others) a feedback:-)

**Comment by FelisCatus** [comment]
Thanks to @celeron533. :beer:

**Comment by Ralkniv** [comment]
I regret to inform that the above workaround doesn't work in my work, even when entering full host number (without the asterisk at the end used accommodate the possible change of the last digits). It's a no go...:-(

**Comment by FelisCatus** [comment]
Did you select the Switch Profile in the popup menu? If not, please try that.
A screenshot of your rules section would be very helpful. You can replace all digits with `1` to protect your privacy, but do keep the format so that I can tell if something goes wrong.

**Comment by Ralkniv** [comment]
Here it is. The IP is ficticious reflecting the used pattern.


![Uploading SwitchyOmega.jpg…]()

**Comment by FelisCatus** [comment]
This looks perfectly fine for me. One question though: Are you visiting the page in question using domain name or bare IP address? If the URL looks like `http://a.internal.example.com/`, then the corresponding host wildcard should be `*.example.com` instead of IP. Remember SwitchyOmega does not attempt any Domain to IP translations.

**Comment by Ralkniv** [comment]
No, there is just bare IP address in the above convention xxx.xx.xxx.xxx

**Comment by FelisCatus** [comment]
Did the extension icon show you anything on the page? Try also hovering over the icon to see detailed information, including the matching rules.

**Comment by Ralkniv** [comment]
It gives me this:

![web page n-a](https://cloud.githubusercontent.com/assets/6896690/9715278/1d2ea578-555f-11e5-8389-31d8c3402395.jpg)

**Comment by FelisCatus** [comment]
Come on... You are visiting `www.bbc.com`, which is not a bare IP address. Why don't you just add `*.bbc.com` to the rules?

**Comment by Ralkniv** [comment]
No, this is just an example page that I attempted to load. My work connection must go through work proxy where I have just the IP. Suggestions?

**Comment by FelisCatus** [comment]
Do you mean anything should go through the proxy except 111.11.111.111? Or the opposite?
Try changing the default profile to `Hermes` if you need proxy by default.

**Comment by Ralkniv** [comment]
The opposite. When at work, everything must go through IP address 111.11.111.111. If the browser sees this IP loaded, it should automatically forward it to the respective proxy, saved as Hermes.

Else, at home, no proxy is needed and the connection is direct.

**Comment by FelisCatus** [comment]
My apologies for wasting your time on this. I didn't understand your problem correctly. Sorry.

Your problem is more like #197, and cannot be solved with Auto Switch for now. Please allow me to further clarify that ALL current switch rules are for matching requests, not the server or proxy. 

But in your case, if you only want to try the proxy server on `111.11.111.111`, and then direct if the proxy server is not reachable, you can just use the PAC script below.

```js
function FindProxyForURL(url, host) {
    return "PROXY 111.11.111.111; DIRECT";
}
```

Create a new PAC Profile from the left menu, paste the code above in script box and you are ready to go. You can use this single profile for both home and work, without any need of Auto Switch.

**Comment by Ralkniv** [comment]
Great! Created a new PAC calling it Auto. Hopefully this would sort it out. I'm at home now and the direct connection works smoothly. Will check the work connection tomorrow and will let you know. I have shortened my work's IP address to 111.11.111.x as it changes the ending dynamically. Hope it would work.:-)

**Comment by Ralkniv** [comment]
It now occured to me that you mention PROXY in the new PAC file. The proxy is in fact different, this is IP address 111.11.111.111. I guess, I should also add here the proxy. But where-how?

**Comment by FelisCatus** [comment]
@Ralkniv I think this can work for you provided that `myIpAddress()` does return an address in `111.11.111.*` at work. Good luck.

**Comment by Ralkniv** [comment]
It doesn't work, even when I change it to 111.11.*

But this seems to work at my work:

function FindProxyForURL(url, host)
{
	return "PROXY 11.111.11.1:1234; DIRECT";
}

At work this works perfectly. Will check the direct functionality back at home in the evening:-)

**Comment by Ralkniv** [comment]
Confirming that it works OK also at home where there is a direct connection. Problem solved! Many thanks...:-)

**Comment by FelisCatus** [comment]
@Ralkniv Glad to know that. Cheers.

**Comment by Ralkniv** [comment]
One more question; I hope I may...:-)

With this last auto setting of mine, is my browser evaluating this PAC on EACH and EVERY page load, or it just does it once - when my browser is loaded, and it stays that way unless a problem with the proxy used is registered? I have in mind possible delays in page load compared with direct proxy option.

**Comment by FelisCatus** [comment]
It does evaluate the PAC script on every load, but detecting whether the proxy is online should occur only once. You may experience some delay when the PAC is initializing, but the performance impact would be trivial afterwards.

**Comment by Ralkniv** [comment]
OK. Many thanks again:-)

**Comment by mitiok2002** [comment]
Thank a lot! Works fine for me!
