### ISSUE TITLE
为什么我用ss和SwitchyOmega时只能使用系统代理了？

### ISSUE THREAD

**Issue by ahappyboy1990** [FelisCatus/SwitchyOmega#579]
SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by pokebaby** [comment]
我也遇到这个问题了，我还换回了之前的SwitchSharp，那个的自动切换却正常的。

**Comment by FelisCatus** [comment]
使用非系统代理的时候有什么问题？

如果代理设置无效，很可能是遇到扩展冲突问题了。这种情况卸载再重新安装 SwitchyOmega 即可。

**Comment by ahappyboy1990** [comment]
非系统代理就打不开墙外网站了

在 2015年9月6日 下午3:39，Felis Catus <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
会不会是 #557 ？

**Comment by ahappyboy1990** [comment]
还真是，我改成http就可以了，我win10 谷歌浏览器 然后是安装了迅雷极速下载版

2015-09-06 16:35 GMT+08:00 Felis Catus <notifications@github.com>:

**Comment by ahappyboy1990** [comment]
真是迅雷的原因，我又卸载装了一下迅雷，然后没选择多浏览器支持就好了呢

在 2015年9月7日 上午12:12，吴强 <ahappyboy1990@gmail.com>写道：

**Comment by davidshen84** [comment]
环境：Win 8.1 64位，chrome 45+，Shadowsocks，迅雷

起初是可以用autoproxy模式的，不知什么时候就不可以了。只能用 **System Proxy** 模式。卸载迅雷后就可以用 **autoproxy** 模式了。

但是我看了下，迅雷没有在 Chrome 里加插件啊。

**Comment by FelisCatus** [comment]
可以看下 `about:plugins` 里面，也许有插件列表。

**Comment by davidshen84** [comment]
@FelisCatus 装上迅雷，`about:plugins` 里没有看到和迅雷有关的插件。但是现在我又可以用 Chrome + Omega 在 **autoproxy** 模式下工作了。

**Comment by FelisCatus** [comment]
@davidshen84 好吧，我感觉更像是网络相关的系统设置被修改了。如果再出问题可以[按这个说明](https://github.com/FelisCatus/SwitchyOmega/issues/557#issuecomment-138070331)测试下。

**Comment by johnhuo** [comment]
我是最近才出现的这种情况，
环境：Win 7 64位，chrome 45+(chrome一直跟进最新版)，Shadowsocks，迅雷(迅雷一直都有，以前也没出现过问题)
改成HTTP模式百度和github可以访问twitter和google不能访问，改成socket4/5模式正好相反。好奇怪
然而我把Shadowsocks客户端代理端口哦换了一个(以前是1090现在8888)一切正常了。

**Comment by dreamtraveler** [comment]
真是迅雷这家伙，我卸了，马上好了
