### ISSUE TITLE
Color tile not properly aligned After add custom colors for profile. 

### ISSUE THREAD

**Issue by sein-tao** [FelisCatus/SwitchyOmega#580]
Operations:
1. select a profile
2. change the color for the profile by adding a customized color
3. repeat step 2 for several times.
4. Click on the color tile left to the profile name

Expect to see:
candidate colors aligned as a matrix

What observed:
a 4x3 matrix, yet the last line extends far away.

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36

**Comment by FelisCatus** [comment]
Wow. Thanks for the detailed report. I will look into it later.

**Comment by FelisCatus** [comment]
This is fixed in v2.3.17. A maximum history of 5 colors is kept now.
