### ISSUE TITLE
SwitchyOmega的自动切换模式突然不能用了，但是选择系统代理就没问题，跪求解答。

### ISSUE THREAD

**Issue by pokebaby** [FelisCatus/SwitchyOmega#581]
机子升级到WIN10系统，chrome版本号“45.0.2454.85 m”，采用Shadowsocks的付费账号，配合SwitchyOmega自动切换一切正常。但就在刚才，突然自动切换失灵，只能选择系统代理模式才能出墙。很费解，能出墙说明SS的服务器没问题，所以猜测是不是SwitchyOmega的问题。
![default](https://cloud.githubusercontent.com/assets/4149848/9700096/2152e3ac-542a-11e5-97c0-4e4b55c2ac84.jpg)
![1](https://cloud.githubusercontent.com/assets/4149848/9700097/21533eba-542a-11e5-9d11-f248a234c1e0.jpg)
![2](https://cloud.githubusercontent.com/assets/4149848/9700098/2155f1c8-542a-11e5-97d8-d483f2b45d7d.jpg)
![3](https://cloud.githubusercontent.com/assets/4149848/9700099/2156fde8-542a-11e5-8d14-3698f22287f9.jpg)
![4](https://cloud.githubusercontent.com/assets/4149848/9700100/2156fa64-542a-11e5-9185-51920b4398b9.jpg)

**Comment by nxtreaming** [comment]
有个疑问： 既然能用系统代理了，还用这个SwitchyOmega干什么呢？用系统代理多方便啊。

**Comment by nxtreaming** [comment]
此外，怎么还用shadowsocks,这货已经死了，不要用。

**Comment by pokebaby** [comment]
SS听闻是win下的客户端开发被禁了，但目前还能用。而且即便win下客户端被禁，订购的服务器账号不会受影响，android上面还是可以用的。在chrome上用SwitchyOmega的作用是，只有遇到被墙的站点时才走SS代理，否则境内的站点也走代理会很慢。

**Comment by nxtreaming** [comment]
I use PAC directly which is transparently as well. and PAC supports all major browser (includes Android and iOS), There's no any advantage to use a 3rd extension such as SwitchyOmega.

**Comment by pokebaby** [comment]
well，thank you for your suggestion，but i have used SwitchyOmega&SwitchySharp for more than 3 years, I really wish this convenient extension work well.

**Comment by pokebaby** [comment]
刚才看了#557的帖子，删除了迅雷，正常了，是否和win10下迅雷有关系呢？ 不得而知

**Comment by celeron533** [comment]
@nxtreaming SS只不过是最先的原型被击毁了，依靠开源社区的力量能衍生出各种版本。

**Comment by shengchou** [comment]
搭车问下，同样是win10系统，突然有一天开始SwitchyOmega+ssh用不了，chrome 版本是  45.0.2454.85。反倒是一个旧版的绿色版chrome能够正常使用，求解...
![chrome-issue](https://cloud.githubusercontent.com/assets/14145060/9702415/5644299a-548e-11e5-9207-ccc6b799e089.jpg)

**Comment by pokebaby** [comment]
@shengchou 我的问题解决方法是卸载了迅雷，你也可以看一下是不是因为有些软件的冲突

**Comment by shengchou** [comment]
@pokebaby 已经卸载其他所有插件...

**Comment by FelisCatus** [comment]
楼主 @pokebaby 的问题，感觉很明显是 #557 。系统代理能用是因为 Shadowsocks 设置系统代理时使用的是 HTTP 代理协议，而可能您在 SwitchyOmega 手动填写的是 SOCKS5 协议。您可以自行在 SwitchyOmega 中也改成 HTTP 协议，就能恢复正常使用了。关于这方面的技术细节讨论和可能的问题原因，可以参考 #557.

@shengchou 的问题也很像，可以先按上面的说明操作切换下代理协议。如果还不行，请打开 `chrome://net-internals/#proxy` 网址，检查页面上的代理设置是否与 Shadowsocks 相符合，以排除扩展冲突的可能。

**Comment by FelisCatus** [comment]
至于 @nxtreaming 关于使用 PAC 文件的意见，我认为也很可取，至少在各个浏览器可以通用。不过有些人喜欢使用代理设置扩展也无可厚非，您也无须花费许多口舌来说服所有人。

从个人的角度而言，我认为SO扩展提供了方便的用户界面，比如切换设置和图形化配置管理规则，起码还是能作为一个便利工具的。Chrome 缺少独立的代理设置对话框，而 SO 正是弥补了这一点。如果用户觉得方便可以使用SO，而如果觉得不好就可以不用，至少也算是多了一种选择吧？

而从项目的角度而言，一个 Issue 需要讨论并解决一个具体问题。我更希望各位能够围绕原主题展开讨论，不要歪楼，不要将精力都放在争论SO到底有用还是没有用上。我当然很感谢您告知各位“使用系统代理也是一种可行的解决方案”，不过关于“SO是否存在问题、是什么问题、如何解决”的讨论还是需要继续的，不是吗？这也不是[您第一次在 SO 项目里否定 SO 了](https://github.com/FelisCatus/SwitchyOmega/issues/504#issuecomment-111835850)，也许是时候收手了。

现在，让我们回到原主题来。

**Comment by nxtreaming** [comment]
I do not reject SwitchyOmega rudely. Why not use a better and simple solution?

**Comment by FelisCatus** [comment]
@nxtreaming You've already made your point. But you don't really HAVE TO convince other people to follow your suggestion, or be aggressive to anybody who does not.

Your latest comment is considered off-topic and not informative. Nor is it persuasive.
This is your last chance. Stop trolling, or you will be banned from commenting in this project.

**Comment by nxtreaming** [comment]
Just do it if you wanna make me silence.

I will do my best to make your project useless.


On Sun, Sep 6, 2015 at 7:19 PM, Felis Catus <notifications@github.com>
wrote:

> @nxtreaming <https://github.com/nxtreaming> You've already made your
> point. But you don't really HAVE TO convince other people to follow your
> suggestion, or be aggressive to anybody who does not.
>
> Your latest comment is considered off-topic and not informative. Nor is it
> persuasive.
> This is your last chance. Stop trolling, or you will be banned from
> commenting in this project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FelisCatus/SwitchyOmega/issues/581#issuecomment-138071204>
> .
>



-- 
Founder of http://coogle.io

**Comment by shengchou** [comment]
@FelisCatus 谢回答，我切换过代理协议但无效，之前一直都是socks5没改动过。然后按照“chrome://net-internals/#proxy”这个执行，出来的东东看不懂....

Recently failed proxies, marked as bad  Clear bad proxies

Bad proxy server	Time for next retry
socks5://127.0.0.1:8388	2015-09-06 20:13:45.845”

**Comment by FelisCatus** [comment]
@shengchou 这个错误信息的大致意思就是 SOCKS5 无法正常连接或者代理服务器不可用。请按 Shadowsocks 的说明改成 HTTP 协议，并设置相应端口号试试看。

**Comment by hehongbo** [comment]
请检查机器是否安装了迅雷-_-
有的机器安装了这货后，socks5用不成，http就可以。有的则没问题。

**Comment by telwenshen** [comment]
我也遇到类似问题了，switchyomega+chrome+latern，系统代理才有用，自动切换失效，迅雷已经删除还是一样。
现在的处理方式是绕过这个问题，而是新建一个pac，url直接填latern的pac地址。

**Comment by vvovv2017** [comment]
@FelisCatus 真是感谢！我的switchyomega也好长时间不能用，通过chrome://net-internals/#proxy查看，才发现，自己的127.0.0.1  端口不知为什么变成了1086，所以导致switchyomega失灵。纯粹门外汉，专门注册账号感谢一下

**Comment by Raysuner** [comment]
> @FelisCatus 真是感谢！我的switchyomega也好长时间不能用，通过chrome://net-internals/#proxy查看，才发现，自己的127.0.0.1 端口不知为什么变成了1086，所以导致switchyomega失灵。纯粹门外汉，专门注册账号感谢一下

为什么我用chrome://net-internals/#proxy只能重新设置代理和清空坏掉的代理这两个选项，怎么查看端口的

**Comment by vvovv2017** [comment]
> > @FelisCatus 真是感谢！我的switchyomega也好长时间不能用，通过chrome://net-internals/#proxy查看，才发现，自己的127.0.0.1 端口不知为什么变成了1086，所以导致switchyomega失灵。纯粹门外汉，专门注册账号感谢一下
> 
> 为什么我用chrome://net-internals/#proxy只能重新设置代理和清空坏掉的代理这两个选项，怎么查看端口的
到你的代理软件的设置里找找看，那里面能看到端口

**Comment by vvovv2017** [comment]
> > @FelisCatus 真是感谢！我的switchyomega也好长时间不能用，通过chrome://net-internals/#proxy查看，才发现，自己的127.0.0.1 端口不知为什么变成了1086，所以导致switchyomega失灵。纯粹门外汉，专门注册账号感谢一下
> 
> 为什么我用chrome://net-internals/#proxy只能重新设置代理和清空坏掉的代理这两个选项，怎么查看端口的

到你的代理软件的设置里找找看，那里面能看到端口
