### ISSUE TITLE
谷歌浏览器插件无法使用 反复弹出登陆窗口

### ISSUE THREAD

**Issue by poundhu** [FelisCatus/SwitchyOmega#582]
SwitchyOmega 2.2.14
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/44.0.2403.89 Chrome/44.0.2403.89 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查用户名和密码是否设置正确。登录窗口中填写时可以使用复制等方式。

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
