### ISSUE TITLE
可不可以加一个新特性

### ISSUE THREAD

**Issue by HengCC** [FelisCatus/SwitchyOmega#583]
显示当前站点走的是代理还是哪个情景模式,或者是直接连接的

SwitchyOmega 2.3.15
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

**Comment by FelisCatus** [comment]
请查看图标来得知当前页面的代理模式。在自动切换模式时，外圈的颜色与使用的情景模式一致，或者如果使用直接连接则为灰色。鼠标悬停在图标上可以查看详情和匹配的规则。

**Comment by HengCC** [comment]
thank you , 刚刚按照你说的确实已经存在了. 多谢
