### ISSUE TITLE
Mac上无法使用，状态栏显示waiting for proxy tunnel...

### ISSUE THREAD

**Issue by wolfrost** [FelisCatus/SwitchyOmega#585]
启用Proxy SwitchySharp 1.10.6 同样无法正常使用。
Windows和Linux都正常。

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.13 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega 只含有平台无关代码，在 Windows / Linux / Mac 上通用。而且既然显示了 `waiting for proxy tunnel` ，说明代理设置已经正确应用，而实际连接时出了问题。

这更像是代理服务器或者代理软件的问题吧……建议去那边反馈。

**Comment by celeron533** [comment]
我觉得很有可能是这些运营推荐用户试用SO，然后用户以为SO就是运营商开发的，所以ticket都发到这里来了
