### ISSUE TITLE
你好。我遇到了不少问题。

### ISSUE THREAD

**Issue by ButterBar** [FelisCatus/SwitchyOmega#586]
你好。我遇到了不少问题。我装了chrome的加速器，选好线路以后并没有跳出窗口要我填账户密码，所以就一直连不上。还有pc版的，设置什么的没有问题，但是就是连接不上。出现这些情况的时候，软件或插件都没有反馈给我到底是怎么回事，我也就只能干等着。想要联系客服，但也始终联系不上，我的问题无法得到解决。我现在需要帮助，但是找不到行之有效的途径，只能联系此处。希望尽快给我答复。我的邮邮箱：xyl2006xyl@126.com

SwitchyOmega 2.2.14
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by Xuanwo** [comment]
请关闭重复的issues

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega ，一个代理配置软件。此项目只提供图形化界面用于配置，并不含任何代理服务器或者加速器之类的网络服务。您的服务商可以推荐您使用 SwitchyOmega 来简化配置，但这并不意味着 SwitchyOmega 与该服务商有任何合作关系。有问题请联系您的服务商。
