### ISSUE TITLE
使用线路的时候无限登录账号

### ISSUE THREAD

**Issue by emmanuelwang** [FelisCatus/SwitchyOmega#588]
使用线路的时候无限登录账号

SwitchyOmega 2.2.14
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

**Comment by FelisCatus** [comment]
这里是 SwitchyOmega ，一个代理配置软件。此项目只提供图形化界面用于配置，并不含任何代理服务器或者加速器之类的网络服务。您的服务商可以推荐您使用 SwitchyOmega 来简化配置，但这并不意味着 SwitchyOmega 与该服务商有任何合作关系。有问题请联系您的服务商。
