### ISSUE TITLE
AutoSwitchy depends on connected profile

### ISSUE THREAD

**Issue by mitiok2002** [FelisCatus/SwitchyOmega#590]
I have to profiles : Work and Home. At work I use Ethernet connection and I need to use proxy (Work profile), at Home I use WiFi connection and no need to use any proxy (Direct connection). Everything works fine, but not automaticaly (I have to choose manually the appropriate profile).
If there is a way to do it automaticaly?

**Comment by FelisCatus** [comment]
You may want to check [this comment](https://github.com/FelisCatus/SwitchyOmega/issues/577#issuecomment-138450492) for trying to connect one proxy, and fall back to direct connection is the proxy is unavailable.
