### ISSUE TITLE
关于网站内引用的资源

### ISSUE THREAD

**Issue by falseen** [FelisCatus/SwitchyOmega#591]
现在的SwitchyOmega在自动切换模式下，不管当前网站匹配的情景模式是什么，在加载当前网站所引用的资源的时候都会重新进行判断。这样有好处也有坏处，好处是如果墙内的网站引用了墙外的资源，那么这种模式下就可以正常加载墙外的资源。坏处是如果当前网站引用了很多不同墙外网站的资源，就需要多次手动添加切换条件。而且这样一来我们很难弄清当前网站有哪些资源走的代理，哪些资源没有走代理。

我记得以前switchysharp对于网站内引用的资源是否走代理是根据该网站所匹配的情景模式而定的，希望能改回以前的这种模式。

另外还有一点，关于未加载资源的提示，似乎只要是没有加载它就提示，而不会事先在已添加的切换条件当中查找是否已添加过。这就造成了很多重复添加，希望能修正一下。

**Comment by FelisCatus** [comment]
根据页面本身的URL来决定整个标签页所有资源的代理，在技术上是不可行的。 switchysharp 也是同样的行为，从来就没改过。您肯定是记错了。

“弄清当前网站有哪些资源走的代理，哪些资源没有走代理”这个需求是  SwitchyOmega 新功能可以解决的。一个功能是未加载资源，另一个是右键菜单中检查元素使用的代理。这个我只能说我已经尽力了。

关于未加载资源只提示自动切换，见 #563

**Comment by falseen** [comment]
可能是记错了，我再换回switchysharp试试。
