### ISSUE TITLE
Doesn't work with Chrome 45 + Shadowsocks 2.5.6 in Auto Switch mode

### ISSUE THREAD

**Issue by euyuil** [FelisCatus/SwitchyOmega#592]
In Shadowsocks' side, the log was like

    failed to recv data in handshakeReceive2Callback

One solution for Chrome 44 was to enable npapi in chrome://flags/#enable-npapi

But Chrome 45 disabled npapi completely.

Ref: https://github.com/shadowsocks/shadowsocks-windows/commit/c688584d489e316abc572643c80071a75e172c86

**Comment by FelisCatus** [comment]
See #557.
