### ISSUE TITLE
Win10+chrome45.0.2454.85 m (64-bit)+插件SwitchyOmega2.3.16 出现failed to recv data in handshakeReceive2Callback

### ISSUE THREAD

**Issue by answer24** [FelisCatus/SwitchyOmega#593]
OS: Windows 10
浏览器:chrome45.0.2454.85 m
插件:SwitchyOmega2.3.16
软件:shadowsocks2.5.2.0

SwitchyOmega无法使用自动切换模式,shadowsocks提示failed to recv data in handshakeReceive2Callback.

SwitchyOmega使用系统代理一切正常.

之前使用win8.1无此BUG.

**Comment by FelisCatus** [comment]
见 #557.
