### ISSUE TITLE
Auto Switch

### ISSUE THREAD

**Issue by azigit** [FelisCatus/SwitchyOmega#594]
I use a proxy server to access a certain geo-blocked tv website.
When I choose the proxy server explicitly, it works - I can access the geo-blocked site and view tv videos.
But when the same proxy server is chosen by Auto Switch it does not work - I can still access the site but cannot view the tv videos.
What can be causing this?

**Comment by celeron533** [comment]
@azigit Could you please attach your configuration?
**Please mask your sensitive data when necessary**

**Comment by azigit** [comment]
@celeron533 
Configuration is below. I can get to bbc using UK_tiny server via Auto Switch, but cannot start bbc flash videos. Under Auto Switch, clicking on 'play' results in 'This content does not seem to be working - try again'.  But using UK_tiny directly, outside Auto Switch, the flash video plays normally. 

Config:

    @with result

    UrlWildcard: *bbc.co.uk* +UK_tiny
    UrlWildcard: *ipchicken.com* +UK_tiny
    UrlRegex: .*pandora\.com.*|.*hulu\.com.* +usa_squid

    * +direct

**Comment by celeron533** [comment]
Thanks @azigit , I have created a new profile on my machine (SSGlobal is my proxy server). And it works well.

ipchicken, pandora and hulu can activate the proxy while github does not bcz it is not defined in the rule list.

![image](https://cloud.githubusercontent.com/assets/3608762/9922753/b4ef72d6-5d1e-11e5-9ce5-ecabb20292f8.png)
![image](https://cloud.githubusercontent.com/assets/3608762/9922808/7007e4b8-5d1f-11e5-920c-174cbd0113c7.png)

**Comment by FelisCatus** [comment]
The problem is some resources loaded by BBC does not lie in the `bbc.co.uk` domain. For example, BBC can use videos from YouTube.

In that case, please wait until a badge is shown on the extension icon. Clicking on the "failed resources" menu item from the extension icon popup should tell you what resources are failing on what domain. You can then add the corresponding rules with one click.

**Comment by azigit** [comment]
Thank you both for answers. The truth is SwitchyOmega is very useful for me even without using Auto Switch, but I was curious about what was happening. I'll now use the 'failed resources' information to   modify my rule set.
Many thanks.
