### ISSUE TITLE
Auto switch rule don't work.

### ISSUE THREAD

**Issue by Alexey1100** [FelisCatus/SwitchyOmega#595]
Here's the config:
```
[SwitchyOmega Conditions]
@with result

* +proxy-socks
*.ccc.ru +proxy_m
*web.stats +proxy_m
*.corp.mot +proxy_m
192.168.* +proxy_m

* +direct
```

All rules are working perfect except one with the wildcard `*web.stats`. When I go to the http://web.stats in the browser, it somehow uses proxy-socks profile.

Browser: Opera 31.0.1889.174
System: Debian GNU/Linux 8 (jessie) (x86_64; XFCE)

Thanks.

**Comment by FelisCatus** [comment]
What, **Opera**?! I didn't even know SwitchyOmega works on Opera, seriously.

Anyway, how do you know that the proxy-socks profile is used? Any more information would be very helpful.

**Comment by Alexey1100** [comment]
Yeah, Opera allows to install chromium extensions, since it based on the Blink engine.

I know that the proxy-socks profile is used, because `http://web.stats` is a local resource and it's reachable only over the `proxy_m` proxy. When I disable the auto-switch and choose `proxy_m` profile it works fine.

**Comment by FelisCatus** [comment]
It could be some resources on that page is loaded from another domain which is not `web.stats`.

In that case, please wait until a badge is shown on the extension icon. Clicking on the "failed resources" menu item from the extension icon popup should tell you what resources are failing on what domain. You can then add the corresponding rules with one click.

**Comment by Alexey1100** [comment]
Yes, I checked this popup and it just shows that domain name:
![- 18 09 2015 - 09 07 42](https://cloud.githubusercontent.com/assets/10757562/9951853/deb7f332-5de5-11e5-8562-500457ee5cc0.png)

But it seems I bypassed this problem, by moving the rule on the top of the config, and now it works:
```
[SwitchyOmega Conditions]
@with result

*web.stats +proxy_m
* +proxy-socks
*.ccc.ru +proxy_m
*.corp.mot +proxy_m
192.168.* +proxy_m

* +direct
```

**Comment by FelisCatus** [comment]
Sorry, I didn't notice you have `* +proxy-socks` there. Switch rules are applied in strict top-to-bottom order for your reference. You may want to move the catch-all line to the bottom.

**Comment by Alexey1100** [comment]
Ok, thanks. Sorry for troubling.
