### ISSUE TITLE
经常出现 ERR_TIMED_OUT。卸载Chrome，重新安装并登录又能用了。过一段时间又不行。

### ISSUE THREAD

**Issue by gameboy709494** [FelisCatus/SwitchyOmega#596]
我用privoxy将socks5代理转换成http代理。
当SwitchyOmega不能用的时候，我的privoxy还能用，证明是我的系统或SwitchyOmega有问题。但是我的系统前几天才安装的呀。

下面是错误信息：

无法显示此网页

ERR_TIMED_OUT
重新加载隐藏详细信息
由于 google.com 响应时间过长，导致 Google Chrome 无法加载网页。该网站可能已崩溃，或者您的互联网连接出现了问题。
请检查您的互联网连接是否正常
请检查您的网线是否插好，并重新启动您在使用的任何路由器、调制解调器或其他网络设备。
对防火墙或防病毒软件进行设置，以允许 Chrome 访问该网络。
如果它已被列为允许访问网络的程序，请尝试将其从列表中删除，然后再重新添加。
如果您使用代理服务器…
请检查您的代理设置，或与网络管理员联系以核实代理服务器是否运转正常。如果您认为自己使用的不是代理服务器，请执行以下操作： 依次转到 Chrome 菜单 >“设置”>“显示高级设置...”>“更改代理服务器设置...”>“LAN 设置”，然后取消选中“为 LAN 使用代理服务器”。

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by celeron533** [comment]
出问题的时候IE能否正常？会不会是防火墙间歇性连接屏蔽？

**Comment by gameboy709494** [comment]
出问题的时候IE是没问题的。

**Comment by gameboy709494** [comment]
出问题的时候，我通过privoxy提供的HTTP代理仍然能够伤到外网，至少这个时候不关GFW的事。

**Comment by gameboy709494** [comment]
非常费解的是：

（谷歌浏览器存在“用户”的概念。）

我删掉当前用户，重新登录我的谷歌账户，稍后所有资料包括SwitchyOmega及其设置同步下来之后就能用了。然后过一段不清楚的时间，SwitchyOmega又不能用了。

**Comment by gameboy709494** [comment]
我先介绍一下我的环境：

我家存在局域网网络。
ssserver服务器位于境外VPS，sslocal服务器位于局域网的一部arm6开发板（192.168.0.210）。
sslocal监听端口是1080，开发板也安装了privoxy（将socks5代理转换成http代理），监听的端口是8080。

当SwitchyOmega不能使用的时候，我通过privoxy仍然能访问外网。

**Comment by gameboy709494** [comment]
另外，尽管我已经正确设置系统代理，chrome在线安装器还是无法正确联网，我是使用standalonesetup安装的，地址https://support.google.com/chrome/answer/126299?hl=zh-Hans ，我选择的是“用于所有用户帐户的备用安装程序 »”。

**Comment by gameboy709494** [comment]
我已经重新安装了chrome，目前SwitchyOmega正常工作。

**Comment by FelisCatus** [comment]
看上去像是和 #557 相同的情况.

**Comment by johnhuo** [comment]
看这个--->>
https://github.com/shadowsocks/shadowsocks-windows/commit/c688584d489e316abc572643c80071a75e172c86

**Comment by gameboy709494** [comment]
果然，我将socks5代理换成http代理就可以用了。
（我的开发板已经将socks5代理转换成http代理了。）
我的操作系统是Windows7，自动安装更新。
chrome是最新版的吧：版本 45.0.2454.93 m。
临时解决这个问题的办法是卸载并重新安装chrome，不过问题又很快出现了。
