### ISSUE TITLE
Is it possible to setup rules based on what network is the computer connected to?

### ISSUE THREAD

**Issue by gzapert** [FelisCatus/SwitchyOmega#597]
I'm using 2 networks. In one I need to turn on proxy, the other works without proxy. Can I setup rules to set the proxy automatically when I connect to one of the networks?

**Comment by FelisCatus** [comment]
See #197 for the tracking issue, and [this comment](https://github.com/FelisCatus/SwitchyOmega/issues/197#issuecomment-138325453) for a temporary solution.
