### ISSUE TITLE
chrome 45  用shadowsocks无法正常连接

### ISSUE THREAD

**Issue by qilin72** [FelisCatus/SwitchyOmega#599]
shadowsocks会出现这样的信息failed to recv data in handshakeReceive2Callback
IE和EDGE都正常

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

**Comment by FelisCatus** [comment]
#557
