### ISSUE TITLE
检测未能加载的元素并提示快速加入规则

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#6]
English Title: Detect elements that could not be loaded due to network issues on the page, and provide quick "Add New Rule" UI

开发工程量比较大，而且权限是否会太多？如果和扩展主程序关系不大考虑做成另一个扩展或者插件的形式。

**Comment by simonsww** [comment]
建议只需要对域名无法访问进行快速加入规则，这个可以参考下红杏插件

**Comment by dingyaguang117** [comment]
红杏做的真不错 +1

**Comment by FelisCatus** [comment]
反正我是觉得近期应该没时间做这个了……除非能有其他人愿意合作或者提交PR。

**Comment by FelisCatus** [comment]
v2.3.6 现在可以自动检测未加载的元素了。如有此情况，图标上将显示提示，且点击菜单后可以将所有资源一键加入代理。

----

P.S. 我本来想要给自己放个假，好好地过个年的。但是，我最终还是选择了在除夕做完这些工作。确实，这不是一件简单的事情，想要做对很难。但是核心代码量并没有想象中的那么多，反而大部分精力花在了界面和提示上。

我只是不愿意被人瞧不起。既然某收费、闭源、商业的软件都做得到，那么凭什么 SwitchyOmega 做不到？即使现在可能仍然有不完善的地方，但技术核心已经确定下来了，而且，这一切都是开源、免费的。开发者可以从中学习、改进，而普通用户也能享受到放心免费的服务。（源代码完全公开，不必担心有任何安全或隐私问题，这是最大的优势。）

我做这个项目，全凭自愿投入时间。我已经说过了，此项目并不是为了赚钱。相反，到现在为止我没有通过 SwitchyOmega 拿到过一分钱，反而贴了5美元给谷歌应用商店。许多商家曾经找过我，让我宣传他们的代理服务器，让我在扩展里植入广告，让我收集用户浏览数据并卖给他们，但我都拒绝了。因此，才能有今天的，仍然开源免费的 SwitchyOmega 。

**活着就是要争一口气。商业软件能做到的，开源一样也能做到。而且，还要比他们都做得更好，让所有人都看到我们的努力。** 如果有人看完这些以后想要帮忙的话，可以共同开发，或者简单的提一个 pull request 就好，这都能帮助这个项目走得更远。

**Comment by syswow** [comment]
一个人维护一开源项目确实很不容易，@FelisCatus  :+1:  :smile:

**Comment by dingyaguang117** [comment]
我其实是很想搞的，不过是做后端的对Chrome开发不熟，实在是有点费劲

感谢下LZ

**Comment by cicku** [comment]
Not sure if you could add an option for uploading blocked websites added by users to somewhere? I could offer you server for storing such list.

I'd like to collect these information and update the gfwlist more quickly.

**Comment by FelisCatus** [comment]
@cicku This diverts from the goal of this project. After all, this is just a proxy configuration tool instead of a collection of blocked websites. I would recommend that you contact the gfwlist project for cooperation, or start your own project aiming at maintaining a up-to-date list of blocked websites.

**Comment by hehh2001** [comment]
只能说感谢的话了，我是个受益者，不懂开发。感谢你做这么好的东西。开源爱好者支持你。
