### ISSUE TITLE
建议加一个支线

### ISSUE THREAD

**Issue by ynyounuo** [FelisCatus/SwitchyOmega#60]
* 主分支应对 Google 商店发布版本
* 另一条分支为不在 Google 拓展商店发布的实验性版本

然后有更新先添加到实验性版本，如果有 bug 也能让大多数人轻松回退然后不用折腾禁止 Chrome 自动更新拓展，实验性支线鲜有大面积的 bug 提交的时候再推到 Google 商店发布的版本

不知是否可行

**Comment by celeron533** [comment]
这个坑看样子是填不上了 :octocat:

**Comment by FelisCatus** [comment]
搞不定啦，之前的 SwitchySharp 看来是没法升级了……用户抵触太大了……

估计大家都对我挺失望的吧……

**Comment by celeron533** [comment]
SwitchySharp 就让他挂在那里。。。或者可以推出个最终告别升级，在初次使用和设置界面里面加一句话，向用户说明项目已经终止，请移步到SO

**Comment by FelisCatus** [comment]
又扑街啦……果然没有测试版是真不好……想想怎么办？

**Comment by FelisCatus** [comment]
但问题是就算我弄一个 “不在 Google 拓展商店发布的实验性版本”， Chrome 也会自动移除非商店安装的所有扩展（主要是 Windows）……测试用户会很不方便的呢……

或者引入 A/B 测试？商店允许部署给 x% 的用户…… x 可以是 5% 或者 50%

**Comment by celeron533** [comment]
测试用户就直接手动安装吧。。。出了bug后也方便更换版本，只是需要手动备份恢复。
测试用户可以第一时间享受到尚在开发中的新特性，代价就是bug和手动升降级

**Comment by FelisCatus** [comment]
没有经过应用商店签名并且手动安装的插件会被 Chrome 自动卸载的……
如果我们要做测试版，那么还没出的新版只能自己想办法打包，应用 ID 会不一样，且没商店签名……所以……
这事比想像的要坑……

**Comment by celeron533** [comment]
也倒是，我之前修改icon大小后，本地版本一直提示不安全，每次新开chrome都提示删除

**Comment by FelisCatus** [comment]
然后用户同时安装了两个版本，就疯狂冲突，各种奇怪的现象……
