### ISSUE TITLE
此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by Arnaud-Github** [FelisCatus/SwitchyOmega#600]
才几十个切换规则怎么就出现这个了！

------------------------------------------------------------------------------------------------------------
SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.93 Safari/537.36

**Comment by FelisCatus** [comment]
可能是规则列表或者PAC使用的存储空间。每项设置的存储空间是有限制的，此限制由谷歌规定，我没有任何办法增加可用空间。
关于显示存储空间具体的使用情况，见 #272.

**Comment by ChenFengPa** [comment]
是否可以尝试添加选项"关闭同步pac文件"" 来让其他可以得到同步
