### ISSUE TITLE
不知为何， FF+FoxyProxy 就能用shadowsocks， chrome上经常不能用

### ISSUE THREAD

**Issue by eromoe** [FelisCatus/SwitchyOmega#602]
公司电脑，chrome 经常是能用一会，立刻不能用了，过了一段时间之后，又能用一下，然后又不行
url: https://www.google.com/ncr
```
无法显示此网页
ERR_CONNECTION_RESET
```
shadowsocks 服务端 也没有显示log

bing.com baidu.com 什么的用 shadowsocks 也都行，难道是 google https 什么的问题？

用FF+FoxyProxy就没有这种情况， 服务端也有log显示

家里的电脑则完全没问题。

**Comment by johnhuo** [comment]
#557
