### ISSUE TITLE
chrome 45版本,无法使用socks5访问bvssh提供ssh代理

### ISSUE THREAD

**Issue by wolffeng** [FelisCatus/SwitchyOmega#604]
错误代码如下
01:17:54.845 Accepted new proxy connection from 127.0.0.1:6663 on 127.0.0.1:1080.
01:18:24.895 Failed to decode proxy request from 127.0.0.1:6663 on 127.0.0.1:1080. Connection ended before a proxy request was received.
为节省空间仅保留相关两条.
26日夜间发现此问题,当时使用switchsharp,更新为omega后软件会自动切换使用socks4连接
同时firefox使用socksv5 或者是系统代理设置为socksv5时代理软件均正常

**Comment by johnhuo** [comment]
#557,顺便更改本地端口看是否可行？

**Comment by wolffeng** [comment]
改了本地端口,还改了http模式,均是开始能用用,然后就又开始无法解析了.还是回到socks4才能用

**Comment by FelisCatus** [comment]
见 #557

**Comment by johnhuo** [comment]
Chrome45+的问题，可以尝试下Firefox呀～

**Comment by eromoe** [comment]
我试了下，https 都可以访问， HTTP的全部出这个错
