### ISSUE TITLE
SOCKS4/5 not working, HTTP HTTPS working 

### ISSUE THREAD

**Issue by jejer** [FelisCatus/SwitchyOmega#605]
It's strange issue, yesterday, every day is working, could you please let me know how to debug?

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36

**Comment by johnhuo** [comment]
#557

**Comment by jejer** [comment]
Uninstall xunlei
