### ISSUE TITLE
立即更新情景模式出错

### ISSUE THREAD

**Issue by DENGLAN** [FelisCatus/SwitchyOmega#606]
安装Proxy SwitchyOmega的最后一步，立即更新情景模式不能更新，显示下载情景模式数据事出错。

SwitchyOmega 2.2.9
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by wenliyang** [comment]
先切换到一个已经配置好的可用翻墙代理，全局模式

**Comment by FelisCatus** [comment]
我相信教程那边也说过了，不过请检查是否正在使用代理服务器的全局模式。如果正在使用，可以随意访问一两个网站确认代理服务器工作正常。

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
