### ISSUE TITLE
自动打开设置页

### ISSUE THREAD

**Issue by cskeleton** [FelisCatus/SwitchyOmega#608]
自动切换模式会在新标签页打开这个模式设置页。之前并没出现过此类问题，重装系统和浏览器之后出现此问题。

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by FelisCatus** [comment]
第一次使用自动切换会提示用户进行设置，之后不会再出现，不影响使用。重装系统和浏览器会重置此检测，请勿见怪。
