### ISSUE TITLE
https connect method

### ISSUE THREAD

**Issue by FlyingHazi** [FelisCatus/SwitchyOmega#609]
Will SwitchyOmega use HTTP CONNECT Method when connecting to a https proxy?

**Comment by FelisCatus** [comment]
Short answer: Yes.

Long answer: SwitchyOmega does not do proxy internals. It tells Chrome about the proxy settings and lets Chrome do the job. Please refer to Chrome source & documentation or ask in relevant forums for the exact behavior.
