### ISSUE TITLE
能否单独为情景模式设置切换的快捷键

### ISSUE THREAD

**Issue by cxjava** [FelisCatus/SwitchyOmega#610]
能否单独为情景模式设置切换的快捷键？
比如：
* Alt+Shift+1 切换代理为ss 
* Alt+Shift+2 切换代理为ss-pac

**Comment by FelisCatus** [comment]
这个其实可以考虑……虽然，估计设置界面又是一堆。

主要问题是设置快捷键只能在 Chrome 的设置界面里弄，然后设置好快捷键以后还要回 SO 这边指定具体切换到哪个模式……用户体验太难做。

**Comment by celeron533** [comment]
或者直接做成层叠菜单？有的人代理会比较多，一长串列表不方便检索

**Comment by FelisCatus** [comment]
出于性能考虑，目前弹出窗口还是不适合玩太多花样……已经够卡啦。

**Comment by FelisCatus** [comment]
我个人感觉 `Alt+Shift+O` 然后再按 `1` 体验不会差太多，而且无须复杂的设置之类的。

弹出菜单中每一个选项都有快捷键，具体可以在弹出菜单后按下 `?` 查看。

**Comment by Shssaber** [comment]
very good useful for the ? shortcut.3q.

**Comment by libiao7** [comment]
不需要到选项设置页, 用户自己到chrome://extensions/shortcuts设置就行啊,但是您只提供了默认激活拓展的命令,就只能设置一个快捷键,为何不多给几个额外命令,比如:切换到模式一 ,模式二 ...
例如Tampermonkey就给了好多命令,默认都没绑定快捷键,用户可以根据自己需要自行绑定.
