### ISSUE TITLE
pac情景模式没法处理https请求

### ISSUE THREAD

**Issue by muink** [FelisCatus/SwitchyOmega#611]
目标pac文件http模式下为空
只有https模式下才会显示内容

pac情景模式更新失败

**Comment by FelisCatus** [comment]
SwitchyOmega 有不少用户使用的规则列表都是`https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt`，确实是`https://`协议，更新似乎没有问题。PAC更新与规则列表更新共享很多代码，理论上应该也不会有太多问题。当然我自己也试过。

遇到这种情况，请务必检查当前正在使用哪个情景模式。按照实际情况，建议选择直接连接，或者一个代理情景模式（如果需要的话），然后再点击更新。还不行的话，请再次检查地址是否填写正确（需要填写`https://`协议的完整URL）。

如果还不放心，可以用抓包软件，或者打开Chrome扩展的开发者模式，点击SwitchyOmega下的`background.html`，并在打开的窗口中选择Network标签。此时再点击立即更新，即可看到具体的网络请求以及结果。

**Comment by muink** [comment]
@FelisCatus 打开背景页选项卡后能更新了,搞不清楚怎么回事....
:o:

**Comment by FelisCatus** [comment]
我准备先关闭这个了，看上去像是网络问题，或者（因为Chrome崩溃等原因）背景页面被暂时关闭了。如果再次遇到此问题请重新开启。
