### ISSUE TITLE
Proxy to connect 127.0.0.1 on remonte machine problem.

### ISSUE THREAD

**Issue by kkolszak** [FelisCatus/SwitchyOmega#613]
Hi, 
After update from ProxySwitch to SwitchyOmega, I have problem with connect to localhost via ssh sock5 tunnel. 

Example:
1) Connecting via ssh -D 8080 option
2) Run proxy profile on SwitchyOmega
3) Run on web browser http://127.0.0.1:631 (I need remote cups server)

Acctualy point 3 - get localhost service on my laptop (not remote 127.0.0.1 via ssh tunneling).

Web browser - google chrome on ubuntu 14.04 from stable repo.

**Comment by FelisCatus** [comment]
Please double check your Bypass List config section and see if anything like `<local>`, `localhost` or `127.0.0.1` is in there. Removing these lines should do what you want.

**Comment by kkolszak** [comment]
Exactly, thx.
