### ISSUE TITLE
Option to activate a proxy profile when going into Incognito mode

### ISSUE THREAD

**Issue by bits01** [FelisCatus/SwitchyOmega#614]
Not sure whether this is possible to implement, but I find it that every time I use Incognito I also enable a proxy profile. It would be nice to have an option that could automatically enable a proxy profile when a new window in Incognito mode is opened. The proxy profile should only apply to that window, if possible, or the proxy profile should to be switched back to what it was when the window is closed.

Thank you for considering this suggestion.

**Comment by FelisCatus** [comment]
This should be addressed by #10.
