### ISSUE TITLE
只能使用系统代理

### ISSUE THREAD

**Issue by specialzsp** [FelisCatus/SwitchyOmega#615]
感谢您提供如此优秀的应用。不过，在chrome上使用SwitchyOmega插件+shadowsocks时，只能使用系统代理才能登陆到网站（将shadowsocks调整至PAC或全局均可使用）；而使用自建的情景模式时，无论是PAC还是全局均无法上网。已经咨询过shadowsocks团队，可能的问题出在SwitchyOmega插件上。请问可能的问题是什么？配置截图在附件中。谢谢！

![switchy_screenshot](https://cloud.githubusercontent.com/assets/15035776/10372059/be4aa7d2-6e18-11e5-9d88-0ca332612def.JPG)

**Comment by celeron533** [comment]
迅雷会修改系统底层连接参数，请删除迅雷后再试。记得相关issue号#557

**Comment by FelisCatus** [comment]
#557.

**Comment by liangsenzhi** [comment]
同时用两个插件好像会有问题
