### ISSUE TITLE
Add Rule that can use profile "System Proxy"

### ISSUE THREAD

**Issue by chrishaly** [FelisCatus/SwitchyOmega#616]
Hi,

Could you Add Rule that can use profile "System Proxy", in auto switch mode.

能不能在自动切换里，添加功能：符合某些规则时使用系统代理，如果系统代理设置了代理就使用系统设置的代理，如果系统代理是直接连接就直接连接。

tks

**Comment by FelisCatus** [comment]
This is technically impossible. See #289.
