### ISSUE TITLE
域名规则的匹配好像有问题喔 例如 https://google.com/a/domain.com 不会触发情景模式

### ISSUE THREAD

**Issue by CicholGricenchos** [FelisCatus/SwitchyOmega#617]
`https://google.com/a/domain.com/`
这种是google的自定域名的apps，发现用这个url访问的时候不会触发auto-switch的切换，但是用
`https://admin.google.com/domain.com/UserHub` 又可以，猜测是匹配出了问题？

谢谢啦

**Comment by FelisCatus** [comment]
用的自动切换规则具体是什么？是通配符还是正则？表达式是什么？

**Comment by CicholGricenchos** [comment]
@FelisCatus 
我用的是github上的gfwlist，我去查了才发现gfwlist里其实没有google.com的匹配。。
这个才是原因，贴issue时没留意=  =

先关掉这个了
