### ISSUE TITLE
Option to disable SwitchyOmega

### ISSUE THREAD

**Issue by jtyr** [FelisCatus/SwitchyOmega#619]
I would appreciate yo have an option to disable SwitchyOmega in the icon context menu.

SwitchyOmega 2.3.16
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36

**Comment by FelisCatus** [comment]
The "[System Proxy]" profile effectively clears all the proxy settings provided by SwitchyOmega, returning control to other extensions or operating system. It is the second item in the popup menu.
