### ISSUE TITLE
我在路由器上配置的ss。。正确在chrome里配置了socket5代理。但无法访问网站。

### ISSUE THREAD

**Issue by hwqchi** [FelisCatus/SwitchyOmega#620]
访问网站一直显示 正在连接。。我用手机配置socket5代理，可以连接上。。就是电脑上不能用。。很急。。 不知道该怎么办。。

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.8 Safari/537.36

**Comment by FelisCatus** [comment]
请检查代理服务器是否可用。显示一直正在连接的情况，很可能和防火墙等设置有关。
用`telnet 192.168.1.1 1080`命令（假设路由器IP为`192.168.1.1`，端口为`1080`）可以检查到代理服务器之间的连接是否可以正常建立。

**Comment by hwqchi** [comment]
我的路由是openwrt系统。。用的是luci-app-shadowsocks	0.12+svn-r1024-1插件
我应该怎么去设置呢？？很急。。
有的时候电脑能连接的上。。但很少时候能连得上。。手机一直都可以。。

**Comment by FelisCatus** [comment]
我知道您很急，但如果您能够前去 openwrt 相关的论坛提问，应该会有更多人可以帮助您。
这里是 SwitchyOmega 项目，熟悉 openwrt 的人并不是很多。比如作为项目维护者之一的我，对于路由器就是一窍不通的。

**Comment by weaming** [comment]
我的情况是扩展 swichyOmega 和路由器ss冲突，禁用扩展就好了

**Comment by woodylh** [comment]
我也遇到了同样的问题，openwrt开启了socks代理，但SwichyOmega连不上。
