### ISSUE TITLE
URL PORT

### ISSUE THREAD

**Issue by Saman24** [FelisCatus/SwitchyOmega#621]
HI
could you please add URL port for auto switch rules
for example i want to set 
if the URL port is 1935 = PROXY1 (Flash Media Server)
URL port is 443 = PROXY2 (SSL Sites)
URL port is 45591 = PROXY3

Thank you very much

**Comment by FelisCatus** [comment]
The `URL wildcard` condition type is better for this.

* PORT 1935: `*://*:1935/*`
* PORT 45591: `*://*:45591/*`
* All HTTPS URLs: `https://*`
  * The HTTPS protocol default to port 443. In that case the port number is not present in the URL string.

**Comment by celeron533** [comment]
I think this use case should be mentioned in wiki. :)

**Comment by FelisCatus** [comment]
@celeron533 [Done.](https://github.com/FelisCatus/SwitchyOmega/wiki/URL-wildcard-condition#matching-url-with-ports) :-)
