### ISSUE TITLE
Sync by default

### ISSUE THREAD

**Issue by wernight** [FelisCatus/SwitchyOmega#622]
Synch of the settings is the number one improvement I'd like to see.

Ideally if I install a Chrome on a new machine, it'd just start installing all my previous extensions and for SwitchyOmega it'd just see that I already enabled "Synching" and show nothing at all, just install all my previous options. So if "Synch" was enabled once:

 - No post-install pop-up
 - Keep "Sync" enabled
 - Don't add the default rules

SwitchyOmega 2.3.16
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2541.0 Safari/537.36

**Comment by FelisCatus** [comment]
SwitchyOmega should immediately use the uploaded options in that case. If not, it is more likely to be a network issue that prevented the download process, leaving SwitchyOmega no choice but to initialize using the default options.

The sync storage is managed by Chrome (and also Google's servers) and cannot be controlled by SwitchyOmega. Thus I'm closing this issue for now. Please let me know if there are better ways to handle this.

**Comment by wernight** [comment]
I tried again on a new Chrome profile using my existing account which has sync enabled. Still noted that:

1. It opened a tab after installing the extension (which is fine if you never installed it but I installed it and it can know that by synching profile)
2. Sync wasn't enabled in Omega settings
3. After enabling sync in Omega settings, my existing/old profile settings didn't appear

**Comment by FelisCatus** [comment]
In step 2, if it says "Enable Syncing" instead of "Download remote copy", then the sync storage is definitely not populated. Please recheck the syncing settings in your old device and make sure that it is enabled. Give it some time to upload the data after you enable it, before initializing SwitchyOmega on another device.

If you do have syncing enabled but it still won't download, either the uploading side or the downloading side has a network issue. SwitchyOmega does not have access to the syncing status and cannot report these issues due to the design of extension storage. Sorry for that.

**Comment by wernight** [comment]
On my other machine it's "Your options are automatically synchronized with your other devices." for days already and Chrome sync is working (I can see recent tabs for example).

On my new device, I didn't see the "Download remote copy" option.

Have you tried with a sync profile that is password protected by any change?

**Comment by FelisCatus** [comment]
I think I am using password encrypted Chrome sync. I remember when I tried to setup a new device, it asks me to enter my password in Chrome settings. Please check the Sign in section in Chrome settings for anything like that.

Anyway, password encryption is also transparent to extension level. For the extension, it can only check the `chrome.sync` storage and see if settings are put there. If not, well, too bad.

**Comment by wernight** [comment]
I agree it should just work but I'm sure it didn't and everything else synched correctly (tried twice). Would you mind adding a profile to your Chrome or installing Chrome in VM to test?

**Comment by FelisCatus** [comment]
Just tried that with my Google account with password enabled. I had to input my password and restart Chrome before the extensions were automatically installed, but everything else worked fine for me. I got all my SwitchyOmega settings back.

**Comment by wernight** [comment]
Did it show the welcome screen of SwitchyOmega when it auto-reinstalled the extension?

**Comment by FelisCatus** [comment]
Yes, I think. This should be fixed later.

**Comment by wernight** [comment]
I can confirm that it worked on one install of Chrome. Not sure what are the steps that make it not work but seems working.

**Comment by FelisCatus** [comment]
Glad to hear that. It might be a Chrome update that fixed the syncing problem.
