### ISSUE TITLE
能否为切换规则加入分组？

### ISSUE THREAD

**Issue by Cod1ng** [FelisCatus/SwitchyOmega#623]
为切换规则建立分组，这一个分组放哪些网站，那一个分组放哪些网站，这样当网址多了之后，看着不会那么乱

**Comment by FelisCatus** [comment]
可以建立多个自动切换模式，每个放对应的规则。然后自动切换1的默认情景模式设置为自动切换2，2=>3，3=>4，……N=>直接连接，如此形成一个链就可以了。
