### ISSUE TITLE
SwitchyOmega在其他网络可以使用，但是在我家里的网络不能使用。

### ISSUE THREAD

**Issue by qiyadeng** [FelisCatus/SwitchyOmega#625]
不知道是不是DNS污染的原因？
请问如何确定？是否有办法可以解决。

**Comment by celeron533** [comment]
说下网络环境啊。。。大哥。。。你是范樯还是一般代理啊，有没有装迅雷？是不是win10

**Comment by FelisCatus** [comment]
代理服务器或网络问题，与 SwitchyOmega 无关。 SwitchyOmega 是一个代理设置软件，并非网络通信软件。遇到此类问题请检查代理服务器工作情况，具体建议谷歌、百度或者到其他相关的论坛提问。
