### ISSUE TITLE
配置每次启动chrome都会丢失

### ISSUE THREAD

**Issue by happysearch** [FelisCatus/SwitchyOmega#626]
用这个插件很久了，最近升级后发现每次重启chrome后配置会回复到初始安装SwitchyOmega状态，重装过chrome，甚至重装了系统都没解决，不知道为什么?

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by FelisCatus** [comment]
请检查是否有垃圾清理软件等自动或定期清理“浏览器缓存”等项目。这种清理可能会错误地清空扩展设置。

由于这并不是一个 SwitchyOmega 可以解决的问题，所以先关闭好了。有问题可以继续讨论。

**Comment by FelisCatus** [comment]
#627
