### ISSUE TITLE
配置每次启动chrome都会丢失

### ISSUE THREAD

**Issue by happysearch** [FelisCatus/SwitchyOmega#627]
昨天反馈了个配置丢失的问题，今天终于是找到原因了，是因为我安装的 CCleaner这个自动系统垃圾清理工具造成，Sorry！

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by celeron533** [comment]
你没有必要新开个ticket，在原先的ticket下回复就行了
