### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by Macry** [FelisCatus/SwitchyOmega#628]
Chrome浏览器，shadowsocks2.5.8 PC客户端，当使用系统代理时可以正常链接，其他模式无法连接！

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by q505507538** [comment]
附上你配置看看

**Comment by Macry** [comment]
​

2015-11-03 11:13 GMT+08:00 q505507538 <notifications@github.com>:

**Comment by zhenhappy** [comment]
@Macry 怎么是空的什么都没有

**Comment by FelisCatus** [comment]
#557.

**Comment by Macry** [comment]
按照#557的办法，改为http代理，问题解决！我的是WIN7系统，而且之前用也一直没有出现过问题，不知道为什么今天突然无法使用！感谢楼上各位的热心回复！
