### ISSUE TITLE
omega跟最新版的chrome可能有冲突

### ISSUE THREAD

**Issue by wenjun5280** [FelisCatus/SwitchyOmega#629]
配合Shadowsocks使用时代理填写的是socks5,无法打开网站，用360浏览器的时候没问题，goagent代理也无法打开一些网站，重新删除chrome账号再登录安装omega后又可以使用，但是使用一段时间后又无法打开网站了，不知道什么，能否解决下，怀疑是跟chrome有冲突，因为使用360极速浏览器时没问题，配置和插件都是一样的

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by FelisCatus** [comment]
#557.
