### ISSUE TITLE
General Settings - Network requests - Show count of failed requests ignored

### ISSUE THREAD

**Issue by jakubklos77** [FelisCatus/SwitchyOmega#630]
Hello
the option "Show count of failed web requests for resources in the current tab.
A yellow badge will be displayed on the icon if some resources fail to load,
and you can set the profile for such resources conveniently via the popup menu." seems to be ignored.

I have it disabled and it still displays a number of failed resources. Can you please fix it?
Thank you very much

Jakub

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by FelisCatus** [comment]
Does closing and restarting Chrome help? You may check the process list to ensure Chrome is completely shut down before relaunching.

If not, please give a screenshot of your settings in the relevant section.

**Comment by jakubklos77** [comment]
After restarting the number is gone but the settings option is On/Checked again. So it seems it is not remembered. Can you please confirm?

**Comment by FelisCatus** [comment]
Sorry, I cannot reproduce this on my side. Any screenshots or other information?

Also, if you are using settings sync, try disabling it. Syncing can introduce conflicts some time.

**Comment by jakubklos77** [comment]
After fiddling witht the settings and creating proxy profiles it all started working properly. I upgraded from your previous version a week ago, then converted to Linux and didn't have the time to setup the profiles and all. But after configuring everything and restarting Chrome it all works.
Sorry for the hassle.
Great addon btw!
Thank you

**Comment by FelisCatus** [comment]
Looks like a temporary syncing issue that resolved over time. Anyway, I'm glad it finally worked for you. You are welcome.
