### ISSUE TITLE
切换规则列表是否可以收起来

### ISSUE THREAD

**Issue by Arnaud-Github** [FelisCatus/SwitchyOmega#631]
列表很多 加载比较慢 而且总提示此情景模式使用存储空间过多，因此无法进行同步。
是否可以解决这个问题更换一个同步存储

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by FelisCatus** [comment]
选项页面加载慢的话可以试试看编辑源代码模式，只需要加载文本即可，编辑起来也不算太复杂。

至于更换存储……目前只能使用扩展设置同步存储，但可以将源代码发布到自己的服务器上（任何静态服务器均可，包括 Github pages），然后使用下方的规则列表URL来加载。

**Comment by Arnaud-Github** [comment]
@FelisCatus 我本身使用GFWList列表，如果URL加载规则，我该如何修改GFWList列表？例通配符网址

**Comment by FelisCatus** [comment]
把 GFWList 列表下载下来，修改后保存到自己的服务器上即可。

**Comment by Arnaud-Github** [comment]
编辑的格式一般是什么样的

**Comment by FelisCatus** [comment]
GFWList 的文件格式是来源于 AutoProxy ，其官方网站已经不在了，因此格式说明也没有办法访问了。请看一下[这份拷贝](http://lian-notes.readthedocs.org/en/latest/writing-autoproxy-rules-by-examples.html)中说明的文档格式是否有帮助。
