### ISSUE TITLE
与360急速浏览器有冲突，不能使用。

### ISSUE THREAD

**Issue by sammy2012** [FelisCatus/SwitchyOmega#633]
提示管理扩展，可是打不开：chrome://chrome/extensions/?id=padekgcemlokbadohgkifijomclgjgif

![image](https://cloud.githubusercontent.com/assets/12810762/10988659/584ffde8-8479-11e5-8ced-34db4bc2d02b.png)

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by FelisCatus** [comment]
请点击管理扩展按钮，检查所有代理设置的扩展（包括部分去广告扩展），然后禁用它们。如果不知道哪些扩展冲突，请将 SwitchyOmega 以外全部禁用掉，然后逐个启用来定位。
