### ISSUE TITLE
希望可以学习下 Surge 根据关键字自动加入翻墙。

### ISSUE THREAD

**Issue by wclebb** [FelisCatus/SwitchyOmega#634]
可以根据域名中的关键字，自动拉入代理。
我觉得这样很不错哩。
比较智能。

**Comment by FelisCatus** [comment]
现在 SwitchyOmega 已经可以支持多种代理规则（包括关键词规则），也可以通过导入 GFWList 等列表来自动使用很多规则。遇到无法访问的网站或资源也可以通过菜单加入到规则里。

不知道您说的根据关键字自动加入翻墙具体是指什么？Surge 项目我不清楚，之前从来没接触过，请问您是否可以简单介绍下 Surge 的这项功能？ SwitchyOmega 可以学习哪些，在目前基础上做出什么样的改进？

**Comment by celeron533** [comment]
域名关键字？用url regex应该可以解决的

**Comment by wclebb** [comment]
感谢回答，有空可以试试你们说的方法

**Comment by FelisCatus** [comment]
我先关闭这个了。如果有任何改进建议请重新开启并提出。
