### ISSUE TITLE
“此情景模式使用存储空间过多，因此无法进行同步”

### ISSUE THREAD

**Issue by gameboy709494** [FelisCatus/SwitchyOmega#635]
此情景模式使用存储空间过多，因此无法进行同步。

额，怎么办？？

如果我有自己可读可写的ftp服务器，可以把同步资料放在ftp上么？？

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36

**Comment by FelisCatus** [comment]
目前只能使用扩展设置同步存储，但可以将通过将规则列表和PAC等比较大的文件发布到自己的服务器上（任何静态服务器均可，包括 Github pages），然后使用URL来加载的方式减轻一些负担。 FTP 服务器好像是不行的，必须要 HTTP 服务器。

**Comment by gameboy709494** [comment]
谢谢你！我点击“发送规则列表”，然后把列表push到我的个人仓库，然后再回到插件这边指定我的仓库raw URL。以后我累积满了我再增加至规则列表的尾部并更新到仓库即可。

谢谢你！

**Comment by gameboy709494** [comment]
但是那个警告“此情景模式使用存储空间过多，因此无法进行同步。”并没有消失，等下我关闭并重新打开浏览器再看看这个警告存不存在。

**Comment by gameboy709494** [comment]
我跑到了另外一台电脑上看了一下，

“规则列表网址”设置同步过去那边了。
但是“切换规则”的设置那边看起来并没有改变，换句话说，我这边删除的“切换规则”的改动没有同步过去。

**Comment by FelisCatus** [comment]
目前一旦某个情景模式被标记为占用过多存储，此标记就不会消失，因为程序无法判断使用的存储空间是否减少了。建议删除此情景模式，然后建立一个不同名称的新情景模式使用。

**Comment by siaimes** [comment]
我的规则列表里面才73条规则就触发了这个提示，是我配置有问题还是可用存储空间就这么多呢？

**Comment by yfdyh000** [comment]
@siaimes 你可以导出看看。规则订阅也占用，gfwlist几百KB。

**Comment by siaimes** [comment]
> @siaimes 你可以导出看看。规则订阅也占用，gfwlist几百KB。

我已经将gfwlist单独作为要给情景模式了，这个几百KB应该不冲突，而且gfwlist本身是不会被同步的，只会同步gfwlist网址。现在的情况是无法匹配auto switch的时候再跳转到gfwlist，gfwlist无法匹配就直连，这样auto switch除了自己添加的几十条规则什么也没有。

**Comment by siaimes** [comment]
> @siaimes 你可以导出看看。规则订阅也占用，gfwlist几百KB。

不过我把auto switch导出来只会有567KB。

**Comment by siaimes** [comment]
![image](https://user-images.githubusercontent.com/34199488/61424215-60009800-a945-11e9-8509-732a8e3ee090.png)
![image](https://user-images.githubusercontent.com/34199488/61424273-8c1c1900-a945-11e9-80bc-32a845fd9aeb.png)

我是这样配置的，然后我将auto_switch导出为PAC之后发现里面包括了整个gfwlist，是我这样配置不行还是switchyOmega有bug呢？

**Comment by siaimes** [comment]
@FelisCatus 你好，能帮我解决一下我的问题吗？
