### ISSUE TITLE
有个小问题需要反馈一下

### ISSUE THREAD

**Issue by TyleRxYan** [FelisCatus/SwitchyOmega#636]
首次使用的时候在线更新列表必须开启其他代理才能访问更新网站, 问一下如果我把在线更新列表频率设置为一天一次, 第二次第三次更新会不会出同样的问题?

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by FelisCatus** [comment]
应该不会吧，更新情景模式是也是网络请求，会使用当前代理进行。如果保持自动切换模式并且将规则列表本身的地址添加到规则中，应该就可以正常更新了。
