### ISSUE TITLE
【好像遇到了Bug】关于“此情景模式使用存储空间过多，因此无法进行同步”

### ISSUE THREAD

**Issue by gameboy709494** [FelisCatus/SwitchyOmega#637]
一旦触发“此情景模式使用存储空间过多，因此无法进行同步”事件，即使你将该情景模式中的“切换规则”“清空”并仅添加一两条记录，但是也不能消除警告“此情景模式使用存储空间过多，因此无法进行同步”，且修改之后的状态无法同步。

详情请见

Issue 635: https://github.com/FelisCatus/SwitchyOmega/issues/635#issuecomment-154831025

我在原issue下comment了几个，不知道你们这边能否看到，所以我就再submit了一个new issue。

**Comment by FelisCatus** [comment]
我在你的 comment 那边回复了具体的问题和解决方案。放心，任何评论都是有邮件通知的，看得到。

您将这个问题作为新的 issue 提出也是非常合适的，不过此问题[在此评论中](https://github.com/FelisCatus/SwitchyOmega/issues/272#issuecomment-73845317)已经有记录了，所以我就暂时关闭这里了。如果还有问题建议在 #272 或者 #635 讨论。

**Comment by gameboy709494** [comment]
好的！
