### ISSUE TITLE
PAC Download Cached

### ISSUE THREAD

**Issue by 1h8fulkat** [FelisCatus/SwitchyOmega#638]
I recently updated one of our PAC files, I noticed that the old PAC file is now cached within Chrome while I am using SwitchyOmega.  When I download the PAC file via the URL in Chrome while SwitchyOmega is installed I get the old version, after uninstalling it I get the correct version.  I assume this is hard coded or cached in the plugin somehow.  I do not have this issue with other browsers.

**Comment by FelisCatus** [comment]
PAC files are now cached in SwitchyOmega, and updated each time Chrome starts or every 12 hours by default. The download interval can be configured in Options > General where it can be changed to as frequent as 15 minutes. You can always update a PAC profile immediately using the Download Profile Now button in Options > (your profile).

Also, when you choose a PAC profile from the popup menu, the PAC file will be immediately updated in the background and applied when the download finishes. In other words, select the PAC profile twice in a row will also clear the cache.

If none of the features above covers your use case, please let me know the exact use case. We can discuss to find out a better solution.

**Comment by 1h8fulkat** [comment]
None of the above is what I am experiencing.  I have gone so far as to completely delete that PAC file profile and completely restart the machine.  When I configure the URL to download the PAC file again, I am seeing an old version of the file which no longer exists anywhere on the network.  Infact, when performing a wireshark capture and clicking "Download" I never see my machine make a request to the server hosting the PAC.  The only explanation is that the extension, or chrome, has cached it somehow.  Using IE and FF, I can get it just fine.

**Comment by FelisCatus** [comment]
@1h8fulkat Then it is definitely not SwitchyOmega's fault. Personally I would blame Chrome for caching the URL. Could you try changing the URL somehow? For example, `http://example.com/test.pac` => `http://example.com/test.pac?_=12345`

**Comment by FelisCatus** [comment]
I'm closing this issue now because it seems to Chrome's fault. Please re-open if you have anything to add.
