### ISSUE TITLE
翻墙服务器正常但使用插件的自动切换后无法翻墙

### ISSUE THREAD

**Issue by q891541372** [FelisCatus/SwitchyOmega#639]
选择ss的全局模式或插件的系统代理都可以正常翻墙，但是使用自动切换时就无法加载
这个问题会随机出现，不更改任何设置能用几天然后又不能用几天所以应该和端口之类的没关系
chromee 46.0.2490.86 dev-m
Proxy SwitchyOmega 2.3.16

**Comment by saiddy** [comment]
我也出现这个问题，正准备反馈。
插件中的自动切换和直接使用代理全局都不能正常翻墙，只能选择使用系统代理。
chrome版本46.0.2490.86 m
SwitchyOmega 2.3.16

**Comment by FelisCatus** [comment]
@saiddy 的问题是 #557 ，和 @q891541372 说的不是一回事。

**Comment by FelisCatus** [comment]
@q891541372 的问题像是切换规则的问题。如果在使用规则列表或者 GFW List 之类的，请说明一下详细情况。另外也有可能是网络问题导致更新规则列表失败，或者下载的文本并非规则列表（比如被运营商劫持变成了广告）。

**Comment by q891541372** [comment]
使用的是GFW List.之前一直正常使用的,上周没更改任何设置的情况下突然无法使用,我就使用ss的全局代理模式将规则列表更新了,规则列表正常,切换规则原本只有一条*google现已删除,依然无法使用,我看了下也本地端口也没有冲突,

**Comment by FelisCatus** [comment]
请到设置>自动切换中，点击导出PAC文件按钮，并将结果上传到这里。

**Comment by q891541372** [comment]
[OmegaProfile__.txt](https://github.com/FelisCatus/SwitchyOmega/files/35275/OmegaProfile__.txt)

**Comment by FelisCatus** [comment]
我这里检查运行了一下PAC文件，不像是有问题。请先确认一下菜单里选中的是自动切换模式，然后打开`chrome://net-internals/#proxy`查看一下代理设置是否正确。（可能会被其他扩展的设置覆盖。）

**Comment by q891541372** [comment]
这是代理设置的图片,全都一样,使用系统代理就能连情景模式里的就不能,也是迷...
![qq 20151116173145](https://cloud.githubusercontent.com/assets/15154455/11178566/8f704cbc-8c88-11e5-9283-97517ecd3840.png)
![qq 20151116173201](https://cloud.githubusercontent.com/assets/15154455/11178567/8f70e83e-8c88-11e5-92d5-daa9eb21a1fc.png)

**Comment by FelisCatus** [comment]
确定一定以及肯定在弹出菜单里选择的是自动切换吗？

**Comment by q891541372** [comment]
这是图
![qq 20151116180000](https://cloud.githubusercontent.com/assets/15154455/11179113/213f0478-8c8c-11e5-8e34-2b4b42f12d67.png)
![qq 20151116180039](https://cloud.githubusercontent.com/assets/15154455/11179112/20ed97aa-8c8c-11e5-9f3e-1b9bf4e014aa.png)

**Comment by FelisCatus** [comment]
请在菜单中选择自动切换模式，然后**右键**点击图标，点击“保存错误日志”，然后把日志上传到这里。

**Comment by q891541372** [comment]
刚刚发现按照https://github.com/FelisCatus/SwitchyOmega/issues/557 这里面说的将socks5改为http就好的,但是我的操作系统是win7,然后查看端口只有ss占用,迅雷没有占用,有可能是chrome后台升级导致,我又用另一台电脑将迅雷和chrome升级到最新版,使用socks5连接却没有问题
[Uploading OmegaLog_1447671285266.txt…]()

**Comment by q891541372** [comment]
的确是迅雷的问题.安装迅雷之后就莫名其妙不能使用的,使用Switchy Sharp也是同样的问题

**Comment by FelisCatus** [comment]
@q891541372 很遗憾日志文件没有上传成功。

P.S. 假设真的是迅雷的问题的话，端口未必会被占用，但SOCKS5协议确实可能会不可用。如果您确认是迅雷的问题，那可以把这个关掉。

**Comment by uniquepengpeng** [comment]
确实,我是装了迅雷极速版也出现这个问题。。。关了相关进程也不行(可能没关干净.)卸了才好.不知道有什么共存的方案没?

**Comment by celeron533** [comment]
@uniquepengpeng 需要在系统服务中停止并禁用XLServicePlatform服务。注意，每次迅雷更新会重启该服务。
![image](https://cloud.githubusercontent.com/assets/3608762/11323824/89c2297c-9159-11e5-9f39-db7b2aad4b6a.png)

**Comment by uniquepengpeng** [comment]
@celeron533 OK,thanks !

**Comment by FelisCatus** [comment]
看起来是迅雷的问题，先关闭了。

**Comment by oliwill** [comment]
一样的情况，只能使用[系统代理]才能正常访问完整的互联网，使用 auto switch 就没办法了。
公司电脑是 Windows 7，自己的 Mac 更严重，使用系统代理也没法正常访问。
（两边都没有按照迅雷

[OmegaLog_1531286108850.txt](https://github.com/FelisCatus/SwitchyOmega/files/2183044/OmegaLog_1531286108850.txt)

**Comment by AlieinApril** [comment]
我也是这个问题，莫名其妙，proxy和系统代理都可以，但是switch固定网址切换到proxy就不能上了，我晕
