### ISSUE TITLE
lantern能不能实现自动切换呢

### ISSUE THREAD

**Issue by rainsun007** [FelisCatus/SwitchyOmega#641]
我现在在使用lantern 
在使用自动切换功能时失败    使用直接连接和系统代理是没有问题
是我设置的不对  还是现在支持呢

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by FelisCatus** [comment]
请先检查代理服务器是否工作正常，然后再切换到指向Lantern的那个情景模式，看看是否可以正常访问。

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
