### ISSUE TITLE
杭州无法使用了

### ISSUE THREAD

**Issue by cwtuan** [FelisCatus/SwitchyOmega#643]
地点：杭州
在没有改任何配置的情况下，已经好几天无法使用SwitchyOmega，请帮忙检查原因

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega只是个代理服务器管理程序，至于你要怎么访问那些不存在的网站不在讨论范围内。

**Comment by FelisCatus** [comment]
感谢 @celeron533
