### ISSUE TITLE
运行很慢

### ISSUE THREAD

**Issue by Alyyyyyy** [FelisCatus/SwitchyOmega#644]
装上OS之后设置成自动切换模式，浏览未屏蔽网站如baidu等也很慢，搭配使用的XX-Net，是我设置出了问题吗？是很慢很不流畅的那种。

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by FelisCatus** [comment]
不像是SO的问题，更像是网络或者代理服务器。

**Comment by celeron533** [comment]
看上去像是规则设置错误，全局代理，所有流量都走了代理。
