### ISSUE TITLE
為啥不直接用autoproxy的UI設計

### ISSUE THREAD

**Issue by zzzgit** [FelisCatus/SwitchyOmega#645]
在實際使用中,遇到一個問題
我平常喜歡用「``自動切換``」模式,因為在這個模式下,國內網站就不會走代理
但是根據網絡環境的不同,我經常更換所使用的代理軟件
那麼,端口就不同了,也就是情景模式不同
更換軟件的時候,可否在保持使用「``自動模式``」的前提下,快速設置``swithOmega``,使之馬上變得可用
**不行**
>>``autoproxy``則可以,直接選一下工具欄菜單就可以了

**Comment by zzzgit** [comment]
:mouse:
>我還以為`Omega`相對`sharp`有啥革命性的創新
>結果UI方面是**一樣**的

**Comment by FelisCatus** [comment]
建立一个虚情景模式名为“国外网站”，指向你现在正在使用的代理，然后点击迁移到虚情景模式就可以了。以后更换所使用的代理软件只需更改虚情景一处，且可以很方便地在弹出菜单里修改。这是 SwitchyOmega 可以做到但 SwitchySharp 做不到的。

至于为什么不采用AutoProxy的UI设计……我只能说这是两个不同的软件，是各自独立设计和开发的，有不同的目标和设计理念。

我至今还是觉得 AutoProxy 有很多值得学习的地方，我也听取了AutoProxy用户的很多建议并改进了产品。请说出你的应用场景，AutoProxy如何优雅地解决这个问题，或是SwitchyOmega可以怎样做得更好，我们可以共同讨论改进。不过直接推翻重来，做一个 AutoProxy 的复刻版，显然不是此项目的目标。

**Comment by zzzgit** [comment]
你這樣操作,還是沒有滿足 國內網站不走代理 這個要求
而且,也用不著搞虛擬場景,普通場景一樣可以在菜單中切換

**Comment by FelisCatus** [comment]
* 自动切换模式（请在菜单中选中这个）：
  * 规则列表（如GFWList） => 国外网站
  * 自己添加的一些规则 => 国外网站
  * 默认（国内） => 直接连接
* 国外网站（虚情景） => Shadowsocks, etc...
  * 指向的目标（具体代理）可以在菜单中灵活调整。
