### ISSUE TITLE
Different proxies for different tabs

### ISSUE THREAD

**Issue by Bargest** [FelisCatus/SwitchyOmega#646]
Suggestion.
Sometimes I need to enter some site with a sertain proxy. SwitchyOmega has ability to enter a site and then select proxy for this site. This proxy would be remembered for host. But the first connection will be done using standard settings for this URL, and it's unacceptable. If I select a static proxy profile, all other tabs automatically switch to the new proxy and some of them fail loading because of this proxy (it can be blocked by sites, opened in other tabs)
To avoid this, I have to:
1) Select "Autoswitch"
2) Add custom rule to autoswitch for sertain URL
3) Enter the site
After leaving the site:
4) Remove the useless rule (If I don't need to enter this site again further)
5) Disable "AutoSwitch"
It is not comfortable. A possible solution for this usecase - ability to select proxy for certain tab and remember the choice for it until tab is closed. Also it would be useful to apply the same proxy to a new tab, opened from one with such proxy selected (if possible, of course).

Maybe this one is somehow similar to #10 , but it's a bit different

**Comment by FelisCatus** [comment]
Tab information is not available for PAC scripts, so this cannot be implemented in SwitchyOmega. Thanks for the suggestion anyway.

**Comment by FelisCatus** [comment]
I would also like to point out that incognito windows use separate proxy settings in Chrome and thus #10 is technically possible. That's a different story though.

**Comment by FelisCatus** [comment]
See #1543 which tracks the request to add this feature on Firefox. It's not possible on Chrome though.

**Comment by arsalanrashid-max** [comment]
I built a Chrome extension for this exact use case: IP per Tab. It assigns a separate residential IP per tab at the extension layer instead of via PAC, with no manual proxy config needed. Might help others who landed here looking for this.
