### ISSUE TITLE
创建PAC情景模式,输入pac网址,chrome就崩溃退出.

### ISSUE THREAD

**Issue by JillCheng** [FelisCatus/SwitchyOmega#647]
重装了chrome和扩展一样的问题。win7 64 chrome版本 46.0.2490.86 m

**Comment by celeron533** [comment]
特定网址？

**Comment by FelisCatus** [comment]
???

**Comment by JillCheng** [comment]
@FelisCatus   @celeron533 
使用以下的服务,里面几个pac都会出现这种情况
https://github.com/akar1nchan/gfvvlist
![QQ截图20151127140550.png](https://ooo.0o0.ooo/2015/11/27/5657f5330d714.png)
![QQ截图20151127140724.png](https://ooo.0o0.ooo/2015/11/27/5657f5332030d.png)

**Comment by FelisCatus** [comment]
无论如何先升级下 Chrome 吧……我记得几个版本之前的 Chrome 有这个问题，现在已经修复了才对，有可能是回归。如果升级后还有这个问题就试试看 Chrome Dev 或者 Canary ，还不行就把崩溃报告发到 Chrome 那边，他们会看。
