### ISSUE TITLE
莫名其妙的规则列表就乱码了

### ISSUE THREAD

**Issue by zhanxiage233** [FelisCatus/SwitchyOmega#649]
刚才用360极速浏览器上网发现不能打开u2b，一看才发现规则列表乱码，可以立即更新规则但是还是乱码
打开360安全浏览器，更新规则都是一切正常，有人知道这是什么问题？

**Comment by zhanxiage233** [comment]
之前保存有配置文件，导入进去可以恢复正常，但是立即更新规则就又乱码了

**Comment by zhanxiage233** [comment]
https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt 用这个地址更新出来就是乱码
换这个https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt就行了
为什么啊

**Comment by celeron533** [comment]
@zhanxiage233 你贴的第一个链接只不过是用base64编码了一下而已。内容是一样的。

**Comment by zhanxiage233** [comment]
@celeron533  但是我以前一直用的第一个地址，一切正常；现在360安全浏览器用第一个地址也没问题，就是极速浏览器更新规则就成了未编码的样子

**Comment by zhanxiage233** [comment]
我看了一下，自动更新规则间隔设置的是12小时
我昨天正好升级了360极速浏览器，难道是浏览器本身的问题？

**Comment by zhanxiage233** [comment]
目前就导入以前的备份然后关闭规则自动更新使用吧，我猜测是浏览器本身的bug

**Comment by celeron533** [comment]
有可能是bug

**Comment by FelisCatus** [comment]
我这边更新`https://autoproxy-gfwlist.googlecode.com/svn/trunk/gfwlist.txt`这个地址是好的……SwitchyOmega更新规则列表这边有自动Base64解码的功能，通常情况下不应该出现大段Base64。估计是网络原因导致下载数据损坏，所以没有办法正常解码吧。试试看选择一个全局代理模式然后再点更新。

**Comment by zhanxiage233** [comment]
@FelisCatus  刚才又试了下手动立即更新，又没问题了...昨天很奇怪，一个360安全浏览器能正常更新，另外一个360极速浏览器就是不行，全局代理也试过了，两个浏览器一样的设置，但是极速浏览器更新结果就是未解码的样子

**Comment by FelisCatus** [comment]
看上去是偶然的浏览器故障或者网络问题。暂时先关闭这个了。
