### ISSUE TITLE
Socks5 IPV6 不支持

### ISSUE THREAD

**Issue by qiukun** [FelisCatus/SwitchyOmega#65]
polipo 转成 http 代理就可以了，不解

**Comment by FelisCatus** [comment]
这边还是不能用吗？可以把 `chrome://net-internals/#proxy` 的内容复制一下再贴到这里。为了保护个人隐私，可以把 IPv6 地址的每一位都改成 `f` （但是尽量不要改地址格式，我想看看是否是和地址格式有关。）

**Comment by FelisCatus** [comment]
这边到底要怎么办……能不能给个回应。哪怕最后发现是Chrome的问题也行啊……

**Comment by FelisCatus** [comment]
Closed per OP's request. The issue cannot be reproduced any more.

**Comment by blueveryday** [comment]
yes, the socks5 don't support the IPv6 server.
I change the socks to http , and then well done.
