### ISSUE TITLE
自动切换模式打开墙内网站速度特别慢

### ISSUE THREAD

**Issue by stefanielyq** [FelisCatus/SwitchyOmega#654]
启用了自动切换模式
（现在自带的切换规则都是不带*的？老版本好像是需要的- -？）
![image](https://cloud.githubusercontent.com/assets/16235150/11707260/e4c88de8-9f3c-11e5-954a-34da64b97a3a.png)
然后打开墙内网站的时候速度也很慢 优酷2分钟都打不开- -
是不是设置出了问题？

**Comment by celeron533** [comment]
你的规则列表（那个可以打勾的）里有些什么东西？

**Comment by gameboy709494** [comment]
最近我也发觉特别慢，尤其是打开淘宝的时候。
我发现浏览器左下角会提示“正在等待Localhost的响应”，我好奇怪为什么会等待localhost的响应呢？我并没有一些资源在localhost，我的shadows5的客户端在开发板(192.168.0.210)上面啊。

我的系统:Win 8.1 x64, chrome 版本 46.0.2490.86 m。ESET 9 杀毒套装.

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by FelisCatus** [comment]
在打开淘宝的时候，请看一下图标上的颜色，确认是否在使用代理。然后也可以将鼠标悬停在图标上，会提示匹配的规则。如果和预期的不一致请检查规则列表中的相应规则。

**Comment by gameboy709494** [comment]
好像这个问题仅存在在Win 8.1。
我Ubuntu和WIn7都不会出现这个问题。
而SwitchyOmega的设置都是同步的。

**Comment by FelisCatus** [comment]
那我真怀疑是 PAC 文件编译慢，或者是因为 Windows 开 socket 慢了……

**Comment by celeron533** [comment]
@FelisCatus 或者又是迅雷影响了SS？

**Comment by gameboy709494** [comment]
@FelisCatus 那我可以请教你一下，有什么工具/方法可以检查我这边载入速度慢的原因是出在哪个环节吗？

**Comment by FelisCatus** [comment]
坦白说，我个人只对Chrome扩展这边有点研究，对于网络和代理协议什么的不是很清楚……以下内容仅供参考。

检查 PAC 文件编译/执行所花费时间的大致方式是观察页面载入时左下角的提示。如果有类似`proxy script`或者`resolving proxy`字样的提示时，此时Chrome正在加载/执行PAC。这个环节的花费时间主要和Chrome版本，CPU资源，内存资源这三者有关。

检查网络请求的实际花费时间，建议使用网络抓包软件（如 Wireshark 等）。此外，如果使用代理软件的情况，建议查看代理软件的日志输出等。也可以自己搭建一个 SS 服务器只用来访问本地的资源以排除网络问题/墙的干扰。

**Comment by celeron533** [comment]
最近我发现国内的DNS也经常鬼畜啊。。。

**Comment by xilin** [comment]
我感觉我这边自动切换模式下时不时墙内的也走成代理了。用的astrill，它家客户端上明显能看到我访问墙内网站时也有流量在走

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36

**Comment by FelisCatus** [comment]
@xilin 先看图标颜色来确定当前页面是否使用了代理。如果使用了代理，可以鼠标悬停在图标上看匹配了哪一条规则，然后如果是自定义规则的话进行修改，如果是规则列表规则的话去维护者那边反馈。

页面内的资源也可以走代理，不过要定位这个会更复杂一些。如果是页面上可见的元素，如图片等可以直接右键检查代理，如果是脚本的话就只能依靠手动判断或者抓包了。

**Comment by celeron533** [comment]
@xilin Astrill我记得是VPN啊，整个操作系统默认都走在隧道里啊。SwitchyOmega只能控制web代理服务器的流量走向啊。

**Comment by xilin** [comment]
@celeron533 Astrill有openweb模式

**Comment by xilin** [comment]
@FelisCatus 我再调查看看，谢谢！

**Comment by celeron533** [comment]
@xilin 哦，是我孤陋寡闻了

**Comment by FelisCatus** [comment]
@xilin 有什么新发现吗？

**Comment by xilin** [comment]
@FelisCatus 最近Astrill Openweb基本废了= =有什么发现立马上报哈

**Comment by FelisCatus** [comment]
@xilin 好吧……

那么 @gameboy709494 那边呢？有没有查出加载速度慢的原因？

**Comment by celeron533** [comment]
@xilin Astrill表示有些事情要做的低调，而不是像某些人整天在那边作死高调炫耀。

> Dear China customers,
> Due to increased censorship, use of VPN from China may not be possible at this time. We believe the situation will be back to normal after the holidays. While our engineers worked tirelessly to fix "issue" with our iOS app, some users were not that smart and helping Chinese censors by spreading news about new Astrill software all over the web. It appears some of the customers show no appreciation for our efforts nor they want open internet. Now you got what you asked for... It's not working anymore.
> We can invent new technologies, we can defeat GFW but we don't have a solution for stupidity. Dear "journalists" please spread this message as usual, all over the web and join DUMB CLUB.
> We wish you great holidays!

**Comment by xilin** [comment]
@celeron533 这是过年时候的通知了吧。最近这次是两会。。

**Comment by gameboy709494** [comment]
很久之前的事情了，我现在已经没有受到类似的困扰了。

但是我的确记得某个服务导致类似的现象，就是阿里旺旺聊天软件，这个软件可不仅仅聊天那么简单，这个软件安装过程会添加一个系统服务在后台运行。把这个服务关掉就不会有问题了。

等一下我作个死安装阿里旺旺看看，看看能不能复现问题，无论与否，我也会回来edit comment.

自动切换规则下速度慢的原因可能是“错综复杂”的，如果你遇到类似问题，不妨参考一下我这里。然而没有人能保证我这个案例适用于其他人。

**Comment by DavidSuccess** [comment]
我这边也还有这个问题，不只是taobao,，当我访问很多国内大网站的时候， 都有这种问题……设置自动切换模式的时候，当我访问国内网站，插件上显示的是不走代理，但是不知道为何速度特别慢，还经常显示有很多资源没有加载，不知为何……

**Comment by celeron533** [comment]
@DavidSuccess 那不用代理访问国内的时候呢？难道运营商有问题？

**Comment by DavidSuccess** [comment]
@celeron533  @FelisCatus 应该不是运营商问题吧。
1.如果不用代理访问国内，速度很快，很正常。
2.如果用代理访问国内也可以，相比情况1 速度稍逊色，但是不至于很慢加载不出来。
3.如果用SwitchyOmega 自动切换模式，再访问国内网站，此时插件已经显示不走代理了，但是速度就奇慢，还显示很多资源加载不出来，反复刷新几次可能会好，但是这种问题经常出现。

**Comment by FelisCatus** [comment]
建议看一下未加载的资源列表然后记录一下域名。之后，可以看看自动切换里是否有匹配的规则。

还有一个方式就是（先启用SO右键菜单选项然后）右键点击加载不出的图片/视频等，然后选择检查该元素使用的代理。此时图标（以及悬停提示）的情况会反映那个元素的代理情况。

**Comment by xilin** [comment]
@FelisCatus 最近Astrill更新后又试了试，应该是Astrill本身设置的问题
它的客户端里有个Browsers选项，选中Chrome以后无论SwitchyOmega怎么选都会走代理

**Comment by FelisCatus** [comment]
@xilin 我很好奇 Astrill 客户端是怎么做到的……以及，能帮忙看一下`chrome://net-internals/#proxy`里面的内容吗？我想知道里面的设置是SO提供的还是 Astrill 的。

**Comment by xilin** [comment]
@FelisCatus 我也不知道它怎么做的。开启Astrill的Browsers选项后，在SwitchyOmega选Direct，`chrome://net-internals/#proxy`的结果是

```
Effective proxy settings

Use DIRECT connections.
```

**Comment by FelisCatus** [comment]
感觉就像加了特技一样……既然不是改浏览器代理设置，那么又会是什么呢……？强行用某种方式，在系统层面之类的拦截浏览器发送的请求？

**Comment by xilin** [comment]
我觉得以前是没特技的，以前正常的时候Chrome里走Direct可以明显看到速度不是走proxy的速度。但是这一版彻底截住了。

**Comment by FelisCatus** [comment]
我准备关闭这个了。其中一个情况已经不能复现了，而 @xilin 的情况充满了各种特技但总之和代理设置无关……应该已经可以排除 SO 的问题了。

如果有任何其他信息或者更新请回复并重新开启。

**Comment by xilin** [comment]
@FelisCatus Astrill是有这个选项会导致无视代理设置
<img width="509" alt="screen shot 2016-05-03 at 10 56 27 pm" src="https://cloud.githubusercontent.com/assets/543395/14987406/74fb2bac-1182-11e6-83c7-7d6e031b05a0.png">

**Comment by FelisCatus** [comment]
感谢更新。

看上去像是 iptables 之类的特技，于是可以肯定和 SO 无关了……那边喜欢加特技就加吧，反正只要不是代理设置层面的，我都只能看个热闹了。

**Comment by mianxiu** [comment]
虽然像是挖坟，但我就是因为这个问题找到这里，请问楼主解决了么？😣

**Comment by wwjay9** [comment]
+1，我也遇到了这个问题，我把系统重装后只安装了Chrome，问题依旧，可能是和运营商有关吧，长城宽带的

**Comment by maoyufeng1985** [comment]
2024淘宝问题依旧, 我F12显示淘宝远程地址:128.1.157.104:443, 看着是国外的ip, 但本机nslooup是国内ip. 暂时停用了.
