### ISSUE TITLE
自动切换模式的设计

### ISSUE THREAD

**Issue by imbear** [FelisCatus/SwitchyOmega#655]
假如我有三个可用代理（也许更多），需要配置成自动切换，必须先添加三个“代理服务器”，然后再添加三个“自动切换模式”，分别选上之前设置好的“代理服务器”，然后在添加相同的规则表（大都会用现成的gfwlist吧），最后就有了六个情景模式，而其中的三个“代理服务器”模式可能很少会使用的

是否能改成“自动切换模式”下能直接设置代理，这样顶多一个代理就一个自动模式，减少了一半情景模式

另外自定义规则表的能否改成单独的设置，这样每个“自动切换模式”既可以自己定义规则，也可以选择已经配置好的规则表，更加的灵活方便

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36

**Comment by FelisCatus** [comment]
请建立一个虚情景模式，名为“翻墙”，然后这个虚拟情景模式可以指向任意代理服务器，指向的目标可以在弹出菜单中方便地修改。自动切换模式中不要指向具体的代理服务器，而只需要指向“翻墙”即可。

自动切换规则目前已经是规则列表+自定义规则的模式了。自定义规则优先级高于列表规则。

**Comment by imbear** [comment]
明白了，也就是如果有N个代理自由切换，需要设置N+2个情景模式，其中N个为代理服务器 ，1个自由切换模式，1个虚情景模式。应该可以达到我设想的要求了

不过工具栏上的按钮弹出菜单，如果代理服务器多的话，菜单就有些长了，最好能设置哪些情景模式需要在弹出菜单中显示。因为代理服务器模式一般不需要显示，我只要显示一个自动模式和一个虚情景模式就可以了

**Comment by FelisCatus** [comment]
下划线`_`开头的情景模式不在菜单中显示。

**Comment by imbear** [comment]
谢谢了

Felis Catus <notifications@github.com>于2015年12月12日周六 13:58写道：
