### ISSUE TITLE
请问这个系统代理是什么意思呢

### ISSUE THREAD

**Issue by ncmon** [FelisCatus/SwitchyOmega#656]
好像用蓝灯的时候都要启用系统代理才能使用，另外这个软件是自动升级的吗好像程序上也没有看到升级按键

**Comment by celeron533** [comment]
1. 蓝灯你不开系统代理也能使用，只要你将SO里面的代理设定到本地127.0.0.1和蓝灯的端口即可
2. 如果你用的是原版google chrome，只要google play应用商店上的版本更新了，chrome会自动更新扩展程序。
其实android里面的app也是一个道理，而且google市场官方不允许app自带更新检测下载模块，所有更新都要通过google官方渠道，然而，在大天朝，你懂的。

**Comment by FelisCatus** [comment]
感谢 @celeron533 ～

补充一下，如果不是从市场装的，可以到 https://github.com/FelisCatus/SwitchyOmega/releases 这个网址下载最新的安装包。我每次发布更新时会将安装包传到这里。
