### ISSUE TITLE
在chrome中使用  浏览器左下角显示 “正在连接” 然后就卡主不动 无法加载网页

### ISSUE THREAD

**Issue by shenhuabuluo** [FelisCatus/SwitchyOmega#657]
在chrome中使用  浏览器左下角显示 “正在连接” 然后就卡主不动 无法加载网页  ，这个问题已经出现了好久了 在其他浏览器上使用 没有问题 但是在chrome上 就会卡主不动 请问有办法解决吗？插件版本是最新版本

**Comment by FelisCatus** [comment]
我只想知道你怎么在其他浏览器中使用 SwitchyOmega ……

**Comment by shenhuabuluo** [comment]
其他浏览器是指 猎豹浏览器 360浏览器 基于chrome内核的浏览器  唯独chrome本身用不了 请问有方法解决吗？

**Comment by FelisCatus** [comment]
要提出一个解决方案，我需要先明白问题是什么。

首先我感觉这像是扩展冲突问题。请先在Chrome中新建一个用户（输入网址`chrome://settings/createProfile`打开那个对话框），然后只安装 SwitchyOmega 这一个扩展试试看。测试之前记得检查SO选项中是否正确设置了代理服务器等，并选择全局代理模式。

如果还不行，请告知你正在使用的代理情景模式（直接连接、自动切换还是全局代理），试图访问的网站URL，你是否希望该网址使用代理，结果实际是否使用了代理（根据图标的颜色确定），网站中的资源是否能正常加载（查看图标上的数字，点击菜单查看等）。

**Comment by shenhuabuluo** [comment]
我刚刚看了关于win10冲突的问题   我是win10系统  我习惯都是开全局  刚才试了一下 设置成socok5 是访问不了的  左下角显示 正在连接  ，设置成HTTP 可以访问

**Comment by FelisCatus** [comment]
像是 #557.

**Comment by shenhuabuluo** [comment]
像是这个 现在知道具体原因了吗？

**Comment by FelisCatus** [comment]
如果 SOCKS5 访问不了而 HTTP 能访问，那么 80% 是和 #557 一样的问题。麻烦到 #557 看一下那边的说明和讨论，如果现象一致，且改成 HTTP （或者按照 #557 讨论过的其他解决方式，如卸载迅雷）确实解决了，那么 99.99% 就是 #557 了。
