### ISSUE TITLE
Authenticate SOCKS5 proxy

### ISSUE THREAD

**Issue by lkinnyc** [FelisCatus/SwitchyOmega#659]
Hello. I've added SOCKS5 proxies, but they require authentication. How can I add a username and password with the SOCKS5 option? I see that with regular http, I can add username and password by clicking the lock icon, but there is no lock icon with SOCKS5 that I can see. Thanks!

**Comment by celeron533** [comment]
Refer to #178 (written in Chinese)

Chrome does not support SOCKS5 authentication
https://code.google.com/p/chromium/issues/detail?id=256785

**Comment by FelisCatus** [comment]
#291
