### ISSUE TITLE
似乎存在某些情况下的代理应用不及时

### ISSUE THREAD

**Issue by cnrat** [FelisCatus/SwitchyOmega#660]
希望能够确认一下是否这种情况只有我一个人遇到：

当打开一个新的标签页的时候（可能是点击了一个链接或者什么），似乎SwitchyOmega没有及时生效，导致浏览器直接发送了非代理请求，结果当然收到了“霾之RST”，不过刷新页面就不会有问题。

我通过WireShark抓包确认了这个现象，确实有非代理请求直接被发送出去。

使用的是自动切换+虚情景模式。

**Comment by FelisCatus** [comment]
从原理上来说， SwitchyOmega 只在更改设置/切换当前情景模式时，才会更改代理设置。之后网络请求等是 Chrome 负责，不存在“打开新标签页后应用代理”这种说法。

如果有 WireShark 抓包，请务必仔细确认日志，尤其是检查非代理请求是否真的是页面本身（和当前网址URL一致），而非页面中嵌套的图片等资源（可能URL有很大的不同，来自于另一个域名等）。

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
