### ISSUE TITLE
Feature Request - Random Proxy as Profile

### ISSUE THREAD

**Issue by doque** [FelisCatus/SwitchyOmega#661]
Hello,

I've got quite a number of proxies set up. I'd like to route my browsing activity through them at random for various reasons.

Ideally, I could select "Random" proxy from the dropdown.

Thanks for considering.

**Comment by FelisCatus** [comment]
Such use cases can be covered by PAC scripts (like [this one](https://gist.github.com/teslatronic/4222759e2cacfdb00a48)), which is fully supported in SwitchyOmega via the PAC Profile.

**Comment by doque** [comment]
Thanks for the suggestion! However, that requires me to type in every proxy manually. It would be quite nice to only add proxies once and not having to double-edit URLs.

**Comment by FelisCatus** [comment]
You still have to add each proxy manually even if you create a SwitchyOmega profile for each of them. And that would be more work to do: clicking on the `Add Profile` button, type in a profile name, filling the server and port separately, etc.

Trust me, using a text editor to craft the PAC script is actually a lot easier if you do have quite a number of proxies to set up.
