### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by yehuiboy** [FelisCatus/SwitchyOmega#665]
遇到了同样的问题，        https://github.com/FelisCatus/SwitchyOmega/issues/540           
尝试了许多方法，任然无解。但在chrome45时还是正常，46,47均出现乱码，插件应用无故损坏，修复后，过一会还是损坏。（图片上传不成功，链接）

**Comment by FelisCatus** [comment]
统一在 #540 讨论吧，那边信息多一些。
