### ISSUE TITLE
允许 SwitchyOmega 将页面的全部资源一键设置特定代理

### ISSUE THREAD

**Issue by zhudhjen** [FelisCatus/SwitchyOmega#666]
现有的功能是将加载失败的资源一键设置特定代理，而实际上有的时候有些资源并不是加载失败，而是通过默认代理访问缓慢，而这种情况下通常整个网站都不适用默认代理。所以希望可以提供一个功能来一键添加该页面的全部资源到某个规则，如果方便的话也可以勾选特定资源。

**Comment by FelisCatus** [comment]
访问缓慢的情况：单一请求时间超过5秒后，会出现在加载失败的资源列表中。

一键添加该页面的全部资源理论上可行，但性能上存在问题。统计页面包含的所有资源可能会极大地影响性能（而且会导致菜单变得非常长），类似 #664.

**Comment by FelisCatus** [comment]
先关闭了，看 #644 吧。
