### ISSUE TITLE
有关win10+chrome下socks5的问题

### ISSUE THREAD

**Issue by RoachJoey** [FelisCatus/SwitchyOmega#667]
https://github.com/FelisCatus/SwitchyOmega/issues/557

这里面认为是迅雷造成了问题的原因
但是在同样环境下，我用火狐+foxyproxy使用socks5一切正常（不卸载迅雷）
所以问题的根源在chrome上？

**Comment by FelisCatus** [comment]
很难说是什么问题，但从目前的讨论来说，我个人觉得和 Windows 的 TCP 协议实现有关，而安装迅雷可能改变了一两个协议实现的有关设置。如果您有任何新的见解，可以在 #557 提出。
