### ISSUE TITLE
Proxy for particular site

### ISSUE THREAD

**Issue by janewilliam** [FelisCatus/SwitchyOmega#669]
Hi,

I just applied proxy to a particular site using filters.

But I can't find any option to set it default so it can accept the default proxy. How to do it?

Secondly, is there any way I can permanently set different proxies for different sites?

Look forward to hearing from you.

Thanks

**Comment by FelisCatus** [comment]
Anything you did using the filter menu item is meant for temporary overrides which do not survive browser restarts. For permanent switch rules, you may want to use a Switch Profile to which you can add rules using the "Add Condition" item in the popup. These rules are easily managed in options > [your switch profile].
