### ISSUE TITLE
Chrome浏览器只要用了这插件就有可能出现ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by oyrx** [FelisCatus/SwitchyOmega#670]
SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2593.0 Safari/537.36

**Comment by oyrx** [comment]
禁用掉插件就没有问题

**Comment by celeron533** [comment]
看上去应该是你外部代理服务器的问题

**Comment by oyrx** [comment]
但我只用了 Shadowsocks 跟 SwitchyOmega  = = 而且禁用掉过后一切安好

**Comment by wenliyang** [comment]
检查在 SwitchyOmega 中定义的规则

**Comment by FelisCatus** [comment]
可能是自动切换模式没有覆盖您访问的部分网站，请尝试使用全局代理模式。

如果全局代理模式也这样，则请参考 #557 ，可能是那个问题。

**Comment by FelisCatus** [comment]
这边测试的结果如何了？

**Comment by FelisCatus** [comment]
已经几个月没有回复了，先关闭了。如果再有任何问题请回复并重新开启。
