### ISSUE TITLE
Host wildcard规则不识别

### ISSUE THREAD

**Issue by vivahu** [FelisCatus/SwitchyOmega#671]
gitlab.alibaba-inc.com是内网域名，只能走DIRECT访问。

Host wildcard设置*.alibaba-inc.com无法匹配gitlab.alibaba-inc.com，不走我设置的DIRECT规则。必须手动切换为DIRECT才能访问。

![image](https://cloud.githubusercontent.com/assets/1997175/12029970/b0e51e48-ae31-11e5-8c89-f1d05ed6f258.png)

![image](https://cloud.githubusercontent.com/assets/1997175/12029978/c64be6f4-ae31-11e5-9810-fa6972532b40.png)

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by FelisCatus** [comment]
可能是规则顺序问题吧……请使用拖动排序功能，将此规则拖动到**最上方**，然后再尝试。
如果页面走的代理和预计不同，可以鼠标悬停在图标上，会提示匹配的规则和最终结果。

**Comment by vivahu** [comment]
忘了说，我就是放的第一条。

发自我的 iPhone

**Comment by FelisCatus** [comment]
请打开那个页面，然后将鼠标悬停在图标上，查看一下匹配的规则和最终结果。

**Comment by vivahu** [comment]
今天把规则稍微调整了下（但是那条规则还是保持在第一条不变），悬停显示能走到正确的规则了。应该是偶发问题，无法重现。Close工单吧。下次有问题我会带着匹配到的规则截图再提issue的。多谢。
