### ISSUE TITLE
grunt coffeelint fails on coffeelint@1.14.2

### ISSUE THREAD

**Issue by celeron533** [FelisCatus/SwitchyOmega#672]
```
Windows 8.1 x64 CHS
Node v4.2.4
```

(This issue is not urgent and a bit off-topic about SO and aked by a Javascript newbie.)

When building the code, ```grunt-coffeelint``` popup the following error message:

![image](https://cloud.githubusercontent.com/assets/3608762/12031950/c50b82e2-ae4d-11e5-803b-429dc19ce5f3.png)

![image](https://cloud.githubusercontent.com/assets/3608762/12031957/cb494518-ae4d-11e5-96e3-f145c276b23a.png)

Yes, after I have solved the 'count of new lines' & 'indentation' issues, the error messages disappeared.
The source code is checked out from git repo, master branch directly. And I also inspected the original code files from Github, they are as same as the ones on my machine.
> "grunt-coffeelint": "^0.0.13"

Is there any way to bypass this error? (not the ```grunt --force```)

References:
https://github.com/clutchski/coffeelint/issues/245
https://github.com/clutchski/coffeelint/issues/107
https://github.com/clutchski/coffeelint/blob/master/test/test_newlines_after_classes.coffee

**Comment by FelisCatus** [comment]
Could you check `npm list coffeelint`? You might be using a newer version which causes the problem.

Mine is `coffeelint@1.6.0` FYI.

**Comment by celeron533** [comment]
Mine is ```coffeelint@1.14.2```. After ```npm install commeelint@1.6.0```, error still exist.

**Comment by FelisCatus** [comment]
Which module are you testing? I suppose you are testing `omega-target`, but the error message also shows something from `omega-web`.

I would suggest testing the modules one by one. For example, please `cd omega-target` before running `npm install coffeelint@1.6.0` and later `grunt coffeelint`.

**Comment by celeron533** [comment]
Thanks @FelisCatus ,
After downgrade the coffeelint to 1.6.0 in ALL project folders, build SUCCESS.
Thank you.

**Comment by FelisCatus** [comment]
I will try `coffeelint@1.14.2` and fix the issues later. Thanks for the information!
