### ISSUE TITLE
我用SwitchyOmega 替换系统代理后，无法上网，切换到直接连接或系统代理才可以上网。

### ISSUE THREAD

**Issue by ShiJess** [FelisCatus/SwitchyOmega#674]
SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

**Comment by ShiJess** [comment]
提示信息：
无法显示此网页
ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

**Comment by celeron533** [comment]
Please refer to #160

**Comment by ShiJess** [comment]
我导出的pac文件传不上去，压缩为zip也没法传，所以改为txt传了
[OmegaProfile__.txt](https://github.com/FelisCatus/SwitchyOmega/files/76943/OmegaProfile__.txt)

**Comment by FelisCatus** [comment]
我看过了哦，好像你内嵌了其他 PAC 脚本吧。那个 PAC 脚本最后是 `    if (u`，似乎没有正常结尾，所以导致了 PAC 脚本无法正常运行。清空`GoAgent PAC`中的 PAC 脚本就能正常使用了。
