### ISSUE TITLE
关于在浏览器外修改Profile

### ISSUE THREAD

**Issue by Chigogo** [FelisCatus/SwitchyOmega#675]
系统：OS X
 
有时需要在浏览器外写脚本来修改profile 的内容。（比如代理服务器的ip 是动态的）不知目前的Profile 的存储是否加密。如果没有加密，可以把文件的存储位置告知一下吗？

这样，通过“引用”代理服务器的ip，在Chrome外，可以实现脚本一键修改profile。

**Comment by xieranmaya** [comment]
你可以考虑间隔一段时间修改host文件然后刷新dns缓存
或者把逻辑写在pac文件里
像你说的修改profile的内容，简直太hack了

**Comment by Chigogo** [comment]
@xieranmaya 公司的ip是动态的，每次登陆都会变。

我的代理服务器放在本机，不用127.0.0.1的原因是，代理服务器要给局域网的设备使用。

为了能让profile中代理的ip动态变化，也只能用脚本来定期自动的修改profile了。（如果可行的话）

**Comment by FelisCatus** [comment]
代理服务器可以监听`0.0.0.0`端口，然后用`127.0.0.1`或者任意其他IP（如局域网分配IP）都可以访问。

**Comment by celeron533** [comment]
看样子你是公司局域网里面一台机器做服务器，每天关机都会变IP的那种。直接用主机名可以吗？

**Comment by Chigogo** [comment]
@celeron533 网关是路由器。
@FelisCatus 正打算这么搞呢。本机可以用127.0.0.1，其他机器必须用代理服务器所在机器的ip才行吧？所以还是要修改profile 的ip地址啊……

**Comment by FelisCatus** [comment]
还是用域名和 `hosts` 文件吧。甚至动态 DNS 也行。

**Comment by xieranmaya** [comment]
正确配置的话应该是可以使用主机名的，我用过很长一段时间

**Comment by FelisCatus** [comment]
我准备关闭这个了，因为感觉 hosts 或者动态 DNS 会更好用。如果有其他建议请重新开启。

**Comment by Chigogo** [comment]
好的！我已经绑定了ip了
