### ISSUE TITLE
crx插件下载不了 怎么回事？

### ISSUE THREAD

**Issue by Farb** [FelisCatus/SwitchyOmega#676]
搞了一晚上也没下载下来，不知道怎么回事？源代码都可以下载下来，就是crx下载不了？急人啊

**Comment by celeron533** [comment]
你从哪里下载的？google play需要科学上网

**Comment by Farb** [comment]
下载的地方提供了三个选项，后两个是源代码，第一个就是扩展程序了 就是第一个下载不了，跟科学上网没关系吧  不然为啥就它不能下载

**Comment by celeron533** [comment]
@Farb 上海电信直连测试无问题。。。
![image](https://cloud.githubusercontent.com/assets/3608762/12133424/63a5b23e-b460-11e5-8e2f-4a4cb2f43c0e.png)

**Comment by Farb** [comment]
家里和公司里用的不是同一家运营商的网络 都下载不了  在杭州

**Comment by FelisCatus** [comment]
是 Amazon S3 被墙了吧……

我在附件里上传一份，如果还不能下载，请找其他镜像或者请好心人上传到百度网盘。
[SwitchyOmega.zip](https://github.com/FelisCatus/SwitchyOmega/files/80710/SwitchyOmega.zip)

**Comment by Farb** [comment]
这个可以下载 谢谢

**Comment by FelisCatus** [comment]
:ok_hand:
