### ISSUE TITLE
Auto Switch to System Proxy

### ISSUE THREAD

**Issue by snakyjake1** [FelisCatus/SwitchyOmega#677]
Can we have a feature that Auto Switches to the System Proxy?

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2587.3 Safari/537.36

**Comment by celeron533** [comment]
Oh, it was mentioned in:
https://github.com/FelisCatus/SwitchyOmega/issues/289#issuecomment-74463233
