### ISSUE TITLE
提示： 此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by AbcdefgXW** [FelisCatus/SwitchyOmega#678]
提示： 此情景模式使用存储空间过多，因此无法进行同步。

因为我把大部分经常用的大陆网站都加入白名单，出现了这个提示，希望改进，如果可以做一个分组列表，情景模式里只需要选择列表作为白名单那就太棒了

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

**Comment by celeron533** [comment]
目前的曲线救国的办法是新开一个情景模式，把当前的情景模式分割一部分到新的情景模式中去，然后老的情景模式默认匹配的全都转向到新的情景模式，达到链式传递的效果。。。

**Comment by AbcdefgXW** [comment]
听起来很不错，具体如何操作？

**Comment by celeron533** [comment]
@AbcdefgXW 
如图，完成了链式操作
![image](https://cloud.githubusercontent.com/assets/3608762/12143018/c33e40ec-b4b7-11e5-9d1e-1ba05dde7d35.png)

![image](https://cloud.githubusercontent.com/assets/3608762/12143072/37251f4e-b4b8-11e5-8196-4fba92ddc2f9.png)

**Comment by AbcdefgXW** [comment]
非常感谢^_^

**Comment by FelisCatus** [comment]
使用存储空间过多的问题我也没有办法，不过拆成几个至少是解决了吧……

**Comment by fanlushuai** [comment]
这个问题，遇到了。怎么感觉是因为有缓存占用空间之类的。具体机制不懂。
但是，我尝试直接删除原来的情景模式。然后原封不动的新建。就没有了这个问题。
