### ISSUE TITLE
打开浏览器全局ss时不能翻墙，刚出现的问题，昨天上还好好的

### ISSUE THREAD

**Issue by lpfphilip** [FelisCatus/SwitchyOmega#679]
SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by celeron533** [comment]
请先参考 https://github.com/FelisCatus/SwitchyOmega/issues/557#issuecomment-166172736

**Comment by FelisCatus** [comment]
这个 issue 太长时间没有更新了，而且缺乏必要的信息。我先关闭这个了，如果有任何问题请重新开启。
