### ISSUE TITLE
在线pac脚本无法在本地保存

### ISSUE THREAD

**Issue by catatnight** [FelisCatus/SwitchyOmega#68]
我使用pac情景模式并填写在线pac地址，同时在通用设置中设置更新间隔为“从不更新”。但每次重启chrome，插件依然会重新下载在线pac脚本。

SwitchyOmega 2.2.0
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

**Comment by FelisCatus** [comment]
见 #148
