### ISSUE TITLE
通过菜单中添加的规则选择放置在最前或最后

### ISSUE THREAD

**Issue by HUMORCE** [FelisCatus/SwitchyOmega#680]
能否让新条件在规则列表最后，而不是在最前

某些特殊的规则需要固定在前面，而通过扩展添加的新条件都会在列表顶部

**Comment by FelisCatus** [comment]
先记录了。

**Comment by FelisCatus** [comment]
Proposed UI:

![image](https://user-images.githubusercontent.com/912649/29145433-1951e9a6-7d2b-11e7-88f5-f4359dd89db2.png)

以上是界面设计，当然是会翻译成中文的。暂定的中文翻译：

- [ ] 把通过弹出窗口创建的规则添加到列表最后。

**Comment by yfdyh000** [comment]
`以弹出菜单创建的规则添加到列表末尾。` 感觉更好。

`Put new conditions to the bottom of (present) list for added by popup.` ，一点想法。

**Comment by FelisCatus** [comment]
中文的就按你说的吧，英文的我也不是很确定，还是先就这么弄上去，然后我们可以在 Weblate 上再讨论翻译问题。

**Comment by FelisCatus** [comment]
v2.5.1 已经修复， Chrome Web Store 已发布。 Firefox 版仍在审核中。

Fixed on v2.5.1. Published on Chrome Web Store. Firefox version still under review.
