### ISSUE TITLE
扩展提示“由其他扩展或系统环境控制”

### ISSUE THREAD

**Issue by fish0413** [FelisCatus/SwitchyOmega#681]
重装扩展也无法恢复

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by celeron533** [comment]
和重装扩展没有多大联系，主要是你的chrome上还安装了其他的代理配置软件，比如unblock youku，某些广告屏蔽插件等。

**Comment by FelisCatus** [comment]
请检查其他可能有冲突的扩展，包括代理设置扩展和去广告等。

Thanks @celeron533

**Comment by fish0413** [comment]
除了ABP，没有别的了，一直在用

**Comment by fish0413** [comment]
已禁用其他扩展，仍然如此

**Comment by celeron533** [comment]
请先检查当前chrome代理是谁在接管

![image](https://cloud.githubusercontent.com/assets/3608762/12163185/27892e84-b546-11e5-987f-4dbc1d5395c7.png)


如果找不到的话，尝试：
```
chrome://net-internals/#proxy
```
看看有没有错误

**Comment by fish0413** [comment]
发现原因了，新版Chrome的扩展菜单无法正确显示，但是点击区域还在，不小心点到启用系统代理那项了

**Comment by FelisCatus** [comment]
类似  #128
