### ISSUE TITLE
设置界面更改设置后, "应用选项"的:hover样式看起来不对

### ISSUE THREAD

**Issue by DengZuoheng** [FelisCatus/SwitchyOmega#682]
hover时按钮的background-color和color都是白色了

建议把hover时字体颜色改成绿色什么的, 就像:

a.btn-default.btn.align-initial.ng-binding.btn-success:hover {
    color: #4cae4c;
}

**Comment by FelisCatus** [comment]
我有时间的话会来处理这个。
不过暂时来说不是很影响使用，所以优先级不是很高。

**Comment by FelisCatus** [comment]
此问题已经在 v2.3.17 版本修复。
