### ISSUE TITLE
Not able to bypass the proxy for the intranet addresses

### ISSUE THREAD

**Issue by ashokbisht** [FelisCatus/SwitchyOmega#683]
I have a local intranet address

https://wh/wh/

which I can open easily using 
no proxy
system proxy
in chrome. and from internet explorer using option "bypass local addresses"

but not able to open it using the proxy settings "Amdocs" profile in SwitchyOmega.

I have copied the same exceptions from IE.

The diff via chrome://net-internals/#proxy is below

system:-
Proxy server: genproxy:8080
Bypass list: 
  *.corp.amdocs.com
  erpprodsso*
  erpdbsso*
  10.*
  <local>
Source: SYSTEM

using proxy settings:-
Proxy server: genproxy:8080
Bypass list: 
  *.corp.amdocs.com
  erpprodsso*
  erpdbsso*
  10.*
  127.0.0.1
  [::1]
  localhost

the diff is <local> vs "127.0.0.1" + [::1]+localhost

which is not working at all.

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by FelisCatus** [comment]
Hi, `Source: SYSTEM` indicates that the `System Profile` is activated in SwitchyOmega, which effectively leaves proxy settings for Chrome's own judgement. You may want to select `Amdocs` in the SwitchyOmega popup menu instead so that you can configure the proxy.

You can also put `wh` in `Amdocs` in SwitchyOmega options as you wish.

**Comment by ashokbisht** [comment]
for your information I gave the proxy information for both cases of system and Amdocs.

problem:-
Can't access the intranet sites on "Amdocs" while can access using system proxy or thru Internet Explorer not in chrome.


what should I put in the Amdocs proxy configuration that will result in effective proxy as <local> which I assume will fix the issue.

I don't want to put wh in the exception as how many exception I'll have to put. For each site?

when system proxy can work and IE can work then definitely it's a limitation of extension that I can't have proxy defined for some sites and not defined for intranet.

**Comment by FelisCatus** [comment]
Hi, this time the PAC script from `http://wpad/wpad.dat` seems to be effective based on your paste, the rest of the proxy settings (marked as `(2)`) are ignored. Therefore the behavior can be completely different.

Why do your system configuration change each time? Please try selecting and deselecting `Auto-detect` option in system proxy settings and see which works better for you.

**Comment by FelisCatus** [comment]
You can also download `http://wpad/wpad.dat` and see what's in there. It should contain a proxy script  which determines proxy to use based on URLs.

**Comment by FelisCatus** [comment]
Okay I got it. It's indeed an extension issue. Let's continue the discussion on #443.

**Comment by ashokbisht** [comment]
From your answers looks like you thinking that the system proxy is working some time and not working other time. 
I confirm that SYSTEM proxy  works each time..

**Comment by FelisCatus** [comment]
As of v2.3.18, `<local>` works as-is. Consider this fixed.

**Comment by cybertk** [comment]
`<local>` works fine.
