### ISSUE TITLE
如何让SwitchyOmega记住在auto switch下手动添加的规则（例如某网站经过proxy，某网站直连）

### ISSUE THREAD

**Issue by speakerz** [FelisCatus/SwitchyOmega#684]
我用了一段时间才发现，好像是重启浏览器之后，在auto switch模式下手动添加的规则全部都重设了，是SwitchyOmega不具备这个功能，还是我设置得不对？谢谢！

**Comment by johnhuo** [comment]
不会的啊…

**Comment by FelisCatus** [comment]
我觉得像是 #515.

**Comment by speakerz** [comment]
谢谢提醒，以前不知道这个规则是临时的，希望以后可以在下拉菜单里面加一个添加永久自定义规则的选项，总是去options有点不方便。

**Comment by FelisCatus** [comment]
@speakerz 点那个加号图标的就是快速永久添加规则。（仅在自动切换的时候可以看到这个选项）

**Comment by youkaichao** [comment]
为什么仅在自动切换模式下才有这个选项呢？

**Comment by hongzhang7** [comment]
hello，在使用proxy switchOmgega过程中使用auto switch 不能访问既不走 代理 也不走 直连，网址访问不了这是啥原因呢？求教
