### ISSUE TITLE
多规则列表支持 | Multiple rule lists

### ISSUE THREAD

**Issue by cicku** [FelisCatus/SwitchyOmega#685]
您好，

在维护 gfwlist 的日常中，我萌生了一个想法，就是拆分 gfwlist，做成类似于 ABP 那种多规则模式。现有 gfwlist 保持不变，新增简洁列表和 CDN 列表。但是我发现 SO 并不支持多规则订阅。

开 issue 之前我特地搜索了一下，发现 #179 有人问过相关的问题，类似串联的解决方案很有意思。

不过，用户可能会遇到需要订阅3+个列表的情况。 _(:з」∠)_ :joy: 原有方法并不能真正解决需求。

鉴于拆分后的列表远比不上 ABP 甚至原有 gfwlist 的规模，我认为如果做多列表支持，在理论上并没有问题。但是有关多个列表之间在处理时是否预先合并（理论上所有拆分的列表之间**不**互相重复），我并不是很了解。

还望考虑！

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by FelisCatus** [comment]
Hi @cicku ～首先感谢您对本项目的关注和之前在各种 issue 的贡献，让我们一起做得更好。

关于未来拆分 gfwlist 的想法，我首先表示支持，并且会尽可能改进SO中关于规则列表的处理，以适应规则列表的理想使用场景。这种情况下列表发布者的意见是最重要的，不过也欢迎共同探讨。

现在的自动切换内嵌切换规则，用的就是建立一个只有切换规则的情景模式然后串联这种 tricky 的方式。只不过实现细节是对用户（设置界面）隐藏的而已。因此关于多列表的问题，在实现层面我需要进行一些考虑，也许要在产品上做一些妥协。

关于多列表的合并处理：

自动切换从产品而言，设计目标是自定义规则优先于列表规则。自定义规则也严格按照从上到下的顺序，并且方便用户排序。这一切都是为了让规则有明确定义的、用户可以简单推断的顺序。我希望之后的多规则也能尽量简单。

我个人认为，假定规则不互相重复是不现实的。在一个开放的生态中，两个规则列表出现同一个规则、甚至矛盾的规则是再正常不过的了。即使所有规则都是同一个组织发布，在某个规则从A列表迁移到B列表的过程中，因为更新延迟也很可能会出现一定的重叠期间。更不用说规则之间的优先级和覆盖范围等问题了：比如A列表的`*.example.com`和B列表的`*/abc`同时匹配`some.example.com/abc`，用户难免会对此产生困惑。还希望您能考虑到这一点。

请问您是否可以详细说说看关于拆分之后的构想？对于以上的问题，也希望得到您的指点。从本项目的这个 issue 而言，我希望更了解 use case. 如果说关于 gfwlist 本身的拆分还有待探讨，我们也可以移步 gfwlist 项目聊聊。

**Comment by FelisCatus** [comment]
Hi @cicku ，我更新了一下 SO 这边的教程，现在推荐用户用 Github 上的新 gfwlist 项目规则列表地址啦～

不知道拆分进行的如何了？我这边有一些新想法，也许可以提供一个服务器做到一个 URL 就可以加载多个列表内容的功能，如 `http://gfwli.st/gfwlist.txt?preset=foo,bar,baz` 这样的？相当于客户端不做多列表整合，而直接让服务器提供已经整合好、可以当做一个列表处理的文件。这样一来大部分客户端都不需要做任何修改，就能支持拆分后的架构，向后兼容。

当然，如果最终决定还是需要改变客户端的话，至少 SwitchyOmega 这边是有精力也有意愿协助开发的。只是提供一种可能性供您参考。

此外，听说 gfwlist 项目使用 github raw 的那个地址违反了 Github ToS ，准备迁移到其他地址，是这样吗？如果换了其他地址请务必告诉我，我再通知用户去改……

或者也可以增强一下 GFWList 文件格式，加一句特殊的注释来指定新的URL，这样 SO 解析后可以自动将设置里的规则列表改为新的URL，这样如何？虽然 Google Code 那个最早的版本已经只读了，不太可能用这种方式，但今后的 URL 迁移也许能这样做？

我知道您维护项目也挺不容易的，所以不要有太大的压力。我说的这些都仅供参考，您有时间的时候稍微看看就可以了。如果有什么我可以做的，请告诉我。

**Comment by zbutfly** [comment]
great! looking forward the processing of the work and maybe I can take part in such great projrct.

**Comment by lybtongji** [comment]
如果想要 listA 走 proxyA，listB 走 proxyB 的话，合并列表的方法就不太行了。

之前用 Foxyproxy，支持 多个列表走不同的代理 这个特性，更新 47 后被砍了…要是 SwitchyOmega 能实现的话就很感谢了。

**Comment by FelisCatus** [comment]
@lybtongji SwitchyOmega 正好有这样的功能。只需要建立两个自动切换，然后分别设置一个规则列表，每个规则列表选一个代理情景模式即可。如果要两个一起用，将 自动切换A 的默认结果设置成 自动切换B 即可串联。

问题是这个功能非常隐蔽，并不是直接在一个自动切换里加入多个规则列表，而是要绕几个圈，通过多自动切换串联这种功能来实现，可能不太友好，所以才有此 Issue 的讨论。

说起来 @cicku 再也没回复过了……话说您那边考虑的如何了？如果决定要拆分了，我们继续讨论下怎么实现？如果 3+ 的话 SwitchyOmega 这边估计是要做多规则列表的支持的。

**Comment by cicku** [comment]
没有继续考虑，我可能就拆成2个。。。

**Comment by FelisCatus** [comment]
如果拆两个的话，服务器直接生成已经合并过的规则列表应该没问题吧？或者直接把合并后的 base64 上传 GitHub 也行？

**Comment by cicku** [comment]
直接合成很简单，因为两个列表不存在叠加情况。

**Comment by FelisCatus** [comment]
OK ，感谢说明，那么我先把这个关掉了……如果还有需求再开。
