### ISSUE TITLE
关掉所有谷歌浏览器后，再次打开浏览器，打开网页很慢

### ISSUE THREAD

**Issue by qiujianzhong** [FelisCatus/SwitchyOmega#686]
插件一直提示加载中，去除该插件后网页打开速度很快

![qq 20160113094759](https://cloud.githubusercontent.com/assets/16606359/12282687/ef4dc50e-b9da-11e5-8d6d-f0744066d717.jpg)

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36

**Comment by wenliyang** [comment]
禁用除 SwitchyOmega 外的所有扩展，再试

**Comment by qiujianzhong** [comment]
试过还是不行  确定就是这个插件的问题

**Comment by wenliyang** [comment]
那你在 SwitchyOmega 中是如何设置的呢，启用了全局翻墙么，国内国外网站全走代理的话，肯定快不了

**Comment by FelisCatus** [comment]
请右键点击图标，然后点击“保存错误日志”，将生成的文件上传（或粘贴）到这里。

**Comment by qiujianzhong** [comment]
我是自动切换的，并不是所有的都慢，只是第一次打开谷歌浏览器慢的，当时的插件是天蓝颜色的时候，网页无法打开（有时候持续一两秒，有时候十几秒），后面变成绿色（自动切换）就打开网页正常了。
我的配置如下
http://pan.baidu.com/s/1skp4pmX

保存错误日志如下：
Options << Options#applyProfile [
    "自动切换"
]

**Comment by FelisCatus** [comment]
加载扩展和第一次应用情景模式时，会有一定延迟，属于正常现象。尤其是自动切换中规则数量多或使用了规则列表的情况，应用代理设置需要一些时间。（此时SwitchyOmega显示“加载中”。）

在代理设置已经应用，但 Chrome 还在预处理时，打开任意网站左下角都会提示“正在解析代理……”等字样，此阶段的预处理时间和电脑系统性能关系很大。我只能说我自己不卡，而且大部分用户加载都少于十秒，但我的确做不到所有设备都不卡。

如果不想这么卡，请尽量减少规则数量，使用全局代理或白名单的方式。或者也可以选择卸载点扩展、关闭一些不用的软件，重装一个更快的系统之类的。

**Comment by celeron533** [comment]
若能智能排序（常hit的规则靠前）呢？

**Comment by FelisCatus** [comment]
@celeron533 预处理阶段是需要编译 PAC 脚本中的全部代码的。我估计规则的顺序不会产生任何影响。

**Comment by qiujianzhong** [comment]
现在发现：第一次打开谷歌的时间有时短有时长，估计还是加载什么导致了时间不同的长短
