### ISSUE TITLE
pass&login

### ISSUE THREAD

**Issue by yuhas** [FelisCatus/SwitchyOmega#687]
When I close browser, all settings are reset. How to make your extension to remember a password and username all time?

**Comment by FelisCatus** [comment]
You can put the username and password in SwitchyOmega settings.

In the `Proxy servers` table on the options page, click on the padlock icon on the rightmost column to input credentials.

Special Note: Authentication for SOCKS proxies are not supported and therefore the button is not shown for these proxies.
