### ISSUE TITLE
上下排序能不能调整？

### ISSUE THREAD

**Issue by yjd** [FelisCatus/SwitchyOmega#690]
![qq 20160120105545](https://cloud.githubusercontent.com/assets/6856740/12438731/7d0530c4-bf64-11e5-9752-f0763c6a13c0.png)

目前好像是要重新全部删除再添加？

**Comment by celeron533** [comment]
#607

**Comment by FelisCatus** [comment]
目前是按名字排序，所以……暂时给情景模式改个名字，改成`1-Goagent`，`2-WallProxy`之类的名字吧。
