### ISSUE TITLE
Why are login/password requested?

### ISSUE THREAD

**Issue by svetasakovets** [FelisCatus/SwitchyOmega#691]
When I turn on proxy profil during the attempt to reach any website, the window with request of login/password appears. Just yesterday i used it without this data. What's wrong?

**Comment by FelisCatus** [comment]
Hey, this dialog is shown by Chrome as requested by your proxy and SwitchyOmega does not even know this. It is very likely that your proxy server requires username/password now. Please contact your network administrator if you are unsure about them.
