### ISSUE TITLE
请问源码coffee是如何生成crx插件的

### ISSUE THREAD

**Issue by Dcyx** [FelisCatus/SwitchyOmega#692]
首先我必须感谢您的分享，这个软件帮了我大忙！下载后我想根据自己的需求做一下修改，之前没有做过chrome插件只好看网上的文档，找到的教程都是通过修改crx解压后的文件实现的，所以，我下载了 source code 和 crx 文件，将 crx 文件解压后发现这里面目录结构不太一样。请问生成chrome插件是直接使用 chrome 自带的打包扩展程序功能将 source code 生成crx，还是将 source code 转成解压后的格式后再利用 chrome 自带的打包扩展程序生成的呢？

**Comment by Dcyx** [comment]
最后还是要再次感谢！感谢您抽时间解决我的疑惑。

**Comment by FelisCatus** [comment]
请参考项目首页的[编译说明](https://github.com/FelisCatus/SwitchyOmega#building-the-project)一节。

此外，如果有什么好的建议或者想法也可以在此提出 Issue 或 PR，我很愿意帮忙实现或者详细说明如何进行修改。

最后，请注意[此项目使用GPL授权](https://github.com/FelisCatus/SwitchyOmega#license)，对于衍生作品和再发布的要求比较严格。如果您修改过的作品需要进行分发，请务必先了解GPL协议细则。
