### ISSUE TITLE
一个资源未加载

### ISSUE THREAD

**Issue by bluesimple** [FelisCatus/SwitchyOmega#693]
不论是在全局模式下还是在自动模式下，
我把一个需要在情景模式下加载的网址添加到里面，但是还是不能进去...Twitter等网站就没问题
是我设置有问题吗？望指教

但是我用iPhone挂VPN还是能访问那个网站的 

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by celeron533** [comment]
说不定那个资源自身的访问就是有问题的呢？比如说已经从互联网消失了

**Comment by FelisCatus** [comment]
先试试看全局模式能否访问。如果不能的话，添加到规则里估计也没用吧。

代理和 VPN 还是有很多不同的，网页打不开也未必是墙的原因。
