### ISSUE TITLE
HostRegex as condition type in autoswitch

### ISSUE THREAD

**Issue by jeka** [FelisCatus/SwitchyOmega#694]
Why in condition types for autoswitch HostRegex is a missing option?
It should not be that hard considering the fact that there is URL RegEx option.
and it would be extremely useful in case of connections by IP.
something like  ^10.87.[0-3].\d{1,3}$  for example which otherwise would require 4 rules (in this case) if I have to use HostWildcard rules.

Yes I know about RulesList and I am currently using it, but there my problem is that more often than not whole browser freezes if I make some typo in these rules

**Comment by FelisCatus** [comment]
Please check "Show advanced condition types" in `Options > Interface > Switch Options`. Congratulations, you have unlocked all condition types in SwitchyOmega now including HostRegex. Enjoy.

**Comment by jeka** [comment]
Thanks for the heads up!
Somehow this option eluded me although I tried to read everything on the Wiki.
Well almost everything, google translate fails to translate screenshots :P

Sorry for the noise :(

**Comment by celeron533** [comment]
![cxkbnzpu](https://cloud.githubusercontent.com/assets/3608762/12646747/c979f3f0-c60c-11e5-926b-6f111476810c.png)

**Comment by FelisCatus** [comment]
:beers: @celeron533
