### ISSUE TITLE
Auto Switch Profiles

### ISSUE THREAD

**Issue by janewilliam** [FelisCatus/SwitchyOmega#696]
Hi,

I have two questions:

1. How can I setup auto switch between multiple profiles based on the speed of the connection or timeout or sending requests to different profiles (not based on conditions). So each request should go to random profile from the list I select, and if some profile is slow, it should be avoided?

2. I forgot how to create a one click profile switch, could you please send me to guide to switch profiles by just clicking the proxy switchy omega icon (from the list I choose)?

Look forward to hearing from you.

Thanks

**Comment by janewilliam** [comment]
Hi,

I found the quick switch option, so please ignore point 2. Just wondering if this could be applied with auto switch so I can use a quick switch for the current site, but auto switch rules still govern?

Look forward to hearing from you.

Thanks

**Comment by FelisCatus** [comment]
For speed test: This is not doable in PAC scripts. Also this is a little bit complicated to be included the SwitchyOmega project.

For random switching: Such use cases can be covered by PAC scripts (like [this one](https://gist.github.com/teslatronic/4222759e2cacfdb00a48)), which are fully supported in SwitchyOmega via PAC Profiles.
