### ISSUE TITLE
在 Chrome 48 上不工作

### ISSUE THREAD

**Issue by Garfield550** [FelisCatus/SwitchyOmega#697]
模式：全局代理
现象：任意网页显示 ERR_TIMED_OUT

模式：直接连接
现象：工作正常

模式：系统代理
现象：工作正常

模式：系统代理，并开启 Proxifier
现象：工作正常

使用 Shadowsocks 客户端：
Shadowsocks Qt 5 Version 2.6.1
Shadowsocks CSharp Version 2.5.8.2

使用 Chrome 版本
48.0.2564.97 m (64-bit)

**Comment by celeron533** [comment]
#557

**Comment by Garfield550** [comment]
@celeron533 感谢您的指引，切换到 Http 可以了

**Comment by FelisCatus** [comment]
Tons of thanks @celeron533

**Comment by celeron533** [comment]
@FelisCatus 我只是遇到这些会解答的case就顺手带过去了。高端的也只有围观的份。

**Comment by FelisCatus** [comment]
@celeron533 已经帮大忙了，真的。
