### ISSUE TITLE
如果能将ss规则导出为user-rule.txt文件就完美了.

### ISSUE THREAD

**Issue by hstdt** [FelisCatus/SwitchyOmega#699]
已有的ss规则,如果可以导出成ss客户端可识别的user-rule.txt文件,替换mac本地的规则就完美了.这样就可以变成一个全局的PAC管理了

**Comment by celeron533** [comment]
虽说都是javascript，不过具体的实现还是有些差别的。。。。

**Comment by FelisCatus** [comment]
SwitchyOmega 的切换规则和 `user-rule.txt` 并非 1:1 映射的，没办法直接导出成那个格式。
此外， SwitchyOmega 不能读写本地磁盘上的文件。

**Comment by hstdt** [comment]
@FelisCatus 
不是很理解您的理由.如果说得不对那您就当我见识浅薄信口开河了,无视就行.
1.我觉得对于一条规则,只要是程序识别了,理论上来说就可以转换的.就算不是1:1的.能转多少是多少,规则我一条一条地复制都行.(我开这个issue是觉得可能不是很复杂的功能,只是你们之前没有考虑过,如果太麻烦就算了)
2.不需要对本地文件进行修改,比如放到剪切板里面就行了,或者弄个文本框让用户手动复制粘贴.

**Comment by FelisCatus** [comment]
1: `user-rule.txt`使用的是 AutoProxy 规则列表格式，其中的规则类型与 SwitchyOmega 的规则设计完全不同。我估计理论上大部分规则类型都是可以转换的（都转换成正则表达式），不过编码实现这种转换显然需要一定的工作量。我觉得这个做成另一个项目会更合适。名字可以叫 Omega2AutoProxy ？

2: 这个当然可行，感谢您的建议。不过实际使用起来，会变成在 SwitchyOmga 里修改规则，然后点导出成 AutoProxy 规则并按下复制，最后打开 `user-rule.txt` 粘贴替换保存。在这之后还要点 Shadowsocks 的更新 PAC 功能才能真正生效。一旦添加/修改了任何规则，都需要手动重复一遍以上过程。如此看来，即使实现了所谓的全局的PAC管理也更繁琐……还不如直接打开`user-rule.txt`手动改呢。
