### ISSUE TITLE
不定时出现 CPU占用99%

### ISSUE THREAD

**Issue by hcwhan** [FelisCatus/SwitchyOmega#70]
换SwitchyOmega后 短时间打开
几个网页会卡cpu 系统直接卡住 要等几秒才可动鼠标 

SwitchyOmega 2.2.1
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36

**Comment by FelisCatus** [comment]
Chrome 也应该更新几个版本了吧，那么请问现在还有没有这个问题？

**Comment by hcwhan** [comment]
没有了 谢谢
