### ISSUE TITLE
Chrome Update

### ISSUE THREAD

**Issue by brunorpinho** [FelisCatus/SwitchyOmega#701]
It is not working for me after today's Chrome Update.

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36

**Comment by celeron533** [comment]
Looks good on my machine.

Could you please try to execute `netsh winsock reset` in cmd with Administrator privilege?

(related discussion written in Chinese language #557 )



SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.97 Safari/537.36

**Comment by FelisCatus** [comment]
Any more information on this? I feel sorry that things didn't work on your side. But could you please tell us what exactly isn't working?

Is direct connection used instead of proxy? Or is there any error?

**Comment by brunorpinho** [comment]
It's working now great, thanks!

**Comment by FelisCatus** [comment]
I'm glad to hear that.

**Comment by brunorpinho** [comment]
It is such a great app! Thanks

*Bruno Ruas de Pinho*
[image: gtfsbrasil.com.br] <http://gtfsbrasil.com.br/>
+55 (53) 8118-5588
bruno@gtfsbrasil.com.br

2016-03-08 9:32 GMT-03:00 Felis Catus <notifications@github.com>:
