### ISSUE TITLE
建议增加多模式轮换

### ISSUE THREAD

**Issue by StrollStars** [FelisCatus/SwitchyOmega#702]
即在虚情景模式中，目标可以有多个，然后调用的时候从多个目标中任选一个，至少和上一个不重复。
更进一步，可以设置每个目标被调用的概率，目标概率加总为1。
不知这样可否实现？

**Comment by FelisCatus** [comment]
多目标见 #152.

随机调用建议还是使用 PAC 实现吧，类似[这种](https://gist.github.com/teslatronic/4222759e2cacfdb00a48)。
