### ISSUE TITLE
键盘快捷键建议

### ISSUE THREAD

**Issue by ThroughLee** [FelisCatus/SwitchyOmega#704]
建议添加一个将未加载资源加入proxy的键盘快捷键.我用了这个插件这么久,就没有用过一次模式切换,一直都是auto switch,然后每天不停的加未加载资源加入proxy~

SwitchyOmega 2.3.16
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by FelisCatus** [comment]
`Shift+Alt+O` 然后按 R 应该可以打开未加载资源的设置。菜单中的其他选项也有快捷键，都是`Shift+Alt+O`之后按某个键。在菜单中按 `?` 可以查看全部快捷键。

**Comment by ThroughLee** [comment]
(⊙o⊙)…,我试了......我还是乖乖的用鼠标点把.....:sweat_smile:

**Comment by ThroughLee** [comment]
(⊙o⊙)…:+1:我试了一下,感觉快捷感提升不大~也可能我是我用惯了Vimium,能在chrome上用到鼠标的机会不多的缘故?不过这个插件还是很棒的,感谢回复!:smiley:
