### ISSUE TITLE
Matching IP literals as host with IP range

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#705]
Currently, there is no obvious way to match IP literals to network.

For example, to match IP addresses in `10.87.0.0/255.255.252.0`, you have to do this:

**Host RegEx `^10.87.[0-3].\d{1,3}$`**

... which is not that nice.

Such feature is already available in `omega-pac` as [`IpCondition`](https://github.com/FelisCatus/SwitchyOmega/blob/master/omega-pac/src/conditions.coffee#L424). However, no user interface is implemented for this, making this condition type unusable in options. The original intention for IpCondition is merely an implementation detail, so it is not exposed.

We would probably want to add this to switch rules with nice editing and proper input validation. Help texts are also needed. What's more, we want to make it clear that these conditions only work with IP literals. It does not translate domain names to IPs via DNS.

**Comment by FelisCatus** [comment]
I'll make another release soon with this condition type supported.

**Comment by jeka** [comment]
Great, I am eager  to test it. Thanks.

**Comment by FelisCatus** [comment]
v2.3.20 is released with IpConditon available. The condition type can be unlocked in Options > Switch Options > Show advanced condition types.

**Comment by jeka** [comment]
@FelisCatus works flawlessly so far. I haven't done excessive testing as I just converted my host regex to this new condition type and everything is as it should be.

Thanks again.
