### ISSUE TITLE
SwithyOmega和Version 48.0.2564.109 m不兼容？

### ISSUE THREAD

**Issue by astralia123** [FelisCatus/SwitchyOmega#707]
我刚刚重新装了电脑，重装swithyomega以后发现手头的两个VPN都不能用了。

我是直接从chromium portable里面导出的bak配置文件，这个配置在chromium portable上能够正常运行，但是重新安装的chrome Version 48.0.2564.109 m上面，设置的两个proxy情景模式都不能正常连接。
不能正常连接的两个情景模式都是socks5，127.0.0.1，端口号这样的设置。
![qq 20160218235509](https://cloud.githubusercontent.com/assets/17318463/13149092/1566d078-d69b-11e5-88bc-832ffb9966e7.png)

chromium portable和chrome的插件版本、插件配置和使用的VPN都是完全一致的，但是chrome就是无法正常使用这两个VPN。只能猜测chrome是否是版本与omega不兼容，或者chrome在安装的过程中出错。

请问最近是否有omega与新版本的chrome不兼容的情况出现？

**Comment by celeron533** [comment]
1. 参见 #557 
2. 你用的方法只是代理，不叫做VPN，两者概念不一样。

**Comment by FelisCatus** [comment]
请在弹出菜单中选中一个代理服务器。打开 `chrome://net-internals/#proxy` 查看一下上面显示的代理设置。如果显示的结果和 SO 中设置的一致，那么 SO 正确已经完成了它的工作，成功将代理设置告知 Chrome 。那么剩下的问题估计就是网络问题，代理问题或者 #557 了吧……

@celeron533 谢谢

**Comment by astralia123** [comment]
用chrome://net-internals/#proxy检查设置正常。
代理工作正常。
根据#557，把代理模式设置成http以后就能正常使用代理了。

非常感谢！@celeron533 @FelisCatus
