### ISSUE TITLE
建议对提示的未加载资源自动使用可配置的代理

### ISSUE THREAD

**Issue by ChetWang** [FelisCatus/SwitchyOmega#708]
很多网站，大部分元素都是可以打开的，但很多时候会存在某些js、css、图片等资源因为是外部网站来的而被墙掉，SwitchyOmega中会显示未加载资源，虽然可通过弹出菜单一键设置使用代理，但还是不怎么方便，每次都要手动去点击、设置。建议对提示的未加载资源自动使用可配置的代理，如果代理还不行就再提示，这样就省去了这一麻烦，用起来更智能。

**Comment by FelisCatus** [comment]
未加载资源未必都是墙的原因，也可能是网络原因或者对方服务器的原因。作为一款代理设置软件， SO 没有足够的信息来替用户做判断。因此，这边的做法就是一定要用户确认后才能添加。

请先尝试一下[COW](https://github.com/cyfdecyf/cow)项目，看看是否能达到您的要求。技术上而言，这个项目比 SwitchyOmega 的检测更进一步，是在代理协议级别的检测，应该会更好一些。

如果需要继续讨论请移步 #550.
