### ISSUE TITLE
Improve rule lists for SwitchyOmega

### ISSUE THREAD

**Issue by netroby** [FelisCatus/SwitchyOmega#71]
Document need improvement
How to write switchy style rule list?

here is a small example

```
#BEGIN

[Wildcard]
*.google.com
*.youtube.com

#END
```

this is the rules for  domain and it's subdomain.

**Comment by FelisCatus** [comment]
SwitchyOmega (as of 2.1.10) now has a "Publish rule list" button for Switch Profiles, which can be used to craft a rule list. However, only Host wildcard, URL wildcard and URL regex conditions are supported.

In Switchy rule list, patterns are grouped by conditions types, which does not make much sense in SwitchyOmega where patterns are strictly ordered. I will see what I can do to improve the rule list format.

**Comment by FelisCatus** [comment]
Proposed rule list format: https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format

The new format is NOT backwards compatible with ProxySwitchy & SwitchySharp, but both the old and new format will continue to be supported in SwitchyOmega.

@netroby How do you feel about the new format? Is there anything that can be improved?

**Comment by FelisCatus** [comment]
v2.3.2 allows exporting rule lists in the [omega style rule list format](https://github.com/FelisCatus/SwitchyOmega/wiki/SwitchyOmega-conditions-format). Also, a single switch profile can be exported by switching to the "source code" view, and then copy & pasted to the source code view of another profile on another computer (provided the dependent profiles are also present on the destination options).

The old rule list format is still supported by default, but SwitchyOmega will not export old-style rule lists unless explicitly told so by checking the "compatible rule list" option in the "Import/Export" tab, which can be useful if you want to publish rule lists to users still using Proxy Switchy!/SwitchyPlus/SwitchySharp. Please note that some profiles just cannot be expressed in the legacy format. In that case, the publish button turns orange, and an omega-style rule list will be exported instead.

**Comment by netroby** [comment]
@FelisCatus I am testing the latest switchy omega now.

**Comment by netroby** [comment]
```
[SwitchyOmega Conditions]
```

this can be ommitted. 

you may add more options besides switchy and autoproxy

**Comment by netroby** [comment]
By using this code, it is amazing faster than before.
```

        if (/(?:^|\.)youtube\.com$/.test(host)) return "+proxy";
```

Nice job

**Comment by FelisCatus** [comment]
```
[SwitchyOmega Conditions]
```
This line is for marking the rule list as omega style. If such line is missing, SwitchyOmega will try to sniff the rule list content and decide whether to use omega style or not. The sniffing works most of the time, but I don't think we should rely on that behavior.

**Comment by netroby** [comment]
Add another checkbox can resolve this problem.

**Comment by FelisCatus** [comment]
But adding an extra line would solve that, too. With that being said, I personally think such radio boxes causes much confusion and should be hidden from the user. Users don't have to select the format of the rule list if the software can detect it for the user. Choosing the right format is hard for non-technical users, which was proven by lots of complaints that the rule list functionality is "broken" that happened in the SwitchySharp era.

In SwitchyOmega, I carefully designed the rule list logic to sniff based on rule list header and choose the rule list format accordingly. For example, an AutoProxy Rule List is always treated as so, even if the user selected the wrong radio box labelled "Switchy", provided that the rule list in question has a header line like `[AutoProxy ...]`. Such logic also applies to the omega format. It is okay to omit the header altogether, but in that case nobody could help you if you selected the wrong format.

Therefore, it is strongly recommended for rule list authors to add the header line to prevent the users from problems with not selecting the right format (or a broken sniffer). This should already have been done when you are exporting a rule list from a Switch Profile. But when you are hand-crafting a rule list, eventually it is up to you to decide.
