### ISSUE TITLE
Conditions.fromStr doesn't check the condition for validity

### ISSUE THREAD

**Issue by libmaru** [FelisCatus/SwitchyOmega#710]
Rule `HostLevel: 0~0 +direct` generates PAC like `if (/*0 <= hostLevels <= 0*/ host.split(".").length === 01) return "DIRECT";` which raises `Uncaught SyntaxError: Octal literals are not allowed in strict mode.` and shows `ERR_MANDATORY_PROXY_CONFIGURATION_FAILED`

**Comment by FelisCatus** [comment]
HostLevel can only be greater or equal to `1`. `http://internal/` is considered to have only one level.

The options page won't let you create a HostLevel rule with `0~0` via the Switch rules table. However, it is a bug that the rule list parser and the PAC generator skip the boundary check.

**Comment by FelisCatus** [comment]
Besides `HostLevelCondition`, many other types of conditions also have similar problems.

`WeekdayCondition` and `TimeCondition` also suffer from out-of-range values.

`IpCondition`'s `prefixLength` can also be out of range. The check of valid IP is also missing.

Those `Regex` conditions should also validate the regular expression. But invalid regexes won't blow up the PAC. They just compile as `/(?!)/` which doesn't even match anything.

The `BypassCondition` has the most complicated syntax and the analyzer probably doesn't check for all corner cases.

**Comment by libmaru** [comment]
This specific bug is more related to "0"+1="01" than missing of validating. ParseInt should be added.

**Comment by FelisCatus** [comment]
@libmaru Didn't even notice that. Thanks for pointing it out.

**Comment by FelisCatus** [comment]
Fixed in v2.3.17.
