### ISSUE TITLE
规则列表正文 如何编写 IP段 规则

### ISSUE THREAD

**Issue by ucoker** [FelisCatus/SwitchyOmega#711]
你好，感谢你提供这么棒的工具。

我想设定个 大陆白名单 模式。

新建规则列表后，如何添加 IP段 让其走 某个代理

IP段如：
39.104.0.0/14
39.108.0.0/16
39.128.0.0/10

**Comment by FelisCatus** [comment]
此功能有待实现，见 #705 

或者，也可以暂时在代理情景模式（不是自动切换模式）的不使用代理列表里填`39.104.0.0/14`等等，每行一个。我个人觉得这个已经够用了。

**Comment by ucoker** [comment]
确实可以，谢谢！

**Comment by FelisCatus** [comment]
* v2.3.20 新增 IP 字面量条件，用于匹配 URL 中的 IP 地址字面量属于某个子网。
  - 只匹配 URL 中的 IP 地址。网址中必须是 IP 地址本身，不处理域名和 DNS。
  - 例如: 规则 127.0.0.1/8 可以匹配网址 http://127.0.0.1/foo.
  - 如需使用，请在 设置 > 切换选项 > 显示高级条件类型 中解锁这种条件。
