### ISSUE TITLE
资源未加载

### ISSUE THREAD

**Issue by neunundneunzig** [FelisCatus/SwitchyOmega#712]
自动切换中选择直接连接
进行新浪微博传图依然会出现资源未加载的提示数字
图片很难上传

使用115浏览器等其他浏览器可以顺利上传

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by FelisCatus** [comment]
请在地址栏中输入`chrome://net-internals/#proxy`回车，查看代理设置是否确实为直接连接。如果是直接连接（`DIRECT`字样），那么设置无误，卡顿等原因可能是由于浏览器本身的原因，或者是被恶意软件影响。

如果不是直接连接而是一长串，或者是某个代理服务器：请再次检查是否在SwitchyOmega菜单里选择了直接连接。如果选了直接连接但还是这样，则代理服务器设置正在被其他扩展控制。请检查其他代理设置扩展或去广告扩展等。
