### ISSUE TITLE
chrome翻译与更新

### ISSUE THREAD

**Issue by wyl2000** [FelisCatus/SwitchyOmega#713]
有一个google翻译的问题，无法自动翻译，全局代理也不行，但是IE下的连接也改成同样的代理就可以了，一般用自动PAC翻，发现过不了试下全局，基本能过，唯有google的自动翻译与更新不能，全局也不行，只有改ie连接才行，是这个插件的局限吗？

**Comment by celeron533** [comment]
应该是插件的局限。chrome自动更新的时候也是要打开windows系统全局才有。

**Comment by FelisCatus** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/264#issuecomment-111838446
