### ISSUE TITLE
备份恢复chrome用户配置文件夹后，该插件需要重新安装

### ISSUE THREAD

**Issue by solidChen** [FelisCatus/SwitchyOmega#716]
其实chrome的用户配置文件夹一直是可以备份出来的，对于以前的switchy proxy，我备份后再恢复，代理插件是可以直接使用的；

但是新版的Omega在这种操作下，插件要重新安装，安装后该插件的代理等配置信息都在，就是不见了插件的程序主体，是否考虑解决一下？

**Comment by FelisCatus** [comment]
首先，这个不是 SwitchyOmega 可以控制的……用户文件夹的目录结构完全取决于 Chrome ， SwitchyOmega 没有任何涉及这个目录的代码。

其次， Chrome 本身的同步功能可以会改进或干扰备份和还原的过程。扩展本身和扩展设置都是可以同步的，而这种同步可能才是导致差异的原因。可以回忆一下之前安装和现在安装分别使用的是什么方式。（是在商店安装还是用 crx 安装？）

最后，我听说 Windows 下 Chrome 用户文件夹的机制改过，现在没有办法拷贝到其他机器/重装过的系统使用了。我不记得是从哪里听说的了，而且也没有找到证据，所以…… 如果真的是这种情况， SwitchyOmega 的配置没有丢，我感觉更像是因为从同步下载了配置，而不是备份/恢复的结果。

**Comment by solidChen** [comment]
你好，感谢你这么快速的恢复~
1.安装前后都没有使用同步功能哦
2.一直使用crx安装的
3.用户配置文件夹备份恢复的方法还是可行的哦，只不过由之前的复制【Default】文件夹改为现在的复制【User Data】文件夹~

在用户文件夹机制更新过后，旧版switchyproxy 依然可以用3的方式来操作哦~
如果你没什么头绪就先不管吧，谢谢

**Comment by FelisCatus** [comment]
如果Chrome已经登录过了的话，那同步会直接后台运行，不存在“使用同步功能”这个步骤。

另外也很可能是因为 SwitchyOmega 的 crx 是从 Chrome Web Store 下载的，带有特殊的标记，所以会导致 Chrome 认为这个扩展并非本地安装的，从而没有正确还原。之前的 proxy switchy 和 switchysharp 项目中，非商店版的是分开来打包的，扩展ID与商店版不同（几乎就是两个不同的扩展），且没有CWS加的标记。

我个人建议还是直接用同步功能吧，省心很多。只需要在Chrome选项里登录下账号然后启用同步就好了。之后再到 SwitchyOmega 选项>导入/导出里确认下同步已经启用。

**Comment by solidChen** [comment]
嗯  谢谢
