### ISSUE TITLE
多窗口能用不同模式而不是公用

### ISSUE THREAD

**Issue by Jsonzhang** [FelisCatus/SwitchyOmega#717]
能否做到在chrome的不同窗口，A窗口保持开启，而B窗口保持关闭。 因为开发调试和上网需要兼顾。

SwitchyOmega 2.3.16
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

**Comment by celeron533** [comment]
可以为开发调试的站点专门建立一条规则，直连。除非你的开发项目也是和chrome代理相关的。

**Comment by FelisCatus** [comment]
这种事情一般我都是弄两个用户搞定的。可以在 Chrome 设置里新建一个用户，这样两个用户可以安装分别不同的扩展，进行不同设置。

我自己的配置是三个用户：墙外用、墙内用、测试用。

当然，还有一个更快的方法，就是禁止 SO 访问隐身窗口，然后打开一个隐身窗口即可。这样常规窗口使用 SO 设置，而隐身窗口会采用系统设置。不过考虑到您是做开发，我还是觉得多用户的方式在长期来看更方便。
