### ISSUE TITLE
代理里设置的用户名和密码未能起效

### ISSUE THREAD

**Issue by iccfish** [FelisCatus/SwitchyOmega#718]
设置的代理是需要密码验证的，但是现在不知道从哪个版本开始，代理设置时输入的用户名和密码失效了，每次第一次访问的时候依然要求输入用户名和密码。

SwitchyOmega 2.3.16
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.12 Safari/537.36

**Comment by FelisCatus** [comment]
最近应该没有改过这个……

首先确定一下，是否是因为用户名和密码不正确导致的？也请确认一下代理设置旁边的小锁图标是绿色的（表示密码验证开启）。

此外，用 Chrome Dev 是有风险的……这个可能是 Chrome 本身的问题，有时候退回 Stable 可以解决，而有时候需要升级到 Canary 才能拿到最新的补丁，建议都试一下。

**Comment by iccfish** [comment]
1.用户名密码肯定都是正确的，因为这是很久以前设置的，一直没改过……（其实这个问题出现也很久了已经，只是刚刚看到有反馈的地方……）
2.那个小锁是绿色的，我也点开看过了确认里面的信息是正确的，也尝试过取消再重新设置
3.DEV……我不记得什么时候发现这个问题的，其实用DEV没多久（有个Material设计的时候为了体验才换的），不太确定是不是用了DEV后才出现的问题

**Comment by iccfish** [comment]
刚用Wireshark抓包看了下，发现在输入用户名密码之前，代理的连接请求里并没有Proxy-Authorization字段……应该是没起效。

**Comment by FelisCatus** [comment]
刚才我用 Chrome 48 试了一下用户名密码，没有问题。用的代理服务器是 Polipo. 等下我换更高版本的试一下。

此外，有几件事情希望能了解一下：

* Chrome 弹出用户名密码的窗口时，点取消会出错吗？
* 用的是全局代理模式，还是自动切换模式？如果是后者请换全局代理模式再试试看。
  * 先右键 SO 图标，选择管理扩展，然后允许 SO 访问隐身窗口，然后再打开隐身窗口即可忘记密码，可用于测试首次是否需要输入密码。
  * 关闭所有隐身窗口后再开隐身窗口可以再次测试首次是否需要输入密码。

**Comment by FelisCatus** [comment]
还有……当没有用户名密码的时候，代理服务器会返回 `407 proxy authentication required` 吗？如果返回的是其他状态码，则 Chrome 不会给 SO 提供用户名密码的机会的。

**Comment by iccfish** [comment]
1.点取消会出现代理的未授权错误信息
2.全局模式和自动切换模式都一样，都会在使用代理之前输入密码；隐身模式下也需要输入密码
3.根据抓包结果来看，代理返回的是407错误

**Comment by FelisCatus** [comment]
建议在图标右键菜单中导出错误日志，然后上传到这里。

错误日志中不会包含用户名密码等敏感信息，但是会包含代理服务器和端口，以及情景模式名称。您可以适当修改或遮挡一些数字来保护个人隐私。

为了保证错误日志较短，可以设置好全局模式，重启 Chrome 浏览器然后直接访问某个网站，输入用户名密码后能正常显示网页后立即导出日志。

**Comment by FelisCatus** [comment]
Chromium 49.0.2623.75 测试未能复现问题。等下继续找个更高版本的测试一下……

**Comment by iccfish** [comment]
刚看了日志，里面并没有啥错误信息。。。只有一些Options << Options#updateProfile 和 Options << Options#applyProfile。然后我切换成全局代理模式重启并访问网站，弹出来要密码的框子，但是保存不了日志，提示找不到文件……

![qq 20160307114946](https://cloud.githubusercontent.com/assets/1091653/13560501/f05b71bc-e45a-11e5-9a16-d098e69a9bb8.png)

应该是没有日志的原因。。

我现在用Stable、Beta、Dev、Canary版本都试试。

**Comment by FelisCatus** [comment]
请禁用 Enable Material Design downloads ，谢谢。那个可能还不支持 blob 下载。与代理验证相关的日志是`ProxyAuth`开头，敬请留意。

如果 ProxyAuth 的日志一条都没有，那么就是 Chrome 没有询问 SO 用户名密码。

**Comment by iccfish** [comment]
支持的啊……注意我的描述啊。。看了日志啊。。没重启之前是有日志并成功保存的啊………………………………………………

**Comment by iccfish** [comment]
就在我回复的时候又保存了日志……但是日志里并没有出现任何ProxyAuth的字样啊。
![qq 20160307115820](https://cloud.githubusercontent.com/assets/1091653/13560577/e2a11e86-e45b-11e5-8ca7-f2f88df4a6f2.png)

我用其它版本的Chrome测试下先。

**Comment by iccfish** [comment]
测试了 Stable 版的Chrome，也是一样的问题 49.0.2623.75 (64-bit)，下载地址是 http://redirector.gvt1.com/edgedl/release2/6y901wx4bvlm5tpp8tf6siej3xh00qwllk8znxl5p3sr9buopjl4srivi3nffr3ae9krsazckbylbf7kkfcn5hzjym5y4dp2ewh/49.0.2623.75_chrome_installer_win64.exe ……日志和上面的一样，没有ProxyAuth的东西……

**Comment by FelisCatus** [comment]
那个“服务器找不到该文件”是什么情况……

此外建议用全局代理测试，不要用自动切换，因为那个处理会比较复杂。

**Comment by iccfish** [comment]
Stable 版的Chrome 49.0.2623.75 (64-bit)，用全局模式也会弹提示……会不会是跟啥扩展有兼容性问题。。。。回来挨个禁用试试看。

**Comment by FelisCatus** [comment]
麻烦给个代理情景模式的截图吧，按老规矩，请自行遮挡一些敏感信息。不需要截图用户名/密码的弹出窗口。

此外，用户名密码中是否有特殊字符？我记得有些字符是没办法用，见 #111

**Comment by FelisCatus** [comment]
请看一下`chrome://net-internals/#proxy`就知道实际使用的代理设置和 SO 中设置的是否一致。如果不一致，那么显然代理验证也不会触发……

仍然建议使用全局代理模式来测试，否则很难看出来是否一致……

**Comment by iccfish** [comment]
无效……

1.现在用的是全局代理模式
2.```chrome://net-internals/#proxy```中的设置和SO中的是一致的（参见附图）
3.密码和用户名都是纯英文（都没有大小写）
4.重置了所有的chrome选项，同样的问题……禁用了所有其它扩展，也还是同样的问题
5.取消保存的密码重新设置，也还是一样……

对着代理模式的工作流程不是很了解，所以我发现没辙了……

![qq 20160307130729](https://cloud.githubusercontent.com/assets/1091653/13561238/91c69824-e465-11e5-88d0-9a676746bb47.png)

![qq 20160307130742](https://cloud.githubusercontent.com/assets/1091653/13561239/93e13b64-e465-11e5-9206-9de0147b1895.png)

**Comment by FelisCatus** [comment]
要不要试试看在本地搭建一个 Polipo 之类的代理服务器然后看看能不能用？我也不知道是什么问题，但……

**Comment by iccfish** [comment]
本地搭个代理……啥。。。是说本地架设一个代理看看用户名密码是不是能用吗

**Comment by FelisCatus** [comment]
是啊……

**Comment by iccfish** [comment]
本地用CCPROXY跑了一个……一样……要输入用户名密码。。

**Comment by FelisCatus** [comment]
还可以看一下`chrome://plugins/`里是否有奇怪的东西，然后禁用一些看看。如果还不行……我感觉我已经没任何办法了……

哦不对，还有最后一招：打开 SO 扩展的 background.html ，在开发者工具的 Console 贴入以下代码：

```js
chrome.webRequest.onAuthRequired.addListener(console.log.bind(console), {
      urls: ['<all_urls>']
    }, ['blocking']);
```

这样每次询问用户名密码应该会有一条日志（注意日志只会出现在这个控制台里，而不会进入 SO 的导出日志功能）。我建议仔细检查日志中的 `challenger` 的 host 和 port 是否符合预期。

如果这个都不调用的话那么 300% 是 Chrome 的锅……啊，其实也未必，也可能是杀毒软件或者某下载软件改了什么不该改的……

**Comment by iccfish** [comment]
恭喜，甩锅成功，Chrome光荣地背了锅，因为自始至终没有任何日志……

不过我想问题解决了……原因是因为新版本的Chrome貌似有这么个东西……

![qq 20160307153915](https://cloud.githubusercontent.com/assets/1091653/13563225/f0da9224-e47a-11e5-98d6-054ecf5e2f19.png)

我一直以为这个仅仅涉及到内容脚本（Content Scripts），所以有个叉叉也一直没去在意，现在才发现这个叉叉原来是会影响后台脚本的权限的。。如果前台没有允许使用的话，那么后台脚本也是拿不到相关数据的（包括事件也不会触发） ……开启为全部允许就行了……

So sad。。。。

**Comment by celeron533** [comment]
我刚刚发现目前的chrome 49.0.2623.75m 还没有“可在当前网页运行”的选项。。。

**Comment by FelisCatus** [comment]
这是什么新功能……好像很厉害的样子……如果这个默认是“点击即可运行”的话，感觉能坑掉很多扩展……

如果这个是改 URL 的权限，那么不仅影响 Content Script，还影响 AJAX 跨域和 `webRequest` API。 SO 无任何 Content Script ，但使用 AJAX 跨域来更新规则列表和PAC等，并使用 `webRequest` 来实现未加载资源和代理验证两个功能。结果就成了大部分功能还能正常使用，但无法更新规则列表、无法显示未加载资源和无法使用代理验证的情况……这种问题超难定位啊。

**Comment by FelisCatus** [comment]
哦哦，会不会是在 `chrome://flags` 里开了 `User consent for extension scripts`？这个可是实验功能哦，千万要小心使用～

**Comment by iccfish** [comment]
这个功能之前版本也是有的，不过需要到Flags里开启，之前还有过bug，所以我是不是后来什么时候又打开了不记得了。但是至少在我手里的这个dev版本是默认开启的，并且默认是点击即运行。
貌似我切换到DEV的开始就有这个功能了，所以一直没想过这个，之前不是DEV的时候我用的也是Beta版，好像也有这个了，所以我才说出现这个问题很久了……

看到工具栏上打叉叉的扩展，全部是被拦截的。不过还好的，这样能降低扩展对页面性能的影响（扩展非常非常影响页面的加载速度）。对于大多数不是每个页面都要用的，需要的时候点击一次就运行，还是很不错的。只不过对于全局可能会导致后台功能失效的（比如后台的代理和连接参数修改啥的），这是个坑，因为我一直以为这只是影响ContentScripts，没想到还控制了后台……

可想而知的是，如果没有启用全部运行，至少我能想到的已安装扩展里肯定有几个失效的，比如Header修改之类的（refControl，UserAgent修改类）都会失效。
于是我突然明白了前些日子找扩展的时候为啥总觉得那几个扩展都不灵了…… :joy:

**Comment by FelisCatus** [comment]
如果有时间的话，能麻烦在 `chrome://flags` 里点一下右上角 `Reset all to default` 么？（在这之前请记好已经开启的实验项目，以便随后恢复。）我想看看是否确实此功能是默认启用。谢谢。

**Comment by iccfish** [comment]
留意我5个小时前的回复：重置了所有的Chrome选项……其实就是重置了这里的Flags。其实按理说重置了应该就可以解决的（刚确认了默认是不启用的），之所以那时候没有发现解决应该是因为重启之后自动打开的标签页，此时SO还没有加载（异步加载）所以导致还是弹出了密码框，所以我以为没解决并恢复了设置……:joy:

**Comment by FelisCatus** [comment]
好吧，辛苦了……总之解决了就好……就好……好……（躺）

**Comment by akyou** [comment]
我也出现那样子的问题要怎么搞

**Comment by FelisCatus** [comment]
@akyou 去 `chrome://flags/#extension-active-script-permission` 里把那个 flag 禁用掉。

**Comment by akyou** [comment]
本身就是禁止掉的但是还是那个样子不知道是不是pac的问题

2017-05-23 0:16 GMT+08:00 Felis Catus <notifications@github.com>:

**Comment by FelisCatus** [comment]
@akyou 感觉应该是另外的问题，另外开 Issue 报告吧。
