### ISSUE TITLE
导出的sorl规则列表里的URL不管什么情景模式都混杂在一起

### ISSUE THREAD

**Issue by chitanda** [FelisCatus/SwitchyOmega#720]
RT。
目前SO我就用了两个情景模式，一个是全局SS代理另一个是手动加的SS规则。然后我个人会不定期的将SO的自定义规则导出到SS的`user-list`里去使用(可参考此文：[ShadowSocks 自定义规则](http://honglu.me/2015/06/26/ShadowSocks%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%84%E5%88%99/))
但是今天发现一个问题：
> 导出的SORL文件里的规则全部都是普通的URL匹配规则，没有例外规则。哪怕那个规则我在自动切换规则里写的是`直接相连`.如下图：（百度域名被配置了直接相连，但是导出的SORL文件里是`www.baidu.com`而不是`@@||www.baidu.com`这样）
![image](https://cloud.githubusercontent.com/assets/8258592/13591625/612b7f20-e525-11e5-963f-f1dab2e20359.png)
![image](https://cloud.githubusercontent.com/assets/8258592/13593070/1a9c9e00-e533-11e5-8119-d9699ad468c3.png)

考虑到可能很多人有其他的代理配置，所以我在想**导出成SORL文件的时候能否将域名按照情景模式分组**，这样也好针对性的处理？

**Comment by FelisCatus** [comment]
首先感谢错误报告……我这边发现了一个很严重的问题，就是导出的结果没有bypass的规则。按照原本的设计，`www.baidu.com => 直接连接`应该导出成`!www.baidu.com`（最前面有一个感叹号），因为目标“直接连接”是和默认规则“直接连接”相同。这个问题我建立了 #721 来跟踪。

关于导出成到`user-rule.txt`的用法，目前的决定是暂不做直接的支持，具体技术说明和相关讨论见 #699. 不过导出 SORL 然后自己转换格式当然是可以的。

我感觉 #721 修复以后已经可以满足这个场景了（只需在编辑器中替换`!`为`@@||`即可）。还需要做按照情景模式分组吗？

如果真的按照情景模式分组了，那么导出的顺序会和书写顺序不同，将会影响已有的 SORL 正常使用。（请特别注意 Switch Profile 和 SORL 的本意就是从上到下依次匹配的，保证顺序是有必要的。）这个要怎么处理呢？所以如果 #721 修复后已经可以用了的话，我不是很倾向于再加一种导出方式。

**Comment by chitanda** [comment]
@FelisCatus 感谢回复。之所以说按情景模式分组主要原因有以下两个：
1. 之前没有想到您上面提出的解决方案，我原先是准备分组后手动添加`@@||`
2. 其他人还有别的代理模式比如GOA之类的，感觉您很难用bypass规则覆盖全部代理规则。(当然这个只是我臆测实现方案了，可能实际上并不存在这个问题）

不过就我个人来说**这个分组功能其实无所谓了**——因为我个人需求的话，就像您说的**只需在编辑器中替换!为@@||**,可以直接满足了。

**Comment by FelisCatus** [comment]
#721 的问题已经在 v2.3.17 版本修复。

我先关闭这个了，如果其他人还有分组的需求，请评论并重新开启。
