### ISSUE TITLE
偷偷重定向各大购物网站合适么，正大光明不好么

### ISSUE THREAD

**Issue by lajicab** [FelisCatus/SwitchyOmega#724]
偷偷重定向各大购物网站合适么，正大光明不好么

**Comment by celeron533** [comment]
我没有遇到过这样的问题。

个人猜测可能原因：
* 无良ISP重定向了http error的页面
* 无良ISP进行了域名/http劫持
* 用户局域网有arp病毒
* 用户系统上有无良插件
* 用户浏览器上有无良插件（包括SwitchyOmega）
* 用户使用的代理服务器上具有重定向行为，比如免费的翻墙服务器会定时推送一些广告

这个项目是开源的，有兴趣的可以亲自审计一下。

**Comment by ggmm2008** [comment]
很有可能是无良ISP进行了域名/http劫持

**Comment by FelisCatus** [comment]
SwitchyOmega 是自由软件，[所有源代码](https://github.com/FelisCatus/SwitchyOmega)可供所有人自行查看。您如果怀疑到 SO 头上来了，不妨亲自去看看代码。此外， SO 是非盈利项目，不存在给购物网站打广告的动机。

不过如果是我碰到这种事情，我估计首先也会怀疑各种扩展/插件吧。先到`chrome://extensions/`里禁用所有扩展，再到`chrome://plugins/`里禁用所有插件，看看是否还有这种情况。如果还有的话，估计就是您的网络提供商/代理服务器提供商动的手脚。正如 @celeron533  如果您用的是免费的代理服务器，非常可能是那个代理服务器在推送广告。
