### ISSUE TITLE
关于网页跨站信任问题

### ISSUE THREAD

**Issue by ggmm2008** [FelisCatus/SwitchyOmega#725]
我设置了A网站域名通过代理访问，但A站部分文件是通过CDN加速的，而这些CDN地址没有在规则里，经常会导致CSS,JS等文件加载失败，不知道是否可以改成，只要是我信任的站点打开的网页都适用A站的规则。

**Comment by gameboy709494** [comment]
那就再添加啊。如果你访问OneDrive.com，你体验会更深咯。

**Comment by FelisCatus** [comment]
根据页面本身的URL来决定整个标签页所有资源的代理，在 PAC 脚本层面是不可行的。因此， SO 没有办法提供这个功能。

**Comment by FelisCatus** [comment]
我的建议是反复使用未加载资源功能，直到整个网站能正常加载为止。通常一次就可以了，但有的比较复杂的网站可能需要三四次。
