### ISSUE TITLE
In the auto-switch list, also include the "system proxy"

### ISSUE THREAD

**Issue by Lambik** [FelisCatus/SwitchyOmega#728]
Hi,

When configuring the auto switch list, I would also need to be able to choose "system proxy" for the "default" rule, since "direct connection" does not do what I want it to do.

Could you add this, or explain why it isn't there? Thanks!

**Comment by FelisCatus** [comment]
This is not possible as discussed in #289.

**Comment by Lambik** [comment]
Yes, I'm sorry for bothering you with it. I closed it for that reason, but could not find a delete button.
