### ISSUE TITLE
老是出现页面的资源未加载，明明加入到翻墙列表了！

### ISSUE THREAD

**Issue by moerfutin** [FelisCatus/SwitchyOmega#729]
自动切换模式下。如题！ 很烦，搞的自定义列表老是重复添加通配符url。神烦，感觉omega根本没老版本sharp好用！！！

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by FelisCatus** [comment]
如果已经添加了，还是出现未加载的情况，就不是因为没有翻墙的问题了。一般来说，这种时候应该换一个速度快一点/稳定一点的代理服务器。也可能是网络连接本来就不稳定，所以代理连接也不稳定。

如果只是看着这个数字比较烦，可以到选项>通用>网络请求里关闭未加载资源的提示。不过先说好，这个只是关闭提示了，并没有实际解决任何问题，只能做到眼不见心不烦，帮助你平复躁动不安的情绪，保持一颗明镜止水的心，少打几个感叹号。

SwitchySharp 和 SwitchyOmega 都只是代理设置软件，原理来说是差不多的，只不过是告诉 Chrome 去访问你的代理服务器而已，不会去碰网络连接等底层的东西，更没办法提高/降低代理服务器的稳定性。如果你愿意换旧版 sharp 我也没有意见，不过就算你迁怒 omega ，你的代理服务器也不会变得更快/更稳定，该加载不出来的还是加载不出来……

**Comment by jiayouQLL** [comment]
我也出现了这个状况，难受。

**Comment by AnyWAT** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/1681#issuecomment-442746440

**Comment by grayashlew** [comment]
确实换了代理就没这个问题了。。。
