### ISSUE TITLE
希望添加“GFW应对模式”

### ISSUE THREAD

**Issue by Septembers** [FelisCatus/SwitchyOmega#73]
希望引入COW的探测模式：
https://github.com/cyfdecyf/cow#cow-%E5%A6%82%E4%BD%95%E6%A3%80%E6%B5%8B%E8%A2%AB%E5%A2%99%E7%BD%91%E7%AB%99
> COW 将以下错误认为是墙在作怪：
>
> 1. 服务器连接被重置 (connection reset)
> 2. 创建连接超时
> 3. 服务器读操作超时
>
> 无论是普通的 HTTP GET 等请求还是 CONNECT 请求，失败后 COW 都会自动重试请求。（如果已经有内容发送回 client 则不会重试而是直接断开连接。）
>
> 用连接被重置来判断被墙通常来说比较可靠，超时则不可靠。COW 每隔半分钟会尝试估算合适的超时间> 隔，避免在网络连接差的情况下把直连网站由于超时也当成被墙。 COW 默认配置下检测到被墙后，过两分钟再次尝试直连也是为了避免误判。
>
> 如果超时自动重试给你造成了问题，请参考样例配置高级选项中的 readTimeout, dialTimeout 选项。

另外希望默认配置：GFWList #9

**Comment by Septembers** [comment]
https://github.com/zizon/switchyd#what-it-does--how-it-works
可以参考学习switchyd的基于Hooks的自动学习
这样针对一部分被墙网站可以自动学习并代理

**Comment by FelisCatus** [comment]
v2.3.6 已经能做到部分检测被墙网站了，[见说明](https://github.com/FelisCatus/SwitchyOmega/issues/6#issuecomment-74818135)。
