### ISSUE TITLE
SwitchyOmega此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by newcastlecy** [FelisCatus/SwitchyOmega#731]
![image](https://cloud.githubusercontent.com/assets/3032427/14009649/f14db280-f1c8-11e5-96f9-05ef8be16f00.png)

**Comment by celeron533** [comment]
google那边允许每个extension上传的空间就那么大。。。曲线救国的方法是拆成两个情景模式。第一个情景模式匹配链的末端跳转到第二个情景模式，然后第二个情景模式匹配链末端你自己定义。

**Comment by FelisCatus** [comment]
话说，如果不介意的话，能否说明一下配置了多少条规则？是否使用了规则列表功能？规则列表是从URL更新的还是手动填写的？

因为这个问题没有办法修，所以我就先把这个关掉了……不过欢迎继续讨论。

**Comment by newcastlecy** [comment]
+FelisCatus  只有14条 规则,还有 gfwlist.txt

**Comment by FelisCatus** [comment]
首先请检查一下规则列表必须填写网址，否则需要整个规则列表正文同步，肯定会超出限制。

其次就是，一旦有一次超出过限制，那么这个情景模式就没有办法再同步了。即使后面通过删除规则或者之类的方式减少了空间占用，也还是不能同步。（这是因为SO没有办法测量占用了多少空间。）新建一个情景模式然后再进行同样的配置，可能可以解决问题。

**Comment by eromoe** [comment]
能不能允许外部存储？比如注册个github 仓库，所有用户的规则直接存这个仓库。因为都是代理规则，所以没有安全问题。

**Comment by yfdyh000** [comment]
Github仓库会有隐私问题。
可以用 http://gist.github.com/ ，支持私有gist和Github令牌（限制仅gist），参考 https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by eromoe** [comment]
我的意识是，用户就不管了，根据用户账号hash直接存一个目录。还可以统计下用户地理位置，整合地区性规则列表。   不想让别人知道自动代理站点的就自己加个地址。

**Comment by celeron533** [comment]
>还可以统计下用户地理位置，整合地区性规则列表。 不想让别人知道自动代理站点的就自己加个地址。

SwitchyOmega只是代理切换工具，并不是翻墙专用，没有必要也不愿意记录用户数据。

**Comment by eromoe** [comment]
@celeron533 那有没考虑做个这种插件？ 和SwitchyOmega 配合，明确告知记录站点，实时在github上整合用户翻墙列表，根据区域和网络位置 定时更新。 这样很多新用户也容易上手，比较好的扩充翻墙名单的方法。 GFWlist 覆盖的太小了。

**Comment by gitcomy** [comment]
有解决办法了吗？
能不能像油猴一样存到onedrive或者google drive

**Comment by AnyWAT** [comment]
👌为减少存储空间而归纳、合并：
1、相同协议与端口的在情景模式名称上能一目了然。。。
2、能自定义端口的统一到不能自定义的端口上来

**Comment by qins** [comment]
是个问题，可以维护一个更广的gfwlist，从而减少自定义的链接数量。类似的一个list链接就可以容纳任意数量的链接了。
也纳闷几百条文本才占多少空间，限制太狠了。

**Comment by Antecer** [comment]
为什么不用WebDAV存储数据呢？再大都不是问题。
