### ISSUE TITLE
Option For Current Tab To Connect To Specific Proxy

### ISSUE THREAD

**Issue by pepanee** [FelisCatus/SwitchyOmega#732]
Hello, so I have a request for an option that would be very useful for me, and probably for others too.
Can you add an option to where I can make a current tab connect to a specific proxy?

So for example, I have 2 tabs that are both open at: google.com
Yet this when I click the icon, at the bottom of the list I would see: google.com and an arrow next to it. When I click the arrow, I can make Google connect to a specific proxy. Yet the problem is that I don't want both tabs to connect to that same proxy; I want the first tab to connect to Proxy #1, and the second tab to connect to Proxy #2. I will attach a picture that I drew by hand for a visual of what I said. 

Please add this option! Thanks!

![proxy for current tab](https://cloud.githubusercontent.com/assets/18107878/14069979/930221d6-f455-11e5-9882-d4b3675b7593.png)

**Comment by FelisCatus** [comment]
Tab information is not available for PAC scripts, so this cannot be implemented in SwitchyOmega. See #646.

**Comment by pepanee** [comment]
Okay. Thank you for the quick reply. I don't understand too much about programming, so I don't really know what PAC scripts mean. I skimmed over #646, and saw that it has been discussed earlier. I saw that guy was using a work-around for it, but got confused. Do you think you can post on here some sort of similar work-around that I can do to put that into effect? 

Thank you

**Comment by FelisCatus** [comment]
If you need different proxy for different tabs, these are options for now:

* Use two Chrome users.
  1. Click on the top-right user switcher button (the one with your name on it), select Switch Person
  2. Click on the `Add Person` button on the popup window
  3. Now you have two different users. Each user has their own apps and configuration, so you may install SwitchyOmega on both of them and configure them individually. You may want one window for each user for testing proposes.
* Use Incognito mode.
  1. Right click on SwitchyOmega icon, and select `Manage extensions`.
  2. Ensure `Allow in incognito` is UNCHECKED. By unchecking this, SwitchyOmega only applies proxy settings to normal windows.
  3. Open an incognito window on the Chrome menu. Incognito windows will NOT be controlled by SwitchyOmega and will use system proxy settings instead.
  4. Configure your system proxy to fit your need. For example, change IE's proxy settings on Windows.
  5. In the future, SwitchyOmega may support selecting different profiles for normal and incognito, so you don't have to configure anything in system settings. See #10.

Please note that either option will only allow you to have different proxies for different WINDOWS, not TABS. These solutions are not perfect, not are they convenient: In Incognito mode, you are limited to TWO proxies (one for normal windows and one for Incognito). You can have as many users as you like, but adding a new user requires much time to setup (e.g. installing SwitchyOmega once for each user). However, I believe these are the only options for now.

**Comment by pepanee** [comment]
Alright, I understand the two options you provided. As a matter of fact, I am trying to set up many different proxies for one website, yet those two options do tend to limit that. Well, thanks for the descriptive reply you provided, yet I'll just wait until that option is possible.

Please post back on this thread whenever that option is possible, so I would receive a notification email... that's if you remember this whole thing later on in the future =D

Thanks again

**Comment by FelisCatus** [comment]
It is very unlikely that tab-based proxy selection is going to land on SwitchyOmega according to the limitation that we just discussed.

Meanwhile, if possible, please explain why you would like to test different proxies for one website and the specific reason for use tabs to accomplish the task. I could propose some alternative solutions based on your particular use case if you like. For example, are you doing speed testing?

**Comment by pepanee** [comment]
Sometimes I want to download multiple files from a single location, yet I am only allowed to download 1 file at a time from an IP number.

No worries though, I appreciate your explanation that this option isn't currently possible to do apply. Hopefully the near future will fix this thing.

**Comment by FelisCatus** [comment]
In that case, it is quite do-able with just one tab. After you initiate the download (when the file shows up in Chrome's downloads Manager), you are safe to switch to any other proxy you want. Since proxy resolving is done BEFORE initiating the download request, the file being downloaded will continue to use the old proxy and complete without any problem.

With that assured, you may safely switch to another proxy and refresh the page with the file list. Click on another file you want to download, and let it start before you switch to yet another proxy. Repeat these steps for a few times, and you can simultaneously download multiple files, each with its own proxy.

Be warned that you can't pause/restart the file download though. Otherwise the request will go through the current proxy at the moment it is resumed/restarted and will be likely to fail due to IP restrictions.

**Comment by pepanee** [comment]
Cool thanks for the information. See sometimes I want to pause the download, yet that doesn't work with the method provided. But thank you for taking the time in explaining everything. I'll just wait it out until the technology is possible.

**Comment by aeroxy** [comment]
This would be a very useful feature for users in China since we need to access western websites like Google and Facebook via proxy but we need to access local websites like Baidu and Weibo via direct connection.

**Comment by evg-zhabotinsky** [comment]
> This would be a very useful feature for users in China since we need to access western websites like Google and Facebook via proxy but we need to access local websites like Baidu and Weibo via direct connection.

Isn't choosing different proxy based on hostname / IP / URL the best way to achieve that? It definitely is one that SwitchyOmega supports. I have a Switch profile set up and active, it defaults to Direct connection, and whenever an URL fails to load I add a condition for the domain to go through my Proxy profile. Conditions can be added very conveniently through SwitchyOmega button / indicator menu.
