### ISSUE TITLE
请问能否增加本地DNS解析或提供手动关闭远程DNS解析的功能？

### ISSUE THREAD

**Issue by ZenFX** [FelisCatus/SwitchyOmega#733]
在公司必须使用代理进行上网，在使用Firefox浏览器时，可以手动设置是否远程解析DNS，这样本地hosts文件可以生效。现在使用Chrome浏览器，默认都是远程解析DNS，这样的话本地hosts文件就完全没作用了，因为一些原因需要使用到hosts文件，而且hosts文件内容较多，不适合手动添加规则，所以希望SwitchyOmega插件能提供一个在开启代理的情况下可以打开或关闭远程DNS解析的功能。

**Comment by FelisCatus** [comment]
我只知道 SwitchyOmega （作为扩展）是没有办法设置这个选项的。至于 Chrome 能不能设置这个嘛……很难说，也许有开关，也许只能改参数重新编译。不过默认是打开的，这一点可以确定。

虽然很抱歉，不过也只能麻烦您自行查找一下如何设置了。如果有什么发现的话，请告诉我。

P.S. 通过合适的文本处理，可以把 hosts 文件的规则转换成 SO 的规则列表格式，然后直接粘贴到SO的“编辑源代码”或者“规则列表”功能里使用。虽然这个也很坑……另外的方式就是用工具（或者扩展）把 hosts 转成 PAC 文件，也一样可以导入进 SO 。

**Comment by jeremyxu2010** [comment]
> 我只知道 SwitchyOmega （作为扩展）是没有办法设置这个选项的。至于 Chrome 能不能设置这个嘛……很难说，也许有开关，也许只能改参数重新编译。不过默认是打开的，这一点可以确定。
> 
> 虽然很抱歉，不过也只能麻烦您自行查找一下如何设置了。如果有什么发现的话，请告诉我。
> 
> P.S. 通过合适的文本处理，可以把 hosts 文件的规则转换成 SO 的规则列表格式，然后直接粘贴到SO的“编辑源代码”或者“规则列表”功能里使用。虽然这个也很坑……另外的方式就是用工具（或者扩展）把 hosts 转成 PAC 文件，也一样可以导入进 SO 。

@FelisCatus 能详细指导一下怎么操作吗？比如我这里有一个域名 `test.aaa.local`，其在`/etc/hosts`里指向了`10.17.0.236`，而`10.17.0.236`这个IP只能通过SOCKS5代理才能连接到，部署的网站又必须以`test.aaa.local`域名来访问。

**Comment by Justsoos** [comment]
这个功能应该是由 socks5/http proxy 客户端来支持的，SwitchyOmega 没法做到这个功能。
目前我使用 proxifier 客户端的这个设置来选择本地或远程 dns 解析：
![image](https://user-images.githubusercontent.com/3480043/72660220-d0c46200-3a05-11ea-93f4-7eac05b0315c.png)
