### ISSUE TITLE
How do I get a Rule List URL?

### ISSUE THREAD

**Issue by ballII** [FelisCatus/SwitchyOmega#737]
Rule List URL is left blank, and Rule List Text is also blank (and cannot be edited). What should I do? (My Auto Switch seems to work, but the Extensions page just keeps warning me "Please correct the errors in this page", and prevent me to visit other SETTINGS or PROFILES pages.)

P.S. I used SwitchySharp before, and I don't remember providing any rule list URL for SwitchySharp.

**Comment by FelisCatus** [comment]
Also, you may click on the red button with the trash icon beside "Rule list rules" in the Switch rules section above if you want to remove the rule list feature from this Switch Profile.
