### ISSUE TITLE
明明gfwlist里有规则，为啥还提示网页有资源没有加载呢？？？ 真崩溃啊！！

### ISSUE THREAD

**Issue by moerfutin** [FelisCatus/SwitchyOmega#738]
![Uploading 捕获sdfs df.P
![sdfs df](https://cloud.githubusercontent.com/assets/9960618/14183977/7878b1ba-f7a5-11e5-9814-37a637baedf7.PNG)
NG…]()

如题！！ 每次页面有gfwlist里本身有的元素，还被提示要加入自定义列表，不停重复，真崩溃啊，wuyu! 根本不如switchysharp好用！
 

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36
```
[1] Unhandled rejection:
 Error
    (No stack trace)
```

**Comment by johnhuo** [comment]
See #729！
话说你都开了#729了，同样的问题。还来再开一个issue.
这已经不是So的问题了，是你翻墙通道的问题。

**Comment by FelisCatus** [comment]
我觉得我[在之前回复的时候](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)已经[说得](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)非常[清楚](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)了，请不要[反复](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)建立[相同的 Issue](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)，只会给项目维护者和其他人带来[不必要的负担](https://github.com/FelisCatus/SwitchyOmega/issues/729#issuecomment-198881621)。

↑ 看到这么多链接了吗？请您高抬贵手点一下，进去看之前的回复。如果有任何其他问题或者仔细阅读过解释以后还有疑惑，欢迎再提出。但如果您再次发送重复内容来抱怨同样的问题，尤其是此问题和SO无关的情况下，您将会[被屏蔽](https://help.github.com/articles/blocking-a-user/)，从而无法在此项目中建立任何 Issue 或回复。
