### ISSUE TITLE
虚情景模式,能否给个例子教程?

### ISSUE THREAD

**Issue by joshatt** [FelisCatus/SwitchyOmega#739]
看了好几篇讨论,都是说如何理解虚情景. 大体的用途我能理解. 问题的关键是添加的步骤不明白. 求步骤实例. 
不理解的: 
虚情景模式....
迁移到虚情景模式...
这两个是干什么的?

**Comment by FelisCatus** [comment]
第一节：虚情景模式：

设置该情景模式的“目标”。如果A虚情景模式的目标是B，那么切换到A的效果等同于切换到B。可以随时调整。

第二节：迁移到虚情景模式：

点击那个按钮会将所有指向B的规则修改为指向A. 主要是用于替换自动切换里的规则。

这个功能主要用于原先有大量规则选择了B作为结果的情况。例如原先只有自动切换和 Proxy1 两个情景模式，然后自动切换中有很多规则（比如公司内网地址）都设置成了 Proxy1 。而现在希望规则不变，但可以方便地选择公司内网的这些网址使用 Proxy1 或者 Proxy2 ，则应该新建虚情景模式叫做 Intranet ，然后点击这里的迁移按钮。

如此一来，自动切换中原先指向 Proxy1 的规则都指向 Intranet 了，然后 Intranet 再指向 Proxy1 或 Proxy2 。相当于在一个统一的地方切换多个规则所对应的代理。

**Comment by joshatt** [comment]
@FelisCatus  多谢解答. 我实验了一番, 似乎明白了----- 新建起名字"虚proxy", 然后必须第一节和第二节都要设置, 而非二选一.  第一节设proxy1, 第二节设: proxy1-->虚proxy.......这样的话, 今后如果添加新的proxy2, proxy3等等, 都不用写规则了, 随时把规则切换过来用

**Comment by joshatt** [comment]
还是有点迷惑: swithyomega的图标显示"虚proxy[proxy1]", 那么我怎么知道国内的网站例如百度, 是走的直接连接呢,还是走的proxy1 ?

**Comment by FelisCatus** [comment]
如果要自动切换，请在菜单里选自动切换……

**Comment by joshatt** [comment]
我是真糊涂了. 想要的是: 通过虚情景, 快速地在不同的代理之间切换, 而各网站规则只在一个代理设置中设好就行了........... 我这么说吧, 这个扩展有两个要素: 代理和网站规则, 设置完后, 又表现成两种东西: "xxx代理"和"xxx自动切换". 
1, 那么在设置虚情景的时候, "目标"是应该填写xxx代理呢, 还是xxx自动切换呢?   
2, 实际使用中, 在虚情景下切换时, 是选 xxx代理呢, 还是xxx自动切换呢? .....我发现选代理的话, 全局了. 选自动切换的话,连不通了

**Comment by joshatt** [comment]
@FelisCatus 谢谢解答.
看了此文,才完全明白: https://gochrome.info/switchyomega-virtual/
原来关键是: 
实际使用时, 要在选中"xxx自动切换"的状态下, 进行虚情景内的代理切换;

**Comment by libiao7** [comment]
感觉就是 批量的   查找  替换
