### ISSUE TITLE
doesn't work after upgrade to 2.3.19

### ISSUE THREAD

**Issue by v6bit** [FelisCatus/SwitchyOmega#741]
I have been used the  switchyOmega  through SSH-D, thank you for the software.
after upgrade to 2.3.19, I can't connect the proxy anymore.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36

**Comment by FelisCatus** [comment]
Does the error page shows you "cannot connect to proxy" or something similar?

If you can connect to the proxy but still can't visit any webpage, then it's not SwitchyOmega's part. Make sure that your SSH connection is stable and your server/port isn't blocked by firewalls.

**Comment by v6bit** [comment]
The firefox+autoproxy works well on the same SSH connection!
The error page shows

This site can’t be reached

The connection was reset.
ERR_CONNECTION_RESET


Reload
Hide details





 
 
------------------ Original ------------------

**Comment by FelisCatus** [comment]
Hi, please enter `chrome://net-internals/#proxy` in the address bar and check the text displayed on the page. It should show you the proxy information. Please copy the text and paste it here.

**Comment by v6bit** [comment]
EEffective proxy settings
Proxy server for everything else: socks5://127.0.0.1:7070


 
 
------------------ Original ------------------

**Comment by FelisCatus** [comment]
In that case, SwitchyOmega already did its job. If you are running `ssh -D7070`, then Chrome should connect to that SOCKS5 server.

But just in case you are wondering what happened, #557 could be an example of a third-party program interfering the connection between Chrome and the proxy server. That particular issue is about Thunder and `XLServicePlatform` tweaking system-wide TCP settings, but other software may also cause the same issue.

Please also note that `ssh -D` offers `SOCKS5` proxy only and **changing the protocol to `HTTP` isn't a valid workaround in your case,** so you may want to find out the exact misbehaving program and uninstall it.

**Comment by v6bit** [comment]
我用的是securet ssh登录到proxy上的，
一直以来chrome+SwitchyOmega都工作正常，似乎是升级后出了问题，起先我以为是墙升级了
后来发现直接vpn没有问题，有发现用firefox+autoproxy工作也正常






 
------------------ Original ------------------

**Comment by FelisCatus** [comment]
我感觉非常像是 #557 ，因为 #557 似乎只影响 Chrome 而 Firefox 仍然能正常使用同一个代理。请看一下 #557 的讨论，然后卸载迅雷吧。当然也不排除其他软件修改了 TCP 参数的可能性，也可以试试看`netsh winsock reset`之类的。

**Comment by v6bit** [comment]
是的，卸载掉迅雷极速版后，可以工作了
以后不用渣雷了，改用qq下载了


 
 
------------------ Original ------------------
