### ISSUE TITLE
Chrome代理失效的问题

### ISSUE THREAD

**Issue by johnstevin** [FelisCatus/SwitchyOmega#744]
前置添加(环境)：
1. 虚拟机vagrant(CentOS 6)，代理服务shadowsocks
![qq 20160410124844](https://cloud.githubusercontent.com/assets/7678086/14408167/347d6410-ff1b-11e5-8a21-a0c27a578659.png)
![qq 20160410124711](https://cloud.githubusercontent.com/assets/7678086/14408171/47561582-ff1b-11e5-9958-672bc292c3da.png)
2. 宿主机win8.1，SwitchyOmega
![qq 20160410125606](https://cloud.githubusercontent.com/assets/7678086/14408185/d1ab3a50-ff1b-11e5-86b1-2a68589af22e.png)

问题：
1. 主机可以正常访问192.168.33.10，火狐浏览器也可正常代理192.168.33.10，唯独SwitchyOmega不能代理通讯，请教是否有Bug存在？？？！

**Comment by johnhuo** [comment]
装迅雷了吗？迅雷会引起win下socket代理失败
2016年4月10日 下午1:01，"蜗牛先生" <notifications@github.com>写道：

**Comment by johnstevin** [comment]
确实啊，我尽然没发现这个问题，我卸载后成功了！

感谢johnhuo！
