### ISSUE TITLE
Linux下导致chrome经常崩溃

### ISSUE THREAD

**Issue by bighzl** [FelisCatus/SwitchyOmega#746]
Linux下启动Omega会经常导致chrome崩溃， Linux版本是deepin 15.1.1 based on Debian 8。狠狠狠频繁

**Comment by johnstevin** [comment]
换Ubuntu。。。

**Comment by FelisCatus** [comment]
崩溃属于 Chrome 问题，请前往 Chromium 项目反馈。

此外，很多 Linux 发行版自带的 Chromium 可能版本会比较落后，建议手动前往 Chrome 主页下载最新版然后再试。如果不行还可以试试看 Chrome Beta.
