### ISSUE TITLE
Startup Profile does not work

### ISSUE THREAD

**Issue by sluTTYusr** [FelisCatus/SwitchyOmega#747]
Hello and thanks for the extension.

Startup profile does not work. I set it in preferences and when I close and reopen the browser system proxy is active.
I have to set the desired proxy by hand.

SwitchyOmega 2.3.19
Chromium 49.0.2623.112 (64-bit)

This happened with earlier versions of Chromium as well.

**Comment by FelisCatus** [comment]
Did you choose system proxy before you close Chromium? If so, then Chromium was probably running in the background and that browser instance was reused when you attempt to re-open it.

Please note that closing all the windows does not always close Chromium itself. It can still be running in the background with Apps or other stuff running. You may want to check the process manager to see if anything is left. Look for process with the name `chromium` or `chrome` (even if your browser is branded `Chromium`).

If the startup profile does not kick in even if you've restarted the whole operating system, then something is seriously wrong. Please right-click on the extension icon and click on `Save error log` and upload the log here. In some rare cases, applying a profile can fail and system proxy is then used as a fallback.

**Comment by sluTTYusr** [comment]
Here's the log.
I have the feeling it might have something to do with the '--disable-reading-from-canvas' option I start Chromium with.
[OmegaLog_1460397425724.txt](https://github.com/FelisCatus/SwitchyOmega/files/213559/OmegaLog_1460397425724.txt)

**Comment by FelisCatus** [comment]
SwitchyOmega uses canvas to draw profile icons and disabling reading from canvas will certainly prevents the extension from working properly.

See #715 for further discussion on this.
