### ISSUE TITLE
socket代理不能进行remote server dns解析

### ISSUE THREAD

**Issue by howorkon** [FelisCatus/SwitchyOmega#748]
相同的socket代理设定
火狐可以上网，chrome不能上网。
修改主机dns设定后，chrome能够上网。
火狐的foxyproxy里面有远程dns查询选项，这个设定在switchyomega没有找到。

**Comment by celeron533** [comment]
是socks代理还是socket代理呢？

**Comment by FelisCatus** [comment]
Chrome 环境下 SOCKS5 是默认进行远程 DNS 解析的，但可能会有 DNS 泄漏问题，见[此处说明和解决方案](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87)。

此外， Chrome 并不能手动选择使用远程解析/本地解析。
