### ISSUE TITLE
关于规则顺序问题

### ISSUE THREAD

**Issue by iir910** [FelisCatus/SwitchyOmega#75]
测试了一下自动切换里面规则列表的顺序的优先权问题。

结论是： 一个url符合两条（或以上）规则时，列表排在上面的会覆盖掉下面的。

---

如果在设置界面来添加新规则的话，是添加都列表最下方的。
如果想不新规则被覆盖掉，就要手动拖到上面。。
列表要是一长一点的话，手动调整顺序操作麻烦。
最好是新建规则时，能够在任意位置插进去

![3333](https://cloud.githubusercontent.com/assets/7844741/5422840/8e22083c-82d4-11e4-9611-15a06566d7e4.png)
设想是这样所有在规则的右边加个按钮，可以在当前规则的下方插进一条新规则。

**Comment by Justsoos** [comment]
本想提个建议 “操作” 里设置 “置顶，置底”的，看到这个也算解决方案，虽然很曲折，拗脑：

由于google多数域名被封，但 translate.google.cn 是没封的，也常用。
所以在自动切换的最上面增加规则 “translate.google.cn” “直连”，按顺序，这样下面再设置 “*.google.com” “虚拟情境” 就非常方便了。
最好能设置个置顶，置底按钮。
