### ISSUE TITLE
请教这是什么鬼啊

### ISSUE THREAD

**Issue by moerfutin** [FelisCatus/SwitchyOmega#750]
![fireshot screen capture 394 - -](https://cloud.githubusercontent.com/assets/9960618/14563745/127ae04c-0356-11e6-971b-b421d39d1df1.png)

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36

**Comment by FelisCatus** [comment]
见 #678
