### ISSUE TITLE
SwitchyOmega Extension Crashes Chrome while I open a file

### ISSUE THREAD

**Issue by drazla** [FelisCatus/SwitchyOmega#751]
SwitchyOmega Extension Crashes Chrome while I open a file with the keyboard shortcut Ctrl+O.
I disable SwitchyOmega and file open with Ctrl+O works fine.
SwitchyOmega version 2.3.19
Chrome version: 49.0.2623.112 m

Disabling the default shortcut and re-enabling the keyboard shortcut fixed the problem.

**Comment by FelisCatus** [comment]
This is definitely a Chrome problem which should be reported to the Chromium project. Please attach the crash report there.

SwitchyOmega has no control over shortcut key bindings not does it attempt to capture any keystrokes. It does provide a default key binding of `Shift+Alt+O`, but it shouldn't conflict with `Ctrl+O`. You can disable the shortcut or change to another one to work around the problem though.

**Comment by drazla** [comment]
Hi,

Thanks for your prompt response. I worked out that changing the key binding
worked around the issue so it's not a huge issue. I'll raise an issue on
Chromium when I have time.

cheers,
Darren
