### ISSUE TITLE
修改规则时反应过慢

### ISSUE THREAD

**Issue by taoist1994** [FelisCatus/SwitchyOmega#752]
因为在自动切换里添加了数千个网址，导致每次在选项卡里添加网站后，点击“应用选项”时都要等待很长时间。

**Comment by FelisCatus** [comment]
如果可以的话，请使用“编辑源代码”功能。也可以将规则拆分到多个自动切换中，每次只修改一个自动切换从而提高效率。

将自动切换规则整理出来成为规则列表、或者使用他人发布的规则列表也是提高性能的一种方式。

虽然卡可能是一个问题，不过我感觉这部分已经优化缓存很多了……接下来我也不知道怎么样才能提高性能了，所以暂时就只能这样了……

**Comment by celeron533** [comment]
有没有试过订阅gfwlist呢？这个list每日更新，有时候你会发现你上周手工添加的条目，今天就已经在pac里了
