### ISSUE TITLE
关键字匹配的BUG?

### ISSUE THREAD

**Issue by Fezreal** [FelisCatus/SwitchyOmega#753]
![image](https://cloud.githubusercontent.com/assets/6703674/14593838/2e147a6c-0562-11e6-9e0b-422abb752b8f.png)

为什么这条规则匹配不到
https://feedly.com/i/latest

求解。

**Comment by FelisCatus** [comment]
点击图中问号按钮可查看各规则的具体匹配方式。“关键字”规则的匹配方式类似于`http://*pattern*`，只在协议为 HTTP 时生效。

如果您希望匹配所有包含 feedly 的 URL ，那么应该使用 网址通配符规则，条件设置为 `*feedly*`。
