### ISSUE TITLE
启动Chrome浏览器时，浏览器部分访问不受代理规则影响

### ISSUE THREAD

**Issue by ZenFX** [FelisCatus/SwitchyOmega#754]
我用Proxifier软件查看，每次打开Chrome时，浏览器都会访问clients4.google.com， www.googleapis.com， ssl.gstatic.com这几个网址，即使将这些添加进Proxy SwitchyOmega扩展的规则中，好像不受影响，仍然走的是直连的通道。

**Comment by ZenFX** [comment]
正常的网页浏览是没有问题的，只是Chrome浏览器启动时后台访问的这些网址不受规则影响。

**Comment by ZenFX** [comment]
我又测试了一下，在使用系统代理或停用扩展使用Chrome启动命令行--proxy-server="socks5://127.0.0.1:1080"的情况下，启动Chrome无论前台后台所有网址走的都是代理；但在使用Proxy SwitchyOmega将情景模式设为同样的代理服务器时（非自动切换）时，前台浏览网页都是正常走代理，但Chrome后台访问的clients4.google.com， www.googleapis.com， ssl.gstatic.com这几个网址依然是直连。

**Comment by FelisCatus** [comment]
确实，从 Chrome 启动，到开始加载扩展，再到 SwitchyOmega 加载完毕并设置代理有一定的延迟。正常情况下这应该不会太影响使用（因为后台加载的几个网址一般都是更新等服务使用的，即使一次未能加载也会重试。）

不过我准备先关闭这个了，毕竟在 SwitchyOmega 加载之前也没什么办法直接改代理设置吧……
