### ISSUE TITLE
校园网/安卓 shadowsocks 无法使用

### ISSUE THREAD

**Issue by nikki70** [FelisCatus/SwitchyOmega#757]
系统是5.0.2
连接后，访问谷歌提示
DNS_PROBE_FINISHED_NO_INTERNET
刷新dsn缓存，依然不行，全局模式／分应用代理 都不行。
同ip ，端口 mac端可以正常使用。
用的是 python ss ，其他版本试过go，也不行。
要如何设置安卓手机 才能正常访问？

还有校园网，window／osx 都无法正常使用ss
检查提示：
检测如下：
[2016-04-20 01:57:21] System.Net.Sockets.SocketException (0x80004005): 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。
在 System.Net.Sockets.Socket.get_RemoteEndPoint()
在 Shadowsocks.Controller.TCPHandler.ConnectCallback(IAsyncResult ar)
————————————
校园网好像不支持ipv6
还是我vps设置问题， 用的是python一键安装ss。。
求指点 谢谢！

**Comment by johnhuo** [comment]
这个问题去隔壁问吧……不属于so的问题。
2016年4月20日 上午4:10，"nikki70" <notifications@github.com>写道：

**Comment by nikki70** [comment]
我发完也意识到了。。然后不会删除－ － 刚来这边 各种不会
