### ISSUE TITLE
dns不走代理了？

### ISSUE THREAD

**Issue by harbinbeer** [FelisCatus/SwitchyOmega#758]
最近的chrome版本里，规则中的网站dns好像不走代理了，从而导致很多无法访问。
证据是我用unbound做8.8.8.8的tcp代理dns的话可以访问，而默认情况下则不行。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36

**Comment by FelisCatus** [comment]
https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87

**Comment by SadPencil** [comment]
@FelisCatus wiki页面应该更新了，新版Chrome设置方法变了
新版Chrome设置如下：https://superuser.com/questions/394562/can-i-turn-off-google-chromes-new-prerendering
Firefox设置如下：https://support.mozilla.org/en-US/kb/firefox-cant-load-websites-other-browsers-can#w_dns-prefetching

**Comment by SadPencil** [comment]
@FelisCatus wiki页面应该更新了，新版Chrome设置方法变了
之前在设置里的选项的含义已经改变修改无效
只能从chrome://flags/里找到No-State Prefetch进行修改
发自Chrome 68
