### ISSUE TITLE
请问有没有类似国内路由表之类的pac文件？

### ISSUE THREAD

**Issue by pexcn** [FelisCatus/SwitchyOmega#760]
我想设置成国内直连，国外全部走代理

**Comment by FelisCatus** [comment]
PAC 是根据网址来匹配的，很难判定是在国内还是国外。所以即使去网上找，也不太可能找到这样的脚本。

对于国内、国外区分的情况，最好改用 VPN 服务。 VPN 服务较为底层，可以在 DNS 解析出结果后再配合基于 IP 归属地的路由表来使用，从而很好地实现此需求。 SO 并没有 VPN 设置功能，所以需要使用其他工具来设置。
