### ISSUE TITLE
Switch rules是不是有规则数量限制？

### ISSUE THREAD

**Issue by uuudbx** [FelisCatus/SwitchyOmega#761]
有些添加过的网站地址消失了，是不是有规则数量限制？是不是后面添加的规则把以前添加的挤出去了？

**Comment by FelisCatus** [comment]
并没有数量限制，也不会自动删除之前的规则。
不过如果规则太多的话，我个人建议拆分到几个自动切换中然后串联使用。这样方便管理，编辑的时候也不会因为规则太多而造成页面卡顿。
