### ISSUE TITLE
[feature] Connect-ibility check

### ISSUE THREAD

**Issue by xuefer** [FelisCatus/SwitchyOmega#762]
Virtual (link) profile is a feature I proposed long time ago and got implemented, it's really handy, cut me off the nightmare of switching proxy for each custom rule

using link feature it means the user have multiple proxy, want to switch because some slow or dead temporarily, so I think why not have a connect-ibility check feature? press it manually in the drop down list should it show how much fast or slow or dead for each proxy. we don't have to use a auto-switch-when-down yet

**Comment by FelisCatus** [comment]
Proxy fail-over is tracked by #578. It is possible to create a PAC script for proxy fail-over. See the issue comment for details.

Proxy availability check is tracked by #277.

**Comment by xuefer** [comment]
Thanks for pointing to relative issue, but i don't think they are identical in some cases. e.g.: i uses my proxy is over vpn, the proxy may not fail at all but become slow. i suppose the load balance or smart switch feature is smart enough to use the "faster" proxy like ed2k/torrent world picking good peer, at least not in a short term. manual speed test is however easier for example: https://proxybay.la/

**Comment by FelisCatus** [comment]
I'm afraid choosing proxies by connection speed is too complicated to automate in SwitchyOmega. Besides, updating proxy references requires changing the PAC file, slowing down the browser as well as requests.

These kind of features are better implemented on the protocol level. For example, one could build a proxy server that forward requests to upstream proxy servers based on speed and connectivity. Unlike extensions, protocol implementations have full control over the traffic and can adapt to changes and balance easily. They also have access to raw connection metrics which are critical for picking the right upstream.
