### ISSUE TITLE
auto detect settings

### ISSUE THREAD

**Issue by henkoventer** [FelisCatus/SwitchyOmega#763]
Hi, in IE you have the option to tick auto detect settings - this is only thing that works on some websites at work - how do i configure omega to do the same thing as selecting direct connect doesnt work

Thanks

**Comment by FelisCatus** [comment]
Try creating a PAC Profile with the URL `http://wpad/wpad.dat` and activate it from the menu.

If that doesn't work, just select `[System Proxy]` in SwitchyOmega and Chrome will try to pick up proxy settings from the environment (in your case IE proxy settings). Be aware that `[System Proxy]` is not available as a target in Auto Switch though, if you use this method.
