### ISSUE TITLE
在“编辑源代码”状态下切换编辑情景模式会丢失未保存的修改

### ISSUE THREAD

**Issue by xdujiang** [FelisCatus/SwitchyOmega#765]
在编辑页面点击左侧的自动切换模式，然后点击编辑源代码进行修改，如果此时点击左侧任意情景模式，之后再返回此自动切换模式，对其源代码做的修改都会丢失。

**Comment by FelisCatus** [comment]
啊哈哈……还真是这样……

暂时就小心点不要去碰啦，之后我会修掉的。

**Comment by FelisCatus** [comment]
代码已经更新，我会尽快发布一个新版本解决此问题。抱歉拖了这么久。

**Comment by xdujiang** [comment]
感谢修复~
都忘了提过这个issue了...

**Comment by FelisCatus** [comment]
v2.3.20 已经修复。

**Comment by xdujiang** [comment]
thanks~
不过菜单好像少了功能？现在好像不能手动指定当前网站的规则了啊

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。
