### ISSUE TITLE
“系统代理”模式可翻，“自动切换”模式不可，禁用其他扩展问题依旧，配置没有问题

### ISSUE THREAD

**Issue by free4537** [FelisCatus/SwitchyOmega#766]
如题，配置是导入的 https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList.bak  “情景模式”（规则列表）已更新。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.87 Safari/537.36

**Comment by FelisCatus** [comment]
我觉得像是 #557. 请阅读一下那边的说明，然后确认一下代理服务器配置。

**Comment by free4537** [comment]
@FelisCatus 果然，代理协议默认为 HTTP 就好了，多谢~

**Comment by free4537** [comment]
卸载了迅雷极速版，然后装了最新版的迅雷，代理协议默认为 SOCKS5 已可用。
