### ISSUE TITLE
点击浏览器右上角的omega图标，弹出的内容不可见

### ISSUE THREAD

**Issue by fanfank** [FelisCatus/SwitchyOmega#767]
我用的是Win10下的Chrome 49.0.2623.112 m (64-bit)，点击Omega的图标时弹出内容不可见，不过按钮实体是存在的。
我试过将弹出页面的body中的min-width:180px去掉就会正常显示

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by fanfank** [comment]
我发现了一个现象，我有两个显示器，一个是笔记本自己的小屏，一个是外接的27吋大屏。
当把Chrome拖拽到小屏并最大化，点击图标时能正常弹出的
当我把Chrome拖拽到小屏并最大化时，点击图标是不能正常弹出的

**Comment by FelisCatus** [comment]
这应该是 Chrome 的问题了，不是 min-width 的问题……好像是只要随便更新一下弹窗页面的大小，就会恢复正常显示。

另外关于您之后的补充……您是想说小屏幕正常还是大屏幕正常？您两句话说的都是“小屏”……

我的建议是换 Chrome Beta 甚至 Canary 试试看。

**Comment by FelisCatus** [comment]
现在还有问题吗？

**Comment by sqzr** [comment]
同win10 也遇到这问题了 。 是chrome的问题。。  换chrome beta 也没解决

**Comment by fanfank** [comment]
@FelisCatus 最近用的比较少，之前是哪个屏幕不行就拖到另外一个屏幕去点。最近的还没用新版的试过

**Comment by FelisCatus** [comment]
这个问题还有吗？感觉 Chrome 也更新了好几个版本了，应该修掉了吧……
