### ISSUE TITLE
Proxy SwitchySharp 升级成 Proxy SwitchyOmega 无法使用

### ISSUE THREAD

**Issue by ilushtu** [FelisCatus/SwitchyOmega#768]
Proxy SwitchySharp  配合 shadowscoks 使用正常。升级成 Proxy SwitchyOmega 就无法使用。而且 Proxy SwitchyOmega 的图标是浅颜色的，感觉没有启动成功的样子，如下图
![1111](https://cloud.githubusercontent.com/assets/18714370/14877518/41a99198-0d50-11e6-853f-11995c4418ee.JPG)

**Comment by FelisCatus** [comment]
SwitchyOmega 的图标本来就是浅色的。如果鼠标悬停在图标上显示的不是 Loading... 或者 加载中 ，那就是已经启动成功了。

“无法使用”具体指的是什么？如果是 Chrome 错误界面显示无法连接到代理服务器之类的话，那么基本可以肯定是设置问题。见下。

然后……请分别截图两个扩展中设置代理服务器地址、协议和端口的界面。一般地址都是`127.0.0.1`，不存在隐私问题。如果不是的话请随意修改下地址再截图来保护您的隐私。

关于 SOCKS 协议使用，可能会受到其他程序干扰从而失效，也请参考 #557 的讨论。

**Comment by kang000feng** [comment]
@FelisCatus 请问chrome +SwitchyOmega 播放视频，经常断流，F12开发者工具network里看到请求的视频数据status总是被 canceled，该如何排查解决？谢谢！代理服务器低延迟高带宽.

**Comment by FelisCatus** [comment]
@kang000feng 这是一个明显的网络请求层面的问题，与 SwitchyOmega 无关。 SwitchyOmega 只负责告诉浏览器什么地址走什么代理，不负责代理协议和网络连接。

如果需要询问其他话题，请另外开 Issue 询问，不要在无关话题中回复。

**Comment by FelisCatus** [comment]
太久没回复了，先关闭这个了。
