### ISSUE TITLE
经常动不动就卡死

### ISSUE THREAD

**Issue by chchuj** [FelisCatus/SwitchyOmega#770]
最新版的chrome和最新版的SO
重装问题依旧，决定暂时停用

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36

**Comment by FelisCatus** [comment]
能问问怎么卡死的么……

* 具体来说，是在选项页面上页面卡死？是在进行什么操作的时候？
* 还是在菜单中选择情景模式的时候反应比较慢？
* 还是访问网页的时候左侧显示正在解析代理……之类的？
* 还是访问网页的加载速度慢？（这不是SO的问题）
* 或者是访问的网页卡死？（这显然是网页的问题）

如果是前三条，建议说明一下是否使用了规则列表，以及有多少自定义规则等情况。
选项的导入/导出页面可以导出设置备份文件，可以上传到这里以便分析问题。如果这个功能也卡死了，那我就真没办法了。

**Comment by chchuj** [comment]
1/各种操作都有吧，多是在新开标签页的时候
2、对SO进行设置的操作时没有问题
3、是有提示在解析之类的，所以我才发现是SO的问题
4、有网速好和坏的环境都会出现
5、访问各种页面都有，有时新开一个标签也有。

手动设置和使用https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList.bak 都 会出现
最近更新了WIN10家庭版中文1511 之后才有的问题，不知道哪里不兼容

**Comment by FelisCatus** [comment]
崩溃的话绝对是 Chrome 的问题。

之前好像遇到过一个 Chrome 关于 PAC 文件解析的 bug 好像会导致崩溃，不过那已经是很久以前的事情了，而且仅限 OS X 平台。

我猜想这次还是和 PAC 文件解析有关。 SwitchySharp 和 SwitchyOmega 都涉及 PAC 生成和加载的技术，这个理论上来说在初次加载时可能会有轻微卡顿，之后网络请求时不应该出现任何延迟。猜想您的情况是面临内存压力/CPU压力的时候出现的，Chrome 运行 PAC 的那个线程（或者多个线程）会有明显的延迟。要不然也可能是进程间通信被阻塞。

请注意整个系统都卡住的情况很可能是有软件/恶意软件/病毒等占用过多 CPU/内存/磁盘 资源导致的，建议检查一下这方面情况。有条件的话也可以用其他设备、相同配置试试看，虽然这没有办法解决您的问题，但可能有助于排查是否是 SO 故障。

因为 SwitchyOmega 没有做到那么底层，所以我准备关闭这个了。我个人建议降级 Chrome 到版本 49 之类的再测试一下，如果还有问题的话可以升级到 Chrome Beta 试试看。

**Comment by celeron533** [comment]
有些操作系统与SSD也会产生奇怪的读写问题造成系统卡顿。都很难说。

**Comment by cicku** [comment]
I met this today, Chrome took at least 10 minutes to startup and then loaded webpage for 5 minutes. But it's waiting for ABP, not SO. Hence I believe there is a bug inside Chrome.

**Comment by FelisCatus** [comment]
But ABP is not using proxy API or PAC scripts... What could be the potential cause of delay that is common between SO and ABP? Could it be the V8 engine de-optimizing some string processing related code and thus affecting both extensions?

**Comment by godvmxi** [comment]
I met many times ,so I have to swtich to pac mode ,the whole system is blocked  ,in windows10 and linux mint 18

**Comment by guojian0624** [comment]
我也碰到这个问题了，整个系统卡滞。后来一个个插件禁用，最后发现是switchyomega。
Chrome 52.0.2743 64bit
