### ISSUE TITLE
Different proxies for different chrome instances

### ISSUE THREAD

**Issue by Hickory420** [FelisCatus/SwitchyOmega#771]
Hello,

At the moment, if I have two or three instances of Google Chrome open and I change my proxy, it changes for all instances I have open.
Would it be possible to only have the proxy change for the instance I've changed it on and not change the other instances?

I ask because sometimes I need to use different proxies at the same time, so when I change it for one instance of Google Chrome, I can't have it changing for the others, because that starts to cause headache for me.

Hope I made sense. 
Please advise.

Cheers,
Chris

**Comment by FelisCatus** [comment]
If you mean "windows" when you say "instances", then sorry, it is not possible to implement that.

But if you are using incognito mode, different Chrome users or different profile directories (sometimes called "instances"), each of those has its own settings and therefore can be separately configured.

Please see the following comment for your options on this. Please ignore the "tab based" part (which is also technically impossible FYI) if you are not interested in that.
https://github.com/FelisCatus/SwitchyOmega/issues/732#issuecomment-202246738

**Comment by LusciousPear** [comment]
@FelisCatus Does this mean I can have one proxy per incognito window, even 20? Or does it mean all the 'main' windows have one proxy, and all the 'incognito' ones share another?

**Comment by FelisCatus** [comment]
@LusciousPear Unfortunately, it's the second case. Please try different Chrome users if you want more.

**Comment by LusciousPear** [comment]
@FelisCatus That's not so bad, I just need to generate users, and specify which user loads for which incognito window? (Thanks for your help!)
