### ISSUE TITLE
是不是与chrome 不兼容？

### ISSUE THREAD

**Issue by cuibty** [FelisCatus/SwitchyOmega#772]
chrome 使用 50.0.2661.94 m (64-bit)

突然就没法使用了，ss代理正常

**Comment by celeron533** [comment]
参考 #557

**Comment by FelisCatus** [comment]
“突然就没法使用了”具体是说什么？请尽量说得详细一点。
“ss代理正常”是指什么正常？用其他浏览器能访问代理服务器之类的？

**Comment by cuibty** [comment]
ss代理正常指：选择SwitchyOmega 的模式为系统代理可以正常访问google等网站。

**Comment by FelisCatus** [comment]
应该是 #557 了吧……请先看看那边的说明。
