### ISSUE TITLE
Raw URL - Switching issue

### ISSUE THREAD

**Issue by tjukoela** [FelisCatus/SwitchyOmega#774]
Hi,

I want to switch to proxy with a specific URL like : 

/home/john/.wine/drive_c/Program%20Files%20(x86)/MyGame2/MyGame.html

but whatever I change to host wildcard or url wildcard or url regex the switcher proxy doesnt work.

And another question : is it possible to use multiple proxies for different target ? like : 
/home/john/.wine/drive_c/Program%20Files%20(x86)/MyGame2/MyGame.html for proxy 1
/home/john/.wine/drive_c/Program%20Files%20(x86)/MyGame2/MyGame1.html for proxy 2
/home/john/.wine/drive_c/Program%20Files%20(x86)/MyGame2/MyGame2.html for proxy 3
etc ... , is it possible ?

Could you help me plz ?

thx

**Comment by FelisCatus** [comment]
File URLs are never sent through the network and SwitchyOmega won't handle them. If you are more interested in the web requests initiated by these HTML files, please use the Chrome Developer Tools to locate them. Then you can add those requests to switch profiles.

**Comment by celeron533** [comment]
Or create a http server then use http://localhost/MyGame2/MyGame.html
