### ISSUE TITLE
Http Proxy Bug

### ISSUE THREAD

**Issue by miemiekurisu** [FelisCatus/SwitchyOmega#775]
switchOmega  2.3.19
设置 http proxy, 如果保持在http proxy状态下关闭chrome, 则再次启动chrome时无法连接到proxy.
切换为direct/system proxy, 再切换回http proxy后正常.
同时 Proxy SwitchySharp 没有此bug...

更新: 服务器端为polipo的时候有此bug, gost无此bug

**Comment by FelisCatus** [comment]
我感觉应该先检查有没有冲突的扩展……冲突的扩展一般是其他代理设置扩展、使用PAC脚本的去广告扩展等。如果两个扩展同时设置了代理设置，新安装的扩展覆盖后安装的扩展。因此，也可以试着重装 SwitchyOmega 看问题是否还会发生。

另外一个思路是，在代理正常工作的时候打开`chrome://net-internals/#proxy`，复制页面上显示的内容。然后复现代理无法连接的问题，再打开`chrome://net-internals/#proxy`，然后对比两次的内容是否不同。如果不介意的话请把两次的内容都粘贴到这里以便分析问题（请注意修改/遮盖IP和端口来保护您的隐私）。

我自己用的时候一般用的是 SOCKS5 代理，不过我也用 Polipo 测试过很多次，没有发现类似的问题……不过按理应该所有服务器都一样的吧…… SO 只是设置代理设置，又不做协议层……一个服务器能复现另一个不能是要闹哪样……

**Comment by miemiekurisu** [comment]
我没有时间抓包分析, 目测gost没问题=w=, 于是我就换了gost...
估计是协议报头有区别...之类的...

**Comment by celeron533** [comment]
前置代理使用privoxy试试吧
（SS以前用的是polipo，近期已经换成了privoxy）

**Comment by FelisCatus** [comment]
由于 SwitchyOmega 并不实现任何代理协议，也不发送数据包/报文，所以……这边就暂时不管了……
至于抓包……就算给我看抓包的结果也没什么帮助的……

如果有时间研究的话，还是建议调查`chrome://net-internals/#proxy`页面，因为那个页面是 SwitchyOmega 唯一能影响的。即使没发现什么特别的，也能至少排除 SwitchyOmega 这个因素。

**Comment by miemiekurisu** [comment]
嘛...其实我已经用排除法确认90%不是SwitchyOmega的问题, 可能是某些代理软件的协议实现不标准, 目前看也就是 linux和mac版的polipo有这个问题
