### ISSUE TITLE
Auto Switch not support system proxy profile

### ISSUE THREAD

**Issue by youyou015** [FelisCatus/SwitchyOmega#776]
Now in Auto Switch config page, only can select [Direct] and my own created profiles, could you add [System proxy] selection?
Thanks.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by FelisCatus** [comment]
See #289
