### ISSUE TITLE
如何支持pptp,l2tp协议的vpn

### ISSUE THREAD

**Issue by geekerzhou** [FelisCatus/SwitchyOmega#782]
如题，购买的vpn支持pptp，l2tp,openvpn协议，但是switchomega不支持，有没有类似shadowsocks的支持用户名密码登录的转sock5的软件

**Comment by celeron533** [comment]
switchOmega只是一款会话层的代理服务器切换软件，VPN协议太底层，两者完全不是同一个概念。

**Comment by FelisCatus** [comment]
Thanks, @celeron533 ! :+1:
