### ISSUE TITLE
提示有由于网络原因而未加载的资源数量  但是我添加规则后 无法保存规则

### ISSUE THREAD

**Issue by skykiahs** [FelisCatus/SwitchyOmega#783]
提示有由于网络原因而未加载的资源数量  但是我添加规则后 无法保存规则  请修正.

**Comment by FelisCatus** [comment]
请问“无法保存”是指什么情况？是打开选项后并没有看到新添加的规则吗？还是无法点击“添加规则”按钮？还是添加规则后重启浏览器即消失？

此外，添加的方式是？是点击菜单，在菜单中选择“未加载资源”，然后统一添加规则吗？还是？

请适当详细说明，必要时请截图。

**Comment by FelisCatus** [comment]
因为缺少必要信息，暂时关闭了。如有问题请评论并重新开启。
