### ISSUE TITLE
希望在“加载失败的资源列表”中给出失败的类型

### ISSUE THREAD

**Issue by ikidou** [FelisCatus/SwitchyOmega#784]
「加载失败的资源列表」中虽然会给出是哪个域名下的资源出了问题，但我们并不知道是不是由于页面错误造成的还是由于墙造成的，所以希望给出加载失败的类型 或 将被墙的部分单独列出 或 可以直接在后面设置临时其使用的方式

SwitchyOmega 2.3.19
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36

**Comment by FelisCatus** [comment]
页面错误本身并不会造成未加载资源。同理，加载出现 404, 500 等请求成功但返回是错误代码的情况也不会记录在内。

所谓未加载资源，一定是因为网络原因而加载失败或加载缓慢的资源。具体的判定请参考代码以及 Chrome 的请求失败错误代码（比如 `ERR: Connection Reset`）。正如扩展中的描述，网络不稳定、网络中间节点（如某墙）或不稳定的代理服务器、对方服务器问题均有可能造成同样的结果。由于 SwitchyOmega 并没有任何其他的信息有助于进一步判定，所以不会给出失败的类型。当然，总是可以把每个请求的详细情况尤其是错误代码丢给用户的，然而大部分情况即使看了错误代码，也无助于缩小和定位问题。（毕竟网络、中间节点、对方服务器中的任何一个都可以导致这些错误代码……）

如果希望对错误的原因得出更细致的分析，甚至通过一定的规则或智能学习等方式判定某墙的干扰，请参考 [COW](https://github.com/cyfdecyf/cow) 项目等更底层的实现方式。 SO 本身作为一款代理设置软件，做不到、也不想做那么多。最后， SO 不是翻墙软件，更不是网络分析软件。
