### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by guoqiyi** [FelisCatus/SwitchyOmega#785]
使用的自动切换模式，当使用时间长了，自行添加的网址过多时，导致每次打开页面时，插件检查网址规则时导致内存使用飙升至满格(电脑内存也不算大，4G)，使archlinux的Chromium浏览器卡死，表现为桌面假死，硬盘灯狂闪，电脑温度急速升高，风扇狂转，而后自动强制退出或是强制重启，此种情况下，该怎样减少插件的内存使用呢？以下几种方式哪个最有效？
1.自己维护一个类似于gfwlist的列表，添加自己需要代理的网址
2.把所有添加的网址改写成pac文件再引用
3.使用正则式表达，把类似facebook.com和facebook.net、fbcdn.com这样的同一网站的域名合并成一个f(|ace)b(|ook)(|cdn)\.(com|net).*正则
请问以上几种方式哪个最有效可以解决网址添加过多导致的内存占用过高的问题？或是还有其他更好的解决方式？

SwitchyOmega 2.3.19
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36

**Comment by FelisCatus** [comment]
我的建议是先按 Shift+Esc 查看内存占用，确定一下 SO 本身占用的内存较多还是 Browser 一项较多。
如果是 SO 占了比较多资源的话，使用 PAC 文件无疑更有效，因为 SO 本身不会去执行 PAC 中的任何代码，可能可以获得不错的性能提升，但图标改变颜色的功能自然也就没有了。此外，也可以试试看禁用网络请求检测功能，然后重启浏览器，还能再提高一点点性能。

如果是 Browser 占用了太多资源的话，估计只能从内存占用本身来下手了。禁用一些占用内存比较多的扩展，少开几个标签页，升级 Chromium。每次打开新页面自然都会卡，内存占用当然也会上升， Chromium 本身就这样的，在非 Windows 环境下尤其是内存占用多且容易内存泄漏，还真未必是“插件检查网址规则”的问题。

我也建议换带有内存压缩功能的内核等。我用的也是 Arch Linux ，至于卡的话……习惯就好了。

**Comment by FelisCatus** [comment]
如果 Shift+Esc 中显示的确实是 SO 占用了大量内存，那么有可能改进。如果想要帮忙的话，请给出 Shift+Esc 中显示的  SO 内存占用大小，以及 SO 后台页面的一份 Heap Snapshot 文件. 要导出这个文件需要在扩展管理页面勾选开发者模式，然后再点击 Proxy SwitchyOmega 下的 background.html ，在选中 Profiles 标签选中 Take Heap Snapshot 并点击按钮，最后将截获的结果导出。
