### ISSUE TITLE
In Chromium, when omega proxy is enabled, clicking "Sign in to Chromium" crashes Chromium

### ISSUE THREAD

**Issue by dansteen** [FelisCatus/SwitchyOmega#787]
When using Chromium for both the Mac and Windows, signing in via the profile button on the top left corner of the window results in a crash.  When I disable Omega Proxy things work fine.  This is true regardless of whether I have authenticated with the proxy prior to attempting to sign-in or not.

Chromium versions:
Windows - 50.0.2657.0
Mac - 51.0.2704.63  ( though I have tried with a 52 version as well)

Thanks!

**Comment by dansteen** [comment]
Looks like the solution is that I have to log in to the proxy prior to attempting to sign-in.  Definitely don't want a crash though...

**Comment by FelisCatus** [comment]
The crash is definitely Chromium's fault and should be reported to the chromium project. I suppose that is somehow related to the interaction with the profile menu and the proxy authentication popup window.

If your proxy requires username and password authentication, you can try to put the username and password in SwitchyOmega. That can be easily done by clicking the padlock icon beside Server and Port. If the credentials are correct, the proxy authentication popup window can be avoided altogether, which could possibly work around the issue.
