### ISSUE TITLE
导致chrome不时卡死

### ISSUE THREAD

**Issue by luoni2002** [FelisCatus/SwitchyOmega#788]
好像这个占用资源比较大还是，不时到底chrome卡死，内存使用率瞬间达到99%，我4G内存

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by FelisCatus** [comment]
分析内存占用的一些方式以及解决方案见 #785.
