### ISSUE TITLE
默认情境模式如果也是代理的话，打开网页偏慢

### ISSUE THREAD

**Issue by drice82** [FelisCatus/SwitchyOmega#789]
实际应用环境是公司有一道防火墙，天朝有一个GFW。
设置为：

1)默认情境模式：代理A，连接到建立在家中服务器的shadowsocks，翻越公司防火墙，目的是访问国内网站速度快；
2)规则列表规则：代理B，连接到国外VPS上的shadowsocks，翻越GFW，访问google等。

实际使用中，访问国内站点速度慢，小圆点要过几秒才变色，似乎是没有默认使用“代理A”而是过了一会儿才切换到“代理A”。

**Comment by FelisCatus** [comment]
图标的变色功能是一个辅助功能，是另外进行的判断，只是便于用户直观地感受页面使用了何种情景模式，那个图标颜色变化的过程没什么太大的意义，最多只能反映网络延迟而已。真的“切换”功能是由 PAC 实现，不存在“过一会才能切换”的情况，而是在菜单中选中情景模式之后的很短一段时间内就会生效的。

因为这种情况真的很难定位具体哪里卡，所以我也只能简单说说了……先用全局代理A尝试一下访问各种国内网站，测试下速度，确保不是单纯的网络本身卡……用代理总是会有点延迟的，可能来源于线路问题、带宽限制或者代理协议本身的开销（数据加密和封装）。 speedtest.net 等网站可以用于测速，记得选国内的节点。全局代理A测速后再换自动切换模式再测速。有些运营商喜欢限制上传带宽，这种事情只要测速自然就可以知道了。

如果想要更详细地了解请求中的各个环节耗时，可以打开 `chrome://net-internals/#events` 然后再开个网站，就可以看到请求的具体记录了。每条都有时间，可以仔细看看延迟在哪个环节。使用代理可能会禁用 DNS 预加载，或者使一些基于 DNS 的 CDN 返回较慢的 IP 地址（常见于本机是电信，代理服务器是网通之类的情况），这一点也应该考虑到。当然，代理服务器和缓存什么的也有关系。
