### ISSUE TITLE
情景無限還原"proxy與auto switch"(初始化)..

### ISSUE THREAD

**Issue by immrdodo** [FelisCatus/SwitchyOmega#790]
如題,是個別問題還是普遍存在??有解決方法嗎?:`(

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by FelisCatus** [comment]
抱歉，请问您说的是什么意思？您进行了什么操作，然后发生了什么？能具体说一下吗？或者也可以描述一下本来应该怎么样，实际上怎么样之类的。

我看了一会“無限還原”，不知道是什么意思……然后又看了一会“初始化”……好像与扩展加载有关？最后又看了 "proxy與auto switch" ，当然最后一句我倒是看懂了，不过实在是没有办法和前面说的联系起来……请原谅我的想像力匮乏……

**Comment by immrdodo** [comment]
**針對更新內容這一點:**
·修复了自动切换教程中的滚动问题，现在教程更友好了。 此外，也修复了教程**反复**显示的问题。

**具體情況**是教程沒有反復顯示,但是選項一直沒辦法保存,只要Chrome重啟,所有選項就會"初始化"(跟剛安裝擴展時一樣,默認情景"proxy與auto switch",自行添加的情景沒有了,如果進行同步,情景會從服務器下載)..

至於我所進行的操作,應該是沒有,就算我把Chrome徹底刪除,重新安裝,問題都存在:(

好像很難描述,難道要錄像給你嗎=..=

**Comment by FelisCatus** [comment]
我知道您说的是什么状况了，感谢您的解释。顺便一说，这个问题应该是和最近的更新没有直接关联。

为了测试这个问题，首先请您到导入/导出界面中禁用同步功能，并清除云端的数据，然后重启浏览器。然后随便修改点什么，再重启浏览器，看是否还存在选项重置的问题。

如果选项重置了，那么可以排除是同步功能所导致的了。此时请立即右键点击扩展图标，并点击“导出错误日志”，并将错误日志上传到这里，以便分析问题。

**Comment by immrdodo** [comment]
感謝你的耐心...

首先禁用了同步功能,也清除了雲端數據,根據你提供的步驟,選項**仍然重置**...

日誌:
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "auto switch",
        "direct",
        "proxy"
    ]
]
Options << Options#updateProfile []

**Comment by FelisCatus** [comment]
首先，请确定日志是在进行过一定的修改，然后重启浏览器之后导出的。不要直接导出日志，也不要重启两次以上后再导出日志。

此外，我猜想有软件在清空扩展的设置。请检查一下系统垃圾清除工具之类的。之前有人反馈过 CCleaner 会错误地清空扩展数据。

**Comment by FelisCatus** [comment]
顺便，可以检查一下 Chrome 用户资料目录下 Default 文件夹(或者 Profile 1 等文件夹，如果用了多用户功能的话)下的 `Local\ Extension\ Settings/padekgcemlokbadohgkifijomclgjgif/` 里面的`.log`文件。这个文件里存储了扩展选项，很可能是必须的文件之一。但因为后缀名是 `.log`，可能容易被各种软件误删。

可以用各种工具监视这个目录下文件的修改，也可以手动打开 log 文件来看。（例如在刚启动 Chrome 时看一次，修改一些选项然后保存的时候看一次，静置一段时间后看一次，关闭 Chrome 后看一次，重启 Chrome 配置丢了再检查一下之类的。）

**Comment by immrdodo** [comment]
好的,確實是該死的CCleaner..雖然只選擇了刪除歷史和下載位置..

感謝你
