### ISSUE TITLE
Load list of proxies from file

### ISSUE THREAD

**Issue by slavafomin** [FelisCatus/SwitchyOmega#792]
Hello!

Thank you for this great extension!

However, is it possible to load list of proxies from file with IPs, ports, and auth credentials (~1000 lines) and pick random proxy from the list on demand?

Thanks!

**Comment by FelisCatus** [comment]
SwitchyOmega isn't designed to handle thousands of profiles so one profile for each proxy won't work well. However, you can write a PAC script that selects a random one from a proxy list
(like [this one](https://gist.github.com/teslatronic/4222759e2cacfdb00a48)) and paste it into a PAC Profile created in SwitchyOmega.

Configuring authentication for each proxy isn't possible now unless all of them share the same username and password pair. In that case, that pair of credentials can be entered in PAC Profile configuration.

----

For advanced use cases, it is recommended to run a personal proxy server that forwards your request to upstream proxies. In that case, you can simply point SwitchyOmega to your personal proxy server. Squid, for example, can be configured to use multiple upstream proxies, each with its own credentials. The following configuration fragment shows a possible use case:

```
cache_peer proxy1.example.com parent 8081 round-robin no-query login=user1:password1
cache_peer proxy2.example.com parent 8082 round-robin no-query login=user2:password2
```

You don't have to own and maintain a dedicated server for that. Running Squid or other proxy servers on the same laptop you are using for browsing purposes is totally fine as long as you configure it to start automatically with your operating system. If you do so, you can instruct SwitchyOmega to connect to server `127.0.0.1` (localhost) on port `3128` (if Squid is listening on the default port). You may also want to restrict the listening address of your personal proxy server to `127.0.0.1` to prevent external access.

**Comment by slavafomin** [comment]
Thank you @FelisCatus for a comprehensive answer! Nice idea about a forwarding proxy, I will look into it. Cheers!
