### ISSUE TITLE
添加当前网页规则只能添加当前域名

### ISSUE THREAD

**Issue by imis12** [FelisCatus/SwitchyOmega#793]
但是实际上网内容有其他域名链接的资源，这些域名无法用菜单下的“添加条件”设置代理
可以参考IPvfoo https://github.com/pmarks-net/ipvfoo 抓取所有域名。

**Comment by FelisCatus** [comment]
我建议使用未加载的资源功能（需要在选项中开启网络请求监测）来批量添加这些域名。这个功能可以应对页面中有图片/脚本/视频/其他资源无法加载的绝大多数情况。

如果需要更复杂的功能，建议使用 Chrome 开发者工具的网络请求功能。
