### ISSUE TITLE
How to set proxy timeout in a PAC file ?

### ISSUE THREAD

**Issue by hillz1** [FelisCatus/SwitchyOmega#794]
Hi, 

So I set up a proxy failover with a pac file:

```
function FindProxyForURL(url, host) {
return "SOCKS5 127.0.0.1:1080; SOCKS5 127.0.0.1:1081; SOCKS5 127.0.0.1:1082; SOCKS5 192.168.1.1:1080; SOCKS5 192.168.1.1:1081";
}
```

Sometimes it takes a long time to load a website so I want to set `proxy timeout` for 5 seconds, if it's been 5 seconds and it's still loading a URL then switch to another proxy listed in the script, how can I do that ?

I'm using Google Chrome anyway

**Comment by FelisCatus** [comment]
This feature is not available in PAC scripts and thus cannot be done by SwitchyOmega.

If you need custom proxy fail-over strategies or timeout, you can try to run your own proxy server which delegates requests to upstream proxies. Squid could be a good choice.
