### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by kongxiaojing** [FelisCatus/SwitchyOmega#795]
不能使用

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36

**Comment by kongxiaojing** [comment]
用不了

**Comment by FelisCatus** [comment]
您好，如果不知道如何设置可以参考[教程](https://github.com/FelisCatus/SwitchyOmega/wiki/GFWList)，如果是页面无法加载请先检查代理和网络原因。

如果您确信是 SwitchyOmega 的问题，请说明您想要做什么，尝试了哪些步骤，最终结果如何，与您想要的结果有什么不同。只是说“不能使用”或者“用不了”的话其他人无法帮助您解决任何问题。
