### ISSUE TITLE
视频数据总是被 canceled

### ISSUE THREAD

**Issue by kang000feng** [FelisCatus/SwitchyOmega#796]
@FelisCatus 请问chrome +SwitchyOmega 播放视频，经常断流，F12开发者工具network里看到在请求的视频数据的status被 canceled，请问该如何排查解决？谢谢！代理服务器低延迟高带宽没有丢包.

**Comment by kang000feng** [comment]
出现canceled 的可能原因有哪些呢？

**Comment by FelisCatus** [comment]
这是一个明显的网络请求层面的问题，与 SwitchyOmega 无关。 SwitchyOmega 只负责告诉浏览器什么地址走什么代理，不负责代理协议和网络连接。

我不是网络方面专家，也不了解 Chrome 的网络请求处理方式。
