### ISSUE TITLE
V8 代理解析工具 占用CPU

### ISSUE THREAD

**Issue by Bpazy** [FelisCatus/SwitchyOmega#797]
V8 代理解析工具，占用CPU，导致chrome打开的所有网页无限加载，Shift+Esc结束掉进程，等进程重启之后才可以正常用。
把模式改成`直接连接`没有这个问题

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by xjkdev** [comment]
同样有这个问题
Chrome 51 \ 52beta 都出现这个问题。

SwitchyOmega 2.3.19 windows 10

**Comment by celeron533** [comment]
我的环境和 @Bpazy 的完全一样，目前没有遇到过这样的问题。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

究竟是和其他扩展冲突了，还是由于SO自身升级导致自动切换格式/应用发生了变化

**Comment by Bpazy** [comment]
```
我的环境和 @Bpazy 的完全一样，目前没有遇到过这样的问题。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

究竟是和其他扩展冲突了，还是由于SO自身升级导致自动切换格式/应用发生了变化
```

换了固态硬盘于是重装了系统，chrome目前只有三个插件：
`SwitchOmega`，`EditThisCookie` ，`滴答清单 - Todo & 任务提醒`
目前未出现之前反映的问题，之前还有一个翻译插件，一个视频下载的插件，一个广告过滤插件

**Comment by celeron533** [comment]
> 目前未出现之前反映的问题，之前还有一个翻译插件，一个视频下载的插件，一个广告过滤插件
有的广告过滤插件为了达到最好效果，会搞一个本地代理绕一圈。另外你也可以关注一下那些“隐形”扩展，比如支付宝安全认证之类的

**Comment by xjkdev** [comment]
清空autoproxy网址及数据之后 目前没有出现这个问题。

**Comment by FelisCatus** [comment]
请选择自动切换模式，然后确定下是否存在占用大量资源的问题。如果是的话，请到选项中自动切换模式中，点击导出 PAC 文件，然后上传到这里以供分析。

另外，请确认一下占资源的是 Chrome 本身的进程(PAC 解析进程)还是 SwitchyOmega 后台进程。如果不能确定的话不妨将导出的 PAC 文件直接用作 PAC 情景模式，然后试试看是否还是占用大量资源。

**Comment by FelisCatus** [comment]
2.3.19 更新就是修正了一下翻译错误…… 2.3.18 倒是有不少更改，我也顺便检查一下……

**Comment by FelisCatus** [comment]
5090ebf3234352020e70766367ac2e21f1ff1785 改了标签页中的图标悬停提示，可能会比原先性能降低一点，但应该不能占 CPU 到 100%， 还是要看到底是那个进程才可以判断。 63938d0e158dfd5462f5432a2deb751c5e00e8c2 和 482c6f634074ace9b66c1be22b089b08fc041774 新加了时间条件， PAC 生成相关，但既然没有用新条件的话应该也不影响。

**Comment by Bpazy** [comment]
环境不变，重装一次系统后问题竟然没有了，插件也和以前完全一样

**Comment by celeron533** [comment]
难道说之前的win10是从老系统升级上来的？有时候老系统直接升级会留下也奇奇怪怪的问题

**Comment by FelisCatus** [comment]
那我只好先关闭这个了……真心觉得是 V8 引擎的问题……

**Comment by xlfjn** [comment]
印象中很早以前就遇到过这个问题了。
系统是Arch Linux i686，使用的是Chromium，打开了chrome://flags/#v8-pac-mojo-out-of-process
有时开网页时内存占用率突然特别高，按Shift+Esc发现是V8代理解析工具，把它杀掉就好了。

上次重装之前，Windows 10下Chrome会经常导致整个系统卡死，硬盘灯狂闪，过个几分钟就恢复了，估计是内存被占满吧。

**Comment by FelisCatus** [comment]
见 #815 ，建议关闭`chrome://flags/#v8-pac-mojo-out-of-process`。

**Comment by cnfree0355** [comment]
看来不是我一个人遇到啊，印象是从chrome 50升级之后就会出现内存严重泄露，然后卡死十】几分钟，只有强制重启，为此还重装了系统

**Comment by huohu4399** [comment]
我的是占用内存   慢慢整个系统卡死  太蛋疼了    升级了chrome 53   重新配置了代理  暂时消停了   这个内存泄漏 真恶心

**Comment by mydansun** [comment]
现在还是经常遇到验证内存泄漏的问题，windows日志如下

> Windows 成功诊断出虚拟内存不足的情况。以下程序使用了大部分虚拟内存: chrome.exe (10944) 使用了 226308096 字节；chrome.exe (15920) 使用了 208736256 字节；MsMpEng.exe (2348) 使用了 204484608 字节。

**Comment by DRL25** [comment]
发现是这个进程在后台更新Chrome最新版本导致CPU占用99%
