### ISSUE TITLE
一直显示这个错误,无法隐藏

### ISSUE THREAD

**Issue by kirito269** [FelisCatus/SwitchyOmega#798]
![Uploading image.png…]()

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by kirito269** [comment]
![image](https://cloud.githubusercontent.com/assets/10243794/15989228/17535358-30a4-11e6-8e46-5f75a229f4f8.png)

**Comment by kirito269** [comment]
[OmegaLog_1465711012262.txt](https://github.com/FelisCatus/SwitchyOmega/files/310663/OmegaLog_1465711012262.txt)

**Comment by celeron533** [comment]
#678

**Comment by kirito269** [comment]
解决完毕 感谢
