### ISSUE TITLE
Chrome 53.0.2763.0 dev-m (64-bit) not work good

### ISSUE THREAD

**Issue by Comup-X** [FelisCatus/SwitchyOmega#799]
but switchysharp works good

**Comment by FelisCatus** [comment]
Please provide additional details instead of "not work good".

**Comment by johnhuo** [comment]
You should submit this issue to Google chrome project team.
2016年6月15日 上午11:39，"Felis Catus" <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
I'm closing this because this does not include any useful information. It is likely that the OP is reporting something related to #815. If so, please subscribe/reply to that issue instead.
