### ISSUE TITLE
还是有内存泄漏问题，用着用着内存就到100%了

### ISSUE THREAD

**Issue by Peter-cao** [FelisCatus/SwitchyOmega#800]
SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by celeron533** [comment]
确认真的是SO占用了这么多内存吗？

![2016-06-13 12_53_17-](https://cloud.githubusercontent.com/assets/3608762/15997388/dbca18cc-3165-11e6-9d7b-f594cf5dc8ce.png)

![2016-06-13 12_52_07-task manager](https://cloud.githubusercontent.com/assets/3608762/15997377/b929cf88-3165-11e6-84e7-ed8f6e7e07e3.png)

**Comment by xjkdev** [comment]
应该是和issue #797 相同的问题 SwitchyOmega 2.3.19 自动更新后就一直出现。
只有自动切换模式有这个问题，PAC、直接连接、全局代理都没有这个问题。
降级到2.3.17也无此问题，请检查近期commit。

**Comment by FelisCatus** [comment]
在 #797 统一讨论吧。

**Comment by celeron533** [comment]
今天到新公司,安装完最近版本的Chrome53后,内存炸了...
有一个svchost.exe内存占用以肉眼可见速度飙升

1. 禁用SO,无效
2. 删除SO,无效
3. 重启,无效
4. 杀掉这个进程后,2分钟会重生
5. 卸掉chrome后居然还有

最后大杀器,删除两个遗留的chrome update相关的服务以及两个task schedule后, 一切回归正常。难道说是更新程序也会调用代理配置导致什么东西出错？

**Comment by FelisCatus** [comment]
什么鬼……`svchost.exe` 又是什么……难道 PAC 脚本还能在 `svchost.exe` 进程上跑？不明觉厉……

**Comment by celeron533** [comment]
因为google update是作为计划任务（trigger：用户登录，或 定时）和service在跑的

**Comment by FelisCatus** [comment]
既然禁用 SO 后还这样的话，我感觉和 PAC 关系不大……

**Comment by celeron533** [comment]
@FelisCatus 明天我试试全新安装完chrome，然后删掉两个更新服务、删掉两个更新的计划任务试试

**Comment by celeron533** [comment]
再次更新：
关键点应该在“关闭chrome后继续运行后台应用”

另一个同事保持后台，`svchost.exe` 爆炸
我不保持后台，若干分钟后`chrome.exe` 爆炸


我打算回滚到老版本的SO。。。

然而家中的机器却没有问题

**Comment by nefiend** [comment]
我遇到的情况如下：
switchyomega是自动切换模式，经常（一天2~3次）在切换到别的页面或者新建一个标签页的时候，电脑内存占满，类似与死机。我怀疑是我选择了switchyomega中的选项同步的原因，今天刚关掉了该选项，目前情况良好。请问是否找到内存泄漏的真正原因？

**Comment by FelisCatus** [comment]
目前结论大概是 Chrome 的内存管理问题了，见 #815. 至于关闭选项同步就能用了……感觉是偶然吧，毕竟不修改选项的时候选项同步应该不占用资源……
