### ISSUE TITLE
F/R: more vibrant colours in icon

### ISSUE THREAD

**Issue by TheBoof** [FelisCatus/SwitchyOmega#801]
Since the update to Omega and the O icon, it has become more difficult to tell the difference in proxies based on the icon. Could we get some more vibrant colours?

**Comment by celeron533** [comment]
@TheBoof , you can change the color for each profile as you wish.

![2016-06-14 13_26_29-battle net desktop app](https://cloud.githubusercontent.com/assets/3608762/16031931/b4a88412-3233-11e6-8950-406a6884c4fa.png)

**Comment by celeron533** [comment]
@FelisCatus , is it possible to made the icon a bit larger?

Here is a screenshot from my machine. SO is the icon between **AdBlock** and **AwesomeScreenshot**:

![image](https://cloud.githubusercontent.com/assets/3608762/16031992/3144d6a6-3234-11e6-890b-889c9b6f4560.png)

**Comment by TheBoof** [comment]
Thanks celeron533 - hadn't found that in the new interface.

**Comment by FelisCatus** [comment]
@celeron533 I will check the visual guidelines for extensions and update if necessary.

**Comment by FelisCatus** [comment]
Created #803 for that.
