### ISSUE TITLE
Enlarge the extension icon | 放大扩展图标

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#803]
For browser action icon, according to [browserAction documentation](https://developer.chrome.com/extensions/browserAction):

> Do use big, colorful icons that make the most of the 38x38-pixel space. Browser action icons should seem a little bigger and heavier than page action icons.

Currently that icon looks a little bit too small compared to other extensions:

![image](https://cloud.githubusercontent.com/assets/3608762/16031992/3144d6a6-3234-11e6-890b-889c9b6f4560.png)

Also, according to the [images guideline for Chrome Web Store](https://developer.chrome.com/webstore/images):

> A circular icon should have a diameter of approximately 112 pixels, or 85% to 90% of the image width.

We might need to check the size of the app icon as well.

**Comment by celeron533** [comment]
@FelisCatus , I am working on this issue.

**Comment by FelisCatus** [comment]
I've written a new script and some SVGs using arcs instead of  bezier curves. Let's see if this works as intended.

@celeron533 Please also test on OS X if possible. I would really appreciate your help.

**Comment by FelisCatus** [comment]
Note that in the new scripts & SVGs, all values are exact (multiples of `0.25`), which means no rounding is necessary even when converted to binary floating point.

**Comment by FelisCatus** [comment]
I just checked the developer guideline. It seems that `19x19` icons are no longer recommended... Instead, we should now use `16x16` and `24x24`, `32x32` for different devices with scaling. I guess I need to update the sizes now.

A simple check shows that the PNG icons are occupying around 87.5% of the image size, which means the PNG icons does not need to be updated. Those images already follow the images guideline for Chrome Web Store.

**Comment by FelisCatus** [comment]
Updated. Please try again.

**Comment by celeron533** [comment]
Tested on my Windows 10 machine, looks pretty good.
And sorry, I haven't got any Mac machine... :apple:

**Comment by FelisCatus** [comment]
Release 2.4.0 is on the way with enlarged icons. Only browser action icons and favicons are affected. Others are unchanged.

**Comment by FelisCatus** [comment]
2.4.0 has been released.

**Comment by celeron533** [comment]
Great thanks for your work, @FelisCatus !
