### ISSUE TITLE
选择系统代理，感觉类似全翻

### ISSUE THREAD

**Issue by specter119** [FelisCatus/SwitchyOmega#804]
系统及软件版本自动生成就不说了。
ss设置了用户规则，通过pac翻墙。
高校买了数据库，数据库一般通过ip判断用户的机构。
也就是说，我SwitchyOmega选择系统翻墙后，chrome应该和什么都没装的safari网络环境一样，该访问的数据库能访问，但是实际上并不是。
选系统代理，safari能正常访问，chrome却不能。
选直接连接，貌似还是不能访问，更不能翻墙。
那么我需要做一个干干净净没插件的chrome的测试吗？还是说禁用SwitchyOmega测试下就好呢？

SwitchyOmega 2.3.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2763.0 Safari/537.36

**Comment by cnrat** [comment]
请禁用SwitchyOmega测试一下。

**Comment by specter119** [comment]
@cnrat 已经禁用，还是不能访问，说明至少不是SwitchyOmega的问题。谢谢！
其实很早就感觉访问数据库有问题，包括上淘宝京东，经常把我重定位到海外，我以前总以为是SwitchyOmega的问题，看来应该是chrome的问题，其他原因能想到的就是[流量节省程序](https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac)这个插件了。我等下测试完了再反馈，谢谢，我自己关了这个了。

**Comment by specter119** [comment]
@cnrat 已测试，就是[流量节省程序]
(https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac)这货的问题，看来这个插件，起的作用还是很底层的。
