### ISSUE TITLE
使用Google帐号同步设置与情景模式的问题

### ISSUE THREAD

**Issue by yzpTsubasa** [FelisCatus/SwitchyOmega#805]
我在电脑A中启用了这个同步，并且当前有一些配置。然后在另外一台电脑B有新的Chrome，并且同步了扩展SwitchyOmega，然后开启同步，会导致B的配置覆盖原有的A的配置。这个问题挺严重的~~~

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36

**Comment by FelisCatus** [comment]
如果 B 是新安装的，那么 A/B 设置应该是一样的，也不存在覆盖的问题了。如果改 B 的时候不想  A 被修改，那么在 B 那边先禁用同步再修改就好了。

如果 B 已经有设置了，且设置不同于 A ，那么 B 在开启同步时会提示云端有数据，可以下载覆盖或删除云端数据，然后再开同步

所以我不太清楚问题在哪里……

**Comment by yzpTsubasa** [comment]
今天我再卸载了重试了一下，发现SwitchyOmega会自动打开同步，同时配置数据也同步了。可能是之前的操作有误吧，上次的时候安装是没有自动开启同步的，我手动去打开，便出现了覆盖的问题。
哈哈~能用就好，辛苦了

**Comment by FelisCatus** [comment]
这可能是网络原因导致 SwitchyOmega 已经安装成功，但是配置并没有同步进来。由于这种情况下 SwitchyOmega 也没有任何办法知道配置同步功能有没有开启，所以没有办法正常处理。

我的建议还是耐心等待 SwitchyOmega 的选项同步完毕后再操作。如果偶尔出现配置还是初始配置的情况，多等等，重启几次 Chrome 之类的，然后再检查 SO 的导入/导出那里是否显示云端有不同的版本可以下载。（由于技术原因，这里显示的其实并不是谷歌的服务器上有没有配置，而是本地有没有下载好的配置。谷歌不允许主动去查询/下载远端数据，只能被动等推送。）
