### ISSUE TITLE
谷歌浏览器升级到50以上就不怎么好用了，经常打不开

### ISSUE THREAD

**Issue by MSG-maniac** [FelisCatus/SwitchyOmega#807]
谷歌浏览器升级到50以上就不怎么好用了，经常打不开

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36

**Comment by MSG-maniac** [comment]
64位的版本

**Comment by FelisCatus** [comment]
经常打不开什么？

**Comment by wensdayh** [comment]
我也发生了同样的情况。
使用Internet选项里面的“局域网设置”里的“为LAN使用代理服务器”能够实现代理访问谷歌；
但是同样的代理等设置 在 “Proxy SwitchyOmega”中，无法访问谷歌，一直提示无法访问此网站。
---------------------------------------
操作系统：win10 64位家庭版
SwitchyOmega版本： 2.3.19
Chrome版本：51.0.2704.79
---------------------------------------
我怀疑是不是最新版本的Chrome的问题，因为昨天我尝试了重新安装该版本号的Chrome，刚装上Proxy SwitchyOmega还能访问谷歌，但是今天突然又无法使用了。只能暂时通过inernet选项里的代理设置了。期望能够尽快找出问题，并修复啊。

**Comment by wensdayh** [comment]
![3l4a0bhj ux5u y85h](https://cloud.githubusercontent.com/assets/20010765/16169823/11a70ede-356f-11e6-90cc-e51393f6f2be.png)

补图如上（使用Proxy SwitchyOmega发生无法访问）

**Comment by FelisCatus** [comment]
请打开 `chrome://net-internals/#proxy` 并将页面上显示的内容复制到这里。

**Comment by wensdayh** [comment]
[net-internals_proxy.txt](https://github.com/FelisCatus/SwitchyOmega/files/321660/net-internals_proxy.txt)
全选复制下来了。。。是这个么？感觉是不是出什么问题了？还是我操作上有什么不对？

**Comment by wensdayh** [comment]
![43 wciyqv 7p99dm 92 fs](https://cloud.githubusercontent.com/assets/20010765/16169952/a6d008cc-3573-11e6-8181-6280897a0ac0.png)
在上面的txt文档里面内容出现以前，有一闪而过的介个，如上。

**Comment by wensdayh** [comment]
刚换用版本 为49.0.2623.110 (64-bit)的Chrome，目前可以使用Proxy SwitchyOmega，后续跟进看看。
在百度贴吧发现一个同样问题的：http://tieba.baidu.com/p/4617561036

**Comment by FelisCatus** [comment]
之前你设置的是“为LAN使用代理服务器”，也就是全局使用代理模式。而从你复制的那段结果显示，你用的很可能是自动切换模式，而且很可能用了 GFWList 之类的列表。请切换到全局模式试试看，应该就能正常访问网站了。

至于自动切换为什么不能访问，这很可能是因为某个网站只能经过代理访问，但实际设置的结果导致其使用了直接连接。根据设置不同，这可能是手动设置的切换规则问题，也可能是规则列表的目标规则选错，甚至可能是规则列表中未包含此网站或者指定此网站使用直接连接。此类问题请自行排查。

**Comment by wensdayh** [comment]
但是我卸载了51版本的chrome，没有删除个人数据。继续安装49版本的chrome，拓展Proxy SwitchyOmega里面的数据基本没变，但是却可以访问谷歌了。这点比较困惑。
如你所述，我在想是否高版本的chrome是否会导致自动切换失败，即不能通过代理访问，而默认了直接连接。门外汉，仅仅是反应下问题，最后还是谢谢你。
