### ISSUE TITLE
加载规则列表过长导致 Chrome 崩溃的问题

### ISSUE THREAD

**Issue by hyxxsfwy** [FelisCatus/SwitchyOmega#809]
在自动切换模式下，一旦加载基于白名单的规则列表（3W+），Chrome 就开始崩溃，无法正常使用。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by FelisCatus** [comment]
可以提供一个规则列表用于测试吗？

顺便，如果 Chrome 崩溃了请提交崩溃报告的 Chromium 项目。理论上 SwitchyOmega 无论做什么 Chrome 都不应该崩溃。

**Comment by hyxxsfwy** [comment]
用全新的 Chrome 账户，只装 SO 扩展测试了一下，确认是 SO 的问题，加载白名单规则后浏览几个网页 （尤其是 flash 播放页面）Chrome 就闪退。

闪退前的报错就是内存溢出：
```[4716:7992:0630/173431:FATAL:memory_win.cc(38)] Out of memory, size = 1048576```

规则备份文件与 debug log 见 [zip 附件](https://dl.dropboxusercontent.com/u/81625521/atts/16.06/SO-WhiteList-Crash.zip "https://dl.dropboxusercontent.com/u/81625521/atts/16.06/SO-WhiteList-Crash.zip") 。

**Comment by FelisCatus** [comment]
这是浏览时的崩溃问题，或者是 PAC 解析进程工作有问题，或者是 flash 的问题。总而言之这都需要到 Chromium 项目反馈。这里无法修复。
