### ISSUE TITLE
Request : Advanced Conditions to include Wifi Network

### ISSUE THREAD

**Issue by fylim** [FelisCatus/SwitchyOmega#812]
Hi This is not an issue but more of a request if you can incorporate Wifi Network as an option to auto switch  Proxy profile.

E.g. 

Home WIFI - Direct
Office Wifi - Proxy Profile 1

Thanks

**Comment by FelisCatus** [comment]
I'm marking this as "won't fix" because Wifi Network name is non-portable information and requires native code for each platform (e.g. Windows, Linux, OS X). This is very unlikely to be implemented.

For solutions related to detecting network environments and workarounds, please refer to #812.
