### ISSUE TITLE
Multiple rule lists supporting in auto switching mode.

### ISSUE THREAD

**Issue by zbutfly** [FelisCatus/SwitchyOmega#813]
Scenario for example:

I maintain a list on github for some personal sites need to be applied on proxy, and I need to follow official gfw list to be applied on proxy too (maybe same proxy, or different proxies). Current I merge these two lists into one file, then put it on github and subscribe it in switchsharp/switchomage manually.

It works, but is ugly! Since the great product upgrade to new generation, can author provide this feature internal? 

THX for your work on FXXXing GFW.

**Comment by FelisCatus** [comment]
Merging into #685.
