### ISSUE TITLE
我们的系统检测到您的计算机网络中存在异常流量

### ISSUE THREAD

**Issue by rakor1986** [FelisCatus/SwitchyOmega#814]
使用谷歌搜索的时候，总提示“我们的系统检测到您的计算机网络中存在异常流量”，然后要求输入验证码，但是输入正确的验证码N次之后，还是提示输入验证码，完全使用不了，该如何解决？

**Comment by celeron533** [comment]
看上去是你选用的代理服务器有问题，被google列入了特殊名单

**Comment by FelisCatus** [comment]
总而言之不是 SwitchyOmega 的问题……
