### ISSUE TITLE
你好，请问安卓手机浏览器可以使用这个插件吗，

### ISSUE THREAD

**Issue by the-blue-sea** [FelisCatus/SwitchyOmega#816]
SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by celeron533** [comment]
android原生的浏览器似乎不能安装任何扩展程序

**Comment by bugparty** [comment]
安卓用影梭
