### ISSUE TITLE
Auto Rule Profile -> System Proxy

### ISSUE THREAD

**Issue by snakyjake1** [FelisCatus/SwitchyOmega#818]
Within the Auto Switch rules, I need the rule profile option to select System Proxy.
Some sites works fine with Direct, but some sites are affected by the proxy server, and require going through the proxy server.

**Comment by celeron533** [comment]
Similar to #170 
> 由于PAC限制，此功能无法实现。

Due to the limitation of PAC, it could not support 'system proxy'.

**Comment by FelisCatus** [comment]
By the way, it is possible to create a Proxy Profile for your proxy and input the same server/port as in your system configuration.

**Comment by snakyjake1** [comment]
@FelisCatus:  Not sure if/how that will work.  I have a laptop.  When I'm at work, I need to use the corporate proxy server for some sites.  When I'm at home on personal time (I also don't want the corporate proxy servers tracking me when I'm at home on personal time), I don't want to use the corporate proxy server, and I want to connect directly to the Internet.

**Comment by SmartWorm** [comment]
System Proxy is pushed by AD admin in company, it is hard to manually set

**Comment by FelisCatus** [comment]
Is your company using WPAD? Could you please try adding a PAC Profile with the URL `http://wpad/wpad.dat` and see whether it works for you?
