### ISSUE TITLE
AutoProxy规则过多导致chrome崩溃

### ISSUE THREAD

**Issue by luckylion** [FelisCatus/SwitchyOmega#819]
win10, chrome 51.0.2704.106 m -32, 8G ram,SwitchyOmega 2.3.19
情景模式
proxy   ss
pac  https://github.com/usufu/Flora_Pac/raw/master/flora_pac.pac
Auto
![ss](https://cloud.githubusercontent.com/assets/3772320/16709056/6d475e90-4638-11e6-9eab-c980daf74acb.png)
==============================================================

问题出在AutoProxy条数上,白名单我是提取gfw_whitelist里面的网址外加自己经常用的一些域名总共有9600+条.
这时如果打开8个到十来个页面标签(具体不固定),chrome会自动关闭.
如果将AutoProxy条数只保留常用的几个,就不会出现自动关闭现象

===================================================
用回SwitchySharp没有出现浏览器崩溃问题

**Comment by FelisCatus** [comment]
应该是 Chrome 问题，也许可以试试看 https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502 的方法？

**Comment by ddzy2015** [comment]
我关闭了进程外V8代理解析，可问题还是存在，关闭之前是v8代理解析工具发生内存泄漏，关闭后是主进程内存泄漏
不管是用PAC还是AUTOPROXY都一样，用系统代理也是（我把系统代理开了PAC自动代理）
我是从这个网站导出的PAC：https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
Chromium 51.0.2704.79 Ubuntu 16.04 (64-bit)

**Comment by FelisCatus** [comment]
这应该只能去 Chrome 反馈了……

**Comment by xlfjn** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=639217
看上去有人已经反馈了。

**Comment by FelisCatus** [comment]
挺好的，多关注吧。

**Comment by xlfjn** [comment]
是否应该在#815说明一下？

**Comment by FelisCatus** [comment]
已经更新到 #815 ，感谢提醒。
