### ISSUE TITLE
Noob - trying to rotate proxies

### ISSUE THREAD

**Issue by LBranigan** [FelisCatus/SwitchyOmega#820]
I am would like to rotate through a list of 10 proxies automatically, maybe every 5 minutes or so. Is this possible? Any help appreciated thanks.

**Comment by FelisCatus** [comment]
Such functionality is possible via PAC scripts, which can be then imported to SwitchyOmega using PAC Profiles.

See http://docs.getfoxyproxy.org/index.php?title=Rotate_IPs for examples about rotating proxy servers.
Disclaimer: The linked website or its author are not associated with the SwitchyOmega project in any way. The scripts there could prove useful for your reference but not guaranteed to be functional or safe.
