### ISSUE TITLE
请问普通的http 加帐号密码登录的是是加密方式？

### ISSUE THREAD

**Issue by heartacker** [FelisCatus/SwitchyOmega#822]
小白斗胆来问一下，恕我无知。ss 有好多类型，我虽然不懂，但是我就想问一下这种事什么加密方式？
![default](https://cloud.githubusercontent.com/assets/1876302/16753767/21549a46-481f-11e6-936d-13e78602178a.png)

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by celeron533** [comment]
这是认证，不是加密
