### ISSUE TITLE
迅雷和omega的冲突

### ISSUE THREAD

**Issue by LastKing** [FelisCatus/SwitchyOmega#823]
这omega。。为什么 迅雷一开就失败，chrome 就通过不了代理了，有什么解决方案没

**Comment by celeron533** [comment]
#557

**Comment by LastKing** [comment]
但是为什么。。我用SwitchySharp。。这个又没事？谢谢。。麻烦了。。

**Comment by FelisCatus** [comment]
代理协议的问题吧……看看 Sharp 里设置和 Omega 有什么不同就知道了……看 #557 的说明，用 HTTP 代理协议可以绕过此问题，或者使用系统代理（如果代理客户端支持的话）。
