### ISSUE TITLE
由于网络原因，此页面部分资源加载 

### ISSUE THREAD

**Issue by l343802858** [FelisCatus/SwitchyOmega#824]
由于网络原因，此页面部分资源加载失败。这些问题可能是由您的网络、代理服务器或网站本身引起的。
这些问题并非由 SwitchyOmega 自身导致，它只不过检测并报告了错误而已。

您可以查看以下域名，并根据实际情况确定是否对其使用代理。

1 *.google.com

**Comment by celeron533** [comment]
SwitchyOmega 不是翻墙工具，他只是一个切换代理服务器的工具。如果你不知道你的代理服务器在哪里，单纯的安装SwitchyOmega 并不能使你能够访问google。

**Comment by l343802858** [comment]
配置都是在网站下的

**Comment by FelisCatus** [comment]
请咨询代理服务器提供商或者网络提供商。如果您的配置文件是从网上下的，那么请联系那个网站来询问配置文件应该如何使用或者需要进行哪些修改。
