### ISSUE TITLE
自动切换模式可以设置不代理hosts吗？

### ISSUE THREAD

**Issue by adasqg** [FelisCatus/SwitchyOmega#825]
SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by FelisCatus** [comment]
SO 作为扩展而言无法读取 hosts 文件。不过可以把 hosts 文件中所有的域名拿出来，然后贴到不代理的地址列表里（需要手动去掉 IP ，并改成一行一个域名的形式），应该可以用。
