### ISSUE TITLE
菜单按钮可能出现不全

### ISSUE THREAD

**Issue by zhuziyi1989** [FelisCatus/SwitchyOmega#826]
菜单按钮偶尔会出现不全（[直接连接]和[系统代理]有时候显示不出来）。
正常情况如图：
![正常情况](http://ww4.sinaimg.cn/large/69b05e0ajw1f5xz7upt62j20x20l242h.jpg)
有问题的时候如图：
![有问题的时候](http://ww4.sinaimg.cn/large/69b05e0ajw1f5xza7ow3zj20nc0iwabd.jpg)

SwitchyOmega 2.3.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by FelisCatus** [comment]
见 #128 ，是 Chrome 问题，请到那边反馈。
