### ISSUE TITLE
能否加入通过自动检测延时/超时来选择代理的功能？

### ISSUE THREAD

**Issue by cxgreat2014** [FelisCatus/SwitchyOmega#827]
譬如说，一个页面中有些资源通过正常访问特别缓慢，能否新增一个模式在检测到这一问题时自动让那些加载缓慢的资源走设定的代理模式呢？感激不尽。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by FelisCatus** [comment]
目前的未加载资源是已经包括了加载缓慢的资源了……可以尝试使用。

至于自动换成其他代理之类的，应该不是本项目可以做到的……
