### ISSUE TITLE
临时规则能否在最下面加个取消？

### ISSUE THREAD

**Issue by distance00** [FelisCatus/SwitchyOmega#828]
偶尔用一下，发现再怎么切换情景模式，直连，还是系统代理，统统都无效了，如果想改变代理就只能在临时里面改了，只有重启浏览器才能恢复。
另外切换规则设置里面能否分组，太多了找起来不好找，有的一个网站需要设置很多规则（比如youtube）如果能分组折叠起来就好了。

**Comment by FelisCatus** [comment]
临时规则的界面请移步 #515 讨论.

切换规则不太好做分组，如果一个网站有多个规则，可以把规则合并在一起，用`|`分隔，例如`www.youtube.com|example.youtube.com`。如果规则实在太多建议建立多个自动切换模式串联使用。

**Comment by distance00** [comment]
@FelisCatus 请教一下串联的方法，是不是把条件类型选为“禁用”，情景模式选另一个自动切换模式？

**Comment by FelisCatus** [comment]
要串联用，只需要把第一个自动切换模式的“默认情景模式”（最下方）设置成另一个自动切换即可。其他规则照常使用。

**Comment by distance00** [comment]
感谢说明。
