### ISSUE TITLE
高速版网络不稳定，电脑内存卡

### ISSUE THREAD

**Issue by the-blue-sea** [FelisCatus/SwitchyOmega#830]
最近高速版感觉不太稳定，老是掉线，而且，也许是我电脑的原因，使用gae的时候有时占用很大的内存，电脑卡了好几次，使用其他应用同时打开几个都不会卡。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by FelisCatus** [comment]
这里不是 GAE. SwitchyOmega 也没有所谓“高速版”。如果您说的是其他软件，请到对应的软件那里反馈。

**Comment by the-blue-sea** [comment]
好像搞错了，抱歉
