### ISSUE TITLE
希望情景模式可以手动调整顺序

### ISSUE THREAD

**Issue by EthanLauAL** [FelisCatus/SwitchyOmega#831]
希望情景模式可以手动调整顺序，强迫症伤不起

SwitchyOmega 2.3.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36

**Comment by FelisCatus** [comment]
见 #607.
