### ISSUE TITLE
Invalid Backup File

### ISSUE THREAD

**Issue by kamiyeye** [FelisCatus/SwitchyOmega#833]
我手动修改了bak文件（复制了几个Profile，只更改了Profile名字），成功导入**修改后的bak文件**，然后在Chrome里面更新了复制的Profile的服务器地址，一切工作正常。但当我想重新导入**修改前的bak文件**时，出现错误信息：Invalid Backup File。现在想导入任何bak文件，无论是不是clean的都会出现这个错误了，好像被我搞坏了，是不是要重装？

**Comment by FelisCatus** [comment]
教程里那个也不行？可能确实玩崩了……

建议再试两次导入，然后在图标上右键导出日志并上传到这里。

如果想重置选项的话，在选项网页上打开控制台，粘贴以下代码并运行：

```js
chrome.storage.sync.clear();
chrome.runtime.restart();
```

**Comment by FelisCatus** [comment]
Hi, 这边怎么样了？

**Comment by FelisCatus** [comment]
暂时关闭了，如果有问题请重新开启。
