### ISSUE TITLE
一直提示DNS错误

### ISSUE THREAD

**Issue by Arnold4869** [FelisCatus/SwitchyOmega#834]
一直提示DNS错误。然后设置成系统代理模式没问题了。。
重置winsock没用。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36

**Comment by celeron533** [comment]
chrome有时候会默认开启DNS缓存，导致当前站点使用了代理生效前的原生DNS地址。
https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy
