### ISSUE TITLE
能否增加自动发送用户名和密码完成认证呢？

### ISSUE THREAD

**Issue by michaelssss** [FelisCatus/SwitchyOmega#835]
每次都要登陆有点蛋疼。。。反正账号密码也是保存在Chrome的 = =我感觉是没差。。
逻辑流程这样:
从Chrome的管理器提供密码自动尝试登陆，
否则尝试软件自身提供的账号密码，
否则提示用户输入账号和密码

**Comment by FelisCatus** [comment]
目前 SwitchyOmega 选项页面可以设置代理用户密码的吧？如果不设置的话那么 Chrome 会自动弹出密码提示。

**Comment by michaelssss** [comment]
=.= 只有PAC一种模式可以，别的不行。。。。

**Comment by FelisCatus** [comment]
HTTP/HTTPS 代理协议应该也可以设置的， SOCKS 不能设置因为 Chrome 不支持。
自动切换对于每个请求都会选择某个特定代理，所以到对应的代理情景模式中设置即可。
