### ISSUE TITLE
系统代理，并没有使用IE设置的代理

### ISSUE THREAD

**Issue by happysky** [FelisCatus/SwitchyOmega#836]
系统代理，并没有使用IE设置的代理

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

**Comment by FelisCatus** [comment]
其他扩展也可以提供代理设置。最终结果请到 `chrome://net-internals/#proxy` 查看。

如果还不确定，可以试着禁用所有扩展。

**Comment by FelisCatus** [comment]
暂时关闭了，如果有测试结果请重新开启。
