### ISSUE TITLE
Autoswitch to proxypac (at work) and direct at home

### ISSUE THREAD

**Issue by psyciknz** [FelisCatus/SwitchyOmega#837]
Is there a way of using autoswitch defaulting to the proxy.pac for work when at work, but when i get to my home network use a direct setting?

**Comment by FelisCatus** [comment]
See #197.

**Comment by psyciknz** [comment]
I'll add one more comment here rather than the referenced issue.

But with the switchyomega interface, how can I use the functions described in issue #197?  I assume I use the source code view?

eg:
[SwitchyOmega Conditions]
@with result

internal.example.com +direct
myIPis 10.0.0.0/24 +proxy
myips 192.168.1.0/2 * +direct

**Comment by FelisCatus** [comment]
The last comment on that issue is only a proposal rather than implemented feature. There is no way to use such conditions whether using source mode or not.

I would suggest reading the earlier comments and pick a PAC-based method.
