### ISSUE TITLE
希望作者能够把这款优秀的插件移植到Firefox浏览器

### ISSUE THREAD

**Issue by caoli5288** [FelisCatus/SwitchyOmega#839]
希望作者能够把这款优秀的插件移植到Firefox浏览器。Firefox浏览器现在的几款代理软件垃圾得不行，但是我实在离不开Firefox的很多其他插件，现在我是需要爬墙的时候用chrome，只因为chrome支持你的这款插件，其他时候用Firefox。听说Firefox现在插件API兼容chrome的了，我觉得作者是时候拯救Firefox用户了！

**Comment by celeron533** [comment]
可以去 #102 讨论
