### ISSUE TITLE
host without domain always uses direct proxy

### ISSUE THREAD

**Issue by klement** [FelisCatus/SwitchyOmega#840]
So I have a condition where I need to tunnel specific host via a specific proxy.

My URL looks like this http://internal-wiki/<...>

Alll the rules which I tried to install to make it go via specific proxy are ignored. Even setting "use proxy A for all URLs" doesn't work.

I think the culprit is this part of the PAC script:

if (host === "127.0.0.1" || host === "::1" || host.indexOf(".") < 0) return "DIRECT";

of course "internal-wiki" doesn't contain a '.' anywhere.

**Comment by FelisCatus** [comment]
Please remove `<local>` from the Bypass List for your intended behavior. That should be a text area in your Proxy Profile (not Switch Profile).
