### ISSUE TITLE
 add "Servers for which you want to use proxy"

### ISSUE THREAD

**Issue by TheOneWhoKnock** [FelisCatus/SwitchyOmega#841]
Can u pls add future to add "Servers for which you want to use proxy"
mean only this domain access over proxy.
thank you for your work.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.46 Safari/537.36

**Comment by FelisCatus** [comment]
Use Switch Profiles for this. One should be already created for you upon installation with the name `Auto Switch`.
