### ISSUE TITLE
希望添加对Win10 Edge浏览器的支持

### ISSUE THREAD

**Issue by quericy** [FelisCatus/SwitchyOmega#842]
稍微修改了下清单文件，使用Edge加载扩展后，点击弹出层提示“网络错误0x2,系统找不到指定的文件”
![如图](http://i.imgur.com/MYj9iuG.png)

也许兼容Edge会比FireFox容易得多？毕竟是相同内核...
而且修改清单文件提示的错误大部分是按照chrome developer的规范的，只是不知道微软是否提供了相应的api

**Comment by FelisCatus** [comment]
见 #589.
