### ISSUE TITLE
关于网址正则实在不知道如何书写才对

### ISSUE THREAD

**Issue by kid101x** [FelisCatus/SwitchyOmega#843]
你好，打扰下我想要匹配：
`https://www.google.com/searchdomaincheck?format=url&type=chrome`
然后我设置额了这两种却都无效，不知道能给指点下么：）：
`://([^/.]+\.)*google\.com(:\d+)?/[searchdomaincheck]`
`^http(|s)://www\.google\.com(|.*)/searchdomaincheck`

SwitchyOmega 2.3.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by celeron533** [comment]
`^http(|s):\/{2}(.*\.)*google\.com(:\d+)?\/searchdomaincheck.*`

推荐这个网站，http://www.regexpal.com/
像我这种regex生手也能在上面写出些可用的匹配

![image](https://cloud.githubusercontent.com/assets/3608762/17460071/71b803ec-5c88-11e6-9dd5-1ec8b192df18.png)

**Comment by FelisCatus** [comment]
其实如果不介意的话也可以用通配符表达式， `*://*.google.com*/searchdomaincheck*`之类的。虽然匹配不是那么精准，但很容易书写和编辑。

**Comment by kid101x** [comment]
依然全都无效……

**Comment by FelisCatus** [comment]
速报： Chrome 52 开始， HTTPS 网址的具体路径和查询参数不再提供给 PAC 脚本。在 SwitchyOmega 中使用网址相关规则的用户请检查是否匹配了域名以外的信息，有则会失效！自制PAC脚本的各位也请多留心。请相互转告。

对于您的情况，不能再使用具体的路径信息了，类似`searchdomaincheck`的规则都会失效。只能匹配`https://www.google.com/`（注意只到域名为止）。所以您看看怎么办吧……只能改成别的规则了……

此更新由 Chromium 项目开始，影响 Google Chrome 和其他 Chromium 内核的所有浏览器。此问题间接影响 SwitchyOmega 但SO没有任何办法可以绕过此限制。更新原因不明，亦无正式通知。不要向我抱怨此问题，这不是我能控制的。

技术细节见 #845.

**Comment by DailyShana** [comment]
目前可以用命令行参数或者组策略，见https://github.com/FelisCatus/SwitchyOmega/issues/845#issuecomment-240948610
但此方法在未来可能会失效

**Comment by olbb** [comment]
PacHttpsUrlStrippingEnabled
false
这个方法目前能用  感谢

**Comment by cheungseol** [comment]
> 目前可以用命令行参数或者组策略，见[#845 (comment)](https://github.com/FelisCatus/SwitchyOmega/issues/845#issuecomment-240948610)
> 但此方法在未来可能会失效

这个是浏览器设置吗？～请问在哪里设置？～没找到入口
