### ISSUE TITLE
Can't create rule that matches local network

### ISSUE THREAD

**Issue by akohlsmith** [FelisCatus/SwitchyOmega#844]
I had expected `<local>` to match any IP or resolved IP which matches my local network (i.e. 192.168.1.0/24 if my wifi has an IP on that network, or 172.16.0.0/16 if my ethernet is connected to that network.

Am I missing something? I would like to set up a rule which uses a direct connection to any IP that matches my local network *without* hard-coding the IP range(s) depending on where I am working.

**Comment by celeron533** [comment]
From my point of view, I think that ```<local>``` only means your machine as ```127.0.0.1```

![image](https://cloud.githubusercontent.com/assets/3608762/17460144/83e32a30-5c8b-11e6-89bf-4024fb71c265.png)

Have you tried to add your subnet to the bypass list?
You could also find in this screenshot that in the old version of SO, there is no ```<local>``` alias, so all three local addresses are manually set in the first three lines.

![image](https://cloud.githubusercontent.com/assets/3608762/17460152/e14f9fa0-5c8b-11e6-86dd-a7e2ec9e3539.png)

**Comment by FelisCatus** [comment]
See https://github.com/FelisCatus/SwitchyOmega/issues/443#issuecomment-197883907 for what `<local>` really does. This behavior is defined by Chromium and SwitchyOmega merely pass it to Chromium as-is (in case of Proxy Profiles) or try to mimic Chromium's logic (in case of Switch Profiles).
