### ISSUE TITLE
最新版本的插件，用chrome官方版本，经常卡死。用以前的版本无问题

### ISSUE THREAD

**Issue by ugvf2009** [FelisCatus/SwitchyOmega#847]
不知道是什么原因。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2829.0 Safari/537.36

**Comment by ugvf2009** [comment]
请把拓展名改成.pac即可。


[OmegaProfile_GoAgent_PAC.pdf](https://github.com/FelisCatus/SwitchyOmega/files/417803/OmegaProfile_GoAgent_PAC.pdf)

**Comment by cnfree0355** [comment]
我也遇到这个问题，好像最近更新google 浏览器导致的我用的版本号 52 ,给的建议是
chrome://flags/#v8-pac-mojo-out-of-process 关闭V8 代理解析，可以试试

**Comment by FelisCatus** [comment]
见 https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502

**Comment by ugvf2009** [comment]
@FelisCatus 感谢回复。辛苦！
