### ISSUE TITLE
关于twitter的切换规则无效

### ISSUE THREAD

**Issue by jackphil** [FelisCatus/SwitchyOmega#85]
不知为何，我关于twitter的切换规则似乎无效，原来在switchysharp下工作的很好：

    *://*.twitter.com/*|*://t.co/*

以上为网址通配符，我也试过其他的一些组合，在另一台电脑上不知怎么又好了

**Comment by FelisCatus** [comment]
我只想说我现在才看到这个……请确认使用使用的是“网址通配符”规则，而非“域名通配符”规则。

**Comment by jackphil** [comment]
我已经把所有网址通配符规则转换成域名通配符了。感谢分享这么好的产品
