### ISSUE TITLE
360极速浏览器 点击图标无法弹出情景模式

### ISSUE THREAD

**Issue by kli-nlpr** [FelisCatus/SwitchyOmega#850]
![qq 20160816180102](https://cloud.githubusercontent.com/assets/13194870/17695503/70186a90-63db-11e6-8f20-dd1756ae1228.png)

点击这个图标无反应。

**Comment by celeron533** [comment]
其他浏览器呢？

**Comment by FelisCatus** [comment]
1. 请告知使用的浏览器版本，可复制 `chrome://version`页面的内容。
2. 如果右键点击能弹出菜单的话，请用菜单里的“导出日志”功能获取日志并上传到这里。如果右键也无法弹出菜单，或者菜单中无此选项，请报告。
3. 既然点图标无反应，之前是如何激活自动切换模式的？还做过哪些操作？

**Comment by distance00** [comment]
多等一会儿，或者重启chrome，如果你编辑了规则，特别是添加删除了情景模式，可能会出现弹出菜单延迟很久才会弹出。如果你在弹出前点了别处，就有了不会弹出的假象。

**Comment by distance00** [comment]
@kli-nlpr 另外请问有没有用虚拟情景模式？

**Comment by kli-nlpr** [comment]
现在又没有问题了。估计确实需要等一会才能弹出，原生的chrome没有问题，基于chrome内核的360极速浏览器估计对chrome的插件支持的还不是太好。。谢谢大家

**Comment by distance00** [comment]
我用的就是原生chrome，目前7个情景模式，两个虚拟，折腾一会儿规则和情景模式，必出。

**Comment by kli-nlpr** [comment]
各位，我发现并不是弹不出菜单，而是已经弹出了，不显示而已，把鼠标放到空白位置竟然可以选择不同模式。。。。。。现在是原生chrome也出现这种情况了，我是从xxnet自带的OmegaOptions.bak文件导入的，其他没进行任何设置。

**Comment by distance00** [comment]
重启一下chrome，看刚启动是否正常。图中那个提示是系统代理的提示，为什么会那么靠下？应该排在第二个。

**Comment by kli-nlpr** [comment]
重启之后chrome没问题了，360急速还是不行，估计是360对谷歌商店的插件支持的不好。

**Comment by distance00** [comment]
我怀疑我遇到的问题跟虚拟情景模式有关，不知道你是否也用了虚拟情景模式？

**Comment by kli-nlpr** [comment]
我不知道什么是虚拟情境模式

这是我所有的模式

![qq 20160822220252](https://cloud.githubusercontent.com/assets/13194870/17857415/3f014d5e-68b4-11e6-93c9-ccf977211c8b.png)

**Comment by distance00** [comment]
你的情景模式不多，看来我们遇到的不是同一个问题。
我的正常弹出就有1-2秒的延迟，不用虚拟情景模式应该不会延迟这么久。
重启后正常的话，可以注意一样做了什么操作以后出现问题。我的是修改规则后出现，甚至有一次没改（改了没保存）就在选项里面浏览一会儿关了就出现。

**Comment by FelisCatus** [comment]
既然已经能点了，但是窗口是“隐形”的，那么这 200% 不是 SwitchyOmega 可以控制的。我觉得更像是浏览器自身的渲染问题/操作系统的问题。

P.S. 之前 Chrome 从来没有人汇报过类似问题，其实我更怀疑是和系统的窗口机制有关……如果是 Windows ，检查是否有安装全局的控制窗口的软件、美化软件，等等，或者干脆（在虚拟机里）装个全新的系统然后看看还有没有这个问题吧。
