### ISSUE TITLE
Proxy SwitchyOmega V2.3.19导致Chrome卡顿？

### ISSUE THREAD

**Issue by MonsterOOF** [FelisCatus/SwitchyOmega#851]
## Proxy SwitchyOmega导致Chrome卡顿现象
- 将Chrome升级至最新版本后仍有此问题
- 禁用SwitchyOmega后使用Chrome一段时间未发现卡顿
- 怀疑是SwitchyOmega的自动代理是问题根源?不使用自动切换代理的情况下没有出现卡顿

> 规则列表AutoProxy: https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt

SwitchyOmega 2.3.19
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36

**Comment by cnfree0355** [comment]
我也遇到这个问题，好像最近更新google 浏览器导致的我用的版本号 52 ,给的建议是
chrome://flags/#v8-pac-mojo-out-of-process 关闭V8 代理解析，可以试试

**Comment by FelisCatus** [comment]
见 https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502

**Comment by MonsterOOF** [comment]
@FelisCatus 你好，[#815](https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502)在问题提出之后也看过，V8代理解析也早已关闭。评论中你提到过可能机器性能问题无法处理过多规则列表，尽量用白名单代替，可是switchyomega以前也用过自动代理，同样是上述GFWList，那时候并未出现这个问题。至于降级Chrome我从v52降到了v50，若需要v50- 版本，因各种原因暂不进行尝试。

**Comment by MonsterOOF** [comment]
@cnfree0355 感谢你的回复～V8代理解析关闭后还是有同样问题出现，已经删除自动代理暂时使用firefox

**Comment by FelisCatus** [comment]
有人在  Chromium 汇报了这个问题，具体请移步 #815 最新评论查看。关于此问题统一在 #815 讨论，不另行回复。
