### ISSUE TITLE
导致电脑卡顿

### ISSUE THREAD

**Issue by luoni2002** [FelisCatus/SwitchyOmega#852]
这个上网啥的都挺好的，可是自从用了这个，电脑总是不时地卡死，然后过几秒才能好。我几台电脑都有这种现象，怎么解决呢？

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36

**Comment by FelisCatus** [comment]
见 https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502
