### ISSUE TITLE
求助！使用switchyomega在Chrome上登录Google账号会闪退！

### ISSUE THREAD

**Issue by DornamNg** [FelisCatus/SwitchyOmega#853]
在新安装的chrome上想登录google账号去同步书签和记录，可是一点击登录按钮加载圆圈转了一圈以后就会闪退，重装好几遍了都这样，不使用switchyomega登录就不会闪退。

**Comment by FelisCatus** [comment]
……我猜想这是 Chrome 的问题？

具体的操作顺序是什么？安装 SwitchyOmega 、设置好、打开自动切换，再登录 Chrome?

用其他方式（比如命令行）设置代理参数是否会闪退？

**Comment by DornamNg** [comment]
我停用了switchyomega以后用internet选项设置PAC代理来登录仍然会闪退，那应该就是chrome自身的问题？

**Comment by FelisCatus** [comment]
那 200% 是 Chrome 的问题，建议前往 Chromium 项目反馈，并提交崩溃报告。与本项目无关。

**Comment by qzhJie** [comment]
我禁用switchyomega，点击登陆就不会闪退

**Comment by FelisCatus** [comment]
@qzhJie 嗯，那大概只能说明只要设置了代理选项（或者连接了某个代理服务器）就会闪退……你可以试试看用命令行设置同样的代理参数，或者直接用系统设置（比如 Internet 选项之类的），也是会闪退的。这种时候就能排除 SwitchyOmega 的因素了，请将崩溃报告提交给 Chrome.

**Comment by Teamo1001** [comment]
我的用了代理  登陆也是会闪退

**Comment by aust7c** [comment]
我的也是闪退，后来你们怎么解决的？？？？

**Comment by LoSealL** [comment]
chrome 56.0.2924.87，用的离线安装包，至今BUG未解决。
如果在线安装的chrome，则没有这个问题。猜测跟离线安装包有关

**Comment by DornamNg** [comment]
到现在我也没有解决掉

2017-02-04 13:56 GMT+08:00 Tang, Wenyi <notifications@github.com>:

**Comment by qzhJie** [comment]
如果你可以使用代理，就是想登录浏览器的google账户，可以看一下http://blog.csdn.net/qzh_jie/article/details/54729912

**Comment by hrd007hrd** [comment]
谷歌chrome一登录账户就崩溃
当连接HTTPS代理时，点击登录Chrome，登录的小方框会弹出来，但是那个页面没显示出来chrome就直接崩溃（闪退）了。
http代理，socks4/5代理均无此问题
操作系统：Win10 专业版
版本 57.0.2987.110 (64-bit)

**Comment by wangyoucao577** [comment]
@qzhJie  It's useful, thanks very much!!

**Comment by mengfanhong** [comment]
我也遇到同样的问题，参考：http://blog.csdn.net/qzh_jie/article/details/54729912，解决了
