### ISSUE TITLE
小建议。

### ISSUE THREAD

**Issue by distance00** [FelisCatus/SwitchyOmega#854]
1、搜索帖子，发现不少人希望能自己排列情景模式的顺序，但实现成本高，不值得，能不能加一个排序方式，不按组，只按名称排列？这样用户可以自己在名称上加个编号什么的来自定义顺序。我加了好几个备用的代理，一般根本就用不上，但排在最上面，最常用的却排在最下面。
2、能不能用鼠标中键来快速切换代理？
3、虚拟情景模式的下拉菜单需要虚拟情景模式和自动切换模式吗？是不是只有代理，直连和系统代理（目前没有）更合理？这个可能是我不知道一些更高级的用法。

**Comment by distance00** [comment]
另外发现虚拟情景模式的下拉菜单中排序怪异，代理上面有，下面也有，自动切换模式和虚拟情景模式排在中间。

**Comment by FelisCatus** [comment]
1. 如果加的都是备用代理的话建议用虚情景，然后备用代理都改成下划线开头即可从菜单中隐藏。其他的排序方式让我再考虑下。
2. 不能， Chrome 扩展无法捕获鼠标点击图标的事件。
3. 未必有用，但是已经有的功能不会故意去掉。此外，由于技术原因，系统代理不可加入自动切换。

**Comment by distance00** [comment]
感谢说明，能隐藏这个功能太实用了。虚拟情景模式下拉菜单的情景模式排序似乎没有规律，虚拟模式中再套一个虚拟模式我几乎可以肯定没什么用，不过也无所谓了。
另外不知道是不是情景模式加多了还是用了dev版（54.0.2832.2）有时候点一下下拉菜单要等好几秒才出来，选项也是要等很久。要重启chrome才行。

**Comment by distance00** [comment]
感觉卡顿跟编辑规则有关，弹出菜单延迟1-2秒正常（虽然跟别的扩展比还是比较慢，这个可能跟情景模式多少及复杂程度有关），卡顿时候弹出菜单延迟6秒以上，打开选项要10秒以上。感觉是编辑了规则才会出现，还有待多加观察。特别是添加删除情景模式后。正常使用不会出现。
也不算什么大问题，大不了编辑后重启一次Chrome。

**Comment by distance00** [comment]
我把chrome://flags/#v8-pac-mojo-out-of-process “关闭”了。不知道默认是开的还是关的？显示是默认。
也许根本没有关系，因为chrome本身并不卡顿，也许默认就是关的。再观察看看吧。

**Comment by distance00** [comment]
![default](https://cloud.githubusercontent.com/assets/13978341/17839305/ec715ca2-6816-11e6-8722-4d7e25f0b7aa.JPG)

**Comment by FelisCatus** [comment]
感谢，但我需要 Timeline 的时间轴截图，这个统计截图虽然也很有用，但没办法显示加载的先后顺序，以及造成的延迟。另外，如果可以的话，右键选 Save timeline data 然后把文件上传到这里。

此外，这个截图显示的是 635ms 脚本执行和其他等，总共的页面加载时间大概不会超过 1 秒，不是很典型……求一两组卡顿时的数据……

注：菜单的卡顿和网页有关，和 PAC 无关，改 flags 不影响菜单的弹出时间。

**Comment by distance00** [comment]
怎么感觉最大的区别在idle上，这个是正常时的。
![default](https://cloud.githubusercontent.com/assets/13978341/17883030/bfc608c4-6942-11e6-862c-e31834099a53.JPG)

**Comment by distance00** [comment]
正常时的data
[TimelineRawData-20160823T150046.pdf](https://github.com/FelisCatus/SwitchyOmega/files/431842/TimelineRawData-20160823T150046.pdf)
扩展名改为zip，开始压成rar不行，说是zip可传，其实也不行。

**Comment by distance00** [comment]
卡顿时的data
[TimelineRawData-20160823T150816.pdf](https://github.com/FelisCatus/SwitchyOmega/files/431850/TimelineRawData-20160823T150816.pdf)

**Comment by distance00** [comment]
在我这里100%重现的办法，找最复杂的一组autoswitch，切换到编辑源代码，全选拷贝，新建一个autoswitch情景模式，粘贴进去，保存，保存时就会发现半天没有反应。

**Comment by distance00** [comment]
补充一下。我这里总共8个情景模式，两个虚拟。

**Comment by distance00** [comment]
发现跟版本有关，用了52.0.2743.116 (64-bit)（以前用的54 dev），正常情况下的弹出延迟也好了一些，暂时还没发现非常卡的情况，老大不用麻烦了，等54到了稳定版再看看吧。
不过也发现别人提出过虚拟模式影响弹出的情况，也许有改进的必要，但也不算是什么大问题。忙得话就别管它了，关键是核心的功能。感谢提供了这么好的一个扩展。

**Comment by FelisCatus** [comment]
保存选项的时候卡也是正常的……只是之后弹出菜单的情况怎么样？

**Comment by distance00** [comment]
那个卡顿时的data，不用管了，应该跟版本有关。正常情况下弹出菜单有个大概1.5秒的延迟，如果要修复的话可以参考那个正常时的data。弹出后再点虚拟情景模式的菜单秒开，是不是跟预先加载了所有虚拟情景模式菜单项目有关？虚拟情景模式菜单下面再套虚拟情景模式和自动切换模式真的没有一点用，去掉会不会还能让弹出快一点？

**Comment by FelisCatus** [comment]
嗯……这样就比较难确定了。首先我可以回答去掉少量几个菜单项目没什么太大的影响，这个可以自己尝试。其次，我目前也没有想到什么办法可以立竿见影地优化加载时间，至少没有什么简单的方法，否则我早就更新了。

至于问题嘛……首先弹出窗口里所有内容都是预先加载的，所以可能会有加载时间。包括子菜单，添加条件，未加载资源的对话框之类的。当然，里面有很多东西是很不常用的，分摊到每次点击确实是有点不太好。最早的时候以为弹出菜单很简单的，所以设计的不是很模块化。现在要改起来会比较麻烦。

然后可能有一些时间会花费在布局上。通常而言， Chromium 会先试图加载页面，然后等页面的高度和宽度完全确定以后才显示，之后如果再有变化，窗口大小也会变化。也有可能是弹出菜单的页面花了很长时间布局才稳定下来，所以导致显示缓慢。这些问题我需要花很多时间来看 Timeline 确定。

我还是要说，我这里是没有这个问题的，所以我真的很难去解决这个。不知道原因的时候，有一个通用的方法是试试各种修改，看加载时间会变快还是变慢。但我如果这里改了以后要发一个更新，然后用户收到更新再判断……这不是很现实，尤其是可能速度变化不明显，也有可能有人变快有人变慢。所以我还是觉得给我点时间钻研比较好，等我发现了深层原因再说优化吧。

**Comment by distance00** [comment]
感谢详细解答，又不影响正常使用，慢慢来。也许是我的心理作用吧，感觉加了3个虚拟情景模式时比只加一个稍卡了一点。
