### ISSUE TITLE
无法代理clients2.google.com:443？

### ISSUE THREAD

**Issue by distance00** [FelisCatus/SwitchyOmega#855]
SwitchyOmega中添加了“*.google.com”，但clients2.google.com:443并不走代理。发现chrome在不断尝试连接  chrome.exe *64 - clients2.google.com:443 error : Could not connect to clients2.google.com:443 - connection attempt failed with error 10060
clients2.google.com是chrome的升级服务器，是不是chrome在后台连接SwitchyOmega无法代理？还是我用的代理（goproxy）无法代理443端口所以直接避开了？

**Comment by FelisCatus** [comment]
这只可能是以下三种情况之一：

1: SwitchyOmega 并没有对此请求使用代理。要验证这个很简单，首先确认选项中添加了此规则，类型为域名通配符。然后在菜单中选择自动切换。然后只需要在新标签页下打开`https://clients2.google.com`这个网址即可。此时确认图标颜色（或将鼠标悬停在图标上），即可得知此域名使用的是何种代理，匹配的规则是哪一条。

注意：页面不需要加载成功，是404页面也可以，只要输入网址并回车即可查看图标。

2: 代理服务器问题。这个也可以用类似上面的方法确认，但需要注意的是页面的加载情况。如果是Chrome内置的灰色错误页面并且有网络错误的代码，基本是代理问题。如果是谷歌那个色彩斑斓的机器人坏掉的 404 页面，说明能正常加载网页，代理服务器和SwitchyOmega都设置正确。那么剩下的可能就只有……

3: 更新的网络请求不使用代理设置。比如，更新可能是由独立的进程/模块处理。这个情况下，只有设置系统代理设置（比如 Windows 下 IE 的代理设置）才可能有效。这不是 SwitchyOmega 问题，无法解决。

**Comment by distance00** [comment]
在标签页中打开确定是用代理的，虽然页面不存在。估计可能是第三种情况。感谢详细说明。

**Comment by distance00** [comment]
有的内容比如一些flash不管你怎么设置它都不走代理，系统代理也不行，不知道是网站的flash代码还是浏览器的原因？又或者是代理不支持这些类型的数据传输？

**Comment by FelisCatus** [comment]
@distance00 关于 Flash ，之前有不少报告称其并没有使用 PAC 脚本的设置。由于 Flash 是插件不完全是浏览器的一部分，使用的也是本地代码，所以我猜测 Flash 想做什么就能做什么。比如 Flash 可以绕过 Chrome 的代理设置而只使用系统代理设置。这当然也不是 SO 可以控制的，甚至可能和网页无关而只和 Flash 插件本身的代码（注意：不是网页提供的 Flash 脚本，是执行 Flash 脚本的那个插件）有关。

**Comment by distance00** [comment]
感谢说明，是不是SO最终就是把所有设置转换成一个PAC设置到chrome上？在chrome://net-internals/#proxy上面看显示的是PAC script，后面base64加密的是PAC的位置？
PAC script: data:application/x-ns-proxy-autoconfig;base64
不知道那些flash无法代理是网站的意图，还是adobe的意图？也许有些是网站的意图，有些是adobe的意图？adobe为什么这么设计？背后的原因可能知道的人并不多。
