### ISSUE TITLE
能不能把老版本的在线规则列表功能加回来

### ISSUE THREAD

**Issue by zx09** [FelisCatus/SwitchyOmega#857]
能不能把老版本的在线规则列表功能加回来
现在的版本只有设置更新间隔的功能
老版本可以自由设置在线规则列表的链接
现在新版本我自己就是想改链接也无从改起

**Comment by FelisCatus** [comment]
在线规则列表现在已经集成在自动切换模式中，可以设置链接，也可以手动更新。

请在左侧选择自动切换模式。和设置更新间隔不是在同一个地方。
