### ISSUE TITLE
自动切换情景模式之间实现相互继承或引用

### ISSUE THREAD

**Issue by gy6221** [FelisCatus/SwitchyOmega#858]
有时候会希望在多个自动切换情景模式内复用一部分规则
现在好像只能在两边都写一次这些规则来实现，是否有可能实现自动切换的引用或继承？

**Comment by FelisCatus** [comment]
我的建议是先把公共部分建立一个情景模式为 A ，然后不同的部分分别建立为情景模式 B 和 C. 然后，在 B 和 C 中，将“默认情景模式”设置为 A. 这样就实现了`B->A`和`C->A`的串联。使用时只需选择 B 或者 C 即可。

上面说的方式大概就称为引用，是 SwitchyOmega 新增的配置灵活性，也可以理解成继承，反正怎么都好……我更喜欢理解成电路或者模块或者数据流那种串联操作。至于您所说的是实际上是在规则层面的复用，那个基本是不可能实现的……想想都知道那在用户交互上实在太复杂了……

如果我的建议没有解决问题，建议您详细说说您的用例，我会考虑是否能用已有的功能实现，或者新增其他功能。一个好问题是：为什么需要新建两个不同的、但内容有重复的自动切换模式？

**Comment by gy6221** [comment]
我的使用场景是这样的：
有一部分地址，需要爬墙访问，以下称为A部分
有一部分地址，是公司内网域名，在公司访问需直连，在家无法访问，也用不到，以下称为B部分
有一部分地址，是家中内网的内容，在家访问直连，在公司访问需要挂家里路由上的SS，以下称为C部分
另外，在家访问外网直连即可，在公司访问外网需挂公司出口代理

我希望实现这样的效果：
爬墙部分规则在家里和公司共用，走爬墙SS代理端口
在公司时，访问B部分地址直连，访问C部分地址走另一个SS代理端口，不在规则内的地址，走公司出口代理
在家时，不需要B、C部分规则，访问不在规则内的地址走直连

笔记本在家和在公司的网络环境下切换时，我希望只需要切换一个情景模式

请问在目前已有的功能下，能否实现这样的功能？

**Comment by FelisCatus** [comment]
不是完全不行，只是设置上估计要复杂很多，要用到虚情景。

* 自动翻墙：自动切换模式，包含翻墙规则，如果需要规则列表则设置好规则列表。
   - 需要翻墙的规则（A部分）和规则列表指向翻墙用 SS。
   - 默认规则指向“不翻墙”。
* 不翻墙：虚情景模式，指向直接连接或者“公司环境”。
* 公司环境：自动切换模式，包含内网域名相关内容以及访问家里 SS 所需的内容。
   - 内网相关域名（B部分）指向直连。
   - 家中内网域名（C部分）指向家里路由 SS。
   - 默认规则指向公司使用的代理。

实际使用时，首先在菜单中选中“自动翻墙”，然后无论在何处，都不要选择其他情景模式。这样可以确保无论在何处，翻墙的行为总是保持一致。接下去只需要解决不翻墙的情况了。

然后，在菜单中允许选择虚情景模式指向的目标。在公司时，将“不翻墙”指向“公司环境”。在家时，将“不翻墙”指向“直接连接”。

**Comment by FelisCatus** [comment]
用流程图或者判定树就很容易表达这种逻辑，比如说：

1. 该网址是否需要翻墙(A)？是：使用翻墙SS。否：继续下一步。
2. 是否处在家中？是：使用直接连接。否：继续下一步。
3. 是否是公司内网域名(B)？是：使用公司代理。否：继续下一步。
4. 是否是家中内网域名(C)？是：使用家中代理。否：使用公司代理。

这样的话就可以看到，很明显第2步需要手动指定，可以使用虚情景模式来指定直接连接还是公司环境。其他几步都是自动处理，使用自动切换规则功能。第一步就是我所说的“自动翻墙”模式，第三、四步骤就是我所说的“公司环境”模式。当然如果你愿意每一步都建立一个情景模式也没关系啦。

从这个分析也可以看出，如果有办法可以自动判定是在哪个环境中，就不必使用虚情景模式了，所有步骤都可以在一个自动切换情景模式中完成。但这个确实没什么可靠的判定方式……一个思路是利用 IP 地址，但此功能尚未实现。见 #197.

**Comment by TotooriaHyperion** [comment]
@FelisCatus 你好作为开发者，经常需要挂代理来解决跨域问题。
所以经常会出现这样一种情景，
有A,B,C,D一共4套用于不同项目互不冲突的配置，但有时需要单独关闭其中1个配置来访问线上文件/接口。
有E,F一共2套用于不同项目的相互冲突的配置。
显然在实际使用中国呢会选择E/F配置，并配置格子的默认模式为E->D->C->B->A和F->D->C->B->A
未来还可能有与其他配置互不冲突的G配置。
这时候就要设置G->D，E->G，F->G
随着冲突配置的增多，每次修改公共配置都需要修改整个继承链。
而且也没办法对公共配置中对某些配置进行暂时对禁用。

所以是否可以支持以 组合 而不是 继承 的形式来配置代理？优先级由配置顺序来决定，而不是继承顺序。
就像SwitchHosts!一样。

**Comment by FelisCatus** [comment]
@TotooriaHyperion 抱歉了，这个当初就是这么设计的，现在很难做一个不向后兼容的大改版。我觉得一次性禁用一个情景模式的所有规则倒是也许可以做。

有一个临时的办法就是把经常需要开关的一部分规则放进规则列表，然后需要关闭的时候在情景模式里把“规则列表”的勾去掉就行了。希望这样能至少稍微简化下操作……
