### ISSUE TITLE
HTTPS的网址规则失效了？

### ISSUE THREAD

**Issue by vvyoko** [FelisCatus/SwitchyOmega#859]
同一规则在HTTPS下失效而在HTTP下有效是什么原因？
1,URL:https://c2.staticflickr.com/8/7418/12548365914_675a0a269e_h.jpg
无效网址正则^https:\/\/c2\.staticflickr\.com\/.*_h\.jpg

2,URL:http://c2.staticflickr.com/8/7418/12548365914_675a0a269e_h.jpg
有效网址正则^http:\/\/c2\.staticflickr\.com\/.*_h\.jpg

3,URL:https://c2.staticflickr.com/8/7418/12548365914_675a0a269e_h.jpg
有效网址正则^http:\/\/c2\.staticflickr\.com   (问题是这不就变成域名正则了吗？)

Chrome版本: cent 版本 2.0.10.57 (portable) (Chromium 52.0.2743.116)
360极速的50内核几种都有效，怀疑是否是内核改了？

**Comment by FelisCatus** [comment]
感谢报告，这是 Chrome 的修改，具体细节见 #845.
