### ISSUE TITLE
Disk busy after add SwitchyImega into chromium

### ISSUE THREAD

**Issue by Wtango** [FelisCatus/SwitchyOmega#861]
After add SwitchyOmega in to chromium, my chromium goes jam with a short time use, and the disk works busy. 

I use a local ssh proxy at 127.0.0.1:12345.

SwitchyOmega 2.3.19
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/51.0.2704.79 Chrome/51.0.2704.79 Safari/537.36

**Comment by xlfjn** [comment]
Please refer to #815. It's a known bug.

@FelisCatus Maybe reopening #815 is a good idea.

**Comment by FelisCatus** [comment]
Are you using Auto Switch? When exactly does the disk usage goes up? Does restarting Chromium help?

**Comment by Wtango** [comment]
@FelisCatus ,中文也OK吧。应该是跟#815的问题一样的，使用Auto Switch的情况下chromium占用了大量的内存，导致使用swap分区，导致硬盘也忙碌了。什么时候能修复这个问题，或者有什么workaround的办法。

**Comment by FelisCatus** [comment]
应该是 #815 了，只能等 Chrome 修复。
