### ISSUE TITLE
Condition for 3rd party domains?

### ISSUE THREAD

**Issue by cwilliams5** [FelisCatus/SwitchyOmega#862]
First, thanks for your amazing plugin. It's an important part of my internet privacy.

Second, would it be possible to have a condition for 3rd party domains? That way I can send them to a different proxy to make tracking/fingerprinting more difficult. So if

page on example.com loads resources from:
example.com
cdn.example.com
adcompany.com
trackingcompany.com
javascript.trackingcompany.com

I can send the first party resources (example.com and cdn.example.com) to one proxy, and all the third parties to another.

A simple condition that just checked if the host of the requested resource was different then the host of the origin page would work wonders here I think.

**Comment by FelisCatus** [comment]
Information about tab, windows, documents and origins are not available to PAC scripts and thus cannot be used in SwitchyOmega. Please understand this is a technical limitation and we cannot do anything about it no matter how helpful that could be.

**Comment by cwilliams5** [comment]
Thanks for taking the time to respond, and thanks again for your work on such a useful extension. I wasn't aware of that limitation with PAC scripts. I know of other extensions that do make decisions based on origins so I was thinking it might work. Thanks again.
