### ISSUE TITLE
Image decode failed -安装一直失败

### ISSUE THREAD

**Issue by skybusy2000** [FelisCatus/SwitchyOmega#863]
安装失败  重试多次后一直提示 Image decode failed

**Comment by norci** [comment]
应该是 store 里某些东西被墙了。

**Comment by FelisCatus** [comment]
试试看从 Github 下载安装包？ https://github.com/FelisCatus/SwitchyOmega/releases

**Comment by skybusy2000** [comment]
被墙了~~ 后来添加了google所有的域名就好了

**Comment by youcailize** [comment]
终于解决了。。。之前是各种装google老版本。原来是墙的问题

**Comment by KrasnayaPloshchad** [comment]
这个问题也影响到了 [Advanced Font Settings](https://chrome.google.com/webstore/detail/advanced-font-settings/caclkomlalccbpcdllchkeecicepbmbm)，而且我已经安装了 SwitchyOmega，不过我发现就算开了全局代理照样出问题。

**Comment by KrasnayaPloshchad** [comment]
测试了一下，好像跟一个 inf.pub 这个域名有关系。

**Comment by Ruth-Seven** [comment]
我也遇到了 很疑惑

**Comment by Ruth-Seven** [comment]
开了全部代理 ，总算可以访问了

**Comment by yxwoaiy** [comment]
*.googleusercontent.com 把这个域名墙了 翻过去就好了

**Comment by badtoken** [comment]
> *.googleusercontent.com 把这个域名墙了 翻过去就好了

加到pac里了，甚至开了全局代理，仍然不行。。。显示Download interrupted

**Comment by jerrychien** [comment]
确实是墙的问题，开了全局代理就可以了
