### ISSUE TITLE
remote DNS for socks5 proxy?

### ISSUE THREAD

**Issue by norci** [FelisCatus/SwitchyOmega#864]
Remote DNS is really helpful.
But SwitchyOmega does not support it.
So I can't use it.

**Comment by celeron533** [comment]
I remember that socks5 already support DNS which socks4 does not.

PS.
in default settings, Chrome enabled the DNS preload and cache. If your browser already sent the DNS request before apply the proxy, the 'wrong' DNS result will be cached. Please disable it in the Chrome settings.

**Comment by FelisCatus** [comment]
Remote DNS is already supported by Chrome. There's one particular issue that you wish to learn more about in order to ensure fully predictable remote resolution: https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy

**Comment by SiberMedya** [comment]
firefox bowser have this setting own proxy page: network.proxy.socks_remote_dns
SwitchyOmega not work with Bitvise ssh

**Comment by QGB** [comment]
using `socks5h://`

socks5 remote resolving.
