### ISSUE TITLE
AutoSwitch DNS leaks

### ISSUE THREAD

**Issue by whitematrix62** [FelisCatus/SwitchyOmega#867]
When autoswitch is in use, dns leaks would occur.
however when proxy is explicitly selected, there'll be no dns leaks. 

Tested with a sock5 proxy.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by FelisCatus** [comment]
Are you looking for this? https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy

If the solution does not work for you, please report to the Chromium project because SwitchyOmega is only a configuration tool and has absolutely no control over DNS.

**Comment by whitematrix62** [comment]
It's not the same issue. The DNS leak does not occur when using SwitchyOmega in Proxy mode. 

But it only happens when using SwitchyOmega in Auto mode. 

If it was happening because of DNS caching then it should leak the DNS regardless of the mode that SwitchOmega is in. The leak is specific to the way how the Auto mode is handled.

**Comment by whitematrix62** [comment]
Disabled DNS prefetching and i get the the same results. Leak in Auto Mode, No leaks in Proxy Mode.

**Comment by FelisCatus** [comment]
In that case, I would like to know a few things on this.

1. What is the leaked domain name?
2. What are the rules? Specifically, does the rules send the request in question to proxy or direct?
  * If the leaked request is a web page, you can tell from the color of the SwitchyOmega icon. You can also hover on the icon to see which rules are in effect.
  * If the leaked request is an embedded resource in some page, please copy & paste that URL into the browser address bar, hit Enter and follow the instructions above.

Please note that SwitchyOmega select proxy servers on a per-request basis, where every single resource is independently checked against all rules. Even if the page URL of a tab seems to be proxified, the resources (images, scripts, etc.) can still go direct. If this is your case, you need to add those resources manually into rules.

From what I know and what I observe, Chrome is using remote DNS when DNS prefetching is completely disabled. That means you get either direct DNS resolve + direct connection or proxified DNS resolve + proxy connection. Therefore, I suggest double checking that all requests indeed go through the proxy before reporting any leaks here or to the Chromium project.

**Comment by whitematrix62** [comment]
You are absolutely right. I relooked at the resources again and indeed they are serving from more than one domain.  So although the page appears to be proxied, some elements are still served directly from other domains. I have added them manually and the leaks in Auto mode has stopped. 

To prevent this, may i suggest a new persistent auto proxy mode? So once it has auto proxied based on defined triggers, it will stay in proxy mode for the current tab and all children tabs?

**Comment by FelisCatus** [comment]
Sorry, tab information is not available for PAC scripts and thus cannot be implemented in SwitchyOmega. I might want to create a FAQ page in the project wiki so people don't keep asking for this...

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/18575624/6e7a42a0-7c0c-11e6-8297-aff01b9b18df.png)

**Comment by meffect** [comment]
Would the best practice here to prevent this be to have the Auto Switch "Default" action be a proxy instead of direct?

**Comment by FelisCatus** [comment]
I would say yes if you care about privacy. Even if you do not have a proxy, a squid server running on your local machine would still give you better control on the protocol level. A customized DNS server (or dnscrypt) would also help.
