### ISSUE TITLE
几个中文网址无法访问

### ISSUE THREAD

**Issue by anuxs** [FelisCatus/SwitchyOmega#868]
http://cn.nytimes.com/
http://cn.reuters.com/
http://cn.nikkei.com/top.html
http://asahichinese.com/

这几个网址无法访问。切换了代理也无法访问。代理在全局模式下，是可以访问的。

SwitchyOmega 2.3.19
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36

**Comment by zdzliqian** [comment]
可以访问啊

**Comment by FelisCatus** [comment]
……如果要汇报规则列表问题，请到对应的规则列表（多半是 gfwlist）那边反馈。

如果是自己使用的话，请打开这些网址并观察图标上显示的数字，以确定是否有其他资源未加载。点击弹出菜单中的黄色项目可以批量对于这些资源添加规则，然后刷新。反复数次后应该就可以访问了。
