### ISSUE TITLE
*.google.com不包括www.google.com？

### ISSUE THREAD

**Issue by distance00** [FelisCatus/SwitchyOmega#869]
只加入`*.google.com`这个规则，进入
`http://generatorlinkpremium.com/`
点I'm not a robot前的框，不弹出验证。
加入`*www.google.com`，再试，可以正常弹出验证。
还遇到过别的例子，不过重现比较麻烦。

**Comment by distance00** [comment]
只加.google.com，很可能都看不到I'm not a robt，我现在看到的可能是缓存。

**Comment by distance00** [comment]
奇怪星号在帖子里看不到。***

**Comment by distance00** [comment]
是拷贝字体带过来了的原因？
只加入.google.com这个规则，进入
http://generatorlinkpremium.com/
点I'm not a robot前的框，不弹出验证。
加入www.google.com，再试，可以正常弹出验证。
还遇到过别的例子，不过重现比较麻烦。

**Comment by distance00** [comment]
和*www.google.com

**Comment by FelisCatus** [comment]
是域名规则吗？求一个自动切换的截图，或者导出 PAC 文件，或者导出的备份文件……

**Comment by distance00** [comment]
是域名通配符。不知道截图有什么用。能否按我一楼说的试下能否重现？在一个自动切换规则中试下两个规则的区别，用不了一分钟。

**Comment by FelisCatus** [comment]
抱歉，我按照你说的试过了多次，情况都无法复现。这种情况建议导出 PAC 文件或者备份文件，这样可以直接确认生成的脚本是否符合期望。如果没有这个我很难调试。

以及，这个页面上要加载出来验证码，需要很多资源，除了 `*.google.com` 之外还有 `*.gstatic.com`, `*.doubleverify.com` 等，建议都添加试试看。以及，加载不出时请关注扩展图标上出现的黄色数字，点击可查看未加载的资源列表，有助于分析问题。

每个人的网络环境都有所不同，我能做的只有帮助您在您那边分析问题，或者直接检查 SwitchyOmega 的切换逻辑是否正确。请谅解。

**Comment by FelisCatus** [comment]
因为无法重现，暂时关闭了。如有问题请评论并重新开启。
