### ISSUE TITLE
你好，关于自动切换

### ISSUE THREAD

**Issue by liuzengming** [FelisCatus/SwitchyOmega#87]
只要第一次登陆的网站都是自动切换到goagent，除非手动直连；还有就是点按钮无法给网站添加新规则，而且选项没有直连。请问上述问题怎么解决。。小白一个，请指教。

SwitchyOmega 2.2.7
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
这个 issue 已经很久都没有回复了，我准备先关闭了。如果还有问题，请留言并点击 reopen 按钮重新开启。
