### ISSUE TITLE
Add supports for geoip configuration

### ISSUE THREAD

**Issue by swj1442291549** [FelisCatus/SwitchyOmega#870]

**Comment by celeron533** [comment]
SO的核心还是根据用户选择的profile生成pac文件交给浏览器处理。
目前主流浏览器均不支持geoip特性。若是每次都由SO根据geoip动态生成pac的话，系统开销较大。

**Comment by FelisCatus** [comment]
SwitchyOmega is a proxy switching tool. It does not perform DNS resolution and cannot switch based on remote IP. There is no way to tell the geolocation based on just the URL.

What you are looking for is VPN, iptables or similar low-level mechanisms.
