### ISSUE TITLE
与阿呆猫配合使用的问题

### ISSUE THREAD

**Issue by mayhuny** [FelisCatus/SwitchyOmega#871]
阿呆猫中有智能[科学上网]，将阿呆猫的规则列表做好导入SwitchyOmega，大约2k3条，此时SwitchyOmega变的卡顿，这么做的目的是可以[科学上网]，可以去广告；

将阿呆猫的规则做好放入SwitchyOmega，然后将这些规则指定到虚情景模式，不用阿呆猫时还可以走其他模式；

但是这么做有一个问题：阿呆猫的规则列表有2k3多个，导入后扩展反应太慢，更改设置时会变的特别慢；

实际使用的流程图：
浏览器----|--SwitchyOmega--阿呆猫-->可以[科学上网]，但不可以去广告
|>---------|--阿呆猫-->可以[科学上网]，可以去广告

大家有更换的解决办法吗？

**Comment by FelisCatus** [comment]
去广告？我不太清楚这个是什么……

如果导入的是自动切换规则，我感觉 2k 以上确实没什么办法，可以试试看用源代码视图，会快不少。然后还不行的话可以多建几个自动切换。再不行的话，用规则列表功能吧。

如果用的就是规则列表，还卡，那么抱歉，这可能真的没什么办法了。其实吧，我之前也这样，于是我买了个新电脑……

**Comment by mayhuny** [comment]
我的电脑配置不差啊，CPU 是i7-4700，实际使用上不卡，就是点击选项进行配置时很卡。是否需要我将配置导出一份给您试试？

在 2016年9月11日 上午11:29，Felis Catus <notifications@github.com>写道：

**Comment by FelisCatus** [comment]
2k3 个规则都在切换规则一节中以表格、文本框和下拉框的形式显示吗？如果是的话，我还是建议平时就开着编辑源代码这个功能，会快很多。关于图形界面我没有任何办法，毕竟网页性能大致如此。 CPU 可能大家都不是特别差，但网页性能受内存和显卡影响比较多。

如果使用的是规则列表功能来保存2k规则，但仍然遇到明显卡顿，请及时告知。

**Comment by chshouyu** [comment]
用React重写界面会不会快一些<(▰˘◡˘▰)>

**Comment by FelisCatus** [comment]
@chshouyu 说不定可以……不过在页面元素太多的情况下，估计能优化的还是很有限。

**Comment by FelisCatus** [comment]
先关闭这个了。之后再考虑优化吧……
