### ISSUE TITLE
谷歌学术使用Shadowsocks在启用 Proxy SwitchyOmega的时候无法访问

### ISSUE THREAD

**Issue by saccohuo** [FelisCatus/SwitchyOmega#872]
使用Shadowsocks作为代理，启用Proxy SwitchyOmega的时候不能访问谷歌学术，但是禁用掉之后可以正常访问谷歌学术。使用Firefox浏览器也可以正常访问。

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by johnhuo** [comment]
其他的网站呢？能否访问？
尝试关闭ss系统代理，在启用SO试下…

2016年9月6日 下午4:32，"husky" <notifications@github.com>写道：

**Comment by saccohuo** [comment]
其他网站两种情况x 都可以访问。
我一直没有开SS系统代理的，Chrome里面是通过SO来设置，外面的程序走Proxifier。

**Comment by FelisCatus** [comment]
我先问问看使用全局代理模式也不能访问，还是只有自动切换不能访问？如果只有自动切换，请检查菜单中提示的未加载资源，并逐个加入自动切换，然后刷新，反复数次后应该可以解决。如果 GFWList 没有包括这些规则，那么请去那边反馈。

如果全局代理模式也不能访问，这多半是 Chrome 自己的 SOCKS 实现和 Proxifier 的差异，和 SwitchyOmega 无关。首先建议您根据[这里的说明排除 DNS 泄漏](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87)，以回避 DNS 污染、劫持等情况。如果情况仍然持续，那么我对于网络底层的理解不足以帮助您解决这个问题，建议去各种相关论坛询问，或者在能确保最小重现的情况下去 Chromium 项目反馈。
