### ISSUE TITLE
Could you please make Chrome stop using IPv6 with SOCKS5 proxy server?

### ISSUE THREAD

**Issue by citbr** [FelisCatus/SwitchyOmega#875]
I was using SwitchySharp but upgraded to SwitchyOmega and it still didn't resolve this issue.  If I go to a site such as ipchicken.com or whatismyip.com using a SOCKS5 proxy, it reports the address back in IPv6 format.  This is something that just recently started happening in Chrome.  If I go to those sites using ANY other browser it still reports the IPv4 address, which is the address I want it to use.  Is there any way in SwitchyOmega to force Chrome to use the IPv4 address?  I don't really understand why this happens but it's definitely a different result when I go to those sites in Chrome vs. when I got to them in Firefox or Opera.  Also if I don't use a SOCKS5 proxy then those sites report my current IPv4 address.  They only seem to report an IPv6 address when I use a SOCKS5 proxy via SwitchySharp or SwitchyOmega in Chrome. Using the IDENTICAL SOCKS5 proxy from Firefox reports the correct IPv4 address of the proxy.

**Comment by wtlusvm** [comment]
It seems that is because the proxy server you use has at least one IPv6 address. And, of course, ipchicken.com and whatismyip.com has its IPv6 address. Both side would use IPv6 protocol preferentially when send a HTTP request. And would you double check if ipchicken.com reports the IPv6 address of PROXY SERVER when you use a SOCKSv5 proxy in other browsers?

**Comment by citbr** [comment]
In Firefox, configured to use the same SOCKS5 proxy I am trying to use from Chrome, it reports the IPv4 address, not the IPv6 address, which is also how Chrome with SwitchySharp worked until recently. I made sure that IPv6 is disabled on my computer but that apparently makes no difference.  I know the SOCKS5 proxy idoes support IPv6 (and has for quite some time) but still, until recently both Firefox and Chrome were able to use IPv4 through it.  SOMETHING has changed in Chrome recently, and I am not saying it's the fault of your software, but rather I am asking if SwitchyOmega can force an IPv4 connection through the proxy, in the same way Firefox apparently does.  I don't know how Firefox does it, but when you set it to use a SOCKS5 proxy, even if the proxy is IPv6 capable, ipchicken.com still sees the IPv4 address.  And that is what I want.

I know that there is no IPv6 traffic between my computer and the proxy because my router is definitely not IPv6 capable.  And I would be very worried if it were, because there's no firewall protection for IPv6 in the router.

**Comment by FelisCatus** [comment]
SwitchyOmega has no control over DNS resolution. Please report all net-internals related issues to the Chromium project.

Plus, I highly doubt that the Chromium project will entertain such feature requests, since they officially removed the option to disable IPv6 some time ago.
