### ISSUE TITLE
规则列表规则不生效

### ISSUE THREAD

**Issue by MythHack** [FelisCatus/SwitchyOmega#876]
我测试的域名是http://zalmos.com/
![11](https://cloud.githubusercontent.com/assets/7798759/18500347/503dea6a-7a79-11e6-8b3c-a4883f06b124.png)
![22](https://cloud.githubusercontent.com/assets/7798759/18500351/562556d4-7a79-11e6-94b8-4efa39ca862b.png)
![33](https://cloud.githubusercontent.com/assets/7798759/18500353/59918388-7a79-11e6-9f57-f85b364f878b.png)
![44](https://cloud.githubusercontent.com/assets/7798759/18500354/5c7deb54-7a79-11e6-94a9-872b88ee274d.png)

**Comment by FelisCatus** [comment]
`.zalmos.com`这条规则的语义是什么样的？和`zalmos.com`有什么区别？

目前 SwitchyOmega 是根据 AutoProxy 的说明文档，实现成 URL 为 HTTP 且包含 `.zalmos.com` 字符串。所以 `http://zalmos.com/` 不包含开头的 `.`，不生效。我觉得这个实现应该是正确的，否则没必要有`.example.com`和`example.com`两种规则。如果有其他资料说需要特殊实现，请告知。

您也可以去 gfwlist 反馈 `.zalmos.com` 不匹配 `http://zalmos.com/` 而后者被墙。如果那边那边项目维护者答复本意就是匹配，那么我就跟着那边的说明改。

**Comment by FelisCatus** [comment]
我这边还是准备暂时认定这两种规则是不同的。先关闭这个了，如果 gfwlist 那边有任何格式说明我会据此修改。
