### ISSUE TITLE
使用HTTPS代理时登录chrome账户会导致Chrome崩溃

### ISSUE THREAD

**Issue by samuelts** [FelisCatus/SwitchyOmega#877]
当连接HTTPS代理时，点击登录Chrome，登录的小方框会弹出来，但是那个页面没显示出来chrome就直接崩溃（闪退）了。
http代理，socks4/5代理均无此问题

操作系统：`Win10 Pro 1607 (64-bit)`
Chrome：`53.0.2785.113 m (64-bit)`
SwitchyOmega: `2.3.19 (Github版)`

**Comment by FelisCatus** [comment]
此问题和 SwitchyOmega 无关，请将崩溃报告提交到 Chromium 项目。
