### ISSUE TITLE
Proxy authentication is supported?

### ISSUE THREAD

**Issue by enervated** [FelisCatus/SwitchyOmega#878]
I see the release notes that state "Proxy authentication (username & password) is now supported." But ... how? I don't see anywhere to enter proxy creds.

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by celeron533** [comment]
![image](https://cloud.githubusercontent.com/assets/3608762/18575630/7f05c73e-7c0c-11e6-9ada-a19981aba995.png)

**Comment by enervated** [comment]
Thanks, but I do not have that icon.

![image](https://cloud.githubusercontent.com/assets/11533799/18586081/bf3ab7d4-7be8-11e6-8f5e-46ee2df3f7de.png)

**Comment by celeron533** [comment]
Hi @enervated
Please refer to #291 & #659

**Comment by enervated** [comment]
Well, that sucks.

I'm sorry to duplicate issues like an idiot. Thank you very much.
