### ISSUE TITLE
能否对整个页面应用情景？

### ISSUE THREAD

**Issue by Nifury** [FelisCatus/SwitchyOmega#879]
您好，不知道chrome是否提供了这样的API可以对这个页面产生的所有连接应用情景模式呢？

比如我访问youtube，只要设置*.youtube.com，之后的*.ytimg.com，*.googlevideo.com等都会自动应用指定的情景，而不用自己手动一个个设置呢？

**Comment by FelisCatus** [comment]
由于PAC脚本限制，无法得知标签页、请求的资源属于哪个页面等信息，所以无法实现此功能。
