### ISSUE TITLE
socket5代理不成功

### ISSUE THREAD

**Issue by tzw0745** [FelisCatus/SwitchyOmega#880]
![](http://i1.piimg.com/567571/cd20d92a3be1d509.jpg)
![](http://i1.piimg.com/567571/007483a3aeb50d42.jpg)
![](http://i1.piimg.com/567571/c7d9a24c24403a33.jpg)
用ProxyChecker可以正常识别socket5代理，用Proxifier也可以全局代理，用swithyomega却不能代理

**Comment by FelisCatus** [comment]
请在地址栏中输入`chrome://net-internals/#proxy`回车，并将页面上的文字复制到这里。
此外，请参考 #557.

**Comment by tzw0745** [comment]
proxy模式
```
Effective proxy settings

Proxy server for everything else: socks5://127.0.0.1:1082
Bypass list: 
  127.0.0.1
  ::1
  localhost
```

**Comment by tzw0745** [comment]
本来我是不报希望了，抱着试一试的心态卸载了迅雷7（迅雷极速版）并重启，然后就可以代理了。WTF？？？迅雷这是什么鬼？？？多谢作者大大！！

**Comment by celeron533** [comment]
https://github.com/FelisCatus/SwitchyOmega/issues/557#issuecomment-131293097
