### ISSUE TITLE
pac内容无法更新

### ISSUE THREAD

**Issue by snoopygao** [FelisCatus/SwitchyOmega#881]
pac内容在服务端更新后在客户端更新还是原来的内容

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by feizhenzhuang** [comment]
貌似 gfwlist作者把列表内容清空了，

**Comment by celeron533** [comment]
现在似乎已经补回

**Comment by FelisCatus** [comment]
感觉你们和OP说的不是同一个问题吧？OP说的是 PAC 脚本，不是规则列表的更新。

我感觉更像是缓存引起的，可以试试看在 PAC 的 URL 之后增加 `?_=1234` 之类的再点更新，看看是否能绕过缓存。请尽量确保在选项页面点击“立即更新脚本”按钮，这样如果有任何错误会提示。

如果手动更新成功，但似乎没有自动更新的话，那么请检查选项>通用里的更新间隔（默认12小时），可以改短一点。此外还可以在弹出菜单中反复选取 PAC 情景模式（即在已经选中的情况下再次选取），也会触发后台更新。

**Comment by snoopygao** [comment]
@FelisCatus 所以上边几位的留言我不知道该怎么回复，这个问题一直存在，确实是缓存的问题，回头我再试一下你提供的方法，我删除之后等了一天重新添加后更新才不再出现原来的内容，感谢回复
