### ISSUE TITLE
auto switch profile not remote dns on sock 5.

### ISSUE THREAD

**Issue by TheOneWhoKnock** [FelisCatus/SwitchyOmega#882]
auto switch profile not remote dns on sock 5.
i use URL wildcard.
thank you for your work 👍 

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.27 Safari/537.36

**Comment by FelisCatus** [comment]
Hi, please see the following link for details.

https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy
