### ISSUE TITLE
今天不知道为什么不能访问XXnet的设置页http://127.0.0.1:8085/

### ISSUE THREAD

**Issue by h411879** [FelisCatus/SwitchyOmega#883]
SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by FelisCatus** [comment]
……这应该不是 SwitchyOmega 的问题。先关闭了。
