### ISSUE TITLE
希望增加 [需要代理的地址列表] 这个选项

### ISSUE THREAD

**Issue by Landius** [FelisCatus/SwitchyOmega#884]
因为在实际使用中，有一部分人一般都是只上固定的一些网站，比如 Google YouTube 之类的，如果只能设置不代理的地址的话，就很不方便了。

**Comment by celeron533** [comment]
可以指定特殊地址走代理
![image](https://cloud.githubusercontent.com/assets/3608762/18820363/838c320a-83cf-11e6-9b62-087eade88783.png)

**Comment by Landius** [comment]
嗯，我也发现了，其实还可以这样……
![issue](https://cloud.githubusercontent.com/assets/11910028/18820614/ae43358c-83d1-11e6-8c0c-a382814e5410.PNG)

**Comment by FelisCatus** [comment]
这里还有问题吗？先关闭了，如果还有其他建议请提出。
