### ISSUE TITLE
如何设置当DNS查询失败时, 自动走proxy

### ISSUE THREAD

**Issue by Fezreal** [FelisCatus/SwitchyOmega#887]
如题

**Comment by celeron533** [comment]
我一般还是手工添加常用站点的。DNS临时抽筋、污染等情况不能很智能的判断出来。

**Comment by Fezreal** [comment]
@celeron533  iOS新出了一个叫 wingy 的东西, 自动规则模式下就是用 DNS 来判断是是否需要翻墙, 效果十分的好. 比 surge 和 shadowrocket 那种规则写死的模式 要优秀很多.

**Comment by celeron533** [comment]
@Fezreal 两者的性质不一样。switchyOmega只是一个代理切换工具，且目前只能运行在chrome的沙箱之中，无法接触浏览器之外的环境，也无法接触系统底层。DNS的判断不仅仅是连通性的检测，也要检测返回的DNS是否被篡改（比如同时再对翻墙代理发送DNS请求，然后对比是否一致，不一致的话则翻墙。但需要考虑CDN、反代、BGP策略路由等多种复杂情况）等等，对于switchyOmega来说有些超出范围。请记住，switchyOmega只是一个代理切换工具，虽然很多翻墙用户（包括我）都是用这个工具个来切换代理，但这并不意味着switchyOmega就是个翻墙工具。
shadowsocks则是实现他们的隧道算法，也有人提出为何不加入用户数据库实现多用户、多登陆、流量配额等等，shadowsocks表示他们只关注最核心的功能，反正代码也是开源的，外围特性让其他人来实现。

**Comment by FelisCatus** [comment]
SwitchyOmega 不是翻墙软件，也不涉及代理协议。这个功能估计浏览器扩展是做不到了，先关闭了。
