### ISSUE TITLE
 无限循环重定向

### ISSUE THREAD

**Issue by fuyou001** [FelisCatus/SwitchyOmega#888]
最近升级macOS后，访问slideshare，好像是无限循环重定向，导致失败。不知道是不是代理插件的问题？

**Comment by celeron533** [comment]
禁用代理后还有吗？？？

**Comment by fuyou001** [comment]
禁用代理不能访问slideshare了，版本信息如下

chrome 版本 53.0.2785.143 (64-bit),OS macOS sierra 10.12

**Comment by celeron533** [comment]
目前我访问http://www.slideshare.net/没有问题

**Comment by fuyou001** [comment]
你的版本是多少，插件也会有版本吗

**Comment by celeron533** [comment]
SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

可能是你的代理服务器那端出了问题

**Comment by FelisCatus** [comment]
这应该是服务器问题， SwitchyOmega 不修改网络请求，自然也就不能导致重定向。
