### ISSUE TITLE
求如何保持“自动切换”，不要再变成“外部情景模式”了

### ISSUE THREAD

**Issue by AKB48kojima** [FelisCatus/SwitchyOmega#890]
我一直都是用“自动切换”的，一直都很好，但是最近不知道怎么的，总是变成“外部情景模式”。我把情景模式改回自动切换，用着用着又变成情景模式。隔那么半个小时左右又就变成“外部情景模式”，搞的网页都不能正常打卡，求固定自动切换。

**Comment by FelisCatus** [comment]
感觉像是和其他扩展有冲突的情况……“外部情景模式”指的就是其他扩展提供的设置。

建议逐个排查新安装的扩展并禁用冲突的扩展。或者重装 SwitchyOmega 也可以提高其优先级（根据 Chrome 的规则，后安装的优先，我也没有办法）。
