### ISSUE TITLE
【求增加功能】：自动通过代理重新加载打不开的页面

### ISSUE THREAD

**Issue by redstoneleo** [FelisCatus/SwitchyOmega#891]
即便是GFWlist也无法前面覆盖被qiang的所有网址，所以我在xx-net的自动切换模式下面经常遇到打不开的网页这时候只有手动切换到代理模式才能打开网页，这有点麻烦了！
建议：自动通过代理重新加载打不开的页面，这样就可以免去上面的麻烦。

**Comment by celeron533** [comment]
有一定的问题，比如提交表单的时候，提交目标由于有敏感内容被墙，此时切换代理不应自动刷新，否则填写的表单内容会丢失。
你可以再新建一个switch profile，然后在里面添加规则
![image](https://cloud.githubusercontent.com/assets/3608762/19231763/60ea50ac-8f0e-11e6-87e9-0d03f473cd23.png)

**Comment by redstoneleo** [comment]
@celeron533 
1 网站打得开提交表单被墙的情况应该非常少见吧？
2 xx-net自动切换的规则来自  https://github.com/gfwlist/gfwlist

**Comment by FelisCatus** [comment]
见 #550.

**Comment by redstoneleo** [comment]
（1）通过chrome extension可以实现下面这个功能吗？
当浏览器开始尝试打开地址栏里的url时，比如5s后还无法收到该url对应的response或者是404，那么我们就开始启用代理尝试去打开这个url
（2）我看了其他几个相关的issue，发现似乎只能有一个extension去控制chrome的代理，而不允许多个extension并列控制代理，那么SwitchyOmega是否有相关的对话接口方便其他的extension发消息来通知它切换代理模式呢？

**Comment by FelisCatus** [comment]
(1) 不能
(2) #44

**Comment by redstoneleo** [comment]
@FelisCatus 大神可以解释下（1）问为什么行不通吗？

**Comment by FelisCatus** [comment]
@redstoneleo 这个问题要解释清楚需要花很多时间，涉及很多代理和扩展的实现细节。

这里简单说一下，代理设置是作为一个脚本提供给 Chrome 的，执行时对于每个 URL 返回一个代理服务器地址。不能控制网络请求发送/接受。不能指定超时时间。不能重试。

如果想了解更多请查阅扩展开发文档等相关资料。
