### ISSUE TITLE
Question - automate the setup process

### ISSUE THREAD

**Issue by mvalitov** [FelisCatus/SwitchyOmega#892]
Hello, for me the problem is to install it and enable it on a group of browsers. Hence the question - whether it is possible to automate the process? For example through the entry in the folder with the settings and the like. No download PAC file settings

**Comment by FelisCatus** [comment]
Hi, SwitchyOmega cannot read any file from your hard disk you did not select.

On way to do this is to export a backup file from one computer you've already set up. Then you can use the Import Backup feature in Options > Import/Export to load all settings from a local file or over the internet. It's not fully automated, but it should save you some time creating profiles and adding rules.

Another way would be using the Sync feature and login one Google account on every computer. Chrome will automatically install SwitchyOmega and fetch the settings from the first computer you've set up. After the process is complete, you can safely sign out your account without losing the settings.

Please let me know if you have better proposals.

**Comment by FelisCatus** [comment]
Closing for now. Let me know if you need any new feature.
