### ISSUE TITLE
https代理证书被吊销问题

### ISSUE THREAD

**Issue by PhantomThief** [FelisCatus/SwitchyOmega#893]
rt. https代理证书被吊销后连接不上。有办法忽略么，比如绕过chrome内置的CRLSet依然连接。

备注：不是网站的证书被吊销，而是https proxy的证书被吊销。

**Comment by FelisCatus** [comment]
据我所知 Chrome 没有给扩展提供任何接口来忽略证书检查。因此即使有解决方案，应该也只能在 Chrome 上操作而无法在 SwitchyOmega 实现。先关闭了。
