### ISSUE TITLE
Adding to chrome will face with error

### ISSUE THREAD

**Issue by rezanos** [FelisCatus/SwitchyOmega#895]
Hi,
Adding to chrome faces with this error:

![image](https://cloud.githubusercontent.com/assets/4385854/19408802/a2852ac4-92d2-11e6-855c-da9fc8c99b23.png)

**Comment by FelisCatus** [comment]
Hi, please [download a copy of SwitchyOmega installer on Github](https://github.com/FelisCatus/SwitchyOmega/releases) if you have trouble accessing Chrome Web Store.

Please pay close attention to the installation instructions for CRX files.
