### ISSUE TITLE
有些网页第一次打开跳转到百度页，提示您访问的页面不存在

### ISSUE THREAD

**Issue by Arcoa** [FelisCatus/SwitchyOmega#896]
最近用xxnet的时候，第一次打开有些链接会跳转到baidu页面，提示：很抱歉，您要访问的页面不存在！，重新点击该链接后可正常打开网页。我确定是xxnet的原因，因为当我用xxnet自动切换（问题网页是直连模式）的时候就会出现这个问题，当我将将swithcy设置成全部通过xxnet连接并重启chrome可正常打开之前出问题的网页

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

**Comment by celeron533** [comment]
看上去是链接或者DNS被劫持？

**Comment by FelisCatus** [comment]
……像是被劫持了，可能是 ISP 问题。与 SwitchyOmega 无关。

P.S. 大概和 xxnet 也无关，应该也不用去那边问了……
