### ISSUE TITLE
域名通配符和网址通配符的区别？

### ISSUE THREAD

**Issue by mrdulin** [FelisCatus/SwitchyOmega#897]
我用代理工具，比如规则 *.domain.com，在网址通配符下有效，但是在域名通配符下却无效。

按咱中文字面意思，域名和网址好像是一个意思。

求解？

**Comment by FelisCatus** [comment]
网址，即  URL ，指页面整个地址，如 `https://www.domain.com/some-page`.

域名指主机名/DNS名，如`www.domain.com`.

如果您观察到的情况与以上说明不符，请提供有问题的网址和对应的规则写法。

**Comment by mrdulin** [comment]
@FelisCatus 之前有个配置是这样的，域名通配符：http://www.domain.com/*  ，无效，但是换成网址通配符就可以。

**Comment by FelisCatus** [comment]
@mrdulin 嗯，因为域名不包括 `http://` 和 `/` 等，只包含 `www.domain.com` 部分，所以无须填写那些内容。您的例子中应该用`*.domain.com`（匹配此域名和子域名）或者`www.domain.com`（只匹配`www`开头的这一个域名）。

而网址通配符则是整个URL网址，见上方说明。

而且，填写错误时可以看到警告，具体效果为选项中填写的规则那一栏变为黄色边框，且选中时黄色边框会发亮。您可以据此来查找有问题的规则并加以修改。

**Comment by mrdulin** [comment]
@FelisCatus 好的，知道了，谢谢。
