### ISSUE TITLE
Latest update chrome SwitchyOmega does not work for https

### ISSUE THREAD

**Issue by dgoo2308** [FelisCatus/SwitchyOmega#898]
After last update of Chrome, Version 54.0.28

on Linux, centos 7 and Mac OSX Sierra, 
when enabling with SwitchyOmega, no https traffic, all timeout on proxy connection: ERR_PROXY_CONNECTION_FAILED
switching to [direct] and [System Proxy], with system proxy set, no problem.

**Comment by FelisCatus** [comment]
Could you please open the page `chrome://net-internals/#proxy` and verify the information there when you have the Proxy Profile selected? (NOT the Auto Switch Profile.)

If the information does not match with your proxy server/port, please check if other extensions are controller the proxy settings.

You can paste the content here if you are not sure about it, but please mask/change your server address to protect your privacy.

**Comment by dgoo2308** [comment]
with SwitchyOmega:

exported pac:
```
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+sing_http", {
    "+sing_http": function(url, host, scheme) {
        "use strict";
        if (/^127\.0\.0\.1$/.test(host) || /^[^:]+:\/\/::1\//.test(url) || /^localhost$/.test(host)) return "DIRECT";
        switch (scheme) {
          case "http":
            return "PROXY 172.17.0.2:8118";

          case "https":
            return "HTTPS 172.17.0.2:8118";

          default:
            return "SOCKS5 172.17.0.2:1080; SOCKS 172.17.0.2:1080";
        }
    }
});
```

and chrome://net-internals/#proxy
```
Effective proxy settings

Proxy server for HTTP: 172.17.0.2:8118
Proxy server for HTTPS: https://172.17.0.2:8118
Proxy server for everything else: socks5://172.17.0.2:1080
Bypass list: 
  127.0.0.1
  ::1
  localhost
```
There is no Internet connection for **https**:
```
There is something wrong with the proxy server, or the address is incorrect.
Try:
Contacting the system admin
Checking the proxy address
ERR_PROXY_CONNECTION_FAILED
```
No problem what so ever on http://.....

on a privoxy http server.

whereass, using the **SwitchySharp**

pac:
```
function regExpMatch(url, pattern) {    try { return new RegExp(pattern).test(url); } catch(ex) { return false; }    }
    function FindProxyForURL(url, host) {
	return 'DIRECT';
}
```

and and chrome://net-internals/#proxy

```
Proxy server for HTTP: 172.17.0.2:8118
Proxy server for HTTPS: 172.17.0.2:8118
Proxy server for everything else: socks5://172.17.0.2:1080
Bypass list: 
  localhost
  127.0.0.1
  <local>
```

no problem at all on **https**

**Comment by FelisCatus** [comment]
Hey, your proxy on `172.17.0.2:8118` is an HTTP proxy, which means you should use HTTP protocol instead of HTTPS protocol, even for `https://` URLs. Yeah I know this is confusing, but what matters here is the protocol of your proxy, not the URL scheme.

Please let me know if your settings are automatically migrated from SwitchySharp but still has the wrong `HTTPS` option selected for you. That would be an issue with the option migrator that should be fixed separately.

**Comment by FelisCatus** [comment]
Closing this for now because this seems to be a configuration problem for me. Please re-open if you have more information.
