### ISSUE TITLE
网址通配符在https协议下不生效

### ISSUE THREAD

**Issue by XanaduNWH** [FelisCatus/SwitchyOmega#899]
自动切换模式下添加一条网址通配符规则，规则设置为 _*/server-status_ 指定一个代理的情景模式SS。

访问 http://domain.com/server-status 时，服务器收到的访问记录为代理服务器的IP，
但是访问 https://domain.com/server-status 时，服务器收到的访问记录为未使用代理的IP，这时插件图标仍会显示情景模式颜色，表示已使用了代理，并且提示匹配的规则 _*/server-status => SS_ 

是我设置的方法不对么？

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

**Comment by celeron533** [comment]
Chrome自身问题  https://github.com/FelisCatus/SwitchyOmega/issues/843#issuecomment-238225368

暂时的解决方法 https://github.com/FelisCatus/SwitchyOmega/issues/845#issuecomment-240948610

**Comment by FelisCatus** [comment]
Cheers!
