### ISSUE TITLE
中国大陆地区以及 GFW List 相关支持

### ISSUE THREAD

**Issue by FelisCatus** [FelisCatus/SwitchyOmega#9]
Title: Extra support for users in China Mainland and the GFW List

目前考虑过的支持如下：

* 默认设置或者一键设置 GFW List 翻墙
* 提交网址给 GFW List
* 检测被墙网站（此问题不在此处理，请移步 #6  ）

要不要做？会不会和扩展主题不符合？是否应该以另一个扩展或者插件的形式实现？

**Comment by Septembers** [comment]
https://github.com/zizon/switchyd#what-it-does--how-it-works
可以参考学习switchyd的基于Hooks的自动学习
这样针对一部分被墙网站可以自动学习并代理
```
net::ERR_CONNECTION_RESET
net::ERR_CONNECTION_TIMED_OUT
net::ERR_SSL_PROTOCOL_ERROR
net::ERR_TIMED_OUT
```

@FelisCatus @Z-Jay

**Comment by FelisCatus** [comment]
v2.3.6 检测被墙网站已经大致做到了，[见说明](https://github.com/FelisCatus/SwitchyOmega/issues/6#issuecomment-74818135)。

**Comment by FelisCatus** [comment]
我感觉目前的支持已经足够了，剩下的部分就交给插件来补足吧。
