### ISSUE TITLE
能否让需要代理的网站自动添加条件

### ISSUE THREAD

**Issue by Jason4774** [FelisCatus/SwitchyOmega#900]
我如果使用gfwlist或者meow、或者cow，那么每次假如访问youtube都还是会做一个判断（判断是否在这个列表里面，是否需要代理），这样就会慢一点，如果我手动添加条件让youtube使用某一个代理工具就不会做这个判断而直接使用这个代理工具，这样就会快一点，但是很多网站都这样手动添加的话也很麻烦，所以我想问问能不能让判断到需要代理的网站自动添加到条件里面，让这些网站直接使用代理工具，而判断到不需要代理的就不管。
谢谢。

**Comment by celeron533** [comment]
SwitchyOmega手动添加条件也是生成pac，从理论上来说没什么不同。只不过项目更少，匹配更快而已。你若是要自动判断然后自动添加，到最后只是重复了gfwlist

**Comment by Jason4774** [comment]
因为pac里面只对部分网站使用用代理，所以我一般不用，gfwlist这种也是，所以我用meow这种自动判断是否需要代理的。但就是感觉这个判断会影响加载速度。谢谢你的回复。

**Comment by FelisCatus** [comment]
技术上不太可行，见 #550.
