### ISSUE TITLE
[建议]把Proxy Profile排在下面

### ISSUE THREAD

**Issue by Jimmy-Z** [FelisCatus/SwitchyOmega#901]
最近搞了好多Profile, 常用的PAC Profile被挤到下面去了不太方便

能手动排序就更好了

**Comment by FelisCatus** [comment]
排序见 #607.

暂时建议给不常用的情景模式改个名，前面加下划线`_`，这样不在菜单中显示（选项界面仍可见并可用于虚情景）。
