### ISSUE TITLE
自动切换添加的自定义规则和规则列表的域名重复导致切换不生效

### ISSUE THREAD

**Issue by Abel-Liu** [FelisCatus/SwitchyOmega#902]
自动切换中添加的自定义规则和规则列表的域名重复时，自动切换就不生效了。

![switch](https://cloud.githubusercontent.com/assets/7625589/19547973/15802926-96ce-11e6-8d24-197110f1916c.jpg)

SwitchyOmega 2.3.19
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36

**Comment by FelisCatus** [comment]
不是吧……感觉不可能……

点立即更新情景模式的时候可以更新吗？如果可以更新应该就没问题了才对……

**Comment by Abel-Liu** [comment]
点立即更新 不能更新

**Comment by FelisCatus** [comment]
请先确定在菜单中选择了 shadowsocks 模式然后再点击立即更新情景模式。如果还无法更新，建议检查代理服务器本身的问题或者网络问题。

**Comment by FelisCatus** [comment]
这边怎么样了？

**Comment by FelisCatus** [comment]
行吧，那么我就当解决了啊……虽然我还是不知道发生了什么，不过没事了就好……
