### ISSUE TITLE
下载pac脚本时对其做合法性检测

### ISSUE THREAD

**Issue by rayline** [FelisCatus/SwitchyOmega#903]
部分计费wifi网络等会劫持HTTP请求到登陆页，而插件经常再此时更新pac脚本，造成获取到完全错误的内容导致代理无法使用
通常这个劫持页面完全不像pac脚本，与正常脚本可以区分

**Comment by FelisCatus** [comment]
感觉检查是否有 `FindProxyForURL` 这个字符串应该就足够了。

**Comment by FelisCatus** [comment]
做了一个简单的检查，会先过滤 HTML 页面（比如 WiFi 登录页面），然后检查是否有 `FindProxyForURL` 这个字符串。应该能屏蔽掉不少莫名其妙的劫持、广告之类的吧。

顺便把错误提示也做得人性化了一点，这样就比较容易知道是什么错误了。

**Comment by FelisCatus** [comment]
新版本很快就会发布～
