### ISSUE TITLE
2016/10/25更新后老用户觉得失去的一点。

### ISSUE THREAD

**Issue by jglimmers** [FelisCatus/SwitchyOmega#904]
因为我常上有些网站经常需要挂代理，有时候又不需要挂代理，所以原来直接在扩展点左键选择 baidu.com 出来二级菜单选择什么代理模式，但是更新后没有了，觉得很不方便。请问作者取消掉那个功能是为什么呢？

**Comment by dupu222** [comment]
是的,二级菜单中选择代理模式功能非常配合自动切换非常方便.
取消掉之后添加自定义规则必须打开**选项**-**添加条件**.
希望作者下个版本能够将这个功能添加回来.

**Comment by zacpang** [comment]
这个功能让我折腾了一个下午- -|| 原来真的没了。请求加上这个功能。有时候访问国外网站，可能最近一段时间需要访问个几次，添加临时规则感觉很重要，否则我要不停的在代理和自动代理之间切换或者手动添加到规则列表里，这样都很不方便。不知道我说清楚没有。

**Comment by ragnarokna** [comment]
是功能取消了吗?应该不会吧,这个功能的很多描述信息还在的.可能只是临时的bug吧.
我也弄了好久,以为是自己这边出了问题.

**Comment by MinamiyaSion** [comment]
我也觉得那个功能挺好用的 我以为就我一个人遇到这情况 而且原本网页右键的那个审查元素也不在了

**Comment by 500646** [comment]
我以爲就我這出席按這個問題了,重裝了下還是不行. 是取消了麽？挺好用的功能啊.

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。

**Comment by MarshallChen** [comment]
Awesome!
