### ISSUE TITLE
自动切换下面的二级选项为什么消失了？

### ISSUE THREAD

**Issue by neunundneunzig** [FelisCatus/SwitchyOmega#905]
不知道什么原因，某些站点并不能自动对应代理
这个时候就需要在自动切换下面手动指定该网站是直接连接还是使用代理
现在它的选项消失了，是我这里出了问题，还是这个插件的设计意图？

请看图：
http://i1.piimg.com/567571/80c57a035076af1e.png

**Comment by yangxin9003** [comment]
我也遇到同样的问题。这是我的错误日志
[OmegaLog_1477470075681.txt](https://github.com/FelisCatus/SwitchyOmega/files/552714/OmegaLog_1477470075681.txt)

**Comment by guxin0123** [comment]
同样的问题

**Comment by alexwfl** [comment]
同上

**Comment by pnjgyl** [comment]
我的也是.....是chrome更新的原因吗?

**Comment by eliyax** [comment]
同样的问题

**Comment by ansemz** [comment]
同样的问题，使用上太不方便了

**Comment by ZHonry** [comment]
是的  我以为我的电脑问题呢   折腾一下午

**Comment by lephix** [comment]
同样的问题。

**Comment by zhanghaoyu1993** [comment]
同样的问题。

**Comment by MerlinPendragon** [comment]
同样的问题。看来不是我一个人T_T

**Comment by cnssr4bb1t** [comment]
同求

**Comment by wjw48818** [comment]
同上

**Comment by MinamiyaSion** [comment]
同上

**Comment by aescin** [comment]
有解决的办法没现在.。

**Comment by parsebyte** [comment]
+1 这个功能很实用

**Comment by Teddy-Zhu** [comment]
同样的问题

**Comment by exoticknight** [comment]
删掉实用功能？

**Comment by BayesZou** [comment]
同上

**Comment by wanglongbiao** [comment]
啊？删掉了吗？
公司里经常屏蔽掉豆瓣、京东之类的网站，那个功能可是相当实用的啊

**Comment by xiashali** [comment]
希望能够解决

**Comment by 2z2** [comment]
希望能还原回来

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。

**Comment by exoticknight** [comment]
@FelisCatus 👍
