### ISSUE TITLE
自定义条件消失

### ISSUE THREAD

**Issue by octowhale** [FelisCatus/SwitchyOmega#907]
你好，omega选项单，本身除了代理模式之外，还有自定义条件等
但是今天下午发现自定义条件消失了，如图。
![image](https://cloud.githubusercontent.com/assets/7335398/19719684/9806f478-9b9d-11e6-92fd-00fc43009286.png)

期间一直在看网页，没有执行其他操作。

在omega选项-》界面中
![image](https://cloud.githubusercontent.com/assets/7335398/19719764/ea248194-9b9d-11e6-8ab0-24db42948ea5.png)
如图，选择了了高级切换和快速切换，也没有出现自定义条件。

-----

以上，请知悉
谢谢

SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by octowhale** [comment]
已有其他相同问题。

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。
