### ISSUE TITLE
无法手动添加被墙的网址进入某个情景模式

### ISSUE THREAD

**Issue by moerfutin** [FelisCatus/SwitchyOmega#909]
如图，
![unnamed 2](https://cloud.githubusercontent.com/assets/9960618/19728776/3d13c9fe-9bc7-11e6-9522-7af48949539b.png)
![unnamed 1](https://cloud.githubusercontent.com/assets/9960618/19728777/3d170cfe-9bc7-11e6-8116-d85d68321925.png)
![unnamed](https://cloud.githubusercontent.com/assets/9960618/19728778/3d1aa92c-9bc7-11e6-8145-81174c1912f9.png)

并且，提示 “ 此情景模式使用存储空间过多，因此无法进行同步。”
![omega](https://cloud.githubusercontent.com/assets/9960618/19728801/53792f9a-9bc7-11e6-8e30-d45ce5175259.PNG)

SwitchyOmega 2.3.20
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36

**Comment by FelisCatus** [comment]
已经确认的 bug ，紧急修复中。由于 Chrome Web Store 审核需要一段时间，所以请耐心等待。见 #908.

**Comment by moerfutin** [comment]
好的多谢，那么情景模式占用存储空间过多无法同步，也是同一个bug嘛。 感谢开发者这么晚还及时回复。

**Comment by FelisCatus** [comment]
见 #678

**Comment by FelisCatus** [comment]
SwitchyOmega 2.3.21 发布！紧急修复了菜单中无法添加条件的问题。不是故意删除了功能。http://goo.gl/5kbmZp   等不及推送的话可直接下载： http://goo.gl/lsFfFl   求转发，让更多人及时更新避免问题。
