### ISSUE TITLE
PAC ERR_MANDATORY_PROXY_CONFIGURATION_FAILED

### ISSUE THREAD

**Issue by catsimple** [FelisCatus/SwitchyOmega#913]
路由器上配置了XXNET 用直连模式打开网页正常 切换到PAC打开所有网页都显示ERR_MANDATORY_PROXY_CONFIGURATION_FAILED包括内网
@FelisCatus 

[OmegaProfile_pandorabox.txt](https://github.com/FelisCatus/SwitchyOmega/files/558459/OmegaProfile_pandorabox.txt)

**Comment by FelisCatus** [comment]
我这里能正常运行你上传的这个脚本。
请问实际使用时， SwitchyOmega 图标下拉菜单中激活的是哪个情景模式？是自动切换还是 PAC 情景模式？ 选项中 PAC 情景模式是直接编辑的正文还是输入 URL 下载？

**Comment by catsimple** [comment]
现在又没问题了

**Comment by FelisCatus** [comment]
暂时关闭了。如果再有问题请再试试看上传脚本。
