### ISSUE TITLE
判断国内外网址，自动切换代理

### ISSUE THREAD

**Issue by ywmail** [FelisCatus/SwitchyOmega#914]
在国内和国外分别有多个代理，希望能按目标网址所在国家自动选择不同的代理。
比如访问美国的网址，就使用美国的代理。访问中国的网址就使用中国的代理。

**Comment by celeron533** [comment]
你可以准备一些只包含中国地址或者美国地址的pac列表文件

**Comment by ywmail** [comment]
不知道网络上有没有现成的pac文件。就像有GFW list列表一样。
但就算有这样的列表，文件估计也是非常大。。
如果支持这样的规划就好了，比如知道哪些IP地址段是国内的，哪些段是国外的。通过IP地址来判断。
还有一种思路是简单地通过网站语言来判断。但是那貌似也要先获取网站内容。。
我现在只能简单地通过.cn就转国内，其它全部用国外的代理。

**Comment by celeron533** [comment]
通过网站语言判断绝对不是个好办法。
你无法判断目标网址的国家，因为有时候web服务器的反向代理和CDN会打破原有的地理限制。

**Comment by ywmail** [comment]
嗯，我平常主要访问一些服务器在国外的网站，因此我把默认规则设置的是国外的代理。然后如果匹配到.cn域名，就使用国内的代理。再就是为一些常用的国内网站，添加了一些规则。

**Comment by FelisCatus** [comment]
SwitchyOmega 是一款代理设置软件，运作原理为生成 PAC 脚本。 PAC 脚本中仅可使用网址信息，不涉及路由表/网络协议等底层通讯。

要实现这类功能需要更底层的路由表 + VPN 解决方案，不在本项目范围之内。具体用法请自行查找，一般来说需要 VPN 或者 SOCKS5 代理，而非普通的代理服务器。
