### ISSUE TITLE
"Make backup" not working

### ISSUE THREAD

**Issue by rnaab** [FelisCatus/SwitchyOmega#915]
Hi
Pushing "Make backup" button doesn't do any action :|

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by FelisCatus** [comment]
It should download a backup file to your downloads folder by default, which is displayed at the bottom left the page by Chrome.

If nothing is downloaded: what browser are you using? Are you blocking file downloads?

Also, could you open Developer Tools (right click on the page > Inspect Element), switch to the Console tab and see if there is any error? You can push the button several times with DevTools open to see if anything gets appended to the output.

**Comment by FelisCatus** [comment]
Closing for now. Please re-open if you have more information.

**Comment by JJOne123** [comment]
This seems to be an issue on the latest release of SwitchyOmega (2.5.18) on Chrome version 68.0.3440.106 (Official Build) (64-bit).

The error in the Chrome developer Console output states:

`ReferenceError: saveAs is not defined
    at omega.js:147
    at omega.js:366
    at angular.min.js:140
    at m.$digest (angular.min.js:151)
    at b.$apply (angular.min.js:155)
    at HTMLButtonElement.<anonymous> (angular.min.js:197)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.y.handle (jquery.min.js:2) "Possibly unhandled rejection: {}"
(anonymous) @ angular.min.js:127
(anonymous) @ omega.js:96
g @ angular.min.js:139
$digest @ angular.min.js:151
$apply @ angular.min.js:155
(anonymous) @ angular.min.js:197
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2`

Re-opening this so as not to duplicate issues. :)

HTH

**Comment by JJOne123** [comment]
Let me try put the stack trace from Console in an easier to read format:

ReferenceError: saveAs is not defined
    at omega.js:147
    at omega.js:366
    at angular.min.js:140
    at m.$digest (angular.min.js:151)
    at b.$apply (angular.min.js:155)
    at HTMLButtonElement.<anonymous> (angular.min.js:197)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.y.handle (jquery.min.js:2) "Possibly unhandled rejection: {}"
(anonymous) @ angular.min.js:127
(anonymous) @ omega.js:96
g @ angular.min.js:139
$digest @ angular.min.js:151
$apply @ angular.min.js:155
(anonymous) @ angular.min.js:197
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by FelisCatus** [comment]
@JJOne123 This is a different issue introduced in 2.5.18 and tracked in #1593.
