### ISSUE TITLE
Mac 版本 Chrome 54 下不稳定

### ISSUE THREAD

**Issue by kyo-chou** [FelisCatus/SwitchyOmega#917]
在 Chrome 54 下总会先出现 "Your connection was interrupted", 然后再次加载 URL 后才能打开页面, 并且很不稳定. 我将 Chrome 版本回退到 Version 51.0.2704.106 (64-bit), 就可以正常使用了.

**Comment by SeavantUUz** [comment]
这个问题和 SO 无关。请升级到 chrome 到最新版。您所说的这个 bug 应该是最新修复的 <https://codereview.chromium.org/2463453002> 。
> Mojo connection error handlers in Blink
to no-op if invoked after Blink shutdown

**Comment by celeron533** [comment]
在54下使用全局代理是否有这个问题？

**Comment by kyo-chou** [comment]
嗯. 同样会有. 我怀疑是 54 的 Chrome 改了底层的网络实现方式. 你们最好装个 54 的版本测试一下

**Comment by celeron533** [comment]
我试了一下，chrome54没问题

**Comment by kyo-chou** [comment]
那这个问题怎么解决?  有收集日志的方法吗? 我把 Chrome 版本更新后如果能重现要如何反馈过来

**Comment by celeron533** [comment]
@kyo-chou 不好意思，我的是windows版本。。。不是mac

**Comment by celeron533** [comment]
@kyo-chou 在SO图标上单击右键，有保存日志的选项

**Comment by kyo-chou** [comment]
是这种日志吗? 好像没什么内容
```
Options << Options#applyProfile [
    "auto switch"
]
Options << Options#updateProfile [
    [
        "auto switch",
        "__ruleListOf_auto switch",
        "default",
        "direct",
        "video-ad"
    ]
]
Options << Options#updateProfile []
Options << Options#applyProfile [
    "default"
]
Options << Options#updateProfile [
    [
        "default"
    ]
]
```

**Comment by kyo-chou** [comment]
我用的是 http 代理, 代理是确定没问题的.

**Comment by FelisCatus** [comment]
用全局代理也有这个问题的话就基本和 SwitchyOmega 无关了。可以试试看命令行设置代理是否也有同样的问题（我猜应该有），如果有的话请反馈给 Chromium 项目。不是这边的问题，无法修复。
