### ISSUE TITLE
最近我的机器经常出现err_network_changed 的报错

### ISSUE THREAD

**Issue by freshcn** [FelisCatus/SwitchyOmega#918]
最近我的机器经常出现err_network_changed 的报错

SwitchyOmega 2.3.21
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36

**Comment by celeron533** [comment]
`err_network_changed` 在正常情况下，一般由操作系统网络变化引发，比如从无线网络切换到有线网络、在两个无线网络之间切换、物理网络连接不稳定等
我今天升级到了chrome 54，暂时没有遇到这个问题

**Comment by freshcn** [comment]
我这儿只有一个wifi而且最近基本都是使用的有线的。

不知道为什么自从系统升级到了mac 10.12后就经常出现这问题了，之前没有

**Comment by FelisCatus** [comment]
此错误与代理设置无关，只与操作系统本身的网络连接有关。
不是 SwitchyOmega 的问题，先关闭了。

**Comment by WingGao** [comment]
@freshcn 
试试这个 `sudo launchctl remove com.alipay.DispatcherService`

**Comment by freshcn** [comment]
@WingGao 谢谢，我在v2ex上找到了这个解决方案，和你说是一样的。已经处理好了。

**Comment by MadeInChina** [comment]
+1
sudo launchctl remove com.alipay.DispatcherService
