### ISSUE TITLE
使用pac方式时，访问google提示ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by northteam** [FelisCatus/SwitchyOmega#919]
使用多态（duotai.org）提供的pac代理方式上网时，总是每过一段时间，访问google（https://www.google.com/ ）就提示ERR_EMPTY_RESPONSE错误。需要把SwitchyOmega的代理方式切换成其他任意一种模式，再切换到多态的pac，才能继续使用。

**Comment by FelisCatus** [comment]
嗯……不好确定呢。好多情况都有可能……不太好排查的样子。

首先果然还是试试看是否是扩展冲突问题吧，禁用其他所有扩展试试看。不排除有扩展会过一段时间设置一下代理设置，所以把那个覆盖掉了。

然后……试试看不要切换到其他代理模式，而是直接菜单里再点一次 PAC 方式。即使那个选项已经是选中状态也可以选，会刷新一次的。

最后……如果再点一次的方法也有效……我没用过你说的那个多态，会不会是他们提供的代理服务器不稳定，每过一段时间就需要换一个 IP 地址，所以 PAC 文件也需要更新？如果是这个情况的话确实能解释你观察到的情况。但这个就没法修复了吧……只能手动点了……

虽然我很想让你把那个 PAC 文件上传上来，不过如果真的要做的话请记得去除个人隐私相关内容和公开的代理服务器地址。而且，最好确认下上传是否会违反授权协议或者侵犯版权。

**Comment by northteam** [comment]
应该不是扩展冲突的问题，我在chrome的隐身模式下用了一段时间，只剩下SwitchyOmega插件，问题依然存在。
不切换其他代理，只是在菜单里点击一次PAC方式，可以解决这个问题，可以打开google首页，没有错误了。
我对比了更新pac文件前后的内容，发现文件内容没有任何变化。
另外，我在windows下系统代理设置中使用这个PAC文件，并禁用SwitchyOmega插件，没有再复现这个问题，不知道插件和系统代理工作方式有什么差异。
这个pac文件地址确实是私密的，不过我可以私下把地址发送给您，方便的话，麻烦留一下邮箱地址，多谢。

**Comment by FelisCatus** [comment]
请尝试在 SwitchyOmega 选项 > 通用中将下载频率设置为永不更新，然后再试试看。这个设置会禁止任何对于 PAC 文件的自动更新，包括在菜单中重新选择也不会更新。
也可以在选项的 PAC 脚本中多按几次立即更新情景模式，看看是否有任何差异。

**Comment by northteam** [comment]
永不更新后，每隔一段时间就会出现，我在本机通过其他方式下载一次pac文件，SwitchyOmega中就又可以用了，看起来极有可能是我的代理服务商的问题。不过也因此发现设置短一点的更新间隔就可以临时解决这个问题了。
多谢在此持续跟进。

**Comment by FelisCatus** [comment]
……看来这个问题不属于本项目的范畴了。感谢提供信息和协助定位问题～
