### ISSUE TITLE
Youtube not working.

### ISSUE THREAD

**Issue by FrutyX** [FelisCatus/SwitchyOmega#920]
Hello,

(My english is not perfect,sorry :-) )

i have a big problem,i dont know what to do with it,so i decided to ask you,but it's not propably problem of Switchy Omega....I don't have any other options anymore.

So..

I am using Tor network and SwitchyOmega together,everything is working very fine,but one day...something get wrong.

I have been cleaning my PC with some tools...Malwarebytes,ADWCleaner,TDDSKiller together with CCleaner,restarted PC.......From this day,Youtube is not working anymore,something went wrong.

The problem is only on Youtube,everything else is working.So what i have tried:

Restarting Google Chrome settings
Reinstalling SwitchyOmega 
Restarting Tor Network
Checked registry,proxy settings,virus scan ........
Cleaned it again with CCleaner
Reinstalled all add-ons of the browser

and many,many other things..

There is not problem with SwitchyOmega,not even with Tor Network,beacuse other websites are working perfectly,it seems that Youtube is not using proxy,but why ? Youtube worked to that day normally.

About YT Details : Youtube,the site,is working normally,but it wont load any videos,after a long time of loading it will say that there were an error,try again later.

I tried another browser (without SwitchyOmega,just browser proxy settings) ,excatly Firefox and Youtube is working,videos are loading,I can even turn on HD quality...

So where,the hell,is the problem ? I have been searching...very deep...what about..HTML5 or flash ? Is there the problem ? Are there two things using proxy ? Beacause the site is working normally,but videos not ?

Man,i really dont know anymore,SwitchyOmega is of course reporting 50-80 problems with network.

I would really appreciate your help,your tips,anything .

And thank you for an amazing add-on for Google Chrome like SwitchyOmega,i am using it,i like it,its just awesome !

**Comment by FrutyX** [comment]
I think i have fix it...I was blid...

SwitchyOmega was reporting network errors on these domains:

*.googlevideo.com
*.youtube.com
*.ggpht.com
*.youtube-nocookie.com
*.ytimg.com

So i have created switch and rules for them ,looks like Youtube videos are working again.

So i have to select my proxy (Tor - profile) for my selected website (I dont want to use proxy for all websites) and activate the switch with these rules (and domains above).

Seems working,i hope it will work like i want and everything is set good - well,it is working so..

**Comment by FelisCatus** [comment]
Okay, i'm glad that it is working.
