### ISSUE TITLE
最近经常出现不能上网的情况。排查后发现是这个扩展的问题

### ISSUE THREAD

**Issue by Arnold4869** [FelisCatus/SwitchyOmega#921]
我现在用的是有线网，插上就能用的那种
win10 X64
用的chrome也是64位版本
这个问题出现有一个月？最近几天重复出现。
今天一天出现三次，我现在是靠着SS的全局模式来上的。。

**Comment by sndnvaps** [comment]
我认为是你一直开着这个代理，但是你实际上没有打开 shadowsocks-qt5 这种代理程序。。所导致的问题。

**Comment by FelisCatus** [comment]
……不能上网是什么问题？提示什么错误？如果有错误页面，错误页面上点展开更多信息，能否看到错误代码？
另请参考 #557.
