### ISSUE TITLE
无法使用shadowsocks代理

### ISSUE THREAD

**Issue by SeaEastXu** [FelisCatus/SwitchyOmega#923]
之前一切正常。。现在配置没有变，sockets5协议，127.0.0.1 ，1080。没法代理上网。
只能使用系统代理模式上网。重新卸载安装也没用。

**Comment by FelisCatus** [comment]
看上去像是 #557?

**Comment by SeaEastXu** [comment]
@FelisCatus 换成HTTP代理协议，果然可以用了。只是很奇怪啊，之前一直用的好好的，自从2.3.20版本出现autoswitch无法添加条件开始，就不行了。迅雷用的是极速版，版本一直没变过，系统是win7 x64，chrome也没更新过。

**Comment by FelisCatus** [comment]
……巧合吧。
