### ISSUE TITLE
使用SwitchyOmega后切换为直接连接，访问任何网站的IP会变成10.*.0.0的内网IP。

### ISSUE THREAD

**Issue by lslqtz** [FelisCatus/SwitchyOmega#924]
使用SwitchyOmega后切换为直接连接，访问任何网站的IP会变成10.*.0.0的内网IP。
标题已描述完毕，Chrome 49。

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

**Comment by lslqtz** [comment]
标记：偶发现象

**Comment by FelisCatus** [comment]
请用其他扩展也试试看？

不确定是不是 SwitchyOmega 的问题，但是看上去更可能和 Chrome 内部实现有关。

**Comment by lslqtz** [comment]
我不切换的时候是一直没有问题的，只有切换后再切换回直接连接才会有这种现象，而且速度很慢，似乎仍然是在走代理。

**Comment by lslqtz** [comment]
本人的扩展程序列表如下：
Postman 4.8.1
EditThisCookie 1.4.1
Proxy SwitchyOmega 2.3.21
Shodan 0.3.0
Switcheroo Redirector 1.33
User-Agent Switcher for Google Chrome 1.8.20

**Comment by lslqtz** [comment]
确定不是扩展问题了，我一个个试过去看看。
sorry

**Comment by FelisCatus** [comment]
解决了就好～

从结论上来说确实是不相关。
