### ISSUE TITLE
什么时候可以把规则同步取消过多限制啊...

### ISSUE THREAD

**Issue by PromiseNev** [FelisCatus/SwitchyOmega#925]
SwitchyOmega 2.3.21
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.87 Safari/537.36

**Comment by celeron533** [comment]
这个限制是google那边限定的。应为每个扩展可用的漫游存储就那么大
参考 #678

**Comment by FelisCatus** [comment]
见 #802.
