### ISSUE TITLE
Maybe stalls my Socks5 Proxy

### ISSUE THREAD

**Issue by marcIhm** [FelisCatus/SwitchyOmega#926]
Hi,

thanx for this nice tool ! But now and then my socks 5 proxy stopps working. Of course I suspected other things and even rebooted my PC (which helped most of the time). But now I found, that Chrome is the culprit. Chrome is sometimes not able to communicate over Socks 5 and even Firefox cannot talk with Socks 5 as long as Chrome is running. When I shutdown Chrome, everything is fine and Firefox can use Socks 5 again. Maybe this is caused by Chrome itself and not by your tool. But maybe it is, and if you get more reports like mine, you might want to investigate. Sorry for not beeing more specific ...

best regards
Marc

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36

**Comment by FelisCatus** [comment]
Thanks for the report.

When things like this happen, the first step to diagnose would be disabling SwitchyOmega altogether and using command-line flags for setting proxies. Once you do that, you will be ready to file an issue on the chromium project if you still observe the problem.

In this case I would suppose it would be the case, but don't trust me on this without your own testing. :-)

**Comment by FelisCatus** [comment]
Closing for now. Please re-open if you have more information.
