### ISSUE TITLE
blocked url

### ISSUE THREAD

**Issue by houkai4355** [FelisCatus/SwitchyOmega#927]
SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.44 Safari/537.36

**Comment by FelisCatus** [comment]
What?

**Comment by FelisCatus** [comment]
Closing for now. Please re-open if you have more information.
