### ISSUE TITLE
1. Chrome版本 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

### ISSUE THREAD

**Issue by Ryan-Xu** [FelisCatus/SwitchyOmega#929]
1. Chrome版本 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit)
2. 使用AutoProxy自动切换， AutoProxy列表https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
软件情况如上，chrome 经常卡死，不确定是不是因为代理网络原因，如果是代理网络质量差，那至少不能让chrome卡死吧，希望能解决！

SwitchyOmega 2.3.21
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36

**Comment by celeron533** [comment]
代理网络质量差还真的能让chrome页面失去响应。
我是上海电信国际网络出口受害者。。。

**Comment by FelisCatus** [comment]
见 #815 ，目前认为是 Chrome 的问题。
