### ISSUE TITLE
SwitchyOmega 在我chrome上不能用了

### ISSUE THREAD

**Issue by choicky** [FelisCatus/SwitchyOmega#934]
不能用的症状是：不管是auto还是全局模式，chrome都上不了网，内网外网都上不了。

只有“直接连接”，才能上网，当然是只能上墙内网站。

这个现象，最近两三周才出现，最初是间歇性出现，重启chrome就能解决问题。

今天是不管怎么重启chrome、重装/重置SwitchyOmega 都解决不了。

**Comment by choicky** [comment]
有可能是这个原因 https://github.com/FelisCatus/SwitchyOmega/issues/557

**Comment by FelisCatus** [comment]
姑且问一下好了，不能上网的时候错误代码是什么？如果 Chrome 有一个错误页面，请仔细查看错误页面上的信息并且点击展开详情等，将页面上的内容复制到这里。错误代码大概会是一个 `ERR::` 开头的字符串。

**Comment by choicky** [comment]
@FelisCatus 我等问题重现时再贴上了。

**Comment by FelisCatus** [comment]
这边怎么样了？

**Comment by choicky** [comment]
@FelisCatus 最近几个月都正常了.... 所以重现问题。

**Comment by FelisCatus** [comment]
好的，总之解决了就好……再出问题的时候再告诉我吧。

**Comment by ShellyShen1019** [comment]
我刚刚解决了这个问题，是代理服务器没有设置好。应该要有一个代理IP

**Comment by ShellyShen1019** [comment]
http://c.biancheng.net/python_spider/switchyomega.html可以参考这个网址进行代理器设置

**Comment by AnyWAT** [comment]
链接与纯文字之间要留空
