### ISSUE TITLE
有台机子最近开始假死了

### ISSUE THREAD

**Issue by houkai4355** [FelisCatus/SwitchyOmega#935]
6台机子，就公司这一台这两个月开始，突然卡死，从最开始的十几秒到现在的十几分钟，禁用SO后就不会出现，启用SO不定时就卡一阵子。
刚刚关闭了chrome://flags/#v8-pac-mojo-out-of-process的选项 不知道有没有用，这是刚刚导出的pac文件

[OmegaProfile_auto_switch.docx](https://github.com/FelisCatus/SwitchyOmega/files/599592/OmegaProfile_auto_switch.docx)

**Comment by celeron533** [comment]
插播：
我最近发现chrome54的flashplayer有严重的性能问题，也会导致浏览器卡顿和莫名失去响应。禁用flash后使用了一天没有出现卡顿。。。:trollface:

**Comment by FelisCatus** [comment]
见 #815 ，目前认为是 Chrome 的问题。

**Comment by FelisCatus** [comment]
我只能说我自己用的时候 Flash 一直都是禁用掉的……只有遇到网站不用 Flash 就不行的时候才会打开一下……
