### ISSUE TITLE
How to add current website into PAC

### ISSUE THREAD

**Issue by MarkLiu2345** [FelisCatus/SwitchyOmega#938]
I have a host list in PAC, and if the url fit the rule it will go through proxy such as *google.com.
When I access to www.facebook.com which is not in the list, the connection will be blocked. So is there any simple way I could add *facebook.com into my PAC except modify PAC script and save it.

Thanks.

**Comment by celeron533** [comment]
You could add the URL to rule list first (before execute the PAC)
![image](https://cloud.githubusercontent.com/assets/3608762/20554615/19f104fa-b198-11e6-8d96-546f8ab34e84.png)

**Comment by FelisCatus** [comment]
In this case, it is recommended to use the Switch Profile and put your customized rules (e.g. facebook) there. Then, set the Default rule to your PAC Profile, which would allow SwitchyOmega to invoke your PAC script if no rules match a given request (e.g. google).
