### ISSUE TITLE
规则多选和操作

### ISSUE THREAD

**Issue by debugzxcv** [FelisCatus/SwitchyOmega#94]
可通过键鼠或其他输入设备多选规则, 并进行操作(删除/更改条件类型等)

**Comment by ztq56** [comment]
workaround：可以建一个虚拟的proxy然后把他设为`系统代理`/你要更改的代理，来达到删除/修改的目的

**Comment by FelisCatus** [comment]
这个我就关掉了，现在有虚情景了，也能直接编辑自动切换模式的源代码来实现查找替换。把自动切换模式的源码复制到 VIM 或者你喜欢的任何编辑器里，感觉没有什么是做不到的了。
