### ISSUE TITLE
乱码的问题

### ISSUE THREAD

**Issue by aini51478** [FelisCatus/SwitchyOmega#940]
安装了switchyomega以后，一会就变形成这样，设置不了！也用不了!
![7c1ed21b0ef41bd571e92dd058da81cb39db3d58](https://cloud.githubusercontent.com/assets/22867072/20701837/f79024ec-b64f-11e6-8f9c-d6402ee90ec6.jpg)

**Comment by celeron533** [comment]
chrome插件的文本资源文件被摧毁了，以前也有人反映过类似问题，那个人最后的调查结果是感染病毒

**Comment by FelisCatus** [comment]
见 #540 ，我感觉像是中了病毒……先杀毒吧……

如果要进一步分析问题的话，姑且可以试试看在扩展图标上右键选择导出错误日志并上传到这里。如果日志里的错误信息和 #540 类似的话……那几乎可以肯定是扩展文件被篡改了……中毒的可能性很高。

**Comment by zzgpku** [comment]
我今天也出现了这种问题，赶紧查下毒。。。

**Comment by aini51478** [comment]
没用的，我重做了系统，还是这样！没办法。⁣

发自 TypeApp ​

2016年12月7日 22:34, 22:34，在 "一棵树的影子" <notifications@github.com> 已写:

**Comment by FelisCatus** [comment]
@aini51478 在选项页面打开开发者工具试试看？选择 Console （控制台）功能，应该可以看到详细的错误信息。

**Comment by zzgpku** [comment]
我的杀完毒就好了。。。

**Comment by FelisCatus** [comment]
这个先关了……注意杀毒……别的不多说了……

**Comment by celeron533** [comment]
以及不要去那些奇奇怪怪的网站~~
> 这个先关了……注意杀毒……别的不多说了……

**Comment by asmosn** [comment]
重装系统还是一样
