### ISSUE TITLE
Rule for GEO IP?

### ISSUE THREAD

**Issue by daniaoren** [FelisCatus/SwitchyOmega#942]
First, thank you very much for this project. It really helps me a lot.

I just want to know if there is anyway to add rules for GEO IP? Like I could connect directly if it's a CN IP, and connect through proxy if it's not a CN IP.

Because now there seems to be a lot of sites that are not only the GFW list but are blocked. I tried GEO rule on Surge and it works really well.

Thank you very much.

**Comment by FelisCatus** [comment]
SwitchyOmega is a proxy configuration tool. What you want would require routing on the network layer, which could not be done in the browser. You would probably need VPNs and route tables (like China routes) to accomplish IP geolocation based switching. Proxies won't help in this case.

See also #914 (Chinese).
