### ISSUE TITLE
有些时候GFWlist模式下匹配的网址一直在加载但就是打不开，这是怎么回事？

### ISSUE THREAD

**Issue by thelastfantasy** [FelisCatus/SwitchyOmega#943]
![image](https://cloud.githubusercontent.com/assets/6077584/20855851/09392b30-b93e-11e6-8ccd-f8d610541236.png)
![image](https://cloud.githubusercontent.com/assets/6077584/20855886/9dc986f0-b93e-11e6-9dcf-e0da7d3ffc34.png)

如图，在处于图1"auto switch"模式下时，打开google，维基百科等匹配网址时**偶尔**会出现无限加载的情况，使用图2"proxy"全局代理的话则不会出现此问题。网页使用firefox+foxyproxy也能打开所以应该不是网络问题。

Chrome版本 54.0.2840.99 m (64-bit)
操作系统：Windows 7 64位，**没有安装迅雷**
已启用扩展列表：
Advanced Font Settings 0.67
ID： caclkomlalccbpcdllchkeecicepbmbm
Apps Launcher 2.4.6
ID： ijmgkhchjindcjamnckoiahagecjnkdc
Beat Finder 0.4.1
ID： ndenpgejcjbklgdhdhimhdbfbcnbknpg
Better History 3.9.14
ID： obciceimmggglbmelaidpjlmodcebijb
Checker Plus for Gmail™ 19.3.4
ID： oeopbcgkkoapgobdbedcemjljbihmemj
Google Keep - 记事和清单 3.1.16472.1428
ID： hmjkmjkepdijhoojdojkdfohbdgmmhki
IDM Integration Module 6.26.9
ID： ngpampappnmepgilojfohadhhmbhlaek
Image Search Options 0.0.7.4
ID： kljmejbpilkadikecejccebmccagifhl
Language Filter for Wikipedia 2.2.0
ID： ibgceajjjioihilfcdppneoljcaofokk
LastPass: Free Password Manager 4.1.33
ID： hdokiejnpimakedhajhdlcegeplioahd
PageExpand 1.5.8
ID： bjnobgdfhefpilajplncgjjeopakpepc
Pinterest Save Button 2.0.5
ID： gpdjojdkbbmdfjfahjcgigfpmkopogic
Pocket 0.810
ID： mjcnijlhddpbdemagnpefmlkjdagkogk
**Proxy SwitchyOmega 2.3.21
ID： padekgcemlokbadohgkifijomclgjgif**
Redirector 3.1.0
ID： ocgpenflpmgnfapjedencafcfakcekcd
Save to Pocket 2.1.17
ID： niloccemoadcdkdjlinkgdfekeahmflj
Select the left tab 1.0.2
ID： lomglahbefgfclaepeiigfplhiekdgdj
smartUp手势 4.0.1575.663
ID： bgjfekefhjemchdeigphccilhncnjldn
Stylish 1.5.2
ID： fjnbnpbmkenffdnngjfgmeleoegfcffe
Tampermonkey 4.2
ID： dhdgffkkebhmkfjojejmpbldmpobfkfo
uBlock Origin 1.10.0
ID： cjpalhdlnbpafiamejdnhcphjbkeiagm
Yet another flags 1.0.2
ID： dmchcmgddbhmbkakammmklpoonoiiomk

**Comment by FelisCatus** [comment]
感谢详尽的报告。扩展比较多，不过粗略地看不是扩展冲突问题。

请在打开问题页面时，多等待一段时间，然后观察扩展图标上是否有显示数字。（如果之前在选项中关闭了网络请求监测，那么请打开那个功能，并重新启动浏览器。）如果有数字显示，说明页面本身可以加载但页面中的资源无法正常加载或者加载缓慢，可能是网络原因。点击弹出菜单中的未加载资源选项可以大致查看哪些资源未能加载，并可以批量添加规则使用代理后再试，一般来说重复几次后即可。

如果要详细地分析网络状况，建议使用 Chrome 开发者工具的 Network 功能，内有详细时间线和延迟等数据，还可以查看具体是哪个请求未能加载。此时可以单独打开此 URL ，并查看扩展图标情况，以判断那个资源是否使用了代理。

**Comment by thelastfantasy** [comment]
![image](https://cloud.githubusercontent.com/assets/6077584/20873144/ad4114c0-badf-11e6-9fef-bb06818cc3fb.png)
![image](https://cloud.githubusercontent.com/assets/6077584/20873204/24400fcc-bae0-11e6-9303-402044efd496.png)
![image](https://cloud.githubusercontent.com/assets/6077584/20873222/502128b0-bae0-11e6-92ce-529f338b953a.png)

能提供的就只有这些了，Network面板下右键点Copy Response也是什么都复制不出来
而且一如之前所说，只要切换到"proxy"使用全局代理的话，页面马上就能刷新出来，所以大概不是网络方面存在问题。

**Comment by celeron533** [comment]
是不是由于没有关闭chrome的预读功能？

**Comment by thelastfantasy** [comment]
![image](https://cloud.githubusercontent.com/assets/6077584/20881020/4db896d2-bb15-11e6-8a62-d8611035ad26.png)
应该不是，装了uBlock Origin的话预读就自动给关闭了

**Comment by FelisCatus** [comment]
这个 Developer Tools 的截图显示的是错误提示页面本身的加载情况，而不是那个实际网址的请求情况……
建议勾掉所有的网络服务功能，然后再尝试一次 DevTools. 这里的诀窍大概是打开新标签页，先开 DevTools ，再输入需要访问的 URL 回车访问。

**Comment by thelastfantasy** [comment]
这有点困难，毕竟不是每次都能遇到问题...

**Comment by FelisCatus** [comment]
所以现在怎么样？还是能遇到这个情况吗？

**Comment by thelastfantasy** [comment]
还是偶尔会遇到

**Comment by gggccc44** [comment]
我也有这问题，全局没问题用自动切换就有问题，很多时候还是google的站最容易出问题，比如chrome.google.com之类，google搜索倒是一般没问题

**Comment by miy4mori** [comment]
我在使用自动切换的时候也会遇到这个问题，估计是规则太多。

**Comment by NIGHT-CORE** [comment]
我也是这个问题，不过我怀疑是dns问题，建议在代理选项里添加dns代理

**Comment by FelisCatus** [comment]
如果说到 DNS 问题的话，会不会是[这个问题](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy#%E4%B8%AD%E6%96%87)？

**Comment by NIGHT-CORE** [comment]
彻底禁用dns缓存后再也没遇到这个问题。

**Comment by FelisCatus** [comment]
于是有什么更新吗？

**Comment by NIGHT-CORE** [comment]
路由器过滤dns后用到现在再也没出过这个问题
可以确定是dns问题了
