### ISSUE TITLE
swithchomeag 与 idm插件兼容性

### ISSUE THREAD

**Issue by kalagxw** [FelisCatus/SwitchyOmega#944]
问题重现：
默认启用PAC模式，使用HTTPS代理
function FindProxyForURL(url, host) {
    return "HTTPS xxxxxx:443";
}
此时在链接上右键 download with idm 为灰色 无法创建下载任务
需先把代理模式切为直连模式再切回pac模式idm才能正常使用
环境为chrome x64 最新版本（上2个版本也有同样问题）。

**Comment by FelisCatus** [comment]
感觉像是 IDM 的问题，那边肯定是判断是否设置代理了，如果设置了就禁用掉了这个菜单项……

此问题与 SwitchyOmega 无关，无法修复。

**Comment by kalagxw** [comment]
问题如果 先是直连 在 设置成pac模式 就是能正常使用的啊

**Comment by FelisCatus** [comment]
我猜想 IDM 那边并不是随时检查的，而是加载页面的时候检查，或者有时候检查有时候不检查之类的……反正没用过，纯猜想……

至少 SwitchyOmega 不会故意去禁用掉 IDM 的菜单项是真的，也没那个权限……具体什么情况不妨去 IDM 问问。
