### ISSUE TITLE
临时添加未加载资源规则

### ISSUE THREAD

**Issue by sswater** [FelisCatus/SwitchyOmega#945]
在 “<n>个资源未加载” 菜单，进入的 “添加条件到情景模式 ↑↓自动切换” 这个小窗口，除了 “添加条件” 按钮，能否再添加一个 “临时添加” 按钮。加入的条件只在本次会话起作用，Chome 关闭后丢弃。以方便在 “隐身模式下” 使用。

**Comment by FelisCatus** [comment]
直接点那个域名的菜单项目（例如“example.com”）弹出菜单即可添加临时规则。不过请注意此设置全局有效，会作用于当前用户的所有窗口，包括隐身窗口和普通窗口。

**Comment by sswater** [comment]
多谢。不过我指的不是对当前地址栏的 URL 添加临时规则，这个我知道。

我浏览某一个页面，这个页面是可以访问的，但页面引用的某些资源位于不同的域名不可访问，通过 “[n]个资源未加载” 进入的界面，对第三方域名添加临时规则。而不是对当前地址栏的 URL 添加临时规则。

**Comment by FelisCatus** [comment]
我明白了。

好像很难做的样子，毕竟那个弹出窗口就那么大，放不下很多选项……而且加了就没办法去掉了，到时候又要被这个坑……

还有不少人都在抱怨弹出窗口卡，如果可以的话我真不想再做功能了……

**Comment by celeron533** [comment]
> 我明白了。
> 
> 好像很难做的样子，毕竟那个弹出窗口就那么大，放不下很多选项……而且加了就没办法去掉了，到时候又要被这个坑……
> 
> 还有不少人都在抱怨弹出窗口卡，如果可以的话我真不想再做功能了……

可惜我不是做前端的，js一窍不通，否则也能来提pull request

**Comment by FelisCatus** [comment]
@celeron533 没关系，已经帮了很多忙了啦～

**Comment by FelisCatus** [comment]
抱歉，这个功能应该是不做了。请谅解。
