### ISSUE TITLE
SwitchyOmega和净网大师插件有冲突

### ISSUE THREAD

**Issue by AKB48kojima** [FelisCatus/SwitchyOmega#946]
装上净网大师插件后SwitchyOmega就不能正常使用了，很多网站都变慢了或者无法打开。

**Comment by celeron533** [comment]
chrome似乎只支持一个扩展来管理代理

**Comment by AKB48kojima** [comment]
净网大师插件是代理的！？？这是栏广告的啊。

**Comment by celeron533** [comment]
广告拦截有时候也会用到类似代理的技术，比如将广告地址扔到一个不存在的代理地址。

**Comment by AKB48kojima** [comment]
怎么解决共存？

**Comment by celeron533** [comment]
这边无法解决。这是chrome的特性之一。

**Comment by FelisCatus** [comment]
感觉大概可以卸载 SwitchyOmega 再重装，这样 SwitchyOmega 的优先级可以提高。

一旦 SwitchyOmega 的优先级为最高，就可以正常使用所有功能。需要去广告时可以在SO菜单中选择“系统代理”模式，将控制权临时还给其他扩展。
