### ISSUE TITLE
多条规则的地址存在包含关系时，被包含的规则无效

### ISSUE THREAD

**Issue by laonader** [FelisCatus/SwitchyOmega#947]
自动切换模式下，如果多条规则的地址存在包含关系，那么被包含的规则无效，不管其配置的规则在前还是在后。
比如：自动切换模式配置规则如下：
UrlRegex: ^http(|s)://www\.google\.com/searchdomaincheck.* +nonet
www.google.com +Shadowsocks
但https://www.google.com/searchdomaincheck这个地址还是会使用Shadowsocks这个模式代理而不会使用nonet模式；如果nonet配置的地址是一个独立的没有配置Shadowsocks模式的规则，则是有效的。
该问题应该是在最近1个月左右开始出现的。

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

**Comment by laonader** [comment]
补充下，地址栏后边的扩展图标哪里，能正确显示使用的是nonet这个代理，但实际上使用的是Shadowsocks这个代理；在之前版本没有这个问题，应该是最新2.3.21版引入的bug

**Comment by FelisCatus** [comment]
见 #899. Chrome 最近加入的“新功能”。

**Comment by laonader** [comment]
通过组策略搞定了，多谢啦。google就是折腾啊，唉
