### ISSUE TITLE
图标建议

### ISSUE THREAD

**Issue by tauyyy** [FelisCatus/SwitchyOmega#949]
Hello，新图标不好看，还是原来的地球图标好看，而且有意义！如果切换到代理，地球旋转并变色就有意思了。

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36

**Comment by FelisCatus** [comment]
原先的图标不支持自定义颜色，默认图标和新色调很不搭配……然后也不支持多颜色显示。

然后 Chrome 不让做无意义的这种旋转动画，如果做了可能会被下架……

另外参见 #107.
