### ISSUE TITLE
不能访问google和youtube

### ISSUE THREAD

**Issue by RunningJS** [FelisCatus/SwitchyOmega#95]
升级omega无法访问google的网站，降级到switchysharp还是不行

SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36

**Comment by FelisCatus** [comment]
我打算关闭这个了，既然没有什么信息，而且“降级到switchysharp还是不行”，那大概就是代理服务器的问题了吧……
