### ISSUE TITLE
此情景模式使用存储空间过多，因此无法进行同步。

### ISSUE THREAD

**Issue by Tomzuo** [FelisCatus/SwitchyOmega#950]
按照[#678](https://github.com/FelisCatus/SwitchyOmega/issues/678)里面的方法进行了分割，把所有我添加的规则都移走了，还是这样提示

![image](https://cloud.githubusercontent.com/assets/12390842/21077908/050461fc-bf96-11e6-8642-06ac6f9e6364.png)

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.75 Safari/537.36

**Comment by FelisCatus** [comment]
目前没有检查占用空间是否会减少，所以移除了也还是会有这个提示。

暂时的解决方法只有把情景模式删掉重新建。
