### ISSUE TITLE
Auto Switch 模式开启后几分钟，系统、浏览器卡死

### ISSUE THREAD

**Issue by tarvos21** [FelisCatus/SwitchyOmega#951]
在 Auto Switch 里设置 gfwlist 用 shadowsocks，几分钟之后整个系统、浏览器卡死，只能硬重启。
用的浏览器是 Chromium 53, Chrome，系统 Ubuntu，Windows 10

我也试过只在列表里设置一两个条目走代理，但是还是会卡死，所以应该不是条目多了的问题。请问大神有什么解决办法？

**Comment by celeron533** [comment]
我更新到chrome55后情况好了很多

**Comment by FelisCatus** [comment]
见 #815, 这锅我不背……

**Comment by tarvos21** [comment]
Windows 更新到 55 之后可以自动模式，Ubuntu 上 55 版的 Chrome/Chromium 还是不能用，可以在 Network中设置自动代理，用 pac 文件。
