### ISSUE TITLE
HTTP works, but HTPPS doesn't

### ISSUE THREAD

**Issue by ankur-goel** [FelisCatus/SwitchyOmega#952]
I am using SwitchyOmega (v2.3.21) to divert select traffic (using URL wildcard) to my local apache server. The HTTP scheme works, but the HTTPS scheme doesn't. Any pointers?
![screen shot 2016-12-15 at 11 32 38 am](https://cloud.githubusercontent.com/assets/8276012/21213458/7a29c838-c2ba-11e6-8777-b8b750c65780.png)
![screen shot 2016-12-15 at 11 33 10 am](https://cloud.githubusercontent.com/assets/8276012/21213462/83396df2-c2ba-11e6-826b-244852f273cb.png)
![screen shot 2016-12-15 at 11 33 32 am](https://cloud.githubusercontent.com/assets/8276012/21213470/8c5129f2-c2ba-11e6-8400-c4dc7212c24e.png)

**Comment by celeron533** [comment]
#845

**Comment by FelisCatus** [comment]
Definitely #845.

**Comment by ankur-goel** [comment]
Thanks @celeron533  and @FelisCatus..!!
