### ISSUE TITLE
Switch proxy based on resolved IP address

### ISSUE THREAD

**Issue by depler** [FelisCatus/SwitchyOmega#953]
There is a computer in local company network with DNS server, so I can access "somehost.local" with IP 192.168.1.28. How can I configure SwitchyOmega to make all requests except local network to go through proxy while network requests will go direct?

I've tried host wildcard with "192.168.1.*" condition and IP literals with "192.168.1.0/24" - both working only if I use IP address instead of DNS name.

**UPDATE.** So far I solved the problem by creating two rules:

1. IP literals "192.168.0.0/16"
2. Host regex "(^((?!\\.).)*$)|(\\.local)"

Second rule is "if hostname not contains dot or ends with .local". Who know how to ignore case for ".local" part?

**Comment by FelisCatus** [comment]
Try putting `192.168.1.0/24` in the bypass list of your proxy profile (not auto switch). If I remember correctly, then Chrome should ignore those hosts that revolves in the network.

Host names should be converted by Chrome to lowercase before it is tested. If not, please let me know.

**Comment by depler** [comment]
@FelisCatus no, that is not working - all DNS-related queries goes through proxy

**Comment by larvata** [comment]
@depler, I have the same issue.
Finally, I added all the *.somehost.local to the hosts file to workaround this.

**Comment by FelisCatus** [comment]
Since SwitchyOmega has no control over DNS, I don't think the issue can be fixed here. You can try using a manually crafted PAC with `dnsResolve` function calls though. Those scripts can also be added in SwitchyOmega via PAC Profiles and then referenced by Switch Profiles.
