### ISSUE TITLE
so many websites can't load such as coursera

### ISSUE THREAD

**Issue by kitianFresh** [FelisCatus/SwitchyOmega#955]
SwitchyOmega 2.3.21
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36

**Comment by celeron533** [comment]
SwitchyOmega只是一个代理服务器切换工具，具体你是用什么代理服务器还是要自己安装、实现。
如果你想翻墙或者加速某些网络的访问，请把这些代理服务器地址填写在SwitchyOmega中并制定相应的使用规则。单单安装SwitchyOmega并不做任何配置是没有用的。

**Comment by kitianFresh** [comment]
我用的是shadowsocks，http://speedmm.com/user/index.php，能上Google，但是自动切换每次都不起作用，很多插件加载不了，连QQ邮箱的很多插件都加载不了，导致不能上传文件，而且使用直接连接也不行。

**Comment by celeron533** [comment]
如果你在国内，直接连接也无法加载QQ邮箱部分内容的话，看上去不太像是SwitchyOmega的问题。有没有试过禁用本扩展或在系统上使用其他浏览器访问

**Comment by kitianFresh** [comment]
是的，火狐可以，chrome不可以。但是我的chrome和Switchy以前用的好好的，我reset settings了，但是好像还是出问题。我在win10 上也用的是同一个chrome账号。win10上就可以

**Comment by celeron533** [comment]
停用switchyomega后还有问题？

**Comment by FelisCatus** [comment]
所以这边怎么样了？遇到这种问题，可以试试看全局代理模式，然后看能不能访问网站。不能的话基本是代理服务器问题。
