### ISSUE TITLE
经常打不来google

### ISSUE THREAD

**Issue by heyiwei** [FelisCatus/SwitchyOmega#956]
SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

**Comment by johnhuo** [comment]
你什么log都不提供，怎么解决问题呢？

**Comment by sndnvaps** [comment]
感觉是 ss设置出问题了吧。。 
或者是ss的 ip被墙了，都有可能。因为什么log也没有提供。

**Comment by FelisCatus** [comment]
见 #957.
