### ISSUE TITLE
访问google基本都是，基本很难打开一次

### ISSUE THREAD

**Issue by heyiwei** [FelisCatus/SwitchyOmega#957]
访问google基本都是，500 Internal Privoxy Error，很难打开一次

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36

**Comment by johnhuo** [comment]
还是什么都没有有价值的信息…不过500猜测是你代理服务器的问题，SO只是一个转发工具，与此问题无关。顺便请把上条issue和此条issue关闭。

**Comment by celeron533** [comment]
`500 Internal Privoxy Error`
我估计你打错了，应该是Proxy
既然你提到了Provixy这个词，那很有可能使用了shadowsocks，有一版本的shadowsocks-windows有这样个问题，升级一下

PS 这个问题和switchyomega没有任何联系，原因如@johnhuo 所述。

**Comment by FelisCatus** [comment]
代理服务器问题，与 SO 无关。
