### ISSUE TITLE
使用SwitchyOmega更新chrome的问题。

### ISSUE THREAD

**Issue by thisisjin** [FelisCatus/SwitchyOmega#958]
貌似通过这个插件来更新chrome有困难。可能是我没有添加相应的规则。
检测chrome新版本时候总是在转圈。 是需要添加一些额外的规则还能通过只用这个插件。不打开shadowsocks的pac代理就能实现chrome更新么

i wanna update my chrome through the "SwitchyOmega/"

but always "cheak the update "   should i have to weite some rules?

**Comment by celeron533** [comment]
Chrome update还是是用系统代理（windows上通过IE设置的代理服务器地址），此时switchyOmega不起作用。
网页访问正常，依旧由switchyOmega托管

**Comment by FelisCatus** [comment]
上次试过，结论是自动更新不受扩展的代理设置控制。也许，可能会使用系统的代理设置吧？
反正不是 SwitchyOmega 这边可以解决的。
