### ISSUE TITLE
SwitchyOmega有没有考虑过增加快速添加功能？

### ISSUE THREAD

**Issue by duckduckcome** [FelisCatus/SwitchyOmega#959]
SwitchyOmega用起来非常流畅，辛苦了！个人以为这个插件已经还有一个小瑕疵，就是快速添加过于麻烦
能否增加一个快速添加的功能？
Firefox下面有两个插件都有这样的功能，可以参考参考。
FoxyProxy：ALT+F2呼出快速添加界面
Autoproxy：点击插件图标--对www.***.com全站启用代理。
个人觉得以上两个插件的快速添加功能非常方便好用。

**Comment by celeron533** [comment]
对我而言，如果第一次访问某个站点添加一次规则后，以后就不用再添加了

**Comment by FelisCatus** [comment]
目前的快捷键是 `Shift+Alt+O`然后'A'，如果确认添加再按回车即可。
