### ISSUE TITLE
自动切换模式可能有内存泄露问题

### ISSUE THREAD

**Issue by dxvgef** [FelisCatus/SwitchyOmega#960]
我每次使用自动加载模式时，chrome的内存占用就不断上升，内存占用达到近2G，指定别的代理模式好像就没这个问题。
![qq 20161229022808](https://cloud.githubusercontent.com/assets/5192264/21528561/71a5185c-cd6e-11e6-97f3-99d666b7e9d3.png)

**Comment by dxvgef** [comment]
刚才看了下之前别人跟我一样的问题，现在尝试把 进程外 V8 代理解析工具 这个选项设为停用，然后再观察问题是否解决

**Comment by FelisCatus** [comment]
好的，如果有什么新发现请在 #815 那边回复。
