### ISSUE TITLE
Auto Proxy need a System Proxy option

### ISSUE THREAD

**Issue by SmartWorm** [FelisCatus/SwitchyOmega#961]
Auto Switch need a [System Proxy] option for default , mostly [direct] is not usefull

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by celeron533** [comment]
Duplicated to #818
