### ISSUE TITLE
Site-specific proxy setting needs a "SwitchyOmega proxy" option

### ISSUE THREAD

**Issue by yaoziyuan** [FelisCatus/SwitchyOmega#962]
When you specify a proxy for a specific website (e.g. github.com), the menu should offer you an option "Use SwitchyOmega's proxy", so that the current SwitchyOmega proxy is used instead of a fixed proxy.

The reason for this suggestion: If you use Freegate and Ultrasurf, you usually have 5 proxy options:

Freegate 8580
Freegate 8581
Ultrasurf 9666
Ultrasurf 9667
Ultrasurf 9668

You often need to switch between these proxies because Freegate and Ultrasurf often jump between them when they're restarted. When you switch ProxyOmega's current proxy, a website's specific proxy also needs to be switched. This is why we need a "Use SwitchyOmega's proxy" option.

**Comment by FelisCatus** [comment]
In that case, it may be helpful to add a new Virtual Profile named `Preferred Proxy` and point that to the current proxy you are using. In Switch Profile, you can then specify all rules to use the `Preferred Proxy` instead of `Freegate 8580`, etc.

The Preferred Proxy can be changed in the popup menu on the extension icon at any time easily.

**Comment by yaoziyuan** [comment]
Too indirect...

I just want an option to remove a site's fixed proxy (so that the site will
use whatever is the current SwitchyOmega proxy).

**Comment by Arlen22** [comment]
@FelisCatus Having an undo button would be very helpful here. I sometimes find I have accidentally selected a site-specific proxy and want to undo the setting. Reinstalling the extension is not an option.

**Comment by yaoziyuan** [comment]
You should simply add a "[Default proxy]" or "[Current proxy]" option below "[Direct connection]" in the site-specific proxy submenu.

**Comment by Arlen22** [comment]
Or call it [Default]. It really cant be very hard. Even a page in settings to list all site-specific selections would be useful, but I'm sure that's harder than just adding an option to the list.
