### ISSUE TITLE
请问在设置http/https代理后DNS的解析还是通过proxy吗??

### ISSUE THREAD

**Issue by yanyan33333** [FelisCatus/SwitchyOmega#963]
我已经读过 [DNS and SOCKS proxy](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy) 
我的理解是在使用socks v5代理的时候 ,关掉chrome的dns预加载dns解析会走socks v5代理,如果用http/https代理后,dns的解析还会走代理吗?还是走系统的dns解析服务呢?
如果走系统的dns解析服务的话,dns应该会被污染了吧?但是我发现用http/https代理还是可以正常访问xxx的,能否解释下~~ 谢谢~

**Comment by celeron533** [comment]
socks5是封装DNS请求的

**Comment by FelisCatus** [comment]
这里问的问题是 HTTP/HTTPS 代理的 DNS 解析如何进行。以下说明与 SwitchyOmega 无关，纯粹基于本人对于网络和代理协议的理解。

对于 HTTP/HTTPS 类型的代理服务器而言，请求的域名会作为 HTTP 协议的一部分直接发往代理服务器，不会在本地进行任何解析操作。也就是说，域名的解析与连接目标服务器，是代理服务器的职责。浏览器本身甚至无须知道最终服务器的 IP 地址。据我所知，此行为无法通过浏览器选项等更改。

也就是说，理论上使用 HTTP/HTTPS 类型的代理服务器时，本地的 DNS 解析、缓存、 hosts 文件等都不使用，与本地设置的 DNS 服务器地址无关。DNS 解析完全在代理服务器上进行。

关于 DNS 污染和特定网络环境问题此处不做解答，但相信 OP 能够从以上说明中推断出具体问题的答案。

**Comment by QuentinChansey** [comment]
请各位指正，所以综合以上大佬们给出的内容，无论使用http还是socks代理，因为域名解析是在代理服务器那边完成的，所以跟本地是否修改DNS，缓存，hosts文件，等等因素都无关。也就是说，如果使用了代理就没必要安装配置DNSCrypt之类的软件对吗？如果是这样，我又产生了一个疑问，比如kknews那样的网站，我即使开了代理也不能上，我粗略了解到可能跟ASN有关，不知道往这个方向想对不对。

**Comment by yfdyh000** [comment]
@QuentinChansey socks代理不是，DNS解析和连接目标服务器（IP地址，而非域名）是两个环节，所以有使用远程代理做DNS解析（并作结果）的选项。而http代理接收的是包含域名的网址，不受本地DNS、hosts影响。

**Comment by mgzhenhong** [comment]
> 请各位指正，所以综合以上大佬们给出的内容，无论使用http还是socks代理，因为域名解析是在代理服务器那边完成的，所以跟本地是否修改DNS，缓存，hosts文件，等等因素都无关。也就是说，如果使用了代理就没必要安装配置DNSCrypt之类的软件对吗？如果是这样，我又产生了一个疑问，比如kknews那样的网站，我即使开了代理也不能上，我粗略了解到可能跟ASN有关，不知道往这个方向想对不对。

简而言之:
1. DNS是基于UDP协议的 
2. socks5代理协议支持TCP和UDP的代理, 所以使用 socks5 代理可以实现远程DNS, 域名解析由socks5代理服务器完成.
3. HTTP和HTTPS 代理协议本身不支持UDP代理, 所以无法实现远程DNS, 使用HTTP/HTTPS代理时, 浏览器使用本地DNS

**Comment by gejun123456** [comment]
@mgzhenhong http代理 只是把http协议的内容通过tcp传到代理服务器，这时候代理服务器可以去走udp查dns，走的是代理服务器本地的dns吧。

**Comment by mgzhenhong** [comment]
> @mgzhenhong http代理 只是把http协议的内容通过tcp传到代理服务器，这时候代理服务器可以去走udp查dns，走的是代理服务器本地的dns吧。

你说的对

**Comment by lishen226** [comment]
做个补充。
我用smartdns在本地电脑做dns服务，dns地址设为127.0.0.1，这样就能看到所有dns请求。
当我使用SwitchyOmega访问google等不存在网站时，在smartdns的日志中能看到解析google的请求，也就是说，即便使用代理，依旧会向dns服务器发送请求，老大哥依旧知道你试图访问哪些网站。
但当我把smartdns关闭后（已无法进行dns解析，不走代理的网站已无法访问），仍能通过代理访问google等网站。
所以，如果想隐蔽dns请求，还要做些额外的操作。

**Comment by QuentinChansey** [comment]
相隔太久没碰网络，大概懂你的意思，就是要么设置dns分流，要么就把dns的这个请求流量加密发送。另外你刚说就算老大哥看到你访问到什么网站，也不能确切知道你访问那个网站的具体什么内容，因为TLS吧。另外我记得再藏得深一点最好用ws而不用tcp。

**Comment by angsheng** [comment]
> 做个补充。 我用smartdns在本地电脑做dns服务，dns地址设为127.0.0.1，这样就能看到所有dns请求。 当我使用SwitchyOmega访问google等不存在网站时，在smartdns的日志中能看到解析google的请求，也就是说，即便使用代理，依旧会向dns服务器发送请求，老大哥依旧知道你试图访问哪些网站。 但当我把smartdns关闭后（已无法进行dns解析，不走代理的网站已无法访问），仍能通过代理访问google等网站。 所以，如果想隐蔽dns请求，还要做些额外的操作。

真的吗？

> 做个补充。 我用smartdns在本地电脑做dns服务，dns地址设为127.0.0.1，这样就能看到所有dns请求。 当我使用SwitchyOmega访问google等不存在网站时，在smartdns的日志中能看到解析google的请求，也就是说，即便使用代理，依旧会向dns服务器发送请求，老大哥依旧知道你试图访问哪些网站。 但当我把smartdns关闭后（已无法进行dns解析，不走代理的网站已无法访问），仍能通过代理访问google等网站。 所以，如果想隐蔽dns请求，还要做些额外的操作。

真的吗？代理了也向本地配置发送请求？？

**Comment by BladeandSoulLyn** [comment]
> > 做个补充。 我用smartdns在本地电脑做dns服务，dns地址设为127.0.0.1，这样就能看到所有dns请求。 当我使用SwitchyOmega访问google等不存在网站时，在smartdns的日志中能看到解析google的请求，也就是说，即便使用代理，依旧会向dns服务器发送请求，老大哥依旧知道你试图访问哪些网站。 但当我把smartdns关闭后（已无法进行dns解析，不走代理的网站已无法访问），仍能通过代理访问google等网站。 所以，如果想隐蔽dns请求，还要做些额外的操作。
> 
> 真的吗？代理了也向本地配置发送请求？？

我也发现了这个问题。我在chrome里用SwitchyOmega开了全局代理后，在自建dns中仍然能看到记录。要想解决这个问题目前暂时只能在浏览器设置里开启安全dns，但是这会导致开标签页的速度变慢。
