### ISSUE TITLE
使用GFWlist作pac代理模式下，Chrome浏览器出现卡死，内存，硬盘使用量100%

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#964]
https://github.com/FelisCatus/SwitchyOmega/issues/815

上面是SwitchOmega 的讨论，发到这里，是为了遇到故障的人可能看到。

我遇到这个问题，删掉GFW list pac模式，故障消失。

**Comment by FelisCatus** [comment]
感谢反馈。
