### ISSUE TITLE
情景模式： proxy 的 不代理的地址列表 中 IP 段格式无效

### ISSUE THREAD

**Issue by hahahahahuo** [FelisCatus/SwitchyOmega#965]
程序版本：Chrome 55.0.2883.87 m (64-bit) / Proxy SwitchyOmega 2.3.21
网络环境：IPv4+IPv6，IPv6 无限量，YouTube 单个下载任务 4M/s，多任务接近满速
本地代理：Shadowsocks-3.4.0，127.0.0.1:1080
目标配置：a) 除非特别指定，能查到 AAAA 记录的域名均直连；b) 学校网域直连；c) 其余需要走 IPv4 的又不是校内的，如无特例统统代理
【下面聊聊操作中发现的不完美】

针对 a)，毕竟现在 IPv6 没普及，主要用在大学和科研院所，没有开关也就不强求了。好在 G 家全球站的好写，有国别的除了 .hk/cn 域，别的不管；YouYube 等专门产品和后台服务类没国别域名好办。mirror6.tuna.tsinghua.edu.cn 下镜像百兆满速，必须不要代理；考虑 edu.cn 内部即使 IPv4 连接也很快就不惜流量了。其他家的需求流量没有那么大就暂且不管，要是能 over the hosts 就方便极了。
再按照https://github.com/lennylxx/ipv6-hosts/tree/master/snippets找规则写好：
`*edu.cn
*google.com
*google.com.hk
*google.com.cn
*googlemashups.com
*appspot.com
*blogger.com
*blogspot.com
*chrome.com
*chromium.org
*googlecode.com
*googledrive.com
*googlelabs.com
*gstatic.com
*gstatic.cn
*googleusercontent.com
*gmodules.com
*ggpht.com
*googleapis.com
*googlehosted.com
*google-analytics.com
*goo.gl
*g.co
*googlezip.net
*android.com
*youtube.com
*youtube-nocookie.com
*youtu.be
*ytimg.com
*gvt0.cn
*gvt0.com
*gvt1.com
*googlevideo.com
*1e100.net`

针对 b)，*edu.cn 规则解决了大部分，但是学校有关通用软件下载的 CDN 网络是 IP 开头的。在 bgp.he.net 查了一下自己学校的网段，用点分十进制附前缀长以忽略，也就是 <ip-literal>/<prefix-length-in-bits>，是不管用的，对 AS 自治域排除应该是大家都可以有的潜在需求吧。

针对 c)，proxy 下不代理白名单正好。

https://github.com/FelisCatus/SwitchyOmega/issues/67 已经琢磨过了，但是对于简单代理，有劳把 IPv6 的 ::/0 和 IPv4 的掩码忽略方式完善一下。

感谢您的付出！

**Comment by FelisCatus** [comment]
SO 没有办法控制 DNS 解析，所以估计 IP 地址的匹配应该就只能做 IP 字面量了吧……读 hosts 也是不可能的吧……
