### ISSUE TITLE
How to configure Auto Switch?

### ISSUE THREAD

**Issue by milteven13** [FelisCatus/SwitchyOmega#966]
Hello, I have 14 profiles (1 proxy for each one), I would like to automatic switch every 1 hour to a different proxy, is that possible? If yes, how can I do that?

Thank you for your attention, have a good day!

![profiles](https://cloud.githubusercontent.com/assets/24919921/21650224/66b8d4f2-d28b-11e6-9fab-38641b15a0ca.png)

**Comment by SeavantUUz** [comment]
Of course it is possible.
You see, the profile infos just stored in your browser's local storage spaces and the method  changes current profile is `applyProfile`. What you should do was just writing a snippet of periodical code to invoke the method. Surely, do not forget to inject the codes into popup page.
But, dude,  you wouldn't follow the solution, aren't you ?
This extension could not do anything we meet and shouldn't neither. I suggest you to try another way to solve it. Like connect with a server to update the pac script every hour.
 I hope my suggestion has a little benefit to you.

**Comment by FelisCatus** [comment]
The closest thing we have right now is the "Current Time" rule in Switch Profiles, which allows different profiles for different hours during the day. This option won't show up unless "Show advanced condition types" is enabled under options page > Interface > Switch Options though. You may need to add 24 rules for `Hour 0~23` if you want to cover the whole day.
