### ISSUE TITLE
建议增加切换条件命中次数统计功能

### ISSUE THREAD

**Issue by TKJohn** [FelisCatus/SwitchyOmega#968]
建议能够统计一个情景模式下，各匹配条件的命中次数，最后使用时间等等

经常碰到不能访问/访问慢的网站，随手就添加一个条件。时间长了情景模式下存了上百个条件，却不知道哪条仍然需要使用。

希望能够提供这项功能，谢谢！

**Comment by FelisCatus** [comment]
由于 PAC 文件并没有办法访问存储或者之类的……所以估计是没办法做了吧……
