### ISSUE TITLE
建议修正【快速切换】下，无法查看哪些网站没有加载的信息

### ISSUE THREAD

**Issue by Justsoos** [FelisCatus/SwitchyOmega#969]
设置到快速切换后，插件图标上出现红色数字，但无法查看，这些无法加载的网站在手动切换下可以查看。

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36

**Comment by FelisCatus** [comment]
见 #328 ，最后有提出一些备选方案，需要您的宝贵建议。
