### ISSUE TITLE
选项显示不全

### ISSUE THREAD

**Issue by mytun** [FelisCatus/SwitchyOmega#970]
选项显示不全，第一个选项被截断了
<img width="377" alt="qq20170108-104446 2x" src="https://cloud.githubusercontent.com/assets/17638002/21746878/8fffcb5c-d58f-11e6-95a7-32541cd1b121.png">
![fe172ebf-a3db-42f3-bad2-c3be31eaf0dd](https://cloud.githubusercontent.com/assets/17638002/21746879/9287922e-d58f-11e6-90b7-134311890f53.png)

SwitchyOmega 2.3.21
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2950.4 Safari/537.36

**Comment by ydq** [comment]
应该是所有版本都有遇到过这个问题，我另外的插件也有遇到过，好像是弹出的这个网页高度如果不固定（根据内容自动撑高），就会有这个问题。

**Comment by celeron533** [comment]
记得以前有人汇报360浏览器可能会有这样的问题。我一直是chrome原生，没有遇到过

**Comment by FelisCatus** [comment]
见 #128 ，常见于 Chrome for OS X，不是 SwitchyOmega 的问题，请向 Chrome 反馈。
