### ISSUE TITLE
情景模式 自动切换 能不能快捷更换代理服务器？

### ISSUE THREAD

**Issue by Remonli** [FelisCatus/SwitchyOmega#971]
举例：
设置3个代理服务器1,2,3
新建自动切换模式1，订阅gfw规则，符合规则的走代理服务器1
新建自动切换模式2，订阅gfw规则，符合规则的走代理服务器2
新建自动切换模式3，订阅gfw规则，符合规则的走代理服务器3
这样子自定义的代理规则要随时保持3个模式一致，才能体验一致，很麻烦。

有没有办法自动切换模式只需要一个，但是可以快捷的更换代理服务器1，2，3？

**Comment by FelisCatus** [comment]
请建立一个虚情景模式，指向任意一个代理服务器。然后只需要一个自动切换模式，需要代理的规则（包括规则列表和自定义规则）都指向那个虚情景模式即可。

之后，虚情景模式的最终目标可以随时在图标的弹出菜单中切换。
