### ISSUE TITLE
Switch on port?

### ISSUE THREAD

**Issue by dain** [FelisCatus/SwitchyOmega#974]
Is it possible to switch based on port in Chromium 52+?

**Comment by FelisCatus** [comment]
Sorry, I don't know. I feel it is still possible via URL wildcard condition, but I haven't tried it myself, so...

I will probably do some experiments with PAC later.

**Comment by FelisCatus** [comment]
Confirmed. Port is still available to PAC scripts.

When visiting `https://example.com:80/test`, the URL `https://example.com:80/` will be provided to PAC scripts. As a result, URL wildcard condition `https://*:80/` works perfectly fine.

Please let me know if you find the description on the options page or the wiki confusing.
