### ISSUE TITLE
chrome disables SwitchyOmega saying your internet is being monitored 

### ISSUE THREAD

**Issue by mardetanha** [FelisCatus/SwitchyOmega#975]
chrome disables SwitchyOmega saying your internet is being monitored and I have to manually enable it via extensions. why this is happening, how could it be stopped ?

**Comment by FelisCatus** [comment]
Well, I can't really stop Chrome from doing this.

SwitchyOmega is indeed monitoring your network traffic to show failed requests on the icon badge. If you don't need the feature, feel free to disable it in Options > General > Network Requests.

The information is only processed temporarily in your browser. It is not uploaded to any one not is it used for commercial purposes. Please check [our privacy policy](https://github.com/FelisCatus/SwitchyOmega/wiki/Privacy) for more details. And more importantly, SwitchyOmega is proudly open source. If you look at the code, you will know that we are not doing you wrong.

**Comment by mardetanha** [comment]
Thanks hopefully this will solve the issue

**Comment by mardetanha** [comment]
sadly it has becoming very bothering, whenever I restart my browser I have to manually enable the extension again. even when I untick network request

**Comment by celeron533** [comment]
I am using win10 x64 en-us with Chrome 56 and installed SwitchyOmega from playstore and haven't met this issue.

**Comment by FelisCatus** [comment]
Please let the Chrome team know they are pretty annoying. There's nothing I can do here.
