### ISSUE TITLE
socks5 没有填写帐号密码的输入框...

### ISSUE THREAD

**Issue by mir3000** [FelisCatus/SwitchyOmega#976]
socks5 没有填写帐号密码的输入框...

SwitchyOmega 2.3.22
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by celeron533** [comment]
Chrome 目前不支持sock5的认证
https://github.com/FelisCatus/SwitchyOmega/issues/178#issuecomment-69450120
