### ISSUE TITLE
请检查浏览器代理设置。

### ISSUE THREAD

**Issue by dlwxn** [FelisCatus/SwitchyOmega#977]
与xx-net配合使用，之前一直是好的，今天xx-net总是提示“请检查浏览器代理设置。” 几种模式都试着切换，也没有用，有该提示的情况下，墙外是可以正常上。

SwitchyOmega 2.3.22
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36

**Comment by wenliyang** [comment]
这是 XX-Net 的问题，请去那个项目的 issue 搜索解决方法

**Comment by FelisCatus** [comment]
不像是 SwitchyOmega 的问题……
