### ISSUE TITLE
最新版在macos的Chrome上的auto switch模式，会CPU占用100%，并导致打不开任何网页。

### ISSUE THREAD

**Issue by libConch** [FelisCatus/SwitchyOmega#978]
应用环境：macos 10.12.3、Chrome 54.0.2840.59 (64-bit)、SwitchyOmega 2.3.22
其他插件：Adblock Plus、Tampermonkey、User-Agent Switcher for Chrome
配置信息：默认的proxy配置项里边添加了一个代理地址；默认的auto switch配置项里边添加了两条匹配规则如下：
        1. 【URL regex】【https?://(\w+.)*google\.(com|\w\w|com\.\w\w)/】【proxy】
        2. 【URL regex】【https?://(\w+.)*(twitter|twimg)\.com/】【proxy】
上边提到的所有系统、软件、插件均为最新版本。

当将SwitchyOmega切换到【auto switch】模式时，突然发现打不开所有网页，chrome一直提示【Resolving proxy...】，且【Google Chrome Helper】进程的CPU占用率接近100%，内存占用倒是正常。

当故障出现时，SwitchyOmega会提示有多个资源获取失败，且在此过程中，Chrome一直提示【Resolving proxy...】。比如在打开【bing.com】的tab上切换到【auto switch】时，会提示为【星号.bing.com】和 【星号.live.com】添加规则。
当故障出现时，偶尔会导致点击工具条的SwitchyOmega按钮时无法弹出菜单，偶尔会导致Tampermonkey的按钮也无法弹出菜单，但Adblock Plus、User-Agent Switcher for Chrome正常。

当故障出现时，可以切换到其他模式如【Direct／System Proxy／Proxy】，都可以恢复正常，但当无法弹出菜单时，就只能关闭Chrome。

///////////////////////////////////////////////////////////

看起来可能是【URL regex】模式的问题，因为如果匹配字符串的内容不变，但模式从【URL regex】切换到【URL wildcard】、【Host wildcard】或者直接Disable的话，都不会出现问题，虽然匹配失效。

**Comment by FelisCatus** [comment]
见 #815， Chrome 的问题，预计 M51 修复。
