### ISSUE TITLE
找不到switchyomega的图标了

### ISSUE THREAD

**Issue by kummar** [FelisCatus/SwitchyOmega#979]
Mac，上午更新了系统，然后switchyomega的logo就不见了，但是在应用商店显示已经添加

**Comment by FelisCatus** [comment]
……这就奇葩了，怎么办呢……

要不要去扩展列表里看看是不是被禁用掉了？

**Comment by FelisCatus** [comment]
所以现在怎么办……再找不到就只能重装啦……

**Comment by opser-gavin** [comment]
楼主这个问题解决了吗？ 我也遇到了，不过我是windows的， 那会一点那个图标，浏览器崩溃，再启来就找不到图标了。

**Comment by kummar** [comment]
> 楼主这个问题解决了吗？ 我也遇到了，不过我是windows的， 那会一点那个图标，浏览器崩溃，再启来就找不到图标了。

@opser-gavin 解决了，但是我忘记是怎么解决的了。。。。。。。。。。
