### ISSUE TITLE
can not open the config page 

### ISSUE THREAD

**Issue by chraac** [FelisCatus/SwitchyOmega#98]
recently i change to SwitchyOmega, then i found that the config page cannot display, but only a blank page:
![proxy_omega](https://cloud.githubusercontent.com/assets/1937740/5536025/1d7afc8a-8ac5-11e4-9c67-ccff90ca97ef.png)

SwitchyOmega 2.2.8
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2166.2 Safari/537.36

**Comment by FelisCatus** [comment]
Closing this issue for now. Please attach the error log if you want to reopen it.

**Comment by zhaoshuguan** [comment]
I also met this issue.Have you resolve it?
