### ISSUE TITLE
gibberish！

### ISSUE THREAD

**Issue by asmosn** [FelisCatus/SwitchyOmega#981]
刚安装时正常，用一段时间后配置界面就出现乱码

SwitchyOmega 2.3.21
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2984.0 Safari/537.36
![qq 20170202165522](https://cloud.githubusercontent.com/assets/9925193/22547683/bac524ac-e97d-11e6-8a3f-287ba6dfe5b7.png)
![qq 20170202171343](https://cloud.githubusercontent.com/assets/9925193/22547688/c11b1898-e97d-11e6-818e-c900392b25ab.png)

**Comment by celeron533** [comment]
参考 #540

**Comment by FelisCatus** [comment]
这个我也关了吧……反正注意杀毒……别的不多说了……
