### ISSUE TITLE
It's unclear if DNS lookups are routed through the proxy?

### ISSUE THREAD

**Issue by geomantik** [FelisCatus/SwitchyOmega#982]
Are DNS lookups routed through the proxy?

**Comment by FelisCatus** [comment]
For HTTP and HTTPS proxy servers, the full URL is always sent to the proxy server where the DNS lookups are performed.

For SOCKS5 proxy, DNS proxies are routed to remote by default by Chromium. There is a [catch with DNS pre-fetch](https://github.com/FelisCatus/SwitchyOmega/wiki/DNS-and-SOCKS-proxy) though.
