### ISSUE TITLE
有人遇到如果启用该拓展 B站 直播就不能看了的情况吗?

### ISSUE THREAD

**Issue by Eri5Ch** [FelisCatus/SwitchyOmega#988]
以前没有遇到这个情况, 最近发现如果开启此拓展, B站就打不开直播(flash播放器), 但是其他视频(html5播放器)是可以正常播放的, 请问应该如何处理呢?

chrome版本:56.0.2924.87 (64-bit)
Proxy SwitchyOmega 2.3.22
win 7 系统

**Comment by FelisCatus** [comment]
我感觉还是因为 Flash 插件对于 PAC 的支持问题，这个问题已经困扰很久了……
至于详细情况等其他人反馈好了。
