### ISSUE TITLE
chrome proxy extension

### ISSUE THREAD

**Issue by zwdzwdzwd** [FelisCatus/SwitchyOmega#989]
hello i am using switchy omega on chrome to swith my proxy ips, when open facebook, it will prompt, sources are failed to load, including facebook, so that i am not able to register new accounts on facebook. can anyone help me out?
am wondering, if failed to load, will browser visit facebook via local address or proxy? anyway to force a proxy visit on facebook in this case?
thanks advance!

**Comment by zwdzwdzwd** [comment]
just tried using switchy omega 's  auto switch, add sources which it failed to load into the auto switch, will this revolve this issue? forcing facebook.com was visited via proxy ip other than local actual ip address?
thanks!

**Comment by celeron533** [comment]
@zwdzwdzwd , There are several pending questions on your side:

1. You are using auto switch rule, have you set the conditions and profiles?
![image](https://cloud.githubusercontent.com/assets/3608762/23004149/0c3111c2-f430-11e6-8535-5519d7638134.png)

2. You also need to test whether your proxy works fine or not. Please try to set the system level proxy then use Internet Explorer (if you are on Windows) to test the connectivity.

**Comment by FelisCatus** [comment]
Closing this. Please re-open if you have more information.
