### ISSUE TITLE
Windows 和 Linux 下使用 SwitchyOmega 导致系统卡死

### ISSUE THREAD

**Issue by bianyifan** [FelisCatus/SwitchyOmega#990]
在 Windows 和 Linux 下均出现此情况
在使用 SwitchyOmega 时（不确定时间），会出现整个桌面环境卡死的现象，后台播放的音乐（网易云音乐）会一直循环一段时间的音乐（大概不到一秒长的音乐一直循环），然后音乐停止播放，桌面环境无响应。等待大约一分半后会恢复，之后会再次发生卡死。在不开启除 Chrome 外的任何程序的情况下依然会卡死。

**Comment by celeron533** [comment]
很有可能是Chrome的V8 javascript的问题  https://github.com/FelisCatus/SwitchyOmega/issues/815#issuecomment-230661502

**Comment by bianyifan** [comment]
之前看到 Issue 815 时候感觉描述跟我的不太一样于是又开了一个 Issue

我的 Chrome 版本信息：
```
Google Chrome	56.0.2924.87 (正式版本) （32 位）
修订版本	0e9a9a6f3676ae439b78cd9b3f62b4193c3ac7d5-refs/branch-heads/2924@{#895}
操作系统	Windows 
JavaScript	V8 5.6.326.50
Flash	24.0.0.154 internal-not-yet-present
用户代理	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
```

这样看来在 Chrome 56 里这个问题还没被修复
那个 issue 里指的 M57 什么时候发布啊？

**Comment by celeron533** [comment]
>那个 issue 里指的 M57 什么时候发布啊？

一般一到两个月发布一个大版本。看样子快了。

![image](https://cloud.githubusercontent.com/assets/3608762/23128482/16a6b61a-f7ba-11e6-8c56-691615eeb105.png)

**Comment by FelisCatus** [comment]
这应该还是 #815, 等修复吧……等不及的话装 Beta 版来试试看？

**Comment by celeron533** [comment]
Chrome 57 released

**Comment by bianyifan** [comment]
谢谢，Chrome 57 中问题已修复。
