### ISSUE TITLE
http://www.ip138.com/?www.google.com 等http地址链接出错

### ISSUE THREAD

**Issue by zhaojiankai** [FelisCatus/SwitchyOmega#992]
使用自动切换模式，图标显示是走代理
使用IE可以正常显示，SS系统代理-pac模式
使用规则https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt ，默认为AutoPoxy
改为Switchy可以显示，但是会导致google,youtube不走代理无法显示

**Comment by FelisCatus** [comment]
应该是规则列表里凡是有`www.google.com`关键字的地址都匹配了，但实际上到达标题所说的那个网站不需要经过某设备。反而可能因为配置的关系，经过代理到达国外再绕回来就加载不出来了。

应该是规则列表问题，请到 gfwlist 那边反馈。
