### ISSUE TITLE
在自动切换模式中增加备注功能

### ISSUE THREAD

**Issue by ZenFX** [FelisCatus/SwitchyOmega#993]
随着使用时间的增加，自动切换模式中的规则越来越多，时间一长，自己都不知道为什么添加过这个网站，能否增加一个备注或注释或分组什么之类的功能，可以写一些注释，方便管理。

**Comment by celeron533** [comment]
理论上可行，但是由于chrome对于扩展的在线同步存储是有限制的，加入注释会加剧这个问题。
> “此情景模式使用存储空间过多，因此无法进行同步” #635

**Comment by FelisCatus** [comment]
……需要考虑一下。主要是界面会变得比较复杂，然后占用空间也是个问题……
