### ISSUE TITLE
更改auto switchy下的“规则列表规则”使用的代理时自动应用到手动添加的网址。同时可以像虚拟情景模式一样增加下拉菜单，用于切换。

### ISSUE THREAD

**Issue by mailsuhua** [FelisCatus/SwitchyOmega#994]
可以像虚拟情景模式一样增加下拉菜单，用于切换。因为使用其它的pac代理时，手动添加的网址还是没办法代理。
研究了下虚拟情景模式，好像实现不了，是我没搞明白吗？

**Comment by FelisCatus** [comment]
虚拟情景模式这边的文档和帮助本来就不是很充分，不是你的问题。

这个例子中，建立一个虚拟情景模式Foo，然后在自动切换中将规则列表规则对应的情景模式设置成 Foo 即可。在下拉菜单中点 Foo 即可随意切换。
