### ISSUE TITLE
#Bug: 自定义规则无法保存

### ISSUE THREAD

**Issue by FindHao** [FelisCatus/SwitchyOmega#999]
保存生效后，**过一定时间，规则会自动失效**，比如我改过hosts了，将google.com设置直连，但是过一段时间，又自动变成了代理模式。

**Comment by celeron533** [comment]
你将规则写在了哪里？
有没有开配置自动同步？

**Comment by myjlpt** [comment]
刷新一次，偶尔可以保存。
还有·就是图标状态永远是蓝色圈圈。不习惯

**Comment by FelisCatus** [comment]
关于临时规则，见 #515，大概。

@myjlpt 请问一下是最近才有这个问题的，还是一直这样？ Chrome 版本是多少？

**Comment by myjlpt** [comment]
最近自动升级到2.4.0出现的。以前都是会变颜色，外圈变化.
临时规则问题对我不天天规则的人而言问题也不大。

**Comment by FelisCatus** [comment]
见 #1003.

**Comment by FindHao** [comment]
@FelisCatus  好吧，原来如此。以前的时候是可以保存的。看来是新设置导致。

**Comment by FelisCatus** [comment]
[v2.4.1](https://github.com/FelisCatus/SwitchyOmega/releases) 已经修复。请互相转告。
